<div id="mail" class="mainState mainStateConnect">
		<div class="postbox-container" id="postbox-container-1">
			<div class="postbox">
			    <div title="Click to toggle" class="handlediv"><br></div>
			    <h3 class="hndle"><span><?php _e('Your mailbox','bidxplugin')?></span></h3>
			    <div class="inside">
			       <div class="well">

		                <div>
		                    <a class="button button-primary button-large button-bidx" href="#connect/compose"><i class="fa fa-edit"></i> <?php _e('Compose','bidxplugin')?></a>
		                </div>
		                <div class="bidx-menuitems">
		                    <div class="bidx-mailFolders">
		                        <!-- menu items will be created by app -->
		                    </div>
		                </div>
		            </div>
			    </div>
			</div>
		</div>
		<div  id="post-body-content">
			<section class="mail postbox">
				 <article class="view viewList">
					<div class="">
						<div class="panel panel-default">
			                <div class="panel-heading">
			                	<h3 class="hndle title titleInbox"><?php _e('Inbox','bidxplugin')?></h3>
			                    <h3 class="hndle title titleSent"><?php _e('Sent','bidxplugin')?></h3>
			                    <h3 class="hndle title titleTrash"><?php _e('Trash','bidxplugin')?></h3>
			                </div>
			                <div class="panel-body inside">
								<form action="">
									<table class="wp-list-table widefat fixed pages">
										<thead>
											<tr>
												<th style="" class="manage-column column-cb check-column" id="cb" scope="col"><input type="checkbox"></th>
												<th style="" class="manage-column" scope="col">Subject</th>
												<th style="" class="manage-column" scope="col">From</th>
												<th style="" class="manage-column" scope="col">Date</th>
											</tr>
										</thead>
										<tfoot>
										<tr>
											<th style="" class="manage-column column-cb check-column" scope="col"><input type="checkbox"></th>
											<th style="" class="manage-column" scope="col">Subject</th>
											<th style="" class="manage-column" scope="col">From</th>

											<th style="" class="manage-column" scope="col">Date</th>
										</tr>
										</tfoot><!-- MESSAGE LIST -->
										<tbody class="list media-list ">
											<tr class="media">
												<th colspan=4> <?php _e('Loading...','bidxplugin')?> </th>
											</tr>

										</tbody>
									</table>
		                        </form>
							</div>
						</div>
					</div>
				</article>
				<article class="view viewRead">
		            <div class="panel panel-default">
		                <div class="panel-heading">
		                	<h3 class="hndle title mail-subject"></h3>
		                </div>
		                <div class="panel-body inside mail-toolbar">
		                    <!-- TOOLBAR -->
		                    <nav class="mail-toolbar bg-primary-dark">
		                        <div class="btn-group">
		                            <a class="btn btn-small btn-primary btn-reply" href="#" data-href="/mail/#mail/%state%/action=reply&id=%id%"><?php _e('Reply','bidxplugin')?></a>
		                            <a class="btn btn-small btn-primary btn-forward" href="#" data-href="/mail/#mail/%state%/action=forward&id=%id%"><?php _e('Forward','bidxplugin')?></a>
		                            <a class="btn btn-small btn-primary bidx-btn-delete1" href="#"><?php _e('Delete','bidxplugin')?></a>
		                            <div class="btn-group btngroup-move-to-folder">
		                                <a class="btn btn-small btn-primary btn-move-to-folder dropdown-toggle bidx-btn-move-to-folder" data-toggle="dropdown" href="#">
		                                    <?php _e('Move message to folder','bidxplugin')?>
		                                    <span class="caret"></span>
		                                </a>
		                                <ul class="dropdown-menu">
		                                    <!-- dropdown menu links -->
		                                </ul>
		                          </div>
		                        </div>
		                    </nav>
		                    <div class="mail-message">
		                        <div class="alert alert-info text-center">
		                            <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
		                                <?php _e('Loading...','bidxplugin')?>
		                            </div>
		                        </div>
		                    </div>

		                    <div id="major-publishing-actions">
							   <div id="delete-action">
							       <a class="submitdelete deletion" href="#connect/discardConfirm">Discard message</a>
							    </div>

							    <div id="publishing-action">
							        <span class="spinner"></span>
							            <a class="button button-primary button-large btn-reply" href="#" data-href="#connect/%state%/action=reply&id=%id%">
							                <?php _e('Reply','bidxplugin')?>
										</a>
							   	</div>
							   	<div id="publishing-action">
							        <span class="spinner"></span>
							            <a class="button button-primary button-large btn-forward" href="#" data-href="#connect/%state%/action=forward&id=%id%">
							                <?php _e('Forward','bidxplugin')?>
										</a>
							   	</div>
							   	<div id="publishing-action">
							        <span class="spinner"></span>
							            <a class="button button-primary button-large bidx-btn-delete" href="#" >
							                <?php _e('Delete','bidxplugin')?>
										</a>
							   	</div>
								<div class="btn-group btngroup-move-to-folder">
									<select class= "chosen-move-tofolder" name="move-to-folder" data-placeholder="<?php _e('Move message to folder','bidxplugin'); ?>">></select>
		                        </div>
								<div class="clear"></div>
							</div>

		                </div>
		            </div>
		        </article>
		        <!-- Compose view -->
		        <article class="view viewCompose">
		            <form action="">
		            <div class="panel panel-default">
		                <div class="panel-heading">
		                    <h3 class="hndle title titleCompose"><?php _e('Create a new e-mail','bidxplugin')?></h3>
		                    <h3 class="hndle title titleReply"><?php _e('Reply to message','bidxplugin')?></h3>
		                    <h3 class="hndle title titleForward"><?php _e('Forward message','bidxplugin')?></h3>
		                </div>
		                <div class="panel-body inside">
		                	<p>
		                        <strong><?php _e('Sender group','bidxplugin'); ?></strong>
		                    </p>
							<select class= "chosen-feedback" name="sendergroup" data-placeholder="<?php _e( 'Select Group', 'bidxplugin' ); ?>">></select>

		                    <p>
		                        <strong><?php _e('Recipient','bidxplugin'); ?></strong>
		                    </p>
		                    <select name="contacts" multiple class="hid chosen-recipient" data-placeholder="<?php _e( 'Select a recipient', 'bidxplugin' ); ?>"></select>
		                    <p>
		                        <strong><?php _e('Subject','bidxplugin'); ?></strong>
		                    </p>
                             <div id="titlediv">
								<div id="titlewrap">
									<input type="text" name="subject" size="30" value="" id="title" autocomplete="off">
								</div>
								</div>


		                    <?php

		                    $args = array("textarea_name" => "content", "editor_class" => "editor_connect",'quicktags' => false);
                            wp_editor(__('Please type your message here','bidxplugin'), "connect_editor_id", $args); ?>

		                    <div id="major-publishing-actions">
							   <div id="delete-action">
							       <a class="submitdelete deletion compose-cancel" href="#connect/discardConfirm">Move to Trash</a>
							    </div>
							    <div id="publishing-action">
							        <span class="spinner"></span>
							            <button type="submit" class="button button-primary button-large compose-submit">
							                <?php _e('Send message','bidxplugin')?>
										</button>
							   	</div>
								<div class="clear"></div>
							</div>

		                </div>
		            </div>
		            </form>
		        </article>
		        <!--  ************************** MODAL VIEWS ****************************************** -->
		        <article class="modalView modalDeleteConfirm" style="display:none">
		            <!-- Modal -->
		            <div class="modal fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		                <div class="modal-dialog">
		                    <div class="modal-content">
		                        <div class="modal-header">
		                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		                            <h3 class="bidx-modalLabel"><?php _e('Delete message(s)','bidxplugin')?></h3>
		                        </div>
		                        <div class="modal-body">
		                        <p>
		                            <?php _e('You are about to delete this/these message(s). Are you sure?','bidxplugin')?>
		                        </p>
		                        </div>
		                        <div class="modal-footer">
		                            <a class="btn" data-dismiss="modal" aria-hidden="true"><?php _e('Close','bidxplugin')?></a>
		                            <a class="btn bidx-btn-confirm" href="#"><?php _e('Delete message(s)','bidxplugin')?></a>
		                        </div>
		                    </div>
		                </div>
		            </div>
		        </article>
		        <article class="modalView modalDiscardConfirm" style="display:none">
		            <!-- Modal -->
		            <div class="modal fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		                <div class="modal-dialog">
		                    <div class="modal-content">
		                        <div class="modal-header">
		                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		                            <h3 class="bidx-modalLabel"><?php _e('Discard message','bidxplugin')?></h3>
		                        </div>
		                        <div class="modal-body">
		                            <p>
		                                <?php _e('You are about to discard this message. Are you sure?','bidxplugin')?>
		                            </p>
		                        </div>

		                        <div class="modal-footer">
		                            <button class="btn" data-dismiss="modal" aria-hidden="true"><?php _e('Cancel','bidxplugin')?></button>
		                            <a class="btn bidx-default-button" href="#" data-href="/mail/#mail/inbox"><?php _e('Discard message')?></a>
		                        </div>
		                    </div>
		                </div>

		            </div>
		        </article>
		        <article class="modalView modalEmptyTrashConfirm" style="display:none">
		            <!-- Modal -->
		            <div class="modal fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		                <div class="modal-dialog">
		                    <div class="modal-content">
		                        <div class="modal-header">
		                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		                            <h3 class="bidx-modalLabel"><?php _e('Delete message','bidxplugin')?></h3>
		                        </div>
		                        <div class="modal-body">
		                        <p>
		                            <?php _e('You are about to empty the trash folder. Are you sure?','bidxplugin')?>
		                        </p>
		                        </div>
		                        <div class="modal-footer">
		                            <a class="btn" data-dismiss="modal" aria-hidden="true"><?php _e('Cancel','bidxplugin')?></a>
		                            <a class="btn bidx-default-button" href="#" data-href="/mail/#mail/%state%/action=doEmptyTrash"><?php _e('Empty trash','bidxplugin')?></a>
		                        </div>
		                    </div>
		                </div>
		            </div>
		        </article>
			</section>
		</div>
</div>
<!-- snippets -->
<script type="text/html" id="mailbox-listitem">
<!--
	<tr class="type-page status-publish hentry alternate iedit author-self level-0">
		<th scope="row" class="check-column">
			<label class="screen-reader-text" for="checkbox-mailboxItem"><span></span></label>
			<input type="checkbox" value="" id="checkbox-mailboxItem" class="mailboxItem" name="mailboxItem" data-toggle="checkbox" data-id="">
			<div class="locked-indicator"></div>
		</th>

		<td class="post-title page-title column-title">
			<strong><a class="row-title" href="%readEmailHref%" title="Edit “Download business plan templates”">%subject%</a></strong>
		</td>

		<td class="author column-author">
			<a href="%readEmailHref%">%senderReceiverName%%emailNew%</a>
		</td>

		<td class="date column-date">
			<abbr title="%dateSent% %timeSent%">%dateSent%</abbr>
		</td>
	</tr>
-->
</script>

<script type="text/html" id="mailbox-listitem-old">
<!--
<li class="media %emailRead%" >
    <div class="pull-left check">
        <div class="checkbox">
            <input type="checkbox" value="" id="checkbox-mailboxItem" class="mailboxItem" name="mailboxItem" data-toggle="checkbox" data-id="" />
            <label for="checkbox-mailboxItem"><span></span></label>
        </div>
    </div>
    <div class="media-body">
        <div class="row">
            <div class="col-sm-9"><h6 class="media-heading"><a href="%readEmailHref%" class="">%senderReceiverName% %emailNew%</a></h6></div>
            <div class="col-sm-3">
                %dateSent%
                <br>
                %timeSent%
            </div>
        </div>
        <div class="subject">
            <span>%subject%</span>
        </div>
    </div>
</li>
-->
</script>

<script type="text/html" id="mailbox-empty">
<!--
<tr class="type-page status-publish hentry alternate iedit author-self level-0">
	<td colspan=4 class="post-title page-title column-title">
		<?php _e('No messages available','bidxplugin')?>
	</td>
</tr>
-->
</script>

<script type="text/html" id="toast-snippet">
<!--
    <div class='alert alert-success hide'>
        <button data-dismiss='alert' class='close fa fa-times' type='button'></button>
        <span class="messageContent"></span>
    </div>
-->
</script>