<div id="mail" class="mainState mainStateConnect">
		<div class="postbox-container mailbox-links" id="postbox-container-1">
			<div class="postbox">
			    <div title="Click to toggle" class="handlediv"><br></div>
			    <h3 class="hndle"><span><?php _e('Your mailbox','bidxplugin')?></span></h3>
			    <div class="inside">
			       <div class="well">

		                <div>
		                    <a class="button button-primary button-large button-bidx" href="#connect/compose"><i class="fa fa-edit"></i> <?php _e('Compose','bidxplugin')?></a>
		                </div>
		                <div class="bidx-menuitems">
		                    <div class="bidx-mailFolders">
		                        <!-- menu items will be created by app -->
		                    </div>
		                </div>
		            </div>
			    </div>
			</div>
		</div>
		<div  id="post-body-content">
			<section class="mail ">
				<!-- ************************* utility views *********************************** -->
                <div class="view viewLoad alert alert-info text-center">
                    <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e('Loading...','bidxplugin')?>
                </div>


				<article class="tablenav top viewAction">
				    <div class="alignleft actions bulkactions viewBulk" style="display:none;">
				        <select name="action" class="bulk-dropdown-menu">
				            <option value="-1" selected="selected">Bulk Actions</option>
				            <option value="read" class="btn bidx-btn-mark-read hide-if-no-js">Mark as read</option>
				            <option value="unread" class="btn bidx-btn-mark-unread hide-if-no-js">Mark as unread</option>
				            <option value="delete" class="btn bidx-btn-delete hide-if-no-js">Delete</option>
				            <option value="undelete" class="btn bidx-btn-undelete hide-if-no-js">Undelete</option>
				            <option value="trash" class="btn bidx-btn-empty-trash-confirm" data-confirm="true">Empty Trash</option>
				        </select>
				        <input disabled = "disabled" type="submit" name="applyBulk" class="button action applyBulk" value="Apply">
				    </div>

				    <div class="alignleft actions btngroup-move-to-folder viewMovetofolder" style="display:none;">
				        <select name="action" class="dropdown-menu">
				            <option value="-1" selected="selected">Move message to</option>
				        </select>
				        <input disabled = "disabled" type="submit" name="applyMove" class="button action applyMove" value="Apply">
				    </div>
				    <div class="tablenav-pages"><span class="displaying-num"></span>
						<span class="pagination-links">
							<a class="prev-page bidx-btn-mail-prev" style="display:none;" title="Go to the previous page" href="#">‹ Newer</a>
							<a class="next-page bidx-btn-mail-next" title="Go to the next page" href="#">Older ›</a>
						</span>
					</div>
				</article>

				 <article class="view viewList">
					<div class="postbox">
						<div class="panel panel-default">
			                <div class="panel-heading">
			                	<h3 class="hndle title titleInbox"><?php _e('Inbox','bidxplugin')?></h3>
			                    <h3 class="hndle title titleSent"><?php _e('Sent','bidxplugin')?></h3>
			                    <h3 class="hndle title titleTrash"><?php _e('Trash','bidxplugin')?></h3>
			                    <h3 class="hndle title titleCustom"></h3>
			                    </div>
			                <div class="panel-body inside">
								<form action="">
									<table class="wp-list-table widefat fixed pages">
										<thead>
											<tr>
												<th style="" class="manage-column column-cb check-column" id="cb" scope="col">
													<input type="checkbox" data-toggle="checkbox" class="messagesCheckall" value="">
												</th>
												<th style="" class="manage-column" scope="col">Subject</th>
												<!-- Will be replaced with To for Sent, or both From/To for Trash and other folders -->
												<th style="" class="manage-column email-from-to" scope="col">From</th>
												<th style="" class="manage-column" scope="col">Date</th>
											</tr>
										</thead>
										<tfoot>
										<tr>
											<th style="" class="manage-column column-cb check-column" scope="col">
												<input type="checkbox" data-toggle="checkbox" class="messagesCheckall" value="">
											</th>
											<th style="" class="manage-column" scope="col">Subject</th>
											<th style="" class="manage-column email-from-to" scope="col">From</th>

											<th style="" class="manage-column" scope="col">Date</th>
										</tr>
										</tfoot><!-- MESSAGE LIST -->
										<tbody class="list media-list ">
											<tr class="media">
												<th colspan=4> <?php _e('Loading...','bidxplugin')?> </th>
											</tr>

										</tbody>
									</table>
		                        </form>
							</div>
						</div>
					</div>
				</article>
				<article class="view viewRead">
					<div class="postbox">
			            <div class="panel panel-default">
			                <div class="panel-heading">
			                	<h3 class="hndle title mail-subject"></h3>
			                </div>
			                <div class="panel-body inside mail-toolbar">
			                    <div class="mail-message">
			                        <div class="alert alert-info text-center">
			                            <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
			                                <?php _e('Loading...','bidxplugin')?>
			                            </div>
			                        </div>
			                    </div>

			                    <div id="major-publishing-actions">
								    <div class="publishing-action">
								        <span class="spinner"></span>
								            <a class="button button-primary button-large btn-reply" href="#" data-href="#connect/%state%/action=reply&id=%id%">
								                <?php _e('Reply','bidxplugin')?>
											</a>
								   	</div>
								   	<div class="publishing-action">
								        <span class="spinner"></span>
								            <a class="button button-primary button-large btn-forward" href="#" data-href="#connect/%state%/action=forward&id=%id%">
								                <?php _e('Forward','bidxplugin')?>
											</a>
								   	</div>
								   	<div class="publishing-action">
								        <span class="spinner"></span>
								            <a class="button button-primary button-large btn-delete" href="#" >
								                <?php _e('Delete','bidxplugin')?>
											</a>
								   	</div>
								   	<div class="publishing-action">
								        <span class="spinner"></span>
								            <a class="button button-primary button-large btn-undelete" href="#" >
								                <?php _e('Undelete','bidxplugin')?>
											</a>
								   	</div>
									<div class="clear"></div>
								</div>

			                </div>
			            </div>
		        	</div>
		        </article>
		        <!-- Compose view -->
		        <article class="view viewCompose">
		            <form id="frmComposeEdit">
		            <div class="panel panel-default">
		                <div class="panel-heading">
		                    <h3 class="hndle title titleCompose"><?php _e('Create a new e-mail','bidxplugin')?></h3>
		                    <h3 class="hndle title titleReply"><?php _e('Reply to message','bidxplugin')?></h3>
		                    <h3 class="hndle title titleForward"><?php _e('Forward message','bidxplugin')?></h3>
		                </div>
		                <div class="panel-body inside">
		                	<p>
		                        <strong><?php _e('Sender group','bidxplugin'); ?></strong>
		                    </p>
							<select class= "chosen-feedback" name="sendergroup" data-placeholder="<?php _e( 'Select Group', 'bidxplugin' ); ?>">></select>
							<div class="form-group">
			                    <p>
			                        <strong><?php _e('Recipient','bidxplugin'); ?></strong>
			                    </p>
			                    <select name="contacts" multiple class="hide chosen-recipient" data-placeholder="<?php _e( 'Select a recipient', 'bidxplugin' ); ?>"></select>
		                	</div>
		                	<div class="form-group">
			                    <p>
			                        <strong><?php _e('Subject','bidxplugin'); ?></strong>
			                    </p>
	                            <div id="titlediv">
									<div id="titlewrap">
										<input type="text" name="subject" size="30" value="" id="title" autocomplete="off">
									</div>
								</div>
							</div>
	                        <div class="form-group tinymce-wrapper">
	                        	<p>
			                        <strong><?php _e('Message','bidxplugin'); ?></strong>
			                    </p>
		                    <?php
								$args = array(	'textarea_name' => 'connectBody'
										, 		'editor_class' 	=> 'editor_connect'
										,		'quicktags' 	=> false
										,       'tinymce'       => false
										,       'media_buttons' => false
										);
                            	wp_editor('', "connectBody", $args);
                            ?>
							</div>
		                    <div id="major-publishing-actions">
							   <div id="delete-action">
							       <a class="submitdelete deletion compose-cancel" href="#connect/discardConfirm"><?php _e('Discard message','bidxplugin');?></a>
							    </div>
							    <div class="publishing-action">
							        <span class="spinner"></span>
							            <button type="submit" class="button button-primary button-large compose-submit">
							                <?php _e('Send message','bidxplugin')?>
										</button>
							   	</div>
								<div class="clear"></div>
							</div>

		                </div>
		            </div>
		            </form>
		        </article>
		        <!--  ************************** MODAL VIEWS ****************************************** -->
		        <article class="modalView modalDeleteConfirm" style="display:none">
		            <!-- Modal -->
		            <div class="modal fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		                <div class="modal-dialog">
		                    <div class="modal-content">
		                        <div class="modal-header">
		                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		                            <h3 class="bidx-modalLabel"><?php _e('Delete message(s)','bidxplugin')?></h3>
		                        </div>
		                        <div class="modal-body">
		                        <p>
		                            <?php _e('You are about to delete this/these message(s). Are you sure?','bidxplugin')?>
		                        </p>
		                        </div>
		                        <div class="modal-footer">
		                            <a class="btn" data-dismiss="modal" aria-hidden="true"><?php _e('Close','bidxplugin')?></a>
		                            <a class="btn bidx-btn-confirm" href="#"><?php _e('Delete message(s)','bidxplugin')?></a>
		                        </div>
		                    </div>
		                </div>
		            </div>
		        </article>
		        <article class="modalView modalDiscardConfirm" style="display:none">
		            <!-- Modal -->
		            <div class="modal fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		                <div class="modal-dialog">
		                    <div class="modal-content">
		                        <div class="modal-header">
		                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		                            <h3 class="bidx-modalLabel"><?php _e('Discard message','bidxplugin')?></h3>
		                        </div>
		                        <div class="modal-body">
		                            <p>
		                                <?php _e('You are about to discard this message. Are you sure?','bidxplugin')?>
		                            </p>
		                        </div>

		                        <div class="modal-footer">
		                            <button class="btn" data-dismiss="modal" aria-hidden="true"><?php _e('Cancel','bidxplugin')?></button>
		                            <a class="btn bidx-default-button" href="#" data-href="/mail/#mail/inbox"><?php _e('Discard message')?></a>
		                        </div>
		                    </div>
		                </div>

		            </div>
		        </article>
		        <article class="modalView modalEmptyTrashConfirm" style="display:none">
		            <!-- Modal -->
		            <div class="modal fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		                <div class="modal-dialog">
		                    <div class="modal-content">
		                        <div class="modal-header">
		                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
		                            <h3 class="bidx-modalLabel"><?php _e('Delete message','bidxplugin')?></h3>
		                        </div>
		                        <div class="modal-body">
		                        <p>
		                            <?php _e('You are about to empty the trash folder. Are you sure?','bidxplugin')?>
		                        </p>
		                        </div>
		                        <div class="modal-footer">
		                            <a class="btn" data-dismiss="modal" aria-hidden="true"><?php _e('Cancel','bidxplugin')?></a>
		                            <a class="btn bidx-default-button" href="#" data-href="/mail/#mail/%state%/action=doEmptyTrash"><?php _e('Empty trash','bidxplugin')?></a>
		                        </div>
		                    </div>
		                </div>
		            </div>
		        </article>
			</section>
		</div>
</div>
<!-- snippets -->
<script type="text/html" id="mailbox-listitem">
<!--
	<tr class="type-page status-publish hentry alternate iedit author-self level-0">
		<th scope="row" class="check-column">
			<label class="screen-reader-text" for="checkbox-mailboxItem"><span></span></label>
			<input type="checkbox" value="" id="checkbox-mailboxItem" class="mailboxItem" name="mailboxItem" data-toggle="checkbox" data-id="">
			<div class="locked-indicator"></div>
		</th>

		<td class="post-title page-title column-title">
			<a class="row-title %emailRead%" href="%readEmailHref%">%subject%</a>
		</td>

		<td class="author column-author">
			<a href="%readEmailHref%">%senderReceiverName%%emailNew%</a>
		</td>

		<td class="date column-date">
			<abbr title="%dateSent% %timeSent%">%dateSent%</abbr>
		</td>
	</tr>
-->
</script>

<script type="text/html" id="mailbox-empty">
<!--
<tr class="type-page status-publish hentry alternate iedit author-self level-0">
	<td colspan=4 class="post-title page-title column-title">
		<?php _e('No messages available','bidxplugin')?>
	</td>
</tr>
-->
</script>

<script type="text/html" id="toast-snippet">
<!--
    <div class='alert alert-success hide'>
        <button data-dismiss='alert' class='close fa fa-times' type='button'></button>
        <span class="messageContent"></span>
    </div>
-->
</script>
