<div class="searchcontrol">
	<div class="filterMonitoring">
	    <?php _e('From date','bidxplugin');?>
	    <input type="text" class="monitoring-date" name="from_date" value=""/>
	    <?php _e('To date','bidxplugin');?>
	    <input type="text" class="monitoring-date" name="to_date" value=""/>
	    <input type="submit" name="" id="monitoring-submit" class="button button-primary button-large" value="Submit">
	</div>
</div>