
<div class='summary' id='role_pie_chart'>

</div>
<div class="view viewApprox" style="display:none;">
   <?php _e ('Incase of multiple profile (Ex Entrpreneur & Mentor) for same user, number may be slightly different.', 'bidxplugin') ?>
</div>
<div class="view viewLoaduserrolepiechart alert alert-info text-center">
    <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e ('Loading user roles...', 'bidxplugin') ?>
</div>
<div class="view viewPieChartError alert alert-warning">
   <p class="errorMsg"></p>
</div>