
<div class='summary' id='role_pie_chart'>

</div>
<div class="view viewApprox" style="display:none;">
   <?php _e ('In case of multiple profiles (eg. Entrepreneur & Mentor) for the same user, numbers may be slightly different.', 'bidxplugin') ?>
</div>
<div class="view viewLoaduserrolepiechart alert alert-info text-center">
    <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e ('Loading user roles...', 'bidxplugin') ?>
</div>
<div class="view viewPieChartError alert alert-warning">
   <p class="errorMsg"></p>
</div>