<!--
    All mainstates begin with display none so that you don't see a quick state changes on the screen
-->


    <!--
        this is the default state
    -->
    <div id="setpassword" class="block-odd mainState mainStateShow" style="display:none;">

        <div class="row">
            <div class="col-sm-6 col-sm-offset-3 well">
                <form id="frmCredentials" action="/">
                    <h1><?php _e('Set your password','bidxplugin');?></h1>
                    <p>
                        <?php _e('Here you can set your new password for logging on to the platform. After you save your password you can enter your group pages.', 'bidxplugin')?>
                    </p>


                    <div class="form-group">
                        <label><?php _e('New password','bidxplugin');?></label>
                        <input type="password" class="form-control" name="newPassword" placeholder="<?php _e('Enter your new password','bidxplugin');?>" />
                    </div>

                    <div class="form-group">
                        <label><?php _e('Repeat new password','bidxplugin');?></label>
                        <input type="password" class="form-control" name="newPasswordRepeat" placeholder="<?php _e('Repeat your new password','bidxplugin');?>" />
                    </div>

                    <button type="submit" class="btn btn-primary"><span class="fa fa-save"></span> <?php _e('Save','bidxplugin');?></button>

                </form>

            </div>
        </div>
    </div>

    <!--
        this state is used to provide feedback after an action on password set or on errors
    -->
    <div id="feedback" class="mainState mainStateFeedback" style="display:none;">

        <div class="row">
            <div class="col-sm-6 col-sm-offset-3 well">
                <section>


                    <article class="view viewLoading "><?php _e('Loading...','bidxplugin')?> </article>

                    <article class="view viewError ">

                       <div class="alert alert-warning">
                           <h1><?php _e('Error','bidxplugin')?></h1>
                           <div class="errorMsg"></div>
                           <p>
                               <a href="/setpassword">Try again</a>
                           </p>
                       </div>

                   </article>

                    <article class="view viewExpired ">
                       <div class="alert alert-warning">
                           <h1><?php _e('Activation token has expired','bidxplugin')?></h1>
                           <div class="errorMsg"></div>
                           <p>
                               <?php _e('Your activation token has expired. You cannot use this account until it has been removed so that you can register again.', 'bidxplugin')?>
                           </p>
                       </div>
                   </article>


                    <article class="view viewDone ">

                        <h1><?php _e('Your password has been set','bidxplugin');?></h1>

                        <p>
                            <?php _e('You have succesfully set your new password. Click on the link below to go to grouphomage ', 'bidxplugin')?>
                        </p>
                        <p>
                            <a href="/"><?php _e('Go to group homepage', 'bidxplugin')?></a>
                        </p>

                    </article>

                </section>
            </div>
        </div>
    </div>

