
<div class="wrap">
    <article>
        <h2>Competition</h2>
        <h4>
            The bidx competition tool is a service for corporates, financiers, SME service providers and other

            organizations that want to identify Small and Medium Enterprises in emerging markets and build a

            pipeline of investment opportunities.
        </h4>

        <div class="manage-menus">
            We can proudly claim to be a global leader in organizing business plan competitions for emerging

            market entrepreneurs, undertaking the first international BiD Challenge for developing countries, as well

            as the first competition for women entrepreneurs and over 80 other competitions with partners since

            2005.

            The bidx competition program is a proven method to:
            <ul>
                <li> Get exposure or start CSR and employee engagement programs

                <li>Identify and support entrepreneurs in emerging markets

                <li>Establish a pipeline of investment or business opportunities for organizations and corporations

                <li>Raise awareness and accelerate your goals.
            </ul>
            Are you interested in organizing a competition, or would you like to have more detailed information?

            We kindly ask you to send an email to <a href= "mailto:info@bidx.net" >info@bidx.net</a>, we will respond within 48 hours.        </div>
    </article>
    <br>
</div>