
<div class="wrap">
    <article>
        <h2>Competition</h2>
        <h4>
            A competition is a perfect way to identify promising entrepreneurs, expose them internationally, and connect them with potential financiers.
        </h4>

        <div class="manage-menus">
            Matchmaking with financiers
            Once your business plan has a high score and is presentable to financiers (investors, funds and banks) we will alert the most relevant financiers about your business.

            Useful documents and links
            Many useful documents and links to write your business plan and grow your business can be found under the Resources section in the header menu.

            Build your network
            Use the powerful search function of this website to find like-minded entrepreneurs. Contact them via the internal messaging system. Also find similar business plans, investment funds, news and events.

            Get started and join bidx.net
            The bidX is a worldwide online community of over 46,000 members, entrepreneurs, coaches, financiers and partner organizations. Use it!
        </div>
    </article>
    <br>
</div>