<!--
    Search startpage.
    Single page application that is setup
-->

<div id="group-dashboard">
    <div class="row">
        <div class="col-sm-8">
            <h2>Group growth</h2>
        </div>

    </div>
    <div class="row">
        <div class="col-sm-6">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Members and business</th>
                        <th>Amount</th>
                        <!-- <th>Lastaddition</th> -->
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Members</td>
                        <td><?php echo $this->data->memberProfileCount; ?></td>
                    </tr>
                    <tr>
                        <td>Entrepreneurs</td>
                        <td><?php echo $this->data->entrepreneurCount; ?></td>
                    </tr>
                    <tr>
                        <td>Investors</td>
                        <td><?php echo $this->data->investorCount; ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <section class="col-sm-12 well dashboard">
            <!-- ************************* utility views *********************************** -->
            <article class="view viewLoad"><?php _e ('Loading...', 'bidxplugin') ?></article>

            <article class="view viewList">
                <div class="row">
                     <div class="col-sm-6">
                        <h2>Members who recently joined</h2>
                    </div>
                    <div class="col-sm-6">
                            <form class="form-search" action="/search" method="GET">
                                <div class="input-append">
                                    <input type="text" class="search-query search-query-rounded" name="q" placeholder="Search" value="<?php echo isset ($_REQUEST['q']) ? $_REQUEST['q'] : ''; ?>">
                                    <button type="submit" class="btn"><span class="fui-search"></span></button>
                                </div>
                            </form>

                    </div>
                    <div class="col-sm-12">
                        These members are new in your group. Select and send a welcome message.
                    </div>

                    <!-- Latest member data -->
                    <div class="col-sm-12 latest-member">
                        <ul class="listheader ">
                            <li class="mediaheader" >
                                <div class="row">
                                    <div class="col-sm-2 pull-left check">
                                        <label class="checkbox">
                                            <input type="checkbox" data-toggle="checkbox" class="messagesCheckall" value="">
                                        </label>
                                    </div>
                                    <div class="col-sm-10 headerbody">
                                        <div class="row">
                                            <div class="col-sm-4"><strong><span class="placeholder user"><?php _e ('First + Last name', 'bidxplugin') ?></span></strong></div>
                                            <div class="col-sm-2"><strong><span class="placeholder userId"/><?php _e ('Location', 'bidxplugin') ?></span></strong></div>
                                            <div class="col-sm-2"><strong><span class="placeholder membersince"/><?php _e ('Member since', 'bidxplugin') ?></span></strong></div>
                                            <div class="col-sm-2"><strong><span class="placeholder role"/><?php _e ('Role', 'bidxplugin') ?></span></strong></div>
                                            <div class="col-sm-2"><strong><span class="placeholder lastlogin"/><?php _e ('Last Login', 'bidxplugin') ?></span></strong></div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>

                        <!-- MESSAGE LIST -->
                        <ul class="list media-list ">
                            <li class="media">
                                <div class="pull-left check"></div>
                                <div class="pull-left">
                                    <?php _e ('Loading...', 'bidxplugin') ?>
                                </div>
                            </li>

                        </ul>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4 offset8">
                        <a class="btn btn-primary" href="#dashboard/dashboardCompose">Compose welcome message</a>
                    </div>
                </div>
            </article>

            <article class="view viewGoat"><?php _e ('Loading...', 'bidxplugin') ?></article>
            <article class="view viewAll">
                <div class="row">
                    <div class="col-sm-6">
                        <h2>All the members</h2>
                    </div>

                    <div class="col-sm-12">
                        See here all the members in your group with their login data, location and role. Select those you want to  send a message to.
                    </div>


                    <!-- All member data -->
                    <div class="col-sm-12 latest-member">
                        <ul class="listheader ">
                            <li class="mediaheader" >
                                <div class="row">
                                    <div class="col-sm-2 pull-left check">
                                        <label class="checkbox">
                                            <input type="checkbox" data-toggle="checkbox" class="messagesCheckall" value="">
                                        </label>
                                    </div>
                                    <div class="col-sm-10 headerbody">
                                        <div class="row">
                                            <div class="col-sm-4"><strong><span class="placeholder user"><?php _e ('First + Last name', 'bidxplugin') ?></span></strong></div>
                                            <div class="col-sm-2"><strong><span class="placeholder userId"/><?php _e ('Location', 'bidxplugin') ?></span></strong></div>
                                            <div class="col-sm-2"><strong><span class="placeholder membersince"/><?php _e ('Member since', 'bidxplugin') ?></span></strong></div>
                                            <div class="col-sm-2"><strong><span class="placeholder role"/><?php _e ('Role', 'bidxplugin') ?></span></strong></div>
                                            <div class="col-sm-2"><strong><span class="placeholder lastlogin"/><?php _e ('Last Login', 'bidxplugin') ?></span></strong></div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>

                        <!-- MESSAGE LIST -->
                        <ul class="all media-list ">
                            <li class="media">
                                <div class="pull-left check"></div>
                                <div class="pull-left">
                                    <?php _e ('Loading...', 'bidxplugin') ?>
                                </div>
                            </li>

                        </ul>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4 offset8">
                        <a class="btn btn-primary" href="#dashboard/dashboardComposeAll">Compose message</a>
                    </div>
                </div>
            </article>

            <article class="modalView modalDashboardCompose">
                <form action="">
                    <div  id="dashboard" class="mainState mainStateDashboard">                <!-- Modal -->
                        <div class="modal hide fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                <h3 id="myModalLabel"><?php _e ('Delete message', 'bidxplugin') ?></h3>
                            </div>
                            <div class="modal-body">
                                <form action="">
                                    <div class="row">
                                        <div class="control-group">
                                            <div class="input-prepend">

                                                <span class="add-on">Recipients</span>
                                                <div class="controls">
                                                    <div class="bidx-tagsinput-container">
                                                        <input type="text" autocomplete="off" name="contacts" class="bidx-tagsinput enclosed defer"  data-bidxdatakey="members" placeholder="<?php _e ('Add Recipient') ?>">
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="control-group">
                                            <div class="input-prepend">

                                                <span class="add-on">Subject</span>
                                                <div class="controls">
                                                    <input type="text" name="subject" placeholder="<?php _e ('Your subject goes here', 'bidxplugin') ?>" >
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="control-group">
                                            <div class="controls">
                                                <textarea name="content" placeholder="<?php _e ('Please type your message here', 'bidxplugin') ?>" value=""></textarea>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="pull-left">

                                    </div>
                                </form>
                            </div>
                            <div class="modal-footer">
                                <a href="#dashboard/discardConfirm" class="btn compose-cancel"><?php _e ('Discard message') ?></a>
                                <button type="submit" class="btn btn-primary compose-submit"><?php _e ('Send message', 'bidxplugin') ?></button>

                            </div>
                        </div>
                    </div>
                </form>
            </article>
            <article class="modalView modalDiscardConfirm">
                <!-- Modal -->
                <div class="modal hide fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h3 id="myModalLabel"><?php _e ('Discard message') ?></h3>
                    </div>
                    <div class="modal-body">
                        <p>
                            <?php _e ('You are about to discard this message. Are you sure?') ?>
                        </p>
                    </div>

                    <div class="modal-footer">
                        <a class="btn" href="#dashboard/dashboardCompose"><?php _e ('Cancel') ?></a>
                        <a class="btn btn-primary" data-dismiss="modal" aria-hidden="true"><?php _e ('Discard message') ?></a>
                    </div>

                </div>
            </article>
        </section>
    </div>
</div>
<script type="text/html" id="dashboard-listitem">
    <!--
    <li class="media" >
    <div class="row">
    <div class="col-sm-2 pull-left check">
    <label class="checkbox">
    <input type="checkbox" data-toggle="checkbox"  value="" data-id="">
    </label>
    </div>
    <div class="col-sm-10 media-body">
    <div class="row">
    <div class="col-sm-4"><h6 class="media-heading"><span class="placeholder user"><?php _e ('SENDER UNKNOWN IN API', 'bidxplugin') ?></span></h6></div>
    <div class="col-sm-2"><span class="placeholder location"/></div>
    <div class="col-sm-2"><span class="placeholder membersince"/></div>
    <div class="col-sm-2"><span class="placeholder role"/></div>
    <div class="col-sm-2"><span class="placeholder lastlogin"/></div>
    </div>
    <div class="subject">
    <span class="placeholder subject"/>
    </div>
    </div>
    </li>
    -->
</script>

<script type="text/html" id="dashboard-empty">
    <!--
    <li class="media">
    <div class="pull-left check"></div>
    <div class="">
    <?php _e ('No messages available') ?>
    </div>
    </li>
    -->
</script>
