<div id='icon-edit' class='icon32 icon32-posts-post'><br></div>
<h2><?php _e('bidX General Settings','bidxplugin');?></h2>

<form method='post'>
    <div class='metabox-holder'>
        <div id='categorydiv' class='postbox'>
            <div class='handlediv' title='Click to toggle'><br></div><h3 class='hndle'><span><?php _e('Express form','bidxplugin');?></span></h3>
            <div class='inside'>
                <div id='taxonomy-category' class='categorydiv'>
                    <div class=''>
                        <div>                       
                        <?php 
                            if( isset($this->expressform))
                            {
                                $checkedFb      = '';
                                $checkedBidx    = '';
                                $checkedDefault = '';
                                switch ( $this->expressform )
                                {
                                    case 'fb':
                                        $checkedFb      = 'checked';
                                    break;

                                    case 'bidx':
                                        $checkedBidx    = 'checked';
                                    break;
                                    default:
                                        $checkedDefault = 'checked';
                                }
                            }
                        ?>
                        <label class="radio">
                            <input type="radio" data-toggle="radio" <?php echo $checkedDefault;?> name="bidx-expressform" value="false" ><?php _e('Disable','bidxplugin'); ?>
                        </label>
                        <label class="radio">
                            <input type="radio" data-toggle="radio" <?php echo $checkedFb;?> name="bidx-expressform"  value="fb"><?php _e('Via facebook','bidxplugin'); ?>
                        </label>
                        <label class="radio">
                            <input type="radio" data-toggle="radio" <?php echo $checkedBidx;?> name="bidx-expressform" value="bidx"><?php _e('Via bidx','bidxplugin'); ?>
                        </label>
                    </div>
                        <div class='label'>
                            <label class='selectit' for='bidx-express-custom'>
                                <span class="description"><?php _e('Please enter wizehive slug ','bidxplugin');?></span><br/>
                                <input <?php if( isset( $this->expressCustom ) ) { echo 'value="'.$this->expressCustom.'"'; }?> type='text' name='bidx-express-custom' id='bidx-express-custom' class='regular-text'>
                            </label>
                        </div>
                    </div>                   
                    
                </div>
            </div>
        </div>

        <div id='categorydiv' class='postbox'>
            <div class='handlediv' title='Click to toggle'><br></div><h3 class='hndle'><span><?php _e('Mentoring evaluation','bidxplugin');?></span></h3>
            <div class='inside'>
                <div id='taxonomy-category' class='categorydiv'>
                    <div class=''>
                        <div class='label'>
                            <label class='selectit'>
                                <input <?php echo (isset($this->webapp) && $this->webapp) ? 'checked':'';?> value='1' type='checkbox' name='bidx-webapp' id='bidx-webapp'>
                                <?php _e('Do you want to activate mentoring evaluation for this portal ? ','bidxplugin');?>
                            </label>
                            <div style="float:right;display:none;"><a target='_blank' href="https://drive.google.com/file/d/0B2cEbY8jkjRaRUNoSU90cWlNN3c/view?usp=sharing"><?php _e('Click here to view docs'); ?></a></div>
                        </div>
                    </div>
                </div>
                <div class='label'>
                    <label class='selectit' for='bidx-evaluation-competitionid'>
                        <span class="description"><?php _e('Please enter competition Id ','bidxplugin');?></span><br/>
                        <input <?php if( isset( $this->competitionId ) ) { echo 'value="'.$this->competitionId.'"'; }?> type='text' name='bidx-evaluation-competitionid' id='bidx-evaluation-competitionid' class='regular-text'>
                    </label>
                </div>
            </div>
        </div>

        <div id='categorydiv' class='postbox'>
            <div class='handlediv' title='Click to toggle'><br></div><h3 class='hndle'><span><?php _e('Wizehive','bidxplugin');?></span></h3>
            <div class='inside'>
                <div id='taxonomy-category' class='categorydiv'>
                    <div class=''>
                        <div class='label'>
                            <label class='selectit'>
                                <input <?php echo (isset($this->wizehive) && $this->wizehive) ? 'checked':'';?> value='1' type='checkbox' name='bidx-wizehive' id='bidx-wizehive'>
                                <?php _e('Do you want to activate Wizehive for this portal ? ','bidxplugin');?>
                            </label>
                            <div style="float:right;"><a target='_blank' href="https://drive.google.com/file/d/0B2cEbY8jkjRaRUNoSU90cWlNN3c/view?usp=sharing"><?php _e('Click here to view docs'); ?></a></div>
                        </div>
                    </div>
                    <div class='label'>
                        <label class='selectit' for='bidx-wizehive-slug'>
                            <span class="description"><?php _e('Please enter wizehive slug ','bidxplugin');?></span><br/>
                            <input <?php if( isset( $this->wizehiveSlug ) ) { echo 'value="'.$this->wizehiveSlug.'"'; }?> type='text' name='bidx-wizehive-slug' id='bidx-wizehive-slug' class='regular-text'>
                        </label>
                     </div>
                    </div>
            </div>
        </div>

        <div id='categorydiv' class='postbox'>
            <div class='handlediv' title='Click to toggle'><br></div><h3 class='hndle'><span><?php _e('News and Events','bidxplugin');?></span></h3>
            <div class='inside'>
                <div id='taxonomy-category' class='categorydiv'>
                    <div class=''>
                        <div class='label'>
                            <label class='selectit'>
                                <input <?php echo (isset($this->groupNews) && $this->groupNews) ? 'checked':'';?> value='1' type='checkbox' name='group-news' id='group-news'>
                                <?php _e('Do you want to activate News and Events for this group ?','bidxplugin');?>
                            </label>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div id='categorydiv' class='postbox'>
            <div class='handlediv' title='Click to toggle'><br></div><h3 class='hndle'><span>SSO Login redirect</span></h3>
            <div class='inside'>
                <div id='taxonomy-category' class='categorydiv'>
                    <div class=''>
        		    	 <p>
        				    <?php _e('When integrating with an external single sign on mechanism a specific redirect is needed. It can be enabled and set here by a Wordpress administrator.<br />For security reasons only a local URI redirect is allowed which can loop it through the SSO mechanism in Bidx-Soca.','bidxplugin');?>
        			     </p>
                        <div class='label'>
                            <label class='selectit'>
                                <input <?php echo (isset($this->ssoRedirect) && $this->ssoRedirect) ? 'checked':'';?> value='1' type='checkbox' name='bidx-sso-redirect' id='bidx-sso-redirect'>
				                <span class="description"><?php _e('Enable an external SSO redirect URL for my portal.','bidxplugin');?></span>
                            </label>
                        </div>
                    </div>
                    <div class='label'>
                        <label class='selectit' for='bidx-ssoredirect-url'>
                            <span class="description"><?php _e('SSO redirect URI for my portal.','bidxplugin');?></span><br/>
                            <input <?php if( isset( $this->ssoRedirectUrl ) ) { echo 'value="'.$this->ssoRedirectUrl.'"'; }?> type='text' name='bidx-ssoredirect-url' id='bidx-ssoredirect-url' class='regular-text' <?php disabled( $this->ssoRedirect, 'disabled', true ); ?> >
                        </label>
		             </div>
                    </div>
                </div>
            </div>
        </div>
       <div class="updated inline below-h2">
            <p><strong><?php _e('Important:');?></strong><?php _e('Refresh the page after saving the option to see the News & Events category in Left menu.','bidxplugin');?></p>
       </div><br/>
        <div class='buttonwrapper'>
            <input type='submit' name = 'action' value='Save' class='button button-primary'>

        </div>
</form>
