<!--
    Getting started page for the bidx dashboard
-->

<div id="invite-members">
    <!-- Linkedin -->
    <div class="wrap">
        <article>
        	On this page we offer you some tips on how to get started, and mange your group. This information will always be available in your control panel.
        
        
            <h2>Grow your group </h2>
            <h4>
				Invite other members of the bidX platform to join your group, 
				or get some tips on how to use social media to send out invitations and promote your group
            </h4>
            <a class="button-primary" href="?page=invite-members">Go to invite members</a>
        </article>
        <br>

        <article>
            <h2>Monitor activity in your group </h2>
            <h4>
				Find out how many new members have joined your group in the last 30 days and welcome them. 
				Follow what your members' activity is, when they logged in for the last time, 
				and if they already created a business proposal or completed their investor profile. 
            </h4>
            <a class="button-primary" href="?page=bidx_monitoring_page">Go to monitoring</a>
        </article>
        <br>

        <article>
            <h2>Update the settings of your group </h2>
            <h4>
				Update the settings of your group, for instance change the logo, description or give it a new focus country.
            </h4>
            <a class="button-primary" href="?page=group-settings">Go to Group Settings</a>
        </article>
        <br>

        <article>
            <h2>Update pages and create new ones</h2>
            <h4>
            	Update the content of existing pages in your group, or create new ones.
				Pages are similar to posts in that they have a title, body text, but they are different 
				in that they are not part of the chronological blog stream. 
				They are sort of permanent posts. Pages can have a hierarchy. 
				You can nest pages under other pages by making one the “Parent” of the other, creating a group of pages.
            </h4>
            <p>
                <a class="button-primary" href="/wp-admin/edit.php?post_type=page">Go to Pages</a>
                Update pages or create new ones
            </p>
            <h4>
            	Create new or update your current posts. Also here you can add pictures. 
            	As for pages you can decide to publish them immediately or at a later date, 
            	make them visible for all your members or only for you.
            </h4>
            <p>
                <a class="button-primary" href="/wp-admin/edit.php">Go to Posts</a>
                Publish new posts
            </p>
            <h4>
            	The Media tab is there for you to upload images. 
            	From here you can attach them to the pages or posts you create. 
            	When you create a post you will be able to see the button "Add media" as well. 
            	Here you can open up the media folder and select the images you have uploaded previously.
            </h4>
            <p>
                <a class="button-primary" href="/wp-admin/upload.php">Go to Media</a>
                Working with media
            </p>
            <h4>
            	You can use the Appearance tab to manage the navigation menu and the look and feel of your group. 
            	Select the pages you want to make available to your visitors, decide on in which order you want to display them and add descriptions. 
            	We will enhance this tab with other functionalities like themes very soon.
            </h4>
            <p>
                <a class="button-primary" href="/wp-admin/themes.php">Go to appearance</a>
                Change the appearance
            </p>
        </article>
        <br>

        <article>
            <h2>Help your members and get help from bidX Customer service </h2>
            <h4>
 				Your members may have all kinds of questions about your group and services.
 				Here you can see all the emails from the members in your group. 
 				You can also reply from here.
            </h4>
            <a class="button-primary" href="?page=support">Go to Support</a>
        </article>
        <br>

        <article>
            <h2>Manage Competitions </h2>
            <h4>
                A competition is a perfect way to identify promising entrepreneurs, expose them internationally, 
                and connect them with potential financiers.
            </h4>
            <a class="button-primary" href="?page=competitions">Competitions</a>
        </article>
        <br>
        <!--
        <article>
            <h2>bidX Board </h2>
            <h4>
                Text (bidx messages to Group Owners)
            </h4>
            <a class="button-primary" href="?page=board">Go to bidX Board</a>
        </article> -->
        <br>
    </div>
 </div>

