<!--
    Search startpage.
    Single page application that is setup
-->

<div id="invite-members">
    <!-- Linkedin -->
    <div class="wrap">
        <article>
            <h2>Grow your group </h2>
            <h4>
                Send a message to your contacts in LinkedIn inviting them to visit and join the group. Explain what your group does and what members can get out of it. Don't forget including a link of your group. This is what you need to do:
            </h4>
            <a class="button-primary" href="?page=invite-members">Go to invite members</a>
        </article>
        <br>

        <article>
            <h2>Monitor activity in your group </h2>
            <h4>
                Send a message to your contacts in LinkedIn inviting them to visit and join the group. Explain what your group does and what members can get out of it. Don't forget including a link of your group. This is what you need to do:
            </h4>
            <a class="button-primary" href="?page=monitoring">Go to monitoring</a>
        </article>
        <br>

        <article>
            <h2>Update the settings of your group </h2>
            <h4>
                Send a message to your contacts in LinkedIn inviting them to visit and join the group. Explain what your group does and what members can get out of it. Don't forget including a link of your group. This is what you need to do:
            </h4>
            <a class="button-primary" href="?page=group-settings">Go to Group Settings</a>
        </article>
        <br>

        <article>
            <h2>Update content of the site </h2>
            <p>
                <a class="button-primary" href="/wp-admin/edit.php?post_type=page">Go to Pages</a>
                Update pages or create new ones
            </p>
            <p>
                <a class="button-primary" href="/wp-admin/edit.php">Go to Posts</a>
                Publish new posts
            </p>
            <p>
                <a class="button-primary" href="/wp-admin/upload.php">Go to Media</a>
                Working with media
            </p>
            <p>
                <a class="button-primary" href="/wp-admin/themes.php">Go to appearance</a>
                Change the appearance
            </p>
        </article>
        <br>

        <article>
            <h2>Help your members and get help from bidX Customer service </h2>
            <h4>
                Send a message to your contacts in LinkedIn inviting them to visit and join the group. Explain what your group does and what members can get out of it. Don't forget including a link of your group. This is what you need to do:
            </h4>
            <a class="button-primary" href="?page=support">Go to Support</a>
        </article>
        <br>

        <article>
            <h2>Manage Competitions </h2>
            <h4>
                A competition is a perfect way to identify promising entrepreneurs, expose them internationally, and connect them with potential financiers.
            </h4>
            <a class="button-primary" href="?page=competitions">Competitions</a>
        </article>
        <br>

        <article>
            <h2>bidX Board </h2>
            <h4>
                Text (bidx messages to Group Owners)
            </h4>
            <a class="button-primary" href="?page=board">Go to bidX Board</a>
        </article>
        <br>
    </div>
 </div>

