<!--
    Search startpage.
    Single page application that is setup
-->

<div id="invite-members">
    <!-- Linkedin -->
    <div class="row-fluid">
        <section class="span8 well dashboard">
            <article class="view">
                <div class="row-fluid">
                    <div class="span6">
                        <h3>Grow your group </h3>
                    </div>
                    <div class="span2 offset4">
                        <a href="?page=invite">Go to invite members</a>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12">
                        Send a message to your contacts in LinkedIn inviting them to visit and join the group. Explain what your group does and what members can get out of it. Don't forget including a link of your group. This is what you need to do:
                    </div>
                </div>

            </article>

        </section>
    </div>
    <div class="row-fluid">
        <section class="span8 well dashboard">
            <article class="view">
                <div class="row-fluid">
                    <div class="span6">
                        <h3>Monitor activity in your group </h3>
                    </div>
                    <div class="span2 offset4">
                        <a href="?page=monitoring">Go to monitoring</a>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12">
                        Send a message to your contacts in LinkedIn inviting them to visit and join the group. Explain what your group does and what members can get out of it. Don't forget including a link of your group. This is what you need to do:
                    </div>
                </div>

            </article>

        </section>
    </div>
    <div class="row-fluid">
        <section class="span8 well dashboard">
            <article class="view">
                <div class="row-fluid">
                    <div class="span6">
                        <h3>Update the settings of your group </h3>
                    </div>
                    <div class="span2 offset4">
                        <a href="?page=groupsettings">Go to Group Settings</a>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12">
                        Send a message to your contacts in LinkedIn inviting them to visit and join the group. Explain what your group does and what members can get out of it. Don't forget including a link of your group. This is what you need to do:
                    </div>
                </div>

            </article>

        </section>
    </div>
     <div class="row-fluid">
        <section class="span8 well dashboard">
            <article class="view">
                <div class="row-fluid">
                    <div class="span12">
                        <h3>Update content of the site </h3>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span6">
                        Update pages and create new ones
                    </div>
                    <div class="span2 offset4">
                        <a href="/wp-admin/edit.php?post_type=page">Go to Pages</a>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span6">
                        Publish new posts
                    </div>
                    <div class="span2 offset4">
                        <a href="/wp-admin/edit.php">Go to Posts</a>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span6">
                        Working with media
                    </div>
                    <div class="span2 offset4">
                        <a href="/wp-admin/upload.php">Go to Media</a>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span6">
                        Change the appearance
                    </div>
                    <div class="span2 offset4">
                        <a href="/wp-admin/themes.php">Go to appearance</a>
                    </div>
                </div>


            </article>

        </section>
    </div>
    <div class="row-fluid">
        <section class="span8 well dashboard">
            <article class="view">
                <div class="row-fluid">
                    <div class="span6">
                        <h3>Help your members and get help from bidX Customer service </h3>
                    </div>
                    <div class="span2 offset4">
                        <a href="?page=support">Go to Support</a>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12">
                        Send a message to your contacts in LinkedIn inviting them to visit and join the group. Explain what your group does and what members can get out of it. Don't forget including a link of your group. This is what you need to do:
                    </div>
                </div>

            </article>

        </section>
    </div>
    <div class="row-fluid">
        <section class="span8 well dashboard">
            <article class="view">
                <div class="row-fluid">
                    <div class="span6">
                        <h3>bidX Board</h3>
                    </div>
                    <div class="span2 offset4">
                        <a href="?page=board">Go to bidX Board</a>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12">
                        Text (bidx messages to Group Owners)
                    </div>
                </div>

            </article>

        </section>
    </div>
 </div>

