<!--
    Search startpage.
    Single page application that is setup
-->

<div id="invite-members">
    <!-- Linkedin -->
    <div class="row">
        <section class="col-sm-12 well dashboard">
            <article class="oldview">
                <div class="row">
                    <div class="col-sm-6">
                        <h3>LinkedIn</h3>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-11">
                        Send a message to your contacts in LinkedIn inviting them to visit and join the group. Explain what your group does and what members can get out of it. Don't forget including a link of your group. This is what you need to do:
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-11">
                        <ul>
                            <li>Login in LinkedIn</li>
                            <li>Click on the Inbox Icon on the top menu</li>
                            <li>Select who you would like to send the invitation to, by using the address book next to the To field of the message</li>
                            <li>Compose and click on Send message. You can copy/paste the draft below, or create your own email</li>
                        </ul>
                    </div>
                    <div class="col-sm-9 col-sm-offset-1">
                        Dear contacts,

                        I would like to present you the group {your group name} which I have created in the bidX platform. bidX platform offers online services to facilitate the creation and growth of entrepreneurial ecosystems.

                        Group {your group name} focuses on {role, region, industry...} I have created this group to {reason} and I would like to invite you to be part of this adventure

                        Please visit us at {link home group page} and register to join. If you are already a member of other groups in the bidX platform, you can just click on Join.

                        Best regards,

                        {name_group_admin}

                    </div>

                </div>
            </article>

        </section>
    </div>
    <!-- Facebook -->
    <div class="row">
        <section class="col-sm-12 well dashboard">
            <article class="oldview">
                <div class="row">
                    <div class="col-sm-6">
                        <h3>Facebook</h3>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-11">
                        Send a message to your friends in Facebook inviting them to visit and join the group. Explain what your group does and what members can get out of it. Don't forget including a link of your group. This is what you need to do:
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-11">
                        <ul>
                            <li>Login in Facebook</li>
                            <li>Click on the message icon on the top menu</li>
                            <li>Type in the names of those friends you would like to send a message to</li>
                            <li>Compose and hit on enter to send the message. You can copy/paste the draft below, or create your own email</li>
                        </ul>
                    </div>
                    <div class="col-sm-9 col-sm-offset-1">
                        Hi all,

                        I would like to present you the group {your group name} which I have created in the bidX platform. bidX platform offers online services to facilitate the creation and growth of entrepreneurial ecosystems.

                        Group {your group name} focuses on {role, region, industry...} I have created this group to {reason} and I would like to invite you to be part of this adventure

                        Please visit us at {link home group page} and register to join. If you are already a member of other groups in the bidX platform, you can just click on Join.

                        Best regards,

                        {name_group_admin}

                    </div>

                </div>
            </article>

        </section>
    </div>
     <!-- Twitter -->
    <div class="row">
        <section class="col-sm-12 well dashboard">
            <article class="oldview">
                <div class="row">
                    <div class="col-sm-6">
                        <h3>Twitter</h3>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-11">
                        Announce you group and welcome your followers to join by posting a tweet for your followers in twitter. One of these could be your tweet.
                    </div>
                    <div class="col-sm-11">
                        Working or interested in the {fill in sector} business? Join the new group, meet other professionals and start collaborating! {fill in link to group}
                    </div>
                    <div class="col-sm-11">
                        Working or interested in business in {fill in country/city/region}? Join the new group, meet other professionals and start collaborating! {fill in link to group}
                    </div>
                    <div class="col-sm-11">
                        Copy and paste the one you have chosen in your twitter account
                    </div>
                    <div class="col-sm-11">
                        Fill in the spaces between {}
                    </div>
                    <div class="col-sm-11">
                        Click on Tweet
                    </div>
                </div>
            </article>

        </section>
    </div>



</div>

