<!--
    Search startpage.
    Single page application that is setup
-->

<div id="monitoring">
    <div class="row">
        <div class="col-sm-8">
            <h2>Group growth</h2>
        </div>

    </div>
    <div class="row">
        <div class="col-sm-6">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Members and business</th>
                        <th>Amount</th>
                        <!-- <th>Lastaddition</th> -->
                    </tr>
                </thead>
                <tbody class="list-growth">
                    <tr>
                        <td>Members</td>
                        <td class="members">
                            <div class="loading"><?php _e ('Loading...', 'bidxplugin') ?></div>
                        </td>
                    </tr>
                    <tr>
                        <td>Entrepreneurs</td>
                        <td class="entrpreneurs">
                            <div class="loading"><?php _e ('Loading...', 'bidxplugin') ?></div>
                        </td>
                    </tr>
                    <tr>
                        <td>Investors</td>
                        <td class = "investors">
                            <div class="loading"><?php _e ('Loading...', 'bidxplugin') ?></div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <section class="col-sm-8 well dashboard">
            <div class="row">
                <div class="col-sm-6">
                        <h2>Members who recently joined</h2>
                </div>
                <div class="col-sm-12">
                        These members are new in your group. Select and send a welcome message.
                </div>
            </div>
            <div class="row">
                <div class="col-sm-offset-9 col-sm-3">

                                <div class="input-append">
                                    <input type="text" class="search-query search-query-rounded searchname" placeholder="Search" data-maxlength="1" data-searchtype="list">
                                    <!-- <button type="submit" class="btn"><span class="fa fa-search"></span></button> -->
                                </div>
                    </div>
            </div>
            <!-- ************************* utility views *********************************** -->
            <article class="view viewLoadlist"><?php _e ('Loading...', 'bidxplugin') ?></article>
            <article class="view viewList">
                <div class="row">
                    <!-- Latest member data -->
                    <div class="col-sm-12 latest-member">
                        <ul class="listheader ">
                            <li class="mediaheader" >
                                <div class="row">
                                    <div class="col-sm-1 pull-left check">
                                        <label class="checkbox">
                                            <input type="checkbox" data-toggle="checkbox" class="messagesCheckall" value="">
                                        </label>
                                    </div>
                                    <div class="col-sm-11 headerbody">
                                        <div class="row">
                                            <div class="col-sm-4"><strong><span class="placeholder user"><?php _e ('First + Last name', 'bidxplugin') ?></span></strong></div>
                                            <div class="col-sm-2"><strong><span class="placeholder userId"/><?php _e ('Location', 'bidxplugin') ?></span></strong></div>
                                            <div class="col-sm-2"><strong><span class="placeholder membersince"/><?php _e ('Member since', 'bidxplugin') ?></span></strong></div>
                                            <div class="col-sm-2"><strong><span class="placeholder role"/><?php _e ('Role', 'bidxplugin') ?></span></strong></div>
                                            <div class="col-sm-2"><strong><span class="placeholder lastlogin"/><?php _e ('Last Login', 'bidxplugin') ?></span></strong></div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>

                        <!-- MESSAGE LIST -->
                        <ul class="list media-list ">
                            <li class="media">
                                <div class="pull-left check"></div>
                                <div class="pull-left">
                                    <?php _e ('Loading...', 'bidxplugin') ?>
                                </div>
                            </li>

                        </ul>
                    </div>
                </div>

            </article>
            <div class="row">
                    <div class="col-sm-12 pagercontainer-list">
                        <div class="pager-list"></div>
                    </div>
            </div>
            <div class="row">
                <div class="col-sm-3 col-sm-offset-9">
                    <a class="btn btn-primary compose-list" href="#monitoring/compose" data-href="#monitoring/compose">Compose welcome message</a>
                </div>
            </div>

            <!-- All Members  -->
            <div class="row">
                <div class="col-sm-6">
                        <h2>All the members</h2>
                </div>
                <div class="col-sm-12">
                        See here all the members in your group with their login data, location and role. Select those you want to  send a message to.
                </div>
            </div>
            <div class="row">
                <div class="col-sm-offset-9 col-sm-3">

                                <div class="input-append">
                                    <input type="text" class="search-query search-query-rounded searchname"  placeholder="Search" data-maxlength="1" data-searchtype="all">
                                    <!-- <button type="submit" class="btn"><span class="fa fa-search"></span></button> -->
                                </div>


                    </div>
            </div>
            <article class="view viewLoadall"><?php _e ('Loading...', 'bidxplugin') ?></article>
            <article class="view viewAll">
                <div class="row">
                    <!-- All member data -->
                    <div class="col-sm-12 latest-member">
                        <ul class="listheader ">
                            <li class="mediaheader" >
                                <div class="row">
                                    <div class="col-sm-1 pull-left check">
                                        <label class="checkbox">
                                            <input type="checkbox" data-toggle="checkbox" class="messagesCheckall" value="">
                                        </label>
                                    </div>
                                    <div class="col-sm-11 headerbody">
                                        <div class="row">
                                            <div class="col-sm-4"><strong><span class="placeholder user"><?php _e ('First + Last name', 'bidxplugin') ?></span></strong></div>
                                            <div class="col-sm-2"><strong><span class="placeholder userId"/><?php _e ('Location', 'bidxplugin') ?></span></strong></div>
                                            <div class="col-sm-2"><strong><span class="placeholder membersince"/><?php _e ('Member since', 'bidxplugin') ?></span></strong></div>
                                            <div class="col-sm-2"><strong><span class="placeholder role"/><?php _e ('Role', 'bidxplugin') ?></span></strong></div>
                                            <div class="col-sm-2"><strong><span class="placeholder lastlogin"/><?php _e ('Last Login', 'bidxplugin') ?></span></strong></div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>

                        <!-- MESSAGE LIST -->
                        <ul class="all media-list ">
                            <li class="media">
                                <div class="pull-left check"></div>
                                <div class="pull-left">
                                    <?php _e ('Loading...', 'bidxplugin') ?>
                                </div>
                            </li>

                        </ul>
                    </div>
                </div>
            </article>
            <div class="row">
                    <div class="col-sm-12 pagercontainer-all">
                        <div class="pager-all"></div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-3 col-sm-offset-9">
                        <a class="btn btn-primary compose-all" href="#monitoring/composeAll" data-href="#monitoring/composeAll">Compose message</a>
                    </div>
                </div>

            <article class="modalView modalCompose">
                <form action="">
                    <div  id="dashboard" class="mainState mainStateMonitoring">                <!-- Modal -->
                        <div class="modal hide fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                <h3 id="myModalLabel"><?php _e ('Compose message', 'bidxplugin') ?></h3>
                            </div>
                            <div class="modal-body">
                                <form action="">
                                    <div class="row">
                                        <div class="control-group">
                                            <label class="control-label"><?php _e('Recipient','bidxplugin'); ?></label>
                                            <div class="controls">
                                                <select name="contacts" multiple class="hide" data-placeholder="<?php _e( 'Select a recipient' ); ?>"></select>
                                            </div>

                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="control-group">
                                            <label class="control-label"><?php _e('Subject','bidxplugin'); ?></label>
                                                <div class="controls">
                                                    <input type="text" name="subject" placeholder="<?php _e ('Your subject goes here', 'bidxplugin') ?>" >
                                                </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="control-group">
                                            <label class="control-label"><?php _e('Message','bidxplugin'); ?></label>
                                            <div class="controls">
                                                <textarea name="content" placeholder="<?php _e ('Please type your message here', 'bidxplugin') ?>" value=""></textarea>
                                            </div>
                                        </div>

                                    </div>
                                    <div class="pull-left">

                                    </div>
                                </form>
                            </div>
                            <div class="modal-footer">
                                <a href="#" data-href="#monitoring/discardConfirm" class="btn compose-cancel"><?php _e ('Discard message') ?></a>
                                <button type="submit" class="btn btn-primary compose-submit"><?php _e ('Send message', 'bidxplugin') ?></button>
                            </div>
                        </div>
                    </div>
                </form>
            </article>
            <article class="modalView modalDiscardConfirm">
                <!-- Modal -->
                <div class="modal hide fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h3 id="myModalLabel"><?php _e ('Discard message') ?></h3>
                    </div>
                    <div class="modal-body">
                        <p>
                            <?php _e ('You are about to discard this message. Are you sure?') ?>
                        </p>
                    </div>

                    <div class="modal-footer">
                        <a class="btn" href="#" data-href="#monitoring/compose"><?php _e ('Cancel') ?></a>
                        <a class="btn btn-primary" data-dismiss="modal" aria-hidden="true"><?php _e ('Discard message') ?></a>
                    </div>

                </div>
            </article>
        </section>
    </div>
</div>

<script type="text/html" id="dashboard-listitem">
    <!--
    <li class="media" >
    <div class="row">
    <div class="col-sm-1 pull-left check">
    <label class="checkbox">
    <input type="checkbox" data-toggle="checkbox"  value="" data-id="%userId%">
    </label>
    </div>
    <div class="col-sm-11 media-body">
    <div class="row">
    <div class="col-sm-4">
        <h6 class="media-heading">
            <span class="placeholder user"><a target="_blank" href="/member/%userId%">%user%</a></span>
        </h6>
    </div>
    <div class="col-sm-2">
        <span class="placeholder location"/>%location%</span>
    </div>
    <div class="col-sm-2">
        <span class="placeholder membersince"/>%membersince%</span>
    </div>
    <div class="col-sm-2">
        <span class="placeholder role"/>%role%</span>
    </div>
    <div class="col-sm-2">
        <span class="placeholder lastlogin"/>%lastlogin%</span>
    </div>
    </div>
   </div>
    </li>
    -->
</script>

<script type="text/html" id="dashboard-empty">
    <!--
    <li class="media">
    <div class="pull-left check"></div>
    <div class="">
    <?php _e ('No messages available') ?>
    </div>
    </li>
    -->
</script>
