<?php
/**
 * Created by PhpStorm.
 * User: Bilel BARHOUMI
 * Email: infobilel@gmail.com
 * Date: 08/03/2016
 * Time: 10:49
 */

?>
<option value="">Currency...</option>
<option value="AFA">AFA - Afghani</option>
<option value="AFN">AFN - Afghani</option>
<option value="ALK">ALK - Albanian old lek</option>
<option value="ALL">ALL - Lek</option>
<option value="DZD">DZD - Algerian Dinar</option>
<option value="USD">USD - US Dollar</option>
<option value="ADF">ADF - Andorran Franc</option>
<option value="ADP">ADP - Andorran Peseta</option>
<option value="EUR">EUR - Euro</option>
<option value="AOR">AOR - Angolan Kwanza Readjustado</option>
<option value="AON">AON - Angolan New Kwanza</option>
<option value="AOA">AOA - Kwanza</option>
<option value="XCD">XCD - East Caribbean Dollar</option>
<option value="ARA">ARA - Argentine austral</option>
<option value="ARS">ARS - Argentine Peso</option>
<option value="ARL">ARL - Argentine peso ley</option>
<option value="ARM">ARM - Argentine peso moneda nacional</option>
<option value="ARP">ARP - Peso argentino</option>
<option value="AMD">AMD - Armenian Dram</option>
<option value="AWG">AWG - Aruban Guilder</option>
<option value="AUD">AUD - Australian Dollar</option>
<option value="ATS">ATS - Austrian Schilling</option>
<option value="AZM">AZM - Azerbaijani manat</option>
<option value="AZN">AZN - Azerbaijanian Manat</option>
<option value="BSD">BSD - Bahamian Dollar</option>
<option value="BHD">BHD - Bahraini Dinar</option>
<option value="BDT">BDT - Taka</option>
<option value="BBD">BBD - Barbados Dollar</option>
<option value="BYR">BYR - Belarussian Ruble</option>
<option value="BEC">BEC - Belgian Franc (convertible)</option>
<option value="BEF">BEF - Belgian Franc (currency union with LUF)</option>
<option value="BEL">BEL - Belgian Franc (financial)</option>
<option value="BZD">BZD - Belize Dollar</option>
<option value="XOF">XOF - CFA Franc BCEAO</option>
<option value="BMD">BMD - Bermudian Dollar</option>
<option value="INR">INR - Indian Rupee</option>
<option value="BTN">BTN - Ngultrum</option>
<option value="BOP">BOP - Bolivian peso</option>
<option value="BOB">BOB - Boliviano</option>
<option value="BOV">BOV - Mvdol</option>
<option value="BAM">BAM - Convertible Marks</option>
<option value="BWP">BWP - Pula</option>
<option value="NOK">NOK - Norwegian Krone</option>
<option value="BRC">BRC - Brazilian cruzado</option>
<option value="BRB">BRB - Brazilian cruzeiro</option>
<option value="BRL">BRL - Brazilian Real</option>
<option value="BND">BND - Brunei Dollar</option>
<option value="BGN">BGN - Bulgarian Lev</option>
<option value="BGJ">BGJ - Bulgarian lev A/52</option>
<option value="BGK">BGK - Bulgarian lev A/62</option>
<option value="BGL">BGL - Bulgarian lev A/99</option>
<option value="BIF">BIF - Burundi Franc</option>
<option value="KHR">KHR - Riel</option>
<option value="XAF">XAF - CFA Franc BEAC</option>
<option value="CAD">CAD - Canadian Dollar</option>
<option value="CVE">CVE - Cape Verde Escudo</option>
<option value="KYD">KYD - Cayman Islands Dollar</option>
<option value="CLP">CLP - Chilean Peso</option>
<option value="CLF">CLF - Unidades de fomento</option>
<option value="CNX">CNX - Chinese People's Bank dollar</option>
<option value="CNY">CNY - Yuan Renminbi</option>
<option value="COP">COP - Colombian Peso</option>
<option value="COU">COU - Unidad de Valor real</option>
<option value="KMF">KMF - Comoro Franc</option>
<option value="CDF">CDF - Franc Congolais</option>
<option value="NZD">NZD - New Zealand Dollar</option>
<option value="CRC">CRC - Costa Rican Colon</option>
<option value="HRK">HRK - Croatian Kuna</option>
<option value="CUP">CUP - Cuban Peso</option>
<option value="CYP">CYP - Cyprus Pound</option>
<option value="CZK">CZK - Czech Koruna</option>
<option value="CSK">CSK - Czechoslovak koruna</option>
<option value="CSJ">CSJ - Czechoslovak koruna A/53</option>
<option value="DKK">DKK - Danish Krone</option>
<option value="DJF">DJF - Djibouti Franc</option>
<option value="DOP">DOP - Dominican Peso</option>
<option value="ECS">ECS - Ecuador sucre</option>
<option value="EGP">EGP - Egyptian Pound</option>
<option value="SVC">SVC - Salvadoran colón</option>
<option value="EQE">EQE - Equatorial Guinean ekwele</option>
<option value="ERN">ERN - Nakfa</option>
<option value="EEK">EEK - Kroon</option>
<option value="ETB">ETB - Ethiopian Birr</option>
<option value="FKP">FKP - Falkland Island Pound</option>
<option value="FJD">FJD - Fiji Dollar</option>
<option value="FIM">FIM - Finnish Markka</option>
<option value="FRF">FRF - French Franc</option>
<option value="XFO">XFO - Gold-Franc</option>
<option value="XPF">XPF - CFP Franc</option>
<option value="GMD">GMD - Dalasi</option>
<option value="GEL">GEL - Lari</option>
<option value="DDM">DDM - East German Mark of the GDR (East Germany)</option>
<option value="DEM">DEM - Deutsche Mark</option>
<option value="GHS">GHS - Ghana Cedi</option>
<option value="GHC">GHC - Ghanaian cedi</option>
<option value="GIP">GIP - Gibraltar Pound</option>
<option value="GRD">GRD - Greek Drachma</option>
<option value="GTQ">GTQ - Quetzal</option>
<option value="GNF">GNF - Guinea Franc</option>
<option value="GNE">GNE - Guinean syli</option>
<option value="GWP">GWP - Guinea-Bissau Peso</option>
<option value="GYD">GYD - Guyana Dollar</option>
<option value="HTG">HTG - Gourde</option>
<option value="HNL">HNL - Lempira</option>
<option value="HKD">HKD - Hong Kong Dollar</option>
<option value="HUF">HUF - Forint</option>
<option value="ISK">ISK - Iceland Krona</option>
<option value="ISJ">ISJ - Icelandic old krona</option>
<option value="IDR">IDR - Rupiah</option>
<option value="IRR">IRR - Iranian Rial</option>
<option value="IQD">IQD - Iraqi Dinar</option>
<option value="IEP">IEP - Irish Pound (Punt in Irish language)</option>
<option value="ILP">ILP - Israeli lira</option>
<option value="ILR">ILR - Israeli old sheqel</option>
<option value="ILS">ILS - New Israeli Sheqel</option>
<option value="ITL">ITL - Italian Lira</option>
<option value="JMD">JMD - Jamaican Dollar</option>
<option value="JPY">JPY - Yen</option>
<option value="JOD">JOD - Jordanian Dinar</option>
<option value="KZT">KZT - Tenge</option>
<option value="KES">KES - Kenyan Shilling</option>
<option value="KPW">KPW - North Korean Won</option>
<option value="KRW">KRW - Won</option>
<option value="KWD">KWD - Kuwaiti Dinar</option>
<option value="KGS">KGS - Som</option>
<option value="LAK">LAK - Kip</option>
<option value="LAJ">LAJ - Lao kip</option>
<option value="LVL">LVL - Latvian Lats</option>
<option value="LBP">LBP - Lebanese Pound</option>
<option value="LSL">LSL - Loti</option>
<option value="ZAR">ZAR - Rand</option>
<option value="LRD">LRD - Liberian Dollar</option>
<option value="LYD">LYD - Libyan Dinar</option>
<option value="CHF">CHF - Swiss Franc</option>
<option value="LTL">LTL - Lithuanian Litas</option>
<option value="LUF">LUF - Luxembourg Franc (currency union with BEF)</option>
<option value="MOP">MOP - Pataca</option>
<option value="MKD">MKD - Denar</option>
<option value="MKN">MKN - Former Yugoslav Republic of Macedonia denar A/93</option>
<option value="MGA">MGA - Malagasy Ariary</option>
<option value="MGF">MGF - Malagasy franc</option>
<option value="MWK">MWK - Kwacha</option>
<option value="MYR">MYR - Malaysian Ringgit</option>
<option value="MVQ">MVQ - Maldive rupee</option>
<option value="MVR">MVR - Rufiyaa</option>
<option value="MAF">MAF - Mali franc</option>
<option value="MTL">MTL - Maltese Lira</option>
<option value="MRO">MRO - Ouguiya</option>
<option value="MUR">MUR - Mauritius Rupee</option>
<option value="MXN">MXN - Mexican Peso</option>
<option value="MXP">MXP - Mexican peso</option>
<option value="MXV">MXV - Mexican Unidad de Inversion (UDI)</option>
<option value="MDL">MDL - Moldovan Leu</option>
<option value="MCF">MCF - Monegasque franc (currency union with FRF)</option>
<option value="MNT">MNT - Tugrik</option>
<option value="MAD">MAD - Moroccan Dirham</option>
<option value="MZN">MZN - Metical</option>
<option value="MZM">MZM - Mozambican metical</option>
<option value="MMK">MMK - Kyat</option>
<option value="NAD">NAD - Namibia Dollar</option>
<option value="NPR">NPR - Nepalese Rupee</option>
<option value="NLG">NLG - Netherlands Guilder</option>
<option value="ANG">ANG - Netherlands Antillian Guilder</option>
<option value="NIO">NIO - Cordoba Oro</option>
<option value="NGN">NGN - Naira</option>
<option value="OMR">OMR - Rial Omani</option>
<option value="PKR">PKR - Pakistan Rupee</option>
<option value="PAB">PAB - Balboa</option>
<option value="PGK">PGK - Kina</option>
<option value="PYG">PYG - Guarani</option>
<option value="YDD">YDD - South Yemeni dinar</option>
<option value="PEN">PEN - Nuevo Sol</option>
<option value="PEI">PEI - Peruvian inti</option>
<option value="PEH">PEH - Peruvian sol</option>
<option value="PHP">PHP - Philippine Peso</option>
<option value="PLZ">PLZ - Polish zloty A/94</option>
<option value="PLN">PLN - Zloty</option>
<option value="PTE">PTE - Portuguese Escudo</option>
<option value="TPE">TPE - Portuguese Timorese escudo</option>
<option value="QAR">QAR - Qatari Rial</option>
<option value="RON">RON - New Leu</option>
<option value="ROL">ROL - Romanian leu A/05</option>
<option value="ROK">ROK - Romanian leu A/52</option>
<option value="RUB">RUB - Russian Ruble</option>
<option value="RWF">RWF - Rwanda Franc</option>
<option value="SHP">SHP - Saint Helena Pound</option>
<option value="WST">WST - Tala</option>
<option value="STD">STD - Dobra</option>
<option value="SAR">SAR - Saudi Riyal</option>
<option value="RSD">RSD - Serbian Dinar</option>
<option value="CSD">CSD - Serbian Dinar</option>
<option value="SCR">SCR - Seychelles Rupee</option>
<option value="SLL">SLL - Leone</option>
<option value="SGD">SGD - Singapore Dollar</option>
<option value="SKK">SKK - Slovak Koruna</option>
<option value="SIT">SIT - Slovenian Tolar</option>
<option value="SBD">SBD - Solomon Islands Dollar</option>
<option value="SOS">SOS - Somali Shilling</option>
<option value="ZAL">ZAL - South African financial rand (Funds code) (discont</option>
<option value="ESP">ESP - Spanish Peseta</option>
<option value="ESA">ESA - Spanish peseta (account A)</option>
<option value="ESB">ESB - Spanish peseta (account B)</option>
<option value="LKR">LKR - Sri Lanka Rupee</option>
<option value="SDD">SDD - Sudanese Dinar</option>
<option value="SDP">SDP - Sudanese Pound</option>
<option value="SDG">SDG - Sudanese Pound</option>
<option value="SRD">SRD - Surinam Dollar</option>
<option value="SRG">SRG - Suriname guilder</option>
<option value="SZL">SZL - Lilangeni</option>
<option value="SEK">SEK - Swedish Krona</option>
<option value="CHE">CHE - WIR Euro</option>
<option value="CHW">CHW - WIR Franc</option>
<option value="SYP">SYP - Syrian Pound</option>
<option value="TWD">TWD - New Taiwan Dollar</option>
<option value="TJS">TJS - Somoni</option>
<option value="TJR">TJR - Tajikistan ruble</option>
<option value="TZS">TZS - Tanzanian Shilling</option>
<option value="THB">THB - Baht</option>
<option value="TOP">TOP - Pa'anga</option>
<option value="TTD">TTD - Trinidata and Tobago Dollar</option>
<option value="TND">TND - Tunisian Dinar</option>
<option value="TRY">TRY - New Turkish Lira</option>
<option value="TRL">TRL - Turkish lira A/05</option>
<option value="TMM">TMM - Manat</option>
<option value="RUR">RUR - Russian rubleA/97</option>
<option value="SUR">SUR - Soviet Union ruble</option>
<option value="UGX">UGX - Uganda Shilling</option>
<option value="UGS">UGS - Ugandan shilling A/87</option>
<option value="UAH">UAH - Hryvnia</option>
<option value="UAK">UAK - Ukrainian karbovanets</option>
<option value="AED">AED - UAE Dirham</option>
<option value="GBP">GBP - Pound Sterling</option>
<option value="USN">USN - US Dollar (Next Day)</option>
<option value="USS">USS - US Dollar (Same Day)</option>
<option value="UYU">UYU - Peso Uruguayo</option>
<option value="UYN">UYN - Uruguay old peso</option>
<option value="UYI">UYI - Uruguay Peso en Unidades Indexadas</option>
<option value="UZS">UZS - Uzbekistan Sum</option>
<option value="VUV">VUV - Vatu</option>
<option value="VEF">VEF - Bolivar Fuerte</option>
<option value="VEB">VEB - Venezuelan Bolivar</option>
<option value="VND">VND - Dong</option>
<option value="VNC">VNC - Vietnamese old dong</option>
<option value="YER">YER - Yemeni Rial</option>
<option value="YUD">YUD - Yugoslav Dinar</option>
<option value="YUM">YUM - Yugoslav dinar (new)</option>
<option value="ZRN">ZRN - Zairean New Zaire</option>
<option value="ZRZ">ZRZ - Zairean Zaire</option>
<option value="ZMK">ZMK - Kwacha</option>
<option value="ZWD">ZWD - Zimbabwe Dollar</option>
<option value="ZWC">ZWC - Zimbabwe Rhodesian dollar</option>
