<div id="mentor-dashboard">

    <h1 class="pagetitle">My mentor dashboard</h1>
    <div class="dashboard">

        <div class="view viewError alert alert-warning">
            <h1><?php _e('Error','bidxplugin')?></h1>
            <span class="errorMsg"></span>
        </div>

        <div class="modalView modalConfirmRequest">
                <!-- Modal -->
                <div class="modal fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                         <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                <h3 id="myModalLabel"><?php _e ('Send request') ?></h3>
                            </div>
                            <div class="modal-body">
                                <p>
                                    <?php _e ('You are about to %action% the request. Are you sure?') ?>
                                </p>
                            </div>

                            <div class="modal-footer">
                                <a class="btn" href="#dashboard/mentor/"><?php _e ('Cancel') ?></a>
                                <a href="#" class="btn btn-primary" data-href="#dashboard/sendRequest/" ><?php _e ('Send request') ?></a>
                            </div>
                         </div>
                    </div>
                </div>
        </div>

        <div id="mentorDashboardAccordion">
            <!-- Help -->
            <div class="view viewLoadrequest alert alert-info text-center">
                <div class="progress progress-striped active">
                    <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                        <?php _e ('Loading (Sending your request)...', 'bidxplugin') ?>
                    </div>
                </div>
            </div>
            <div class="view viewLoad alert alert-info text-center">
                <div class="progress progress-striped active">
                    <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                        <?php _e ('Loading requests (Respond to a mentoring request)...', 'bidxplugin') ?>
                    </div>
                </div>
            </div>

            <div class="view viewLoadwait alert alert-info text-center">
                <div class="progress progress-striped active">
                    <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                        <?php _e ('Loading requests (Respond to a mentoring request)...', 'bidxplugin') ?>
                    </div>
                </div>
            </div>
            <div class="view viewLoadongoing alert alert-info text-center">
                <div class="progress progress-striped active">
                    <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                        <?php _e ('Loading requests (Respond to a mentoring request)...', 'bidxplugin') ?>
                    </div>
                </div>
            </div>
            <div class="panel panel-default <?php echo ($this->startingPage) ? 'panel-open': '';?>">
                <div class="panel-heading">
                    <a class="btn-block" data-toggle="collapse" data-parent="#mentorDashboardAccordion" href="#mentorDashboardAccordion-Help"><span class="fa fa-chevron-right accordion-state-icon"></span> <?php _e('Help','bidxplugin'); ?></a>
                </div>
                <div id="mentorDashboardAccordion-Help" class="panel-collapse collapse <?php echo ($this->startingPage) ? 'in': '';?>">
                    <div class="panel-body">
                       <?php $this->render('mentor/help.phtml'); ?>
                    </div>
                 </div>
            </div>
            <div class="panel panel-default panel-open view viewRespond">
                <div class="panel-heading">
                    <a class="btn-block" data-toggle="collapse" data-parent="#mentorDashboardAccordion" href="#mentorDashboardAccordion-Respond"><span class="fa fa-chevron-right accordion-state-icon"></span> Respond to mentoring request</a>
                </div>
                <div id="mentorDashboardAccordion-Respond" class="panel-collapse collapse in">
                    <div class="panel-body">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th class="hidden-xs">Business</th>
                                    <th>Entrepreneur</th>
                                    <th>Status</th>
                                    <th class="hidden-xs">Actions</th>
                                </tr>
                            </thead>
                            <tbody class="respond mentor-respond">

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="panel panel-default panel-open view viewWait">
                <div class="panel-heading">
                    <a class="btn-block" data-toggle="collapse" data-parent="#mentorDashboardAccordion" href="#mentorDashboardAccordion-Wait"><span class="fa fa-chevron-right accordion-state-icon"></span> Waiting a mentoring approval </a>
                </div>
                <div id="mentorDashboardAccordion-Wait" class="panel-collapse collapse in">
                    <div class="panel-body">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th class="hidden-xs">Business</th>
                                    <th>Entrepreneur</th>
                                    <th>Status</th>
                                    <th class="hidden-xs">Actions</th>
                                </tr>
                            </thead>
                            <tbody class="wait mentor-wait">

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="panel panel-default panel-open view viewOngoing">
                <div class="panel-heading">
                    <a class="btn-block" data-toggle="collapse" data-parent="#mentorDashboardAccordion" href="#mentorDashboardAccordion-Ongoing"><span class="fa fa-chevron-right accordion-state-icon"></span> Ongoing mentoring </a>
                </div>
                <div id="mentorDashboardAccordion-Ongoing" class="panel-collapse collapse in">
                    <div class="panel-body">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th class="hidden-xs">Business</th>
                                    <th>Entrepreneur</th>
                                    <th>Status</th>
                                    <th class="hidden-xs">Actions</th>
                                </tr>
                            </thead>
                            <tbody class="ongoing mentor-ongoing">

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div><!-- accordion -->

    </div>
</div>
<script type="text/html" id="mentor-item">
    <!--
    <tr>
   <td>
      <a data-toggle="collapse" data-target="#%accordion-id%" class="btn-block">
      <span class="placeholder name_s">%name_s%</span>
      </a>
   </td>
   <td>
      <span class="placeholder creator"><a target = "_blank" href="/member/%creatorId%" >%creator%</a></span>
   </td>
   <td class="hidden-xs">
      <span class="placeholder status">%status%</span>
   </td>
   <td class="hidden-xs">
      <span class="placeholder actions">%action%</span>
   </td>
</tr>
<tr class="list detail-list" >
   <td colspan="5" class="detailRow">
      <div class="panel-collapse collapse" id="%accordion-id%">
      <div class="row">
            <div class="col-sm-3">
                <span class="placeholder js-companylogo companylogodoc_url"><img src="%companylogodoc_url%"/></span>
            </div>
        <div class="col-sm-9">
            <div class="row">
                <div class="col-sm-6">
                    <label>Business proposal</label>
                    <div class="placeholder name_s"><a target = "_blank" href="/businesssummary/%entityid_l%">%name_s%</a></div>
                </div>
                <div class="col-sm-6">
                     <label>Entrepreneur</label>
                     <div class="placeholder creator"><a target = "_blank" href="/member/%creatorId%">%creator%</a></div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <label>Industry</label>
                    <div class="placeholder industrylabel_ss">%industrylabel_ss%</div>
                </div>
                <div class="col-sm-6">
                    <label>Product</label>
                    <div class="placeholder productservicelabel_ss">%productservicelabel_ss%</div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <label>Country</label>
                    <div class="placeholder countrylabel_ss">%countrylabel_ss%</div>
                </div>
                <div class="col-sm-6">
                    <label>Investment needed</label>
                    <div class="placeholder financingneeded_d">%financingneeded_d%</div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <label>Business stage</label>
                    <div class="placeholder stagebusinesslabel_s">%stagebusinesslabel_s%</div>
                </div>
                <div class="col-sm-6">
                    <label>Environmental Impact</label>
                    <div class="placeholder envimpactlabel_ss">%envimpactlabel_ss%</div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 col-sm-offset-6">
                    <div class="pull-right">
                        <span class="placeholder entityid_l"><a class="btn btn-primary btn-sm" target = "_blank" href="/businesssummary/%entityid_l%">View Proposal</a> </span>
                    </div>
                </div>
            </div>
         </div>
      </div>
      </div>
   </td>
</tr>
-->
</script>
<script type="text/html" id="mentor-empty">
<!--
<tr class="match mentor-match" >
    <td colspan='7'>
       <div class="pull-left">
          <?php _e ('No matches available', 'bidxplugin') ?>
       </div>
    </td>
</tr>
-->
</script>
<script type="text/html" id="respond-action">
<!--
<a href="#" class="btn-bidx-accept">Accept</a>|
<a href="#" class="btn-bidx-ignore">Ignore</a>|
<a href="#" class="btn-bidx-contact">Contact entrepreneur</a>
-->
</script>
<script type="text/html" id="wait-action">
<!--
<a href="#" class="btn-bidx-reminder">Send a reminder</a>|
<a href="#" class="btn-bidx-contact">Contact entrepreneur</a>|
<a href="#" class="btn-bidx-cancel">Cancel request</a>
-->
</script>
<script type="text/html" id="ongoing-action">
<!--
<a href="#" class="btn-bidx-add-feedback">Add feedback</a>|
<a href="#" class="btn-bidx-view-feedback">View feedback</a>|
<a href="#" class="btn-bidx-contact">Contact entrepreneur</a>|
<a href="#" class="btn-bidx-stop">Stop</a>
-->
</script>
