<div id="mentor-dashboard">

    <h1 class="pagetitle">My mentor dashboard</h1>
    <div class="dashboard">

        <div class="view viewError alert alert-warning">
            <h1><?php _e('Error','bidxplugin')?></h1>
            <span class="errorMsg"></span>
        </div>

        <div class="modalView modalConfirmRequest">
                <!-- Modal -->
                <div class="modal fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                         <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                <h3 id="myModalLabel"><?php _e ('Send request') ?></h3>
                            </div>
                            <div class="modal-body">
                                <p>
                                    <?php _e ('You are about to %action% the request. Are you sure?') ?>
                                </p>
                            </div>

                            <div class="modal-footer">
                                <a class="btn" href="#dashboard/mentor/"><?php _e ('Cancel') ?></a>
                                <a href="#" class="btn btn-primary btn-request" data-href="#dashboard/sendRequest/" ><?php _e ('Send request') ?></a>
                            </div>
                         </div>
                    </div>
                </div>
        </div>
        <!-- Modal -->
        <div class="modalView modalConfirmFeedback">                
            <div class="modal fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="feedbackLabel" aria-hidden="true">
                <div class="modal-dialog">
                     <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h3 id="feedbackLabel"><?php _e ('Add feedback') ?></h3>
                        </div>
                        <div class="modal-body">
                            <p>
                                <?php _e ('You are about to add the feedback. Are you sure?') ?>
                            </p>
                        </div>
                        <div class="modal-footer">
                            <a href="#" class="btn btn-cancel" data-href="#dashboard/addFeedback/"><?php _e ('Change feedback') ?></a>
                            <a href="#" class="btn btn-primary btn-send-feedback" data-href="#dashboard/sendFeedback/" ><?php _e ('Add feedback') ?></a>
                        </div>
                     </div>
                </div>
            </div>
        </div>
        <!-- Modal -->
        <div class="modalView modalSendFeedback">                
        <div class="modal fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                 <div class="modal-content">
                    <div class="modal-header">
                        <a class="btn btnRequestCancel pull-right" href="#dashboard/mentor">
                            <button type="button" class="close">×</button>
                        </a>
                        <h3 id="myModalLabel"><?php _e ('Send feedback') ?></h3>
                    </div>
                    <div class="modal-body">
                        <form class="frmsendFeedback">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label><?php _e('Feedback purpose','bidxplugin'); ?></label>
                                         <select class= "chosen-feedback" name="feedbackpurpose" multiple></select>
                                    </div>
                                    <div class="form-group">
                                        <label><?php _e('Feedback','bidxplugin'); ?></label>
                                        <textarea name="feedback" class="form-control" placeholder="<?php _e('Please write your feedback','bidxplugin');?>" ></textarea>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <a class="btn btn-feedback-cancel" href="#dashboard/mentor"><?php _e ('Cancel') ?></a>
                        <a class="btn btn-primary btn-feedback-submit"  ><?php _e ('Add feedback') ?></a> <!-- data-href="#mentoringRequest/sendRequest/" -->
                    </div>
                 </div>
            </div>
        </div>
    </div>
        <div class="view viewLoadrequest alert alert-info text-center">
          <div class="progress progress-striped active">
              <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                  <?php _e ('Loading (Sending your request)...', 'bidxplugin') ?>
              </div>
          </div>
        </div>
        <div id="mentorDashboardAccordion">
            <!-- Help -->        
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a class="btn-block" data-toggle="collapse" data-parent="#mentorDashboardAccordion" href="#mentorDashboardAccordion-Help"><span class="fa fa-chevron-right accordion-state-icon"></span> <?php _e('Help','bidxplugin'); ?></a>
                </div>
                <div id="mentorDashboardAccordion-Help" class="panel-collapse collapse">
                    <div class="panel-body">
                       <?php $this->render('dashboard/help.phtml'); ?>
                    </div>
                 </div>
            </div>           
              <?php $this->render('dashboard/mentor-mentoring.phtml'); ?>
              <?php $this->render('dashboard/entrepreneur-mentoring.phtml'); ?>
              <?php //$this->render('dashboard/ongoing-mentoring.phtml'); ?>           
        </div><!-- accordion -->
    </div>
</div>


<script type="text/html" id="mentor-empty">
<!--
<tr class="match mentor-match" >
    <td colspan='7'>
       <div class="pull-left">
          <?php _e ('No matches available', 'bidxplugin') ?>
       </div>
    </td>
</tr>
-->
</script>
