<!-- Help -->
<div class="entrepreneur-mentordashboard">
    <div class="panel panel-default panel-open">
        <div class="panel-heading">
            <a class="btn-block" data-toggle="collapse" data-parent="#entrepreneurDashboardAccordion" href="#entrepreneurDashboardAccordion-Respond"><span class="fa fa-chevron-right accordion-state-icon"></span> <?php _e ("Entrepreneur's mentoring activities", 'bidxplugin') ?></a>
        </div>
        <div id="entrepreneurDashboardAccordion-Respond" class="panel-collapse collapse in">
            <div class="panel-body">
                <h3><?php _e ('Respond to a mentoring request', 'bidxplugin') ?></h3>
                <!-- ********Mentoring Respond Request********* -->
                <table class="table table-striped view viewRespond">
                    <thead>
                        <tr>
                            <th><?php _e ('Mentor', 'bidxplugin') ?></th>
                            <th class="hidden-xs"><?php _e ('Business', 'bidxplugin') ?></th>
                            <th><?php _e ('Status', 'bidxplugin') ?></th>
                            <th class="hidden-xs"><?php _e ('Actions', 'bidxplugin') ?></th>
                        </tr>
                    </thead>
                    <tbody class="respond mentor-respond">

                    </tbody>
                </table>
                <div class="view viewLoadrespond alert alert-info text-center">
                    <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e ('Loading mentoring respond requests...', 'bidxplugin') ?>
                </div>

                <h3><?php _e ('Waiting for a mentoring approval', 'bidxplugin') ?></h3>
                <!-- ********Mentoring Waiting Request********* -->
                <table class="table table-striped view viewWait">
                    <thead>
                        <tr>
                            <th><?php _e ('Mentor', 'bidxplugin') ?></th>
                            <th class="hidden-xs"><?php _e ('Business', 'bidxplugin') ?></th>
                            <th><?php _e ('Status', 'bidxplugin') ?></th>
                            <th class="hidden-xs"><?php _e ('Actions', 'bidxplugin') ?></th>
                        </tr>
                    </thead>
                    <tbody class="wait mentor-wait">

                    </tbody>
                </table>
                <div class="view viewLoadwait alert alert-info text-center">
                    <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e ('Loading mentoring waiting requests...', 'bidxplugin') ?>
                </div>

                <h3><?php _e ('Ongoing mentoring', 'bidxplugin') ?></h3>
                 <!-- ********Mentoring Ongoing Request********* -->
                <table class="table table-striped view viewOngoing">
                    <thead>
                        <tr>
                            <th><?php _e ('Mentor', 'bidxplugin') ?></th>
                            <th class="hidden-xs"><?php _e ('Business', 'bidxplugin') ?></th>
                            <th><?php _e ('Status', 'bidxplugin') ?></th>
                            <th class="hidden-xs"><?php _e ('Actions', 'bidxplugin') ?></th>
                        </tr>
                    </thead>
                    <tbody class="ongoing mentor-ongoing">

                    </tbody>
                </table>
                 <div class="view viewLoadongoing alert alert-info text-center">
                    <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e ('Loading mentoring ongoing requests...', 'bidxplugin') ?>
                </div>

                <!-- ********Mentoring Renew Request*********
                <h3><?php _e ('Renew a mentoring', 'bidxplugin') ?></h3>

                <div class="view viewLoadrenew alert alert-info text-center">
                    <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e ('Loading mentoring renew requests...', 'bidxplugin') ?>
                </div>
                <table class="table table-striped view viewRenew">
                    <thead>
                        <tr>
                            <th><?php _e ('Mentor', 'bidxplugin') ?></th>
                            <th class="hidden-xs"><?php _e ('Business', 'bidxplugin') ?></th>
                            <th><?php _e ('Status', 'bidxplugin') ?></th>
                            <th class="hidden-xs"><?php _e ('Actions', 'bidxplugin') ?></th>
                        </tr>
                    </thead>
                    <tbody class="renew mentor-renew">

                    </tbody>
                </table>

                 <h3><?php _e ('Display the ended mentoring sessions', 'bidxplugin') ?></h3>
                 ********Mentoring Renew Request*********
                <div class="view viewLoadended alert alert-info text-center">
                    <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e ('Loading the ended mentoring sessions...', 'bidxplugin') ?>
                </div>
                <table class="table table-striped view viewEnded">
                    <thead>
                        <tr>
                            <th><?php _e ('Entrepreneur', 'bidxplugin') ?></th>
                            <th class="hidden-xs"><?php _e ('Business', 'bidxplugin') ?></th>
                            <th><?php _e ('Status', 'bidxplugin') ?></th>
                            <th class="hidden-xs"><?php _e ('Actions', 'bidxplugin') ?></th>
                        </tr>
                    </thead>
                    <tbody class="ended mentor-ended">

                    </tbody>
                </table>
                -->
            </div>
        </div>
    </div>
</div>

<script type="text/html" id="entrepreneur-activities">
     <!--
    <tr>
    <td>
      <span class="placeholder creator"><a target = "_blank" href="/member/%creatorId%" >%creator%</a></span>
   </td>
   <td>
      <a data-toggle="collapse" data-target="#%accordion-id%" class="btn-block">
      <span class="placeholder name">%name%</span>
      </a>
   </td>
   <td class="hidden-xs">
      <span class="placeholder status">%status%</span>
   </td>
   <td class="hidden-xs">
      <span class="placeholder actions">%action%</span>
   </td>
</tr>
<tr class="list detail-list" >
   <td colspan="5" class="detailRow">
      <div class="panel-collapse collapse" id="%accordion-id%">
      <div class="row">
            <div class="col-sm-3">
                <span class="placeholder document js-companylogo"><img src="%document%"/></span>
            </div>
        <div class="col-sm-9">
            <div class="row">
                <div class="col-sm-6">
                    <label><?php _e('Business proposal','bidxplugin');?></label>
                    <div class="placeholder name"><a target = "_blank" href="/businesssummary/%entityId%">%name%</a></div>
                </div>
                <div class="col-sm-6">
                     <label><?php _e('Entrepreneur','bidxplugin');?></label>
                     <div class="placeholder creator"><a target = "_blank" href="/member/%creatorId%">%creator%</a></div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <label><?php _e('Industry','bidxplugin');?></label>
                    <div class="placeholder industry">%industry%</div>
                </div>
                <div class="col-sm-6">
                    <label><?php _e('Product','bidxplugin');?></label>
                    <div class="placeholder productService">%productService%</div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <label><?php _e('Country','bidxplugin');?></label>
                    <div class="placeholder countryOperation">%countryOperation%</div>
                </div>
                <div class="col-sm-6">
                    <label><?php _e('Investment needed','bidxplugin');?></label>
                    <div class="placeholder financingNeeded">%financingNeeded%</div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <label><?php _e('Business stage','bidxplugin');?></label>
                    <div class="placeholder stageBusiness">%stageBusiness%</div>
                </div>
                <div class="col-sm-6">
                    <label><?php _e('Environmental Impact','bidxplugin');?></label>
                    <div class="placeholder envImpact">%envImpact%</div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 col-sm-offset-6">
                    <div class="pull-right">
                        <span class="placeholder entityid_l"><a class="btn btn-primary btn-sm" target = "_blank" href="/businesssummary/%entityId%"><?php _e('View Proposal','bidxplugin');?></a> </span>
                    </div>
                </div>
            </div>
         </div>
      </div>
      </div>
   </td>
</tr>
-->
</script>


<script type="text/html" id="entrepreneur-respond-action">
<!--
<a href="#" data-href="<?php echo _l('mentor-dashboard')?>/#mentoring/confirmRequest/entityId=%entityId%&userId=%userId%&type=mentor&action=accepted" class="btn-bidx-accept"><?php _e('Accept','bidxplugin');?></a>|
<a href="#" data-href="<?php echo _l('mentor-dashboard')?>/#mentoring/confirmRequest/entityId=%entityId%&userId=%userId%&type=mentor&action=rejected" class="btn-bidx-ignore"><?php _e('Ignore','bidxplugin');?></a>|
<a href="#" data-href="<?php echo _l('mail')?>/#mail/compose/recipients=%receipientId%" target="_blank" class="btn-bidx-contact"><?php _e('Contact mentor','bidxplugin');?></a>
-->
</script>
<script type="text/html" id="entrepreneur-wait-action">
<!--
<a href="#" data-href="<?php echo _l('mail')?>/#mail/compose/recipients=%receipientId%" class="btn-bidx-reminder"><?php _e('Send a reminder','bidxplugin');?></a>|
<a href="#" data-href="<?php echo _l('mail')?>/#mail/compose/recipients=%receipientId%" target="_blank" class="btn-bidx-contact"><?php _e('Contact mentor','bidxplugin');?></a>|
<a href="#" data-href="<?php echo _l('mentor-dashboard')?>/#mentoring/confirmRequest/entityId=%entityId%&userId=%userId%&type=mentor&action=cancel" class="btn-bidx-cancel"><?php _e('Cancel request','bidxplugin');?></a>
-->
</script>
<script type="text/html" id="entrepreneur-ongoing-action">
<!--
<a href="#" data-href="<?php echo _l('mentor-dashboard')?>/#mentoring/addFeedback/entityId=%entityId%&commentorId=%commentorId%" class="btn-bidx-add-feedback"><?php _e('Add feedback','bidxplugin');?></a>|
<a href="#" data-href="<?php echo _l('mentor-dashboard')?>/#mentoring/viewFeedback/entityId=%entityId%" class="btn-bidx-view-feedback"><?php _e('View feedback','bidxplugin');?></a>|
<a href="#" data-href="<?php echo _l('mail')?>/#mail/compose/recipients=%receipientId%" target="_blank" class="btn-bidx-contact"><?php _e('Contact mentor','bidxplugin');?></a>|
<a href="#" data-href="<?php echo _l('mentor-dashboard')?>/#mentoring/confirmRequest/entityId=%entityId%&userId=%userId%&type=mentor&action=cancel" class="btn-bidx-stop"><?php _e('Stop mentoring','bidxplugin');?></a>
-->
</script>
<script type="text/html" id="entrepreneur-renew-action">
<!--
<a href="#" data-href="<?php echo _l('mentor-dashboard')?>/#mentoring/viewFeedback/entityId=%entityId%" class="btn-bidx-view-feedback"><?php _e('View feedback','bidxplugin');?></a>|
<a href="#" data-href="<?php echo _l('mail')?>/#mail/compose/recipients=%receipientId%" target="_blank" class="btn-bidx-contact"><?php _e('Contact mentor','bidxplugin');?></a>|
<a href="#" data-href="<?php echo _l('mentor-dashboard')?>/#mentoring/confirmRequest/" class="btn-bidx-renew"><?php _e('Renew request','bidxplugin');?></a>|
<a href="#" data-href="<?php echo _l('mentor-dashboard')?>/#mentoring/confirmRequest/entityId=%entityId%&userId=%userId%&type=mentor&action=cancel" class="btn-bidx-stop"><?php _e('Stop mentoring','bidxplugin');?></a>
-->
</script>
<script type="text/html" id="entrepreneur-ended-action">
<!--
<a href="#" data-href="<?php echo _l('mentor-dashboard')?>/#mentoring/viewFeedback/entityId=%entityId%" class="btn-bidx-view-feedback"><?php _e('View feedback','bidxplugin');?></a>|
<a href="#" data-href="<?php echo _l('mail')?>/#mail/compose/recipients=%receipientId%" target="_blank" class="btn-bidx-contact"><?php _e('Contact mentor','bidxplugin');?></a>|
<a href="#" data-href="<?php echo _l('mentor-dashboard')?>/#mentoring/confirmRequest/" class="btn-bidx-delete"><?php _e('Delete from dashboard','bidxplugin');?></a>
-->
</script>
