<!-- Help -->
<div class="entrepreneur-mentordashboard">
    <div class="respond mentor-respond"></div>
    <!-- ********Mentoring Respond Request********* -->
    <div class="view viewLoadrespond alert alert-info text-center">
        <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e ('Loading', 'bidxplugin') ?>
    </div>

    <div class="wait mentor-wait"></div>
    <div class="view viewLoadwait alert alert-info text-center">
        <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e ('Loading', 'bidxplugin') ?>
    </div>

    <div class="ongoing mentor-ongoing"></div>
    <div class="view viewLoadongoing alert alert-info text-center">
        <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e ('Loading', 'bidxplugin') ?>
    </div>
</div>

<script type="text/html" id="entrepreneur-activities">
     <!--
    <div class="cardView">
        <div class="cardHeader hide-overflow">
            <div class="info-cell pull-left bg-%status%"><?php echo _e( 'Status', 'bidxplugin' ); ?>: %status%</div>
            <div class="info-cell pull-left"><?php echo _e( 'Finance Needed', 'bidxplugin' ); ?>: %financingNeeded%</div>
            <a href="/businesssummary/%entityId%" class="btn btn-primary btn-xs pull-right info-action main-margin-half"><?php echo _e( 'View Business', 'bidxplugin' ); ?> </a>
        </div>
        <div class="cardContent main-padding">
            <div class="cardTop">
                <div class="row">
                    <div class="col-sm-3">
                        <a class="pull-left main-margin-half" href="/businesssummary/%entityId%" data-role='businessImage'>
                            <div class="icons-rounded"><i class="fa fa-suitcase text-primary-light"></i></div>
                        </a>
                    </div>
                    <div class="col-sm-9">
                        <h3 class="top-0">%name%</h3>
                        <h4><span class="bs-slogan">%slogan%</span></h4>
                        <table class="table table-condensed table-bottom-border">
                            <tbody>
                                <tr><td>Business stage</td><td>%stageBusiness%</td></tr>
                                <tr><td>Year sales started</td><td>%yearSalesStarted%</td></tr>
                                <tr><td>Industry</td><td>%industry%</td></tr>
                                <tr><td>Country of business</td><td>%countryOperation%</td></tr>
                            </tbody>
                        </table>                    
                    </div>
                </div>
            </div>
        </div>
        <div class="cardFooter">
            <div class="alert bg-%status% hide-overflow">
            <div class="pull-left">
                %statusMessage% <a href="/member/%creatorId%">%creator%</a>
            </div>
            <div class="pull-right actions">%action%</div>
            </div>
        </div>
    </div>
-->
</script>


<script type="text/html" id="entrepreneur-respond-action">
<!--
<a href="#" data-href="<?php echo _l('mentor-dashboard')?>/#mentoring/confirmRequest/requestId=%requestId%&type=mentor&action=accepted" class="btn-bidx-accept btn btn-xs btn-success"><?php _e('Accept','bidxplugin');?></a>
<a href="#" data-href="<?php echo _l('mentor-dashboard')?>/#mentoring/confirmRequest/requestId=%requestId%&type=mentor&action=rejected" class="btn-bidx-ignore btn btn-xs btn-danger"><?php _e('Ignore','bidxplugin');?></a>
<a href="#" data-href="<?php echo _l('mail')?>/#mail/compose/recipients=%receipientId%" target="_blank" class="btn-bidx-contact hide btn btn-xs btn-info"><?php _e('Contact mentor','bidxplugin');?></a>
-->
</script>
<script type="text/html" id="entrepreneur-wait-action">
<!--
<a href="#" data-href="<?php echo _l('mail')?>/#mail/compose/recipients=%receipientId%" class="btn-bidx-reminder btn btn-xs btn-primary"><?php _e('Send a reminder','bidxplugin');?></a>
<a href="#" data-href="<?php echo _l('mail')?>/#mail/compose/recipients=%receipientId%" target="_blank" class="btn-bidx-contact hide btn btn-xs btn-info"><?php _e('Contact mentor','bidxplugin');?></a>
<a href="#" data-href="<?php echo _l('mentor-dashboard')?>/#mentoring/confirmRequest/requestId=%requestId%&type=mentor&action=cancel" class="btn-bidx-cancel btn btn-xs btn-danger"><?php _e('Cancel request','bidxplugin');?></a>
-->
</script>
<!--  TODO Arjan TODO Sakis see comment in mentor-mentoring.phtml (as for data-visibility, data-hidevisiblities and enabling data-setcount) -->
<script type="text/html" id="entrepreneur-ongoing-action">
<!--
<a href="#" data-href="<?php echo _l('mail')?>/#mail/compose/recipients=%receipientId%" target="_blank" class="btn-bidx-contact hide btn btn-xs btn-info"><?php _e('Contact mentor','bidxplugin');?></a>
<a href="#" data-href="<?php echo _l('mentor-dashboard')?>/#mentoring/confirmRequest/requestId=%requestId%&type=mentor&action=cancel" class="btn-bidx-stop btn btn-xs btn-danger"><?php _e('Stop mentoring','bidxplugin');?></a>
-->
</script>
<script type="text/html" id="entrepreneur-renew-action">
<!--
<a href="#" data-href="<?php echo _l('mail')?>/#mail/compose/recipients=%receipientId%" target="_blank" class="btn-bidx-contact hide btn btn-xs btn-info"><?php _e('Contact mentor','bidxplugin');?></a>
<a href="#" data-href="<?php echo _l('mentor-dashboard')?>/#mentoring/confirmRequest/" class="btn-bidx-renew btn btn-xs btn-primary"><?php _e('Renew request','bidxplugin');?></a>
<a href="#" data-href="<?php echo _l('mentor-dashboard')?>/#mentoring/confirmRequest/entityId=%entityId%&type=mentor&action=cancel" class="btn-bidx-stop btn btn-xs btn-danger"><?php _e('Stop mentoring','bidxplugin');?></a>
-->
</script>
<script type="text/html" id="entrepreneur-ended-action">
<!--
<a href="#" data-href="<?php echo _l('mail')?>/#mail/compose/recipients=%receipientId%" target="_blank" class="btn-bidx-contact hide btn btn-xs btn-info"><?php _e('Contact mentor','bidxplugin');?></a>
<a href="#" data-href="<?php echo _l('mentor-dashboard')?>/#mentoring/confirmRequest/" class="btn-bidx-delete btn btn-xs btn-danger"><?php _e('Delete from dashboard','bidxplugin');?></a>
-->
</script>
