<!-- Help -->
<div class="view viewLoadrequest alert alert-info text-center">
    <div class="progress progress-striped active">
        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
            <?php _e ('Loading (Sending your request)...', 'bidxplugin') ?>
        </div>
    </div>
</div>

<div class="panel panel-default panel-open">
    <div class="panel-heading">
        <a class="btn-block" data-toggle="collapse" data-parent="#mentorDashboardAccordion" href="#mentorDashboardAccordion-Respond"><span class="fa fa-chevron-right accordion-state-icon"></span> Respond to mentoring request</a>
    </div>
    <div id="mentorDashboardAccordion-Respond" class="panel-collapse collapse in">
        <div class="panel-body">        
            <!-- ********Mentoring Respond Request********* -->
            <div class="view viewLoadrespond alert alert-info text-center">
                <div class="progress progress-striped active">
                    <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                        <?php _e ('Loading mentoring respond requests...', 'bidxplugin') ?>
                    </div>
                </div>
            </div>
            <table class="table table-striped view viewRespond">
                <thead>
                    <tr>
                        <th class="hidden-xs">Business</th>
                        <th>Entrepreneur</th>
                        <th>Status</th>
                        <th class="hidden-xs">Actions</th>
                    </tr>
                </thead>
                <tbody class="respond mentor-respond">

                </tbody>
            </table>            
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <a class="btn-block" data-toggle="collapse" data-parent="#mentorDashboardAccordion" href="#mentorDashboardAccordion-Wait"><span class="fa fa-chevron-right accordion-state-icon"></span> Waiting a mentoring approval </a>
    </div>
    <div id="mentorDashboardAccordion-Wait" class="panel-collapse collapse">
        <div class="panel-body">
            <!-- ********Mentoring Waiting Request********* -->
            <div class="view viewLoadwait alert alert-info text-center">
                <div class="progress progress-striped active">
                    <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                        <?php _e ('Loading mentoring waiting requests...', 'bidxplugin') ?>
                    </div>
                </div>
            </div>
            <table class="table table-striped view viewWait">
                <thead>
                    <tr>
                        <th class="hidden-xs">Business</th>
                        <th>Entrepreneur</th>
                        <th>Status</th>
                        <th class="hidden-xs">Actions</th>
                    </tr>
                </thead>
                <tbody class="wait mentor-wait">

                </tbody>
            </table>            
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <a class="btn-block" data-toggle="collapse" data-parent="#mentorDashboardAccordion" href="#mentorDashboardAccordion-Ongoing"><span class="fa fa-chevron-right accordion-state-icon"></span> Ongoing mentoring </a>
    </div>
    <div id="mentorDashboardAccordion-Ongoing" class="panel-collapse collapse">
        <div class="panel-body">
            <!-- ********Mentoring Ongoing Request********* -->
            <div class="view viewLoadongoing alert alert-info text-center">
                <div class="progress progress-striped active">
                    <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                        <?php _e ('Loading mentoring ongoing requests...', 'bidxplugin') ?>
                    </div>
                </div>
            </div>
            <table class="table table-striped view viewOngoing">
                <thead>
                    <tr>
                        <th class="hidden-xs">Business</th>
                        <th>Entrepreneur</th>
                        <th>Status</th>
                        <th class="hidden-xs">Actions</th>
                    </tr>
                </thead>
                <tbody class="ongoing mentor-ongoing">

                </tbody>
            </table>       
        </div>
    </div>
</div>
    


    