<div id="mentor-dashboard">

    <h1 class="pagetitle"><?php _e('My mentor dashboard','bidxplugin');?></h1>
    <div class="dashboard">

        <div class="view viewError alert alert-warning">
            <h1><?php _e('Error','bidxplugin')?></h1>
            <span class="errorMsg"></span>
        </div>

        <div class="modalView modalConfirmRequest">
            <!-- Modal -->
            <div class="modal fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                     <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h3 id="myModalLabel"><?php _e ('Send request','bidxplugin') ?></h3>
                        </div>
                        <div class="modal-body">
                            %message%
                        </div>
                        <div class="modal-footer">
                            <a class="btn" href="#mentoring/mentor/"><?php _e ('Cancel','bidxplugin') ?></a>
                            <a href="#" class="btn btn-primary btn-request" data-href="#mentoring/sendRequest/" ><?php _e ('Send request','bidxplugin') ?></a>
                        </div>
                     </div>
                </div>
            </div>
        </div>
        <!-- Modal -->
        <div class="modalView modalConfirmFeedback">
            <div class="modal fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="feedbackLabel" aria-hidden="true">
                <div class="modal-dialog">
                     <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h3 id="feedbackLabel"><?php _e ('Add feedback','bidxplugin') ?></h3>
                        </div>
                        <div class="modal-body">
                            <p>
                                <?php _e ('You are about to add the feedback. Are you sure?','bidxplugin') ?>
                            </p>
                        </div>
                        <div class="modal-footer">
                            <a href="#" class="btn btn-cancel btn-cancel-feedback" data-href="#mentoring/addFeedback/"><?php _e ('Change feedback','bidxplugin') ?></a>
                            <a href="#" class="btn btn-primary btn-send-feedback" data-href="#mentoring/sendFeedback/" ><?php _e ('Add feedback','bidxplugin') ?></a>
                        </div>
                     </div>
                </div>
            </div>
        </div>
        <!-- View feedback modal -->
        <div class="modalView modalListFeedback">
            <div class="modal fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="feedbackLabel" aria-hidden="true">
                <div class="modal-dialog">
                     <div class="modal-content">
                        <div class="modal-header">
                            <a  class="close" href="#mentoring/cancel">×</a>
                            <h3 id="feedbackLabel"><?php _e ('View feedback','bidxplugin') ?></h3>
                        </div>
                        <div class="modal-body well">
                            <form action="">
                                <!-- MESSAGE LIST -->
                                <ul class="list media-list ">
                                    <li class="media">
                                        <div class="pull-left">
                                            <?php _e('Loading...','bidxplugin')?>
                                        </div>
                                    </li>
                                </ul>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <a href="#mentoring/cancel" class="btn btn-view-feedback" href=""><?php _e ('Close','bidxplugin') ?></a>
                            <a href="#" data-href="#mentoring/addFeedback/" class="btn btn-primary btn-feedback-submit">Add feedback</a>
                        </div>
                     </div>
                </div>
            </div>
        </div>
        <!-- Modal -->
        <div class="modalView modalSendFeedback">
            <div class="modal fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                     <div class="modal-content">
                        <div class="modal-header">
                            <a class="btn btnRequestCancel pull-right" href="#mentoring/cancel">
                                <button type="button" class="close">×</button>
                            </a>
                            <h3 id="myModalLabel"><?php _e ('Send feedback','bidxplugin') ?></h3>
                        </div>
                        <div class="modal-body">
                            <form class="frmsendFeedback">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="form-group">
                                            <label><?php _e('Feedback purpose','bidxplugin'); ?></label>
                                             <select class= "chosen-feedback" name="feedbackpurpose" multiple></select>
                                        </div>
                                        <div class="form-group">
                                            <label><?php _e('Feedback','bidxplugin'); ?></label>
                                            <textarea name="feedback" class="form-control" placeholder="<?php _e('Please write your feedback','bidxplugin');?>" ></textarea>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <a class="btn btn-feedback-cancel" href="#mentoring/cancel"><?php _e ('Cancel','bidxplugin') ?></a>
                            <a class="btn btn-primary btn-feedback-submit"  ><?php _e ('Add feedback','bidxplugin') ?></a> <!-- data-href="#mentoringRequest/sendRequest/" -->
                        </div>
                     </div>
                </div>
            </div>
        </div>
        <div class="view viewLoadrequest alert alert-info text-center">
            <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e ('Loading (Sending your request)...', 'bidxplugin') ?>
        </div>
        <div id="mentorDashboardAccordion">
            <!-- Help -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a class="btn-block" data-toggle="collapse" data-parent="#mentorDashboardAccordion" href="#mentorDashboardAccordion-Help"><span class="fa fa-chevron-right accordion-state-icon"></span> <?php _e('Help','bidxplugin'); ?></a>
                </div>
                <div id="mentorDashboardAccordion-Help" class="panel-collapse collapse">
                    <div class="panel-body">
                       <?php $this->render('dashboard/help.phtml'); ?>
                    </div>
                 </div>
            </div>
              <?php ($this->isMentor)       ? $this->render('dashboard/mentor-mentoring.phtml')       : '' ?>
              <?php ($this->isEntrpreneur)  ? $this->render('dashboard/entrepreneur-mentoring.phtml') : '' ?>
              <?php ($this->isGroupOwner)   ? $this->render('dashboard/groupowner-mentoring.phtml')   : '' ?>
        </div><!-- accordion -->
    </div>
</div>


<script type="text/html" id="mentor-empty">
<!--
<tr class="match mentor-match" >
    <td colspan='7'>
       <div class="pull-left">
          <?php _e ('No matches available', 'bidxplugin') ?>
       </div>
    </td>
</tr>
-->
</script>

<script type="text/html" id="mentor-request-txt">
<!--
<p>
    <?php _e ('You are about to %action% the request. Are you sure?','bidxplugin') ?>
</p>
-->
</script>

<script type="text/html" id="feedback-listitem">
<!--
<div class="panel panel-default">
    <div class="panel-heading" data-toggle="collapse" data-target="#feedback-%accordion-id%">
         <div class="col-sm-12"><?php _e('Posted on','bidxplugin');?> <strong>%dateSent%-%timeSent%</strong> <?php _e('by','bidxplugin');?> <strong>%senderReceiverName%</strong>
         </div>
    </div>
    <div class="panel-body panel-collapse collapse in" id="feedback-%accordion-id%">
       <span>%comment%</span>
    </div>
</div>
-->
</script>
<script type="text/html" id="feedback-empty">
<!--
<li class="media">
    <div class="pull-left check"></div>
    <div class="">
        <?php _e('No messages available','bidxplugin')?>
    </div>
</li>
-->
</script>
