<div id="mentor-dashboard">
    <?php

    // TODO Arjan TODO Altaf typo in $this->isEntrpreneur ?
    if($this->isMentor || $this->isEntrpreneur || $this->isGroupOwner)
    { ?>
        <h1 class="pagetitle"><?php _e('My mentor dashboard','bidxplugin');?></h1>
    <?php }
    ?>

    <div class="dashboard">
        <?php
        if( !$this->isBuisnessSummary )
        {
        ?>
        <div class="view viewMainsuccess alert alert-success">
                <p class="successMsg"></p>
        </div>

        <div class="view viewError alert alert-warning">
            <h1><?php _e('Error','bidxplugin')?></h1>
            <span class="errorMsg"></span>
        </div>
        <?php
        } ?>
        <div class="modalView modalConfirmRequest">
            <!-- Modal -->
            <div class="modal fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                     <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h3 id="myModalLabel"><?php _e ('Send request','bidxplugin') ?></h3>
                        </div>
                        <div class="modal-body">
                            %message%
                        </div>
                        <div class="modal-footer">
                            <a class="btn btn-request-cancel" href="#mentoring/cancel/"><?php _e ('Cancel','bidxplugin') ?></a>
                            <a href="#" class="btn btn-primary btn-request" data-href="#mentoring/sendRequest/" ><?php _e ('Send request','bidxplugin') ?></a>
                        </div>
                     </div>
                </div>
            </div>
        </div>
        <!-- Modal -->
        <div class="view viewLoadrequest alert alert-info text-center">
            <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e ('Loading (Sending your request)...', 'bidxplugin') ?>
        </div>
        <div id="mentorDashboardAccordion">
            <!-- Help
            <div class="panel panel-default">

                <div class="panel-heading">
                    <a class="btn-block" data-toggle="collapse" data-parent="#mentorDashboardAccordion" href="#mentorDashboardAccordion-Help"><span class="fa fa-chevron-right accordion-state-icon"></span> <?php //_e('Help','bidxplugin'); ?></a>
                </div>
                <div id="mentorDashboardAccordion-Help" class="panel-collapse collapse">
                    <div class="panel-body">
                       <?php //$this->render('dashboard/help.phtml'); ?>
                    </div>
                </div>
            </div> -->
              <?php ($this->isMentor)       ? $this->render('dashboard/mentor-mentoring.phtml')       : '' ?>
              <?php ($this->isEntrpreneur)  ? $this->render('dashboard/entrepreneur-mentoring.phtml') : '' ?>
              <?php ($this->isGroupOwner)   ? $this->render('dashboard/groupowner-mentoring.phtml')   : '' ?>
        </div><!-- accordion -->
    </div>
</div>


<script type="text/html" id="mentor-empty">
<!--
<tr class="match mentor-match" >
    <td colspan='7'>
       <div class="pull-left">
          <?php _e ('No matches available', 'bidxplugin') ?>
       </div>
    </td>
</tr>
-->
</script>

