<div id="mail" class="mainState mainStateMail">
    <h1>Your mailbox</h1>
    <div class="row-fluid">
        <!-- Left menu -->
        <div class="span2 side-menu well">
            <div>
                <a class="btn btn-large btn-block btn-info bidx-theme-colour-one" href="#mail/compose"><?php _e('Compose','bidxplugin')?></a>
            </div>
            <div class="bidx-menuitems">
                <div class="bidx-mailFolders">
                    <!-- menu items will be created by app -->
                </div>
                <div class="bidx-contacts">
                    <a class="btn btn-large btn-block" href="#mail/contacts">Contacts</a>
                </div>
            </div>

    <!--         <a class="btn btn-large btn-block" href="#drafts">Drafts</a>
            <a class="btn btn-large btn-block" href="#archived">Archived</a>
            <a class="btn btn-large btn-block" href="#trash">Trash</a> -->
        </div>

        <!-- mail stage: this is the ajax target -->
        <section class="span10 well mail">

            <!-- ************************* utility views *********************************** -->
            <article class="view viewLoad"><?php _e('Loading...','bidxplugin')?></article>

            <article class="view viewError">
                <h1><?php _e('Error','bidxplugin')?></h1>
                <span class="errorMsg"></span>
            </article>

            <article class="view viewUndefined"><h1><?php _e('No view defined for this state','bidxplugin')?></h1></article>


            <!-- ************************* application views *********************************** -->

            <!-- mail listview like mail, sent, drafts, archived or trash -->
            <article class="view viewList">

                <!-- Email searchbox  CURRENTLY NO SEARCH SUPPORTED IN API-->
                <!-- <div class="mail-search text-right">
                    <div class="control-group small">
                        <div class="input-append">
                            <input type="text" placeholder="Search" id="appendedInputButton-01" class="span2">
                            <button type="button" class="btn btn-small"><span class="fui-search"></span></button>
                        </div>
                    </div>
                </div> -->

                <div class="">

                    <!-- TOOLBAR -->
                    <nav class="mail-toolbar bidx-theme-colour-one">
                        <div class="check">
                            <label class="checkbox">
                                <input type="checkbox" data-toggle="checkbox" class="messagesCheckall" value="">
                            </label>
                        </div>
                        <div class="btn-group">
                                <!-- generic folder buttons -->
                                <a class="btn btn-small btn-primary bidx-btn-delete" href="#"><?php _e('Delete','bidxplugin')?></a>
                                <a class="btn btn-small btn-primary bidx-btn-mark-read" href="#"><?php _e('Mark as read','bidxplugin')?></a>
                                <a class="btn btn-small btn-primary bidx-btn-mark-unread" href="#"><?php _e('Mark as unread','bidxplugin')?></a>
                                <div class="btn-group btngroup-move-to-folder">
                                    <a class="btn btn-small btn-primary dropdown-toggle bidx-btn-move-to-folder" data-toggle="dropdown" href="#">
                                        <?php _e('Move message to folder','bidxplugin')?>
                                        <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu">
                                    <!-- dropdown menu links -->
                                    </ul>
                                </div>

                                <!-- trash only buttons -->
                                <a class="btn btn-small btn-primary bidx-btn-empty-trash-confirm" href="/mail/#mail/empty-trash-confirm"><?php _e('Empty trash','bidxplugin')?></a>
                        </div>
                        <div class="pull-right">
                            <a class="btn btn-small btn-primary bidx-btn-mail-prev" href="#"><?php _e('< Newer', 'bidxplugin')?></a>
                            <a class="btn btn-small btn-primary bidx-btn-mail-next" href="#"><?php _e('Older >', 'bidxplugin')?></a>
                        </div>
                    </nav>
                    <form action="">

                    <!-- MESSAGE LIST -->
                    <ul class="list media-list ">
                        <li class="media">
                            <div class="pull-left check"></div>
                            <div class="pull-left">
                                <?php _e('Loading...','bidxplugin')?>
                            </div>
                        </li>

                    </ul>
                    </form>
                </div>
            </article>

            <!-- read view -->
            <article class="view viewRead">
                  <!-- TOOLBAR -->
                <nav class="mail-toolbar bidx-theme-colour-one">
                    <div class="btn-group">
                        <a class="btn btn-small btn-primary btn-reply" href="#" data-href="/mail/#mail/%state%/action=reply&id=%id%"><?php _e('Reply','bidxplugin')?></a>
                        <a class="btn btn-small btn-primary btn-forward" href="#" data-href="/mail/#mail/%state%/action=forward&id=%id%"><?php _e('Forward','bidxplugin')?></a>
                        <a class="btn btn-small btn-primary bidx-btn-delete" href="#"><?php _e('Delete','bidxplugin')?></a>
                        <div class="btn-group btngroup-move-to-folder">
                            <a class="btn btn-small btn-primary btn-move-to-folder dropdown-toggle bidx-btn-move-to-folder" data-toggle="dropdown" href="#">
                                <?php _e('Move message to folder','bidxplugin')?>
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- dropdown menu links -->
                            </ul>
                      </div>
                    </div>
                </nav>

                <div class="row-fluid">
                    <div class="span12 mail-subject"></div>
                </div>
                <div class="row-fluid">
                    <div class="span12 mail-message">
                        <?php _e('Loading...','bidxplugin')?>
                    </div>
                </div>


            </article>


            <!-- Compose view -->
            <article class="view viewCompose">
                <form action="">

                    <h2>
                        <span class="title titleCompose"><?php _e('Create a new e-mail','bidxplugin')?></span>
                        <span class="title titleReply"><?php _e('Reply to message','bidxplugin')?></span>
                        <span class="title titleForward"><?php _e('Forward message','bidxplugin')?></span>
                    </h2>

                    <div class="row-fluid">
                        <div class="control-group">

                            <label class="control-label"><?php _e('Recipient','bidxplugin'); ?></label>
                            <div class="controls">
                                <div class="bidx-tagsinput-container">
                                    <input type="text" name="contacts" class="bidx-tagsinput enclosed defer" autocomplete="off" data-bidxdataservice="mail.getMembers" placeholder="<?php _e('Add Recipient','bidxplugin')?>">
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="control-group">
                            <label class="control-label"><?php _e('Subject','bidxplugin'); ?></label>
                            <div class="controls">
                                <input type="text" name="subject" placeholder="<?php _e('Your subject goes here','bidxplugin')?>">
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="control-group">
                            <label class="control-label"><?php _e('Message','bidxplugin'); ?></label>
                            <div class="controls">
                                <textarea name="content" placeholder="<?php _e('Please type your message here','bidxplugin')?>"></textarea>
                            </div>
                        </div>

                    </div>
                    <div class="pull-left">
                        <button type="submit" class="btn bidx-default-button compose-submit"><?php _e('Send message','bidxplugin')?></button>

                    </div>
                    <div class="pull-right">
                        <a href="/mail/#mail/discardConfirm" class="btn bidx-default-button compose-cancel">
                            <?php _e('Discard message')?>
                        </a>

                    </div>

                </form>
            </article>

              <!-- contacts view -->
            <article class="view viewContacts">

                <div class="toast-wrapper"></div>

                <h3>Contacts </h3>
                <!-- Accordion -->
                <div class="accordion" id="contacts">
                    <div class="accordion-group">
                        <div class="accordion-heading">
                            <a class="accordion-toggle trigger-incoming-contacts" data-toggle="collapse" data-parent="#contacts" href="#incomingRequests">
                                <?php _e('Incoming contact requests (0)')?>
                            </a>
                        </div>

                        <!-- RECEIVED CONTACT REQUESTS -->
                        <div id="incomingRequests" class="accordion-body collapse">
                            <div class="accordion-inner">
                                <ul class="contact-request-list span6-layout unstyled clearfix">
                                </ul>
                                <div class="text-center">
                                    <a class="btn bidx-default-button bidx-btn-showMore" href="showMore=incoming"><?php _e('Show more', 'bidxplugin')?></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- SEND REQUESTS -->
                    <div class="accordion-group">
                        <div class="accordion-heading">
                            <a class="accordion-toggle trigger-pending-contacts" data-toggle="collapse" data-parent="#contacts" href="#pendingRequests">
                                <?php _e('Pending contact requests (0)')?>
                            </a>
                        </div>
                        <div id="pendingRequests" class="accordion-body collapse">
                            <div class="accordion-inner">
                                <ul class="contact-request-list span6-layout unstyled clearfix">
                                </ul>
                                <div class="text-center">
                                    <a class="btn bidx-default-button bidx-btn-showMore" href="showMore=pending"><?php _e('Show more', 'bidxplugin')?></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- ACTIVE REQUESTS -->
                    <div class="accordion-group">
                        <div class="accordion-heading">
                            <a class="accordion-toggle trigger-active-contacts" data-toggle="collapse" data-parent="#contacts" href="#activeRequests">
                                <?php _e('Active contact requests (0)')?>
                            </a>
                        </div>
                        <div id="activeRequests" class="accordion-body collapse">
                            <div class="accordion-inner">
                                <ul class="contact-request-list unstyled span4-layout clearfix">
                                </ul>
                                <div class="text-center">
                                    <a class="btn bidx-default-button bidx-btn-showMore" href="showMore=active"><?php _e('Show more', 'bidxplugin')?></a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- IGNORED REQUESTS -->
                    <div class="accordion-group">
                        <div class="accordion-heading">
                            <a class="accordion-toggle trigger-ignored-contacts" data-toggle="collapse" data-parent="#contacts" href="#ignoredRequests">
                                <?php _e('Ignored contact requests (0)')?>
                            </a>
                        </div>
                        <div id="ignoredRequests" class="accordion-body collapse">
                            <div class="accordion-inner">
                                <ul class="contact-request-list span4-layout unstyled clearfix">
                                </ul>
                                <div class="text-center">
                                    <a class="btn bidx-default-button bidx-btn-showMore" href="showMore=ignored"><?php _e('Show more', 'bidxplugin')?></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div> <!-- \\ END Accordion  -->





            </article>

            <!--  ************************** MODAL VIEWS ****************************************** -->
            <article class="modalView modalDeleteConfirm">
                <!-- Modal -->
                <div class="modal hide fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h3 class="bidx-modalLabel"><?php _e('Delete message(s)','bidxplugin')?></h3>
                    </div>
                    <div class="modal-body">
                    <p>
                        <?php _e('You are about to delete this/these message(s). Are you sure?','bidxplugin')?>
                    </p>
                    </div>
                    <div class="modal-footer">
                        <a class="btn" data-dismiss="modal" aria-hidden="true"><?php _e('Close','bidxplugin')?></a>
                        <a class="btn bidx-default-button bidx-btn-confirm" href="#"><?php _e('Delete message(s)','bidxplugin')?></a>

                    </div>
                </div>
            </article>

             <article class="modalView modalDiscardConfirm">
                <!-- Modal -->
                <div class="modal hide fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h3 class="bidx-modalLabel"><?php _e('Discard message')?></h3>
                    </div>
                    <div class="modal-body">
                        <p>
                            <?php _e('You are about to discard this message. Are you sure?')?>
                        </p>
                    </div>

                    <div class="modal-footer">
                        <button class="btn" data-dismiss="modal" aria-hidden="true"><?php _e('Cancel')?></button>
                        <a class="btn bidx-default-button" href="#" data-href="/mail/#mail/inbox"><?php _e('Discard message')?></a>
                    </div>

                </div>
            </article>

            <article class="modalView modalEmptyTrashConfirm">
                <!-- Modal -->
                <div class="modal hide fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h3 class="bidx-modalLabel"><?php _e('Delete message','bidxplugin')?></h3>
                    </div>
                    <div class="modal-body">
                    <p>
                        <?php _e('You are about to empty the trash folder. Are you sure?','bidxplugin')?>
                    </p>
                    </div>
                    <div class="modal-footer">
                        <a class="btn" data-dismiss="modal" aria-hidden="true"><?php _e('Cancel','bidxplugin')?></a>
                        <a class="btn bidx-default-button" href="#" data-href="/mail/#mail/%state%/action=doEmptyTrash"><?php _e('Empty trash','bidxplugin')?></a>

                    </div>
                </div>
            </article>

        </section>

    </div>
</div>

<!-- snippets -->

<script type="text/html" id="mailbox-listitem">
<!--
<li class="media" >
    <div class="pull-left check">
        <label class="checkbox">
            <input type="checkbox" data-toggle="checkbox"  value="" data-id="">
        </label>
    </div>
    <div class="media-body">
        <div class="row-fluid">
            <div class="span10"><h6 class="media-heading"><a href="%readEmailHref%" class="%emailRead%">%sendername%</a></h6></div>
            <div class="span2">%dateSent% %timeSent%</div>
        </div>
        <div class="subject">
            <span>%subject%</span>
        </div>
    </div>
</li>
-->
</script>

<script type="text/html" id="mailbox-empty">
<!--
<li class="media">
    <div class="pull-left check"></div>
    <div class="">
        <?php _e('No messages available','bidxplugin')?>
    </div>
</li>
-->
</script>


<script type="text/html" id="contact-request-incoming">
<!--
    <li class="span6 ">
        <div class="well">
            <div class="row-fluid">
                <div class="span12">
                    <a class="pull-left clearfix" href="#">
                        <img class="media-object" data-src="holder.js/90x90" src="%pictureUrl%">
                    </a>
                    <div>
                        <a href="/member/%contactId%">%contactName%</a>
                    </div>
                </div>
            </div>
            <div class="row-fluid contact-request-buttons">
                <a href="#" class="span6 btn btn-success btn-bidx-accept"><?php _e('Accept','bidxplugin')?></a>
                <a href="#" class="span6 btn btn-danger btn-bidx-ignore"><?php _e('Ignore','bidxplugin')?></a>
            </div>
        </div>
    </li>
-->
</script>

<script type="text/html" id="contact-request-pending">
<!--

    <li class="span6 ">
        <div class="well">
            <div class="row-fluid">
                <div class="span12">
                    <a class="pull-left clearfix" href="/member/%contactId%">
                        <img class="media-object" data-src="holder.js/90x90" src="%pictureUrl%">
                    </a>
                    <div>
                        <span>Contact request sent to</span>
                        <a href="/member/%contactId%"><strong>%contactName%</strong></a>
                    </div>
                </div>
            </div>
            <div class="alert alert-info contact-request-status">
              <strong><?php _e('Request is pending','bidxplugin')?></strong>
            </div>

        </div>
    </li>
-->
</script>

<script type="text/html" id="contact-request-active">
<!--
    <li class="span4 ">
        <div class="well">
            <div class="outer-check">
                <span class="fui-check"></span>
            </div>

            <div class="row-fluid">
                <div class="span12">
                    <a class="pull-left clearfix" href="#">
                        <img class="media-object" data-src="holder.js/90x90" src="%pictureUrl%">
                    </a>
                    <div>

                        <span><a href="/member/%contactId%">%contactName%</a></span>
                        <strong></strong>
                    </div>
                </div>
            </div>

        </div>
    </li>
-->
</script>

<script type="text/html" id="contact-request-ignored">
<!--
    <li class="span4 ">
        <div class="well">
            <div class="outer-check">
                <span class="fui-check"></span>
            </div>

            <div class="row-fluid">
                <div class="span12">
                    <a class="pull-left clearfix" href="#">
                        <img class="media-object" data-src="holder.js/90x90" src="%pictureUrl%">
                    </a>
                    <div>

                        <span><a href="/member/%contactId%">%contactName%</a></span>
                        <strong></strong>
                    </div>
                </div>
            </div>

        </div>
    </li>
-->
</script>

<script type="text/html" id="contacts-empty">
<!--
<li>
    <div class="">
        <?php _e('No contacts available')?>
    </div>
</li>
-->
</script>


<script type="text/html" id="toast-snippet">
<!--
    <div class='alert alert-success hide'>
        <button data-dismiss='alert' class='close fui-cross' type='button'></button>
        <span class="messageContent"></span>
    </div>
-->
</script>