

<h1>Your inbox</h1>

<div id="mail" class="row-fluid">

    <!-- Left menu -->
    <div class="span2 side-menu well">
        <a class="btn btn-large btn-block btn-info" href="#mail/compose">Compose</a>
        <a class="btn btn-large btn-block" href="#mail/inbox">Inbox</a>
        <a class="btn btn-large btn-block" href="#mail/sent">Sent</a>
<!--         <a class="btn btn-large btn-block" href="#drafts">Drafts</a>
        <a class="btn btn-large btn-block" href="#archived">Archived</a>
        <a class="btn btn-large btn-block" href="#trash">Trash</a> -->
    </div>

    <!-- mail stage: this is the ajax target -->
    <section class="span10 well mail">

        <!-- ************************* utility views *********************************** -->
        <article class="view viewLoad">Loading...</article>

        <article class="view viewError">
            <h1>Error</h1>
            <span class="errorMsg"></span>
        </article>

        <article class="view viewUndefined"><h1>No view defined for this state</h1></article>


        <!-- ************************* application views *********************************** -->

        <!-- mail listview like mail, sent, drafts, archived or trash -->
        <article class="view viewList">

            <!-- Email searchbox  CURRENTLY NO SEARCH SUPPORTED IN API-->
            <!-- <div class="mail-search text-right">
                <div class="control-group small">
                    <div class="input-append">
                        <input type="text" placeholder="Search" id="appendedInputButton-01" class="span2">
                        <button type="button" class="btn btn-small"><span class="fui-search"></span></button>
                    </div>
                </div>
            </div> -->

            <div class="">

                <!-- TOOLBAR -->
                <div class="mail-toolbar">
                    <div class="check">
                        <label class="checkbox">
                            <input type="checkbox" data-toggle="checkbox" class="messagesCheckall" value="">
                        </label>
                    </div>
                    <div class="btn-group">.
                        <a class="btn btn-small btn-primary" href="#fakelink">Delete</a>
                        <a class="btn btn-small btn-primary" href="#fakelink">Mark read</a>
                        <a class="btn btn-small btn-primary" href="#fakelink">Mark unread</a>
                    </div>


                </div>

                <!-- MESSAGE LIST -->
                <ul class="list media-list ">
                    <li class="media">
                        <div class="pull-left check"></div>
                        <div class="pull-left">
                            Loading...
                        </div>
                    </li>

                </ul>
                <div class="pagination">
                    <ul>
                        <li class="previous"><a class="fui-arrow-left" href="#fakelink"></a></li>
                        <li class="active"><a href="#fakelink">1</a></li>
                        <li><a href="#fakelink">2</a></li>
                        <li><a href="#fakelink">3</a></li>
                        <li><a href="#fakelink">4</a></li>
                        <li><a href="#fakelink">5</a></li>
                        <li><a href="#fakelink">6</a></li>
                        <li><a href="#fakelink">7</a></li>
                        <li><a href="#fakelink">8</a></li>
                        <li><a href="#fakelink">9</a></li>
                        <li><a href="#fakelink">10</a></li>
                        <li class="next"><a class="fui-arrow-right" href="#fakelink"></a></li>
                    </ul>
                </div>
            </div>
        </article>

        <!-- read view -->
        <article class="view viewRead">
              <!-- TOOLBAR -->
            <div class="mail-toolbar">
                <div class="btn-group">
                    <a class="btn btn-small btn-primary" href="#/mail/#mail/reply/">Reply</a>
                    <!-- <a class="btn btn-small btn-primary" href="#fakelink">Reply All</a> -->
                    <a class="btn btn-small btn-primary" href="/mail/#mail/forward/">Forward</a>
                    <a class="btn btn-small btn-primary" href="/mail/#mail/deleteConfirm/">Delete</a>
<!--                     <a class="btn btn-small btn-primary" href="#fakelink">Report</a> -->
                </div>
            </div>

                <div class="row-fluid">
                    <div class="span12 mail-message">
                        Loading...
                    </div>
                </div>


        </article>


        <!-- Compose view -->
        <article class="view viewCompose">

            <div class="row-fluid">
                <div class="control-group span12">
                    <div class="control-group formfield">
                        <div class="controls">
                            <input type="text" name="contacts" class="bidx-tagsinput" data-bidxdataservice="mail.memberRelationships" placeholder="Recipient">
                        </div>
                    </div>
                </div>
                <div class="row-fluid">
                <div class="control-group span12">
                    <div class="input-prepend ">
                        <span class="add-on">Subject</span>
                        <input id="prependedInput" type="text" placeholder="Add people you want to send a copy">
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12">
                        <textarea></textarea>
                    </div>
                </div>
            </div>
        </article>

        <!--  ************************** MODAL VIEWS ****************************************** -->
        <article class="view viewDeleteConfirm">
            <!-- Modal -->
            <div class="modal hide fade bidx-modal-deleteEmail" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h3 id="myModalLabel">Delete message</h3>
                </div>
                <div class="modal-body">
                <p>
                    You are about to remove this message. Are you sure?
                </p>
                </div>
                <div class="modal-footer">
                    <a class="btn" data-dismiss="modal" aria-hidden="true">Close</a>
                    <a class="btn btn-primary" href="/mail/#mail/delete/">Delete message</a>
                </div>
            </div>
        </article>

    </section>

</div>

<script type="text/html" id="listMessage">
<!--
<li class="media">
    <div class="pull-left check">
        <label class="checkbox">
            <input type="checkbox" data-toggle="checkbox"  value="">
        </label>
    </div>
    <a class="pull-left" href="#">
        <img class="media-object" data-src="holder.js/64x64">
    </a>
    <div class="media-body">
        <div class="row-fluid">
            <div class="span10"><h6 class="media-heading"><span class="placeholder sendername">SENDER UNKNOWN IN API</span></h6></div>
            <div class="span2"><span class="placeholder sentDate"/></div>
        </div>
        <div class="subject">
            <span class="placeholder subject"/>
        </div>
    </div>
</li>
-->
</script>
