<?php
$finalistDisplay   =   '';
$winnerDisplay     =   '';
$winnerCount       =    0;
$finalistCount     =    0;
$snippet        =   "<tr>
                        <td><a href='/businesssummary/%entityId%' target='_blank'>%bidxEntityDisplayName%</a></td>
                        <td> <a href='/member/%bidxOwnerId%'>%bidxOwnerDisplayName%</a> </td>
                        <td> %bidxRatingAverage% </td>
                    </tr>";
$competition    = $this->data;
// d($competition);

$competitionBidxMeta = isset($competition->bidxMeta)
    ? $competition->bidxMeta
    : null;

foreach($competition->applications as $application)
{
    $bidxMeta   =   $application->bidxMeta;

    if( $application->status === 'WINNER')
    {
        $winnerHtml =  str_replace("%entityId%", $application->id , $snippet);
        $winnerHtml =  str_replace("%bidxEntityDisplayName%", $bidxMeta->bidxEntityDisplayName , $winnerHtml);
        $winnerHtml =  str_replace("%bidxOwnerId%", $bidxMeta->bidxOwnerId , $winnerHtml);
        $winnerHtml =  str_replace("%bidxOwnerDisplayName%", $bidxMeta->bidxOwnerDisplayName , $winnerHtml);
        $winnerHtml =  str_replace("%bidxRatingAverage%", round($bidxMeta->bidxRatingAverage,2) , $winnerHtml);

        $winnerDisplay .= $winnerHtml;

        $winnerCount++;

    }

    if( $application->status === 'FINALIST')
    {
        $finalistHtml =  str_replace("%entityId%", $application->id , $snippet);
        $finalistHtml =  str_replace("%bidxEntityDisplayName%", $bidxMeta->bidxEntityDisplayName , $finalistHtml);
        $finalistHtml =  str_replace("%bidxOwnerId%", $bidxMeta->bidxOwnerId , $finalistHtml);
        $finalistHtml =  str_replace("%bidxOwnerDisplayName%", $bidxMeta->bidxOwnerDisplayName , $finalistHtml);
        $finalistHtml =  str_replace("%bidxRatingAverage%", round($bidxMeta->bidxRatingAverage,2) , $finalistHtml);

        $finalistDisplay .= $finalistHtml;

        $finalistCount++;
    }
}



$canEdit        = $this->exst($competitionBidxMeta->bidxCanEdit, false);

$endDateTime    = ( isset( $competition->endDateTime ) ) ? date( 'd M Y H:i', strtotime ( $this->exst( $competition->endDateTime ) ) ) : NULL;

$endTimeStamp   = ( isset( $competition->endDateTime ) ) ? strtotime ( $this->exst( $competition->endDateTime ) )  : NULL;

$competitionId  = $competitionBidxMeta->bidxCompetitionId;

$hasCover       = '';

if ( !(isset($competition->competitionLogo) && isset($competition->competitionLogo->document) ) )
{
    $hasCover = 'hide';

}

?>
<div class="competitionSummary box-border top-margin-lineheight" id="competitionSummary" data-bsid="<?php echo $competitionId; ?>">
    <div class="competitionCover">
        <div class="coverImageContainer <?php echo $hasCover; ?>">
<?php
            if ( $competition->competitionLogo && $competition->competitionLogo->document ) :
?>
            <div class="coverImage">
                <img src="<?php echo $competition->competitionLogo->document ?>" alt="Cover Image" data-initop="<?php echo $competition->competitionLogo->top?>" style="position: relative; top: <?php echo $competition->competitionLogo->top?>px">
            </div>
<?php
            endif;
?>
        </div>
    </div>

    <div class="competition-info hide-overflow text-center">
        <div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
            <div class="row main-padding">
                <div class="col-sm-3">
                    <div class="participants-number"><?php echo $competition->appliedCount;?></div>
                    <div class="participants-state"><?php echo _e( 'Participants', 'bidxplugin' ); ?></div>
                </div>
                <div class="col-sm-3">
                    <div class="participants-number"><?php echo $competition->submittedCount;?></div>
                    <div class="participants-state"><?php echo _e( 'Submitted', 'bidxplugin' ); ?></div>
                </div>
<?php
                 if($competition->withdrawnCount && $canEdit )
                 {
?>
                 <div class="col-sm-3">
                    <div class="participants-number"><?php echo $competition->withdrawnCount;?></div>
                    <div class="participants-state"><?php echo _e( 'Submitted', 'bidxplugin' ); ?></div>
                </div>
<?php
                 }
                 if($competition->rejectedCount && $canEdit )
                 {
?>
                 <div class="col-sm-3">
                    <div class="participants-number"><?php echo $competition->rejectedCount;?></div>
                    <div class="participants-state"><?php echo _e( 'Submitted', 'bidxplugin' ); ?></div>
                </div>
<?php
            }
?>
                <div class="col-sm-3">
                    <div class="participants-number"><?php echo $finalistCount;?></div>
                    <div class="participants-state"><?php echo _e( 'Finalists', 'bidxplugin' ); ?></div>
                </div>
                <div class="col-sm-3">
                    <div class="participants-number"><?php echo $winnerCount;?></div>
                    <div class="participants-state"><?php echo _e( 'Winners', 'bidxplugin' ); ?></div>
                </div>
            </div>
        </div>
    </div>

<?php
    if ( $this->exst($competitionBidxMeta->bidxEntityId) )
    {
?>
    <div class="main-padding bg-info">
        <div class="row view viewShow viewParticipate">
            <div class="col-sm-8 col-sm-offset-2">
                <h4 class="text-center"><?php echo _e( 'Apply before', 'bidxplugin' ); ?>:
                    <strong><?php echo $endDateTime;?></strong>
                </h4>
<?php
                if ( $this->exst($competitionBidxMeta->bidxEntityId) )
                {
?>
                    <div class="counter hide-overflow text-center flat" data-time="<?php echo $endTimeStamp; ?>">
<?php
                        if ( $endTimeStamp < time() )
                        {
?>
                            <div class="alert alert-warning">
                                <strong><i class="fa fa-exclamation-triangle"></i> <?php _e( 'This competition has expired','bidxplugin' ); ?></strong>
                            </div>
                            <a class="btn btn-secondary btn-block" href="/competition"><?php _e( 'Visit our competition overview','bidxplugin' ); ?> </a>
<?php
                        }
                        else
                        {
?>
                            <div class="counter-block">
                                <div class="days counter-number"></div>
                                <div class="counter-text"><?php _e( 'DAYS','bidxplugin' ); ?></div>
                            </div>
                            <div class="counter-block">
                                <div class="hours counter-number"></div>
                                <div class="counter-text"><?php _e( 'HOURS','bidxplugin' ); ?></div>
                            </div>
                            <div class="counter-block">
                                <div class="minutes counter-number"></div>
                                <div class="counter-text"><?php _e( 'MINUTES','bidxplugin' ); ?></div>
                            </div>
                            <div class="counter-block">
                                <div class="seconds counter-number"></div>
                                <div class="counter-text"><?php _e( 'SECONDS','bidxplugin' ); ?></div>
                            </div>
<?php
                        }
?>
                    </div>
<?php
                }
?>
            </div>
        </div>
    </div>
<?php
    }
?>

    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
<?php
            if ( $this->exst($competitionBidxMeta->bidxEntityId) )
            {
?>
                <h1>
                    <?php echo $this->exst( $competition->name ); ?>
                </h1>
<?php
            }
?>
            <div class="competition-description"><?php echo $this->exst( $competition->description ); ?></div>
            <?php
            if($winnerDisplay)
            { ?>
            <div class="viewWinner well">
                <div>
                    <h3><i class="fa fa-trophy fa-big fa-above pull-left"></i>&nbsp;<?php _e( 'WINNERS', 'bidxplugin' ); ?></h3>
                </div>
                <div>
                    <table class="table table-condensed table-bottom-border">
                        <thead>
                        <tr>
                            <th><?php _e('Business','bidxplugin');?></th>
                            <th><?php _e('Entrepreneur','bidxplugin');?></th>
                            <th><?php _e('Score','bidxplugin');?></th>
                        </tr>
                    </thead>
                        <tbody class='winnerDisplay'>
                            <?php echo $winnerDisplay;?>
                        </tbody>
                    </table>
                </div>
            </div>
            <?php
            }
            if($finalistDisplay)
            { ?>
                <div class="viewFinalist">
                    <div>
                        <h3><?php _e( 'FINALISTS', 'bidxplugin' ); ?></h3>
                    </div>
                    <div>
                        <table class="table table-condensed table-bottom-border">
                            <thead>
                            <tr>
                                <th><?php _e('Business','bidxplugin');?></th>
                                <th><?php _e('Entrepreneur','bidxplugin');?></th>
                                <th><?php _e('Score','bidxplugin');?></th>
                            </tr>
                        </thead>
                            <tbody class='finalistDisplay'>
                                <?php echo $finalistDisplay;?>
                            </tbody>
                        </table>
                    </div>
                </div>
            <?php }

            if ( $endTimeStamp > time() )
            {
            ?>
            <div class="row">
                <div class="col-sm-4 col-sm-offset-4 big-padding-vertical">
                    <a href="/join" class="btn btn-lg btn-block btn-secondary"><?php echo _e( 'Participate', 'bidxplugin' ); ?></a>
                </div>
            </div>
            <?php } ?>
        </div>
    </div>

</div>

