<div class="block-odd">
    <div class="pageHeader clearfix">
      <div class="container clearfix">
        <h1><?php echo ucwords( $this->company->name); ?></h1>
        <div class="editControls btn-group"></div>
      </div>
    </div>

    <div class="row-fluid mainState mainStateShow">
      <div class="span12">
        <?php $this->render('view-company.phtml'); ?>
      </div>
    </div>

    <?php $this->render('edit-company.phtml'); ?>
</div>
