<div id="editCompany" class="row-fluid mainState mainStateEditCompany">

    <!-- LOAD -->
    <div class="view viewLoad span12">
        <span>Retrieving company information...</span>
    </div>

    <!-- ERROR -->
    <div class="view viewError span12">
        <h2>Error</h2>
        <p class="errorMsg"></p>
    </div>

    <!-- EDIT -->
    <div class="view viewEdit">

        <form id="frmeditCompany">

            <!-- "id" is actually the memberProfileId, but to not have to rewrite the file upload let's do it like this -->
            <input type="hidden" name="companyProfileId"     />
            <input type="hidden" name="domain"              />

            <fieldset class="well">
                <span class="scrollPositionMarker" id="editCompany/companyDetail"></span>
                <legend>Company detail</legend>

                <div class="row-fluid">
                    <div class="span4">

                        <div class="control-group formfield" data-validation='{"required":{"text":"This field is mandatory"}}'>
                            <label class="control-label">Company name</label>
                            <div class="controls">
                                <input type="text" name="name" placeholder="Please type your company name">
                            </div>
                        </div>

                        <div class="control-group formfield" data-validation='{"typecheck": [{"url":{"text":"Please fill in a valid URL"}}]}'>
                            <label class="control-label">Company website</label>
                            <div class="controls">
                                <input type="text" name="website" placeholder="Please type your website">
                            </div>
                        </div>

                        <input type="hidden" name="statutoryAddress.coordinates"    />

                        <div class="control-group formfield">
                            <label class="control-label">Country</label>
                            <div class="controls">
                                <select name="statutoryAddress.country"></select>
                            </div>
                        </div>

                        <div class="control-group formfield">
                            <label class="control-label">City</label>
                            <div class="controls">
                                <input type="text" name="statutoryAddress.cityTown" placeholder="Please type your city" />
                            </div>
                        </div>

                        <div class="control-group formfield">
                            <label class="control-label">Street</label>
                            <div class="controls">
                                <input type="text" name="statutoryAddress.street" placeholder="Please type your street" />
                            </div>
                        </div>

                        <div class="control-group formfield">
                            <label class="control-label">Street number</label>
                            <div class="controls">
                                <input type="text" name="statutoryAddress.streetNumber" placeholder="Please type your street number" />
                            </div>
                        </div>

                        <div class="control-group formfield">
                            <label class="control-label">Postal code</label>
                            <div class="controls">
                                <input type="text" name="statutoryAddress.postalCode" placeholder="Please type your postcode" />
                            </div>
                        </div>

                        <div class="control-group formfield">
                            <label class="control-label">Neighborhood</label>
                            <div class="controls">
                                <input type="text" name="statutoryAddress.neighborhood" placeholder="Please type your neighborhood" />
                            </div>
                        </div>

                        <div class="currentAddressMap"></div>

                        <div class="control-group formfield">
                            <label class="control-label">Is your company registered?</label>
                            <div class="controls">
                                <label class="radio inline"><input type="radio" value="true"  name="registered" data-toggle="radio"/> Yes</label>
                                <label class="radio inline"><input type="radio" value="false" name="registered" data-toggle="radio"/> No</label>
                            </div>
                        </div>

                        <div class="control-group formfield toggle toggle-registered">
                            <label class="control-label">Date of registration</label>
                            <div class="controls">
                                <input type="text" name="dateCompanyEstab" data-type="date" placeholder="Please type your date of date of registration">
                            </div>
                        </div>

                        <div class="control-group formfield toggle toggle-registered">
                            <label class="control-label">Legal form of business</label>
                            <div class="controls">
                                <input type="text" name="dateCompanyEstab" data-type="date" placeholder="Please type your date of date of registration">
                            </div>
                        </div>

                        <div class="control-group formfield toggle toggle-registered">
                            <label class="control-label">Fiscal number</label>
                            <div class="controls">
                                <input type="text" name="fiscalNumber" placeholder="Please type your fiscal number">
                            </div>
                        </div>

                        <div class="control-group formfield toggle toggle-registered">
                            <label class="control-label">Company registration number</label>
                            <div class="controls">
                                <input type="text" name="registrationNumber" placeholder="Please type your registration number">
                            </div>
                        </div>

                        <div class="control-group formfield">
                            <label class="control-label">Do you have employees?</label>
                            <div class="controls">
                                <label class="radio inline"><input type="radio" value="true"  name="haveEmployees" data-toggle="radio"/> Yes</label>
                                <label class="radio inline"><input type="radio" value="false" name="haveEmployees" data-toggle="radio"/> No</label>
                            </div>
                        </div>

                        <div class="control-group formfield toggle toggle-haveEmployees">
                            <label class="control-label">Number of permanent female employees</label>
                            <div class="controls">
                                <input type="number" name="numPermFemaleEmpl" placeholder="Please type the number of permanent female employees">
                            </div>
                        </div>

                        <div class="control-group formfield toggle toggle-haveEmployees">
                            <label class="control-label">Number of permanent male employees</label>
                            <div class="controls">
                                <input type="number" name="numPermMaleEmpl" placeholder="Please type the number of permanent male employees">
                            </div>
                        </div>

                        <div class="control-group formfield toggle toggle-haveEmployees">
                            <label class="control-label">Number of temporary female employees</label>
                            <div class="controls">
                                <input type="number" name="numTempFemaleEmpl" placeholder="Please type the number of temporary female employees">
                            </div>
                        </div>

                        <div class="control-group formfield toggle toggle-haveEmployees">
                            <label class="control-label">Number of temporary male employees</label>
                            <div class="controls">
                                <input type="number" name="numTempMaleEmpl" placeholder="Please type the number of temporary male employees">
                            </div>
                        </div>
                    </div>

                    <div class="span4">
                        <div class="control-group formfield logo-control">
                            <label class="control-label">Logo</label>
                            <div class="controls">
                                <div class="logoContainer" id="editCompanyLogo"></div>
                                <input type="file" name="fileContent" data-type="fileUpload" data-type-arguments='{"url":"/wp-admin/admin-ajax.php?action=file_upload", "extraValues":[{"name": "uploadtype", "value":"companylogo"}], "addFields":["companyProfileId","domain"], "imageContainer": "#editCompanyLogo"}'/>
                            </div>
                        </div>
                    </div>

                    <div class="span4 countryOperationSpecifics">
                        <div class="accordion">
                        </div>
                        <a href="#addCountryOperationSpecifics" class="btn btn-large btn-block btn-primary">Add country specific operations</a>
                    </div>
                </div>

            </fieldset>

        </form>
    </div>

    <div class="snippets hide">
        <div class="countryOperationSpecificsItem accordion-group">
            <div class="accordion-heading">
                <a class="accordion-toggle " data-toggle="collapse" data-parent=".countryOperationSpecifics" href="#">
                    <h4 class="accordion-title">&nbsp;</h4>
                    <div class="control-buttons">
                        <span class="bidx-expand">+</span>
                        <span class="bidx-collapse">-</span>
                    </div>
                </a>
            </div><!-- accordion-heading -->
            <div id="">
                <div class="accordion-inner">
                    <div class="control-group formfield">
                        <label class="control-label">Country</label>
                        <div class="controls">
                            <select name="country"></select>
                        </div>
                    </div>

                    <div class="control-group formfield">
                        <label class="control-label">Company trade name</label>
                        <div class="controls">
                            <input type="text" name="companyTradeName" placeholder="Please type your company trade name">
                        </div>
                    </div>

                    <div class="control-group formfield">
                        <label class="control-label">Permits licences obtained</label>
                        <div class="controls">
                            <select name="permitsLicencesObtained"></select>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

</div><!-- // row -->
