<?php

$useDataSrc = false;
$picSrc     = $this->exst($this->company->logo->document);

if (!$picSrc) {
    $picSrc     = 'holder.js/100x100/industrial/auto/text:No Image';
    $useDataSrc = true;
}

?>
<div class="well profile-block">

    <div class="btn-group controls">
    <?php if ($this->company->bidxCanEdit) { ?>
        <a class="btn btn-primary" href="#editCompany/<?php echo $this->company->ownerId; ?>">Edit</a>
    <?php } ?>
    </div>

    <h4>Company details</h4>

    <div class="row-fluid">
        <div class="span8">

<?php
    $options = array( 'class_label' => 'bidx-label' );

    echo $this->addRowsWithLabelAdjacent( 'span6', 'span6',
        array( 'Company name' => $this->company->name ), $options );

    echo $this->addRowsWithLabelAdjacent( 'span6', 'span6',
        array( 'Company website' => $this->company->website ), $options );

    if ($this->exst($this->company->registered)) {

        echo $this->addRowsWithLabelAdjacent( 'span6', 'span6',
            array( 'Date of registration' =>   date("d-m-Y", strtotime( $this->company->dateCompanyEstab ))), $options );
        echo $this->addRowsWithLabelAdjacent( 'span6', 'span6',
            array( 'Legal form of business' => $this->exst($this->company->legalFormBusiness)), $options );

        $statutoryAddress = $this->exst($this->company->statutoryAddress);

        $arStatutoryAddress = array();

        if ($this->exst($statutoryAddress->street)) {
            $arStatutoryAddress[] = $statutoryAddress->street;
        }

        if ($this->exst($statutoryAddress->streetNumber)) {
            $arStatutoryAddress[] = $statutoryAddress->streetNumber;
        }

        if ($this->exst($statutoryAddress->postalCode)) {
            $arStatutoryAddress[] = $statutoryAddress->postalCode;
        }

        echo $this->addRowsWithLabelAdjacent( 'span6', 'span6',
            array( 'Statutory address' => implode( ' ', $arStatutoryAddress )), $options );

        $arStatutoryCityCountry = array();

        if ($this->exst($statutoryAddress->cityTown)) {
            $arStatutoryCityCountry[] = $statutoryAddress->cityTown;
        }

        if ($this->exst($statutoryAddress->country)) {
            $arStatutoryCityCountry[] = $statutoryAddress->country;
        }

        echo $this->addRowsWithLabelAdjacent( 'span6', 'span6',
            array( 'Statutory city, country' => implode( ' ', $arStatutoryCityCountry )), $options );

        echo $this->addRowsWithLabelAdjacent( 'span6', 'span6',
            array( 'Fiscal number' => $this->exst($this->company->fiscalNumber)), $options );
        echo $this->addRowsWithLabelAdjacent( 'span6', 'span6',
            array( 'Company registration number' => $this->exst($this->company->registrationNumber)), $options );
    }

    if ($this->exst($this->company->numPermFemaleEmpl) || $this->exst($this->company->numPermMaleEmpl) || $this->exst($this->company->numTempFemaleEmpl) || $this->exst($this->company->numTempMaleEmpl)) {
        echo $this->addRowsWithLabelAdjacent( 'span6', 'span6',
            array( 'Number of permanent female employees' => $this->exst($this->company->numPermFemaleEmpl)), $options );
        echo $this->addRowsWithLabelAdjacent( 'span6', 'span6',
            array( 'Number of permanent male employees' => $this->exst($this->company->numPermMaleEmpl)), $options );
        echo $this->addRowsWithLabelAdjacent( 'span6', 'span6',
            array( 'Number of temporary female employees' => $this->exst($this->company->numTempFemaleEmpl)), $options );
        echo $this->addRowsWithLabelAdjacent( 'span6', 'span6',
            array( 'Number of temporary male employees' => $this->exst($this->company->numTempMaleEmpl)), $options );
    }
?>
        </div>

        <div class="span4">
            <img <?php echo $useDataSrc ? "data-" : "" ?>src="<?php echo $picSrc ?>" class="img-rounded">
        </div>
    </div><!-- row -->
</div><!-- well -->
