<div class="view viewShow top-margin-lineheight bottom-margin-lineheight">
	<div class="row container">
		<div class="col-md-8">
			<h1 class="text-primary-dark expressTitle"><?php _e('Usaha Pintar 50', 'bidxplugin');?> </h1>
			<h3 class="text-copy"><?php _e("Mekars business model is to offer loans to small businesses in Indonesia via a network of entrepreneur agents. These agents will be equipped with mobile devices for loan origination, monitoring and collection. Mekar offers loans to SMEs in the range of Rp. 20 million to Rp 200 million. We offer unsecured loans up to Rp. 100 million, at competitive rates with no hidden costs. In 2016 it will relaunch its crowdfunding platform for institutional lenders.", "bidxplugin");?>
			</h3>
			<a class="btn btn-primary btn-lg center btn-block active btn-participate pull-right" href="#createExpressForm"><?php _e('Participate now','bidxplugin');?> </a>
		</div>
		<div class="col-md-4">
			<img src="/wp-content/plugins/bidx-plugin/apps/expressform/static/img/pintar.png" alt="Cover Image"  width="100%" height="100%" />
		</div>
	</div>
</div>