<div class="view viewShow">
	<div class="row">
		<div class="col-md-3">
			<h1 class="text-center"> <?php _e('Usaha Pintar', 'bidxplugin');?> </h1>
			<img src="/wp-content/plugins/bidx-plugin/apps/expressform/static/img/pintar.png" alt="Cover Image"  width="100%" height="100%" />
		</div>
		<div class="col-md-9">
			<h3>Every Bright Idea Needs Proper Support To Light Up. Find Out How Putera Sampoerna Foundation Supports Emerging Entrepreneurs And How You Can Get Involved, Mekar Entrepreneur Network Enables Bright And Potential Entrepreneurs To Meet With Angel Investors. Through This Platform, Putera Sampoerna Foundation Facilitates Collaboration And Creates New Businesses That Will Open Job Opportunities And Contribute To The National Economy. The Best Reason To Start An Organization Is To Make Meaning - To Create A Product Or Service To Make The World A Better Place.
			</h3>
			<a class="btn btn-primary btn-lg center btn-block active btn-participate pull-right" href="#createExpressForm"><?php _e('Participate now','bidx-plugin');?> </a>
		</div>
	</div>
</div>