<?php
// Render a 'join this group' button in case the current user is not in this group
//
if (property_exists($this -> sessionData, 'data') ) {

    $currentGroup   = $this->exst( $this->sessionData->data->currentGroup );
    $groups         = $this->exst( $this->sessionData->data->groups );

    if ( !empty( $currentGroup ) && !empty( $groups ) && !isset( $groups->$currentGroup )) {
?>
<div class="text-center content-row">
    <a class="btn" href="#joinGroup">Join our group</a>
</div>
<?php
    }
}
?>
