<div>
	<ul class="thumbnails">
	  <li class="span3">
	    <div class="thumbnail" data-link="group/0001">
	      type
	      <img data-src="holder.js/300x200">
	      <h3>Firstname Lastname</h3>
	      <p>Thumbnail caption...</p>
	    </div>
	  </li>
	  <li class="span3">
	    <div class="thumbnail" data-link="group/0002">
	      type
	      <img data-src="holder.js/300x200">
	      <h3>Firstname Lastname</h3>
	      <p>Thumbnail caption...</p>
	    </div>
	  </li>
	   <li class="span3">
	    <div class="thumbnail" data-link="group/0003">
	      type
	      <img data-src="holder.js/300x200">
	      <h3>Firstname Lastname</h3>
	      <p>Thumbnail caption...</p>
	    </div>
	  </li>
	  <li class="span3">
	    <div class="thumbnail" data-link="group/0004">
	      type
	      <img data-src="holder.js/300x200">
	      <h3>Firstname Lastname</h3>
	      <p>Thumbnail caption...</p>
	    </div>
	  </li>
	</ul>			
</div>