<div class="well span4">
	<div class="row-fluid">
		<a class="pull-left" href="#">
    		<img class="media-object" data-src="holder.js/64x64" src="http://placehold.it/100x100">
		</a>
		<div class="media-body">
			<h3>Group name</h3>
			<p>Tagline</p>
		</div>
	</div>
	<div class="row-fluid">
		Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
		Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
	</div>
	<div class="row-fluid">
		<div class="span6">Company name</div>
		<div class="span6"><a href="http://www.companyurl.com/">http://www.companyurl.com/</a></div>

	</div>
	
</div>