<div class="well">
<div class="row-fluid">
	<h3>New members in this group</h3>
</div>
<div class="row-fluid">
<?php
if (is_array($this -> members)) {
	$i = 0;
	foreach ($this -> members as $member) {
?>
	<div class="span4">
		<div class="media member-thumb img-rounded">
		  <a class="pull-left" href="/member/<?php echo $member -> bidxMemberId; ?>">
		  	<?php 
			  	if ( empty( $member -> profilePicture ) ) {
					echo '<img data-src="holder.js/50x50/social/auto/text:None" class="media-object img-rounded" />';
				}
				else {
					echo '<img class="media-object img-rounded" src="' . $member -> profilePicture . '" />';
			  	}
		  	?>
		  </a>
		  <div class="media-body centering">
		    <h5 class="media-heading"><?php echo $member -> firstName . ' ' . $member -> lastName; ?></h5>
			<div><?php $this -> showProperty($member, 'professionalTitle') ?></div>
			<div><?php $this -> showProperty($member, 'country') ?></div>
		  </div>
		</div>
	</div>
	<?php
		$i++ ;
		if ( $i == 3 ) {
	?>
</div>
<div class="row-fluid">		
	<?php
		}
		else if ( $i == 5 ) { break; }
	}
}
?>	
	<div class="span4 ">
		<div class="media member-thumb img-rounded">
			<div class="centering">
			   	<a href="/search" class="btn">Search new members</a>
			</div>
			<div class="centering">   	
				<a href="/member" class="btn">View all</a>
			</div>
		</div>	
	</div>					
</div>
</div>

