<div>
	<div data-link="member/0001">
		Image with text placeholder below
		on click go to resource
	</div>
	<div data-link="member/0001">
		Image with text placeholder below
		on click go to resource
	</div>
	<div data-link="member/0001">
		Image with text placeholder below
		on click go to resource
	</div>
	<div data-link="member/0001">
		Image with text placeholder below
		on click go to resource
	</div>
	<div data-link="member/0001">
		Image with text placeholder below
		on click go to resource
	</div>				
</div>