<?php
	//$members = $this -> members;
?>
<div class="well">
<div class="row-fluid">
	<h3>New members in this group</h3>
</div>
<div class="row-fluid">
<?php
if (is_array($this -> members)) {
	foreach ($this -> members as $member) {
?>
	<div class="span4">
		<div class="media member-thumb">
		  <a class="pull-left" href="/member/<?php echo $member -> bidxMemberId; ?>">
		  	<img class="media-object" data-src="holder.js/100x100" src="<?php 
			  	if ( empty( $member -> profilePicture ) ) {
					echo 'http://placehold.it/100x100&text=No+Image';
				}
				else {
			  		$image = $member -> profilePicture;
			  	}
		  	?>">
		  </a>
		  <div class="media-body centering">
		    <h5 class="media-heading"><?php echo $member -> firstName . ' ' . $member -> lastName; ?></h5>
			<div><?php echo $member -> professionalTitle; ?></div>
			<div><?php echo $member -> industry; ?></div>
			<div><?php echo $member -> country; ?></div>
		  </div>
		</div>
	</div>
	<?php
		$i++ ;
		if ( $i == 3 ) {
	?>
</div>
<div class="row-fluid">		
	<?php
		}
		else if ( $i == 5 ) { break; }
	}
}
?>	
	<div class="span4 ">
		<div class="media member-thumb centering">
		   	<a href="/search" class="btn">Search new members</a>
			<a href="/member" class="btn">View all</a>
		</div>	
	</div>					
</div>
</div>

