<div class="iconbar iconbar-horizontal iconbar-info">
	<ul>
        <li><a href="/member" class="fui-user" alt="Profile"></a></li>
		<li><button class="btn btn-navbar" data-toggle="collapse" data-target="#nav-collapse-main"></button></li>
        <li>
        	<a href="/inbox" class="fui-mail" alt="Inbox">
            	<!-- If messages are available -->
              	<span class="iconbar-unread">1</span>
            </a>
		</li>
<?php
if (property_exists($this -> sessionData, 'data') &&
	false != ($roles = $this -> sessionData -> data -> roles)) {
	if ( in_array( 'GroupAdmin', $roles ) ||
		 in_array( 'GroupOwner', $roles ) ) {
?>
 	<li><a href="/admin" class="fui-cmd" alt="Admin"></a></li>
<?php
	}
}
?>
    	<li>
    		<a href="#" class="dropdown-toggle" data-toggle="dropdown" alt="Personal">
    			<i class="fui-gear"></i>
    		</a>
    		<ul class="dropdown-menu">
<?php
if (property_exists($this -> sessionData, 'data') ) {

    $currentGroup   = $this->exst( $this->sessionData->data->currentGroup );
    $groups         = $this->exst( $this->sessionData->data->groups );
    $showLogout     = true;
    if ( !empty( $currentGroup ) && !empty( $groups ) && !isset( $groups->$currentGroup )) {
?>
                <li><a href="#joinGroup">Join this group</a></li>
<?php
    } else {
?>
				<li><a href="#leaveGroup">Leave this group</a></li>
<?php
    }
}
?>
				<li><a href="#messageOwner">Message to Group owner</a></li>
           <?php if( $showLogout ) { ?>
                     <li> <a href="<?php echo wp_logout_url( home_url() ); ?>" title="Logout">Logout</a>
           <?php } ?>
    		</ul>
    	</li>
	</ul>
</div>
