<ul class="memberInfo pull-right nav nav-pills">
	<li class="dropdown dropdown-hover">
   		<a href="#" class="dropdown-toggle" 
   			data-toggle="dropdown"><?php echo $this -> sessionData -> data -> displayName?></a> 
   		<ul class="dropdown-menu">
			<li><a href="/member">Profile</a></li>
<?php
if ( in_array( $this -> sessionData, 'GroupAdmin') && 
	 in_array( $this -> sessionData, 'GroupOwner') ) {
?>		
            <li><a href="/wp-admin">Dashboard</a></li>
<?php
}
?>
			<li><a href="<?php echo wp_logout_url('/'); ?>">Logout</a></li>
   		</ul>
   	</li>
</ul>