<?php
$businessSummary = $this->data;


?>
<div class="span3" id="scrollSummary">
    <ul class="nav nav-list affix" >
        <li class="active"><a href="#businessSummary">Business summary</a></li>
        <li><a href="#aboutBusiness">About the business</a></li>
        <li><a href="#aboutSupporting">About the supporting team</a></li>
    </ul>
</div>

<div class="span9 scrollcontent"  data-target="#scrollSummary" data-spy="scroll" data-offset-top="10px">
    <div id="sectionContent">
        <span id="businessSummary" class="scrollPositionMarker"></span>
        <h3>Business summary</h3>
        <div class="row-fluid">

            <?php
//$rowValues = array('Business summary');
//echo $this->addMultipleRows('span12', $rowValues, NULL, 'h3');
            ?>

            <?php
            $rowValues = array ('Business name' => $businessSummary->name);
            echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'h6', 'class_value' => 'adjacentval'));
            ?>

            <?php
            $rowValues = array ('Describe your business in 15 words' => $businessSummary->summary);
            echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'h6', 'class_value' => 'adjacentval'));
            ?>


            <?php
            $industry = $this->getMultiValues ($businessSummary->industry, ', ');
            $rowValues = array ('Industry' => $industry);
            echo $this->addRowsWithLabelAdjacent ('span6', 'span6', $rowValues, array ('tag_label' => 'h6', 'class_value' => 'adjacentval'));
            ?>

            <?php
            $country = $this->getMultiValues ($businessSummary->countryOperation, ', ', 'country');
            $rowValues = array ('Country of business ' => $country);
            echo $this->addRowsWithLabelAdjacent ('span6', 'span6', $rowValues, array ('tag_label' => 'h6', 'class_value' => 'adjacentval'));
            ?>
        </div>
    </div>
    <div id="sectionContent">
        <span id="aboutBusiness" class="scrollPositionMarker"></span>

        <h3> About the business </h3>
        <div class="row-fluid">
            <?php
//$rowValues = array('About the business');
//echo $this->addMultipleRows('span12', $rowValues, NULL, 'h3');
            ?>

            <?php
            $rowValues = array ('Summary of this business' => $businessSummary->summary);
            echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'h6', 'class_value' => 'adjacentval'));
            ?>

            <?php
            $reasonSubmission = $this->getMultiValues ($businessSummary->reasonForSubmission, ', ');
            $rowValues = array ('Reason for submission of business summary' => $reasonSubmission);
            echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'h6', 'class_value' => 'adjacentval'));
            ?>

            <?php
            $socialImpact = $this->getMultiValues ($businessSummary->socialImpact, ', ');
            $rowValues = array ('Social Impact' => $socialImpact);
            echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'h6', 'class_value' => 'adjacentval'));
            ?>

            <?php
            $rowValues = array ('Percentage equity you currently retain ( optional )' => $businessSummary->equityRetained);
            echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'h6', 'class_value' => 'adjacentval'));
            ?>

            <?php
            $rowValues = array ('Finance needed' => $businessSummary->financingNeeded);
            echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'h6', 'class_value' => 'adjacentval'));
            ?>

            <?php
            $rowValues = array ('Why do you need financing? Describe in maximum 30 words ( optional )' => $businessSummary->summaryFinancingNeeded);
            echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'h6', 'class_value' => 'adjacentval'));
            ?>

            <?php
            // Media/Attachments
            $rowVideoValues = NULL;
            if ($businessSummary->videoPitch->document) {
                //$rowVideoValues[] = $this->embedAudioVideo ($businessSummary->videoPitch->document);
                $rowVideoValues[] = "<a href= '" . $businessSummary->videoPitch->document . "' " . $classValue . " target='_blank' > " . $businessSummary->videoPitch->documentName . " </a>";

            }

            if ($businessSummary->audioPitch->document) {
                //$rowVideoValues[] = $this->embedAudioVideo ($businessSummary->audioPitch->document);
                $rowVideoValues[] = "<a href= '" . $businessSummary->audioPitch->document . "' " . $classValue . " target='_blank' > " . $businessSummary->audioPitch->documentName . " </a>";
            }

            if ($rowVideoValues) {
                $rowVideoAudioHtml = $this->displayAudioVideo ('span6', 'span6', $rowVideoValues, array ());


                $rowValues = array ('Media' => $rowVideoAudioHtml);
                echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'h6', 'class_value' => 'adjacentval'));
            }
            //echo $this->displayAttachments ($header = '<h6>Media<h6>', $businessSummary->attachment);
            ?>
        </div>
    </div>
    <div id="sectionContent">
        <span id="aboutSupporting" class="scrollPositionMarker"></span>
        <h3>About the supporting team</h3>
        <div class="row-fluid">

            <?php
// $rowValues = array('Media');
//echo $this->addMultipleRows('span12', $rowValues, NULL, 'h3');
            ?>

            <?php
            $rowValues = array ('Role of entrepreneur in this business' => $businessSummary->personalRole);
            echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'h6', 'class_value' => 'adjacentval'));
            ?>

            <?php
            $rowValues = array ('Please provide details of your expertise applicable to this business' => $businessSummary->personalExpertise);
            echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'h6', 'class_value' => 'adjacentval'));
            ?>

            <?php
            $supportingData = $businessSummary->personalDetails;
            $header = array ('Name' => 'name', 'Role of partner in this business' => 'role', 'Expertise of partner applicable' => 'expertise');
            $merge['name'] = array ('firstName', 'lastName');
            $supportingMembersHtml = $this->addTableRows ($header, $supportingData, 'table table-bordered', $merge);
  
            $rowValues = array ('Supporting members of management team' => $supportingMembersHtml);
            echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'h5'));
            ?>
        </div>
        <div class = "nextPageBtn">
            <a class="btn btn-large btn-primary btn-embossed mlm" href="#tab2" data-toggle="tab">
                View financial details
                <i class="fui-arrow-right pull-right"></i>
            </a>
        </div>
    </div>
</div>