<?php $businessSummary = $this->data; ?>

<div class="row-fluid">
    <div class="span3">
        <ul class="nav nav-list affix" id="bpSummary-BusinessSummary-Nav">
            <li><a href="#businessSummary">Business summary</a></li>
            <li><a href="#aboutBusiness">About the business</a></li>
            <li><a href="#aboutSupporting">About the supporting team</a></li>
        </ul>
    </div>

    <div class="span9">
        <div class ="well profile-block">
            <span id="businessSummary" class="scrollPositionMarker"></span>
            <h4>Business summary</h4>
            <div class="row-fluid">

                <?php
    //$rowValues = array('Business summary');
    //echo $this->addMultipleRows('span12', $rowValues, NULL, 'h4');
                ?>

                <?php
                $rowValues = array ('Business name' => $this->exst ($businessSummary->name));
                echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'div', 'class_label' => 'bidx-label'));
                ?>

                <?php
                $rowValues = array ('Describe your business in 15 words' => $this->exst ($businessSummary->summary));
                echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'div', 'class_label' => 'bidx-label'));
                ?>

                <?php
                $industry = $this->getMultiValues ($this->exst ($businessSummary->industry), ', ');
                $rowValues = array ('Industry' => $industry);
                echo $this->addRowsWithLabelAdjacent ('span6', 'span6', $rowValues, array ('tag_label' => 'div', 'class_label' => 'bidx-label'));
                ?>

                <?php
                $country = $this->getMultiValues ($this->exst ($businessSummary->countryOperation), ', ', 'country');
                $rowValues = array ('Country of business ' => $country);
                echo $this->addRowsWithLabelAdjacent ('span6', 'span6', $rowValues, array ('tag_label' => 'div', 'class_label' => 'bidx-label'));
                ?>
            </div>
        </div>
        <div class ="well profile-block">
            <span id="aboutBusiness" class="scrollPositionMarker"></span>

            <h4> About the business </h4>
            <div class="row-fluid">
                <?php
    //$rowValues = array('About the business');
    //echo $this->addMultipleRows('span12', $rowValues, NULL, 'h4');
                ?>

                <?php
                $rowValues = array ('Summary of this business' => $this->exst ($businessSummary->summary));
                echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'div', 'class_label' => 'bidx-label'));
                ?>

                <?php
                $reasonSubmission = $this->getMultiValues ($this->exst ($businessSummary->reasonForSubmission), ', ');
                $rowValues = array ('Reason for submission of business summary' => $reasonSubmission);
                echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'div', 'class_label' => 'bidx-label'));
                ?>

                <?php
                $socialImpact = $this->getMultiValues ($this->exst ($businessSummary->socialImpact), ', ');
                $rowValues = array ('Social Impact' => $socialImpact);
                echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'div', 'class_label' => 'bidx-label'));
                ?>

                <?php
                $rowValues = array ('Percentage equity you currently retain ( optional )' => $this->exst ($businessSummary->equityRetained));
                echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'div', 'class_label' => 'bidx-label'));
                ?>

                <?php
                $rowValues = array ('Finance needed' => $this->exst ($businessSummary->financingNeeded));
                echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'div', 'class_label' => 'bidx-label'));
                ?>

                <?php
                $rowValues = array ('Why do you need financing? Describe in maximum 30 words ( optional )' => $this->exst ($businessSummary->summaryFinancingNeeded));
                echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'div', 'class_label' => 'bidx-label'));
                ?>

                <?php
                // Media/Attachments
                $rowVideoValues = NULL;
                $videoPitch = $this->exst ($businessSummary->videoPitch->document);
                $audioPitch = $this->exst ($businessSummary->audioPitch->document);
                if ($videoPitch) {
                    $videoPitchDocName = $this->exst ($businessSummary->videoPitch->documentName);
                    //$rowVideoValues[] = $this->embedAudioVideo ($businessSummary->videoPitch->document);
                    $rowVideoValues[] = "<a href= '" . $videoPitch . "' target='_blank' > " . $videoPitchDocName . " </a>";
                }

                if ($audioPitch) {
                    $audioPitchDocName = $this->exst ($businessSummary->audioPitch->documentName);
                    //$rowVideoValues[] = $this->embedAudioVideo ($businessSummary->audioPitch->document);
                    $rowVideoValues[] = "<a href= '" . $audioPitch . "' target='_blank' > " . $audioPitchDocName . " </a>";
                }

                if ($rowVideoValues) {
                    $rowVideoAudioHtml = $this->displayAudioVideo ('span6', 'span6', $rowVideoValues, array ());


                    $rowValues = array ('Media' => $rowVideoAudioHtml);
                    echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'div', 'class_label' => 'bidx-label'));
                }
                //echo $this->displayAttachments ($header = '<div>Media<div>', $businessSummary->attachment);
                ?>
            </div>
            <?php
            $personalRole = $this->exst ($businessSummary->personalRole);
            $personalExpertise = $this->exst ($businessSummary->personalExpertise);
            $supportingData = $this->exst ($businessSummary->personalDetails);
            if ($personalRole || $personalExpertise || $supportingData) {
                ?>
            </div>
            <div class ="well profile-block">
                <span id="aboutSupporting" class="scrollPositionMarker"></span>
                <h4>About the supporting team </h4>
                <div class="row-fluid">

                    <?php
    // $rowValues = array('Media');
    //echo $this->addMultipleRows('span12', $rowValues, NULL, 'h4');
                    ?>

                    <?php
                    $rowValues = array ('Role of entrepreneur in this business' => $personalRole);
                    echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'div', 'class_label' => 'bidx-label'));
                    ?>

                    <?php
                    $rowValues = array ('Please provide details of your expertise applicable to this business' => $personalExpertise);
                    echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'div', 'class_label' => 'bidx-label'));
                    ?>

                    <?php
                    $header = array ('Name' => 'name', 'Role of partner in this business' => 'role', 'Expertise of partner applicable' => 'expertise');
                    $merge['name'] = array ('firstName', 'lastName');
                    $supportingMembersHtml = $this->addTableRows ($header, $supportingData, 'table table-bordered', $merge);

                    $rowValues = array ('Supporting members of management team' => $supportingMembersHtml);
                    echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'h5'));
                    ?>
                </div>
            <?php } ?>
        </div>
    </div>
</div>
