<?php
$businessSummary = $this->data;
?>
<div class ="well profile-block">
<?php echo $this->displayAttachments ($header = '<h6>Documents</h6>', $businessSummary->attachment); ?>
</div>
<div class = "prevPageBtn">
    <a class="btn btn-large btn-primary btn-embossed mlm" href="#tab3" data-toggle="tab">View company details<i class="fui-arrow-left pull-left"></i></a>
</div>
<div class = "nextPageBtn">
    <a class="btn btn-large btn-primary btn-embossed mlm" href="#tab1" data-toggle="tab">View business details<i class="fui-arrow-right pull-right"></i></a>
</div>
