<div id="editBusinessSummary" class="row-fluid">

    <!-- LOAD -->
    <div class="view viewLoad span12">
        <span>Retrieving business summary information...</span>
    </div>

    <!-- ERROR -->
    <div class="view viewError span12">
        <h2>Error</h2>
        <p class="errorMsg"></p>
    </div>

    <!-- EDIT -->
    <div class="view viewEdit">

        <form id="frmeditBPSummary-BusinessSummary">

            <div class="span3">
                <ul class="nav nav-list affix" id="editBusinessSummary-BusinessSummary-Nav">
                    <li><a href="#editBusinessSummary/BusinessSummary/businessSummary">Business summary</a>
                    <li><a href="#editBusinessSummary/BusinessSummary/aboutYourBusiness">About your business</a>
                    <li><a href="#editBusinessSummary/BusinessSummary/aboutYouAndSupportingTeam">About you and supporting team</a>
                </ul>
            </div>

            <div class="span9">

                <p>Lorem ipsum dolizzle sit amizzle, consectetuer adipiscing my shizz. Nullizzle sapien velizzle, fo volutpizzle, suscipizzle quis, the bizzle vizzle, fo shizzle. Pellentesque eget tortor. Sure eros. Shizznit izzle dolizzle dapibizzle turpis break it down shit. Maurizzle uhuh ... yih! nibh da bomb turpizzle. Things in tortizzle. Pellentesque check it out rhoncizzle nisi. In check it out habitasse daahng dawg dictumst. Pizzle dapibizzle. Curabitur tellus nizzle, pretizzle tellivizzle, mattizzle daahng dawg, phat ass, nunc. Da bomb suscipit. Integer sheezy velit izzle purizzle.</p>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editBusinessSummary/BusinessSummary/businessSummary"></span>
                    <legend>Business summary</legend>

                    <div class="row-fluid">
                        <div class="span6">

                            <div class="control-group formfield">
                                <label class="control-label">Describe your business name in 5 words</label>
                                <div class="controls">
                                    <input type="text" name="name" placeholder="Business name">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span12">
                            <div class="control-group formfield">
                                <label class="control-label">Describe your business in 15 words ( optional )</label>
                                <div class="controls">
                                    <textarea type="text" name="slogan" placeholder="Please give a description of your business"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Industry</label>
                                <div class="controls">
                                    <input type="text" name="industry" class="bidx-tagsinput disabled" disabled data-bidxdatakey="industry" placeholder="Tags">
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Suggested industry</label>
                                <div class="controls">
                                    <input type="text" name="suggestedIndustry" class="bidx-tagsinput" placeholder="Tags">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Country of business</label>
                                <div class="controls">
                                    <input type="text" name="countryOperation" class="bidx-tagsinput disabled" disabled data-bidxdatakey="country" placeholder="Tags">
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Stage of business</label>
                                <div class="controls">
                                    toggle button group thingy (2 options)
                                    <input type="checkbox" name="stageOfBusiness" />
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">productService</label>
                                <div class="controls">
                                    <input type="text" name="productService" class="bidx-tagsinput disabled" disabled data-bidxdatakey="productService" placeholder="Tags">
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Suggested productService</label>
                                <div class="controls">
                                    <input type="text" name="suggestedProductService" class="bidx-tagsinput" placeholder="Tags">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">socialImpact</label>
                                <div class="controls">
                                    <input type="text" name="socialImpact" class="bidx-tagsinput disabled" disabled data-bidxdatakey="socialImpact" placeholder="Tags">
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">envImpact</label>
                                <div class="controls">
                                    <input type="text" name="envImpact" class="bidx-tagsinput" placeholder="Tags">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Consumper type</label>
                                <div class="controls">
                                    checkbox thingy, rendered from the list "consumerType"
                                    <input type="checkbox" name="consumerType" />
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Investment type</label>
                                <div class="controls">
                                    checkbox thingy, rendered from the list "investmentType"
                                    <input type="checkbox" name="investmentType" />
                                </div>
                            </div>
                        </div>
                    </div>

                </fieldset>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editBusinessSummary/BusinessSummary/aboutYourBusiness"></span>
                    <legend>Tell us more about your business</legend>

                    <div class="row-fluid">
                        <div class="span12">
                            <div class="control-group formfield">
                                <label class="control-label">Provide a summary of your business in maximum 150 words</label>
                                <div class="controls">
                                    <textarea name="summary" placeholder="Please give a summary of your business"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Reason for submission of business summary</label>
                                <div class="controls">
                                    checkbox thingy / toggle button
                                    <input type="checkbox" name="reasonForSubmission" />
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Percentage equity your currently retain ( optional )</label>
                                <div class="controls">
                                    <input type="number" name="equityRetained" placeholder="Please give the environmental impact">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Finance needed</label>
                                <div class="controls">
                                    <input type="text" name="financeNeeded" placeholder="Please give finance needed">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span12">
                            <div class="control-group formfield">
                                <label class="control-label">Why do you need financing? Describe in maximum 30 words ( optional )</label>
                                <div class="controls">
                                    <textarea name="summaryFinancingNeeded" placeholder="Please give the reason you need financing"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                    <h3>Media</h3>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Add online video</label>
                                <div class="controls">
                                    <input type="text" name="externalVideoPitch" placeholder="Please give online video">
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Add online audio</label>
                                <div class="controls">
                                    <input type="text" name="externalAudioPitch" placeholder="Please give online audio">
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editBusinessSummary/BusinessSummary/aboutYouAndSupportingTeam"></span>
                    <legend>Tell us more about the people that are supporting you in this business</legend>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Role of entrepreneur in this business (5 words)</label>
                                <div class="controls">
                                    <input type="text" name="personalRole" placeholder="Please give role of entrepreneur in this business">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span12">
                            <div class="control-group formfield">
                                <label class="control-label">Please provide details of your expertise applicable to this business (30 words)</label>
                                <div class="controls">
                                    <textarea name="personalExpertise" placeholder="Please give the "></textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                    <h4>Supporting members of management team</h4>
                    <div class="row-fluid">
                        reflowrower thingy with personaldetails
                    </div>

                </fieldset>

            </div>

        </form>
    </div>

    <div class="snippets hide">
        <div class="personalDetailsItem">
            personalDetailsItem snippet
        </div>
    </div>

</div><!-- // row -->
