<div id="editBusinessSummary" class="row-fluid">

    <!-- LOAD -->
    <div class="view viewLoad span12">
        <span><?php _e('Retrieving business summary information...'); ?></span>
    </div>

    <!-- ERROR -->
    <div class="view viewError span12">
        <h2><?php _e('Error'); ?></h2>
        <p class="errorMsg"></p>
    </div>

    <!-- EDIT -->
    <div class="view viewEdit">

        <form id="frmeditBPSummary-BusinessSummary">

            <div class="span3">
                <ul class="nav nav-list affix" id="editBusinessSummary-BusinessSummary-Nav">
                    <li><a href="#editBusinessSummary/BusinessSummary/businessSummary"><?php _e('Business summary'); ?></a>
                    <li><a href="#editBusinessSummary/BusinessSummary/aboutYourBusiness"><?php _e('About your business'); ?></a>
                    <li><a href="#editBusinessSummary/BusinessSummary/aboutYouAndSupportingTeam"><?php _e('About you and supporting team'); ?></a>
                </ul>
            </div>

            <div class="span9">

                <p>work in progress, this edit state is not finished yet</p>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editBusinessSummary/BusinessSummary/businessSummary"></span>
                    <legend><?php _e('Business summary'); ?></legend>

                    <div class="row-fluid">
                        <div class="span6">

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Describe your business name in 5 words'); ?></label>
                                <div class="controls">
                                    <input type="text" name="name" placeholder="<?php _e('Business name'); ?>">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span12">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Describe your business in 15 words ( optional )'); ?></label>
                                <div class="controls">
                                    <textarea type="text" name="slogan" placeholder="<?php _e('Please give a description of your business'); ?>"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Industry'); ?></label>
                                <div class="controls">
                                    <input type="text" autocomplete="off" name="industry" class="bidx-tagsinput disabled" disabled data-bidxdatakey="industry" placeholder="<?php _e('Industry'); ?>">
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Suggested industry'); ?></label>
                                <div class="controls">
                                    <input type="text" autocomplete="off" name="suggestedIndustry" class="bidx-tagsinput" placeholder="<?php _e('Suggested industry'); ?>">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Country of business'); ?></label>
                                <div class="controls">
                                    <input type="text" autocomplete="off" name="countryOperation" class="bidx-tagsinput disabled" disabled data-bidxdatakey="country" placeholder="<?php _e('Country of business'); ?>">
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Stage of business'); ?></label>
                                <div class="controls">
                                    <input type="checkbox" name="stageOfBusiness" />
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Products'); ?></label>
                                <div class="controls">
                                    <input type="text" autocomplete="off" name="productService" class="bidx-tagsinput disabled" disabled data-bidxdatakey="productService" placeholder="<?php _e('Products'); ?>">
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Suggested product'); ?></label>
                                <div class="controls">
                                    <input type="text" autocomplete="off" name="suggestedProductService" class="bidx-tagsinput" placeholder="S<?php _e('Suggested products'); ?>">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Social impact'); ?></label>
                                <div class="controls">
                                    <input type="text" autocomplete="off" name="socialImpact" class="bidx-tagsinput disabled" disabled data-bidxdatakey="socialImpact" placeholder="<?php _e('Social impact'); ?>">
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Environmental impact'); ?></label>
                                <div class="controls">
                                    <input type="text" autocomplete="off" name="envImpact" class="bidx-tagsinput" placeholder="<?php _e('Environmental impact'); ?>">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Consumper type'); ?></label>
                                <div class="controls">
                                    <input type="checkbox" name="consumerType" />
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Investment type'); ?></label>
                                <div class="controls">
                                    <input type="checkbox" name="investmentType" />
                                </div>
                            </div>
                        </div>
                    </div>

                </fieldset>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editBusinessSummary/BusinessSummary/aboutYourBusiness"></span>
                    <legend><?php _e('Tell us more about your business'); ?></legend>

                    <div class="row-fluid">
                        <div class="span12">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Provide a summary of your business in maximum 150 words'); ?></label>
                                <div class="controls">
                                    <textarea name="summary" placeholder="<?php _e('Please give a summary of your business'); ?>"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Reason for submission of business summary'); ?></label>
                                <div class="controls">
                                    <input type="checkbox" name="reasonForSubmission" />
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Percentage equity your currently retain ( optional )'); ?></label>
                                <div class="controls">
                                    <input type="number" name="equityRetained" placeholder="<?php _e('Percentage'); ?>">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Finance needed'); ?></label>
                                <div class="controls">
                                    <input type="text" name="financeNeeded" placeholder="<?php _e('Please give finance needed'); ?>">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span12">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Why do you need financing? Describe in maximum 30 words ( optional )'); ?></label>
                                <div class="controls">
                                    <textarea name="summaryFinancingNeeded" placeholder="<?php _e('Please give the reason you need financing'); ?>"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                    <h3><?php _e('Media'); ?></h3>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Add online video'); ?></label>
                                <div class="controls">
                                    <input type="text" name="externalVideoPitch" placeholder="<?php _e('Please give online video'); ?>">
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Add online audio'); ?></label>
                                <div class="controls">
                                    <input type="text" name="externalAudioPitch" placeholder="<?php _e('Please give online audio'); ?>">
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editBusinessSummary/BusinessSummary/aboutYouAndSupportingTeam"></span>
                    <legend><?php _e('Tell us more about the people that are supporting you in this business'); ?></legend>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Role of entrepreneur in this business (5 words)'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalRole" placeholder="<?php _e('Please give role of entrepreneur in this business'); ?>">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span12">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Please provide details of your expertise applicable to this business (30 words)'); ?></label>
                                <div class="controls">
                                    <textarea name="personalExpertise" placeholder="<?php _e('The details of your expertise for this business'); ?>"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                    <h4><?php _e('Supporting members of management team'); ?></h4>
                    <div class="row-fluid">
                        ...
                    </div>

                </fieldset>

            </div>

        </form>
    </div>

    <div class="snippets hide">
        <div class="personalDetailsItem">
            personalDetailsItem snippet
        </div>
    </div>

</div><!-- // row -->
