<div id="editBusinessSummary" class="row-fluid">

    <!-- LOAD -->
    <div class="view viewLoad span12">
        <span><?php _e('Retrieving business summary information...','bidxplugin'); ?></span>
    </div>

    <!-- ERROR -->
    <div class="view viewError span12">
        <h2><?php _e('Error','bidxplugin'); ?></h2>
        <p class="errorMsg"></p>
    </div>

    <!-- EDIT -->
    <div class="view viewEdit">

        <form id="frmeditBPSummary-BusinessSummary">

            <div class="span3">
                <ul class="nav nav-list affix" id="editBusinessSummary-BusinessSummary-Nav">
                    <li><a href="#editBusinessSummary/BusinessSummary/businessSummary"><?php _e('Business summary','bidxplugin'); ?></a>
                    <li><a href="#editBusinessSummary/BusinessSummary/aboutYourBusiness"><?php _e('About your business','bidxplugin'); ?></a>
                    <li><a href="#editBusinessSummary/BusinessSummary/aboutYouAndSupportingTeam"><?php _e('About you and supporting team','bidxplugin'); ?></a>
                </ul>
            </div>

            <div class="span9">

                <p>work in progress, this edit state is not finished yet</p>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editBusinessSummary/BusinessSummary/businessSummary"></span>
                    <legend><?php _e('Business summary','bidxplugin'); ?></legend>

                    <div class="row-fluid">
                        <div class="span6">

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Describe your business name in 5 words','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="name" placeholder="<?php _e('Business name','bidxplugin'); ?>">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span12">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Describe your business in 15 words ( optional )','bidxplugin'); ?></label>
                                <div class="controls">
                                    <textarea type="text" name="slogan" placeholder="<?php _e('Please give a description of your business','bidxplugin'); ?>"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Industry','bidxplugin'); ?></label>
                                <div class="controls">
                                    <div class="bidx-tagsinput-container">
                                        <input type="text" autocomplete="off" name="industry" class="bidx-tagsinput enclosed disabled" disabled data-bidxdatakey="industry" placeholder="<?php _e('Industry','bidxplugin'); ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Suggested industry','bidxplugin'); ?></label>
                                <div class="controls">
                                    <div class="bidx-tagsinput-container">
                                        <input type="text" autocomplete="off" name="suggestedIndustry" class="bidx-tagsinput enclosed" placeholder="<?php _e('Suggested industry','bidxplugin'); ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Country of business','bidxplugin'); ?></label>
                                <div class="controls">
                                    <div class="bidx-tagsinput-container">
                                        <input type="text" autocomplete="off" name="countryOperation" class="bidx-tagsinput enclosed disabled" disabled data-bidxdatakey="country" placeholder="<?php _e('Country of business','bidxplugin'); ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Stage of business','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="checkbox" name="stageOfBusiness" />
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Products','bidxplugin'); ?></label>
                                <div class="controls">
                                    <div class="bidx-tagsinput-container">
                                        <input type="text" autocomplete="off" name="productService" class="bidx-tagsinput enclosed disabled" disabled data-bidxdatakey="productService" placeholder="<?php _e('Products','bidxplugin'); ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Suggested product','bidxplugin'); ?></label>
                                <div class="controls">
                                    <div class="bidx-tagsinput-container">
                                        <input type="text" autocomplete="off" name="suggestedProductService" class="bidx-tagsinput enclosed" placeholder="<?php _e('Suggested products','bidxplugin'); ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Social impact','bidxplugin'); ?></label>
                                <div class="controls">
                                    <div class="bidx-tagsinput-container">
                                        <input type="text" autocomplete="off" name="socialImpact" class="bidx-tagsinput enclosed disabled" disabled data-bidxdatakey="socialImpact" placeholder="<?php _e('Social impact','bidxplugin'); ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Environmental impact','bidxplugin'); ?></label>
                                <div class="controls">
                                    <div class="bidx-tagsinput-container">
                                        <input type="text" autocomplete="off" name="envImpact" class="bidx-tagsinput enclosed" placeholder="<?php _e('Environmental impact','bidxplugin'); ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Consumper type','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="checkbox" name="consumerType" />
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Investment type','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="checkbox" name="investmentType" />
                                </div>
                            </div>
                        </div>
                    </div>

                </fieldset>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editBusinessSummary/BusinessSummary/aboutYourBusiness"></span>
                    <legend><?php _e('Tell us more about your business','bidxplugin'); ?></legend>

                    <div class="row-fluid">
                        <div class="span12">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Provide a summary of your business in maximum 150 words','bidxplugin'); ?></label>
                                <div class="controls">
                                    <textarea name="summary" placeholder="<?php _e('Please give a summary of your business','bidxplugin'); ?>"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Reason for submission of business summary','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="checkbox" name="reasonForSubmission" />
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Percentage equity your currently retain ( optional )','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="equityRetained" placeholder="<?php _e('Percentage','bidxplugin'); ?>">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Finance needed','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="financeNeeded" placeholder="<?php _e('Please give finance needed','bidxplugin'); ?>">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span12">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Why do you need financing? Describe in maximum 30 words ( optional )','bidxplugin'); ?></label>
                                <div class="controls">
                                    <textarea name="summaryFinancingNeeded" placeholder="<?php _e('Please give the reason you need financing','bidxplugin'); ?>"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                    <h3><?php _e('Media','bidxplugin'); ?></h3>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Add online video','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="externalVideoPitch" placeholder="<?php _e('Please give online video','bidxplugin'); ?>">
                                </div>
                            </div>
                        </div>
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Add online audio','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="externalAudioPitch" placeholder="<?php _e('Please give online audio','bidxplugin'); ?>">
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editBusinessSummary/BusinessSummary/aboutYouAndSupportingTeam"></span>
                    <legend><?php _e('Tell us more about the people that are supporting you in this business','bidxplugin'); ?></legend>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Role of entrepreneur in this business (5 words)','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalRole" placeholder="<?php _e('Please give role of entrepreneur in this business','bidxplugin'); ?>">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span12">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Please provide details of your expertise applicable to this business (30 words)','bidxplugin'); ?></label>
                                <div class="controls">
                                    <textarea name="personalExpertise" placeholder="<?php _e('The details of your expertise for this business','bidxplugin'); ?>"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                    <h4><?php _e('Supporting members of management team','bidxplugin'); ?></h4>
                    <div class="row-fluid">
                        ...
                    </div>

                </fieldset>

            </div>

        </form>
    </div>

    <div class="snippets hide">
        <div class="personalDetailsItem">
            personalDetailsItem snippet
        </div>
    </div>

</div><!-- // row -->
