<script type="text/javascript">
    //using temporary inline loading
    $( function()
    {



        ( function( $ )
        {
            var $element                    = $( "#editBusinessSummary" )
            ,   $views                      = $element.find( ".view" )
            ,   $tables                     = $( ".financial-details" )
            ,   bidx                        = window.bidx
            ,   snippets                    = {}
            ;


            //public functions

            //private functions
            var _init = function ()
            {
                _generateTable();
            };

            //  function that generates the table based on the returned data from the API
            var _generateTable = function ()
            {
                var  financialData           = _getData()
                ,   $table
                ,   $item
                ,   $clone
                ,   $row
                ,   dataGrid        = {}
                ;

                //loop though statements
                $.each( financialData, function ( idx, statement )
                {
                    bidx.utils.log(idx);
                    //get the correct table
                    $table = $tables.filter( "." + idx );
                    bidx.utils.log("STATEMENT", statement);

                    //now loop throught items in the statement
                    $.each( statement, function( key , item )
                    {
                        //  get the row
                        $row = $table.find( "." + key );
                        //  get the value item that will be cloned
                        $item = $( $row.find( ".item-value" )[0] ).remove();

                        //  loop through collection of item values and generate table cells
                        $.each( item, function( idv, value )
                        {
                            $clone = $item.clone();
                            $clone.text( value.value );
                            $clone.addClass( idv );
                            $row.append( $clone );
                        } );
                        //  end item loop
                    } );
                    //  end row loop
                } );
                //  end statement loop


            }


            //THIS FUNCTION CREATES MOCK DATA FOR THE FINANCIAL SUMMARY
            var _getData = function ()
            {
                //use the table markup to get the report rows, this would normally come from the API
                var mockStructure   = {}
                ,   mockData        = {}
                ,   statement
                ,   years           = [ 2011, 2012, 2013, 2014, 2015, 2016 ]
                ;

                //  loop through each tabel that has the class financial-details
                $( ".financial-details" ).each( function( idt, table )
                {
                    $table = $ ( table );

                    //  get items/rows from this table

                        //get statement label
                        statement = $.trim( $table.attr( "class" ).replace( "financial-details", "" ) ) ;
                        mockStructure[ statement ] = [];

                        // retrieve tbody so we can map the item from markup into the dataGrid object
                        $table.find( "tr:not(.ignore)" ).each( function( idi, row )
                        {
                            $row = $( row );
                            //  get the
                            mockStructure[ statement ].push( $row.attr( "class" ).split(" ").shift() );
                        } );


                } );



                //now create a grid of the mockStructre and the years with mock values
                $.each( mockStructure, function( idx, statement )
                {

                    mockData[ idx ] = {};
                    $.each( statement, function( idz, item )
                    {
                        mockData[ idx ][ item ] = {};
                        $.each( years, function ( idy, year)
                        {
                            mockData[ idx ][ item ][ year ] = {};
                            if( idx !== "header")
                            {
                                mockData[ idx ][ item ][ year ][ "value" ] = Math.floor( 1000 * Math.random() );
                            }
                            else
                            {
                                mockData[ idx ][ item ][ year ][ "value" ] = year;
                            }
                        } );

                    } );

                } );


                return mockData;

            };



            if ( !window.bidx )
            {
                window.bidx = {};
            }

            //window.bidx.financialDetails = {};
            _init();

        } ( jQuery ));

    } );
</script>

<section class="well">
    <article class="view viewNew">

        <span class="block-title"><?php _e('Financial details','bidxplugin')?></span>

        <form action="">
            <div>
                <label><?php _e('Number of years this business has generated sales or incurred costs','bidxplugin')?></label>
                <input type="text" name="years" value="">
            </div>
            <div>
                <label><?php _e('In which month does your financial year start?','bidxplugin')?></label>
                <input type="text" name="startdate" value="">
            </div>
            <div>
                <p>
                    <?php _e('Once you have completed this information, a table will be generated','bidxplugin')?>
                </p>
                <button type="submit" class="btn btn-primary"><?php _e('Generate table','bidxplugin')?></button>
            </div>
        </form>

    </article>

    <article class="view viewShow" style="display:block;">



        <table class="financial-details header" border="0">
            <colgroup>
                <col class="item-spacer">
                <col class="item-label">
                <col class="item-value" span="5">
            </colgroup>
            <tbody>
                <tr class="years">
                    <th class="item-spacer"></th>
                    <th class="item-label"></th>
                    <th class="item-value"></th>
                </tr>
            </tbody>
        </table>

        <table class="financial-details income-statement" border="0">
            <caption><?php _e('Income Statement','bidxplugin'); ?></caption>
            <colgroup>
                <col class="item-spacer">
                <col class="item-label">
                <col class="item-value" span="5">
            </colgroup>
            <thead>
                <tr class="profit-before-tax">
                    <th class="item-spacer"><span class="fui-triangle-down"></span></th>
                    <th class="item-label"><?php _e('Profit before tax','bidxplugin'); ?></th>
                    <th class="item-value"> $ 00,00 </th>
                </tr>
            </thead>
            <tfoot>
                <tr class="net-profit">
                    <td class="item-spacer"></td>
                    <td class="item-label"><?php _e('Net profit','bidxplugin'); ?></td>
                    <td class="item-value"> $ 00,00 </td>
                </tr>
            </tfoot>

            <tbody >
                <tr class="total-sales-reveneus">
                    <td class="item-spacer"></td>
                    <td class="item-label"><?php _e('Total sales reveneus','bidxplugin'); ?></td>
                    <td class="item-value"> $ 00,00 </td>
                </tr>
                <tr class="cost-of-goods-sold">
                    <td class="item-spacer"></td>
                    <td class="item-label"><?php _e('Cost of goods sold','bidxplugin'); ?></td>
                    <td class="item-value"> $ 00,00 </td>
                </tr>
                <tr class="gross-profit subtotal">
                    <td class="item-spacer"></td>
                    <td class="item-label"><?php _e('Gross Profit','bidxplugin'); ?></td>
                    <td class="item-value"> $ 00,00 </td>
                </tr>
                <tr class="ignore spacer">
                    <td colspan="7"></td>
                </tr>



                <tr class="salary">
                    <td class="item-spacer"></td>
                    <td class="item-label"><?php _e('Salary','bidxplugin'); ?></td>
                    <td class="item-value"> $ 00,00 </td>
                </tr>
                <tr class="depreciation">
                    <td class="item-spacer"></td>
                    <td class="item-label"><?php _e('Depreciation','bidxplugin'); ?></td>
                    <td class="item-value"> $ 00,00 </td>
                </tr>
                <tr class="other-operating-costs">
                    <td class="item-spacer"></td>
                    <td class="item-label"><?php _e('Other operating costs','bidxplugin'); ?></td>
                    <td class="item-value"> $ 00,00 </td>
                </tr>
                <tr class="operating-profit subtotal">
                    <td class="item-spacer"></td>
                    <td class="item-label"><?php _e('Operating profit','bidxplugin'); ?></td>
                    <td class="item-value"> $ 00,00 </td>
                </tr>
                <tr class="ignore spacer">
                    <td colspan="7"></td>
                </tr>

                <tr class="interest-payment">
                    <td class="item-spacer"></td>
                    <td class="item-label"><?php _e('Interest payment','bidxplugin'); ?></td>
                    <td class="item-value"> $ 00,00 </td>
                </tr>

<!--                 <tr class="ignore spacer">
                    <td colspan="7"></td>
                </tr> -->

                <tr class="total-profit-before-tax total">
                    <td class="item-spacer"></td>
                    <td class="item-label"><?php _e('Total profit before tax','bidxplugin'); ?></td>
                    <td class="item-value"> $ 00,00 </td>
                </tr>
                <tr class="tax">
                    <td class="item-spacer"></td>
                    <td class="item-label"><?php _e('Tax'); ?></td>
                    <td class="item-value"> $ 00,00 </td>
                </tr>
                <!-- <tr class="ignore spacer">
                    <td colspan="7"></td>
                </tr>
                 -->
            </tbody>

        </table>


        <table class="financial-details cash-flow-statement" border="0">
            <caption><?php _e('Cash Flow Statement','bidxplugin'); ?></caption>
            <colgroup>
                <col class="item-spacer">
                <col class="item-label">
                <col class="item-value" span="5">
            </colgroup>
            <thead>
                <tr class="change-in-cash">
                    <th class="item-spacer"><span class="fui-triangle-down"></span></th>
                    <th class="item-label"><?php _e('Profit before tax','bidxplugin'); ?></th>
                    <th class="item-value"> $ 00,00 </th>
                </tr>
            </thead>

            <tbody >
                <tr class="investing-cash-flow">
                    <td class="item-spacer"></td>
                    <td class="item-label"><?php _e('Investing cash flow','bidxplugin'); ?></td>
                    <td class="item-value"> $ 00,00 </td>
                </tr>
                <tr class="financing-cash-flow">
                    <td class="item-spacer"></td>
                    <td class="item-label"><?php _e('Financing cash flow','bidxplugin'); ?></td>
                    <td class="item-value"> $ 00,00 </td>
                </tr>
                <tr class="total-change-in-cash total">
                    <td class="item-spacer"></td>
                    <td class="item-label"><?php _e('Total change in cash','bidxplugin'); ?></td>
                    <td class="item-value"> $ 00,00 </td>
                </tr>
                <tr class="ignore spacer">
                    <td colspan="7"></td>
                </tr>

            </tbody>

        </table>

        <table class="financial-details balance-sheet-statement" border="0">
            <caption><?php _e('Balance Sheet Statement','bidxplugin'); ?></caption>
            <colgroup>
                <col class="item-spacer">
                <col class="item-label">
                <col class="item-value" span="5">
            </colgroup>
            <thead>
                <tr class="total-assets-header">
                    <th class="item-spacer"><span class="fui-triangle-down"></span></th>
                    <th class="item-label"><?php _e('Total Assets','bidxplugin'); ?></th>
                    <th class="item-value"> $ 00,00 </th>
                </tr>
            </thead>


            <tbody >
                <tr class="fixed-assets">
                    <td class="item-spacer"></td>
                    <td class="item-label"><?php _e('Fixed Assets','bidxplugin'); ?></td>
                    <td class="item-value"> $ 00,00 </td>
                </tr>
                <tr class="total-fixed-assets subtotal">
                    <td class="item-spacer"></td>
                    <td class="item-label"><?php _e('Total Fixed Assets','bidxplugin'); ?></td>
                    <td class="item-value"> $ 00,00 </td>
                </tr>

                <tr class="ignore spacer">
                    <td colspan="7"></td>
                </tr>

                <tr class="total-inventory">
                    <td class="item-spacer"></td>
                    <td class="item-label"><?php _e('Total inventory','bidxplugin'); ?></td>
                    <td class="item-value"> $ 00,00 </td>
                </tr>
                <tr class="net-receivables">
                    <td class="item-spacer"></td>
                    <td class="item-label"><?php _e('Net receivables','bidxplugin'); ?></td>
                    <td class="item-value"> $ 00,00 </td>
                </tr>
                <tr class="cash">
                    <td class="item-spacer"></td>
                    <td class="item-label"><?php _e('Cash','bidxplugin'); ?></td>
                    <td class="item-value"> $ 00,00 </td>
                </tr>
                <tr class="current-assets subtotal">
                    <td class="item-spacer"></td>
                    <td class="item-label"><?php _e('Current Assets','bidxplugin'); ?></td>
                    <td class="item-value"> $ 00,00 </td>
                </tr>
                <tr class="ignore spacer">
                    <td colspan="7"></td>
                </tr>

                <tr class="total-assets total">
                    <td class="item-spacer"></td>
                    <td class="item-label"><?php _e('Total Assets','bidxplugin'); ?></td>
                    <td class="item-value"> $ 00,00 </td>
                </tr>
                <tr class="ignore spacer">
                    <td colspan="7"></td>
                </tr>
            </tbody>

        </table>
    </article>

</section>
