<?php
$progress = trim ($this->data->rating->Completeness) . '%';

//To display Company Tab
$companyId = $this->exst ($this->data->company);

//To display Documents Tab
$companyId = $this->exst ($this->data->company);

?>
<script>
    // Hack untill wordpress will do this for us.
    //
    ( function()
    {
        var body = document.getElementsByTagName( "body" )[ 0 ];
        body.className += " bidx-business";
    } ());
</script>
<div class="bp-summary">

    <!-- header of bp summary -->
    <div class="pageHeader container">
        <div class="editControls btn-group clearfix">
            <a class="btn btn-primary" href="#editSummary/">Edit</a>
            <a class="btn btn-primary" href="#publishSummary/">Publish</a>
        </div>

        <div class="bp-summary-progress">
            <div class="progress progress-striped">
                <div style="width:<?php echo $progress ?>" class="bar summarybar">Business completion <?php echo $progress ?></div>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span4">
                <h3><?php echo $this -> data -> name;?></h3>
                <h4>Business summary </h4>
            </div>

            <!-- Tab Header -->
            <div class="span8">

                <ul class="nav nav-tabs businessSummaryTabs pull-right">
                    <li class="active"><a href="#bpSummary-BusinessSummary" data-toggle="tab">Business summary</a></li>
                    <li><a href="#bpSummary-FinancialDetails" data-toggle="tab">Financial details</a></li>
<?php if($companyId) { ?>
                    <li><a href="#bpSummary-CompanyDetails" data-toggle="tab">Company details</a></li>
<?php } ?>
                    <li><a href="#bpSummary-Documents" data-toggle="tab">Documents</a></li>
                </ul>

            </div>
        </div>
    </div><!-- /header of bp summary -->

    <!-- content of bp summary -->
    <div class="tab-content">

        <!-- Tab: Business Summary -->
        <div class="tab-pane active" id="bpSummary-BusinessSummary">
            <?php $this -> render ( 'business-summary.phtml' ); ?>

            <!-- Navigational buttons -->
            <div>
                <a class="btn btn-large btn-primary pull-right tabControl" href="#bpSummary-FinancialDetails" data-tab=".businessSummaryTabs">View financial details<i class="fui-arrow-right pull-right"></i></a>
            </div><!-- /Navigation buttons -->

        </div><!-- /Tab: Business Summary -->

        <!-- Tab: Financial Details -->
        <div class="tab-pane" id="bpSummary-FinancialDetails">
            <?php $this -> render ( 'financial-details.phtml' ); ?>

            <!-- Navigational buttons -->
            <div>
                <a class="btn btn-large btn-primary pull-left tabControl" href="#bpSummary-BusinessSummary" data-tab=".businessSummaryTabs">View business details<i class="fui-arrow-left pull-left"></i></i></a>
<?php if($companyId) {  ?>
                <a class="btn btn-large btn-primary pull-right tabControl" href="#bpSummary-CompanyDetails" data-tab=".businessSummaryTabs">View company details<i class="fui-arrow-right pull-right"></i></a>
<?php } else { ?>
                <a class="btn btn-large btn-primary pull-right tabControl" href="#bpSummary-Documents" data-tab=".businessSummaryTabs">View documents<i class="fui-arrow-right pull-right"></i></a>
<?php } ?>
            </div><!-- /Navigational buttons -->
        </div><!-- /Tab: Financial Details -->

        <!-- Tab: Company Details -->
<?php if($companyId) {  ?>
        <div class="tab-pane" id="bpSummary-CompanyDetails">
<?php
            echo do_shortcode('[bidx app="company" id='.$this->data->company.'] ');
?>
            <!-- Navigational buttons -->
            <div>
                <a class="btn btn-large btn-primary pull-left tabControl" href="#bpSummary-FinancialDetails" data-tab=".businessSummaryTabs">View Financial details<i class="fui-arrow-left pull-left"></i></a>
                <a class="btn btn-large btn-primary pull-right tabControl" href="#bpSummary-Documents" data-tab=".businessSummaryTabs">View document<i class="fui-arrow-right pull-right"></i></a>
            </div><!-- /Navigational buttons -->
        </div><!-- /Tab: Company Details -->
<?php } ?>

        <!-- Tab: Documents -->
        <div class="tab-pane" id="bpSummary-Documents">
            <?php $this -> render ( 'documents.phtml' ); ?>

            <!-- Navigational buttons -->
            <div>
<?php if($companyId) {  ?>
                <a class="btn btn-large btn-primary pull-left tabControl" href="#bpSummary-CompanyDetails" data-tab=".businessSummaryTabs">View company details<i class="fui-arrow-left pull-left"></i></a>
<?php } else { ?>
                <a class="btn btn-large btn-primary pull-left tabControl" href="#bpSummary-FinancialDetails" data-tab=".businessSummaryTabs">View Financial details<i class="fui-arrow-left pull-left"></i></a>
<?php } ?>
            </div><!-- /Navigational buttons -->

        </div><!-- /Tab: Documents -->

    </div><!-- /content of bp summary -->
</div><!-- /bp-summary -->

