<div id="support" class="mainState mainStateSupport">
    <h1>Support</h1>
    <div class="row-fluid">
        <div class="span8">
            <h2>Group inbox messages</h2>
        </div>
        <div class="row-fluid">
            <div class="span12">
                See here the list of platform emails. You can send them a reply, or <a target='_blank' href='/support'>create a ticket with bidX</a> support.
            </div>

        </div>

    </div>
    <div class="row-fluid">

         <!-- mail stage: this is the ajax target -->
        <div class="span10 well support">
            <!-- ************************* utility views *********************************** -->
            <div class="view viewLoad"><?php _e('Loading...','bidxplugin')?></div>

            <div class="view viewError">
                <h1><?php _e('Error','bidxplugin')?></h1>
                <span class="errorMsg"></span>
            </div>

            <div class="view viewUndefined"><h1><?php _e('No view defined for this state','bidxplugin')?></h1></div>

            <!-- ************************* application views *********************************** -->

            <!-- mail listview like mail, sent, drafts, archived or trash -->
            <div class="view viewList">
                <div id="support-set">
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th><?php _e ('Sender', 'bidxplugin') ?></th>
                                <th><?php _e ('Subject', 'bidxplugin') ?></th>
                                <th><?php _e ('Date', 'bidxplugin') ?></th>
                                <th class="hidden-phone"><?php _e ('Action', 'bidxplugin') ?></th>
                            </tr>
                        </thead>
                        <tbody class="list-support">
                            <div class="pull-left">
                                <?php// _e ('Loading...', 'bidxplugin') ?>
                            </div>
                        </tbody>
                    </table>
                </div>
            </div>
             <div class="row-fluid">
                    <div class="span12 pagercontainer-support">
                        <div class="pager-support"></div>
                    </div>
            </div>
        </div>
    </div>
</div>

<script type="text/html" id="mailbox-listitem">
<!--
<tr>
    <td>
       <span class="placeholder sendername">%sendername%</span>
    </td>
    <td>
       <span class="placeholder subject"/>%subject%</span>
    </td>
    <td class="hidden-phone">
       <span class="placeholder dateSent"/>%dateSent% %timeSent%</span>
    </td>
    <td class="hidden-phone">
       <span class="placeholder viewmessage">
            <a target = "_blank" href="/mail/#mail/mbx-inbox/id=%emailId%">View message</a>
        </span>|
        <span class="placeholder replyto">
            <a target = "_blank" href="/mail/#mail/mbx-inbox/action=reply&id=%emailId%">Reply to member</a>
        </span>
    </td>
</tr>
-->
</script>

<script type="text/html" id="mailbox-empty">
<!--
<li class="media">
    <div class="pull-left check"></div>
    <div class="">
        <?php _e('No messages available')?>
    </div>
</li>
-->
</script>
