<div id="zendesk" >
    <div class="row-fluid">
            <div class="span8">
                <h2>Status of questions and support requests</h2>
            </div>
            <div class="row-fluid">
                <div class="span8">
                    See here the status of your question/tickets you created through <a target='_blank' href='/support'>bidx Support</a>.
                </div>

            <div>
                <?php echo $this->zendeskView; ?>
            </div>
    </div>
</div>
