<script type="text/javascript">
    

    window.$(function(){
        /*
            bind messageCheckAll to all chexkboxes in messages listing
        */        
        $("#messagesCheckall").change(function(){
            $(".inbox-messages :checkbox").each(function(){
                var $this=$(this);
                $this.attr("checked", !$this.attr("checked"));
                $this.parent().toggleClass("checked");
            });
        });
    });


</script>

<div class="row-fluid">

    <!-- Left menu -->
    <div class="span2 side-menu well">
        <a class="btn btn-large btn-block btn-primary" href="#fakelink">Inbox</a>
        <a class="btn btn-large btn-block" href="#fakelink">Sent</a>
        <a class="btn btn-large btn-block" href="#fakelink">Drafts</a>
        <a class="btn btn-large btn-block" href="#fakelink">Archived</a>
    </div>

    <!-- Inbox stage: this is the ajax target -->
    <div class="span10 well inbox-stage">
        <!-- Email searchbox -->
        <div class="inbox-search text-right">
            <div class="control-group small">
                <div class="input-append">
                    <input type="text" placeholder="Search" id="appendedInputButton-01" class="span2">
                    <button type="button" class="btn btn-small"><span class="fui-search"></span></button>
                </div>
            </div>
        </div>       
        <div class="inbox">


            <!-- TOOLBAR -->
            <div class="inbox-toolbar">
                <div class="check">
                    <label class="checkbox">
                        <input type="checkbox" data-toggle="checkbox" id="messagesCheckall" value="">
                    </label>
                </div>
                <div class="btn-group">.
                    <a class="btn btn-small btn-primary" href="#fakelink">Delete</a>
                    <a class="btn btn-small btn-primary" href="#fakelink">Mark read</a>
                    <a class="btn btn-small btn-primary" href="#fakelink">Mark unread</a>
                </div>
              

            </div>

            <!-- MESSAGE LIST -->
            <ul class="media-list inbox-messages">
                <!-- message -->
                <li class="media">
                    <div class="pull-left check">
                        <label class="checkbox">
                            <input type="checkbox" data-toggle="checkbox"  value="">
                        </label>
                    </div>
                    <a class="pull-left" href="#">
                        <img class="media-object" data-src="holder.js/64x64">
                    </a>
                    <div class="media-body">
                        <div class="row-fluid">
                            <div class="span10"><h6 class="media-heading">Sender firstname lastname</h6></div>
                            <div class="span2">5 November 2013 12:44</div>
                        </div>
                        
                        <!-- Nested media object -->
                        <div class="subject">
                            Message subject
                        </div>
                    </div>
                </li>
                <!-- end message -->
                <!-- message -->
                <li class="media">
                    <div class="pull-left check">
                        <label class="checkbox">
                            <input type="checkbox" data-toggle="checkbox" value="">
                        </label>
                    </div>
                    <a class="pull-left" href="#">
                        <img class="media-object" data-src="holder.js/64x64">
                    </a>
                    <div class="media-body">
                        <h6 class="media-heading">Sender firstname lastname</h6>
                        <!-- Nested media object -->
                        <div class="subkect">
                            Message subject
                        </div>
                    </div>
                </li>     
                <!-- end message -->           
            </ul>
            <div class="pagination">
                <ul>
                    <li class="previous"><a class="fui-arrow-left" href="#fakelink"></a></li>
                    <li class="active"><a href="#fakelink">1</a></li>
                    <li><a href="#fakelink">2</a></li>
                    <li><a href="#fakelink">3</a></li>
                    <li><a href="#fakelink">4</a></li>
                    <li><a href="#fakelink">5</a></li>
                    <li><a href="#fakelink">6</a></li>
                    <li><a href="#fakelink">7</a></li>
                    <li><a href="#fakelink">8</a></li>
                    <li><a href="#fakelink">9</a></li>
                    <li><a href="#fakelink">10</a></li>
                    <li class="next"><a class="fui-arrow-right" href="#fakelink"></a></li>
                </ul>
            </div>
        </div>
    </div>

</div>