<div class="row-fluid">
    <div class="span2 side-menu well">
        <a class="btn btn-large btn-block btn-primary" href="#fakelink">Inbox</a>
        <a class="btn btn-large btn-block" href="#fakelink">Sent</a>
        <a class="btn btn-large btn-block" href="#fakelink">Drafts</a>
        <a class="btn btn-large btn-block" href="#fakelink">Archived</a>
    </div>
    <div class="span6 well">
        <div>
            <ul class="nav nav-pills">
              <li><a href="#fakelink">Delete</a></li>
              <li><a href="#fakelink">Mark read</a></li>
              <li><a href="#fakelink">Mark unread</a></li>
            </ul>
        </div>
        <div>
            <ul class="media-list">
                <li class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" data-src="holder.js/64x64">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Media heading</h4>
                        ...

                        <!-- Nested media object -->
                        <div class="media">
                        ...
                        </div>
                    </div>
                </li>
                <li class="media">
                    <a class="pull-left" href="#">
                        <img class="media-object" data-src="holder.js/64x64">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Media heading</h4>
                        ...

                        <!-- Nested media object -->
                        <div class="media">
                        ...
                        </div>
                    </div>
                </li>                
            </ul>
        </div>
    </div>
    <div class="span4">
        <div class="well">Advert 1</div>
        <div class="well">Advert 2</div>
        <div class="well">Advert 3</div>
    </div>
</div>