<div class="view viewShow top-margin-lineheight bottom-margin-lineheight">
	<div class="row container">
		<div class="col-md-4">
			<img src="/wp-content/plugins/bidx-plugin/apps/expressform/static/img/pintar.png" alt="Cover Image"  width="100%" height="100%" />
		</div>
		<div class="col-md-8">
			<h1 class="text-primary-dark expressTitle"><?php _e('Usaha Pintar 50', 'bidxplugin');?> </h1>
			<h3 class="text-copy"><?php _e("Is your business revenue growing by 20%+ per year?
Then your business is probably one of the fastest growers in your city.<br/><br/>

Apply with Usaha Pintar 50 and be awarded the Usaha Pintar award.<br>With Usaha Pintar 50 you can receive:
<ul>
	<li>free mentoring (accounting, marketing, legal, etc.)</li>
	<li>Access to loans & equity finance</li>
	<li>Get media exposure (on Kompas TV, Detik, Bens Radio, etc.)</li>
	<li>Access a network of other innovative businesses (usahapintar.com)</li>
	<li>Get support from KPMG</li></ul><br/>
Join Usaha Pintar 50 Today! ", "bidxplugin");?>
			</h3>
			<a class="btn btn-primary btn-lg center btn-block active btn-participate pull-right" href="#createExpressForm"><?php _e('Participate now','bidxplugin');?> </a>
		</div>
	</div>
</div>