<div id="editInvestor" class="row-fluid mainState mainStateEditInvestor">

    <!-- LOAD -->
    <div class="view viewLoad span12">
        <span>Retrieving investor information...</span>
    </div>

    <!-- CREATE -->
    <div class="view viewCreate span12">
        <span>Creating investor...</span>
    </div>

    <!-- ERROR -->
    <div class="view viewError span12">
        <h2>Error</h2>
        <p class="errorMsg"></p>
    </div>

    <!-- EDIT -->
    <div class="view viewEdit">

        <form id="frmeditInvestor">

            <div class="span3">
                <ul class="nav nav-list nav-edit nav-editInvestor hidden-phone">
                    <li><a href="#editInvestor/generalInformation">General information</a>
                    <li><a href="#editInvestor/investmentPreferences">Investment preferences</a>
                    <li><a href="#editInvestor/investmentHistory">Investment history</a>
                    <li><a href="#editInvestor/references">References</a>
                    <li><a href="#editInvestor/documents">Documents</a>
                </ul>
            </div>

            <div class="span9">

                <!-- "id" is actually the memberProfileId, but to not have to rewrite the file upload let's do it like this -->
                <input type="hidden" name="investorProfileId"     />
                <input type="hidden" name="domain"              />

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editInvestor/generalInformation"></span>
                    <legend>General information</legend>

                    <div class="row-fluid">
                        <div class="span12">

                            <div class="control-group formfield">
                                <label class="control-label">Describe yourself as investor</label>
                                <div class="controls">
                                    <textarea name="summary" placeholder="Please type the summary of yourself as investor" ></textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">

                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Do you invest on behalf of an institution?</label>
                                <div class="controls">
                                    <label class="radio inline"><input type="radio" value="true"  name="investsForInst" data-toggle="radio"/> Yes</label>
                                    <label class="radio inline"><input type="radio" value="false" name="investsForInst" data-toggle="radio"/> No</label>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid toggle toggle-investsForInst">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Institution type</label>
                                <div class="controls">
                                    <select name="investorType"></select>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid toggle toggle-investsForInst">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Institution name</label>
                                <div class="controls">
                                    <input type="text" name="institutionName" placeholder="Please type the name of the institution">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid toggle toggle-investsForInst">
                        <div class="span6">
                            <div class="control-group formfield" data-validation='{"typecheck": [{"url":{"text":"Please fill in a valid URL"}}]}'>
                                <label class="control-label">Institution website</label>
                                <div class="controls">
                                    <input type="text" name="institutionWebsite" placeholder="Please type the website of the institution">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">

                            <input type="hidden" name="institutionAddress.coordinates"    />

                            <div class="control-group formfield">
                                <label class="control-label">Country</label>
                                <div class="controls">
                                    <select name="institutionAddress.country" ></select>
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label">City</label>
                                <div class="controls">
                                    <input type="text" name="institutionAddress.cityTown" placeholder="Please type your city" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label">Street</label>
                                <div class="controls">
                                    <input type="text" name="institutionAddress.street" placeholder="Please type your street" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label">Street number</label>
                                <div class="controls">
                                    <input type="text" name="institutionAddress.streetNumber" placeholder="Please type your street number" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label">Postal code</label>
                                <div class="controls">
                                    <input type="text" name="institutionAddress.postalCode" placeholder="Please type your postcode" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label">Neighborhood</label>
                                <div class="controls">
                                    <input type="text" name="institutionAddress.neighborhood" placeholder="Please type your neighborhood" />
                                </div>
                            </div>


                        </div>

                        <div class="span6">
                            <div class="institutionAddressMap"></div>
                        </div>
                    </div>

                </fieldset>


                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editInvestor/investmentPreferences"></span>
                    <legend>Investment preferences</legend>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Industry</label>
                                <div class="controls">
                                    <input type="text" name="focusIndustry" class="bidx-tagsinput disabled" disabled data-bidxdatakey="industry" placeholder="Focus industry">
                                </div>
                            </div>
                        </div>

                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Social impact</label>
                                <div class="controls">
                                    <input type="text" name="focusSocialImpact" class="bidx-tagsinput disabled" disabled data-bidxdatakey="socialImpact" placeholder="Social impact">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Environmental impact</label>
                                <div class="controls">
                                    <input type="text" name="focusEnvImpact" class="bidx-tagsinput disabled" disabled data-bidxdatakey="envImpact" placeholder="Environmental impact">
                                </div>
                            </div>
                        </div>

                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Consumer type</label>
                                <div class="controls">
                                    <input type="text" name="focusConsumerType" class="bidx-tagsinput disabled" disabled data-bidxdatakey="consumerType" placeholder="Consumer type">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Languages</label>
                                <div class="controls">
                                    <input type="text" name="focusLanguage" class="bidx-tagsinput disabled" disabled data-bidxdatakey="language" placeholder="Languages">
                                </div>
                            </div>
                        </div>

                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Country</label>
                                <div class="controls">
                                    <input type="text" name="focusCountry" class="bidx-tagsinput disabled" disabled data-bidxdatakey="country" placeholder="Country">
                                </div>
                            </div>
                        </div>

                    </div>

                    <div class="row-fluid">
                        <div class="span6 offset6">
                            <div class="control-group formfield">
                                <label class="control-label">City</label>
                                <div class="controls">
                                    <input type="text" name="focusCity" class="bidx-tagsinput" placeholder="City">
                                </div>
                            </div>
                        </div>

                    </div>

                    <div class="flow-ruid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Stage of business</label>
                                <div class="btn-group" data-toggle="buttons-checkbox" name="focusStageBusiness">
                                  <button type="button" class="btn btn-primary" value="startUp">Start up</button>
                                  <button type="button" class="btn btn-primary" value="established">Established</button>
                                </div>
                            </div>
                        </div>

                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Gender</label>
                                <div class="btn-group" data-toggle="buttons-checkbox" name="focusGender">
                                  <button type="button" class="btn btn-primary" value="m">Male</button>
                                  <button type="button" class="btn btn-primary" value="f">Female</button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Investment type</label>
                                <div class="controls">
                                    <input type="text" name="investmentType" class="bidx-tagsinput disabled" disabled data-bidxdatakey="investmentType" placeholder="Investment type">
                                </div>
                            </div>
                        </div>
                    </div>

                    <h4>Investment size</h4>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Minimal investment</label>
                                <div class="controls">
                                    <div class="input-prepend">
                                        <span class="add-on">$</span>
                                        <input type="number" name="minInvestment" placeholder="Minimal investment" min="0">
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Maximum investment</label>
                                <div class="controls">
                                    <div class="input-prepend">
                                        <span class="add-on">$</span>
                                        <input type="number" name="maxInvestment" placeholder="Maximal investment" min="0">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span12">

                            <div class="control-group formfield">
                                <label class="control-label">Other preferences (max. 60 words)</label>
                                <div class="controls">
                                    <textarea name="additionalPreferences" placeholder="Please type any additional preferences"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                </fieldset>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editInvestor/investmentHistory"></span>
                    <legend>Investment history</legend>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Number of investments in the last 12 months</label>
                                <div class="controls">
                                    <input type="number" name="numberInvestments" placeholder="Number of investments">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Amount invested in the last 12 months</label>
                                <div class="controls">
                                    <div class="input-prepend">
                                        <span class="add-on">$</span>
                                        <input type="number" name="numberInvestments" placeholder="Number of investments">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Typical involvement</label>
                                <div class="btn-group" data-toggle="buttons-radio" name="typicalInvolvement">
                                  <button type="button" class="btn btn-primary" value="advisory">Advisory</button>
                                  <button type="button" class="btn btn-primary" value="handsOn">Hands-On</button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="intermediate-row">
                        <h6>Previous investment</h6>
                        <a href="#addPreviousInvestment" class="btn btn-primary"><span class="fui-plus"></span>Add</a>
                    </div>

                    <div class="previousInvestmentContainer"></div>

                </fieldset>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editInvestor/references"></span>
                    <legend>References</legend>

                    <div class="intermediate-row">
                        <a href="#addReference" class="btn btn-primary"><span class="fui-plus"></span>Add</a>
                    </div>

                    <div class="referencesContainer"></div>

                </fieldset>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editInvestor/documents"></span>
                    <legend>Documents</legend>

                    <div class="formfield">
                        <input type="file" name="attachment" data-type="fileUpload" data-type-arguments='{"url":"/wp-admin/admin-ajax.php?action=file_upload", "extraValues":[{"name": "uploadtype", "value":"investorprofileattachment"}], "addFields":["investorProfileId","domain"], "callback": "bidx.investorprofile.attachmentUploadDone"}'/>
                    </div>

                    <div class="attachmentsContainer"></div>

                </fieldset>
            </div>

        </form>
    </div>

    <div class="snippets hide">

        <!-- Previous Investment -->
        <div class="previousInvestmentsItem span6 well well-white">
            <div class="control-group formfield">
                <label class="control-label">Company name</label>
                <div class="controls">
                    <input type="text" name="companyName" placeholder="Please type the name">
                </div>
            </div>

            <div class="control-group formfield">
                <label class="control-label">Company web-site?</label>
                <div class="controls">
                    <input type="text" name="companyWebsite" placeholder="Please type the URL">
                </div>
            </div>

            <div class="control-group formfield">
                <label class="control-label">Amount invested</label>
                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on">$</span>
                        <input type="number" name="investment" placeholder="Amount invested">
                    </div>
                </div>
            </div>

            <div class="control-group formfield">
                <label class="control-label">Investment type</label>
                <div class="controls">
                    <select name="investmentType"></select>
                </div>
            </div>

            <a href="#removeItem" class="btn btn-danger btn-mini btn-block">Remove this investment</a>
        </div>

        <!-- Reference -->
        <div class="referencesItem span6 well well-white">
            <div class="control-group formfield">
                <label class="control-label">First name</label>
                <div class="controls">
                    <input type="text" name="firstName" placeholder="Please type the first name">
                </div>
            </div>

            <div class="control-group formfield">
                <label class="control-label">Last name</label>
                <div class="controls">
                    <input type="text" name="lastName" placeholder="Please type the last name">
                </div>
            </div>

            <div class="control-group formfield">
                <label class="control-label">Professional title</label>
                <div class="controls">
                    <input type="text" name="professionalTitle" placeholder="Please type the professional title">
                </div>
            </div>

            <div class="control-group formfield" >
                <label class="control-label">LinkedIn profile</label>
                <div class="controls">
                    <input type="text" name="linkedIn" placeholder="Please type your LinkedIn profile url" />
                </div>
            </div>

            <div class="control-group formfield" data-validation='{"typecheck": [{"email":{"text":"Please fill in a valid email address"}}]}'>
                <label class="control-label">Email address</label>
                <div class="controls">
                    <input type="email" name="emailAddress" placeholder="Please type your email address" />
                </div>
            </div>

            <div class="control-group formfield">
                <label class="control-label">Landline</label>
                <div class="controls">
                    <input type="text" name="contactDetail[0].landLine" placeholder="Please type your landline number" />
                </div>
            </div>

            <div class="control-group formfield">
                <label class="control-label">Mobile</label>
                <div class="controls">
                    <input type="text" name="contactDetail[0].mobile" placeholder="Please type your mobile number" />
                </div>
            </div>

            <a href="#removeItem" class="btn btn-danger btn-mini btn-block">Remove this reference</a>
        </div>

        <!-- Attachment -->
        <div class="attachmentItem span4 well well-white">
            <div class="row-fluid">
                <div class="span4">
                    <a href="#" class="documentLink"><img class="img-rounded documentImage"></a>
                </div>
                <div class="span8">
                    <h3 class="documentName"></h3>
                    <p class="uploadedDateTime"></p>

                    <div class="control-group formfield">
                        <div class="controls">
                            <input type="text" name="purpose" placeholder="Short description">
                        </div>
                    </div>

                    <div class="control-group formfield">
                        <label class="control-label">Document type</label>
                        <div class="controls">
                            <select name="documentType"></select>
                        </div>
                    </div>
                </div>
            </div>

            <a href="#removeItem" class="btn btn-danger btn-mini btn-block">Delete</a>
        </div>
    </div>

</div><!-- // row -->
