<div id="editMember" class="row-fluid mainState mainStateEditMember">

    <!-- LOAD -->
    <div class="view viewLoad span12">
        <span>Retrieving member information...</span>
    </div>

    <!-- ERROR -->
    <div class="view viewError span12">
        <h2>Error</h2>
        <p class="errorMsg"></p>
    </div>

    <!-- EDIT -->
    <div class="view viewEdit">

        <form id="frmeditMember">

            <div class="span3">
                <ul class="nav nav-list nav-editMember nav-edit hidden-phone">
                    <li><a href="#editMember/personalDetail">Personal detail</a>
                    <li><a href="#editMember/language">Language</a>
                    <li><a href="#editMember/currentAddress">Current address</a>
                    <li><a href="#editMember/contactDetails">Contact details</a>
                    <li><a href="#editMember/documents">Documents</a>
                </ul>
            </div>

            <div class="span9">

                <!-- "id" is actually the memberProfileId, but to not have to rewrite the file upload let's do it like this -->
                <input type="hidden" name="memberProfileId"     />
                <input type="hidden" name="domain"              />

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editMember/personalDetail"></span>
                    <legend>Personal detail</legend>

                    <div class="row-fluid">
                        <div class="span6">

                            <div class="control-group formfield">
                                <label class="control-label">First name</label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.firstName" placeholder="Please type your first name">
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label">Last name</label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.lastName" placeholder="Please type your last name">
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label">Professional title</label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.professionalTitle" placeholder="Please type your professional title">
                                </div>
                            </div>
                        </div>

                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Profile image</label>
                                <div class="controls">
                                    <div class="profilePictureContainer" id="editMemberProfilePicture"></div>
                                    <input type="file" name="fileContent" data-type="fileUpload" data-type-arguments='{"url":"/wp-admin/admin-ajax.php?action=file_upload", "extraValues":[{"name": "uploadtype", "value":"memberprofilepicture"}], "addFields":["memberProfileId","domain"], "imageContainer": "#editMemberProfilePicture"}'/>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">

                            <div class="control-group formfield">
                                <label class="control-label">Gender</label>
                                <div class="controls">
                                    <label class="radio inline"><input type="radio" value="m" name="personalDetails.gender" data-toggle="radio"/> Male</label>
                                    <label class="radio inline"><input type="radio" value="f" name="personalDetails.gender" data-toggle="radio"/> Female</label>
                                </div>
                            </div>

                        </div>
                        <div class="span6">

                            <div class="control-group formfield">
                                <label class="control-label">Date of birth</label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.dateOfBirth" data-type="date" placeholder="Please type your date of birth">
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">

                            <div class="control-group formfield">
                                <label class="control-label">Nationality</label>
                                <div class="controls">
                                    <select name="personalDetails.nationality" ></select>
                                </div> <!-- // controls -->
                            </div> <!-- // control-group -->

                        </div>
                        <div class="span6">

                            <div class="control-group formfield">
                                <label class="control-label">Highest Education</label>
                                <div class="controls">
                                    <select name="personalDetails.highestEducation"></select>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">

                            <div class="control-group formfield" data-validation='{"typecheck": [{"email":{"text":"Please fill in a valid email address"}}]}'>
                                <label class="control-label">Email address</label>
                                <div class="controls">
                                    <input type="email" name="personalDetails.emailAddress" placeholder="Please type your email address" />
                                </div>
                            </div>

                        </div>
                        <div class="span6">

                            <div class="control-group formfield" >
                                <label class="control-label">LinkedIn profile</label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.linkedIn" placeholder="Please type your LinkedIn profile url" />
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">

                            <div class="control-group formfield">
                                <label class="control-label">Skype</label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.skype" placeholder="Please type your Skype identifier" />
                                </div>
                            </div>

                        </div>
                        <div class="span6">

                            <div class="control-group formfield">
                                <label class="control-label">Facebook profile</label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.facebook" placeholder="Please type your Facebook profile url" />
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">

                            <div class="control-group formfield">
                                <label class="control-label">Twitter</label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.twitter" placeholder="Please type your Twitter identifier" />
                                </div>
                            </div>

                        </div>
                        <div class="span6">

                        </div>
                    </div>
                </fieldset>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editMember/language"></span>
                    <legend>Language</legend>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield addLanguageGroup">
                                <label class="control-label">Select the languages you speak:</label>
                                <div class="controls">
                                    <div class="row-fluid">
                                        <div class="span8">
                                            <input type="text" name="addLanguage" autocomplete="off" disabled />
                                        </div>
                                        <div class="span4">
                                            <button type="button" class="btn btnAddLanguage pull-right" disabled>Add to list</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span4">
                            <strong>List of your languages</strong>
                        </div>
                        <div class="span4">
                            <strong>Choose your mother tongue</strong>
                        </div>
                    </div>

                    <div class="languageList clearfix"></div>
                </fieldset>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editMember/currentAddress"></span>
                    <legend>Your current address</legend>

                    <div class="row-fluid">
                        <div class="span6">

                            <input type="hidden" name="personalDetails.address[0].coordinates"    />

                            <div class="control-group formfield">
                                <label class="control-label">Country</label>
                                <div class="controls">
                                    <select name="personalDetails.address[0].country" ></select>
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label">City</label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.address[0].cityTown" placeholder="Please type your city" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label">Street</label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.address[0].street" placeholder="Please type your street" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label">Street number</label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.address[0].streetNumber" placeholder="Please type your street number" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label">Postal code</label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.address[0].postalCode" placeholder="Please type your postcode" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label">Neighborhood</label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.address[0].neighborhood" placeholder="Please type your neighborhood" />
                                </div>
                            </div>


                        </div>

                        <div class="span6">
                            <div class="currentAddressMap"></div>
                        </div>
                    </div>
                </fieldset>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editMember/contactDetails"></span>
                    <legend>Your contact details?</legend>

                    <div class="row-fluid">
                        <div class="span6">

                            <div class="control-group formfield">
                                <label class="control-label">Landline</label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.contactDetail[0].landLine" placeholder="Please type your landline number" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label">Mobile</label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.contactDetail[0].mobile" placeholder="Please type your mobile number" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label">Fax</label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.contactDetail[0].fax" placeholder="Please type your fax number" />
                                </div>
                            </div>

                        </div><!-- // span6 - left form column -->

                        <div class="span6">
                        </div>
                    </div>
                </fieldset>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editMember/documents"></span>
                    <legend>Documents</legend>

                    <div class="formfield">
                        <input type="file" name="attachment" data-type="fileUpload" data-type-arguments='{"url":"/wp-admin/admin-ajax.php?action=file_upload", "extraValues":[{"name": "uploadtype", "value":"memberprofileattachment"}], "addFields":["memberProfileId","domain"], "callback": "bidx.memberprofile.attachmentUploadDone"}'/>
                    </div>

                    <div class="attachmentsContainer"></div>
                </fieldset>
            </div>

        </form>
    </div>

    <div class="snippets hide">

        <!-- Language item -->
        <div class="row-fluid languageItem">
            <div class="span4">
                <label class="pull-left languageDescr"></label>
                <button class="btn pull-right btnRemoveLanguage"><i class="icon-trash"></i></button>
            </div>
            <div class="span4">
                <button class="btn btnSetMotherLanguage">This is your mother tongue</button>
                <p class="isCurrentMotherLanguage">My mother tongue</p>
            </div>
        </div>

        <!-- Attachment -->
        <div class="attachmentItem span4 well well-white">
            <div class="row-fluid">
                <div class="span4">
                    <a href="#" class="documentLink"><img class="img-rounded documentImage"></a>
                </div>
                <div class="span8">
                    <h3 class="documentName"></h3>
                    <p class="uploadedDateTime"></p>
                </div>
            </div>
            <a href="#removeItem" class="btn btn-danger btn-mini btn-block">Delete</a>
        </div>
    </div>

</div><!-- // row -->
