<div id="editMember" class="row-fluid mainState mainStateEditMember">

    <!-- LOAD -->
    <div class="view viewLoad span12">
        <span><?php _e('Retrieving member information...'); ?></span>
    </div>

    <!-- ERROR -->
    <div class="view viewError span12">
        <h2><?php _e('Error'); ?></h2>
        <p class="errorMsg"></p>
    </div>

    <!-- EDIT -->
    <div class="view viewEdit">

        <form id="frmeditMember">

            <div class="span3">
                <ul class="nav nav-list nav-editMember nav-edit hidden-phone">
                    <li><a href="#editMember/personalDetail"><?php _e('Personal detail'); ?></a>
                    <li><a href="#editMember/language"><?php _e('Language'); ?></a>
                    <li><a href="#editMember/currentAddress"><?php _e('Current address'); ?></a>
                    <li><a href="#editMember/contactDetails"><?php _e('Contact details'); ?></a>
                    <li><a href="#editMember/documents"><?php _e('Documents'); ?></a>
                </ul>
            </div>

            <div class="span9">

                <!-- "id" is actually the memberProfileId, but to not have to rewrite the file upload let's do it like this -->
                <input type="hidden" name="memberProfileId"     />
                <input type="hidden" name="domain"              />

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editMember/personalDetail"></span>
                    <legend><?php _e('Personal detail'); ?></legend>

                    <div class="row-fluid">
                        <div class="span6">

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('First name'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.firstName" placeholder="<?php _e('Please type your first name'); ?>">
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Last name'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.lastName" placeholder="<?php _e('Please type your last name'); ?>">
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Professional title'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.professionalTitle" placeholder="<?php _e('Please type your professional title'); ?>">
                                </div>
                            </div>
                        </div>

                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Profile image'); ?></label>
                                <div class="controls">
                                    <div class="profilePictureContainer" id="editMemberProfilePicture"></div>
                                    <input type="file" name="fileContent" data-type="fileUpload" data-type-arguments='{"url":"/wp-admin/admin-ajax.php?action=file_upload", "extraValues":[{"name": "uploadtype", "value":"memberprofilepicture"}], "addFields":["memberProfileId","domain"], "imageContainer": "#editMemberProfilePicture"}'/>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Gender'); ?></label>
                                <div class="controls">
                                    <label class="radio inline"><input type="radio" value="m" name="personalDetails.gender" data-toggle="radio"/> <?php _e('Male'); ?></label>
                                    <label class="radio inline"><input type="radio" value="f" name="personalDetails.gender" data-toggle="radio"/> <?php _e('Female'); ?></label>
                                </div>
                            </div>

                        </div>
                        <div class="span6">

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Date of birth'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.dateOfBirth" data-type="date" placeholder="<?php _e('Please type your date of birth'); ?>">
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Nationality'); ?></label>
                                <div class="controls">
                                    <select name="personalDetails.nationality" ></select>
                                </div> <!-- // controls -->
                            </div> <!-- // control-group -->

                        </div>
                        <div class="span6">

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Highest Education'); ?></label>
                                <div class="controls">
                                    <select name="personalDetails.highestEducation"></select>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">

                            <div class="control-group formfield" data-validation='{"typecheck": [{"email":{"text":"<?php _e('Please fill in a valid email address'); ?>"}}]}'>
                                <label class="control-label"><?php _e('Email address'); ?></label>
                                <div class="controls">
                                    <input type="email" name="personalDetails.emailAddress" placeholder="<?php _e('Please type your email address'); ?>" />
                                </div>
                            </div>

                        </div>
                        <div class="span6">

                            <div class="control-group formfield" >
                                <label class="control-label"><?php _e('LinkedIn profile'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.linkedIn" placeholder="<?php _e('Please type your LinkedIn profile url'); ?>" />
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Skype'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.skype" placeholder="<?php _e('Please type your Skype identifier'); ?>" />
                                </div>
                            </div>

                        </div>
                        <div class="span6">

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Facebook profile'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.facebook" placeholder="<?php _e('Please type your Facebook profile url'); ?>" />
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Twitter'); ?></label>
                                <div class="controls">
                                    <div class="input-prepend">
                                        <span class="add-on">@</span>
                                        <input type="text" name="personalDetails.twitter" placeholder="<?php _e('Please type your Twitter identifier'); ?>" />
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="span6">

                        </div>
                    </div>
                </fieldset>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editMember/language"></span>
                    <legend><?php _e('Language'); ?></legend>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield addLanguageGroup">
                                <label class="control-label"><?php _e('Select the languages you speak:'); ?></label>
                                <div class="controls">
                                    <div class="row-fluid">
                                        <div class="span8">
                                            <input type="text" name="addLanguage" autocomplete="off" disabled />
                                        </div>
                                        <div class="span4">
                                            <button type="button" class="btn btnAddLanguage pull-right" disabled><?php _e('Add to list'); ?></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span4">
                            <strong><?php _e('List of your languages'); ?></strong>
                        </div>
                        <div class="span4">
                            <strong><?php _e('Choose your mother tongue'); ?></strong>
                        </div>
                    </div>

                    <div class="languageList clearfix"></div>
                </fieldset>

                <fieldset class="well addressItem">
                    <span class="scrollPositionMarker" id="editMember/currentAddress"></span>
                    <legend><?php _e('Your current address'); ?></legend>

                    <div class="row-fluid">
                        <div class="span6">

                            <input type="hidden" name="personalDetails.address[0].coordinates"    />

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Country'); ?></label>
                                <div class="controls">
                                    <select name="personalDetails.address[0].country" ></select>
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('City'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.address[0].cityTown" placeholder="<?php _e('Please type your city'); ?>" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Street'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.address[0].street" placeholder="<?php _e('Please type your street'); ?>" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Street number'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.address[0].streetNumber" placeholder="<?php _e('Please type your street number'); ?>" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Postal code'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.address[0].postalCode" placeholder="<?php _e('Please type your postcode'); ?>" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Neighborhood'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.address[0].neighborhood" placeholder="<?php _e('Please type your neighborhood'); ?>" />
                                </div>
                            </div>


                        </div>

                        <div class="span6">
                            <div class="currentAddressMap"></div>
                        </div>
                    </div>
                </fieldset>

                <fieldset class="well contactDetailItem">
                    <span class="scrollPositionMarker" id="editMember/contactDetails"></span>
                    <legend><?php _e('Your contact details?'); ?></legend>

                    <div class="row-fluid">
                        <div class="span6">

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Landline'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.contactDetail[0].landLine" placeholder="<?php _e('Please type your landline number'); ?>" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Mobile'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.contactDetail[0].mobile" placeholder="<?php _e('Please type your mobile number'); ?>" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Fax'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.contactDetail[0].fax" placeholder="<?php _e('Please type your fax number'); ?>" />
                                </div>
                            </div>

                        </div><!-- // span6 - left form column -->

                        <div class="span6">
                        </div>
                    </div>
                </fieldset>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editMember/documents"></span>
                    <legend><?php _e('Documents'); ?></legend>

                    <div class="formfield">
                        <input type="file" name="attachment" data-type="fileUpload" data-type-arguments='{"url":"/wp-admin/admin-ajax.php?action=file_upload", "extraValues":[{"name": "uploadtype", "value":"memberprofileattachment"}], "addFields":["memberProfileId","domain"], "callback": "bidx.memberprofile.attachmentUploadDone"}'/>
                    </div>

                    <div class="attachmentsContainer"></div>
                </fieldset>
            </div>

        </form>
    </div>

    <div class="snippets hide">

        <!-- Language item -->
        <div class="row-fluid languageItem">
            <div class="span4">
                <label class="pull-left languageDescr"></label>
                <button class="btn pull-right btnRemoveLanguage"><i class="icon-trash"></i></button>
            </div>
            <div class="span4">
                <button class="btn btnSetMotherLanguage"><?php _e('This is your mother tongue'); ?></button>
                <p class="isCurrentMotherLanguage"><?php _e('My mother tongue'); ?></p>
            </div>
        </div>

        <!-- Attachment -->
        <div class="attachmentItem span4 well well-white">
            <div class="row-fluid">
                <div class="span4">
                    <a href="#" class="documentLink"><img class="img-rounded documentImage"></a>
                </div>
                <div class="span8">
                    <h3 class="documentName"></h3>
                    <p class="uploadedDateTime"></p>

                    <div class="control-group formfield">
                        <div class="controls">
                            <input type="text" name="purpose" placeholder="Short description">
                        </div>
                    </div>

                    <div class="control-group formfield">
                        <label class="control-label"><?php _e('Document type'); ?></label>
                        <div class="controls">
                            <select name="documentType"></select>
                        </div>
                    </div>
                </div>
            </div>
            <a href="#removeItem" class="btn btn-danger btn-mini btn-block"><?php _e('Delete'); ?></a>
        </div>
    </div>

</div><!-- // row -->
