<div id="editEntrepreneur" class="row-fluid mainState mainStateEditEntrepreneur">

    <!-- LOAD -->
    <div class="view viewLoad span12">
        <span>Retrieving entrepreneur information...</span>
    </div>

    <!-- ERROR -->
    <div class="view viewError span12">
        <h2>Error</h2>
        <p class="errorMsg"></p>
    </div>

    <!-- EDIT -->
    <div class="view viewEdit">

        <form id="frmeditEntrepreneur">

            <div class="span12">

                <!-- "id" is actually the entrepreneurProfileId, but to not have to rewrite the file upload let's do it like this -->
                <input type="hidden" name="entrepreneurProfileId"     />
                <input type="hidden" name="domain"              />

                <fieldset class="well">
                    <div class="row-fluid">
                        <div class="span12">

                            <div class="control-group formfield">
                                <label class="control-label">Summary</label>
                                <div class="controls">
                                    <textarea name="summary" placeholder="Please type the summary of your entrepreneurship" ></textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Focus industry</label>
                                <div class="controls">
                                    <select name="focusIndustry"></select>
                                </div>
                            </div>
                        </div>

                    </div>

                    <div class="row-fluid">
                        <div class="span6">

                            <div class="control-group formfield">
                                <label class="control-label">Have you ever own a business before?</label>
                                <div class="controls">
                                    <label class="radio inline"><input type="radio" value="true" name="prevRunBusiness" data-toggle="radio"/> Yes</label>
                                    <label class="radio inline"><input type="radio" value="false" name="prevRunBusiness" data-toggle="radio"/> No</label>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="toggle togglePrevRunBusiness intermediate-row">
                        <h3>Previous businesses</h3>
                        <a href="#addPreviousBusiness" class="btn btn-primary"><span class="fui-plus"></span>Add</a>
                    </div>

                    <div class="toggle togglePrevRunBusiness previousBusinessContainer"></div>

                </fieldset>

                <fieldset class="well">
                    <legend>CV</legend>

                    <div class="fow-fluid cvContainer">
                        <div class="span4">

                            <div class="hasCV">
                                <h3 class="documentName"></h3>
                                <p class="uploadedDateTime"></p>

                                <a href="#" class="documentLink">Download CV</a>
                            </div>

                            <div class="noCV">
                                <i>No CV uploaded yet</i>
                            </div>

                        </div>
                        <div class="span8 formfield">
                            <p><span class="hasCV">Or u</span><span class="noCV">U</span>pload a <span class="hasCV">new </span> document:</p>
                            <input type="file" name="attachment" data-type="fileUpload" data-type-arguments='{"url":"/wp-admin/admin-ajax.php?action=file_upload", "extraValues":[{"name": "uploadtype", "value":"entrepreneurprofilecv"}], "addFields":["entrepreneurProfileId","domain"], "callback": "bidx.entrepreneurprofile.cvUploadDone"}'/>
                        </div>
                    </div>
                </fieldset>

                <fieldset class="well">
                    <legend>Other documents</legend>

                    <div class="attachmentsContainer">
                        <div class="row-fluid"></div>
                    </div>

                    <div class="row-fluid">

                        <div class="span4 addAttachment well well-white">
                            <div class="fow-fluid">
                                <div class="span4">
                                    <img src="/wp-content/plugins/bidx-plugin/static/img/iconAddDocument.png">
                                </div>
                                <div class="span8 formfield">
                                    <p>Upload a new document:</p>

                                    <input type="file" name="attachment" data-type="fileUpload" data-type-arguments='{"url":"/wp-admin/admin-ajax.php?action=file_upload", "extraValues":[{"name": "uploadtype", "value":"entrepreneurprofileattachment"}], "addFields":["entrepreneurProfileId","domain"], "callback": "bidx.entrepreneurprofile.attachmentUploadDone"}'/>
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>

        </form>
    </div>

    <div class="snippets hide">
        <div class="previousBusinessItem span4 well well-white">
            <div class="control-group formfield">
                <label class="control-label">Name of company</label>
                <div class="controls">
                    <input type="text" name="company" placeholder="Please type the name of the company">
                </div>
            </div>

            <div class="control-group formfield">
                <label class="control-label">What happened?</label>
                <div class="controls">
                    <select name="businessOutcome"></select>
                </div>
            </div>

            <div class="control-group formfield">
                <label class="control-label">Company web-site?</label>
                <div class="controls">
                    <input type="text" name="webSite" placeholder="Please type the URL of the company">
                </div>
            </div>

            <a href="#removeItem" class="btn btn-danger btn-mini btn-block">Remove this business</a>
        </div>

        <div class="attachmentItem span4 well well-white">
            <div class="row-fluid">
                <div class="span4">
                    <a href="#" class="documentLink"><img class="img-rounded documentImage"></a>
                </div>
                <div class="span8">
                    <h3 class="documentName"></h3>
                    <p class="uploadedDateTime"></p>

                    <div class="control-group formfield">
                        <div class="controls">
                            <input type="text" name="purpose" placeholder="Short description">
                        </div>
                    </div>

                    <div class="control-group formfield">
                        <label class="control-label">Document type</label>
                        <div class="controls">
                            <select name="documentType"></select>
                        </div>
                    </div>

                    <a href="#deleteAttachment" class="btn btn-danger btn-mini pull-right">Delete</a>
                </div>
            </div>
        </div>
    </div>

</div><!-- // row -->
