<div id="editInvestor" class="row-fluid mainState mainStateEditInvestor">

    <!-- LOAD -->
    <div class="view viewLoad span12">
        <span>Retrieving investor information...</span>
    </div>

    <!-- ERROR -->
    <div class="view viewError span12">
        <h2>Error</h2>
        <p class="errorMsg"></p>
    </div>

    <!-- EDIT -->
    <div class="view viewEdit">

        <form id="frmeditInvestor">

            <div class="span3">
                <ul class="nav nav-list nav-edit nav-editInvestor hidden-phone">
                    <li><a href="#editInvestor/generalInformation">General information</a>
                    <li><a href="#editInvestor/investmentPreferences">Investment preferences</a>
                    <li><a href="#editInvestor/investmentHistory">Investment history</a>
                    <li><a href="#editInvestor/references">References</a>
                    <li><a href="#editInvestor/documents">Documents</a>
                </ul>
            </div>

            <div class="span9">

                <!-- "id" is actually the memberProfileId, but to not have to rewrite the file upload let's do it like this -->
                <input type="hidden" name="investorProfileId"     />
                <input type="hidden" name="domain"              />

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editInvestor/generalInformation"></span>
                    <legend>General information</legend>

                    <div class="row-fluid">
                        <div class="span12">

                            <div class="control-group formfield">
                                <label class="control-label">Describe yourself as investor</label>
                                <div class="controls">
                                    <textarea name="summary" placeholder="Please type the summary of yourself as investor" ></textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">

                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Do you invest on behalf of an institution?</label>
                                <div class="controls">
                                    <label class="radio inline"><input type="radio" value="true"  name="investsForInst" data-toggle="radio"/> Yes</label>
                                    <label class="radio inline"><input type="radio" value="false" name="investsForInst" data-toggle="radio"/> No</label>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid toggle toggle-investsForInst">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Institution type</label>
                                <div class="controls">
                                    <select name="investorType"></select>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid toggle toggle-investsForInst">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Institution name</label>
                                <div class="controls">
                                    <input type="text" name="institutionName" placeholder="Please type the name of the institution">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid toggle toggle-investsForInst">
                        <div class="span6">
                            <div class="control-group formfield" data-validation='{"typecheck": [{"url":{"text":"Please fill in a valid URL"}}]}'>
                                <label class="control-label">Institution website</label>
                                <div class="controls">
                                    <input type="text" name="institutionWebsite" placeholder="Please type the website of the institution">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">

                            <input type="hidden" name="institutionAddress.coordinates"    />

                            <div class="control-group formfield">
                                <label class="control-label">Country</label>
                                <div class="controls">
                                    <select name="institutionAddress.country" ></select>
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label">City</label>
                                <div class="controls">
                                    <input type="text" name="institutionAddress.cityTown" placeholder="Please type your city" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label">Street</label>
                                <div class="controls">
                                    <input type="text" name="institutionAddress.street" placeholder="Please type your street" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label">Street number</label>
                                <div class="controls">
                                    <input type="text" name="institutionAddress.streetNumber" placeholder="Please type your street number" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label">Postal code</label>
                                <div class="controls">
                                    <input type="text" name="institutionAddress.postalCode" placeholder="Please type your postcode" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label">Neighborhood</label>
                                <div class="controls">
                                    <input type="text" name="institutionAddress.neighborhood" placeholder="Please type your neighborhood" />
                                </div>
                            </div>


                        </div>

                        <div class="span6">
                            <div class="currentAddressMap"></div>
                        </div>
                    </div>

                </fieldset>


                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editInvestor/investmentPreferences"></span>
                    <legend>Investment preferences</legend>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Industry</label>
                                <div class="controls">
                                    <input type="text" name="focusIndustry" class="bidx-tagsinput disabled" disabled data-bidxdatakey="industry" placeholder="Focus industry">
                                </div>
                            </div>
                        </div>

                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Social impact</label>
                                <div class="controls">
                                    <input type="text" name="focusSocialImpact" class="bidx-tagsinput disabled" disabled data-bidxdatakey="socialImpact" placeholder="Social impact">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Environmental impact</label>
                                <div class="controls">
                                    <input type="text" name="focusEnvImpact" class="bidx-tagsinput disabled" disabled data-bidxdatakey="envImpact" placeholder="Environmental impact">
                                </div>
                            </div>
                        </div>

                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Consumer type</label>
                                <div class="controls">
                                    <input type="text" name="focusConsumerType" class="bidx-tagsinput disabled" disabled data-bidxdatakey="consumerType" placeholder="Consumer type">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label">Languages</label>
                                <div class="controls">
                                    <input type="text" name="focusLanguage" class="bidx-tagsinput disabled" disabled data-bidxdatakey="language" placeholder="Languages">
                                </div>
                            </div>
                        </div>
                    </div>

                </fieldset>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editInvestor/investmentHistory"></span>
                    <legend>Investment history</legend>

                    <div class="row-fluid">
                        <div class="span6">

                        </div>
                        <div class="span6">

                        </div>
                    </div>
                </fieldset>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editInvestor/references"></span>
                    <legend>References</legend>
                </fieldset>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editInvestor/documents"></span>
                    <legend>Documents</legend>

                    <div class="row-fluid attachments">
                        <div class="span6 attachmentList">
                        </div>

                        <div class="span6 addAttachment">
                            <div class="fow-fluid">
                                <div class="span4">
                                    <img src="/wp-content/plugins/bidx-plugin/static/img/iconAddDocument.png">
                                </div>
                                <div class="span8 formfield">
                                    <input type="file" name="attachment" data-type="fileUpload" data-type-arguments='{"url":"/wp-admin/admin-ajax.php?action=file_upload", "extraValues":[{"name": "uploadtype", "value":"investorprofileattachment"}], "addFields":["investorProfileId","domain"], "callback": "bidx.investorprofile.attachmentUploadDone"}'/>
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>

        </form>
    </div>

    <div class="snippets hide">
        <div class="previousInvestmentItem">
            Previousinvestment item.
        </div>

        <div class="fow-fluid clearfix attachmentItem">
            <div class="span4">
                <a href="#" class="documentLink"><img class="img-rounded documentImage"></a>
            </div>
            <div class="span8">
                <h3 class="documentName"></h3>
                <p class="uploadedDateTime"></p>
                <a href="#deleteAttachment" class="btn">Delete</a>
            </div>
        </div>
    </div>

</div><!-- // row -->
