<?php

$member = $this->exst($this->data->member->displayName);
?>
<div class="block-odd">
    <div class="pageHeader clearfix">
      <div class="container clearfix">
        <h1 class="pull-left"><?php echo ($this->data->isMyProfile) ? 'My Profile' : $member; ?></h1>
        <div class="editControls btn-group"></div>
      </div>
    </div>

    <div class="row-fluid mainState mainStateShow">
      <div class="span8">
        <?php $this->render('view-member.phtml');  ?>
        <?php $this->render('view-entrepreneur.phtml'); ?>
        <?php $this->render('view-investor.phtml'); ?>
      </div>
      <div class="span4 sidebar">
        <?php $this->render('view-group.phtml'); ?>
      </div>
    </div>
    <div class="row-fluid">
        <div class="span6">
           <?php echo do_shortcode( '[bidx app="auth" view="standard-auth" type="login"]' ); ?>
        </div>
        <div class="span6">
            <?php echo do_shortcode( '[bidx app="auth" view="standard-auth" type="register"]' ); ?>
        </div>

    </div>

    <?php $this->render('edit-member.phtml'); ?>
    <?php $this->render('edit-entrepreneur.phtml'); ?>
    <?php $this->render('edit-investor.phtml'); ?>
</div>
