<?php $personalDetails = $this->data->bidxMemberProfile->personalDetails; ?>

<div class="row-fluid">
  <div class="span12">
    <h4>Entrepreneur profile</h4>
  </div>
</div>
<div class="row-fluid">
  <?php
  $rowValues = array('Summary' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s.');
  echo $this->addRowsWithLabelBelow('span12', 'span12', $rowValues, array('tag_label' => 'h5'));
  ?>
  <br/>
  <?php
  $rowValues = array('Focus Industry' => 'Lorem Ipsum');
  echo $this->addRowsWithLabelAdjacent('span6', 'span6', $rowValues, array('tag_label' => 'h5'));
  ?>
  <br/>
  <?php
  $rowValues = array('Previous Business(es)' => 'Table');
  echo $this->addRowsWithLabelBelow('span12', 'span12', $rowValues, array('tag_label' => 'h5'));
  ?>
  <br/>
  <?php
  $rowValues = array('Documents' => array('Document1', 'Document2'));
  echo $this->addRowsWithLabelBelow('span12', 'span12', $rowValues, array('tag_label' => 'h5'));
  ?>
</div>
<br/>
<!-- Company Profile -->
<div class="row-fluid">
  <div class="span12">
    <h4>This person has a business</h4>
  </div>
</div>

<div class="row-fluid">
  <div class="span3">
    <h4>Member</h4>
    <img src="http://placehold.it/150x175" class="img-rounded"></div>
  <div class="span7"><br/>
    <div class="row-fluid">
      <div class="span12"><h4>Name Business</h4></div>
      <!-- Personal details 6/6 Start -->

      <?php
      $rowValues = array('Tagline',
        'Summary',
        'Industry',
        'Location');
      echo $this->addMultipleRows('span12', $rowValues);
      echo $this->addMultipleRows('span12 offset10', array('view more'));
      ?>



    </div>
  </div>
</div>






