<?php

?>
            <fieldset>
              <legend>Member</legend>
              <div class="row-fluid">
                <div class="span4"><img src="https://test.bidx.net/dl/document/369/iis.jpg" class="img-rounded"></div>
                <div class="span8">
                  <div class="row-fluid">
                    <div class="span12"><h4><?php echo $this->data->displayName; ?></h4>
                      <!-- Personal details 6/6 Start -->
                      <div class="row-fluid">
                        <?php
                          //NO language variable
                          $rowValues = array($this->data->personalDetails->professionalTitle,
                                             $this->data->personalDetails->gender,
                                             $this->data->personalDetails->nationality,
                                             $this->data->personalDetails->dateOfBirth,
                                             $this->data->personalDetails->highestEducation,
                                            'Spanish',
                                            'I speak Dutch and English',
                                            'Current Address',
                                            'CV Name');
                          echo $this->addRows('12',$rowValues);
                        ?>
                                      
                      </div>
                  
                      <div class="row-fluid">
                        <div class="span6">
                          <span class="label label-info">E-mail</span>
                        </div>
                        <div class="span6">
                          <span class="label label-info">Mobile</span>
                        </div>
                      </div>
                      <div class="row-fluid">
                        <div class="span6">
                          <span class="label label-info">Landline</span>
                        </div>
                        <div class="span6">
                          <span class="label label-info">Linkedin</span>
                        </div>
                      </div>
                      <div class="row-fluid">
                        <div class="span6">
                          <span class="label label-info">Fax</span>
                        </div>
                        <div class="span6">
                          <span class="label label-info">Skype</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </fieldset>
          

