<?php
$entrepreneurDetails = $this->data->bidxEntrepreneurProfile;
$entityDetails = $this->data->entities;
$companies = $this->data->companies;

if ($entrepreneurDetails) {
  ?>

<div class="well profile-block">

  <div class="btn-group controls">
  <?php if ($entrepreneurDetails->bidxCanEdit) { ?>
    <a class="btn btn-primary" href="#editEntrepreneur/<?php echo $entrepreneurDetails->ownerId; ?>">Edit</a>
  <?php } ?>
  </div>

  <h4>Entrepreneur profile</h4>
  <div class="row-fluid">
    <?php
    $rowValues = array('Summary' => $entrepreneurDetails->entrepreneurProfileSummary);
    echo $this->addRowsWithLabelBelow('span12', 'span12', $rowValues, array('tag_label' => 'h5'));
    ?>
    <br/>
    <?php
    $focusIndustry = $this->getMultiValues($entrepreneurDetails->focusIndustry, ', ');
    $rowValues = array('Focus Industry' => $focusIndustry);
    echo $this->addRowsWithLabelAdjacent('span6', 'span6', $rowValues, array('tag_label' => 'h5', 'class_value' => 'adjacentval' ));
    ?>
    <br/>
    <?php
    $header = array('Name of Company' => 'company', 'Outcome of business' => 'businessOutcome', 'Url of company website' => 'webSite');
    $previousBusinessHtml = $this->addTableRows($header, $entrepreneurDetails->previousBusiness, 'table table-bordered');

    $rowValues = array('Previous Business(es)' => $previousBusinessHtml);
    echo $this->addRowsWithLabelBelow('span12', 'span12', $rowValues, array('tag_label' => 'h5'));
    ?>
    <br/>
    <?php
    echo $this->getAttachmentsDisplay('12', '12', array('Documents' => $entrepreneurDetails1->attachment));
    ?>
  </div>
</div>
<? }

// Business Summary
//
if($entityDetails) {
?>
<div class="well profile-block">

  <!-- Business Summaries Profile -->
  <div class="row-fluid">
    <div class="span12">
      <h4><?php echo ($this->data->isMyProfile) ? 'My business' : 'This person has a business'; ?></h4>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span3">
      <img data-src="holder.js/100x100/industrial/auto/text:No Image" class="img-rounded">
    </div>
    <div class="span7">
      <div class="row-fluid">
        <div class="span12">
          <h5><?php echo $entityDetails->name;?></h5>
        </div>
      </div>
        <!-- Personal details 6/6 Start -->

        <?php
        $industryVal = $this->getMultiValues($entityDetails->industry, ', ');
        $countryVal  = $this->getMultiValues($entityDetails->countryOperation, ', ','country','country');
        $joinLink = ($entityDetails->bidxEntityId) ? "<a href='/businessplan/".$entityDetails->bidxEntityId."'>view more</a>":'';
        $rowValues = array( $entityDetails->slogan,
          $entityDetails->summary,
          $industryVal,
          $countryVal);
        echo $this->addMultipleRows('span12', $rowValues);

        echo $this->addMultipleRows('span12 offset10', array($joinLink));
        ?>
    </div>
  </div>
</div>
<?php
}

// Companies listing
//
if ( $companies ) {
?>
<div class="accordion" id="companies">
<?php
  foreach ( $companies as $index => $company ) {

    $collapseId = sprintf( 'companyAccordion-%s', $company->bidxEntityId );

    $useDataSrc = false;
    $picSrc     = $company->logo->document;

    if (!$picSrc ) {
      $picSrc     = 'holder.js/100x100/industrial/auto/text:No Image';
      $useDataSrc = true;
    }
?>
  <div class="accordion-group">
    <div class="accordion-heading">
      <a class="accordion-toggle <?php echo ( $index != 0 ) ? 'collapsed' : ''; ?>" data-toggle="collapse" data-parent="#companies" href="#<?php echo $collapseId ?>">
        <h4><?php echo $company->name ?></h4>
        <div class="controls">
          <span class="bidx-expand">+</span>
          <span class="bidx-collapse">-</span>
        </div>
      </a>
    </div><!-- accordion-heading -->
    <div id="<?php echo $collapseId ?>" class="accordion-body collapse <?php echo ( $index == 0 ) ? 'in' : ''; ?>">
      <div class="accordion-inner">
        <div class="row-fluid">
          <div class="span4">
            <img <?php $useDataSrc ? "data-" : "" ?>src="<?php echo $picSrc ?>" class="img-rounded">
          </div>
          <div class="span8">
            <ul class="unstyled">
            <?php
              printf( '<li>%s</li>', $company->name );

              if ( $company->website ) {
                printf( '<li>%s</li>', $company->website );
              }

              if ( $company->registered ) {
                printf( '<li>%s</li>', date( 'd-m-Y', strtotime( $company->dateCompanyEstab )) );

                $arStatutoryAddress = array();

                if ( $company->statutoryAddress->street )
                {
                    $arStatutoryAddress[] = $company->statutoryAddress->street;
                }

                if ( $company->statutoryAddress->streetNumber )
                {
                    $arStatutoryAddress[] = $company->statutoryAddress->streetNumber;
                }

                if ( $company->statutoryAddress->postalCode )
                {
                    $arStatutoryAddress[] = $company->statutoryAddress->postalCode;
                }


                $arStatutoryCityCountry = array();

                if ( $company->statutoryAddress->cityTown )
                {
                    $arStatutoryCityCountry[] = $company->statutoryAddress->cityTown;
                }

                if ( $company->statutoryAddress->country )
                {
                    $arStatutoryCityCountry[] = $company->statutoryAddress->country;
                }

                printf( '<li>%s</li>', implode( ' ', $arStatutoryAddress ) );
                printf( '<li>%s</li>', implode( ' ', $arStatutoryCityCountry ) );
              }
            ?>
            </ul>
          </div>
        </div>

        <div class="controls">
        <?php
          $viewMoreLink = "<a href='/company/". $company->ownerId ."'>view more</a>";
          echo $viewMoreLink;
        ?>
        </div>
      </div>
    </div><!-- accordion-body -->
  </div><!-- accordion-group -->
<?php
  }
?>
</div><!-- accordion #companies -->
<?php
}

if ( $this->data->isMyProfile ) {
?>

<div class="pull-right">
  <a href="/company/#createCompany" class="btn btn-primary">Add a company</a>
</div>

<?php } ?>




