<?php

$groupDetails = $this->data->groups;
$showGroup = (count( (array)$groupDetails)) ? true : false;

?>
<!-- Group Info -->
<?php
    if($showGroup) {
        foreach ($groupDetails as $groupValue) {
            if (strtolower(str_replace(" ","",$groupValue->name)) == strtolower(str_replace(" ","",$this->bidxGroupDomain))) {
?>
<div class="well sidebar-block">
    <div class="row-fluid sidebar-block-heading">
        <div class="span4"><img data-src="holder.js/100x100/industrial/auto/text:No Image" class="img-rounded"></div>
        <div class="span8 sidebar-block-intro">
            <h3 class="sidebar-block-title"><?php echo $this->bidxGroupDomain ?></h3>
            <p><?php echo $groupValue->slogan ?></p>
        </div>
    </div>

    <!-- Description -->
    <p class="sidebar-block-content"><?php echo $groupValue->description;?></p>

    <!-- Company name , URL -->
    <div class="row-fluid">
<?php
        $rowValues = array('Company name' => 'www.companyurl.com' );
        echo $this->addRowsWithLabelAdjacent('span6','span6',$rowValues);
?>
    </div>
</div>
<?php
            }
        }
    }
?>

<div class="well sidebar-block">
    <!-- Joined Group -->
    <h3>Joined groups</h3>

<?php
    foreach( $groupDetails as $groupValue) {
        $joinLink = "<a href='#joinGroup/".$groupValue->bidxGroupId."'>Join</a>";
?>
    <div class="clearfix">
        <div class="row-fluid sidebar-block-heading">
            <div class="span4"><img data-src="holder.js/100x100/industrial/auto/text:No Image" class="img-rounded"></div>
            <div class="span8 sidebar-block-intro">
                <h4 class="sidebar-block-title"><?php echo $groupValue->name?></h4>
                <p><?php echo $groupValue->slogan?></p>
            </div>
        </div>
        <div class="pull-right"><a href='#joinGroup/<?php echo $groupValue->bidxGroupId?>'>Join</a></div>
    </div>
<?php } ?>
</div>
