<?php 

$groupDetails = $this->exst ($this->data->groups);

$showGroup = (count( (array)$groupDetails)) ? true : false;

?>
<!-- Group Info -->
<?php
    if($showGroup) {
        foreach ($groupDetails as $groupValue) {
            if (strtolower(str_replace(" ","",$groupValue->name)) == strtolower(str_replace(" ","",$this->bidxGroupDomain))) {
              $groupDataSrc = false;
              $picSrc     = $groupValue->logo;

              if (!$groupValue->logo) {
                $picSrc     = 'holder.js/100x100/industrial/auto/text:No Image';
                $groupDataSrc = true;
              }

?>
<div class="well sidebar-block">
    <div class="row-fluid sidebar-block-heading">
        <div class="span4"><img width="100" height="100" <?php $groupDataSrc ? "data-" : "" ?>src="<?php echo $picSrc ?>" class="img-rounded"></div>
        <div class="span8 sidebar-block-intro">
            <h3 class="sidebar-block-title"><?php echo $this->bidxGroupDomain ?></h3>
            <p><?php echo $groupValue->slogan ?></p>
        </div>
    </div>

    <!-- Description -->
    <p class="sidebar-block-content"><?php echo $groupValue->description;?></p>

    <!-- Company name , URL -->
    <div class="row-fluid">
<?php
        //$rowValues = array('Company name' => $groupValue->bidxGroupUrl );
        //echo $this->addRowsWithLabelAdjacent('span6','span6',$rowValues);
?>
    </div>
</div>
<?php
            }
        }
    }


if( $groupDetails ) { ?>
<div class="well sidebar-block">
    <!-- Joined Group -->
    <h3>Joined groups</h3>

<?php
    foreach( $groupDetails as $groupValue) {
        $joinLink = ($this->exst($groupValue->join)) ? "<a href='#joinGroup/".$groupValue->bidxGroupId."'>Join</a>":'';
        $groupDataSrc = false;
              $picSrc     = $this->exst($groupValue->logo);

              if (!$picSrc) {
                $picSrc     = 'holder.js/100x100/industrial/auto/text:No Image';
                $groupDataSrc = true;
              }
?>
    <div class="clearfix">
        <div class="row-fluid sidebar-block-heading">
            <div class="span4"><img width="100" height="100" <?php $groupDataSrc ? "data-" : "" ?>src="<?php echo $picSrc ?>" class="img-rounded"></div>
            <div class="span8 sidebar-block-intro">
                <h4 class="sidebar-block-title"><?php echo $groupValue->name?></h4>
                <p><?php echo $groupValue->slogan?></p>
            </div>

        </div>
        <div class="pull-right"><?php echo $joinLink ?></div>
    </div>
<?php } ?>
</div>
<? } ?>
