<?php
//echo "<pre>";
//print_r($this->data);
//echo "</pre>";
//exit;
?>
  <div class="row-fluid">
          <div class="span7">
            <fieldset>
              <legend>Member</legend>
              <div class="row-fluid">
                <div class="span4"><img src="https://test.bidx.net/dl/document/369/iis.jpg" class="img-rounded"></div>
                <div class="span8">
                  <div class="row-fluid">
                    <div class="span12"><h4><?php echo $displayData->displayName; ?></h4>
                      <!-- Personal details 5/5 Start -->
                      <div class="row-fluid">
                        <div class="span6">
                          <div> <?php echo ($displayData->personalDetails->gender == 'm') ? 'Male' : 'Female' ?> </div>
                          <div> Date</div>
                          <div> Spanish</div>
                        </div>
                        <div class="span6">
                          <div> Professional title </div>
                          <div> Highest education</div>
                          <div> Nationality</div>
                        </div>
                      </div>
                      <div class="row-fluid">
                        <div class="span8">I Speak Dutch English</div>
                      </div>
                      <div class="row-fluid">
                        <div class="span4">
                          <span class="label label-info">E-mail</span>
                        </div>
                        <div class="span4">
                          <span class="label label-info">Mobile</span>
                        </div>
                      </div>
                      <div class="row-fluid">
                        <div class="span4">
                          <span class="label label-info">Landline</span>
                        </div>
                        <div class="span4">
                          <span class="label label-info">Linkedin</span>
                        </div>
                      </div>
                      <div class="row-fluid">
                        <div class="span4">
                          <span class="label label-info">Fax</span>
                        </div>
                        <div class="span4">
                          <span class="label label-info">Skype</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </fieldset>
          </div>
        </div>

