<?php
if ( property_exists($this -> group, 'data') ) {
?>
<div class="well">
	<div class="row">
		<div class="media img-rounded">
			<div class="media-body centering">
				<h3 class="media-heading">About Us</h3>
				<h5><?php echo $this -> group -> data -> bidxGroupProfile -> slogan ?></h5>
				<p><?php echo $this -> group -> data -> bidxGroupProfile -> description ?></p>
			</div>
		</div>
	</div>
</div>
<?php
}
?>
