<div id="groupHome" class="outer-content-container mainState mainStateShow mainStateGroupHome">
    <div class="container">
<?php
        echo bidx_get_status_msgs();
?>
    </div>

<?php
    // include the carousel ( id=groupCarousel )
    //
    require_once "inc/inc_carousel.phtml";
?>
    <div class="container">
        <div class="clearfix">
            <h1 class="pull-left bidx-page-heading">
                <span class="members hide">Members</span>
                <span class="businesssummaries hide">Busines Summaries</span>
            </h1>
        </div>
        <div class="row">

            <!-- CONTENT Block -->
            <div class="col-sm-8">

                <section class="views">

                    <div class="view viewLoad alert alert-info text-center">
                        <div class="progress progress-striped active">
                            <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                                <?php _e('Loading...','bidxplugin')?>
                            </div>
                        </div>
                    </div>

                    <article class="view viewError alert alert-warning">
                        <h1><?php _e('Error','bidxplugin')?></h1>
                        <span class="errorMsg"></span>
                    </article>

                    <!-- Home VIEW -->
                    <article class="view viewHome viewInitial">
                        <!-- NEWS BLOCK -->
                        <div class="panel panel-primary">
                            <div class="panel-heading hide-overflow">
                                <h4 class="pull-left">
                                    <?php _e('News and Events','bidxtheme')?>
                                </h4>
                                <a href="#home/news" class="pull-right btn btn-info"><?php _e('view all','bidxtheme')?></a>
                            </div>
                            <div class="panel-body">
                                <div class="bidx-latest clearfix">
                                    <!-- Grab news -->
<?php
                                    echo do_shortcode( '[bidx app="group" view="latest-news"]' );
?>
                                </div>
                            </div>
                        </div>

                        <!-- BUSINESS BLOCK -->
                        <div class="panel panel-primary">
                            <div class="panel-heading hide-overflow">
                                <h4 class="pull-left">
                                    <?php _e('New Business Summaries','bidxtheme')?>
                                </h4>
                                <a href="#home/businesssummaries" class="pull-right btn btn-info"><?php _e('view all','bidxtheme')?></a>
                            </div>
                            <div class="panel-body">
                                <div class="bidx-latest clearfix">
                                <!-- Grab latests members -->
<?php
                                    echo do_shortcode( '[bidx app="group" view="latest-business-summaries"]' );
?>
                                </div>
                            </div>
                        </div>

                        <!-- MEMBERS BLOCK -->
                        <div class="panel panel-primary">
                            <div class="panel-heading hide-overflow">
                                <h4 class="pull-left">
                                    <?php _e('New members in the group','bidxtheme')?>
                                </h4>
                                <a href="#home/members" class="pull-right btn btn-info"><?php _e('view all','bidxtheme')?></a>
                            </div>
                            <div class="panel-body">
                                <div class="bidx-latest clearfix">
                                <!-- Grab latests members -->
<?php
                                    $joinedGroup = $this->joinedGroup ? "true" : "false";
                                    echo do_shortcode( '[bidx app="group" view="last-members" authenticated="true" joinedgroup="' . $joinedGroup . '"]' );

?>
                                </div>

                            </div>
                        </div>
                    </article>

                    <!-- BusinessSummaries VIEW -->
                    <article class="view viewBusinessSummaries">
                         <ul class="media-list js-businessSummaries-list">
                        </ul>
                        <div class="pagerContainer">
                            <ul class="pager"></ul>
                        </div>
                    </article>

                    <!-- Members VIEW -->
                    <article class="view viewMembers">
                        <ul class="media-list js-member-list">
                        </ul>
                        <div class="pagerContainer">
                            <ul class="pager"></ul>
                        </div>
                    </article>

                    <!-- news VIEW -->
                    <article class="view viewNews">
                        <div class="newsList clearfix">

                        </div>
                        <div class="pagerContainer">
                            <ul class="pager"></ul>
                        </div>
                    </article>
                </section>

            </div>


            <!-- SIDE BAR -->
            <div class="col-sm-4">
                <div class="side-bar well sideBar">
                <h2><?php _e('Create and grow', 'bidxtheme')?></h2>
<?php
                    echo do_shortcode( '[bidx app="member" view="entrepreneur-profile-links"]' );
                    echo do_shortcode( '[bidx app="member" view="investor-profile-links"]' );
?>
                </div>
            </div>
        </div>



    </div>

    <div class="snippets hide">
        <!--
            I use %value% for explanatory reasons within the markup body and as placeholders within href links
        -->

        <!-- member Snippet -->
        <div class="snippet" data-key="member">


            <li class="media well">
                <a class="pull-left" href="/member/%memberId%" data-role="memberImage">
                    <div class="icons-circle pull-left"><i class="fa fa-user text-primary-light"></i></div>
                </a>
                <div class="media-body">
                    <h4 class="media-heading">
                        <a href="/member/%memberId%" data-role="memberLink">%firstname% %lastname%</a>
                    </h4>
                    <div data-role="country"></div>
                    <div data-role="roles">
                        <span class="label" data-role="value">test</span>
                    </div>
                    <div>
                        <a href="/mail/#mail/contacts/action=connect&amp;id=%memberId%" data-role="memberId"><?php _e('Connect','bidxtheme')?></a>
                    </div>
                    <div class="pull-right">
                        <a href="/member/%memberId%" data-role="memberView"><?php _e('View profile','bidxtheme')?></a>
                    </div>
                </div>
            </li>

        </div>

        <!-- businessSummary Snippet -->
        <div class="snippet" data-key="businessSummary">


            <li class="media well">
                <a class="pull-left" href="/businessSummary/%businessSummaryId%" data-role="businessSummaryImage">
                    <img src="/wp-content/themes/bidx-group-template/assets/img/mock/new-business.png" alt="" class="media-object img-circle">
                </a>
                <div class="media-body">
                    <h4 class="media-heading">
                        <a href="/businessSummary/%businessSummaryId%" data-role="businessSummaryLink">%name%</a>
                    </h4>
                    <div data-role="summary"></div>
                    <div data-role="slogan"></div>
                    <div data-role="industry"></div>
                    <div data-role="country"></div>
                   
                    <div class="pull-right">
                        <a href="/businessSummary/%businessSummaryId%" data-role="businessSummaryView"><?php _e('View Business Summary','bidxtheme')?></a>
                    </div>
                </div>
            </li>

        </div>

        <!-- news Snippet -->
        <div class="snippet" data-key="news">
            <div class="col-sm-12 clearfix well">
                <h2 data-role="title"><span class="header-meta pull-right" data-role="date">%date%</span></h2>
                <div data-role="content"></div>
            </div>
        </div>

    </div>
</div>
