<div id="groupHome" class="container mainState mainStateShow mainStateGroupHome">

<?php
    if ( bidx_get_status_msgs() != NULL ) {
?>
    <div class="row">
        <div class="col-sm-12">
<?php
        echo bidx_get_status_msgs();
?>
        </div>
    </div>
<?php
    }
?>

<?php
    // include the carousel ( id=groupCarousel )
    //
    require_once "inc/inc_carousel.phtml";
?>

        <div class="row">

            <!-- CONTENT Block -->
            <div class="col-sm-8">

                <section class="views">

                    <div class="view viewLoad alert alert-info text-center">
                        <div class="progress progress-striped active">
                            <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                                <?php _e('Loading...','bidxplugin')?>
                            </div>
                        </div>
                    </div>

                    <article class="view viewError alert alert-warning">
                        <h1><?php _e('Error','bidxplugin')?></h1>
                        <span class="errorMsg"></span>
                    </article>

                    <!-- Home VIEW -->
                    <article class="view viewHome viewInitial">
                        <!-- NEWS BLOCK -->
                        <div class="panel panel-primary panel-news">
                            <div class="panel-heading hide-overflow">
                                <h4 class="pull-left">
                                    <?php _e('News and Events','bidxplugin')?>
                                </h4>
                                <a href="#home/news" class="pull-right btn btn-info"><?php _e('view all','bidxplugin')?></a>
                            </div>
                            <div class="panel-body">
                                <div class="bidx-latest clearfix">
                                    <!-- Grab news -->
<?php
                                    echo do_shortcode( '[bidx app="group" view="latest-news"]' );
?>
                                </div>
                            </div>
                        </div>

                        <!-- BUSINESS BLOCK -->
                        <div class="panel panel-primary panel-businesses">
                            <div class="panel-heading hide-overflow">
                                <h4 class="pull-left">
                                    <?php _e('New Businesses','bidxplugin')?>
                                </h4>
                                <a href="#home/businessSummaries" class="pull-right btn btn-info"><?php _e('view all','bidxplugin')?></a>
                            </div>
                            <div class="panel-body">
                                <div class="bidx-latest js-fakecrop clearfix">
                                <!-- Grab latests business summaries -->
<?php
                                    echo do_shortcode( '[bidx app="group" view="latest-business-summaries"]' );
?>
                                </div>
                            </div>
                        </div>

                        <!-- MEMBERS BLOCK -->
                        <div class="panel panel-primary panel-members">
                            <div class="panel-heading hide-overflow">
                                <h4 class="pull-left">
                                    <?php _e('New members in the group','bidxplugin')?>
                                </h4>
                                <a href="#home/members" class="pull-right btn btn-info"><?php _e('view all','bidxplugin')?></a>
                            </div>
                            <div class="panel-body">
                                <div class="bidx-latest clearfix">
                                <!-- Grab latests members -->
<?php
                                    $joinedGroup = (isset($this->joinedGroup) && $this->joinedGroup) ? "true" : "false";
                                    echo do_shortcode( '[bidx app="group" view="last-members" authenticated="true" joinedgroup="' . $joinedGroup . '"]' );

?>
                                </div>
                            </div>
                        </div>
                    </article>

                    <!-- BusinessSummaries VIEW -->
                    <article class="view viewBusinessSummaries">
                         <ul class="media-list js-businessSummaries-list">
                        </ul>
                        <div class="pagerContainer">
                            <ul class="pager"></ul>
                        </div>
                    </article>

                    <!-- Members VIEW -->
                    <article class="view viewMembers">
                        <ul class="media-list js-member-list">
                        </ul>
                        <div class="pagerContainer">
                            <ul class="pager"></ul>
                        </div>
                    </article>

                    <!-- news VIEW -->
                    <article class="view viewNews">
                        <ul class="newsList media-list">

                        </ul>
                        <div class="pagerContainer">
                            <ul class="pager"></ul>
                        </div>
                    </article>
                </section>

            </div>


            <!-- SIDE BAR -->
            <div class="col-sm-4">
                <div class="side-bar well sideBar">
                <h2><?php _e('Create and grow', 'bidxplugin')?></h2>
<?php
                    echo do_shortcode( '[bidx app="group" view="join-group"]' );
                    echo do_shortcode( '[bidx app="member" view="entrepreneur-profile-links"]' );
                    echo do_shortcode( '[bidx app="member" view="investor-profile-links"]' );
                    echo do_shortcode( '[bidx app="member" view="mentor-profile-links"]' );
?>
                </div>
            </div>
        </div>


    <div class="snippets hide">
        <!--
            I use %value% for explanatory reasons within the markup body and as placeholders within href links
        -->

        <!-- member Snippet -->
        <div class="snippet" data-key="member">


            <li class="media well">
                <a class="pull-left" href="<?php echo _l('member');?>/%memberId%" data-role="memberImage">
                    <div class="icons-rounded pull-left"><i class="fa fa-user text-primary-light"></i></div>
                </a>
                <div class="media-body">
                    <h4 class="media-heading">
                        <a href="<?php echo _l('member');?>/%memberId%" data-role="memberLink">%firstname% %lastname%</a>
                        <a href="<?php echo _l('mail');?>/#mail/contacts/action=connect&amp;id=%memberId%" class="btn btn-xs btn-warning pull-right" data-role="memberId"><?php _e('Connect','bidxplugin')?></a>
                    </h4>
                    <div data-role="profession"></div>
                    <div data-role="country"></div>
                    <div data-role="roles">
                        <span class="label" data-role="value">test</span>
                    </div>
                    <div>
                    </div>
                    <div class="pull-right">
                        <a href="/member/%memberId%" data-role="memberView"><?php _e('View profile','bidxplugin')?></a>
                    </div>
                </div>
            </li>

        </div>

        <!-- businessSummary Snippet -->
        <div class="snippet" data-key="businessSummary">


            <li class="media well js-fakecrop">
                <a class="pull-left" href="<?php echo _l('businesssummary');?>/%businessSummaryLink%" data-role="businessSummaryImage">
                    <div class="icons-rounded pull-left"><i class="fa fa-suitcase text-primary-light"></i></div>
                </a>
                <div class="media-body">
                    <h4 class="media-heading">
                        <a href="<?php echo _l('businesssummary');?>/%businessSummaryLink%" data-role="businessSummaryName">%name%</a>
                    </h4>
                    <div data-role="summary"></div>
                    <div data-role="slogan"></div>
                    <div data-role="industry"></div>
                    <div data-role="country"></div>

                    <div class="pull-right">
                        <a href="<?php echo _l('businesssummary');?>/%businessSummaryLink%" data-role="businessSummaryLink"><?php _e('View Business Summary','bidxplugin')?></a>
                    </div>
                </div>
            </li>

        </div>

        <!-- news Snippet -->
        <div class="snippet" data-key="news">

            <li class="media well">
                <a class="pull-left" href="#" data-role="newsView">
                    <div data-role="newsImage" class="icons-rounded pull-left"><i class="fa fa-bullhorn text-primary-light"></i></div>
                </a>
                <div class="media-body">
                    <h2 class="media-heading" data-role="title"><span class="header-meta pull-right" data-role="date">%date%</span></h2>
                    <div data-role="content"></div>

                    <div class="pull-right">
                        <a href="#" data-role="newsView"><?php _e('Read more','bidxplugin')?></a>
                    </div>
                </div>
            </li>

        </div>

    </div>

</div>

<?php
    require_once "inc/sponsors.phtml";
?>
