<?php
    echo bidx_get_status_msgs();

    // include the carousel ( id=groupCarousel )
    //
?>
<div class="container">
<?php
    require_once "inc/inc_carousel.phtml";
?>
</div>
<?php
    // if there is custom frontpage markup defind in wordpress theme customizr
    //
    if (get_theme_mod( 'front_content' ))
    {
?>
        <div class="container">
            <?php echo get_theme_mod( 'front_content' ); ?>
        </div>
<?php

    //else load regular frontpage
    //
    }
    else
    {

    ?>
        <div class="container">
            <div class="row">

                <div class="col-sm-6">
                    <div class="bidx-register-block spacer">
                        <a class="clearfix" href="register-as-investor/#register/firstLogin=getting-started-investor">
                            <i class="fa fa-building-o pull-left text-primary-light icon"></i>
                            <div class="action-call-text">Register as<br/> INVESTOR</div>
                            <i class="fa fa-arrow-circle-right arrow"></i>
                        </a>
                    </div>
                </div>

                <div class="col-sm-6">
                    <div class="bidx-register-block spacer">
                        <a href="register-as-entrepreneur/#register/firstLogin=getting-started-entrepreneur">
                            <i class="fa fa-lightbulb-o pull-left text-primary-light icon"></i>
                            <div class="action-call-text">Register as<br/> ENTREPRENEUR</div>
                            <i class="fa fa-arrow-circle-right arrow"></i>
                        </a>
                    </div>
                </div>

                <div class="col-sm-4 hide">
                    <div class="bidx-register-block spacer">
                        <a href="register-as-mentor/#register/firstLogin=getting-started-mentor">
                            <i class="fa fa-compass pull-left text-primary-light icon"></i>
                            <div class="action-call-text">Register as<br/> MENTOR</div>
                            <i class="fa fa-arrow-circle-right arrow"></i>
                        </a>
                    </div>
                </div>

            </div>

            <div class="row">

                <div class="col-sm-8">
                    <?php
                    $meta_key = 'box_intro_text';
                    if (get_post_meta( get_the_ID(), $meta_key, true )) {
                        echo get_post_meta( get_the_ID(), $meta_key, true );
                    } else {
                        $output = "<h1>What is the [yourname here] Group?</h1><p>An introduction of your group here...</p>";
                        echo $output;
                        add_post_meta( get_the_ID(), $meta_key, $output, true );
                    } ?>
                </div>

                <div class="col-sm-4">
                    <div class="bidx-testimonial">
                        <i class="fa fa-quote-right testimonial-quote"></i>
                        <?php
                            $meta_key = 'box_testimonial_text';
                            if (get_post_meta( get_the_ID(), $meta_key, true )) {
                                echo get_post_meta( get_the_ID(), $meta_key, true );
                            } else {
                                $output = "<div><p>Testimonial text here.</p><em>Firstname Lastname</em>,  Function</div>";
                                echo $output;
                                add_post_meta( get_the_ID(), $meta_key, $output, true );
                            }
                        ?>
                        <span class="triange"></span>
                    </div>
                </div>

            </div>
        </div>


        <!-- // container -->

        <div class="feature-container bg-primary-dark">
            <div class="container">
                <div class="row">

                    <div class="col-sm-4 feature-col">
                        <h2><?php _e('New Businesses', 'bidxtheme')?></h2>
                        <!-- Grab latests members -->
                        <?php echo do_shortcode( '[bidx app="group" view="latest-business-summaries"]' ); ?>
                    </div>

                    <div class="col-sm-4 feature-col">
                        <h2><?php _e('New Members', 'bidxtheme')?></h2>
                        <!-- Grab latests members -->
                        <?php echo do_shortcode( '[bidx app="group" view="last-members" authenticated="false"]' ); ?>
                    </div>

                    <div class="col-sm-4 feature-col">
                        <h2><?php _e('News &amp; Events', 'bidxtheme')?></h2>
                        <!-- Grab news -->
                        <?php echo do_shortcode( '[bidx app="group" view="latest-news"]' ); ?>
                    </div>

                </div>
            </div>
        </div>

        <div class="container join-our-group-block">

            <div class="row">
                <div class="col-sm-4 col-sm-offset-4 text-center">
                    <a href="/auth/#auth/register" class="btn btn-lg btn-primary btn-block"><?php _e('Join our group','bidxtheme');?></a>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-6 col-sm-offset-3 text-center btn-lg">
                    <?php printf(__('Already have an account? Just %1$slogin%2$s','bidxtheme'), '<a href="/auth/#auth/login">', '</a>'); ?>
                </div>
            </div>

        </div>
        <!-- // container -->
<?php
        require_once "inc/sponsors.phtml";
?>
    <?php
    }
    ?>
