<div>
	<ul class="thumbnails">
	  <li class="col-sm-3">
	    <div class="thumbnail" data-link="group/0001">
	      <div>type</div>
	      <img data-src="holder.js/200x200" src="http://placehold.it/200x200">
	    </div>
	  </li>
	  <li class="col-sm-3">
	    <div class="thumbnail" data-link="group/0002">
	      <div>type</div>
	      <img data-src="holder.js/200x200" src="http://placehold.it/200x200">
	    </div>
	  </li>
	   <li class="col-sm-3">
	    <div class="thumbnail" data-link="group/0003">
	      <div>type</div>
	      <img data-src="holder.js/200x200" src="http://placehold.it/200x200">
	    </div>
	  </li>
	  <li class="col-sm-3">
	    <div class="thumbnail" data-link="group/0004">
	      <div>type</div>
	      <img data-src="holder.js/200x200" src="http://placehold.it/200x200">
	    </div>
	  </li>
	</ul>
</div>
