<?php
// Render a 'join this group' button in case the current user is not in this group
//
if (property_exists($this -> sessionData, 'data') ) {

    $currentGroup   = $this->exst( $this->sessionData->data->currentGroup );
    $groups         = $this->exst( $this->sessionData->data->groups );

    if ( !empty( $currentGroup ) && !empty( $groups ) && !isset( $groups->$currentGroup )) {
?>

<div class="panel panel-default">
    <div class="panel-body">
        <p>
        <?php _e('You are currently not a member of this group', 'bidx')?>
        </p>
         <a class="btn btn-success btn-block" href="#joinGroup">Join our group</a>
    </div>
</div>
<?php
    }
}
?>
