<?php

        // check if span is empty, then revert to default 6
        //
        $span = !empty($this->span) ? $this->span : 6;

        // check if user is logged in
        //
        $authenticated = isset( $this -> authenticated ) && $this -> authenticated ==  'true';
        $joinedGroup = isset( $this -> joinedGroup ) && $this -> joinedGroup ==  'true';

        if ( is_array( $this -> members ) && count( $this -> members ) ) {
            $index = 0;

            $maxMemberItems = $authenticated ? 4 : 3;

            // iterate through the members
        	foreach ($this -> members as $member) {

                // if maxmembers has been reached, stop the itaration
                //
                if ( $index === $maxMemberItems) {
                    break;
                }
		      	$memberBidxMeta = isset( $member->bidxMeta ) ? $member->bidxMeta : $member;
 ?>

                <div class="span<?php echo $span ?> clearfix">
                    <a href="/member/<?php echo $member -> bidxMeta -> bidxMemberId ?>">
<?php
    				  	if ( empty( $member -> profilePicture ) ) {
    						echo '<img src="/wp-content/themes/bidx-group-template/assets/img/mock/new-members.png" alt="" class="img-circle pull-left">';
                        } else {
    						echo '<img src="' . $member -> profilePicture . '" alt="" class="img-circle pull-left" style="height:95px;">';
                        }
?>
                    </a>
                <div>

                <div>
                    <a href="/member/<?php echo $member -> bidxMeta -> bidxMemberId ?>">
                        <strong>
<?php
                            echo $this -> exst( $member -> firstName ) . ' ' . $this -> exst( $member -> lastName );
?>
                        </strong>
                    </a>
                </div>
<?php
                if ( $this -> exst( $member -> professionalTitle) ) {
                    echo '<div>' . $this -> escapeHtml( $member -> professionalTitle ) . '</div>';
                }

                if ( $this -> exst( $member -> country) ) {
                    echo '<div>' . $member -> country . '</div>';
                }

                if ( $this -> exst( $member -> roles ) ) {
                    echo '<div>';
                    foreach ($member -> roles as $role) {
                        if ( $role === 'entrepreneur' ) {
?>
                        <span class="label bidx-label-entrepreneur"><?php _e('Entrepreneur', 'bidxplugin') ?></span>&nbsp;
<?php
                        }
                        if ( $role === 'investor' ) {
?>
                        <span class="label bidx-label-investor"><?php _e('Investor', 'bidxplugin') ?></span>&nbsp;
<?php
                        }
                    }
                    echo '</div>';
                } else {
                    echo '<div><span class="label bidx-label-member">Member</span></div>';
                }
?>
<?php
                // only show connect link when authenticated and member has joined the group
                //
                if ( $authenticated && $joinedGroup ) {
?>
                    <div>
                        <a href="/mail/#mail/contacts/action=connect&id=<?php echo $member -> bidxMeta -> bidxMemberId ?>"><?php _e('Connect', 'bidxplugin')?></a>
                    </div>
<?php
                }
?>
            </div>
        </div>
<?php


            $index++;
            }
            // end foreach
        } else {
 ?>
            <div class="span12">
                <?php _e( "There are currently no new members", 'bidxplugin' ); ?>
            </div>
<?php
        }
?>



