<div class="well">
<div class="row-fluid">
	<h3 class="pull-left"><?php _e('New members in this group','bidxplugin')?></h3>
	<span class="pull-right">
		<a href="/member" class=""><?php _e('View all','bidxplugin')?></a>
	</span>
</div>


<div class="row-fluid">
<?php
if (is_array($this -> members)) {
	$i = 0;

	foreach ($this -> members as $member) {

		$memberBidxMeta = isset( $member->bidxMeta ) ? $member->bidxMeta : $member;
?>
	<div class="span4">
		<div class="media member-thumb img-rounded">
		  	<a class="pull-left" href="/member/<?php echo $memberBidxMeta -> bidxMemberId; ?>">
			  	<?php
				  	if ( empty( $member -> profilePicture ) ) {
						echo '<img data-src="holder.js/50x50/social/auto/text:None" class="media-object img-rounded" />';
					}
					else {
						echo '<img class="media-object img-rounded member-thumb-small-100" src="' . $member -> profilePicture . '" />';
				  	}
			  	?>
		  </a>
		  <div class="media-body centering">
		    	<h5 class="media-heading"><?php $this -> showProperty($member, 'firstName') . ' ' . $this -> showProperty($member, 'lastName'); ?></h5>
				<div><?php $this -> showProperty($member, 'professionalTitle') ?></div>
				<div><?php $this -> showProperty($member, 'country') ?></div>
				<div class="member-connect"><a href="#fakelink"><?php _e('Connect','bidxplugin')?></a></div>
		  </div>
		</div>
	</div>
	<?php
		$i++ ;
		if ( $i == 3 ) {
	?>
</div>
<div class="row-fluid">
	<?php
		}
		else if ( $i == 5 ) { break; }
	}
}
?>
	<div class="span4 ">
		<div class="media member-thumb img-rounded">
			<div class="text-center vertical-middle">
			   	<a href="/search" class=""><?php _e('Search new members','bidxplugin')?></a>
			</div>
		</div>
	</div>
</div>
</div>

