<?php
        $authenticated = isset($this -> sessionData -> authenticated ) && $this -> sessionData -> authenticated ==  'true';

        if (is_array( $this -> summaries )) {
            if ( $authenticated ) {
?>
                <div class="row">
<?php
            }
?>
                <ul class="media-list">
<?php

            $index = 0;
            foreach ( $this -> summaries as $summary ) {

                $bsitems = $authenticated ? 4 : 3;
                if ( $index === $bsitems ) {
                    break;
                }
                $summaryBidxMeta = isset( $summary->bidxMeta ) ? $summary->bidxMeta : $summary;
                if ( $authenticated ) {
 ?>
                    <div class="col-sm-6">
 <?php
                }
 ?>


                <li class="media">
<?php
                    if ( $authenticated ) {
?>
                        <a class="pull-left" href="/businesssummary/<?php echo $summary -> bidxMeta -> bidxEntityId ?>">
<?php
                    }

                    if ( empty( $summary -> externalVideoPitch ) ) {
                        echo '<div class="icons-rounded pull-left"><i class="fa fa-suitcase text-primary-light"></i></div>';
                    } else {
                        $videoUrl = $this->exst($summary -> externalVideoPitch);
                        $parsedVideo = $this->parseVideos( $videoUrl );
                        $videoThumb = $parsedVideo[0]['fullsize'];

                        echo '<div class="img-cropper pull-left"><img src="' . $videoThumb . '" alt=""></div>';
                    }

                    if ( $authenticated ) {
?>
                        </a>
<?php
                    }
?>
                    <div class="media-body">
                        <div class="media-heading">
<?php
                        if ( $authenticated ) {
?>
                            <a href="/businesssummary/<?php echo $summary -> bidxMeta -> bidxEntityId ?>"><strong>
<?php
                        }

                        echo html_entity_decode( $summary -> name  );

                        if ( $authenticated ) {
?>
                            </strong></a>
<?php
                        }
?>

                        </div>
                        <div>
<?php
                            $industries = $this -> exst( $summary -> industry );

                            $ix = 1;
                            // create a comma separated list of translated industries
                            //
                            if(!empty($industries))
                            {
                                foreach ( $industries as $industry )
                                {
                                    echo $this->getStaticVal( 'industry', $industry ) ;
                                    if ( count( $industries ) != $ix )
                                    {
                                    echo ", ";
                                    }
                                    $ix++;
                                }
                            }
?>
                        </div>
                        <div>
<?php
                            $countries =  $this -> exst( $summary -> countryOperation );

                            $ix = 1;
                            // create a comma separated list of translated industries
                            //
                            if(!empty($countries))
                            {
                                foreach ( $countries as $country )
                                {
                                    echo $this->getStaticVal( 'country', $country ) ;
                                    if ( count( $countries ) != $ix )
                                    {
                                        echo ", ";
                                    }
                                    $ix++;
                                }
                            }
?>
                        </div>
<?php
                            if ( $authenticated ) {
?>
                        <div>
<?php
                                echo date_i18n( 'd M Y', $summary -> bidxMeta -> bidxCreationDateTime );
?>
                        </div>
<?php
                            }
?>
                    </div>
                </li>
<?php
            if ( $authenticated ) {
?>
            </div>
<?php

            }
                $index++;
            } // end foreach
?>
        </ul>
<?php
            if ( $authenticated ) {
?>
        </div>
<?php
            }
        } else {
?>
            <ul class="media-list">
                <li class="media">
                    <div class="icons-rounded pull-left"><i class="fa fa-exclamation text-primary-light"></i></div>
                    <div class="media-body">
                        <p><?php _e( "There are currently no new business summaries", 'bidxplugin' ); ?></p>
                    </div>
                </li>
            </ul>
<?php
        }
?>


