<?php
        $authenticated = isset($this -> sessionData -> authenticated ) && $this -> sessionData -> authenticated ==  'true';

        if (is_array( $this -> summaries )) {
            if ( $authenticated ) {
?>
                <div class="row">
<?php
            }
?>
                <ul class="media-list">
<?php

            $index = 0;
            foreach ( $this -> summaries as $summary ) {
                $bsitems = $authenticated ? 4 : 3;
                if ( $index === $bsitems ) {
                    break;
                }
                $summaryBidxMeta = isset( $summary->bidxMeta ) ? $summary->bidxMeta : $summary;
                if ( $authenticated ) {
 ?>
                    <div class="col-sm-6">
 <?php
                }
 ?>


                <li class="media">
<?php
                    if ( $authenticated ) {
?>
                        <a class="pull-left" href="/businesssummary/<?php echo $summary -> bidxMeta -> bidxEntityId ?>">
<?php
                    }

                    if ( empty( $summary -> profilePicture ) ) {
                        echo '<div class="icons-circle pull-left"><i class="fa fa-suitcase text-primary-light"></i></div>';
                    } else {
                        echo '<img src="' . $summary -> profilePicture . '" alt="" class="media-object img-circle pull-left" style="height:95px;">';
                    }
                        if ( $authenticated ) {
?>
                            </a>
<?php
                        }
?>
                    <div class="media-body">
                        <div class="media-heading">
<?php
                        if ( $authenticated ) {
?>
                            <a href="/businesssummary/<?php echo $summary -> bidxMeta -> bidxEntityId ?>"><strong>
<?php
                        }

                        echo html_entity_decode( $this -> exst( $summary -> name ) );

                        if ( $authenticated ) {
?>
                            </strong></a>
<?php
                        }
?>

                        </div>
                        <div>
<?php
                            $industries = $this -> exst( $summary -> industry );

                            $ix = 1;
                            // create a comma separated list of translated industries
                            //
                            foreach ( $industries as $industry ) {
                                echo $this->getStaticVal( 'industry',$industry ) ;
                                if ( count( $industries ) != $ix ){
                                    echo ", ";
                                }
                                $ix++;
                            }
?>
                        </div>
                        <div>
<?php

                            $countries = implode( ", ", $this -> exst( $summary -> countryOperation ));

                            echo $this->getStaticVal( 'country',$countries );
?>
                        </div>
<?php
                            if ( $authenticated ) {
?>
                        <div>
<?php
                                echo date_i18n( 'd M Y', $summary -> bidxMeta -> bidxCreationDateTime );
?>
                        </div>
<?php
                            }
?>
                    </div>
                </li>
<?php
            if ( $authenticated ) {
?>
            </div>
<?php

            }
                $index++;
            } // end foreach
?>
        </ul>
<?php
            if ( $authenticated ) {
?>
        </div>
<?php
            }
        } else {
?>
            <ul class="media-list">
                <li class="media">
                    <div class="icons-circle pull-left"><i class="fa fa-exclamation text-primary-light"></i></div>
                    <div class="media-body">
                        <p><?php _e( "There are currently no new business summaries", 'bidxplugin' ); ?></p>
                    </div>
                </li>
            </ul>
<?php
        }
?>


