<?php

    // check if user is logged in
    //
    $authenticated = isset($this -> sessionData -> authenticated ) && $this -> sessionData -> authenticated ==  'true';
    $newsitems = $authenticated ? 4 : 3;
    $post_type = (get_option ('group-news')) ? 'news' : 'post';
    
    $args=array(
      'post_type' => $post_type,
      'post_status' => 'publish',
      'posts_per_page' => $newsitems
    );
    
    $my_query = null;
    $my_query = new WP_Query($args);

    if( $my_query->have_posts() ) {
            if ( $authenticated ) {
?>
                <div class="row">
<?php
            }
?>
            <ul class="media-list">
<?php
        $index = 0;
        while ( $my_query->have_posts() ) {
            if ( $index == $newsitems) {
                break;
            }
            $my_query->the_post();
            if ( $authenticated ) {
?>
                <div class="col-sm-6">
<?php
            }
?>
                    <li class="media">
                        <a class="pull-left" href="<?php the_permalink() ?>" rel="bookmark" title="Permanent Link to <?php the_title_attribute(); ?>">
<?php
                        if ( has_post_thumbnail() ) {
                            $size = array(90,90);
                            $atts = array('data-src' => 'holder.js/50x50/social/auto/text:News',
                                          'class' => 'media-object img-circle pull-left');
                            the_post_thumbnail($size, $atts);
                        } else {
?>
                            <div class="icons-circle pull-left"><i class="fa fa-bullhorn text-primary-light"></i></div>
<?php
                        }
?>
                        </a>

                        <div class="media-body">
                            <div><a href="<?php the_permalink() ?>"><strong><?php the_title(); ?></strong></a></div>
                            <div><?php the_date( 'd M Y' ) ?></div>
<?php
                            if ( $authenticated ) {
                                echo ucfirst( strtolower( substr( get_the_excerpt(),0,65 ) ) ) . '...';
                            }
?>
                        </div>
                    </li>
<?php
            if ( $authenticated ) {
?>
                </div>
<?php
            }
         $index++;
        } //while
?>
            </ul>
<?php
            if ( $authenticated ) {
?>
        </div>
<?php
            }
?>
<?php
        } else {
?>
            <ul class="media-list">
                <li class="media">
                    <div class="icons-circle pull-left"><i class="fa fa-exclamation text-primary-light"></i></div>
                    <div class="media-body">
                        <p><?php _e( "There are currently no news or events", 'bidxplugin' ); ?></p>
                    </div>
                </li>
            </ul>
<?php
        }
    wp_reset_query();
?>
