
<?php
        // check if span is empty, then revert to default 6
        $span = !empty($this->span) ? $this->span : 6;

        if (is_array($this -> summaries)) {

            $index = 0;
            foreach ( $this -> summaries as $summary ) {
                if ( $index === 3 ) {
                    break;
                }
                $summaryBidxMeta = isset( $summary->bidxMeta ) ? $summary->bidxMeta : $summary;
 ?>

                <div class="span<?php echo $span ?> clearfix">
<?php
                    if ( empty( $summary -> profilePicture ) ) {
                        echo '<img src="/wp-content/themes/bidx-group-template/assets/img/mock/new-business.png" alt="" align="left" class="img-circle">';
                    } else {
                        echo '<img src="' . $summary -> profilePicture . '" alt="" align="left" class="img-circle" style="height:95px;">';
                    }
?>
                    <div>
                        <div><strong><a href="/businesssummary/<?php echo $summary -> bidxMeta -> bidxProfileId ?>"><?php echo $this -> exst( $summary -> displayName ) ; ?></a></strong></div>
                    </div>
                </div>
<?php
                $index++;
            }
            // end foreach
        }
?>


