<?php
    include_once( ABSPATH . 'wp-admin/includes/plugin.php' );
    $sessionSvc = new SessionService( );

    // define the profiles we currently want to display
    //
    $profiles = array(
        'bidxInvestorProfile'        => array(
            'Investor Dashboard' => '/investor-dashboard'
        ),
        'bidxEntrepreneurProfile'   => array(
            'Entrepreneur Dashboard' => '/entrepreneur-dashboard'
        )
    );

    // error_log(var_export($sessionSvc->getGroups(), true));

    // check for each profile if it exists in the members entities
    //
    foreach (  $profiles as $profilekey => $profilevalue ) {

        // check if current profile is existent, if not remove it from the array
        //
        if ( !$sessionSvc->isHavingProfile( $profilekey ) ) {
            unset( $profiles[ $profilekey ] );
        }
    }

    // get the groups for his user
    //
    $groups = $sessionSvc->getGroups();

    // set boolean to display the profile menu
    //
    $hasProfiles = count( $profiles) !== 0;
    $hasGroups = count( $groups) > 1;
	$isAdmin = $sessionSvc->isAdmin();
?>

<div class="iconbar bg-primary-dark">

<?php
        // only when a member has profiles, show the profile dropdown
        //
        if ( $hasProfiles || $isAdmin ) {
 ?>
            <div class="btn-group profiles">
                <a href="#" type="button" class="text-white dropdown-toggle" data-toggle="dropdown" title="<?php _e('Dashboards', 'bidxplugin')?>">
                    <i class="fa fa-dashboard"></i>
                </a>
                <ul class="dropdown-menu bg-primary-dark">
<?php
                    foreach ( $profiles as $profilekey => $profilevalue ) {
                        // fetch the key value for printing as text in the hyperlink
                        //
                        $key = array_keys($profilevalue);
                        $key = $key[0];
?>
                        <li><a href="<?php echo $profilevalue[ $key ] ?>"><?php _e( $key, 'bidxplugin' ); ?></a></li>
<?php
                    }
                    if ( $isAdmin ) {
?>
                        <li><a href="/wp-admin/admin.php?page=getting-started"><?php _e( 'bidX Dashboard', 'bidxplugin' ); ?></a></li>
<?php
                    }
?>
                </ul>
            </div>
<?php
        }
 ?>

 <?php
        // only when a has grous, show the group dropdown
        //
        if ( $hasGroups ) {
 ?>
            <div class="btn-group groups">
                <a href="#" type="button" class="text-white dropdown-toggle" data-toggle="dropdown" title="<?php _e('Groups', 'bidxplugin')?>">
                    <i class="fa fa-users"></i>
                </a>
                <ul class="dropdown-menu bg-primary-dark">
<?php
                    foreach ( $groups as $groupKey => $groupValue ) {
?>
                        <li><a href="<?php echo $groupValue[ "url" ] ?>"><?php echo $groupValue[ "name" ] ?></a></li>
<?php
                    }
?>
                </ul>
            </div>
<?php
        }
 ?>
        <div class="btn-group">
            <a href="/mail/#mail" type="button" class="bidx-mail text-white" title="<?php _e('Mail', 'bidxplugin')?>">
                <!-- If messages are available -->
                <i class="fa fa-envelope"></i>
                <span class="iconbar-unread">?</span>
            </a>
        </div>
<?php
        $roles = (!empty($this -> sessionData -> data -> roles)) ? $this -> sessionData -> data -> roles:NULL;
        $currentGroupAdmin = false;
        if ( !empty($this->sessionData) && !empty( $roles) ) {
            if ( in_array( 'GroupAdmin', $roles ) ||
                 in_array( 'GroupOwner', $roles ) ) {
                $currentGroupAdmin = true;
?>

<?php
    }
}
?>
        <div class="btn-group settings">
            <a href="#" type="button" class="text-white dropdown-toggle" data-toggle="dropdown" title="<?php _e('Account settings')?>">
                <i class="fa fa-cog"></i>
            </a>
            <ul class="dropdown-menu bg-primary-dark">
                <li><a href="/member"><?php _e('Profile','bidxplugin')?></a></li>
                <li><a href="/account/#account"><?php _e('Account settings','bidxplugin')?></a></li>
                <li><a href="/media"><?php _e('All my documents','bidxplugin')?></a></li>


<?php

                if (!empty( $this -> sessionData -> data ) ){

                    $currentGroup   = $this->exst( $this->sessionData->data->currentGroup );
                    $groups         = $this->exst( $this->sessionData->data->groups );
                    $showLogout     = true;

                    if ( !empty( $currentGroup ) && !empty( $groups ) && !isset( $groups->$currentGroup )) {
?>
                        <li><a href="#joinGroup"><?php _e('Join this group', 'bidxplugin')?></a></li>
<?php
                    } else if(!$currentGroupAdmin) {
?>
                        <li><a href="#leaveGroup"><?php _e('Leave this group', 'bidxplugin')?></a></li>
<?php
                    }
                }

                if( !$currentGroupAdmin && $hasGroups ) {?>

                    <li><a href="#messageOwner"><?php _e('Help','bidxplugin')?></a></li>
<?php
                }


                if ($currentGroupAdmin && is_plugin_active('zendesk/zendesk-support.php'))  { ?>

                     <li><a href="/support"><?php _e('Ask your question','bidxplugin')?></a></li>
<?php           }
                if( $showLogout ) {
?>
                     <li> <a href="<?php echo wp_logout_url( home_url() ); ?>"><?php _e('Logout', 'bidxplugin')?></a>
<?php
                }
?>
            </ul>
        </div>

</div>
