<?php
    include_once( ABSPATH . 'wp-admin/includes/plugin.php' );
    $sessionSvc = new SessionService( );
    // define the profiles we currently want to display
    //
    $profiles = array(
        'bidxInvestorProfile'        => array(
            __('Investor', 'bidxplugin')     => _l('investor-dashboard')
        ),
        'bidxEntrepreneurProfile'    => array(
            __('Entrepreneur', 'bidxplugin') => _l('entrepreneur-dashboard')
        ,   __('Mentor', 'bidxplugin')       => _l('mentor-dashboard')
        ),
        'bidxMentorProfile'          => array(
            __('Mentor Dashboard', 'bidxplugin')       => _l('mentor-dashboard')
        )
    );

    // error_log(var_export($sessionSvc->getGroups(), true));

    // check for each profile if it exists in the members entities
    //
    foreach (  $profiles as $profilekey => $profilevalue )
    {

        // check if current profile is existent, if not remove it from the array
        //
        if ( !$sessionSvc->isHavingProfile( $profilekey ) ) {
            unset( $profiles[ $profilekey ] );
        }

        if( $sessionSvc->isHavingProfile( 'bidxEntrepreneurProfile' ) ) {
            unset( $profiles[ 'bidxMentorProfile' ] );
        }
    }

    // get the groups for his user
    //
    $groups = $sessionSvc->getGroups();



    // set boolean to display the profile menu
    //
    $hasProfiles    = count( $profiles) !== 0;
    $hasGroups      = count( $groups) > 1;
    $isAdmin        = $sessionSvc->isAdmin();
    $isSysAdmin     = $sessionSvc->isSysAdmin();

?>

<div class="iconbar pull-right">

<?php

    $session = BidxCommon::$staticSession;
    $authenticated  = $session -> authenticated;

        // check for the widget
        if ( is_plugin_active( 'sitepress-multilingual-cms/sitepress.php') )
        {
?>
            <div class="btn-group language-switcher">
                <?php //the_widget('ICL_Language_Switcher'); ?>
                <?php echo languages_list_header();?>
            </div>
<?php
         }

    if ( $authenticated === "true" )
    {

    // check if the curent user is has joined this group
    // only when a member has profiles, show the profile dropdown
    $currentGroup   = $this -> sessionData -> data -> currentGroup;
    $groupIds       = array_keys ( (array)$this -> sessionData -> data -> groups );
    $inGroup        = in_array( $currentGroup, $groupIds);
    $isCompetition  = get_option ('skipso-competition');
    $skipsoJudgeUrl = get_option ('skipso-judge-url');
    $userName       = $this -> sessionData -> data -> username;
    $displayName    = $this -> sessionData -> data -> bidxMemberProfile -> firstName ? $this -> sessionData -> data -> bidxMemberProfile -> firstName : $this -> sessionData -> data -> displayName ;
    if ( $isSysAdmin )
    {
        // we could add something in the account's name, but that would make it very clear who the platform
        // administrators are if they join a group. So, add some indicator in the navigation instead.
        $displayName = $displayName . ' ☆';
    }
    $judgeEmails    = explode(",", get_option ('skipso-judge-emails'));
    $isJudge        = ($isCompetition && in_array( $userName, $judgeEmails )) ? true : false;
    $showLogout     = true;

        if ( $isSysAdmin || $isAdmin || ( $inGroup && $hasProfiles ) || $isJudge)
        {
 ?>
            <div class="btn-group profiles">
                <a href="#" type="button" class="text-white dropdown-toggle" data-toggle="dropdown" title="<?php _e('Dashboards', 'bidxplugin')?>">
                    <i class="fa fa-dashboard"></i>
                    <span class="iconbar-text"><?php _e('Dashboards','bidxplugin')?></span>
                </a>
                <ul class="dropdown-menu bg-primary-darker">
<?php
                    foreach ( $profiles as $profilekey => $profilevalue )
                    {
                        foreach($profilevalue as $menuName => $menuLink)
                        {
                            // fetch the key value for printing as text in the hyperlink
                            //
?>
                            <li><a href="<?php echo $menuLink ?>"><i class="fa fa-angle-right"></i>&nbsp;<?php _e( $menuName, 'bidxplugin' ); ?></a></li>
<?php                   }
                    }
                    if ( $isSysAdmin )
                    {
?>
                        <li>
                            <a href="/wp-admin/"><i class="fa fa-angle-right"></i>&nbsp;<?php _e( 'Wordpress dashboard', 'bidxplugin' ); ?></a>
                        </li>
<?php
                    }
                    if ( $isAdmin )
                    {
?>
                        <li>
                            <a href="/wp-admin/admin.php?page=getting-started"><i class="fa fa-angle-right"></i>&nbsp;<?php _e( 'bidX', 'bidxplugin' ); ?></a>
                        </li>
<?php
                    }
                    if ( $isJudge )
                    {
?>
                        <li>
                            <a href="<?php echo $skipsoJudgeUrl;?>"><i class="fa fa-angle-right"></i>&nbsp;<?php _e('Judge','bidxplugin')?></a>
                        </li>
<?php
                    }
?>
                </ul>
            </div>
<?php
        }
 ?>

 <?php

        // only when a has grous, show the group dropdown
        //As per Sakis instruction, when multilingual switcher is there, switching of group should go away so disabling it.
        if ( $hasGroups && false )
        {
 ?>
            <div class="btn-group groups">
                <a href="#" type="button" class="text-white dropdown-toggle" data-toggle="dropdown" title="<?php _e('Groups', 'bidxplugin')?>">
                    <i class="fa fa-users"></i>
                    <span class="iconbar-text"><?php _e('Groups','bidxplugin')?></span>
                </a>
                <ul class="dropdown-menu bg-primary-darker">
<?php
                    foreach ( $groups as $groupKey => $groupValue ) {
?>
                        <li><a href="<?php echo $groupValue[ "url" ] ?>"><i class="fa fa-angle-right"></i>&nbsp;<?php echo $groupValue[ "name" ] ?></a></li>
<?php
                    }
?>
                </ul>
            </div>
<?php
        }
 ?>
        <div class="btn-group">
<?php
            if ( $inGroup )
            {
?>
                <a href="<?php echo _l('mail');?>/#mail" type="button" class="bidx-mail text-white" title="<?php _e('Mail', 'bidxplugin')?>">
                    <!-- If messages are available -->
                    <i class="fa fa-envelope"></i>
                    <span class="iconbar-unread hide-it">?</span>
                    <span class="iconbar-text"><?php _e('Messages','bidxplugin')?></span>
                </a>
<?php
            }
            else
            {
?>
                <a type="button" class="text-white" href="#joinGroup"><i class="fa fa-sign-in"></i>&nbsp;<?php _e('Join this group', 'bidxplugin')?></a>
<?php
            }
?>
        </div>
<?php
        $roles = ( !empty( $this -> sessionData -> data -> roles ) ) ? $this -> sessionData -> data -> roles : NULL;
        $currentGroupAdmin = false;

        if ( !empty($this->sessionData) && !empty( $roles) )
        {
            if ( in_array( 'GroupAdmin', $roles ) || in_array( 'GroupOwner', $roles ) )
            {
                $currentGroupAdmin = true;
            }
        }
?>
        <div class="btn-group settings">
            <a href="#" type="button" class="text-white dropdown-toggle" data-toggle="dropdown" title="<?php _e('Account settings','bidxplugin')?>">
                <i class="fa fa-cogs"></i>
                <span class="iconbar-text"><?php echo $displayName; ?></span>
            </a>
            <ul class="dropdown-menu bg-primary-darker">
<?php
                // the following menu-items only to be displayed when user has joined the group
                //
                if ( $inGroup )
                {
?>
                    <li><a href="<?php echo _l('member');?>"><i class="fa fa-user"></i>&nbsp;<?php _e('Profile','bidxplugin')?></a></li>
                    <li><a href="<?php echo _l('account');?>/#account"><i class="fa fa-cog"></i>&nbsp;<?php _e('Account settings','bidxplugin')?></a></li>
                    <li><a href="<?php echo _l('media');?>"><i class="fa fa-file"></i>&nbsp;<?php _e('All my documents','bidxplugin')?></a></li>
<?php
                }

                if ( !$inGroup )
                {
?>
                    <li><a href="#joinGroup"><i class="fa fa-sign-in"></i>&nbsp;<?php _e('Join this group', 'bidxplugin')?></a></li>
<?php
                }
                elseif ( !$currentGroupAdmin )
                {
?>
                    <li><a href="#leaveGroup"><i class="fa fa-sign-out"></i>&nbsp;<?php _e('Leave this group', 'bidxplugin')?></a></li>
<?php
                }

                if( !$currentGroupAdmin && $hasGroups )
                {
?>
                    <li><a href="<?php echo _l('mail');?>/#mail/compose"><i class="fa fa-question"></i>&nbsp;<?php _e('Help','bidxplugin')?></a></li>
<?php
                }

                if ( $currentGroupAdmin && is_plugin_active('zendesk/zendesk-support.php') )
                {
?>
                     <li><a href="<?php echo _l('support');?>"><?php _e('Ask your question','bidxplugin')?></a></li>
<?php           }

                if( $showLogout )
                {
?>
                     <li> <a href="<?php echo wp_logout_url( home_url() ); ?>"><i class="fa fa-power-off"></i>&nbsp;<?php _e('Logout', 'bidxplugin')?></a>
<?php
                }
?>
            </ul>
        </div>
<?php
    }
    else
    {
?>
        <div class="btn-group">
            <a href="<?php echo _l('auth');?>/#auth/login" type="button" class="text-white" title="<?php _e('Login', 'bidxplugin')?>">
                <i class="fa fa-lock"></i>
                <span><?php _e('Login','bidxplugin')?></span>
            </a>
        </div>
<?php
    }
?>
</div>
