<?php
    global $latest_items;

    $authenticated = isset($this -> sessionData -> authenticated ) && $this -> sessionData -> authenticated ==  'true';
    $isPanel = isset( $this -> panel ) && $this -> panel ==  'true';
    $panelItems = (int)$this -> items;
    $region = $this -> region;

    $addColumns = true;
    if ( $isPanel && ( $region === 'priv-front-side' || $region === 'pub-front-side' ) ) :
        $addColumns = false;
    endif;

    $columnsCount = 'col col-sm-4';
    if ( $addColumns && $isPanel && ( $region === 'priv-front-body' || $region === 'pub-front-body' ) ) :
        $columnsCount = 'col col-sm-6';
    endif;

        if ( is_array( $this -> summaries ) && !empty( $this -> summaries )) {
            $index = 0;
            if ( $isPanel )
            {
                $bsitems = $panelItems;
            }
            else
            {
?>
                <h2><?php _e('New Businesses', 'bidxplugin')?></h2>
<?php
                $bsitems = (int)$latest_items;
            }
?>
            <ul class="media-list bottom-0">
<?php
            if ( $addColumns && $isPanel ) :
?>
                <div class="row">
<?php
            endif;

            foreach ( $this -> summaries as $summary ) {

                if ( $index === $bsitems ) {
                    break;
                }
                if ( $addColumns && $isPanel ) :
                    if ( $index % 2 == 0  ) {

                        if ( $index != 0 ) {
                            echo "</div>";
                        }

                        echo '<div class="'. $columnsCount .'">';
                    }
                endif;

                $summaryBidxMeta = isset( $summary->bidxMeta ) ? $summary->bidxMeta : $summary;
 ?>
                <li class="media">
                        <a class="pull-left" href="/businesssummary/<?php echo $summary -> bidxMeta -> bidxEntityId ?>">
<?php

                            if ( $this -> exst( $summary->logo )  && $this -> exst( $summary->logo->document ) )
                            {
                                echo '<div class="img-cropper img-logo pull-left"><span class="valign"></span><img src="' . $summary->logo->document . '" alt=""></div>';
                            }
                            elseif ( $this -> exst( $summary->cover )  && $this -> exst( $summary->cover->document ) )
                            {
                                echo '<div class="img-cropper img-logo pull-left"><span class="valign"></span><img src="' . $summary->cover->document . '" alt=""></div>';
                            }
                            else
                            {
                                echo '<div class="icons-rounded pull-left"><i class="fa fa-suitcase text-primary-light"></i></div>';
                            }




?>
                        </a>

                    <div class="media-body">
                        <div class="media-heading">
                            <a href="/businesssummary/<?php echo $summary -> bidxMeta -> bidxEntityId ?>"><strong>
<?php
                        echo html_entity_decode( $summary -> name  );
?>
                            </strong></a>

                        </div>
                        <div>
<?php
                            $industries = $this -> exst( $summary -> industry );

                            $ix = 1;
                            // create a comma separated list of translated industries
                            //
                            if( $industries )
                            {
                                foreach ( $industries as $industry )
                                {
                                    echo $this->getStaticVal( 'industry', $industry ) ;
                                    if ( count( $industries ) != $ix )
                                    {
                                        echo ", ";
                                    }
                                    $ix++;
                                }
                            }
?>
                        </div>
                        <div>
<?php
                            $countries =  $this -> exst( $summary -> countryOperation );

                            $ix = 1;
                            // create a comma separated list of translated industries
                            //
                            if( !empty( $countries ))
                            {
                                foreach ( $countries as $country )
                                {
                                    echo $this->getStaticVal( 'country', $country ) ;
                                    if ( count( $countries ) != $ix )
                                    {
                                        echo ", ";
                                    }
                                    $ix++;
                                }
                            }
?>
                        </div>
<?php
                            if ( $authenticated ) {
?>
                        <div>
<?php
                                echo date_i18n( 'd M Y', $summary -> bidxMeta -> bidxCreationDateTime );
?>
                        </div>
<?php
                            }
?>
                    </div>
                </li>
<?php
                $index++;
            } // end foreach

            if ( $addColumns && $isPanel ) :
?>
                </div>
<?php
            endif;
?>
        </ul>
        <a href="#" class="hide btn btn-link btn-block"><?php _e( "View more", 'bidxplugin' ); ?></a>
<?php
        }
        else
        {
            if ( !$isPanel )
            {
?>
                <h2><?php _e('New Businesses', 'bidxplugin')?></h2>
<?php
            }
?>
            <ul class="media-list">
                <li class="media">
                    <div class="icons-rounded pull-left"><i class="fa fa-exclamation text-primary-light"></i></div>
                    <div class="media-body">
                        <p><?php _e( "There are currently no new business summaries", 'bidxplugin' ); ?></p>
                    </div>
                </li>
            </ul>
<?php
        }
?>


