<div id="media" class="mainState mainStateMedia">

    <!-- LOAD -->
    <div class="view viewLoad alert alert-info text-center">
        <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e('Loading media data...','bidxplugin'); ?>
    </div>

    <!-- ERROR -->
    <div class="view viewError col-sm-12">
        <h2><?php _e('Error','bidxplugin'); ?></h2>
        <p class="errorMsg"></p>
    </div>

    <!-- LIST -->
    <div class="view viewList">

        <div class="js-new-file newFile well dropzone text-center">
            <p><?php _e( 'Drop file here to upload', 'bidxplugin' ); ?></p>
            <p><?php _e( 'or', 'bidxplugin' ); ?></p>

            <!-- The fileinput-button span is used to style the file input field as button -->
            <span class="btn btn-success fileinput-button">
                <i class="fa fa-plus"></i>
                <span><?php _e( 'Select new file', 'bidxplugin' ); ?></span>

                <!-- The file input field used as target for the file upload widget -->
                <input type="file" class="fileUpload" name="fileContent" />
            </span>

            <div class="row">

                <div class="col-sm-6">
                    <div class="form-group">
                        <label><?php _e('Purpose','bidxplugin'); ?></label>
                        <input type="text" class="form-control" name="purpose" placeholder="<?php _e('Please describe the attachment','bidxplugin'); ?>">
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label><?php _e('Document type','bidxplugin'); ?></label>
                        <select name="documentType"></select>
                    </div>
                </div>
            </div>

        </div>
        <div class="panel panel-default">
            <div class="panel-heading hide-in-modal">
                <h3 class="panel-title"><?php _e( 'Media list', 'bidxplugin' ); ?></h3>
            </div>
            <div class="panel-body table-responsive">
                <table class="fileList table table-striped table-condensed">
                    <tbody class="files"></tbody>
                </table>
            </div>
        </div>

    </div>

    <!-- EDIT of one file -->
    <div class="view viewEdit">

        <form id="frmeditMedia">
            <div class="col-sm-12">
                <h1><?php _e( 'Filename', 'bidxplugin' ); ?>:&nbsp;<span class="filename"></span></h1>
            </div>
            <div class="col-sm-8">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php _e( 'Document', 'bidxplugin' ); ?></h3>
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            <label><?php _e('Purpose','bidxplugin'); ?></label>
                            <input type="text" class="form-control" name="purpose" placeholder="<?php _e('Please describe the attachment','bidxplugin'); ?>">
                        </div>
                        <div class="form-group">
                            <label><?php _e('Document type','bidxplugin'); ?></label>
                            <select name="documentType"></select>
                        </div>
                        <a href="#" class="btn btn-primary btnSave"></a>
                        <a href="#media/list" class="btn btn-default btnCancel"></a>
                    </div>
                </div>
            </div>

            <div class="col-sm-4">
                <div class="panel panel-default fileDetails">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?php _e( 'Details', 'bidxplugin' ); ?></h3>
                    </div>
                    <div class="panel-body">
                        <dl>
                            <dt><?php _e( 'Created on', 'bidxplugin' ); ?></dt>
                            <dd class="created"></dd>
                            <dt><?php _e( 'Filename', 'bidxplugin' ); ?></dt>
                            <dd class="filename"></dd>
                            <dt><?php _e( 'Filetype', 'bidxplugin' ); ?></dt>
                            <dd class="contentType"></dd>
                            <dt><?php _e( 'Size', 'bidxplugin' ); ?></dt>
                            <dd class="size"></dd>
                        </dl>

                        <a href="#" target="_blank" class="btn btn-warning btnDownload"><i class="fa fa-download"></i> <?php _e( 'Download', 'bidxplugin' ); ?></a>
                        <a href="#" class="btn btn-danger btnDelete"><i class="fa fa-ban"></i> <?php _e( 'Delete permanently', 'bidxplugin' ); ?></a>
                    </div>
                </div>
            </div>
        </form>
    </div>

    <!-- SNIPPETS -->
    <div class="snippets hide">

        <table class="fileItemTable">
            <tr class="fileItem">
                <td class="selectFile">
                    <div class="controls">

                        <div class="multiSelectCheckbox">
                            <div class="checkbox">
                                <input type="checkbox" value="true" id="checkbox-uploadCheckbox" name="uploadCheckbox" data-toggle="checkbox" />
                                <label for="checkbox-uploadCheckbox"><span></span></label>
                            </div>
                        </div>

                        <div class="multiSelectRadio">
                            <div class="radio">
                                <input type="radio" value="true" id="radio-uploadRadio" name="uploadRadio" data-toggle="radio" />
                                <label for="radio-uploadRadio"><span></span></label>
                            </div>
                        </div>
                    </div>
                </td>
                <td>
                    <a href="#" class="documentLink done" target="_blank">
                        <img class="documentImage"></img>
                    </a>

                    <div class="uploading">
                        <div class="progress progress-striped active">
                            <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 0%"></div>
                        </div>
                    </div>
                </td>
                <td>
                    <p class="name"></p>
                </td>
                <td class="hide-in-modal">
                    <p class="purpose"></p>
                    <p class="documentType"></p>
                </td>
                <td class="hide-in-modal">
                    <div class="done">
                        <a class="btn btn-info btnEdit pull-right" href="#">
                            <i class="fa fa-pencil-square-o"></i>
                            <span><?php _e( 'Edit', 'bidxplugin' ); ?></span>
                        </a>
                    </div>
                </td>
            </tr>
        </table>
    </div>

</div>

