<div id="media" class="row-fluid mainState mainStateMedia">

    <!-- LOAD -->
    <div class="view viewLoad span12">
        <span><?php _e('Loading media data...','bidxplugin'); ?></span>
    </div>

    <!-- ERROR -->
    <div class="view viewError span12">
        <h2><?php _e('Error','bidxplugin'); ?></h2>
        <p class="errorMsg"></p>
    </div>

    <!-- LIST -->
    <div class="view viewList">

        <div class="newFile well dropzone">
            <p><?php _e( 'Drop file here to upload', 'bidxplugin' ); ?></p>
            <p><?php _e( 'or', 'bidxplugin' ); ?></p>

            <!-- The fileinput-button span is used to style the file input field as button -->
            <span class="btn btn-success fileinput-button">
                <i class="fui-plus"></i>
                <span><?php _e( 'Select new file from your computer', 'bidxplugin' ); ?></span>

                <!-- The file input field used as target for the file upload widget -->
                <input type="file" class="fileUpload" name="fileContent" />
            </span>
        </div>

        <table class="fileList table table-striped">
            <tbody class="files"></tbody>
        </table>

    </div>

    <!-- EDIT of one file -->
    <div class="view viewEdit">

        <form id="frmeditMedia">

            <div class="span8">
                <fieldset class="well">
                    <legend><?php _e( 'Document', 'bidxplugin' ); ?></legend>

                    <div class="control-group">
                        <label class="control-label"><?php _e('Purpose','bidxplugin'); ?></label>
                        <div class="controls">
                            <input type="text" name="purpose" placeholder="<?php _e('Please describe the attachment','bidxplugin'); ?>">
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label"><?php _e('Document type','bidxplugin'); ?></label>
                        <div class="controls">
                            <select name="documentType"></select>
                        </div>
                    </div>

                    <a href="#" class="btn btn-primary btnSave"></a>
                    <a href="#media/list" class="btn btn-primary btnCancel"></a>

                </fieldset>
            </div>

            <div class="span4">
                <fieldset class="well fileDetails">
                    <legend><?php _e( 'Details', 'bidxplugin' ); ?></legend>

                    <dl>
                        <dt><?php _e( 'Created on', 'bidxplugin' ); ?></dt>
                        <dd class="created"></dd>
                        <dt><?php _e( 'Filename', 'bidxplugin' ); ?></dt>
                        <dd class="filename"></dd>
                        <dt><?php _e( 'Filetype', 'bidxplugin' ); ?></dt>
                        <dd class="contentType"></dd>
                        <dt><?php _e( 'Size', 'bidxplugin' ); ?></dt>
                        <dd class="size"></dd>
                    </dl>

                    <a href="#" target="_blank" class="btn btnDownload"><?php _e( 'Download', 'bidxplugin' ); ?></a>
                    <a href="#" class="btn btn-danger btnDelete"><?php _e( 'Delete permanently', 'bidxplugin' ); ?></a>
                </fieldset>
            </div>
        </form>
    </div>

    <div class="snippets hide">

        <table class="fileItemTable">
            <tr class="fileItem">
                <td class="selectFile">
                    <div class="controls">

                        <div class="multiSelectCheckbox">
                            <label class="checkbox"><input type="checkbox" value="true" name="uploadCheckbox"  /></label>
                        </div>

                        <div class="multiSelectRadio">
                            <label class="radio"><input type="radio" value="true" name="uploadRadio" /></label>
                        </div>
                    </div>
                </td>
                <td>
                    <a href="#" class="documentLink done">
                        <img class="documentImage"></img>
                    </a>

                    <div class="uploading">
                        <div class="progress progress-striped active">
                            <div class="bar" style="width: 0%;"></div>
                        </div>
                    </div>
                </td>
                <td>
                    <p class="name"></p>
                </td>
                <td>
                    <p class="purpose"></p>
                    <p class="documentType"></p>
                </td>
                <td>
                    <div class="done">
                        <a class="btn btn-warning btnEdit" href="#">
                            <i class="fui-new"></i>
                            <span><?php _e( 'Edit', 'bidxplugin' ); ?></span>
                        </a>
                    </div>
                </td>
            </tr>
        </table>
    </div>

</div>

