<div class="row-fluid">
    <div class="span8 offset2 bidx-well">
        <h1>Download business plan templates</h1>
        <ul class="unstyled">
            <li class="clearfix">
                <img class="documentImage pull-left" src="/wp-content/plugins/bidx-plugin/static/img/iconViewDocument.png">
                <div class="pull-left">
                    <h4>Full financial template <img src="/wp-content/themes/bidx-group-template/assets/img/flags/us.gif" alt="" /></h4>
                    <h5>18/11/2013</h5>
                </div>
                <a href="/wp-content/themes/bidx-group-template/assets/docs/businessplan/bidX_Financial_Plan_EN_V1_18112013.xls" class="btn btn-primary pull-right">Download</a>
            </li>
            <li class="clearfix">
                <img class="documentImage pull-left" src="/wp-content/plugins/bidx-plugin/static/img/iconViewDocument.png">
                <div class="pull-left">
                    <h4>Business plan template <img src="/wp-content/themes/bidx-group-template/assets/img/flags/us.gif" alt="" /></h4>
                    <h5>18/11/2013</h5>
                </div>
                <a href="/wp-content/themes/bidx-group-template/assets/docs/businessplan/bidX_Business_Plan_Template_EN_v1.0_18112013.doc" class="btn btn-primary pull-right">Download</a>
            </li>
            <li class="clearfix">
                <img class="documentImage pull-left" src="/wp-content/plugins/bidx-plugin/static/img/iconViewDocument.png">
                <div class="pull-left">
                    <h4>Completo finaciero modelo <img src="/wp-content/themes/bidx-group-template/assets/img/flags/es.gif" alt="" /></h4>
                    <h5>18/11/2013</h5>
                </div>
                <a href="/wp-content/themes/bidx-group-template/assets/docs/businessplan/bidX_Financial_Plan_ES_V1_18112013.xls" class="btn btn-primary pull-right">Download</a>
            </li>

            <li class="clearfix">
                <img class="documentImage pull-left" src="/wp-content/plugins/bidx-plugin/static/img/iconViewDocument.png">
                <div class="pull-left">
                    <h4>Plantilla de Plan de negocios <img src="/wp-content/themes/bidx-group-template/assets/img/flags/es.gif" alt="" /></h4>
                    <h5>18/11/2013</h5>
                </div>
                <a href="/wp-content/themes/bidx-group-template/assets/docs/businessplan/bidX_Business_Plan_Template_ES_v1.0_18112013.doc" class="btn btn-primary pull-right">Download</a>
            </li>
        </ul>
        <a href="javascript:window.history.back()" class="btn btn-warning btn-wide"><span class="fa fa-chevron-left"></span> Go Back</a>
    </div>
</div>
