<div class="row">
    <div class="col-sm-8 col-sm-offset-2 well">
        <h1>Download business plan templates</h1>
        <div class="row">
            <div class="col-sm-1">
                <i class="fa fa-file-text-o document-icon"></i>
            </div>
            <div class="col-sm-8">
                <h4>Full financial template <img src="/wp-content/themes/bidx-group-template/assets/img/flags/gb.gif" alt="" /></h4>
            </div>
            <div class="col-sm-3">
                <a href="/wp-content/plugins/bidx-plugin/assets/docs/businessplan/bidX_Financial_Plan_2014.xls" class="btn btn-primary pull-right"><i class="fa fa-download"></i> Download</a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-1">
                <i class="fa fa-file-text-o document-icon"></i>
            </div>
            <div class="col-sm-8">
                <h4>Business plan template <img src="/wp-content/themes/bidx-group-template/assets/img/flags/gb.gif" alt="" /></h4>
            </div>
            <div class="col-sm-3">
                <a href="/wp-content/plugins/bidx-plugin/assets/docs/businessplan/bidX_Business_Plan_Template_EN_2014.doc" class="btn btn-primary pull-right"><i class="fa fa-download"></i> Download</a>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-1">
                <i class="fa fa-file-text-o document-icon"></i>
            </div>
            <div class="col-sm-8">
                <h4>Modèle de plan financier <img src="/wp-content/themes/bidx-group-template/assets/img/flags/fr.gif" alt="" /></h4>
            </div>
            <div class="col-sm-3">
                <a href="/wp-content/plugins/bidx-plugin/assets/docs/businessplan/bidX_Financial_Plan_2014_Fr.xls" class="btn btn-primary pull-right"><i class="fa fa-download"></i> Download</a>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-1">
                <i class="fa fa-file-text-o document-icon"></i>
            </div>
            <div class="col-sm-8">
                <h4>Modèle de plan d' affaires <img src="/wp-content/themes/bidx-group-template/assets/img/flags/fr.gif" alt="" /></h4>
            </div>
            <div class="col-sm-3">
                <a href="/wp-content/plugins/bidx-plugin/assets/docs/businessplan/bidX_Business_Plan_Template_FR_2014__1.doc" class="btn btn-primary pull-right"><i class="fa fa-download"></i> Download</a>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-1">
                <i class="fa fa-file-text-o document-icon"></i>
            </div>
            <div class="col-sm-8">
                <h4>Plantilla de Plan de negocios <img src="/wp-content/themes/bidx-group-template/assets/img/flags/es.gif" alt="" /></h4>
            </div>
            <div class="col-sm-3">
                <a href="/wp-content/plugins/bidx-plugin/assets/docs/businessplan/bidX_Business_Plan_Template_ES_2014.doc" class="btn btn-primary pull-right"><i class="fa fa-download"></i> Download</a>
            </div>
        </div>
    </div>
</div>
