<div class="row">
    <div class="col-sm-8 col-sm-offset-2 bidx-well">
        <h1>Download finacial templates</h1>
        <ul class="list-unstyled">
            <li class="clearfix">
                <img class="documentImage pull-left" src="/wp-content/plugins/bidx-plugin/static/img/iconViewDocument.png">
                <div class="pull-left">
                    <h4>Full financial template <img src="/wp-content/themes/bidx-group-template/assets/img/flags/us.gif" alt="" /></h4>
                    <h5>03 June 2013</h5>
                    <h5>full_finacial_template.xlsx</h5>
                </div>
                <a href="/wp-content/themes/bidx-group-template/assets/docs/financial" class="btn btn-primary pull-right">Download</a>
            </li>
            <li class="clearfix">
                <img class="documentImage pull-left" src="/wp-content/plugins/bidx-plugin/static/img/iconViewDocument.png">
                <div class="pull-left">
                    <h4>Completo finaciero modelo <img src="/wp-content/themes/bidx-group-template/assets/img/flags/es.gif" alt="" /></h4>
                    <h5>03 June 2013</h5>
                    <h5>completo_finaciero_modelo.xlsx</h5>
                </div>
                <a href="/wp-content/themes/bidx-group-template/assets/docs/financial" class="btn btn-primary pull-right">Download</a>
            </li>
            <li class="clearfix">
                <img class="documentImage pull-left" src="/wp-content/plugins/bidx-plugin/static/img/iconViewDocument.png">
                <div class="pull-left">
                    <h4>Plein finacier modéle <img src="/wp-content/themes/bidx-group-template/assets/img/flags/fr.gif" alt="" /></h4>
                    <h5>03 June 2013</h5>
                    <h5>plein_finacier_modele.xlsx</h5>
                </div>
                <a href="/wp-content/themes/bidx-group-template/assets/docs/financial" class="btn btn-primary pull-right">Download</a>
            </li>
        </ul>
        <a href="javascript:window.history.back()" class="btn btn-warning btn-wide"><span class="fa fa-chevron-left"></span> Go Back</a>
    </div>
</div>
