<div class="row-fluid">
    <h1>Download finacial templates</h1>
    <div class="span6">

        <ul class="unstyled">
            <li>
                <img class="documentImage pull-left" src="/wp-content/plugins/bidx-plugin/static/img/iconViewDocument.png">
                <h2>Full financial template <img src="/wp-content/themes/bidx-group-template/assets/img/flags/us.gif" alt="" /></h2>
                <h5>03 June 2013</h5>
                <h5>full_finacial_template.xlsx</h5>
                <a href="/wp-content/themes/bidx-group-template/assets/docs/financial" class="btn btn-large btn-primary btn-block">Download</a>
            </li>
            <li>
                <img class="documentImage pull-left" src="/wp-content/plugins/bidx-plugin/static/img/iconViewDocument.png">
                <h2>Completo finaciero modelo <img src="/wp-content/themes/bidx-group-template/assets/img/flags/es.gif" alt="" /></h2>
                <h5>03 June 2013</h5>
                <h5>completo_finaciero_modelo.xlsx</h5>
                <a href="/wp-content/themes/bidx-group-template/assets/docs/financial" class="btn btn-large btn-primary btn-block">Download</a>
            </li>
            <li>
                <img class="documentImage pull-left" src="/wp-content/plugins/bidx-plugin/static/img/iconViewDocument.png">
                <h2>Plein finacier modéle <img src="/wp-content/themes/bidx-group-template/assets/img/flags/fr.gif" alt="" /></h2>
                <h5>03 June 2013</h5>
                <h5>plein_finacier_modele.xlsx</h5>
                <a href="/wp-content/themes/bidx-group-template/assets/docs/financial" class="btn btn-large btn-primary btn-block">Download</a>
            </li>
        </ul>
    </div>
</div>
