<div class="row-fluid">
    <div class="span8">

        <h1>Register as entrepreneur</h1>
        <div class="clearfix">
            <div class="pull-right">
                <img style="margin: 0 20px 0 0;" alt="" src="/wp-content/themes/bidx-group-template/assets/img/icons/icon-entrepreneur-dark.png" width="63" height="80" />
            </div>
            Thank you for your interest in becoming an entrepreneur in this group on the bidX platform.
            Before you start completing your entrepreneur registration, here are a few points and features that may be of interest to you.

        </div>
        <hr/>
        <ul class="unstyled">
            <li class="clearfix" style="margin-bottom: 20px;">

                <div class="pull-left">
                    <img style="margin: 0 20px 0 0;" alt="" src="/wp-content/themes/bidx-group-template/assets/img/icons/icon-magic.png" width="63" height="80" />
                </div>
                <div>
                    <div class="title">
                        <strong>Creating your entrepreneur profile</strong>
                    </div>
                    <div class="text">
                        Once you have completed and saved your information about you as an entrepreneur, you will be visible on the site as an entrepreneur. During the registration stage, you will be requested to give information about your investment preferences to enable us to find the best matches for you.
                     </div>
                </div>
            </li>
            <li class="clearfix" style="margin-bottom: 10px;">
                <div class="pull-left">
                    <img style="margin: 0 20px 0 0;" alt="" src="/wp-content/themes/bidx-group-template/assets/img/icons/icon-magic.png" width="63" height="80" />
                </div>
                <div>
                    <div class="title">
                        <strong>Your entrepreneur dashboard</strong>
                    </div>
                    <div class="text">
                        Once you have created your entrepreneur profile, you will have access to your entrepreneur dashboard. Here you can find business plans recommended to you by bidX, as well as the list of plans you have chosen yourself. This dashboard will be expanding in future to include further new, interesting features.
                    </div>
                </div>
            </li>
            <li class="clearfix" style="margin-bottom: 10px;">
                <div class="pull-left">
                    <img style="margin: 0 20px 0 0;" alt="" src="/wp-content/themes/bidx-group-template/assets/img/icons/icon-magic.png" width="63" height="80" />
                </div>
                <div>
                    <div class="title">
                        <strong>Visibility of your profile</strong>
                    </div>
                    <div class="text">
                        Your entrepreneur profile will be visible and searchable by other members on this platform, however, they will not be able to email you or request to become your contact.
                    </div>
                </div>
            </li>
            <li class="clearfix" style="margin-bottom: 10px;">
                <div class="pull-left">
                    <img style="margin: 0 20px 0 0;" alt="" src="/wp-content/themes/bidx-group-template/assets/img/icons/icon-magic.png" width="63" height="80" />
                </div>
                <div>
                    <div class="title">
                        <strong>Join other groups in bidX</strong>
                    </div>
                    <div class="text">
                        We encourage you to visit and join other groups in the bidX platform. By joining more groups, you will increase the number of matching plans you receive, and the number of potentially interesting entrepreneurs you meet. You will not need to register again as an entrepreneur in order to join new groups.
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>