<div class="row-fluid">
    <div class="span8">

        <h1>Register as a member</h1>
        <div class="clearfix">

            Thank you for your interest in becoming a member of group_name group on the bidX platform.<br/>
            Before you start the process of completing your personal profile, here are some points that may be of interest to you.

        </div>
        <hr/>
        <ul class="unstyled">
            <li class="clearfix" style="margin-bottom: 20px;">

                <div class="pull-left">
                    <img style="margin: 0 20px 0 0;" alt="" src="/wp-content/themes/bidx-group-template/assets/img/icons/icon-magic.png" width="63" height="80" />
                </div>
                <div>
                    <div class="title">
                        <strong>Completing your personal profile </strong>
                    </div>
                    <div class="text">
                        Your personal profile is the way for other members of the platform to get to know you and to contact you. Complete your profile to create your own identity in this group and on the bidX platform.
                     </div>
                </div>
            </li>
            <li class="clearfix" style="margin-bottom: 10px;">
                <div class="pull-left">
                    <img style="margin: 0 20px 0 0;" alt="" src="/wp-content/themes/bidx-group-template/assets/img/icons/icon-magic.png" width="63" height="80" />
                </div>
                <div>
                    <div class="title">
                        <strong>Register as entrepreneur, investor or mentor</strong>
                    </div>
                    <div class="text">
                        Choose the role that best fits your needs and benefit from our services and tools for entrepreneurs, investors and mentors. This platform offers tools and services that enable you to realize your business ambitions. As an entrepreneur, you can develop your business proposition to attract financiers, to find business contacts or to participate in a competition. As an investor, you can find finance ready investment proposals that fit your indicated preferences. All members are kept informed about news and events of the group.
                    </div>
                </div>
            </li>
            <li class="clearfix" style="margin-bottom: 10px;">
                <div class="pull-left">
                    <img style="margin: 0 20px 0 0;" alt="" src="/wp-content/themes/bidx-group-template/assets/img/icons/icon-magic.png" width="63" height="80" />
                </div>
                <div>
                    <div class="title">
                        <strong>Increase your network</strong>
                    </div>
                    <div class="text">
                        Add interesting members from this or other groups to your list of contacts. Once you are a contact you will be able to send each other messages through the email system of the platform.
                    </div>
                </div>
            </li>
            <li class="clearfix" style="margin-bottom: 10px;">
                <div class="pull-left">
                    <img style="margin: 0 20px 0 0;" alt="" src="/wp-content/themes/bidx-group-template/assets/img/icons/icon-magic.png" width="63" height="80" />
                </div>
                <div>
                    <div class="title">
                        <strong>Visibility of your profile</strong>
                    </div>
                    <div class="text">
                        The most general part of your data will be visible to members in this group, but it will also appear in search results from members in other groups. You can share more data by becoming a contact of someone and sharing information with him/her.
                    </div>
                </div>
            </li>
            <li class="clearfix" style="margin-bottom: 10px;">
                <div class="pull-left">
                    <img style="margin: 0 20px 0 0;" alt="" src="/wp-content/themes/bidx-group-template/assets/img/icons/icon-magic.png" width="63" height="80" />
                </div>
                <div>
                    <div class="title">
                        <strong>Join other groups in bidX</strong>
                    </div>
                    <div class="text">
                        We encourage you to visit and join other groups on the bidX platform. In this way you will make your profile and business data more accessible to members of those groups. You won't need to register or log in again (if you already have). By joining other groups, your profile will become visible to a larger number of members. You can find groups that fit your interests by searching in our group database. You can specify your search by location, industry focus for example.
                    </div>
                </div>
            </li>
        </ul>
        <div>
            <a href="/member" class="btn btn-danger btn-wide pull-right">Continue</a>
        </div>
    </div>
</div>