<div class="row">
    <div class="col-sm-8 col-sm-offset-2">
        <h1>Register as mentor</h1>
        <blockquote class="alert-success">
            THIS HAS BEEN COPIED FROM INVESTOR<br/>
            Thank you for registering as entrepreneur on this bidx.net group!<br/>
            Before completing your entrepreneur profile, here are some points that may be of interest to you:
        </blockquote>
        <hr/>

        <dl>
            <dt class="title">Creating your entrepreneur profile</dt>
            <dd class="text">
                Once you have completed and saved your entrepreneur profile, it will become visible to the group you joined as well as other groups. Your entrepreneur profile is short and easy to complete. It essentially gives you the opportunity to pitch yourself as an entrepreneur to other members of bidx.net groups.
             </dd>
            <hr>

            <dt class="title">Submitting your business proposal</dt>
            <dd class="text">
                Once you have created your entrepreneur profile, you will be able to give information about your business. This is a simple form (with instructions should you require them), that will take only a few minutes to complete.
            </dd>
            <hr>

            <dt class="title">Visibility of your profile and business data</dt>
            <dd class="text">
                Your profile and business summary will be visible and discoverable to members of other groups on bidx.net. This stimulates the creation and growth of entrepreneurial ecosystems, while helping you build a larger, more relevant network for your business.<br/>
                However, attached documents are only visible to you and investors that you have allowed to view your data. You will be able to check an investor’s profile before deciding whether to give him/her permission to access these documents.
            </dd>
            <hr>

            <dt class="title">Joining other groups on bidx.net</dt>
            <dd class="text">
                We encourage you to visit and join other groups on bidx.net. You won’t need to register as entrepreneur again, or re-enter your business data, but you can create a new business proposal if you wish to do so. By joining other groups, you will be visible to a larger number of members, thus increasing your chances of finding an interested investor, buyer, potential client, etc.<br/>
                <div class="text alert-danger">
                    There is no restriction to the number of groups that you can join, however please note that some groups may restrict access to members based on region or sector of business, for example.
                </div>
            </dd>

        </dl>
        <div>
            <a href="/member/#createEntrepreneur" class="btn btn-danger btn-wide pull-right">Continue</a>
        </div>
    </div>
</div>
