<div class="row">
    <div class="col-sm-8 col-sm-offset-2">

        <h1>Register as a member</h1>
        <blockquote class="alert-success">
            Thank you for your interest in becoming a member of %group_name% group on the bidX platform.
        </blockquote>
        <blockquote class="alert-success">
            Before you start the process of completing your personal profile, here are some points that may be of interest to you.
        </blockquote>
        <hr/>
        <dl>

            <dt class="title">Completing your personal profile</dt>
            <dd class="text">
                Your personal profile is the way for other members of the platform to get to know you and to contact you. Complete your profile to create your own identity in this group and on the bidX platform.
             </dd>
            <hr>

            <dt class="title">Register as entrepreneur, investor or mentor</dt>
            <dd class="text">
                Choose the role that best fits your needs and benefit from our services and tools for entrepreneurs, investors and mentors. This platform offers tools and services that enable you to realize your business ambitions. As an entrepreneur, you can develop your business proposition to attract financiers, to find business contacts or to participate in a competition. As an investor, you can find finance ready investment proposals that fit your indicated preferences. All members are kept informed about news and events of the group.
            </dd>
            <hr>

            <dt class="title">Increase your network</dt>
            <dd class="text">
                Add interesting members from this or other groups to your list of contacts. Once you are a contact you will be able to send each other messages through the email system of the platform.
            </dd>
            <hr>

            <dt class="title">Visibility of your profile</dt>
            <dd class="text">
                The most general part of your data will be visible to members in this group, but it will also appear in search results from members in other groups. You can share more data by becoming a contact of someone and sharing information with him/her.
            </dd>
            <hr>

            <dt class="title">Join other groups in bidX</dt>
            <dd class="text">
                We encourage you to visit and join other groups on the bidX platform. In this way you will make your profile and business data more accessible to members of those groups. You won't need to register or log in again (if you already have). By joining other groups, your profile will become visible to a larger number of members. You can find groups that fit your interests by searching in our group database. You can specify your search by location, industry focus for example.
            </dd>

        </dl>
        <div>
            <a href="/member" class="btn btn-danger btn-wide pull-right">Continue</a>
        </div>
    </div>
</div>
