<div class="row-fluid">
    <div class="span8 offset2">
        <h1>Register as entrepreneur</h1>
        <div class="clearfix">
            <div class="pull-right">
                <img style="margin: 0 20px;" alt="" src="/wp-content/themes/bidx-group-template/assets/img/icons/icon-entrepreneur-dark.png" width="63" height="80" />
            </div>
            Thank you for your interest in becoming an entrepreneur in this group on the bidX platform
            Before you start the process of completing your entrepreneur registration, here are some points that may be of interest to you
        </div>
        <hr/>
        <ul class="unstyled">
            <li class="clearfix" style="margin-bottom: 20px;">

                <div class="pull-left">
                    <img style="margin: 0 20px 0 0;" alt="" src="/wp-content/themes/bidx-group-template/assets/img/icons/icon-magic.png" width="63" height="80" />
                </div>
                <div>
                    <div class="title">
                        <strong>Creating your entrepreneur profile</strong>
                    </div>
                    <div class="text">
                        When you have completed and saved your entrepreneur profile, you will be able to publish it and make it visible to the group. This means that other members viewing your profile will be able to view your entrepreneur information. Your entrepreneur profile is short and easy to complete. It essentially gives you the opportunity to pitch yourself as an entrepreneur to other members of the site
                     </div>
                </div>
            </li>
            <li class="clearfix" style="margin-bottom: 10px;">
                <div class="pull-left">
                    <img style="margin: 0 20px 0 0;" alt="" src="/wp-content/themes/bidx-group-template/assets/img/icons/icon-magic.png" width="63" height="80" />
                </div>
                <div>
                    <div class="title">
                        <strong>Submitting your business proposal/strong>
                    </div>
                    <div class="text">
                        Once you have created your entrepreneur profile, you will be able to give information about your business. This is a simple form (with instructions should you require them), that will take only a few minutes to complete, ready for publication.
                    </div>
                </div>
            </li>
            <li class="clearfix" style="margin-bottom: 10px;">
                <div class="pull-left">
                    <img style="margin: 0 20px 0 0;" alt="" src="/wp-content/themes/bidx-group-template/assets/img/icons/icon-magic.png" width="63" height="80" />
                </div>
                <div>
                    <div class="title">
                        <strong>Visibility of your profile and business</strong>
                    </div>
                    <div class="text">
                        Your data will be visible and discoverable to other members in other groups on this platform. However, they will only be able to view part of your information. For now, only investors who are interested in your business, and that you give permission to, will be able to see your data. The profile of the investor will become visible to you, so then you can decide whether you want to grant them access to your business information
                    </div>
                </div>
            </li>
            <li class="clearfix" style="margin-bottom: 10px;">
                <div class="pull-left">
                    <img style="margin: 0 20px 0 0;" alt="" src="/wp-content/themes/bidx-group-template/assets/img/icons/icon-magic.png" width="63" height="80" />
                </div>
                <div>
                    <div class="title">
                        <strong>Join other groups in bidX</strong>
                    </div>
                    <div class="text">
                        We encourage you to visit and join other groups in the bidX platform. You won't need to register as entrepreneur again, or re-enter your business data, although you could create a new business proposal if you wish to do so. By joining other groups, you will be visible to a larger number of members
                    </div>
                </div>
            </li>
        </ul>
        <div>
            <a href="/member/#createEntrepreneur" class="btn btn-danger btn-wide pull-right">Continue</a>
        </div>
    </div>
</div>
