<div class="row">
    <div class="col-sm-8 col-sm-offset-2">
        <h1>Register as mentor</h1>
        <blockquote class="alert-success">
            Thank you for your interest in becoming a mentor in this group on the bidX platform.
        </blockquote>
        <blockquote class="alert-success">
            Before you start completing your mentor registration, here are a few points and features that may be of interest to you.
        </blockquote>
        <hr/>
        <dl>

            <dt class="title">Creating your mentor profile</dt>
            <dd class="text">
                Once you have completed and saved your information about you as mentor, you will be visible on the site as a mentor. During the registration stage, you will be requested to give information about your experience, knowledge and mentoring preferences.
             </dd>
            <hr>

            <dt class="title">Visibility of your profile</dt>
            <dd class="text">
                Your mentor profile will be visible and searchable by other members on this platform, and they will also be able to email you or request to become your contact.
            </dd>
            <hr>

            <dt class="title">Join other groups in bidX</dt>
            <dd class="text">
                We encourage you to visit and join other groups in the bidX platform. By joining more groups, you will increase the number of matching plans you receive, and the number of potentially interesting entrepreneurs you meet. You will not need to register again in order to join new groups.
            </dd>

        </dl>
        <div>
            <a href="/member/#createMentor" class="btn btn-danger btn-wide pull-right">Continue</a>
        </div>
    </div>
</div>
