<div class="row">
    <div class="col-sm-8 col-sm-offset-2">
        <h1>Register as investor</h1>
        <blockquote class="alert-success">
            Thank you for your interest in becoming an investor in this group on the bidX platform.
        </blockquote>
        <blockquote class="alert-success">
            Before you start completing your investor registration, here are a few points and features that may be of interest to you.
        </blockquote>
        <hr/>
        <dl>

            <dt class="title">Creating your investor profile</dt>
            <dd class="text">
                Once you have completed and saved your information about you as an investor, you will be visible on the site as an investor. During the registration stage, you will be requested to give information about your investment preferences to enable us to find the best matches for you.
             </dd>
            <hr>

            <dt class="title">Your investor dashboard</dt>
            <dd class="text">
                Once you have created your investor profile, you will have access to your investor dashboard. Here you can find business plans recommended to you by bidX, as well as the list of plans you have chosen yourself. This dashboard will be expanding in future to include further new, interesting features.
            </dd>
            <hr>

            <dt class="title">Visibility of your profile</dt>
            <dd class="text">
                Your investor profile will be visible and searchable by other members on this platform, however, they will not be able to email you or request to become your contact.
            </dd>
            <hr>

            <dt class="title">Join other groups in bidX</dt>
            <dd class="text">
                We encourage you to visit and join other groups in the bidX platform. By joining more groups, you will increase the number of matching plans you receive, and the number of potentially interesting entrepreneurs you meet. You will not need to register again as an investor in order to join new groups.
            </dd>

        </dl>
        <div>
            <a href="/member/#createInvestor" class="btn btn-danger btn-wide pull-right">Continue</a>
        </div>
    </div>
</div>
