<div class="row">
    <div class="col-sm-8 col-sm-offset-2">
        <h1>Register as entrepreneur</h1>
        <blockquote class="alert-success">
            Thank you for your interest in becoming an entrepreneur in this group on the bidX platform
        </blockquote>
        <blockquote class="alert-success">
            Before you start the process of completing your entrepreneur registration, here are some points that may be of interest to you
        </blockquote>
        <hr/>


        <dl>

            <dt class="title">Creating your entrepreneur profile</dt>
            <dd class="text">
                When you have completed and saved your entrepreneur profile, you will be able to publish it and make it visible to the group. This means that other members viewing your profile will be able to view your entrepreneur information. Your entrepreneur profile is short and easy to complete. It essentially gives you the opportunity to pitch yourself as an entrepreneur to other members of the site
             </dd>
            <hr>

            <dt class="title">Submitting your business proposal</dt>
            <dd class="text">
                Once you have created your entrepreneur profile, you will be able to give information about your business. This is a simple form (with instructions should you require them), that will take only a few minutes to complete, ready for publication.
            </dd>
            <hr>

            <dt class="title">Visibility of your profile and business</dt>
            <dd class="text">
                Your data will be visible and discoverable to other members in other groups on this platform. However, they will only be able to view part of your information. For now, only investors who are interested in your business, and that you give permission to, will be able to see your data. The profile of the investor will become visible to you, so then you can decide whether you want to grant them access to your business information
            </dd>
            <hr>

            <dt class="title">Join other groups in bidX</dt>
            <dd class="text">
                We encourage you to visit and join other groups in the bidX platform. You won't need to register as entrepreneur again, or re-enter your business data, although you could create a new business proposal if you wish to do so. By joining other groups, you will be visible to a larger number of members
            </dd>

        </dl>


        <div>
            <a href="/member/#createEntrepreneur" class="btn btn-danger btn-wide pull-right">Continue</a>
        </div>
    </div>
</div>
