<div class="row">
    <div class="col-sm-8 col-sm-offset-2">
        <h1>Privacy statement</h1>
        <p>This Privacy Statement applies to the personal information that is collected in relation to your use of the bidx Platform as well as the manner in which this information is subsequently used and stored.</p>
        <p>First of all, the information which you provide will be collected and used by the Licensors to which Portal you have subscribed. The Licensor is responsible for the use of your personal information for the purposes described below. All personal information will be collected, used and stored with all due care and diligence, in accordance with the applicable legislation.</p>
        <p>Secondly, the personal information collected through the Platform and Portal will be sent to bidx. Bidx is responsible for the use of your personal information for the purposes as described below. All personal information will be collected, used and stored with all due care and diligence, in accordance with the Data Protection Act of The Netherlands.</p>
        <p>Please be advised that bidx has no control over the manner in which the Licensors collect and use personal information. Bidx can therefore not be held liable for any damages occurring as a result thereof.</p>
        <p>In this Privacy Statement the terms written with an initial capital letter, that have not been defined above, have the meaning given to them in the User Terms of Service.</p>
        <h3>1. Who is the Licensor?</h3>
        <p>Licensor is <code>[insert name of organisation, that operates this portal, and its address.]</code></p>
        <h3>2. Who is bidx?</h3>
        <p>bidx is a web services company that facilitates the start, growth and finance of small businesses in emerging markets. It is owner and operator of <a target="_blank" href="http://bidx.net">http://bidx.net</a>  and <a target="_blank" href="http://www.bidnetwork.org">www.bidnetwork.org</a>. Bidx offers its web-services to entrepreneurs; to intermediaries that serve entrepreneurs; to mentors and to financiers of small businesses. It is based in Amsterdam, The Netherlands and works with partners all over the world.</p>
        <p>The manner in which your personal information will be stored and used has been registered with The Netherlands Data Protection Authority.</p>
        <h3>3. Which information does Licensor collect?</h3>
        <p>The information provided by the User is collected by bidx via the Portal’s and the Platform’s screens. The Licensor receives this information, from the Portal and the Platform via monitoring reports. The information provided in these monitoring reports contains all user information except their email address.</p>
        <h3>4. Information collect by bidx</h3>
        <h4><em>User Account</em></h4>
        <p>To use the Platform and the Portal, you need to create a personal User Account. If you create such a User Account, you will be asked to provide information about yourself. You can always modify the information at a later stage.</p>
        <h4><em>Information about use</em></h4>
        <p>the Licensor will compile data about the way you are utilising the Platform and Portals, including, but not limited to, times logged in, pages visited, Portals that you are a member of, interactions between you and other Users. However, the Licensor cannot see the content of the messages you send to Users on bidx.net nor your email address.</p>
        <h4><em>Content</em></h4>
        <p>The Licensor stores and processes all of the User Content that you make available through the Platform and/or the Portals.</p>
        <p>When you terminate your User Account, the Licensor will in principle delete your User Content. However, the Licensor and bidx remain entitled to use some of the User Content, for historical statistics purposes. The User Content that remains after deleting will only be visible to the administrator of bidx and Licensor.</p>
        <h4><em>Data localisation</em></h4>
        <p>To be able to offer you relevant information related to your location, such as members, events, mentors or investors near you, the Licensor will collect information on where you are located.</p>
        <h4><em>Transfer to bidx</em></h4>
        <p>The personal information collected by the Licensor as described above in paragraph 3, will also be transferred to bidx. Bidx will use this personal information of the purposes as described under paragraph 6. Bidx also directly collects personal information that is not shared with the Licensor. The manner in which the personal information is collected is stated below.</p>
        <h4><em>Automatically generated information</em></h4>
        <p>In order to function optimally (for example, in order to reproduce information well and to secure the Platform), bidx needs certain information. Bidx therefore collects automatically generated information about your surfing behaviour when you use the Platform and/or Portals. This information consists of your IP address (the number of your computer that enables bidx to recognise your computer), the type of browser (the computer application used to view internet pages), the computer system that you use, your account number and the pages that you visit on the Platform.</p>
        <h4><em>Cookies</em></h4>
        <p>bidx uses cookies on the Platform for a variety of reasons which you can learn about below. The cookies bidx use do not store personally identifiable information, other than your IP-address, nor can they harm your computer. Bidx wants the Platform to be informative, personal, and as user friendly as possible and cookies help bidx to achieve that goal.</p>
        <p>By using the Platform, you agree to the use of cookies and other technologies as set out in this policy. Bidx appreciates some Users may like more individual control over their visit to the Platform and can adjust their settings accordingly. You can read all about this in the section below "How to control and delete cookies". If you do not agree to such use, please refrain from using the Platform.</p>
        <p>bidx uses both persistent and session cookies:</p>
        <p>Persistent cookies are used to allow the Platform to recognise Users when they return to the Platform and to remember certain information about their preferences. These cookies are cookies which stay on your computer permanently, until you "manually" delete them.</p>
        <p>Session cookies are used in order to allow Users to carry information across pages of the Platform without having to re-enter such information. These cookies delete themselves automatically when you leave the Platform and go to another website, or when you shut down your browser.bidx has also developed relationships with carefully selected and monitored partners, to assist in the delivery of a high quality Platform. Some of these partners may also set cookies during your visit to support customisation of adverts that you may see elsewhere on the Internet, and/or in order to meet contractual obligations with bidx.</p>
        <p>While these cookies do not store any personal details relating to you or your credit cards, please note we do not have access or control over the cookies and similar technologies that partners of bidx use.</p>
        <p>Social Media Cookies <br> To enrich the Platform content, sometimes bidx may embed video content from other social media websites such as Linkedin, YouTube or Facebook.   As a result, when you visit a page with content embedded, you may be presented with cookies from these websites.  bidx has no control or liability over these cookies set, so you should check the relevant third party's cookie policy for more information.</p>
        <p>bidx also offers a 'share page' widget on some of the Platform pages, where content can be shared easily on the following sites - Facebook, Twitter, LinkedIn, etc.  These sites may set a cookie when you are logged into their service.  bidx has no control or liability over these cookies set, so you should check the relevant third party's cookie policy for more information.</p>
        <p>How to control cookies <br> bidx will not use cookies to collect personally identifiable information about you. However, should you choose to disable, reject or block our cookies, some parts of the Platform will not function fully, or in some cases, the Platform will not be accessible at all.</p>
        <p>For more information on how to control your cookie settings and browser settings, or how to delete cookies on your hard drive, please visit <a target="_blank" href="http://www.aboutcookies.org">www.aboutcookies.org</a>.</p>
        <h3>5. For which purposes will the Licensor use your personal information?</h3>
        <h4><em>Purposes</em></h4>
        <p>Licensor will use the personal information collected about you for the following purposes:</p>
        <ul>
            <li>To enable you to create and use your User Account;</li>
            <li>To connect you to other relevant Users and content;</li>
            <li>To send you information about Licensor’s own, similar services; </li>
            <li>To send you messages from other Users, if you have consented to this;</li>
            <li>To furnish your information to third parties pursuant to statutory obligations;</li>
        </ul>
        <h4><em>Use by the Licensor</em></h4>
        <p>The Licensor offers you the possibility to create a User Account in order to access the Portal. To ensure that you are provided relevant advertising and/or offers, the Licensor will use the information from your User Account, the Automatically Generated Information and/or other information provided under the Agreement.</p>
        <p>The Licensor may occasionally send you email updates about its latest products and services, as well as special offers to those who subscribe to such services. Should you decide not to receive any email updates from the Licensor, feel free to unsubscribe from these services or please email the Licensor to remove you from the subscription list. An opportunity to opt out is also provided in every message the Licensor send you.</p>
        <h3>6. For which purposes will bidx use your personal information?</h3>
        <p>bidx will use the personal information collected about you for the following purposes:</p>
        <ul>
            <li>to enable you to use the Platform and the Portals;</li>
            <li>to connect you to relevant Users, Portals, events, and content;</li>
            <li>market research via surveys to better serve your needs, improve the effectiveness of the Platform, the Portal, our various types of communications, advertising campaigns, and/or promotional activities;</li>
            <li>to send you information about bidx Parties own, similar services; </li>
            <li>to formulate anonymous, statistical data;</li>
            <li>to implement security for the Platform and Portal; to send you messages from third parties, if you have consented to this;</li>
            <li>to furnish your information to third parties pursuant to statutory obligations</li>
        </ul>
        <h4><em>Use by bidx</em></h4>
        <p>bidx offers you access to the Platform. To ensure that you are provided relevant advertising and/or offers, bidx will use the information from your User Account, the Automatically Generated Information and/or other information provided under the Agreement.</p>
        <p>bidx may occasionally send you email updates about our latest products and services, as well as special offers to those who subscribe to such services. Should you decide not to receive any email updates from us, feel free to unsubscribe from these services or please email us to remove you from the subscription list. An opportunity to opt out is also provided in every message bidx Parties send you.</p>
        <h3>7. Use by third parties</h3>
        <h4><em>Use by third parties</em></h4>
        <p>bidx and/or Licensor will not furnish your personal information to third parties for direct marketing purposes (such as sending advertising) without your explicit permission.</p>
        <p>bidx and/or Licensor may furnish your personal information to third parties insofar as this information cannot be traced back to you personally. In other words, insofar as this information is made anonymous, Licensor and/or bidx may provide your information to third parties if it is required to do so by law, is forced to do so because of an actual or potential lawsuit and/or if it deems this necessary to protect its own rights.</p>
        <p>Finally, bidx may furnish your information to third parties insofar as this is necessary in bidx‘s opinion to offer the Platform and/or Portals to you.</p>
        <h3>8. How is personal information protected?</h3>
        <p>Licensor and bidx have taken appropriate technical and organisational measures to secure your personal information against loss and other types of unlawful processing. Bidx stores our personal information in Ireland (in the European Union) at Amazon Web Services.</p>
        <p>Your personal information is safeguarded against inappropriate use through your user name and password. Log-in data may be sent and stored in encrypted form as well. Licensor and/or bidx cannot, however, guarantee that unauthorised third parties will never circumvent the measures taken by Licensor and/or bidx and will not use your personal information for improper purposes.</p>
        <h3>9. Storage of your personal information</h3>
        <p>Licensor and bidx will not save your personal information longer than necessary to accomplish the purposes for which the information has been compiled and processed.</p>
        <h3>10. Examination and correction of your personal information</h3>
        <p>If you wish to know what information Licensor and/or bidx have collected about you, you can send Licensor and/or bidx a request to receive an overview of your personal information by sending an email. The Licensor and/or bidx will provide you with the written information within four (4) weeks.</p>
        <dl class="dl-horizontal">
            <dt>Licensor:</dt><dd><code>[insert email address Licensor]</code></dd>
            <dt>bidx:</dt><dd><a href="mailto:info@bidx.net">info[at]bidx.net</a></dd>
        </dl>
        <p>If the personal information the Licensor and/or bidx process about you is inaccurate, incomplete or unnecessary for the purposes for which it was collected, you can request to the Licensor and/or bidx to rectify, erase or block the information. Bidx will respond to such a request within four (4) weeks by sending a request to the email addresses stated above.</p>
        <h3>11. What is the scope of this Privacy Statement?</h3>
        <p>The Platform and Portal may contain links and/or references to third party websites and/or content. The Licensor and bidx are not responsible or liable for these third party websites and/or content. If you leave the Platform and/or Portal to visit this third party websites and/or content, please be advised that third party privacy statements may apply to the collection and use of your personal information. This Privacy Statement only pertains to the personal information collected through the Platform and Portal.</p>
        <h3>12. Transfer of business bidx</h3>
        <p>Should bidx grow and develop further (or for other reasons), one or more units or assets of bidx’s business may be transferred or outsourced to a third party, bidx may be acquired by a third party or bidx may merge with a third party. In that case, too, your personal information will be transferred.</p>
        <h3>13. Can this Privacy Statement be changed?</h3>
        <p>This Privacy Statement can be changed. These changes will be announced through the Platform and the Portal.</p>
        <h3>14. Questions?</h3>
        <p>If you have any questions about this Privacy Statement, please send an email to <code>[insert email address Licensor]</code> or <a href="mailto:info@bidx.net">info[at]bidx.net</a>.</p>
    </div>
</div>
