<div class="row">
    <div class="col-sm-8 col-sm-offset-2">
        <h1>Privacy statement</h1>
        <p>The information and data that you provide through this Web Portal is stored and managed by bidX (www.bidx.net). bidX respects the privacy of all users of its Platform and treats personal information (personal data) provided by them as confidential. We will collect, use and store such information with all due care and diligence, in accordance with the Dutch Data Protection Act.</p>
        <p>This Privacy Statement explains what information bidX, the moderator of this Portal and other participating interests (hereinafter together: “bidX”) collect, how we use it, and how this can benefit your experience of our Platform. With respect to this information and the manner in which we use it, bidX is considered the “controller” as meant in the Dutch Data Protection Act.</p>
        <p>Please be advised that this Privacy Statement does not pertain to the manner in which the Administrator or Moderator of this Portal (we call this Party the "The Licensor") collect, use and otherwise process your personal data you provided to them when subscribing to a Portal and make use of the service related thereto. bidX has agreed with the Licensor that the Licensor is only entitled to process your personal data in so far as necessary in order to provide access to the Portal and the services provided there under. Notwithstanding the above, bidX has no control over the manner in which the Licensor collects and uses personal data and can not be held liable for any damages occurring as a result thereof.</p>
        <p>This personal data provided to Licensors will also be transferred to bidX. For the manner in which bidX subsequently uses this personal data, bidX is deemed controller.</p>
        <p>In these Privacy Statement the terms written with an initial capital letter, that have not been defined above, have the meaning given to them in the General Terms and Conditions.</p>
        <h3>2. Who is bidX?</h3>
        <p>BidX is a web services company that facilitates the start, growth and finance of small businesses in emerging markets. It is owner and operator of <a target="_blank" href="http://www.bidx.net/">www.bidx.net</a> and <a target="_blank" href="http://www.bidnetwork.org/">www.bidnetwork.org</a> . BidX offers its web-services to entrepreneurs; to intermediaries that serve entrepreneurs; to mentors and to financiers of small businesses. It is based in Amsterdam, The Netherlands ad works with partners all over the world.</p>
        <p>The manner in which your personal data will be stored and used has been registered with the Dutch Data Protection Authority.</p>
        <h3>2. Which information does bidX collect?</h3>
        <h5><em>Account </em></h5>
        <p>To use the Platform, you need to create a personal Account. If you create such an Account, you will be asked to provide information about yourself. You can always modify the information at a later stage.</p>
        <h5><em>Information about use</em></h5>
        <p>bidX will compile data about the way you are utilising the Platform and Portals, including, but not limited to, times logged in, pages visited, Portals or Groups that you are a member of, interactions between you and other members. However we cannot see the content of the messages you send to members on bidx.net.</p>
        <h5><em>Content</em></h5>
        <p>bidX stores and processes all of the Member Content that you make available through the Platform and/or the Portals.</p>
        <p>When you terminate your Account, bidX will in principle delete your Member Content. However, bidX remains entitled to use some of the Member Content, for historical statistics purposes.</p>
        <h5><em>Automatically generated information</em></h5>
        <p>In order to function optimally (for example, in order to reproduce information well and to secure the Platform), bidX needs certain information. bidX therefore collects automatically generated information about your surfing behaviour when you use the Platform and/or Portals. This information consists of your IP address (the number of your computer that enables bidX to recognise your computer), the type of browser (the computer program used to view internet pages), the computer system that you use, your account number and the pages that you visit on the Platform.</p>
        <h5><em>Data localisation</em></h5>
        <p>To be able to offer you relevant information related to your location, such as members, events, mentors, etc. near you bidX will collect information on where you are located.</p>
        <h3> 3. What are cookies, and how does bidX use these?</h3>
        <p>bidX uses cookies on our website for a variety of reasons which you can learn about below. The cookies we use do not store personally identifiable information nor can they harm your computer. We want our website to be informative, personal, and as user friendly as possible and cookies help us to achieve that goal.</p>
        <p>By using our website, you agree to the use of cookies and other technologies as set out in this policy. We appreciate some users may like more individual control over their visit to our website and can adjust their settings accordingly. You can read all about this in the section below "How to control and delete cookies". If you do not agree to such use, please refrain from using the website.</p>
        <p>bidX uses both persistent and session cookies:</p>
        <p>Persistent cookies are used to allow the website to recognise users when they return to the site and to remember certain information about their preferences. These cookies are cookies which stay on your computer permanently, until you "manually" delete them.</p>
        <p>Session cookies are used in order to allow customers to carry information across pages of the website, without having to re-enter such information. These cookies delete themselves automatically when you leave a website and go to another, or when you shut down your browser.</p>
        <p>We have also developed relationships with carefully selected and monitored partners, to assist in the delivery of a high quality website. Some of these partners may also set cookies during your visit to support customisation of adverts that you may see elsewhere on the Internet, and/or in order to meet contractual obligations with us.</p>
        <p>While these cookies do not store any personal details relating to you or your credit cards, please note we do not have access or control over the cookies and similar technologies that our partners use.</p>
        <h5><em>Social Media Cookies</em></h5>
        <p>To enrich our website content, sometimes we may embed video content from other social media websites such as YouTube or Facebook.   As a result, when you visit a page with content embedded, you may be presented with cookies from these websites.  bidX has no control or liability over these cookies set, so you should check the relevant third party's cookie policy for more information.</p>
        <p>We also offer a 'share page' widget on some of our web pages, where content can be shared easily on the following sites - Facebook, Twitter, LinkedIn, MySpace, Delicious and Digg.  These sites may set a cookie when you are logged into their service.  bidX has no control or liability over these cookies set, so you should check the relevant third party's cookie policy for more information.</p>
        <h5><em>How to control cookies</em></h5>
        <p>bidX will not use cookies to collect personally identifiable information about you. However, should you choose to disable, reject or block our cookies, some parts of our website will not function fully, or in some cases, our website will not be accessible at all.</p>
        <p>For more information on how to control your cookie settings and browser settings, or how to delete cookies on your hard drive, please visit <a target="_blank" href="http://www.aboutcookies.org/">www.aboutcookies.org</a> .</p>
        <h3>4. For which purposes will your information be collected?</h3>
        <h5><em>Purposes</em></h5>
        <p>bidX will use the personal data collected about you for the following purposes:</p>
        <ul>
            <li>to enable you to use the Platform and the Portals;</li>
            <li>to connect you to relevant Members, Portals, Groups, Events, and content;</li>
            <li>market research via surveys to better serve your needs, improve the effectiveness of our Platform, our various types of communications, advertising campaigns, and/or promotional activities;</li>
            <li>to send you information about bidX’s own, similar services;</li>
            <li>to formulate anonymous, statistical data;</li>
            <li>to implement security for the Platform;</li>
            <li>to send you messages from third parties, if you have consented to this;</li>
            <li>to furnish your information to third parties pursuant to statutory obligations.</li>
        </ul>
        <h5><em>Use by bidX</em></h5>
        <p>bidX offers you the Platform. To ensure that you are provided relevant advertising and/or offers, bidX will use the data from your Account, the Automatically Generated Information and/or other data provided under the Agreement.</p>
        <p>bidX will occasionally send you email updates about our latest products and services, as well as special offers to those who subscribe to such services. Should you decide not to receive any email updates from us, feel free to unsubscribe from these services or please email us to remove you from the subscription list. An opportunity to opt out is also provided in every message bidX sends you.</p>
        <h5><em>Use by third parties</em></h5>
        <p>bidX will not furnish your personal data to third parties for direct marketing purposes (such as sending advertising) without your explicit permission.</p>
        <p>bidX may, though, furnish your data to third parties insofar as this is necessary in bidX’s opinion to offer the Platform and/or Portals to you and/or insofar as this data cannot be traced back to you personally (in other words, insofar as bidX has made this data anonymous). Finally, bidX may provide your data to third parties if it is required to do so by law, is forced to do so because of an actual or potential lawsuit and/or if it deems this necessary to protect its own rights.</p>
        <h3>5. How is personal information protected?</h3>
        <p>bidX has taken appropriate technical and organisational measures to secure your personal data against loss and other types of unlawful processing. bidX’s data is stored within the European Union.</p>
        <p>Your personal data is safeguarded against inappropriate use through your user name and password. Log-in data may be sent and stored in encrypted form as well. bidX cannot, however, guarantee that unauthorised third parties will never circumvent the measures taken by bidX and will not use your personal data for improper purposes.</p>
        <h3>6. Transfer of business</h3>
        <p>Should bidX grow and develop further (or for other reasons), one or more units or assets of bidX’s business may be transferred or outsourced to a third party, bidX may be acquired by a third party or bidX may merge with a third party. In that case, too, your personal data will be transferred.</p>
        <h3>7. Storage of your data</h3>
        <p>bidX will not save your personal data longer than necessary to accomplish the purposes for which the data has been compiled and processed.</p>
        <h3>8. Examination and correction of your data</h3>
        <p>If you wish to know what information bidX has collected about you, you can send bidX a request to receive an overview of your personal data by sending an email to info[at]bidx.net. bidX will provide you with the written information within four (4) weeks.</p>
        If the personal data bidX processes about you are inaccurate, incomplete or unnecessary for the purposes for which they were collected, you can request bidX to rectify, erase or block the data. bidX will respond to such a request within four (4) weeks.
        <h3>9. What is the extent of bidX’s responsibility?</h3>
        Third party content, including Member Content and Licensor Content, is used within the Platform. bidX has no control over the Member Content and/or Licensor Content. Third parties, including, other Members and Customers will furthermore collect and use your personal data. As described above, this Privacy Statement only pertains to the personal data collected, obtained and used by bidX. bidX does not accept any responsibility or liability whatsoever for the operation and/or contents of Member Content and/or Licensor Content.
        <h3>10. Can this Privacy Statement be changed?</h3>
        This Privacy Statement can be changed. These changes will be announced through the Platform
        <h3>11. Questions?</h3>
        <p>If you have any questions about this Privacy Statement, please send an email to info[at]bidx.net.</p>
    </div>
</div>
