<div class="row-fluid">
    <div class="span5 offset1 ">
        <h1>Registering as an investor in a bidX group</h1>
        <p class="clearfix">
            By following the steps below, you can register as investor in no time at all. Putting your investor profile and investment preference online will increase your chances of finding business opportunities. To complete your investor registration:
        </p>
        <ul class="unstyled">
            <li class="clearfix" style="margin-bottom: 20px;">
                <div>
                    <div class="title"><strong>Start with a few initial details</strong></div>
                    <div class="text">
                        Complete the form you can see on the right of this screen. Give your first and last name, your email address (you will use this later to log in), and tell us in which country you are located. Don't forget to accept the terms and conditions, and the privacy policy.
                    </div>
                </div>
            </li>
            <li class="clearfix" style="margin-bottom: 10px;">

                <div>
                    <div class="title"><strong>Your username and password</strong></div>
                    <div class="text">
                        Once you have created your investor profile, you will have access to your investor dashboard. Here you can find business plans recommended to you by bidX, as well as the list of plans you have chosen yourself. This dashboard will be expanding in future to include further new, interesting features.
                    </div>
                </div>
            </li>
            <li class="clearfix" style="margin-bottom: 10px;">
                <div>
                    <div class="title"><strong>Finalize registration</strong></div>
                    <div class="text">
                        Follow the screens with tips and help to complete both your personal and investor profile. You will be visible on this group in no time at all!
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="span5 bidx-well">[bidx app="register" hash="register" contenttitle="Register as investor"]</div>
</div>
