<div class="row">
    <div class="col-sm-5 col-sm-offset-1 ">
        <h1>Registering as an entrepreneur in a bidX group</h1>
        <p class="clearfix">
            By following the steps below, you can register as entrepreneur in no time at all. Putting your entrepreneur profile and business data online will increase your chances of being financed, finding other interesting businesses or getting advice from experts in your business. To complete your entrepreneur registration:
        </p>
        <dl>
            <hr>
            <dt>Start with a few initial details</dt>
            <dd>
                Complete the form you can see on the right of this screen. Give your first and last name, your email address (you will use this later to log in), and tell us in which country you are located. Don't forget to accept the terms and conditions, and the privacy policy
            </dd>
            <hr>
            <dt>Your username and password</dt>
            <dd>
                Once you have completed the first step, we will send you your password to the email address you gave us in the registration form. You will also find a link in that email. Click on this link and simply copy and paste the password in to the login screen. You can change this password later
            </dd>
            <hr>
            <dt>Finalize registration</dt>
            <dd>
                Follow the screens with tips and help to complete both your personal and entrepreneur profile and create you business summary. You will be visible on this group in no time at all!
            </dd>
        </dl>
    </div>
    <div class="col-sm-5 well">[bidx app="register" hash="register" contenttitle="Register as entrepreneur"]</div>
</div>
