<div class="row">
    <div class="col-sm-5 col-sm-offset-1 ">
        <h1>Registering as a member in a bidX group</h1>
        <p class="clearfix">
            By following the steps below, you can register as member in no time.
        </p>
        <dl>
            <hr>
            <dt>Start with a few initial details</dt>
            <dd>
                Complete the form you can see on the right of this screen. Give your first and last name, your email address (you will use this later to log in), and tell us in which country you are located. Don't forget to accept the terms and conditions, and the privacy policy.
            </dd>
            <hr>
            <dt>Your username and password</dt>
            <dd>
                Once you have completed the first step, we will send you your password to the email address you gave us in the registration form. You will also find a link in that email. Click on this link and simply copy and paste the password in to the login screen. You can change this password later in your account settings
            </dd>
            <hr>
            <dt>Finalize your registration</dt>
            <dd>
                Finally you are in! After your first login you will be able to complete your personal profile and continue your registration as entrepreneur or investor if you wished to do so.
            </dd>
        </dl>
    </div>
    <div class="col-sm-5 well">[bidx app="register" hash="register" contenttitle="Register as a member"]</div>
</div>
