<div class="row">
    <div class="col-sm-5 col-sm-offset-1 ">
        <h1>Registering as an mentor in a bidX group</h1>
        <p class="clearfix">
            THIS HAS BEEN COPIED FROM INVESTOR<br/>
            By following the steps below, you can register as investor in no time at all. Putting your investor profile and investment preference online will increase your chances of finding business opportunities. To complete your investor registration:
        </p>
        <dl>
            <hr>
            <dt>Start with a few initial details</dt>
            <dd>
                Complete the form you can see on the right of this screen. Give your first and last name, your email address (you will use this later to log in), and tell us in which country you are located. Don't forget to accept the terms and conditions, and the privacy policy.
            </dd>
            <hr>
            <dt>Your username and password</dt>
            <dd>
                Once you have created your investor profile, you will have access to your investor dashboard. Here you can find business plans recommended to you by bidX, as well as the list of plans you have chosen yourself. This dashboard will be expanding in future to include further new, interesting features.
            </dd>
            <hr>
            <dt>Finalize registration</dt>
            <dd>
                Follow the screens with tips and help to complete both your personal and investor profile. You will be visible on this group in no time at all!
            </dd>
        </dl>
    </div>
    <div class="col-sm-5 well">[bidx app="register" hash="register" contenttitle="Register as mentor"]</div>
</div>
