<div class="row-fluid">
    <div class="span7 ">
        <h1>Register as investor</h1>
        <p class="clearfix">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident, iste quos dolores impedit veritatis nesciunt minima voluptate. Ad, suscipit, sunt, ratione optio eligendi architecto ipsum velit pariatur nam recusandae tenetur.
        </p>
        <ul class="unstyled">
            <li class="clearfix" style="margin-bottom: 20px;">
                <div>
                    <div class="title"><strong>Creating your investor profile</strong></div>
                    <div class="text">Once you have completed and saved your information about you as an investor, you will be visible on the site as an investor. During the registration stage, you will be requested     to give information about your investment preferences to enable us to find the best matches for you.
                    </div>
                </div>
            </li>
            <li class="clearfix" style="margin-bottom: 10px;">

                <div>
                    <div class="title"><strong>Your investor dashboard</strong></div>
                    <div class="text">
                        Once you have created your investor profile, you will have access to your investor dashboard. Here you can find business plans recommended to you by bidX, as well as the list of plans you have chosen yourself. This dashboard will be expanding in future to include further new, interesting features.
                    </div>
                </div>
            </li>
            <li class="clearfix" style="margin-bottom: 10px;">
                <div>
                    <div class="title"><strong>Visibility of your profile</strong></div>
                    <div class="text">
                        Your investor profile will be visible and searchable by other members on this platform, however, they will not be able to email you or request to become your contact.
                    </div>
                </div>
            </li>
            <li class="clearfix" style="margin-bottom: 10px;">
                <div>
                    <div class="title"><strong>Join other groups in bidX</strong></div>
                    <div class="text">
                        We encourage you to visit and join other groups in the bidX platform. By joining more groups, you will increase the number of matching plans you receive, and the number of potentially interesting entrepreneurs you meet. You will not need to register again as an investor in order to join new groups.
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="span4 offset1 bidx-well">[bidx app="register" hash="register"]</div>
</div>