<?php

$businessSummary    = $this->data;
$progress           = trim ($this->exst($businessSummary->rating->Completeness)) . '%';

$businessSummaryBidxMeta = isset($businessSummary->bidxMeta)
    ? $businessSummary->bidxMeta
    : null;

$canEdit        = $this->exst($businessSummaryBidxMeta->bidxCanEdit, false);
$entityStatus   = $this->exst($businessSummaryBidxMeta->bidxEntityStatus, '');

// To display Company Tab
//
$companyId = $this->exst ($businessSummary->company);

// Default set of rowproperties
//
$viewRowProperties = array ('tag_label' => 'div', 'class_label' => 'bidx-label', 'class_value' => 'bidx-value', 'class_row' => '' );

?>
<div class="businessSummary" id="businessSummary">

    <div class="pageHeader container">
        <div class="row-fluid">
            <div class="span4">
                <h1>Business plan</h1>
                <p><?php echo $this->exst( $businessSummary->slogan ); ?></p>
            </div>

            <div class="span4 completion">
                <h2>Business completion</h2>
                <div class="progress">
                    <div style="width:<?php echo $progress ?>" class="bar"><?php echo $progress ?> completed</div>
                </div>
            </div>


            <div class="span4 editControlsContainer">
                <div class="editControls btn-group">

                    <!-- SHOW -->
                    <div class="view viewShow">

<?php
    if ( $canEdit ) {
?>
                        <a class="btn btn-primary" href="#editBusinessSummary/<?php echo $businessSummaryBidxMeta->bidxEntityId; ?>"><?php _e( 'Edit', 'bidxplugin' ); ?></a>
<?php
        if ( $entityStatus == 'DRAFT' ) {
?>
                        <a class="btn" href="#publish"><?php _e( 'Publish', 'bidxplugin' ); ?></a>
<?php
        }
    }
?>
                    </div>

                    <!-- EDIT -->
                    <div class="view viewEdit"></div>

                    <!-- ERROR -->
                    <div class="view viewError"></div>

                </div>
            </div>

        </div>
    </div><!-- /pageHeader -->

    <div class="container">

        <!-- Accordion -->
        <div class="accordion" id="businessSummaryAccordion">

            <!-- General Overview -->
            <div class="accordion-group accordion-open">
                <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#businessSummaryAccordion" href="#businessSummaryAccordion-GeneralOverview"><span class="fui-arrow-right accordion-state-icon"></span> <?php _e('General overview','bidxplugin'); ?></a>
                </div>
                <div id="businessSummaryAccordion-GeneralOverview" class="accordion-body collapse"><!-- @todo: put back 'in' class! -->
                    <div class="accordion-inner">

                        <div class="pull-right">
                            <a href="#businessSummaryAccordion-AboutTheBusiness" data-toggle="collapse" data-parent="#businessSummaryAccordion" class="btn">About the business <span class="fui-arrow-right"></span></a>
                        </div>

                        <!-- SHOW -->
                        <div class="view viewShow">
<?php
                $rowValues = array (
                    __('Business name','bidxplugin')
                        => $this->exst($businessSummary->name),

                    __('Describe your business in 15 words','bidxplugin')
                        => $this->exst($businessSummary->slogan),

                    __('Summary of this business','bidxplugin')
                        => $this->exst($businessSummary->summary),

                    __('Reason for submission of business summary','bidxplugin')
                        => $this->exst($businessSummary->reasonForSubmission),

                    __('Percentage equity you currently retain','bidxplugin')
                        => $this->exst($businessSummary->equityRetained),

                    __('Finance needed','bidxplugin')
                        => $this->exst($businessSummary->financingNeeded),

                    __('Investment type','bidxplugin')
                        => $this->getMultiValues( $this->exst($businessSummary->investmentType), ', ', 'investmentType' ),

                    __('Reason for financing','bidxplugin')
                        => $this->exst($businessSummary->summaryFinancingNeeded)
                );
                echo $this->addRowsWithLabelBelow('', '', $rowValues, $viewRowProperties );

                // @TODO: video
?>
                        </div>

                        <!-- LOAD -->
                        <div class="view viewLoad">
                            <span><?php _e('Retrieving business summary information...','bidxplugin'); ?></span>
                        </div>

                        <!-- ERROR -->
                        <div class="view viewError">
                            <p class="errorMsg"></p>
                        </div>

                        <!-- EDIT -->
                        <div class="view viewEdit">
                            <form id="frmBusinessSummary-GeneralOverview">

                                <!-- Name -->
                                <div class="control-group">
                                    <label class="control-label"><?php _e('Business name','bidxplugin'); ?></label>
                                    <div class="controls">
                                        <input type="text" name="name" placeholder="<?php _e('Business name','bidxplugin'); ?>">
                                    </div>
                                </div>

                                <!-- Slogan -->
                                <div class="control-group">
                                    <label class="control-label"><?php _e('Describe your business in 15 words ( optional )','bidxplugin'); ?></label>
                                    <div class="controls">
                                        <textarea type="text" name="slogan" placeholder="<?php _e('Please give a description of your business','bidxplugin'); ?>"></textarea>
                                    </div>
                                </div>

                                <!-- Summary -->
                                <div class="control-group">
                                    <label class="control-label"><?php _e('Summary of this business','bidxplugin'); ?></label>
                                    <div class="controls">
                                        <textarea type="text" name="summary" placeholder="<?php _e('Summary','bidxplugin'); ?>"></textarea>
                                    </div>
                                </div>

                                <!-- Reason For Submission -->
                                <div class="control-group">
                                    <label class="control-label"><?php _e('Reason for submission of business summary','bidxplugin'); ?></label>
                                    <div class="controls">
                                        <select name="reasonForSubmission">
                                            <option value=""><?php _e( 'Select an item', 'bidxplugin' ); ?></option>

<?php
                                        // Render the select based upon the items from the static data api for the 'reasonForSubmission' typeCode / groupCode / context
                                        //
                                        $typeCode = 'reasonForSubmission';
                                        if ( isset(BidxCommon::$i18nData['static'][$typeCode]) ) {
                                            foreach ( BidxCommon::$i18nData['static'][$typeCode] as $item ) {
                                                printf( '<option value="%s">%s</option>', $item->value, $item->label );
                                            }
                                        }
?>
                                        </select>
                                    </div>
                                </div>

                                <!-- Equity Retained -->
                                <div class="control-group">
                                    <label class="control-label"><?php _e('Percentage equity your currently retain ( optional )','bidxplugin'); ?></label>
                                    <div class="controls">
                                        <input type="text" name="equityRetained" placeholder="<?php _e('Percentage','bidxplugin'); ?>">
                                    </div>
                                </div>

                                <!-- Finance Needed -->
                                <div class="control-group">
                                    <label class="control-label"><?php _e('Finance needed','bidxplugin'); ?></label>
                                    <div class="controls">
                                        <input type="text" name="financingNeeded" placeholder="<?php _e('Please give finance needed','bidxplugin'); ?>">
                                    </div>
                                </div>

                                <!-- Investment type -->
                                <div class="control-group">
                                    <label class="control-label"><?php _e('Investment type','bidxplugin'); ?></label>
                                    <div class="controls">
<?php
                                        // Render the checkboxes based upon the items from the static data api for the 'investmentType' typeCode / groupCode / context
                                        //
                                        if ( isset(BidxCommon::$i18nData['static']['investmentType']) ) {
                                            foreach ( BidxCommon::$i18nData['static']['investmentType'] as $investmentType ) {
                                                printf( '<label class="checkbox inline"><input type="checkbox" value="%s" name="investmentType" data-toggle="checkbox" />%s</label>', $investmentType->value, $investmentType->label );
                                            }
                                        }
?>
                                    </div>
                                </div>

                                <!-- Summary Financing Needed -->
                                <div class="control-group">
                                    <label class="control-label"><?php _e('Why do you need financing? Describe in maximum 30 words ( optional )','bidxplugin'); ?></label>
                                    <div class="controls">
                                        <textarea name="summaryFinancingNeeded" placeholder="<?php _e('Please give the reason you need financing','bidxplugin'); ?>"></textarea>
                                    </div>
                                </div>
                            </form>
                        </div><!-- /EDIT -->

                    </div><!-- /Accordion-inner -->
                </div>
            </div><!-- /General Overview -->

            <!-- About the business -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#businessSummaryAccordion" href="#businessSummaryAccordion-AboutTheBusiness"><span class="fui-arrow-right accordion-state-icon"></span> <?php _e('About the business','bidxplugin'); ?></a>
                </div>
                <div id="businessSummaryAccordion-AboutTheBusiness" class="accordion-body collapse">
                    <div class="accordion-inner">

                        <div class="pull-right">
                            <a href="#businessSummaryAccordion-AboutYouAndYourTeam" data-toggle="collapse" data-parent="#businessSummaryAccordion" class="btn">About you &amp; your team <span class="fui-arrow-right"></span></a>
                        </div>

                        <!-- SHOW -->
                        <div class="view viewShow">
<?php
                $rowValues = array (

                    __('Industry','bidxplugin')
                        => $this->getMultiValues( $this->exst($businessSummary->industry), ', ', 'industry' ),

                    __('Suggested industry','bidxplugin')
                        => $this->getMultiValues( $this->exst($businessSummary->suggestedIndustry), ', ' ),

                    __('Product Service','bidxplugin')
                        => $this->getMultiValues( $this->exst($businessSummary->productService), ', ', 'productService' ),

                    __('Suggested product service','bidxplugin')
                        => $this->getMultiValues( $this->exst($businessSummary->suggestedProductService), ', ' ),

                    __('Country of business','bidxplugin')
                        => $this->getMultiValues( $this->exst($businessSummary->countryOperation), ', ', 'country' ),

                    __('Social impact','bidxplugin')
                        => $this->getMultiValues( $this->exst($businessSummary->socialImpact), ', ', 'socialImpact' ),

                    __('Environmental impact','bidxplugin')
                        => $this->getMultiValues( $this->exst($businessSummary->envImpact), ', ', 'envImpact' ),

                    __('Stage of business','bidxplugin')
                        => $this->getStaticVal( 'stageBusiness', $this->exst($businessSummary->stageBusiness)),

                    // This is likely a mismatch in labeling. The UI label is set to Customer Type but the object property is Consumer Type
                    // PM-163 for clarification
                    __('Customer type','bidxplugin')
                        => $this->getMultiValues( $this->exst($businessSummary->consumerType), ', ', 'consumerType' ),

                );
                echo $this->addRowsWithLabelBelow('', '', $rowValues, $viewRowProperties );
?>
                        </div>

                        <!-- LOAD -->
                        <div class="view viewLoad">
                            <span><?php _e('Retrieving business summary information...','bidxplugin'); ?></span>
                        </div>

                        <!-- ERROR -->
                        <div class="view viewError">
                            <p class="errorMsg"></p>
                        </div>

                        <!-- EDIT -->
                        <div class="view viewEdit">
                            <form id="frmBusinessSummary-AboutYourBusiness">

                                <!-- Industry -->
                                <div class="control-group">
                                    <label class="control-label"><?php _e('Industry','bidxplugin'); ?></label>
                                    <div class="controls">
                                        <div class="bidx-tagsinput-container">
                                            <input type="text" autocomplete="off" name="industry" class="bidx-tagsinput enclosed disabled" disabled data-bidxdatakey="industry" placeholder="<?php _e('Industry','bidxplugin'); ?>">
                                        </div>
                                    </div>
                                </div>

                                <!-- Suggested Industry -->
                                <div class="control-group">
                                    <label class="control-label"><?php _e('Suggested industry','bidxplugin'); ?></label>
                                    <div class="controls">
                                        <div class="bidx-tagsinput-container">
                                            <input type="text" autocomplete="off" name="suggestedIndustry" class="bidx-tagsinput enclosed" placeholder="<?php _e('Suggested industry','bidxplugin'); ?>">
                                        </div>
                                    </div>
                                </div>

                                <!-- Product Service -->
                                <div class="control-group">
                                    <label class="control-label"><?php _e('Product service','bidxplugin'); ?></label>
                                    <div class="controls">
                                        <div class="bidx-tagsinput-container">
                                            <input type="text" autocomplete="off" name="productService" class="bidx-tagsinput enclosed disabled" disabled data-bidxdatakey="productService" placeholder="<?php _e('Product service','bidxplugin'); ?>">
                                        </div>
                                    </div>
                                </div>

                                <!-- Suggested Product Service -->
                                <div class="control-group">
                                    <label class="control-label"><?php _e('Suggested product service','bidxplugin'); ?></label>
                                    <div class="controls">
                                        <div class="bidx-tagsinput-container">
                                            <input type="text" autocomplete="off" name="suggestedProductService" class="bidx-tagsinput enclosed" placeholder="<?php _e('Suggested industry','bidxplugin'); ?>">
                                        </div>
                                    </div>
                                </div>

                                <!-- Country operation -->
                                <div class="control-group">
                                    <label class="control-label"><?php _e('Country of business','bidxplugin'); ?></label>
                                    <div class="controls">
                                        <div class="bidx-tagsinput-container">
                                            <input type="text" autocomplete="off" name="countryOperation" class="bidx-tagsinput enclosed disabled" disabled data-bidxdatakey="country" placeholder="<?php _e('Country of business','bidxplugin'); ?>">
                                        </div>
                                    </div>
                                </div>

                                <!-- Social impact -->
                                <div class="control-group">
                                    <label class="control-label"><?php _e('Social impact','bidxplugin'); ?></label>
                                    <div class="controls">
                                        <select name="socialImpact">
                                            <option value=""><?php _e( 'Select an item', 'bidxplugin' ); ?></option>
<?php
                                        // Render the select options based upon the items from the static data api for the 'socialImpact' typeCode / groupCode / context
                                        //
                                        $typeCode = 'socialImpact';
                                        if ( isset(BidxCommon::$i18nData['static'][$typeCode]) ) {
                                            foreach ( BidxCommon::$i18nData['static'][$typeCode] as $item ) {
                                                printf( '<option value="%s">%s</option>', $item->value, $item->label );
                                            }
                                        }
?>
                                        </select>
                                    </div>
                                </div>

                                <!-- Env impact -->
                                <div class="control-group">
                                    <label class="control-label"><?php _e('Environmental impact','bidxplugin'); ?></label>
                                    <div class="controls">
                                        <select name="envImpact">
                                            <option value=""><?php _e( 'Select an item', 'bidxplugin' ); ?></option>
<?php
                                        // Render the select options based upon the items from the static data api for the 'envImpact' typeCode / groupCode / context
                                        //
                                        $typeCode = 'envImpact';
                                        if ( isset(BidxCommon::$i18nData['static'][$typeCode]) ) {
                                            foreach ( BidxCommon::$i18nData['static'][$typeCode] as $item ) {
                                                printf( '<option value="%s">%s</option>', $item->value, $item->label );
                                            }
                                        }
?>
                                        </select>
                                    </div>
                                </div>

                                <!-- Stage Business is read only -->

                                <!-- Consumer Type -->
                                <div class="control-group">
                                    <label class="control-label"><?php _e('Type of customer you sell to','bidxplugin'); ?></label>
                                    <div class="controls">
<?php
                                        // Render the checkboxes based upon the items from the static data api for the 'consumerType' typeCode / groupCode / context
                                        //
                                        $typeCode = 'consumerType';
                                        if ( isset(BidxCommon::$i18nData['static'][$typeCode]) ) {
                                            foreach ( BidxCommon::$i18nData['static'][$typeCode] as $item ) {
                                                printf( '<label class="checkbox inline"><input type="checkbox" value="%s" name="consumerType" data-toggle="checkbox" />%s</label>', $item->value, $item->label );
                                            }
                                        }
?>
                                    </div>
                                </div>
                            </form>
                        </div><!-- /EDIT -->

                        <div>
                            <a href="#businessSummaryAccordion-GeneralOverview" data-toggle="collapse" data-parent="#businessSummaryAccordion" class="btn"><span class="fui-arrow-left"></span> General Overview</a>
                        </div>

                    </div><!-- /accordion-inner -->
                </div>
            </div><!-- /About the business -->

            <!-- About you & your team -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#businessSummaryAccordion" href="#businessSummaryAccordion-AboutYouAndYourTeam"><span class="fui-arrow-right accordion-state-icon"></span> <?php _e('About you & your team','bidxplugin'); ?></a>
                </div>
                <div id="businessSummaryAccordion-AboutYouAndYourTeam" class="accordion-body collapse">
                    <div class="accordion-inner">

                        <div class="pull-right">
                            <a href="#businessSummaryAccordion-FinancialDetails" data-toggle="collapse" data-parent="#businessSummaryAccordion" class="btn">Financial Details <span class="fui-arrow-right"></span></a>
                        </div>

                        <!-- SHOW -->
                        <div class="view viewShow">
<?php
                            $rowValues = array (
                                __('Role of entrepreneur in this business','bidxplugin')
                                    => $this->exst($businessSummary->personalRole),

                                __('Expertise applicable to this business','bidxplugin')
                                    => $this->exst($businessSummary->personalExpertise)
                            );
                            echo $this->addRowsWithLabelBelow('', '', $rowValues, $viewRowProperties );

                            // Supporting members
                            //
                            $tableHeader = array (
                                __('Name','bidxplugin') => 'name',
                                __('Role of partner in this business','bidxplugin') => 'role',
                                __('Expertise of partner applicable','bidxplugin') => 'expertise'
                            );

                            $merge['name'] = array ('firstName', 'lastName');

                            $supportingMembersHtml = $this->addTableRows (
                                $tableHeader,
                                $this->exst( $businessSummary->managementTeam ),
                                'table table-bordered',
                                $merge
                            );

                            $rowValues = array (
                                __('Supporting members of management team','bidxplugin') => $supportingMembersHtml
                            );

                            echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'h5'));
?>
                        </div>

                        <!-- LOAD -->
                        <div class="view viewLoad">
                            <span><?php _e('Retrieving business summary information...','bidxplugin'); ?></span>
                        </div>

                        <!-- ERROR -->
                        <div class="view viewError">
                            <p class="errorMsg"></p>
                        </div>

                        <!-- EDIT -->
                        <div class="view viewEdit">
                            <form id="frmBusinessSummary-AboutYouAndYourTeam">

                                <!-- Personal Role -->
                                <div class="control-group formfield">
                                    <label class="control-label"><?php _e('Role of entrepreneur in this business (5 words)','bidxplugin'); ?></label>
                                    <div class="controls">
                                        <input type="text" name="personalRole" placeholder="<?php _e('Please give role of entrepreneur in this business','bidxplugin'); ?>">
                                    </div>
                                </div>

                                <!-- Personal Expertise -->
                                <div class="control-group">
                                    <label class="control-label"><?php _e('Please provide details of your expertise applicable to this business (30 words)','bidxplugin'); ?></label>
                                    <div class="controls">
                                        <textarea name="personalExpertise" placeholder="<?php _e('The details of your expertise for this business','bidxplugin'); ?>"></textarea>
                                    </div>
                                </div>

                                <div class="intermediate-row">
                                    <label><?php _e('Here you can give information about other members in your team.','bidxplugin'); ?></label>
                                    <a href="#addManagementTeam" class="btn btn-primary"><span class="fui-plus"></span><?php _e('Add','bidxplugin'); ?></a>
                                </div>

                                <div class="managementTeamContainer"></div>

                            </form>
                        </div><!-- /EDIT -->

                        <div>
                            <a href="#businessSummaryAccordion-AboutTheBusiness" data-toggle="collapse" data-parent="#businessSummaryAccordion" class="btn"><span class="fui-arrow-left"></span> About the business</a>
                        </div>

                    </div><!-- /Accordion inner -->
                </div>
            </div><!-- /About you & your team -->

            <!-- Financial details -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#businessSummaryAccordion" href="#businessSummaryAccordion-FinancialDetails"><span class="fui-arrow-right accordion-state-icon"></span> Financial Details</a>
                </div>
                <div id="businessSummaryAccordion-FinancialDetails" class="accordion-body collapse in">
                    <div class="accordion-inner">

                        <div class="pull-right">
                            <a href="#businessSummaryAccordion-CompanyDetails" data-toggle="collapse" data-parent="#businessSummaryAccordion" class="btn">Company details <span class="fui-arrow-right"></span></a>
                        </div>

                        <!-- SHOW -->
                        <div class="view viewShow">
<?php
                $numYearsSalesCosts = $this->exst($businessSummary->numYearsSalesCosts);
                $periodStartDate    = $this->exst($businessSummary->periodStartDate);

                // @TODO: what to do with $periodStartDate

                // Either set or interpret it as 0
                //
                if ( $numYearsSalesCosts || property_exists( $businessSummary, "numYearsSalesCosts" ))
                {
                    $yearSinceGeneratingSales = date( 'Y' ) + $numYearsSalesCosts;

                    $rowValues = array (
                        __('Business sales started in','bidxplugin') => $yearSinceGeneratingSales
                    );
                    echo $this->addRowsWithLabelBelow( '', '',  $rowValues, $viewRowProperties );
                }
?>
                        </div>

                        <!-- LOAD -->
                        <div class="view viewLoad">
                            <span><?php _e('Retrieving business summary information...','bidxplugin'); ?></span>
                        </div>

                        <!-- EDIT -->
                        <div class="view viewEdit">

                                <!-- numYear-->
                                <div class="control-group formfield">
                                    <label class="control-label"><?php _e('When did your business\'s sales start?','bidxplugin'); ?></label>
                                    <div class="controls">
                                        <select name="yearSinceGeneratingSales">
<?php
                                            $todayYear = date( 'Y' );
                                            $firstYear = $todayYear - 10;

                                            for ( $i = $firstYear; $i <= $todayYear; $i++ ) {
                                                printf( '<option value="%s">%s</option>', $i, $i );
                                            }
?>
                                        </select>
                                    </div>
                                </div>

                        </div>

                        <!-- VIEW and EDIT -->
                        <div class="view viewShow viewEdit">
<?php
    $this->render('financialsummary.phtml');
?>

                        </div><!-- /VIEW and EDIT -->

                        <!-- ERROR -->
                        <div class="view viewError">
                            <p class="errorMsg"></p>
                        </div>

                        <div>
                            <a href="#businessSummaryAccordion-AboutYouAndYourTeam" data-toggle="collapse" data-parent="#businessSummaryAccordion" class="btn"><span class="fui-arrow-left"></span> About you &amp; your team</a>
                        </div>

                    </div><!-- /Accordion-inner -->
                </div>
            </div><!-- /Financial details -->

            <!-- Company details -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#businessSummaryAccordion" href="#businessSummaryAccordion-CompanyDetails"><span class="fui-arrow-right accordion-state-icon"></span> Company Details</a>
                </div>
                <div id="businessSummaryAccordion-CompanyDetails" class="accordion-body collapse">
                    <div class="accordion-inner">

                        <div class="pull-right">
                            <a href="#businessSummaryAccordion-Documents" data-toggle="collapse" data-parent="#businessSummaryAccordion" class="btn">Documents <span class="fui-arrow-right"></span> </a>
                        </div>

                        <!-- SHOW -->
                        <div class="view viewShow">
                            show
                        </div>

                        <!-- LOAD -->
                        <div class="view viewLoad">
                            <span><?php _e('Retrieving business summary information...','bidxplugin'); ?></span>
                        </div>

                        <!-- ERROR -->
                        <div class="view viewError">
                            <p class="errorMsg"></p>
                        </div>

                        <!-- EDIT -->
                        <div class="view viewEdit">
                            edit
                        </div><!-- /Edit -->

                        <div>
                            <a href="#businessSummaryAccordion-FinancialDetails" data-toggle="collapse" data-parent="#businessSummaryAccordion" class="btn"><span class="fui-arrow-left"></span> Financial Details</a>
                        </div>

                    </div><!-- /Accordion inner -->
                </div>
            </div><!-- /Company details -->

            <!-- Documents -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#businessSummaryAccordion" href="#businessSummaryAccordion-Documents"><span class="fui-arrow-right accordion-state-icon"></span> Documents</a>
                </div>
                <div id="businessSummaryAccordion-Documents" class="accordion-body collapse">
                    <div class="accordion-inner">

                        <div class="pull-right">
                            <a href="#businessSummaryAccordion-GeneralOverview" data-toggle="collapse" data-parent="#businessSummaryAccordion" class="btn">General Overview <span class="fui-arrow-right"></span> </a>
                        </div>

                        <!-- SHOW -->
                        <div class="view viewShow">
                            show
                        </div>

                        <!-- LOAD -->
                        <div class="view viewLoad">
                            <span><?php _e('Retrieving business summary information...','bidxplugin'); ?></span>
                        </div>

                        <!-- ERROR -->
                        <div class="view viewError">
                            <p class="errorMsg"></p>
                        </div>

                        <!-- EDIT -->
                        <div class="view viewEdit">
                            edit
                        </div>

                        <div>
                            <a href="#businessSummaryAccordion-CompanyDetails" data-toggle="collapse" data-parent="#businessSummaryAccordion" class="btn"><span class="fui-arrow-left"></span> Company Details</a>
                        </div>

                    </div><!-- /Accordion-inner -->
                </div>

            </div><!-- /Documents -->

        </div><!-- /#businessSummaryAccordion -->

    </div><!-- /business summary content container -->

    <!-- SNIPPETS -->
    <div class="snippets hide">
        <div class="managementTeamItem span6 well well-white">

            <!-- First Name -->
            <div class="control-group">
                <label class="control-label"><?php _e('First name','bidxplugin'); ?></label>
                <div class="controls">
                    <input type="text" name="firstName" placeholder="<?php _e('Please type the first name','bidxplugin'); ?>">
                </div>
            </div>

            <!-- Last Name -->
            <div class="control-group">
                <label class="control-label"><?php _e('Last name','bidxplugin'); ?></label>
                <div class="controls">
                    <input type="text" name="lastName" placeholder="<?php _e('Please type the last name','bidxplugin'); ?>">
                </div>
            </div>

            <!-- Role -->
            <div class="control-group">
                <label class="control-label"><?php _e('Role of partner in this business','bidxplugin'); ?></label>
                <div class="controls">
                    <input type="text" name="role" placeholder="<?php _e('Please type the role of the partner','bidxplugin'); ?>">
                </div>
            </div>

            <!-- Expertise -->
            <div class="control-group">
                <label class="control-label"><?php _e('Expertise of partner applicable to business','bidxplugin'); ?></label>
                <div class="controls">
                    <textarea type="text" name="expertise" placeholder="<?php _e('Please give the expertise of partner applicable to business','bidxplugin'); ?>"></textarea>
                </div>
            </div>

            <a href="#removeItem" class="btn btn-danger btn-mini btn-block"><?php _e('Remove this partner','bidxplugin'); ?></a>
        </div>
    </div>

</div><!-- /businesssummary -->
