<?php

$businessSummary    = $this->data;
$progress           = trim ($this->exst($businessSummary->rating->Completeness)) . '%';

$businessSummaryBidxMeta = isset($businessSummary->bidxMeta)
    ? $businessSummary->bidxMeta
    : null;

$canEdit        = $this->exst($businessSummaryBidxMeta->bidxCanEdit, false);
$entityStatus   = $this->exst($businessSummaryBidxMeta->bidxEntityStatus, '');

$attachmentItem = <<<EOT
    <div class="span4 well well-white">
        <div class="row-fluid">
            <div class="span4">
                <a href="#" class="documentLink" target="_blank"><img class="img-rounded documentImage"></a>
            </div>
            <div class="span7">
                <h3 class="documentName">{{documentName}}</h3>
                <p class="purpose">{{purpose}}</p>
                <p class="documentType">{{documentType}}</p>
            </div>
        </div>
    </div>
EOT;

// The attachments item template exists of two types of variables, dynamic values and translations
//
$attachmentItemTranslations = array(
);

// To display Company Tab
//
$company    = $this->exst ($businessSummary->company);
$attachment = $this->exst ($businessSummary->attachment);

// Default set of rowproperties
//
$viewRowProperties = array ('tag_label' => 'label', 'tag_value' => 'div', 'class_label' => 'bidx-label', 'class_value' => 'bidx-value', 'class_row' => '' );


// Find the Download Financial templates URL
// TODO: Not the final version
//
$dlpage = get_page_by_title( 'Download financial templates' );
$dlurl = !empty( $dlpage ) ? $dlpage -> guid : false;

?>
<div class="businessSummary" id="businessSummary">

    <div class="pageHeader container">
        <div class="row-fluid">
            <div class="span4">
                <h1><?php _e('Business plan', 'bidxplugin')?></h1>
                <p><?php echo $this->exst( $businessSummary->slogan ); ?></p>
            </div>

            <div class="span4 completion">
                <h2><?php _e('Business completion', 'bidxplugin')?></h2>
                <div class="progress">
                    <div style="width:<?php echo $progress ?>" class="bar"><?php echo $progress ?> <?php _e('completed', 'bidxplugin')?></div>
                </div>
            </div>


            <div class="span4 editControlsContainer">
                <div class="editControls btn-group pull-right">

                    <!-- SHOW -->
                    <div class="view viewShow">

<?php
    if ( $canEdit ) {
?>
                        <a class="btn btn-primary" href="#editBusinessSummary/<?php echo $businessSummaryBidxMeta->bidxEntityId; ?>"><?php _e( 'Edit', 'bidxplugin' ); ?></a>
<?php
        if ( $entityStatus == 'DRAFT' ) {
?>
                        <a class="btn" href="#publish"><?php _e( 'Publish', 'bidxplugin' ); ?></a>
<?php
        }
    }
?>
                    </div>

                    <!-- EDIT, conditionally filled by the app -->
                    <div class="view viewEdit"></div>

                    <!-- ERROR, used as a placeholder for showing errors -->
                    <div class="view viewError"></div>

                </div>
            </div>

        </div>
    </div><!-- /pageHeader -->

    <div class="container">

        <!-- Accordion -->
        <div class="accordion" id="businessSummaryAccordion">

            <!-- General Overview -->
            <div class="accordion-group accordion-open">
                <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#businessSummaryAccordion" href="#businessSummaryAccordion-GeneralOverview"><span class="fui-arrow-right accordion-state-icon"></span> <?php _e('General overview','bidxplugin'); ?></a>
                </div>
                <div id="businessSummaryAccordion-GeneralOverview" class="accordion-body collapse in" style="overflow: visible;">
                    <div class="accordion-inner clearfix">

                        <!-- SHOW -->
                        <div class="view viewShow">

<?php
                $rowValues = array (
                    __('Business name','bidxplugin')
                        => $this->exst($businessSummary->name),

                    __('Describe your business (max. 140 characters) ','bidxplugin')
                        => $this->exst($businessSummary->slogan),

                    __('Summary of this business','bidxplugin')
                        => $this->exst($businessSummary->summary),

                    __('Reason for submission of business summary','bidxplugin')
                        => $this->exst($businessSummary->reasonForSubmission),

                    __('Percentage equity you currently retain','bidxplugin')
                        => $this->exst($businessSummary->equityRetained),

                    __('Finance needed','bidxplugin')
                        => $this->exst($businessSummary->financingNeeded),

                    __('Investment type','bidxplugin')
                        => $this->getMultiValues( $this->exst($businessSummary->investmentType), ', ', 'investmentType' ),

                    __('Reason for financing','bidxplugin')
                        => $this->exst($businessSummary->summaryFinancingNeeded)
                );
                echo $this->pairRows( $rowValues );

                // @TODO: video
?>
                        </div>

                        <!-- LOAD -->
                        <div class="view viewLoad">
                            <span><?php _e('Retrieving business summary information...','bidxplugin'); ?></span>
                        </div>

                        <!-- ERROR -->
                        <div class="view viewError">
                            <p class="errorMsg"></p>
                        </div>

                        <!-- EDIT -->
                        <div class="view viewEdit">
                            <div class="alert alert-info">
                                <?php _e('This section gives your the opportunity to describe your business. Think about what information you would like other people to know if you only had a few minutes to explain.','bidxplugin')?>
                            </div>
                            <form id="frmBusinessSummary-GeneralOverview">
                                <div class="row-fluid">
                                    <!-- Name -->
                                    <div class="control-group span5">
                                        <label class="control-label"><?php _e('Business name','bidxplugin'); ?></label>
                                        <div class="controls">
                                            <input type="text" name="name" placeholder="<?php _e('Business name','bidxplugin'); ?>">
                                        </div>
                                    </div>

                                    <!-- Slogan -->
                                    <div class="control-group span5 offset1">
                                        <label class="control-label"><?php _e('Describe your business (max. 140 characters) optional','bidxplugin'); ?></label>
                                        <div class="controls">
                                            <textarea type="text" name="slogan" placeholder="<?php _e('Please give a description of your business','bidxplugin'); ?>"></textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="row-fluid">
                                    <!-- Summary -->
                                    <div class="control-group span5">
                                        <label class="control-label"><?php _e('Summary of this business','bidxplugin'); ?></label>
                                        <div class="controls">
                                            <textarea type="text" name="summary" placeholder="<?php _e('Summary','bidxplugin'); ?>"></textarea>
                                        </div>
                                    </div>

                                    <!-- Reason For Submission -->
                                    <div class="control-group span5 offset1">
                                        <label class="control-label"><?php _e('Reason for submission of business summary','bidxplugin'); ?></label>
                                        <div class="controls">
                                            <select name="reasonForSubmission" data-forcearray="true">
                                                <option value=""><?php _e( 'Select an item', 'bidxplugin' ); ?></option>

    <?php
                                            // Render the select based upon the items from the static data api for the 'reasonForSubmission' typeCode / groupCode / context
                                            //
                                            $typeCode = 'reasonForSubmission';
                                            if ( isset(BidxCommon::$i18nData['static'][$typeCode]) ) {
                                                foreach ( BidxCommon::$i18nData['static'][$typeCode] as $item ) {
                                                    printf( '<option value="%s">%s</option>', $item->value, $item->label );
                                                }
                                            }
    ?>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="row-fluid">
                                <!-- Equity Retained -->
                                    <div class="control-group span5">
                                        <label class="control-label"><?php _e('Percentage equity your currently retain','bidxplugin'); ?></label>
                                        <div class="controls input-append">
                                            <input type="text" name="equityRetained" placeholder="<?php _e('Percentage','bidxplugin'); ?>">
                                            <span class="add-on">%</span>
                                        </div>
                                    </div>

                                    <!-- Finance Needed -->
                                    <div class="control-group span5 offset1">
                                        <label class="control-label"><?php _e('Finance needed','bidxplugin'); ?></label>
                                        <div class="controls">
                                            <input type="text" name="financingNeeded" placeholder="<?php _e('Please enter amount of finance needed','bidxplugin'); ?>">
                                        </div>
                                    </div>
                                </div>
                                <div class="row-fluid">
                                    <!-- Investment type -->
                                    <div class="control-group span5">
                                        <label class="control-label"><?php _e('Investment type','bidxplugin'); ?></label>
                                        <div class="controls">
<?php
                                            // Render the checkboxes based upon the items from the static data api for the 'investmentType' typeCode / groupCode / context
                                            //
                                            if ( isset(BidxCommon::$i18nData['static']['investmentType']) ) {
                                                foreach ( BidxCommon::$i18nData['static']['investmentType'] as $investmentType ) {
                                                    printf( '<label class="checkbox inline"><input type="checkbox" value="%s" name="investmentType[]" data-toggle="checkbox" />%s</label>', $investmentType->value, $investmentType->label );
                                                }
                                            }
?>
                                        </div>
                                    </div>

                                    <!-- Summary Financing Needed -->
                                    <div class="control-group span5 offset1">
                                        <label class="control-label"><?php _e('Why does your business need financing? (max. 300 characters)','bidxplugin'); ?></label>
                                        <div class="controls">
                                            <textarea name="summaryFinancingNeeded" placeholder="<?php _e('Please give the reason your business needs financing','bidxplugin'); ?>"></textarea>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div><!-- /EDIT -->
                        <div class="accordion-controls-bottom">
                            <a href="#businessSummaryAccordion-AboutTheBusiness" data-toggle="collapse" data-parent="#businessSummaryAccordion" class="btn pull-right"><?php _e('About the business','bidxplugin')?> <span class="fui-arrow-right"></span></a>
                        </div>

                    </div><!-- /Accordion-inner -->
                </div>
            </div><!-- /General Overview -->

            <!-- About the business -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#businessSummaryAccordion" href="#businessSummaryAccordion-AboutTheBusiness"><span class="fui-arrow-right accordion-state-icon"></span> <?php _e('About the business','bidxplugin'); ?></a>
                </div>
                <div id="businessSummaryAccordion-AboutTheBusiness" class="accordion-body collapse">
                    <div class="accordion-inner clearfix">

                        <!-- SHOW -->
                        <div class="view viewShow">
<?php
                $rowValues = array (

                    __('Industry','bidxplugin')
                        => $this->getMultiValues( $this->exst($businessSummary->industry), ', ', 'industry' ),

                    __('Suggested industry','bidxplugin')
                        => $this->getMultiValues( $this->exst($businessSummary->suggestedIndustry), ', ' ),

                    __('Product / Service','bidxplugin')
                        => $this->getMultiValues( $this->exst($businessSummary->productService), ', ', 'productService' ),

                    __('Suggested product service','bidxplugin')
                        => $this->getMultiValues( $this->exst($businessSummary->suggestedProductService), ', ' ),

                    __('Country of business','bidxplugin')
                        => $this->getMultiValues( $this->exst($businessSummary->countryOperation), ', ', 'country' ),

                    __('Social impact','bidxplugin')
                        => $this->getMultiValues( $this->exst($businessSummary->socialImpact), ', ', 'socialImpact' ),

                    __('Environmental impact','bidxplugin')
                        => $this->getMultiValues( $this->exst($businessSummary->envImpact), ', ', 'envImpact' ),

                    __('Stage of business','bidxplugin')
                        => $this->getStaticVal( 'stageBusiness', $this->exst($businessSummary->stageBusiness)),

                    // This is likely a mismatch in labeling. The UI label is set to Customer Type but the object property is Consumer Type
                    // PM-163 for clarification
                    __('Customer type','bidxplugin')
                        => $this->getMultiValues( $this->exst($businessSummary->consumerType), ', ', 'consumerType' )

                );
                echo $this->pairRows( $rowValues );
?>
                        </div>

                        <!-- LOAD -->
                        <div class="view viewLoad">
                            <span><?php _e('Retrieving business summary information...','bidxplugin'); ?></span>
                        </div>

                        <!-- ERROR -->
                        <div class="view viewError">
                            <p class="errorMsg"></p>
                        </div>

                        <!-- EDIT -->
                        <div class="view viewEdit">
                            <div class="alert alert-info">
                                <?php _e('Here we have provided you with tools for you to provide more precise information about your business; what industry it operates in, what it produces and where it operates. This information will be used to match your initiative with other businesses, and investors.','bidxplugin')?>
                            </div>
                            <form id="frmBusinessSummary-AboutYourBusiness">

                                <div class="row-fluid">
                                    <!-- Industry -->
                                    <div class="control-group span5">
                                        <label class="control-label"><?php _e('Industry','bidxplugin'); ?></label>
                                        <select name="industry" multiple></select>
                                    </div>

                                    <!-- Suggested Industry -->
                                    <div class="control-group span5 offset1">
                                        <label class="control-label"><?php _e('Suggested industry','bidxplugin'); ?></label>
                                        <div class="controls">
                                            <div class="bidx-tagsinput-container">
                                                <input type="text" autocomplete="off" name="suggestedIndustry" class="bidx-tagsinput enclosed" placeholder="<?php _e('Suggested industry','bidxplugin'); ?>">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row-fluid">
                                    <!-- Product Service -->
                                    <div class="control-group span5">
                                        <label class="control-label"><?php _e('Product / service','bidxplugin'); ?></label>
                                        <select name="productService" multiple></select>
                                    </div>

                                    <!-- Suggested Product Service -->
                                    <div class="control-group span5 offset1">
                                        <label class="control-label"><?php _e('Suggested product / service','bidxplugin'); ?></label>
                                        <div class="controls">
                                            <div class="bidx-tagsinput-container">
                                                <input type="text" autocomplete="off" name="suggestedProductService" class="bidx-tagsinput enclosed" placeholder="<?php _e('Suggested product / service','bidxplugin'); ?>">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row-fluid">
                                    <!-- Country operation -->
                                    <div class="control-group span5">
                                        <label class="control-label"><?php _e('Country of business','bidxplugin'); ?></label>
                                        <select name="countryOperation" multiple></select>
                                    </div>

                                    <!-- Social impact -->
                                    <div class="control-group span5 offset1">
                                        <label class="control-label"><?php _e('Social impact','bidxplugin'); ?></label>
                                        <div class="controls">
                                            <select name="socialImpact">
                                                <option value=""><?php _e( 'Select an item', 'bidxplugin' ); ?></option>
<?php
                                            // Render the select options based upon the items from the static data api for the 'socialImpact' typeCode / groupCode / context
                                            //
                                            $typeCode = 'socialImpact';
                                            if ( isset(BidxCommon::$i18nData['static'][$typeCode]) ) {
                                                foreach ( BidxCommon::$i18nData['static'][$typeCode] as $item ) {
                                                    printf( '<option value="%s">%s</option>', $item->value, $item->label );
                                                }
                                            }
?>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="row-fluid">
                                    <!-- Env impact -->
                                    <div class="control-group span5">
                                        <label class="control-label"><?php _e('Environmental impact','bidxplugin'); ?></label>
                                        <div class="controls">
                                            <select name="envImpact">
                                                <option value=""><?php _e( 'Select an item', 'bidxplugin' ); ?></option>
<?php
                                            // Render the select options based upon the items from the static data api for the 'envImpact' typeCode / groupCode / context
                                            //
                                            $typeCode = 'envImpact';
                                            if ( isset(BidxCommon::$i18nData['static'][$typeCode]) ) {
                                                foreach ( BidxCommon::$i18nData['static'][$typeCode] as $item ) {
                                                    printf( '<option value="%s">%s</option>', $item->value, $item->label );
                                                }
                                            }
?>
                                            </select>
                                        </div>
                                    </div>

                                    <!-- Stage Business is read only -->

                                    <!-- Consumer Type -->
                                    <div class="control-group span5 offset1">
                                        <label class="control-label"><?php _e('Type of customer you sell to','bidxplugin'); ?></label>
                                        <div class="controls">
<?php
                                            // Render the checkboxes based upon the items from the static data api for the 'consumerType' typeCode / groupCode / context
                                            //
                                            $typeCode = 'consumerType';
                                            if ( isset(BidxCommon::$i18nData['static'][$typeCode]) ) {
                                                foreach ( BidxCommon::$i18nData['static'][$typeCode] as $item ) {
                                                    printf( '<label class="checkbox inline"><input type="checkbox" value="%s" name="consumerType[]" data-toggle="checkbox" />%s</label>', $item->value, $item->label );
                                                }
                                            }
?>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div><!-- /EDIT -->


                        <div class="accordion-controls-bottom">
                            <a href="#businessSummaryAccordion-GeneralOverview" data-toggle="collapse" data-parent="#businessSummaryAccordion" class="btn"><span class="fui-arrow-left"></span> <?php _e('General Overview', 'bidxplugin')?></a>
                            <a href="#businessSummaryAccordion-AboutYouAndYourTeam" data-toggle="collapse" data-parent="#businessSummaryAccordion" class="btn pull-right"><?php _e('About you &amp; your team', 'bidxplugin')?> <span class="fui-arrow-right"></span></a>
                        </div>

                    </div><!-- /accordion-inner -->
                </div>
            </div><!-- /About the business -->

            <!-- About you & your team -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#businessSummaryAccordion" href="#businessSummaryAccordion-AboutYouAndYourTeam"><span class="fui-arrow-right accordion-state-icon"></span> <?php _e('About you & your team','bidxplugin'); ?></a>
                </div>
                <div id="businessSummaryAccordion-AboutYouAndYourTeam" class="accordion-body collapse">
                    <div class="accordion-inner clearfix">

                        <!-- SHOW -->
                        <div class="view viewShow">
<?php
                            $rowValues = array (
                                __('Role of entrepreneur in this business','bidxplugin')
                                    => $this->exst($businessSummary->personalRole),

                                __('Expertise applicable to this business','bidxplugin')
                                    => $this->exst($businessSummary->personalExpertise)
                            );
                            echo $this->pairRows( $rowValues );

                            // Supporting members
                            //
                            $tableHeader = array (
                                ''                                                                      => 'profilePicture',
                                __('Name','bidxplugin')                                                 => 'name',
                                __('Role of partner in this business','bidxplugin')                     => 'role',
                                __('Describe relevant expertise of business partner','bidxplugin')      => 'expertise',
                                'LinkedIn'                                                              => 'linkedIn'
                            );

                            $merge['name'] = array ('firstName', 'lastName');

                            $supportingMembersHtml = $this->addTableRows(
                                $tableHeader,
                                $this->exst( $businessSummary->managementTeam ),
                                'table table-bordered',
                                $merge,
                                array( 'profilePicture' => 'bidx-profilepicture' )
                            );

                            $rowValues = array (
                                __('Supporting members of management team','bidxplugin') => $supportingMembersHtml
                            );

                            echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'h5'));
?>
                        </div>

                        <!-- LOAD -->
                        <div class="view viewLoad">
                            <span><?php _e('Retrieving business summary information...','bidxplugin'); ?></span>
                        </div>

                        <!-- ERROR -->
                        <div class="view viewError">
                            <p class="errorMsg"></p>
                        </div>

                        <!-- EDIT -->
                        <div class="view viewEdit">
                            <div class="alert alert-info">
                                <?php _e('Your team is an essential part of the success of your business. Give more information here about you as part of this team, and about the other team members.', 'bidxplugin')?>
                            </div>
                            <form id="frmBusinessSummary-AboutYouAndYourTeam">
                                <div class="row-fluid">
                                    <!-- Personal Role -->
                                    <div class="control-group formfield span5">
                                        <label class="control-label"><?php _e('Role of entrepreneur in this business (max. 30 characters)','bidxplugin'); ?></label>
                                        <div class="controls">
                                            <input type="text" name="personalRole" placeholder="<?php _e('Please give role of entrepreneur in this business','bidxplugin'); ?>">
                                        </div>
                                    </div>

                                    <!-- Personal Expertise -->
                                    <div class="control-group span5 offset1">
                                        <label class="control-label"><?php _e('Please describe your expertise in relation to this business (180 characters)','bidxplugin'); ?></label>
                                        <div class="controls">
                                            <textarea name="personalExpertise" placeholder="<?php _e('The details of your expertise for this business','bidxplugin'); ?>"></textarea>
                                        </div>
                                    </div>
                                </div>

                                <div class="control-group span11">
                                    <label><?php _e('Here you can give information about other members in your team.','bidxplugin'); ?></label>
                                    <a href="#addManagementTeam" class="btn btn-primary"><span class="fui-plus"></span><?php _e('Add','bidxplugin'); ?></a>
                                </div>

                                <div class="managementTeamContainer"></div>

                                <div class="managementTeamProfilePictureModal modal hide fade">
                                  <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                    <h3><?php _e('Check the file you want to use as the picture for this member', 'bidxplugin' ); ?></h3>
                                  </div>
                                    <div class="modal-body">
    <?php
                                        echo do_shortcode( '[bidx app="media"]' );
    ?>
                                    </div>
                                    <div class="modal-footer">
                                        <a href="#" class="btn btn-primary btnSelectFile"><?php _e( 'Select file(s)', 'bidxplugin' ); ?></a>
                                        <a href="#" class="btn btnCancelSelectFile"><?php _e( 'Cancel', 'bidxplugin' ); ?></a>
                                    </div>
                                </div>

                            </form>
                        </div><!-- /EDIT -->

                        <div class="accordion-controls-bottom">
                            <a href="#businessSummaryAccordion-AboutTheBusiness" data-toggle="collapse" data-parent="#businessSummaryAccordion" class="btn"><span class="fui-arrow-left"></span> <?php _e('About the business', 'bidxplugin')?></a>
                            <a href="#businessSummaryAccordion-FinancialDetails" data-toggle="collapse" data-parent="#businessSummaryAccordion" class="btn pull-right"><?php _e('Financial Details', 'bidxplugin')?> <span class="fui-arrow-right"></span></a>
                        </div>

                    </div><!-- /Accordion inner -->
                </div>
            </div><!-- /About you & your team -->

            <!-- Financial details -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#businessSummaryAccordion" href="#businessSummaryAccordion-FinancialDetails"><span class="fui-arrow-right accordion-state-icon"></span> <?php _e('Financial Details', 'bidxplugin')?></a>
                </div>
                <div id="businessSummaryAccordion-FinancialDetails" class="accordion-body collapse">
                    <div class="accordion-inner clearfix">

                        <form id="frmBusinessSummary-FinancialDetails">

                            <!-- SHOW -->
                            <div class="view viewShow">
<?php
                $rowValues = array (
                    __('Business sales started in','bidxplugin') => $this->exst($businessSummary->yearSalesStarted)
                );
                echo $this->addRowsWithLabelBelow( '', '',  $rowValues, $viewRowProperties );
?>
                            </div>

                            <!-- LOAD -->
                            <div class="view viewLoad">
                                <span><?php _e('Retrieving business summary information...','bidxplugin'); ?></span>
                            </div>

                            <!-- EDIT -->
                            <div class="view viewEdit">
                                <div class="alert alert-info">
                                <?php _e('Here you should provide a very general overview of your finances, the financing you need, the number of employees you have currently and how you think your business has, and will continue to grow over time','bidxplugin')?>

                                </div>
                                <!-- numYear-->

<?php
?>

                                <!-- If there is no financial plan uploaded -->
                                <a class="btn btn-primary" href=""><?php _e('Upload your financial plan', 'bidxplugin'); ?></a>

<?php
                                if ( $dlurl !== false) :
?>
                                    <a  class="btn btn-link" href="<?php echo $dlurl; ?>"><?php _e('Or download a financial plan template.', 'bidxplugin'); ?>&nbsp;<span class="icon-download text-info"></span></a>
<?php
                                endif;
?>


                                <hr>
                                <div class="row-fluid">
                                    <div class="control-group formfield span5">
                                        <label class="control-label"><?php _e('When did your business\'s sales start?','bidxplugin'); ?></label>
                                        <div class="controls">
                                            <select name="yearSalesStarted">
                                                <option value=""><?php _e('Select year', 'bidxplugin');?></option>
<?php
                                                $todayYear = date( 'Y' );
                                                $firstYear = $todayYear - 10;

                                                for ( $i = $firstYear; $i <= $todayYear; $i++ ) {
                                                    printf( '<option value="%s">%s</option>', $i, $i );
                                                }
?>
                                            </select>
                                        </div>
                                    </div>
                                </div>

                            </div>

                            <!-- VIEW and EDIT -->
                            <div class="view viewShow viewEdit">
<?php
    $this->render('financialsummary.phtml');
?>
                            </div><!-- /VIEW and EDIT -->

                            <!-- ERROR -->
                            <div class="view viewError">
                                <p class="errorMsg"></p>
                            </div>

                            <div class="accordion-controls-bottom">
                                <a href="#businessSummaryAccordion-AboutYouAndYourTeam" data-toggle="collapse" data-parent="#businessSummaryAccordion" class="btn"><span class="fui-arrow-left"></span> <?php _e('About you &amp; your team', 'bidxplugin')?></a>
                                <a href="#businessSummaryAccordion-CompanyDetails" data-toggle="collapse" data-parent="#businessSummaryAccordion" class="btn pull-right"><?php _e('Company details', 'bidxplugin')?> <span class="fui-arrow-right"></span></a>
                            </div>
                        </form>
                    </div><!-- /Accordion-inner -->
                </div>
            </div><!-- /Financial details -->

            <!-- Company details -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#businessSummaryAccordion" href="#businessSummaryAccordion-CompanyDetails"><span class="fui-arrow-right accordion-state-icon"></span> <?php _e('Company Details', 'bidxplugin')?></a>
                </div>
                <div id="businessSummaryAccordion-CompanyDetails" class="accordion-body collapse">
                    <div class="accordion-inner clearfix">


                        <!-- SHOW -->
                        <div class="view viewShow">
<?php
                            // Is there a company object?
                            //
                            if ( !$this->exst( $company )) {

                                _e( 'This business summary doesn\'t have a company', 'bidxplugin' );

                            } else {

                                $companyWebsite = null;

                                if ( $this->exst( $company->website ) ) {
                                    $companyWebsite = sprintf( '<a href="%1$s" target="_blank">%1$s</a>', $this->exst($company->website) );
                                }

                                $rowValues = array (
                                    __('Company name','bidxplugin')
                                        => $this->exst($company->name),

                                    __('Company website','bidxplugin')
                                        => $companyWebsite,

                                    __('Registered','bidxplugin')
                                        => $this->exst($company->registered) == true ? __('Yes','bidxplugin') : __('No','bidxplugin'),

                                    __('Legal form','bidxplugin')
                                        => $this->getStaticVal( 'legalForm', $this->exst($company->legalFormBusiness) ),

                                    __('Registration number','bidxplugin')
                                        => $this->exst($company->registrationNumber),

                                    __('Fiscal number','bidxplugin')
                                        => $this->exst($company->fiscalNumber),

                                    __('Date company established','bidxplugin')
                                        => $this->exst($company->dateCompanyEstab),

                                    __('Number permanent male employees','bidxplugin')
                                        => $this->exst($company->numPermMaleEmp ),

                                    __('Number permanent female employees','bidxplugin')
                                        => $this->exst($company->numPermFemaleEmp ),

                                    __('Number temporary male employees','bidxplugin')
                                        => $this->exst($company->numTempMaleEmp ),

                                    __('Number temporary female employees','bidxplugin')
                                        => $this->exst($company->numTempFemaleEmp ),

                                    __('Street','bidxplugin')
                                        => $this->exst($company->statutoryAddress->street),

                                    __('Street number','bidxplugin')
                                        => $this->exst($company->statutoryAddress->streetNumber),

                                    __('Neighborhood','bidxplugin')
                                        => $this->exst($company->statutoryAddress->neighborhood),

                                    __('Postalcode','bidxplugin')
                                        => $this->exst($company->statutoryAddress->postalCode),

                                    __('Postbox','bidxplugin')
                                        => $this->exst($company->statutoryAddress->postBox),

                                    __('City','bidxplugin')
                                        => $this->exst($company->statutoryAddress->cityTown),

                                    __('Country','bidxplugin')
                                        => $this->getStaticVal( 'country', $this->exst($company->statutoryAddress->country) )
                                );
                                echo $this->pairRows( $rowValues );
                            }
?>
                        </div>

                        <!-- LOAD -->
                        <div class="view viewLoad">
                            <span><?php _e('Retrieving business summary information...','bidxplugin'); ?></span>
                        </div>

                        <!-- ERROR -->
                        <div class="view viewError">
                            <p class="errorMsg"></p>
                        </div>

                        <!-- EDIT -->
                        <div class="view viewEdit">
                            <div class="alert alert-info">
                                <?php _e('In this section you can link your business to an existing company. If you do not yet have a company, you can skip this step by answering \'No\' to the first question. If you already created a company in the past, you can select it from the list', 'bidxplugin')?>
                            </div>

                            <form id="frmBusinessSummary-CompanyDetails">

                                <!-- Has Company? -->
                                <div class="control-group">
                                    <label class="control-label"><?php _e('Does this business summary have a company?','bidxplugin'); ?></label>
                                    <div class="controls">
                                        <label class="radio inline"><input type="radio" value="true"  name="hasCompany" data-toggle="radio"/> <?php _e('Yes','bidxplugin'); ?></label>
                                        <label class="radio inline"><input type="radio" value="false" name="hasCompany" data-toggle="radio"/> <?php _e('No','bidxplugin'); ?></label>
                                    </div>
                                </div>

                                <!-- Does have a company -->
                                <div class="doesHaveCompany">
                                    <h2><?php _e('Select your company from the list below','bidxplugin'); ?></h2>
                                    <table class="table table-striped">
                                        <thead>
                                            <tr>
                                                <th></th>
                                                <th><?php _e('Company name','bidxplugin'); ?></th>
                                                <th><?php _e('Registered','bidxplugin'); ?></th>
                                                <th><?php _e('Employees','bidxplugin'); ?></th>
                                                <th><?php _e('Location','bidxplugin'); ?></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <!-- going into edit will populate this list with the response of the current company list of a member -->
                                        </tbody>
                                    </table>

                                    <a href="#addNewCompany" class="btn"><?php _e('Or add a new company', 'bidxplugin')?></a>
                                </div>
                            </form>

                            <div class="addNewCompany">
<?php
                                echo do_shortcode( '[bidx app="company" noheader="true"]' );
?>
                                <a href="#addCompany" class="btn btn-primary"><?php _e('Save to list', 'bidxplugin')?></a>
                                <a href="#cancelAddCompany" class="btn"><?php _e('Cancel', 'bidxplugin')?></a>
                            </div>
                        </div><!-- /Edit -->
                        <div class="accordion-controls-bottom">
                            <a href="#businessSummaryAccordion-FinancialDetails" data-toggle="collapse" data-parent="#businessSummaryAccordion" class="btn"><span class="fui-arrow-left"></span> <?php _e('Financial Details', 'bidxplugin')?></a>
                            <a href="#businessSummaryAccordion-Documents" data-toggle="collapse" data-parent="#businessSummaryAccordion" class="btn pull-right"><?php _e('Documents', 'bidxplugin')?> <span class="fui-arrow-right"></span> </a>
                        </div>

                    </div><!-- /Accordion inner -->
                </div>
            </div><!-- /Company details -->

            <!-- Documents -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#businessSummaryAccordion" href="#businessSummaryAccordion-Documents"><span class="fui-arrow-right accordion-state-icon"></span> <?php _e('Documents', 'bidxplugin')?></a>
                </div>
                <div id="businessSummaryAccordion-Documents" class="accordion-body collapse">
                    <div class="accordion-inner clearfix">

                        <!-- SHOW -->
                        <div class="view viewShow">
<?php
                if ( !is_null( $attachment ) ) {
                    $count = 0;

                    foreach ( $attachment as $a ) {

                        // 3 attachments items per row, are we full? Add a new row
                        //
                        if ( $count % 3 == 0  ) {

                            if ( $count != 0 ) {
                                echo "</div>";
                            }

                            echo '<div class="row-fluid reflow-row">';
                        }

                        // Echo the attachment item with the values from the API
                        //
                        echo $this->replaceMessageTokens(
                            $attachmentItem,
                            array_merge(
                                $attachmentItemTranslations,
                                array(
                                    '{{documentName}}'          => $this->exst( $a->documentName ),
                                    '{{purpose}}'               => $this->exst( $a->purpose ),
                                    '{{documentType}}'          => $this->getStaticVal( 'documenType', $this->exst( $a->dcoumentType ))
                                )
                            )
                        );

                        $count++;
                    }

                    // Closing the last row, this will always be the case since we wouldn't be here unless there was at least
                    // one attachment
                    //
                    echo "</div>";
                } else {
?>
                <div class="alert alert-danger">
                    <?php _e('This business summary doesn\'t have any Documents attached!', 'bidxplugin')?>
                </div>
<?php
                }
?>
                        </div>

                        <!-- LOAD -->
                        <div class="view viewLoad">
                            <span><?php _e('Retrieving business summary information...','bidxplugin'); ?></span>
                        </div>

                        <!-- ERROR -->
                        <div class="view viewError">
                            <p class="errorMsg"></p>
                        </div>

                        <!-- EDIT -->
                        <div class="view viewEdit">

                            <div class="attachmentContainer"></div>

                            <div class="alert alert-info">
                                <?php _e('Upload your full plans or other supporting documents or images here','bidxplugin');?>
                            </div>

                            <a href="#addFiles" data-toggle="modal" class="btn btn-primary"><?php _e('Add files', 'bidxplugin')?></a>

                            <div class="addFiles modal hide fade">
                              <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                <h3><?php _e('Check the files you want to attach to your business plan', 'bidxplugin' ); ?></h3>
                              </div>
                                <div class="modal-body">
<?php
                                    echo do_shortcode( '[bidx app="media"]' );
?>
                                </div>
                                <div class="modal-footer">
                                    <a href="#" class="btn btn-primary btnSelectFile"><?php _e( 'Select file(s)', 'bidxplugin' ); ?></a>
                                    <a href="#" class="btn btnCancelSelectFile"><?php _e( 'Cancel', 'bidxplugin' ); ?></a>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-controls-bottom">
                            <a href="#businessSummaryAccordion-CompanyDetails" data-toggle="collapse" data-parent="#businessSummaryAccordion" class="btn"><span class="fui-arrow-left"></span> <?php _e('Company Details', 'bidxplugin')?></a>
                            <a href="#businessSummaryAccordion-GeneralOverview" data-toggle="collapse" data-parent="#businessSummaryAccordion" class="btn pull-right"><?php _e('General Overview', 'bidxplugin')?> <span class="fui-arrow-right"></span> </a>
                        </div>

                    </div><!-- /Accordion-inner -->
                </div>

            </div><!-- /Documents -->

        </div><!-- /#businessSummaryAccordion -->

    </div><!-- /business summary content container -->

    <!-- SNIPPETS -->
    <div class="snippets hide">

        <!-- Existing company item -->
        <table>
            <tr class="companyItem">
                <td>
                    <div class="controls">
                        <label class="radio"><input type="radio" name="company" data-toggle="radio" value=""></label>
                    </div>
                </td>
                <td class="companyName"></td>
                <td class="registered"></td>
                <td class="employees"></td>
                <td class="location"></td>
            </tr>
        </table>

        <!-- Attachment -->
        <div class="attachmentItem span4 well well-white">
            <div class="row-fluid">
                <div class="span4">
                    <a href="#" class="documentLink" target="_blank"><img class="img-rounded documentImage"></a>
                </div>
                <div class="span7">
                    <h3 class="documentName"></h3>
                    <p class="createdDateTime"></p>
                    <p class="purpose"></p>
                    <p class="documentType"></p>
                </div>
                <a href="#removeItem" class="btn btn-danger btn-mini btn-block"><?php _e( 'Remove document from this business summary', 'bidxplugin' ); ?></a>
            </div>
        </div>

        <!-- Management Team Item -->
        <div class="managementTeamItem span6 well well-white">

            <!-- First Name -->
            <div class="control-group span11">
                <label class="control-label"><?php _e('First name','bidxplugin'); ?></label>
                <div class="controls">
                    <input type="text" name="firstName" placeholder="<?php _e('Please enter the first name','bidxplugin'); ?>">
                </div>
            </div>

            <!-- Last Name -->
            <div class="control-group span11">
                <label class="control-label"><?php _e('Last name','bidxplugin'); ?></label>
                <div class="controls">
                    <input type="text" name="lastName" placeholder="<?php _e('Please enter the last name','bidxplugin'); ?>">
                </div>
            </div>

            <!-- Role -->
            <div class="control-group span11">
                <label class="control-label"><?php _e('Role of partner in this business','bidxplugin'); ?></label>
                <div class="controls">
                    <input type="text" name="role" placeholder="<?php _e('Please type the role of the partner','bidxplugin'); ?>">
                </div>
            </div>

            <!-- Expertise -->
            <div class="control-group span11">
                <label class="control-label"><?php _e('Describe relevant expertise of business partner','bidxplugin'); ?></label>
                <div class="controls">
                    <textarea type="text" name="expertise" placeholder="<?php _e('Please describe relevant expertise of business partner','bidxplugin'); ?>"></textarea>
                </div>
            </div>

            <!-- LinkedIn -->
            <div class="control-group span11">
                <label class="control-label"><?php _e('LinkedIn profile','bidxplugin'); ?></label>
                <div class="controls">
                    <input type="text" name="linkedIn" placeholder="<?php _e('Please enter your LinkedIn profile URL','bidxplugin'); ?>" />
                </div>
            </div>

            <!-- Profile picture -->
            <div class="profilePictureControl control-group span11">
                <label class="control-label"><?php _e('Picture','bidxplugin'); ?></label>
                <div class="controls">
                    <div class="profilePictureContainer"></div>
                    <a href="#changeProfilePicture" class="btn btn-primary"><?php _e('Change profile picture', 'bidxplugin')?></a>
                </div>
            </div>

            <a href="#removeItem" class="btn btn-danger btn-mini btn-block"><?php _e('Remove this partner','bidxplugin'); ?></a>
        </div>
    </div>

</div><!-- /businesssummary -->
