<?php

$businessSummary    = $this->data;
$progress           = $this -> completenessScore ? $this -> completenessScore : '0';

$businessSummaryBidxMeta = isset($businessSummary->bidxMeta)
    ? $businessSummary->bidxMeta
    : null;

$canEdit        = $this->exst($businessSummaryBidxMeta->bidxCanEdit, false);
$canRate        = $this->exst($businessSummaryBidxMeta->bidxCanRate, false);
$ratingCount    = $this->exst($businessSummaryBidxMeta->bidxRatingCount, 0);
$ratingAverage  = $this->exst($businessSummaryBidxMeta->bidxRatingAverage, null);
$entityStatus   = $this->exst($businessSummaryBidxMeta->bidxEntityStatus, '');

// get the enitities of the current user
$ownerId 		= $businessSummary->bidxMeta->bidxOwnerId;

$businessSummaryId = $businessSummaryBidxMeta->bidxEntityId;

// check, is access granted?
$hasAccess = false;

// To display Company Tab
//
$company    = $this->exst ($businessSummary->company);
$attachment = $this->exst ($businessSummary->attachment);

$currentYear = date("Y");

?>
<div class="businessSummary anonymous">
<?php             
            if ( $this->exst($businessSummaryBidxMeta->bidxEntityId) )
            {
?>
    <div class="businessCover">
        <div class="coverImageContainer">
<?php
            if ( $businessSummary->cover && $businessSummary->cover->document ):
?>            
            <div class="coverImage">
                <img src="<?php echo $businessSummary->cover->document ?>" alt="Cover Image" style="position: relative; top: <?php echo $businessSummary->cover->top?>px">
            </div>
<?php
            endif;
?>
        </div>
    </div>

<?php

        $updatedDate = date( 'd M Y', $businessSummaryBidxMeta->bidxLastUpdateDateTime );

?>
    <div class="bg-gray control-bar">


        <div class="bs-info hide-overflow">
            <div class="bs-cell main-padding pull-left"><i class="fa fa-line-chart"></i> <span class="hidden-xs"><?php echo _e('Completed', 'bidxplugin')?>:</span> <?php echo $progress; ?><span>%</span></div>
            <div class="bs-cell main-padding pull-left hidden-xs">
                <div class="rating-wrapper">
                    <div class="rating-no-score <?php echo !$ratingAverage ? '' : 'hide' ?>">
                        <span class="rating-score-text"><?php echo _e('No Score', 'bidxplugin'); ?></span>
                    </div>
                    <div class="rating-score <?php echo $ratingAverage ? '' : 'hide' ?>">
                        <i class="fa fa-star"></i> 
                        <?php echo _e('Score', 'bidxplugin')?>: <span class="rating-average"><?php echo $ratingAverage ? $ratingAverage : "?"; ?></span>
                    </div>
                </div>
            </div>
            <div class="bs-cell main-padding pull-left"><i class="fa fa-refresh"></i> <span class="hidden-xs"><?php echo _e('Last Update', 'bidxplugin')?>:</span> <?php echo $updatedDate; ?></div>
<?php
            foreach ($businessSummary->financialSummaries as $key => $year)
            {
                if ( $key === $currentYear ) :
            ?>
                    <div class="bs-cell main-padding pull-left"><i class="fa fa-dollar"></i> <span class="hidden-xs"><?php echo _e('Finance Needed', 'bidxplugin')?>:</span> <?php echo $year->financeNeeded; ?></div>
            <?php 
                endif;
            }
?>            
        </div>


    </div>
    <br>
    <div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
<?php
            if ( $businessSummary->logo && $businessSummary->logo->document ):
?>            
            <div class="logoImage">
                <img src="<?php echo $businessSummary->logo->document ?>" class="center-img" alt="Logo Image">
            </div>
<?php
            endif;
?>
        
    </div>
    </div>



    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
            <h1>
                <?php echo $this->exst( $businessSummary->name ); ?>
                <small>&nbsp;<?php echo _e( 'by', 'bidxplugin' ); ?>&nbsp;
                    <a href="/member/<?php echo $this->exst( $businessSummaryBidxMeta->bidxOwnerId ); ?>"><?php echo $this->exst( $businessSummaryBidxMeta->bidxOwnerDisplayName ); ?></a>
                </small>
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
            <h4><?php echo $this->exst( $businessSummary->slogan ); ?></h4>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
<?php
            $videoUrl = $this->exst($businessSummary->externalVideoPitch);
            $parsedVideo = $this->parseVideos( $videoUrl );

            if ( $parsedVideo )
            {
                $theVideo .= '<div class="video-wrapper embed-responsive embed-responsive-16by9 bottom-margin-lineheight">'.$parsedVideo[0]['videoplayer'].'</div>';
            }

            echo $theVideo;
?>
        </div>
    </div>





    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">

<?php
            $rowValues = array (

                __('Stage of business','bidxplugin')
                    => $this->getStaticVal( 'stageBusiness', $this->exst($businessSummary->stageBusiness)),

                __('Countries','bidxplugin')
                    => $this->getMultiValues( $this->exst($businessSummary->countryOperation), ', ', 'country' ),

                __('Industry','bidxplugin')
                    => $this->getMultiValues( $this->exst($businessSummary->industry), '<br> ','industry')

            );
?>

            <h3 class="to-uppercase"><?php _e('Basic information', 'bidxplugin')?></h3>
<?php
            echo $this->tableRow( $rowValues );

            if ( $attachment )
            {
?>
                <h4>Has attachment</h4>
<?php                
            }
?>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-4 col-sm-offset-4 big-padding-vertical">
            <a href="/join" class="btn btn-lg btn-block btn-secondary"><?php echo _e( 'Access business summary', 'bidxplugin' ); ?></a>
        </div>
    </div>


<?php
            }
?>


</div>
