<?php

$businessSummary    = $this->data;

$progress           = $this -> completenessScore ? $this -> completenessScore : '0';

$businessSummaryBidxMeta = isset($businessSummary->bidxMeta)
    ? $businessSummary->bidxMeta
    : null;

$canEdit        = $this->exst($businessSummaryBidxMeta->bidxCanEdit, false);
$canRate        = $this->exst($businessSummaryBidxMeta->bidxCanRate, false);
$ratingCount    = $this->exst($businessSummaryBidxMeta->bidxRatingCount, 0);
$ratingAverage  = $this->exst($businessSummaryBidxMeta->bidxRatingAverage, null);
$entityStatus   = $this->exst($businessSummaryBidxMeta->bidxEntityStatus, '');

// get the enitities of the current user
//
$sessionData    = BidxCommon::$staticSession;
$entities       = isset( $sessionData->data->wp->entities ) ? $sessionData->data->wp->entities : null;

$ownerId        = $businessSummary->bidxMeta->bidxOwnerId;
$loggedInUserId = $sessionData->data->id;

// if a user has an investorProfile, he is allowed to request access to a business summary
//
$canRequestAccess = isset( $entities->bidxInvestorProfile );

$businessSummaryId = $businessSummaryBidxMeta->bidxEntityId;

// get accessrequest status for this user and businesssummary
//
$requestStatus = isset( $businessSummary->accessAuthorization ) ? $businessSummary->accessAuthorization : null;

// check, is access granted?
$hasAccess = false;

$attachmentItem = <<<EOT
    <div class="attachmentItem col-md-6">
        <div class="media well">
            <div class="pull-left img-cropper">
                {{documentImage}}
            </div>
            <div class="media-body">
                <strong class="media-heading documentName">{{documentName}}</strong>
                <div class="purpose">{{purpose}}</div>
                <div class="documentType">{{documentType}}</div>
                {{documentLink}}
            </div>
        </div>
    </div>
EOT;

// The attachments item template exists of two types of variables, dynamic values and translations
//
$attachmentItemTranslations = array(
);

// To display Company Tab
//
$company    = $this->exst ($businessSummary->company);
$attachment = $this->exst ($businessSummary->attachment);

// Default set of rowproperties
//
$viewRowProperties = array ('tag_label' => 'label', 'tag_value' => 'div', 'class_label' => 'bidx-label', 'class_value' => 'bidx-value', 'class_row' => '' );

// Find the Download Financial templates URL
// TODO: Not the final version
//
$dlpage = get_page_by_title( 'Download financial templates' );
$dlurl = !empty( $dlpage ) ? $dlpage -> guid : false;

?>
<div class="businessSummary" id="businessSummary" data-bsid=<?php echo $businessSummaryId; ?>>
    <div class="businessCover">
        <div class="coverImageContainer">
<?php
            if ( $businessSummary->cover && $businessSummary->cover->document ):
?>            
            <div class="coverImage">
                <img src="<?php echo $businessSummary->cover->document ?>" alt="Cover Image" data-initop="<?php echo $businessSummary->cover->top?>" style="position: relative; top: <?php echo $businessSummary->cover->top?>px">
            </div>
<?php
            endif;
?>
            <div class="view viewEdit">
<?php
            if ( $canEdit )
            {
    ?>
                <div class="btn-group coverBtns">
                    <a class="btn btn-primary btn-large btnCover" data-toggle="modal" href="#coverImage"><?php echo _e( 'Add or Change', 'bidxplugin' ); ?></a>
                    <a class="btn btn-primary btn-large btnRemove" data-toggle="modal" href="#coverRemove"><?php echo _e( 'Remove', 'bidxplugin' ); ?></a>
                </div>

                <div class="coverModal modal fade">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                <h3><?php _e('Check the file you want to use as your cover', 'bidxplugin' ); ?></h3>
                            </div>
                            <div class="modal-body">
<?php
                                // Media app will only be inserted once, this is by design!
                                //
                                echo do_shortcode( '[bidx app="media"]' );
?>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-primary btnSelectFile"><?php _e( 'Select file(s)', 'bidxplugin' ); ?></button>
                                <button type="button" class="btn btn-link btnCancelSelectFile" data-dismiss="modal"><?php _e( 'Cancel', 'bidxplugin' ); ?></button>

                            </div>
                        </div>
                    </div>
                </div>
<?php           
            }
?>        
            </div>
        </div>
    </div>

<?php
    if ( $this->exst($businessSummaryBidxMeta->bidxEntityId) )
    {

        $updatedDate = date( 'd M Y', $businessSummaryBidxMeta->bidxLastUpdateDateTime );

?>
    <div class="bg-gray control-bar">

<?php
                if ( $canRequestAccess && !$canEdit )
                {
                    $accessRequestControl = "";

                    switch ( $requestStatus )
                    {
                        case 'pending':
                            $accessRequestProgress = '';
                            $accessGranted = 'hide';
                            break;
                        case 'refused':
                            $accessRequestProgress = '';
                            $accessGranted = 'hide';
                            break;
                        case 'granted':
                            $accessRequestProgress = 'hide';
                            $accessGranted = '';
                            break;
                        case 'none':
                            $accessRequestProgress = 'hide';
                            $accessGranted = 'hide';
                            break;
                        default:
                            $accessRequestProgress = 'hide';
                            $accessGranted = 'hide';
                    }
                }

?>


        <div class="bs-info hide-overflow">
            <div class="bs-cell main-padding pull-left"><i class="fa fa-line-chart"></i> <?php echo _e('Completed', 'bidxplugin')?>: <?php echo $progress; ?><span>%</span></div>
            <div class="bs-cell main-padding pull-left">
                <div class="rating-wrapper">
                    <div class="rating-no-score <?php echo !$ratingAverage ? '' : 'hide' ?>">
                        <span class="rating-score-text"><?php echo _e('No Score', 'bidxplugin'); ?></span>
                    </div>
                    <div class="rating-score <?php echo $ratingAverage ? '' : 'hide' ?>">
                        <i class="fa fa-star"></i> 
                        <?php echo _e('Score', 'bidxplugin')?>: <span class="rating-average"><?php echo $ratingAverage ? $ratingAverage : "?"; ?></span>
                    </div>
                </div>
            </div>
            <div class="bs-cell main-padding pull-left"><i class="fa fa-refresh"></i> <?php echo _e('Last Update', 'bidxplugin')?>: <?php echo $updatedDate; ?></div>
            <div class="bs-cell main-padding pull-left <?php echo $accessGranted; ?>"><i class="fa fa-check"></i> <?php echo _e('Full Access granted', 'bidxplugin')?></div>
            <div class="bs-cell main-padding pull-left <?php echo $accessRequestProgress; ?>"><i class="fa fa-exclamation-circle"></i> <?php echo _e('Access request pending', 'bidxplugin')?></div>
        </div>


    </div>
        <div class="row main-padding">
            <div class="col-sm-4">
            </div>

            <div class="col-sm-5">
    <?php
                /*
                 * We want ratings to be indexed by Google, so need to include this on page load. It
                 * might be updated in JavaScript though, so also check the translations in i18n.xml.
                 */

    ?>
                <div class="rating-wrapper">
<?php
                    // Owners and active mentors cannot rate their plans
                    if( $canRate )
                    {
                        $ratingUser = $this->rating->userRating;
?>
                        <div class="rating-vote">
                            <span class="rating-vote-text"><span class="rating-user-label"><?php $ratingUser->value ? _e('Your rating', 'bidxplugin') : _e('Rate this plan', 'bidxplugin') ?></span></span>
                            <div data-rating="<?php echo $this->rating->userRating->value ? $this->rating->userRating->value : 0 ?>" class="raty"></div>
                        </div>
    <?php
                    }
    ?>
                </div>
            </div>
            <div class="col-sm-3 text-right">
                <div class="btn-group">
<?php
                // if a user is allowed to request full access to a business summary and it NOT The owner of the business summary
                //
                if ( $canRequestAccess && !$canEdit )
                {
                    $accessRequestControl = "";

                    switch ( $requestStatus )
                    {
                        case 'pending':
                            $accessRequestSend = 'hide';
                            break;
                        case 'refused':
                            $accessRequestSend = 'hide';
                            break;
                        case 'granted':
                            $accessRequestSend = 'hide';
                            break;
                        case 'none':
                            $accessRequestSend = '';
                            break;
                        default:
                            $accessRequestSend = 'hide';
                    }
?>
                    <a class="btn btn-primary bidxRequestFullAccess <?php echo $accessRequestSend; ?>" href="#"><i class="fa fa-eye fa-big fa-above"></i><?php echo _e( 'Request full access', 'bidxplugin' ); ?></a>

<?php
                }
?>
<?php
                // does a user have rights to edit ( is the owner )
                //
                    if ( $canEdit )
                    {
?>
                        <a class="btn btn-primary editBS" href="#editBusinessSummary/<?php echo $businessSummaryId; ?>"><i class="fa fa-pencil fa-big fa-above"></i> <?php _e( 'Edit', 'bidxplugin' ); ?></a>
<?php
                    }
?>
                </div>
                <div class="editControlsContainer">
                    <div class="editControls pull-right">

                        <!-- SHOW -->
                        <div class="view viewShow"></div>

                        <!-- EDIT, conditionally filled by the app -->
                        <div class="view viewEdit btn-group"></div>

                        <!-- sucess msg, used as a placeholder for showing msgs -->

                        <div class="view viewMainsuccess alert alert-success">
                            <p class="successMsg"></p>
                        </div>
                    </div>
                </div>

            </div>
        </div>
<?php
    }
?>
<!-- SHOW -->
<div class="view viewShow">
<div class="mainBusiness hide-overflow">
<div class="row">
<div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
<?php
            if ( $this->exst($businessSummaryBidxMeta->bidxEntityId) )
            {
?>
                <h1>
                    <?php echo $this->exst( $businessSummary->name ); ?>
                    <small>&nbsp;<?php echo _e( 'by', 'bidxplugin' ); ?>&nbsp;
                        <a href="/member/<?php echo $this->exst( $businessSummaryBidxMeta->bidxOwnerId ); ?>"><?php echo $this->exst( $businessSummaryBidxMeta->bidxOwnerDisplayName ); ?></a>
                    </small>
                </h1>
<?php
            }
            else
            {
?>
                <h1><?php echo _e( 'Create Business Summary', 'bidxplugin' ); ?></h1>
<?php

            }
?>

            <h4><?php echo $this->exst( $businessSummary->slogan ); ?></h4>
<?php
            $videoUrl = $this->exst($businessSummary->externalVideoPitch);
            $parsedVideo = $this->parseVideos( $videoUrl );

            if ( $parsedVideo )
            {
                $theVideo .= '<div class="video-wrapper embed-responsive embed-responsive-16by9">'.$parsedVideo[0]['videoplayer'].'</div>';
            }

            echo $theVideo;
?>
<?php
    if ( $this->exst($businessSummary->summary) )
    {
?>
            <h3 class="to-uppercase"><?php _e('In a few words', 'bidxplugin')?></h3>
            <div>
<?php
                echo $this->exst($businessSummary->summary);
?>
            </div>

<?php
    }
?>

    <div class="main-padding-vertical">
            <h3 class="to-uppercase"><?php _e('General Overview', 'bidxplugin')?></h3>
<?php

            $rowValues = array
            (
                __('Reason for financing','bidxplugin') => $this->exst($businessSummary->summaryFinancingNeeded),
                __('Reason for submission','bidxplugin') => $this->getMultiValues( $this->exst($businessSummary->reasonForSubmission), ', ', 'reasonForSubmission' ),
                __('Equity currently retained','bidxplugin') => $this->exst($businessSummary->equityRetained),
                __('Investment type','bidxplugin') => $this->getMultiValues( $this->exst($businessSummary->investmentType), ', ', 'investmentType' )

            );
            echo $this->tableRow ( $rowValues );
?>
    </div>

    <div class="main-padding-vertical">
            <h3 class="to-uppercase"><?php _e('The Business', 'bidxplugin')?></h3>
<?php

            $rowValues = array
            (
                __('Stage of business','bidxplugin') => $this->getStaticVal( 'stageBusiness', $this->exst($businessSummary->stageBusiness)),
                __('Industry') => $this->getMultiValues( $this->exst($businessSummary->industrySector), ', ','industrySector'),
                __('Product / Service','bidxplugin') => $this->getMultiValues( $this->exst($businessSummary->productService), ', ', 'productService' ),
                __('Country of business','bidxplugin') => $this->getMultiValues( $this->exst($businessSummary->countryOperation), ', ', 'country' ),
                __('Social impact','bidxplugin') => $this->getMultiValues( $this->exst($businessSummary->socialImpact), ', ', 'socialImpact' ),
                __('Environmental impact','bidxplugin') => $this->getMultiValues( $this->exst($businessSummary->envImpact), ', ', 'envImpact' ),
                __('Customer type','bidxplugin') => $this->getMultiValues( $this->exst($businessSummary->consumerType), ', ', 'consumerType' )

            );
            echo $this->tableRow ( $rowValues );
?>
    </div>

    <div class="main-padding-vertical">
            <h3 class="to-uppercase"><?php _e('The Team', 'bidxplugin')?></h3>
<?php
            $rowValues = array
            (
                __('Role of Entrepreneur','bidxplugin') => $this->exst($businessSummary->personalRole),
                __('Applicable Expertise') => $this->exst($businessSummary->personalExpertise)

            );
            echo $this->tableRow ( $rowValues );

?>
            <h4><?php echo _e('Supporting members of management team', 'bidxplugin')?></h4>
            <table class="table">
<?php            
            foreach ( $businessSummary->managementTeam as $key => $member)
            {
?>
                <tr><td>
                <div class="media team-member">
<?php
                    if ( $member->profilePicture->document )
                    {
?>                            
                        <div class="bidx-profilepicture pull-left team-picture">
                            <div class="img-cropper">
                                <img src="<?php echo $member->profilePicture->document ?>" alt="">
                            </div>
                        </div>
<?php
                    }
                    else
                    {
?>
                        <div class="pull-left">
                            <div class="icons-rounded pull-left"><i class="fa fa-user text-primary-light"></i></div>
                        </div>
<?php                        
                    }
?>                            
                    <div class="media-body">
                        <div class="media-heading">
                            <strong><?php echo $member->firstName . ' ' . $member->lastName; ?></strong>
<?php
                            if ( $member->linkedIn ) :
?>                            
                                <div class="team-linkedin pull-right">
                                    <a target="_blank" class="btn btn-linkedin btn-xs" href="<?php echo $member->linkedIn; ?>">
                                        <i class="fa fa-linkedin-square"></i>
                                        <?php echo _e('LinkedIn', 'bidxplugin')?> </a> 
                                </div>
<?php
                            endif;
?>                            
                        </div>
                        <div class="media-body">
                            <div class="team-role">
                                <em><?php echo $member->role; ?></em>
                            </div>
                            <div class="team-expert">
                                <?php echo $member->expertise; ?>
                            </div>
                        </div>
                    </div>
                </div>
                </td></tr>
<?php
            }
?>
            </table>

    </div>

            <h3 class="to-uppercase"><?php _e('Financial Details', 'bidxplugin')?></h3>
<?php
            $rowValues = array
            (
                __('Business sales started in','bidxplugin')=> $this->exst($businessSummary->yearSalesStarted)
            );

            echo $this->inlineRow ( $rowValues );
?>
        <table class="table table-bordered">
            <tr>
                <th class="text-center td-15" rowspan="2"><?php _e('Year', 'bidxplugin')?></th>
                <th class="text-center hidden-sm hidden-xs" colspan="3"><?php _e('Income statement', 'bidxplugin')?></th>
                <th class="text-center visible-sm visible-xs"><?php _e('Income statement', 'bidxplugin')?></th>
                <th class="text-center" rowspan="2"><?php _e('Finance needed', 'bidxplugin')?> * </th>
                <th class="text-center hidden-sm hidden-xs" rowspan="2"><?php _e('Employees', 'bidxplugin')?> ** </th>
            </tr>
            <tr>
                <th class="text-center td-15 hidden-sm hidden-xs"><small><?php _e('Sales revenues', 'bidxplugin')?></small></th>
                <th class="text-center td-15 hidden-sm hidden-xs"><small><?php _e('Operational costs', 'bidxplugin')?></small></th>
                <th class="text-center td-15"><small><?php _e('Total income', 'bidxplugin')?></small></th>
            </tr>
<?php
            $financialDetails = $this->exst( $businessSummary->financialSummaries );

            foreach ( $financialDetails as $year => $yearDetails )
            {
                $currentYear = date("Y");
                $yd;

                if ( $year < $currentYear )
                {
                    $yd = __('Actuals', 'bidxplugin');
                }
                elseif ( $year > $currentYear )
                {
                    $yd = __('Forecast', 'bidxplugin');
                }
                else
                {
                    $yd = __('Current year', 'bidxplugin');
                }

                echo '<tr>';
                echo '<td class="text-center">' . $year . '</td>';
                echo '<td class="text-right hidden-sm hidden-xs">' . '<small>$</small> ' . $yearDetails->salesRevenue . '</td>';
                echo '<td class="text-right hidden-sm hidden-xs">' . '<small>$</small> ' . $yearDetails->operationalCosts . '</td>';
                echo '<td class="text-right">' . '<small>$</small> ' . $yearDetails->totalIncome . '</td>';
                echo '<td class="text-right">' . '<small>$</small> ' . $yearDetails->financeNeeded . '</td>';
                echo '<td class="text-center hidden-sm hidden-xs">' . $yearDetails->numberOfEmployees . '</td>';
                echo '</tr>';

            }
?>            
        </table>
        <p>
            * <small><?php _e('from external financiers in US Dollars', 'bidxplugin')?></small><br>
            ** <small><?php _e('being directly paid in this business', 'bidxplugin')?></small>
        </p>



<?php
    if ( $this->exst( $company )) :
?>
    <div class="main-padding-vertical">
            <h3 class="to-uppercase"><?php _e('Company Details', 'bidxplugin')?></h3>
<?php
                $companyWebsite = null;

                if ( $this->exst( $company->website ) ) {
                    $companyWebsite = sprintf( '<a href="%1$s" target="_blank">%1$s</a>', $this->exst($company->website) );
                }

            $rowValues = array
            (
                __('Company name','bidxplugin') => $this->exst($company->name),
                __('Company website') => $companyWebsite,
                __('Registered') => $this->exst($company->registered) == true ? __('Yes','bidxplugin') : __('No','bidxplugin'),
                __('Legal form') => $this->getStaticVal( 'legalForm', $this->exst($company->legalFormBusiness) ),
                __('Registration number') => $this->exst($company->registrationNumber),
                __('Fiscal number') => $this->exst($company->fiscalNumber),
                __('Date company established') => $this->exst($company->dateCompanyEstab),
                __('Number permanent male employees') => $this->exst($company->numPermMaleEmp ),
                __('Number permanent female employees') => $this->exst($company->numPermFemaleEmp ),
                __('Number temporary male employees') => $this->exst($company->numTempMaleEmp ),
                __('Number temporary female employees') => $this->exst($company->numTempFemaleEmp ),
                __('Street') => $this->exst($company->statutoryAddress->street),
                __('Street number') => $this->exst($company->statutoryAddress->streetNumber),
                __('Neighborhood') => $this->exst($company->statutoryAddress->neighborhood),
                __('Postalcode') => $this->exst($company->statutoryAddress->postalCode),
                __('Postbox') => $this->exst($company->statutoryAddress->postBox),
                __('City') => $this->exst($company->statutoryAddress->cityTown),
                __('Country') => $this->getStaticVal( 'country', $this->exst($company->statutoryAddress->country) )

            );
            echo $this->tableRow ( $rowValues );
?>
    </div>
<?php
    endif;

    if ( $this->exst( $businessSummary->mentorAdvisory )) :
?>
    <div class="main-padding-vertical ">
            <h3 class="to-uppercase"><?php _e('For Mentors', 'bidxplugin')?></h3>
<?php
                $rowValues = array
                (
                    __('Expertise needed') => $this->getMultiValues( $this->exst($businessSummary->expertiseNeeded), ', ', 'mentorExpertise' ),
                    __('Expertise needed in detail') => $this->exst($businessSummary->expertiseNeededDetail)
                );

                echo $this->tableRow ( $rowValues );
?>            
    </div>
<?php
    endif;

    if ( $this->exst( $businessSummary->attachment )) :
?>

    <div class="main-padding-vertical">
            <h3 class="to-uppercase"><?php _e('Attached Documents', 'bidxplugin')?></h3>
<?php
            echo $this->displayDocuments ( $businessSummary->attachment );
?>
    </div>
<?php
    endif;
?>

</div>
<div class="col-sm-4 panel-feedback hide"></div>
</div>
</div>
</div>
<!-- LOAD -->
<div class="view viewLoad alert alert-info text-center">
    <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e('Retrieving business summary information...','bidxplugin'); ?>
</div>


<!-- ERROR -->
<div class="view viewError alert alert-warning">
    <p class="errorMsg"></p>
</div>

<div class="view viewEdit">
    <!-- Accordion -->
<div class="row tabs-vertical">

    <div class="col-sm-3 tabs-nav">
        <ul class="nav nav-tabs tabs-left">
            <li class="active"><a href="#tab-bs-overview" data-toggle="tab"><?php _e('General Overview','bidxplugin'); ?></a></li>
            <li><a href="#tab-bs-about-business" data-toggle="tab"><?php _e('About the business','bidxplugin'); ?></a></li>
            <li><a href="#tab-bs-about-you" data-toggle="tab"><?php _e('About you and your team','bidxplugin'); ?></a></li>
            <li><a href="#tab-bs-financial" data-toggle="tab"><?php _e('Financial Details','bidxplugin'); ?></a></li>
            <li><a href="#tab-bs-company" data-toggle="tab"><?php _e('Company Details','bidxplugin'); ?></a></li>
            <li><a href="#tab-bs-mentoring" data-toggle="tab"><?php _e('Mentoring Details','bidxplugin'); ?></a></li>
            <li><a href="#tab-bs-documents" data-toggle="tab"><?php _e('Documents','bidxplugin'); ?></a></li>
        </ul>
    </div>
    <div class="col-sm-9 tabs-content">
        <div class="tab-content">
            <div class="tab-pane hide-overflow active" id="tab-bs-overview">



        <!-- General Overview -->
            <div  id="businessSummaryCollapse-GeneralOverview">

                    <!-- EDIT -->
                    <div class="view viewEdit">
                        <blockquote class="alert-info"><?php _e('Use this section to describe your business. Think about what information you would like other people (investors and entrepreneurs) to know about your business if you only had a few minutes to explain.','bidxplugin')?></blockquote>
                        <form id="frmBusinessSummary-GeneralOverview">
                            <div class="row">
                                <!-- Name -->
                                <div class="form-group col-sm-6">
                                    <label><?php _e('Business name','bidxplugin'); ?></label>
                                    <input type="text" class="form-control" name="name" placeholder="<?php _e('Business name','bidxplugin'); ?>">
                                </div>

                                <!-- Slogan -->
                                <div class="form-group col-sm-6">
                                    <label><?php _e('Give a short description of your business in a maximum of 140 characters','bidxplugin'); ?> <small class="text-muted"><?php _e('Optional','bidxplugin'); ?></small></label>
                                    <textarea type="text" class="form-control" name="slogan" placeholder="<?php _e('Here you can add a few words to promote your business. It should be a short sentence to help your audience understand and remember what it is that you sell and why','bidxplugin'); ?>"></textarea>
                                </div>
                            </div>
                            <div class="row">
                                <!-- Summary -->
                                <div class="form-group col-sm-6">
                                    <label><?php _e('Provide a summary of your business in a maximum of 900 characters','bidxplugin'); ?></label>
                                    <textarea type="text" class="form-control" name="summary" placeholder="<?php _e('Fill in a description of your business here: what you sell, who your potential customers are, and what your business vision and mission is','bidxplugin'); ?>"></textarea>
                                </div>

                                <!-- Reason For Submission -->
                                <div class="form-group col-sm-6">
                                    <label><?php _e('Reason for submission of business summary','bidxplugin'); ?></label>
                                    <select name="reasonForSubmission" data-forcearray="true"></select>

                                </div>
                            </div>
                            <div class="row">
                            <!-- Equity Retained -->
                                <div class="form-group col-sm-6">
                                    <label><?php _e('Percentage equity you currently retain','bidxplugin'); ?></label>
                                    <div class="input-group">
                                        <span class="input-group-addon">%</span>
                                        <input type="text" class="form-control" name="equityRetained" placeholder="<?php _e('Percentage','bidxplugin'); ?> (e.g. 11.11)">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <!-- Investment type -->
                                <div class="form-group col-sm-6">
                                    <label><?php _e('Investment type','bidxplugin'); ?></label>
<?php
                                        // Render the checkboxes based upon the items from the static data api for the 'investmentType' typeCode / groupCode / context
                                        //
                                        if ( isset(BidxCommon::$i18nData['static']['investmentType']) ) {
                                            foreach ( BidxCommon::$i18nData['static']['investmentType'] as $investmentType ) {
                                                printf( '<div class="checkbox">
                                                            <input type="checkbox" value="%s" id="checkbox-%s" name="investmentType[]" />
                                                            <label for="checkbox-%s"><span></span>%s</label>
                                                        </div>', $investmentType->value, $investmentType->value, $investmentType->value, $investmentType->label );
                                            }
                                        }
?>
                                </div>

                                <!-- Summary Financing Needed -->
                                <div class="form-group col-sm-6">
                                    <label><?php _e('Why does your business need financing? (max. 300 characters)','bidxplugin'); ?> <small class="text-muted"><?php _e('Optional','bidxplugin'); ?></small></label>
                                    <textarea name="summaryFinancingNeeded" class="form-control" placeholder="<?php _e('Please give the reason your business needs financing','bidxplugin'); ?>"></textarea>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-sm-6">
                                    <label><?php _e('Video pitch','bidxplugin'); ?> <small class="text-muted"><?php _e('Optional','bidxplugin'); ?></small></label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-video-camera"></i></span>
                                        <input type="text" class="form-control" name="externalVideoPitch" placeholder="<?php _e('Please enter a YouTube or Vimeo url link','bidxplugin'); ?>">
                                    </div>
                                </div>
                                <div class="form-group col-sm-6">
                                    <label><?php _e('Audio pitch','bidxplugin'); ?> <small class="text-muted"><?php _e('Optional','bidxplugin'); ?></small></label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-music"></i></span>
                                        <input type="text" class="form-control" name="externalAudioPitch" placeholder="<?php _e('Please enter a url link','bidxplugin'); ?>">
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div><!-- /EDIT -->

        </div><!-- /General Overview -->
    </div>

    <div class="tab-pane hide-overflow" id="tab-bs-about-business">

        <!-- About the business -->
            <div  id="businessSummaryCollapse-AboutTheBusiness">

                    <!-- EDIT -->
                    <div class="view viewEdit">
                        <blockquote class="alert-info"><?php _e('Here we provide you with tools to share more precise information about your business, i.e. what industry it operates in, what it produces and where it operates. This information will be used to match your initiative with other businesses and investors.','bidxplugin')?></blockquote>
                        <form id="frmBusinessSummary-AboutYourBusiness">

                            <div class="industrySectors">
                                <label><?php _e('Industry','bidxplugin'); ?></label>
                            </div>

                            <div class="row">
                                <!-- Country operation -->
                                <div class="form-group col-sm-6">
                                    <label><?php _e('Country of business','bidxplugin'); ?></label>
                                    <select name="countryOperation" multiple></select>
                                </div>

                                <!-- Social impact -->
                                <div class="form-group col-sm-6">
                                    <label><?php _e('Social impact','bidxplugin'); ?> <small class="text-muted"><?php _e('Optional','bidxplugin'); ?></small></label>
                                    <select name="socialImpact" multiple></select>
                                </div>
                            </div>
                            <div class="row">
                                <!-- Env impact -->
                                <div class="form-group col-sm-6">
                                    <label><?php _e('Environmental impact','bidxplugin'); ?> <small class="text-muted"><?php _e('Optional','bidxplugin'); ?></small></label>
                                    <select name="envImpact" multiple></select>
                                </div>

                                <!-- Stage Business is read only -->

                                <!-- Consumer Type -->
                                <div class="form-group col-sm-6">
                                    <label><?php _e('Type of customer you sell to','bidxplugin'); ?></label>
<?php
                                        // Render the checkboxes based upon the items from the static data api for the 'consumerType' typeCode / groupCode / context
                                        //
                                        $typeCode = 'consumerType';
                                        if ( isset(BidxCommon::$i18nData['static'][$typeCode]) ) {
                                            foreach ( BidxCommon::$i18nData['static'][$typeCode] as $item ) {
                                                printf( '<div class="checkbox">
                                                            <input type="checkbox" value="%s" id="checkbox-%s" name="consumerType[]" />
                                                            <label for="checkbox-%s"><span></span>%s</label>
                                                        </div>', $item->value, $item->value, $item->value, $item->label );
                                            }
                                        }
?>
                                </div>
                            </div>
                        </form>
                    </div><!-- /EDIT -->

        </div><!-- /About the business -->
    </div>

    <div class="tab-pane hide-overflow" id="tab-bs-about-you">
        <!-- About you & your team -->
            <div  id="businessSummaryCollapse-AboutYouAndYourTeam">

                    <!-- EDIT -->
                    <div class="view viewEdit">
                        <blockquote class="alert-info"><?php _e('Your team is an essential part of the success of your business. Use this template to provide more information about yourself and your team members.', 'bidxplugin')?></blockquote>
                        <form id="frmBusinessSummary-AboutYouAndYourTeam">
                            <div class="row">
                                <!-- Personal Role -->
                                <div class="form-group formfield col-sm-6">
                                    <label><?php _e('Role of entrepreneur in this business (max. 30 characters)','bidxplugin'); ?></label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-tag"></i></span>
                                        <input type="text" name="personalRole" class="form-control" placeholder="<?php _e('Please give role of entrepreneur in this business','bidxplugin'); ?>">
                                    </div>
                                </div>

                                <!-- Personal Expertise -->
                                <div class="form-group col-sm-6">
                                    <label><?php _e('Please describe your expertise in relation to this business (180 characters)','bidxplugin'); ?></label>
                                    <textarea name="personalExpertise" class="form-control" placeholder="<?php _e('The details of your expertise for this business','bidxplugin'); ?>"></textarea>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-sm-12">
                                    <label><?php _e('Here you can give information about other members in your team.','bidxplugin'); ?></label>
                                    <a href="#addManagementTeam" class="btn btn-xs btn-primary"><span class="fa fa-plus"></span> <?php _e('Add','bidxplugin'); ?></a>
                                </div>
                            </div>

                            <div class="managementTeamContainer"></div>

                            <div class="managementTeamProfilePictureModal modal fade">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                      <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                        <h3><?php _e('Check the file you want to use as the picture for this member', 'bidxplugin' ); ?></h3>
                                      </div>
                                        <div class="modal-body">
<?php
                                            echo do_shortcode( '[bidx app="media"]' );
?>
                                        </div>
                                        <div class="modal-footer">
                                            <a href="#" class="btn btn-primary btnSelectFile"><?php _e( 'Select file(s)', 'bidxplugin' ); ?></a>
                                            <a href="#" class="btn btn-default btnCancelSelectFile"><?php _e( 'Cancel', 'bidxplugin' ); ?></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>


                    </div><!-- /EDIT -->

        </div><!-- /About you & your team -->
    </div>
    <div class="tab-pane hide-overflow" id="tab-bs-financial">
        <!-- Financial details -->
            <div  id="businessSummaryCollapse-FinancialDetails">

                    <form id="frmBusinessSummary-FinancialDetails">

                        <!-- EDIT -->
                        <div class="view viewEdit">
                            <blockquote class="alert-info"><?php _e('Here you should provide a very general overview of your finances, the financing you need, the number of employees you have currently and how you think your business has, and will continue to grow over time','bidxplugin')?></blockquote>
                            <!-- numYear-->

<?php
?>

                            <!-- If there is no financial plan uploaded -->
                            <a class="btn btn-primary" href="#businessSummaryCollapse-Documents" data-toggle="collapse" data-parent="#businessSummaryCollapse" ><span class="fa fa-upload"></span> <?php _e('Upload your financial plan', 'bidxplugin'); ?></a>

<?php
                            if ( $dlurl !== false) :
?>
                                <a  class="btn btn-link" href="<?php echo $dlurl; ?>"><?php _e('Or download a financial plan template.', 'bidxplugin'); ?>&nbsp;<span class="icon-download text-info"></span></a>
<?php
                            endif;
?>


                            <hr>
                            <div class="row">
                                <div class="form-group formfield col-sm-6">
                                    <label><?php _e('When did your business\'s sales start?','bidxplugin'); ?></label>
                                    <div class="controls">
                                        <select name="yearSalesStarted">
<?php
                                            $todayYear = date( 'Y' );
                                            $firstYear = $todayYear - 10;

                                            for ( $i = $todayYear; $i >= $firstYear; $i-- ) {
                                                printf( '<option value="%s">%s</option>', $i, $i );
                                            }
?>
                                        </select>
                                    </div>
                                </div>
                            </div>

                        </div>

                        <!-- VIEW and EDIT -->
                        <div class="view viewShow viewEdit">
<?php
                            $this->render('financialsummary.phtml');
?>
                        </div><!-- /VIEW and EDIT -->

                        <!-- ERROR -->
                        <div class="view viewError alert alert-warning">
                            <p class="errorMsg"></p>
                        </div>

                    </form>
        </div><!-- /Financial details -->
    </div>

    <div class="tab-pane hide-overflow" id="tab-bs-company">
        <!-- Company details -->
            <div  id="businessSummaryCollapse-CompanyDetails">

                    <!-- EDIT -->
                    <div class="view viewEdit">
                        <blockquote class="alert-info"><?php _e('In this section you can link your business to an existing company. If you do not yet have a company, you can skip this step by answering \'No\' to the first question. If you already created a company in the past, you can select it from the list', 'bidxplugin')?></blockquote>

                        <form id="frmBusinessSummary-CompanyDetails">

                            <!-- Has Company? -->
                            <div class="form-group">
                                <label><?php _e('Do you want to add a company profile to your Business Proposal?','bidxplugin'); ?></label>
                                <div class="controls">
                                    <div class="radio">
                                        <input type="radio" value="true" id="radio-CompanyYes" name="hasCompany" data-toggle="radio" />
                                        <label for="radio-CompanyYes"><span></span><?php _e('Yes','bidxplugin'); ?></label>
                                    </div>
                                    <div class="radio">
                                        <input type="radio" value="false" id="radio-CompanyNo" name="hasCompany" data-toggle="radio" />
                                        <label for="radio-CompanyNo"><span></span><?php _e('No','bidxplugin'); ?></label>
                                    </div>
                                </div>
                            </div>

                            <!-- Does have a company -->
                            <div class="doesHaveCompany">
                                <h2><?php _e('Select your company from the list below','bidxplugin'); ?></h2>
                                <table class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th></th>
                                            <th><?php _e('Company name','bidxplugin'); ?></th>
                                            <th><?php _e('Registered','bidxplugin'); ?></th>
                                            <th><?php _e('Employees','bidxplugin'); ?></th>
                                            <th><?php _e('Location','bidxplugin'); ?></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <!-- going into edit will populate this list with the response of the current company list of a member -->
                                    </tbody>
                                </table>

                                <a href="#addNewCompany" class="btn btn-primary"><?php _e('Or add a new company', 'bidxplugin')?></a>
                            </div>
                        </form>

                        <div class="addNewCompany">
<?php
                            echo do_shortcode( '[bidx app="company" noheader="true"]' );
?>
                            <a href="#addCompany" class="btn btn-primary"><?php _e('Save to list', 'bidxplugin')?></a>
                            <a href="#cancelAddCompany" class="btn btn-default"><?php _e('Cancel', 'bidxplugin')?></a>
                        </div>
                    </div><!-- /Edit -->

        </div><!-- /Company details -->
    </div>
    <div class="tab-pane hide-overflow" id="tab-bs-mentoring">
        <!-- Mentoring Details -->
            <div  id="businessSummaryCollapse-MentoringDetails">

                    <!-- EDIT -->
                    <div class="view viewEdit">
                        <blockquote class="alert-info"><?php _e('A mentor can help you ​to ​complete and improve your business proposal. ​Please indicate here if you would like the help of a mentor and, if yes, ​select the areas of expertise where you would like support.', 'bidxplugin')?></blockquote>
                        <form id="frmBusinessSummary-MentoringDetails">
                            <div class="row">
                                <div class="col-sm-6">
                                    <!-- Mentor Advisory? -->
                                    <div class="form-group">
                                        <label><?php _e('Do you want a mentor to advise you?​','bidxplugin'); ?></label>
                                        <div class="controls">
                                            <div class="radio">
                                                <input type="radio" value="true" id="radio-AdvisoryYes" name="mentorAdvisory" data-toggle="radio" />
                                                <label for="radio-AdvisoryYes"><span></span><?php _e('Yes','bidxplugin'); ?></label>
                                            </div>
                                            <div class="radio">
                                                <input type="radio" value="false" id="radio-AdvisoryNo" name="mentorAdvisory" data-toggle="radio" />
                                                <label for="radio-AdvisoryNo"><span></span><?php _e('No','bidxplugin'); ?></label>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row toggle toggle-mentorAdvisory">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label><?php _e('In which areas of expertise do you seek support?','bidxplugin'); ?></label>
                                        <select name="expertiseNeeded" multiple></select>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label><?php _e('Please specify for your business (max. 300 characters)'); ?></label>
                                        <textarea type="text" class="form-control" name="expertiseNeededDetail" placeholder="<?php _e('Describe here the problem areas or challenges in your business in the areas of expertise you selected.','bidxplugin'); ?>"></textarea>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div><!-- /EDIT -->
                    <!-- Mentor Matching Start -->
                        <div class="toggle toggle-mentorMatches">
                            <div class="view viewMentor">
                                <!-- ACTIVE REQUESTS -->
                                <div class="panel-heading">
                                    <a class="btn-block trigger-active-contacts">
                                        <?php _e('Active mentors')?>
                                    </a>
                                </div>
                                <div id="activeRequests">
                                    <div class="panel-body">
                                        <div class="mentor-active-list list-unstyled clearfix row">
                                        </div>
                                    </div>
                                </div>
                            </div>
                                 <!-- RECEIVED CONTACT REQUESTS -->
                            <div class="view viewMatchingmentors">
                                <div class="panel-heading">
                                    <a class="btn-block trigger-incoming-contacts">
                                        <?php _e('Matching mentors')?>
                                    </a>
                                </div>
                                <div id="incomingRequests">
                                    <div class="panel-body">
                                        <div class="mentor-match-list list-unstyled clearfix row"></div>
                                        <div class="view viewPager">
                                            <div class="pagerContainer">
                                                <div class="row">
                                                    <div class="col-sm-2 pagerTotal">
                                                        <?php _e('%count% matches found', 'bidxplugin'); ?>
                                                    </div>
                                                    <div class="col-sm-10">
                                                        <ul class="pager pull-left"></ul>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                            <!-- Mentor Matching End -->

        </div><!-- /Mentoring Details -->
    </div>
    <div class="tab-pane hide-overflow" id="tab-bs-documents">
        <!-- Documents -->
            <div  id="businessSummaryCollapse-Documents">

                    <!-- EDIT -->
                    <div class="view viewEdit">

                        <blockquote class="alert-info"><?php _e('Please upload your full business plan and financial plan here.','bidxplugin');?></blockquote>

                        <div class="attachmentContainer"></div>
                        <div class="alert alert-info">
                            <h2><?php _e('Templates to download','bidxplugin');?></h2>
                            <div>
                                <?php _e('If you do not have a full business or financial plan yet, you can use our templates to create one.', 'bidxplugin')?>
                            </div>
                            <p>

                                <a class="btn btn-warning" target="_blank" href="<?php echo _l(_pageuri('download-business-plan-templates'));?>">
                                    <?php _e('Go to templates page', 'bidxplugin' ); ?>
                                </a>
                            </p>

                        </div>
                        <a href="#addFiles" data-toggle="modal" class="btn btn-primary"><span class="fa fa-plus"></span> <?php _e('Add files', 'bidxplugin')?></a>

                        <div class="addFiles modal fade">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                        <h3><?php _e('Check the files you want to attach to your business plan', 'bidxplugin' ); ?></h3>
                                    </div>
                                    <div class="modal-body">
<?php
                                        echo do_shortcode( '[bidx app="media"]' );
?>
                                    </div>
                                    <div class="modal-footer">
                                        <a href="#" class="btn btn-primary btnSelectFile"><?php _e( 'Select file(s)', 'bidxplugin' ); ?></a>
                                        <a href="#" class="btn btn-default btnCancelSelectFile"><?php _e( 'Cancel', 'bidxplugin' ); ?></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

        </div><!-- /Documents -->
    </div>
    </div>
</div> <!-- tabs-content myBusinessSummary -->
</div>

    <!-- EDIT DOCUMENT MODAL -->
    <div class="js-edit-document modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body clearfix">
<?php
                    echo do_shortcode( '[bidx app="media"]' );
?>
                </div>
                <div class="modal-footer"></div>
            </div>
        </div>
    </div>

    <!-- SNIPPETS -->
    <div class="snippets hide">

        <!-- Existing company item -->
        <table>
            <tr class="companyItem">
                <td>
                    <div class="controls">
                        <div class="radio" >
                            <input type="radio" value="" id="radio-Company" name="companyList" data-toggle="radio" />
                            <label for="radio-Company"><span></span></label>
                        </div>
                    </div>
                </td>
                <td class="companyName"></td>
                <td class="registered"></td>
                <td class="employees"></td>
                <td class="location"></td>
            </tr>
        </table>

        <!-- Attachment -->
        <div class="attachmentItem col-md-6">
            <div class="media well">
                <div class="pull-left icons-rounded attachmentMissing"><i class="fa fa-question-circle text-primary-light"></i></div>
                <a class="pull-left documentLink img-cropper" href="#">
                    <div class="icons-rounded attachmentDefault"><i class="fa fa-file-text-o text-primary-light"></i></div>
                    <img class="media-object img-rounded documentImage">
                </a>
                <div class="media-body">
                    <strong class="media-heading documentName"></strong>
                    <div class="createdDateTime"></div>
                    <div class="purpose"></div>
                    <div class="documentType"></div>
                </div>
                <a href="#removeItem" class="btn btn-danger btn-sm btn-block clearboth top-margin-lineheight"><?php _e('Remove','bidxplugin'); ?></a>
                <!-- <a href="#editDocument" class="btn btn-block editDocumentProp"><?php _e( 'Edit document properties', 'bidxplugin' ); ?></a> -->
            </div>
        </div>

        <!-- Management Team Item -->
        <div class="managementTeamItem col-sm-6">
            <div class="well">
                <div class="row">
                    <!-- First Name -->
                    <div class="form-group col-sm-12">
                        <label><?php _e('First name','bidxplugin'); ?></label>
                        <input type="text" class="form-control" name="firstName" placeholder="<?php _e('Please enter the first name','bidxplugin'); ?>">
                    </div>

                    <!-- Last Name -->
                    <div class="form-group col-sm-12">
                        <label><?php _e('Last name','bidxplugin'); ?></label>
                        <input type="text" class="form-control" name="lastName" placeholder="<?php _e('Please enter the last name','bidxplugin'); ?>">
                    </div>

                    <!-- Role -->
                    <div class="form-group col-sm-12">
                        <label><?php _e('Role of the team member in this business','bidxplugin'); ?></label>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-tag"></i></span>
                            <input type="text" class="form-control" name="role" placeholder="<?php _e('Please type the role of the team member','bidxplugin'); ?>">
                        </div>
                    </div>

                    <!-- Expertise -->
                    <div class="form-group col-sm-12">
                        <label><?php _e('Describe relevant expertise of the team member','bidxplugin'); ?></label>
                        <textarea type="text" class="form-control" name="expertise" placeholder="<?php _e('Please describe relevant expertise of the team member','bidxplugin'); ?>"></textarea>
                    </div>

                    <!-- LinkedIn -->
                    <div class="form-group col-sm-12">
                        <label><?php _e('LinkedIn profile','bidxplugin'); ?> <small class="text-muted"><?php _e('Optional','bidxplugin'); ?></small></label>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-linkedin-square"></i></span>
                            <input type="text" class="form-control" name="linkedIn" placeholder="<?php _e('Please enter your LinkedIn profile URL','bidxplugin'); ?>" />
                        </div>
                    </div>

                    <!-- Profile picture -->
                    <div class="profilePictureControl form-group col-sm-12">
                        <label><?php _e('Picture','bidxplugin'); ?> <small class="text-muted"><?php _e('Optional','bidxplugin'); ?></small></label>
                        <div class="profilePictureWrapper hide-overflow">
                            <div class="profilePictureContainer"></div>
                        </div>
                        <a href="#changeProfilePicture" class="btn btn-primary"><?php _e('Upload picture', 'bidxplugin')?></a>
                    </div>
                </div>

                <a href="#removeItem" class="btn btn-danger btn-sm btn-block"><?php _e('Remove this team member','bidxplugin'); ?></a>
            </div>
        </div>
    </div>

</div><!-- /businesssummary -->
<?php
$this->isBuisnessSummary = true;
$this->render('../../mentor/templates/dashboard/main.phtml'); ?>

<script type="text/html" id="mentor-snippet">
<!--
        <div class="well media">
            <a class="pull-left" href="/member/%contactId%">
                %pictureUrl%
            </a>
            <div class="action">%action%</div>
            <div class="media-body">
                <a class="media-heading" href="/member/%contactId%"><strong>%contactName%</strong></a>

                <div>%professionalTitle%</div>
                <div>%country%</div>
                <div>
                    <span class="label bidx-label bidx-entrepreneur">%role_entrepreneur%</span>
                    <span class="label bidx-label bidx-mentor">%role_mentor%</span>
                    <span class="label bidx-label bidx-investor">%role_investor%</span>
                </div>

            </div>
        </div>
-->
</script>
<script type="text/html" id="empty-mentors">
<!--
    <div class="col-sm-12">
        <div class="well media">
            <div class="media-body">
            <?php _e('No matching mentors','bidxplugin')?>
            </div>
        </div>
    </div>
-->
</script>
<script type="text/html" id="empty-active-mentors">
<!--
    <div class="col-sm-12">
        <div class="well media">
            <div class="media-body">
            <?php _e('No current mentor relationship','bidxplugin')?>
            </div>
        </div>
    </div>
-->
</script>
<script type="text/html" id="active-mentor-action">
<!--
<a href="#" data-href="#mentoring/confirmInitiateMentoring/entityId=%entityId%&requestId=%requestId%&type=mentor&action=bpCancel" class="view viewRequestmentor btn btn-xs btn-danger pull-right label bidx-label btn-bidx-reject"><?php _e('Cancel request','bidxplugin');?></a>
-->
</script>
<script type="text/html" id="send-mentor-action">
<!--
<a href="#" data-href="#mentoring/confirmInitiateMentoring/entityId=%entityId%&mentorId=%mentorId%&initiatorId=%initiatorId%&type=mentor&action=bpSend" class="view viewRequestmentor btn btn-xs btn-success pull-right label bidx-label btn-bidx-send" ><?php _e('Request mentoring','bidxplugin');?></a>
-->
</script>
<script type="text/html" id="respond-mentor-action">
<!--
<a href="#" data-href="#mentoring/confirmInitiateMentoring/requestId=%requestId%&type=mentor&action=rejected&initiate=bp" class="view viewRequestmentor btn btn-xs btn-danger pull-right label bidx-label btn-bidx-ignore" ><?php _e('Ignore','bidxplugin');?></a>
<a href="#" data-href="#mentoring/confirmInitiateMentoring/requestId=%requestId%&type=mentor&action=accepted&initiate=bp" class="view viewRequestmentor btn btn-success pull-right label bidx-label btn-bidx-accept" ><?php _e('Accept','bidxplugin');?></a>

-->
</script>
<script type="text/html" id="load-mentor">
<!--
    <div class="col-sm-6 member%contactId%">
        <div class="viewLoadrequest alert alert-info text-center">
                <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e ('Loading active mentors', 'bidxplugin') ?>
        </div>
    </div>
-->
</script>
<script type="text/html" id="error-mentor">
<!--
    <div>
        <div class="viewLoadrequest alert alert-danger text-center">
            <?php _e ('Error loading mentor', 'bidxplugin') ?>
        </div>
    </div>
-->
</script>
