<?php

$businessSummary    = $this->data;
$progress           = $this -> completenessScore ? $this -> completenessScore : '0';

$businessSummaryBidxMeta = isset($businessSummary->bidxMeta)
    ? $businessSummary->bidxMeta
    : null;

$canEdit        = $this->exst($businessSummaryBidxMeta->bidxCanEdit, false);
$canRate        = $this->exst($businessSummaryBidxMeta->bidxCanRate, false);
$ratingCount    = $this->exst($businessSummaryBidxMeta->bidxRatingCount, 0);
$ratingAverage  = $this->exst($businessSummaryBidxMeta->bidxRatingAverage, null);
$entityStatus   = $this->exst($businessSummaryBidxMeta->bidxEntityStatus, '');

// get the enitities of the current user
$ownerId 		= $businessSummary->bidxMeta->bidxOwnerId;

$businessSummaryId = $businessSummaryBidxMeta->bidxEntityId;

// check, is access granted?
$hasAccess = false;

// To display Company Tab
//
$company    = $this->exst ($businessSummary->company);
$attachment = $this->exst ($businessSummary->attachment);
$tmpsummary = $this->exst($businessSummary->summary, null, false);
$currentYear = date("Y");

/*test data
$businessSummary->socialImpact = ["education"];
$businessSummary->envImpact = ["climateChangeReduction"];
$businessSummary->personalRole = "CEO";
$businessSummary->personalExpertise = "CEO stuff";
test data*/

?>
<div class="businessSummary anonymous">
<?php
            if ( $this->exst($businessSummaryBidxMeta->bidxEntityId) )
            {
?>
    <div class="businessCover">
        <div class="coverImageContainer">
<?php
            if ( $businessSummary->cover && $businessSummary->cover->document ):
?>
            <div class="coverImage">
                <img src="<?php echo $businessSummary->cover->document ?>" alt="Cover Image" style="position: relative; top: <?php echo $businessSummary->cover->top?>px">
            </div>
<?php
            endif;
?>
        </div>
<?php
            if ( $businessSummary->logo && $businessSummary->logo->document ):
?>
            <div class="logoImage">
                <img src="<?php echo $businessSummary->logo->document ?>" class="center-img" alt="Logo Image">
            </div>
<?php
            endif;
?>

    </div>

<?php
        $updatedDate    =   $this->getLocaleDate( $businessSummaryBidxMeta->bidxLastUpdateDateTime  );

?>
    <div class="bg-gray control-bar">


        <div class="bs-info hide-overflow">
            <div class="bs-cell main-padding pull-left hide"><i class="fa fa-line-chart"></i> <span class="hidden-xs"><?php echo _e('Completed', 'bidxplugin')?>:</span> <?php echo $progress; ?><span>%</span></div>
            <div class="bs-cell main-padding pull-left hidden-xs">
                <div class="rating-wrapper">
                    <div class="rating-no-score <?php echo !$ratingAverage ? '' : 'hide' ?>">
                        <span class="rating-score-text"><?php echo _e('No Score', 'bidxplugin'); ?></span>
                    </div>
                    <div class="rating-score <?php echo $ratingAverage ? '' : 'hide' ?>">
                        <i class="fa fa-star"></i>
                        <?php echo _e('Score', 'bidxplugin')?>: <span class="rating-average"><?php echo $ratingAverage ? $ratingAverage : "?"; ?></span>
                    </div>
                </div>
            </div>
            <div class="bs-cell main-padding pull-left"><i class="fa fa-refresh"></i> <span class="hidden-xs"><?php echo _e('Last Update', 'bidxplugin')?>:</span> <?php echo $updatedDate; ?></div>
<?php
            foreach ($businessSummary->financialSummaries as $key => $year)
            {
                if ( $key === $currentYear ) :
            ?>
                    <div class="bs-cell main-padding pull-left"><i class="fa fa-dollar"></i> <span class="hidden-xs"><?php echo _e('Finance Needed', 'bidxplugin')?>:</span> <?php echo number_format($year->financeNeeded, 0, '', '.'); ?></div>
            <?php
                endif;
            }
?>
        </div>


    </div>
    <br>

    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
            <h1>
                <?php echo $this->exst( $businessSummary->name, null, false ); ?>
                <small>&nbsp;<?php echo _e( 'by', 'bidxplugin' ); ?>&nbsp;
                    <a href="/member/<?php echo $this->exst( $businessSummaryBidxMeta->bidxOwnerId ); ?>"><?php echo $this->exst( $businessSummaryBidxMeta->bidxOwnerDisplayName ); ?></a>
                </small>
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
            <h4><?php echo $this->exst( $businessSummary->slogan, null, false ); ?></h4>
        </div>    
    </div>
    <div class="row">
<?php
    if ( $tmpsummary )
    {
?>
        <div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
            <h3 class="text-uppercase"><?php _e('In a few words', 'bidxplugin')?></h3>
            <div>
<?php
                echo $tmpsummary;
?>
            </div>
        </div>

<?php
    }
?>  
    </div>
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
<?php
            $videoUrl = $this->exst($businessSummary->externalVideoPitch);
            $parsedVideo = $this->parseVideos( $videoUrl );

            if ( $parsedVideo )
            {
                $theVideo .= '<div class="video-wrapper embed-responsive embed-responsive-16by9 bottom-margin-lineheight">'.$parsedVideo[0]['videoplayer'].'</div>';
            }

            echo $theVideo;
?>
        </div>
    </div>





    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">

<?php
            $rowValues = array (

                __('Stage of business','bidxplugin')
                    => $this->getStaticVal( 'stageBusiness', $this->exst($businessSummary->stageBusiness)),

                __('Countries of business','bidxplugin')
                    => $this->getMultiValues( $this->exst($businessSummary->countryOperation), ', ', 'country' ),

                __('Industry','bidxplugin')
                    => $this->getMultiValues( $this->exst($businessSummary->industry), '<br> ','industry'),

                __('Social impact','bidxplugin') => $this->getMultiValues( $this->exst($businessSummary->socialImpact), ', ', 'socialImpact' ),
                    
                __('Environmental impact','bidxplugin') => $this->getMultiValues( $this->exst($businessSummary->envImpact), ', ', 'envImpact' )
            );
?>

            <h3 class="text-uppercase"><?php _e('Basic information', 'bidxplugin')?></h3>
<?php
            echo $this->tableRow( $rowValues );

            if ( $attachment )
            {
?>
                <h4>Has attachment</h4>
<?php
            }
?>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
<?php
            $rowValues = array
            (
                __('Role of the entrepreneur','bidxplugin') => $this->exst($businessSummary->personalRole, null, false),
                __('Expertise of the entrepreneur','bidxplugin') => $this->exst($businessSummary->personalExpertise, null, false)
            );

            if ( $this->checkEmpty( $rowValues ) ) :
?>
                <h3 class="text-uppercase"><?php _e('The Team', 'bidxplugin')?></h3>
<?php
                echo $this->tableRow ( $rowValues );
            endif;

            if ( $this->exst( $businessSummary->managementTeam ) ) :
?>
            <h4 class="text-uppercase"><?php echo _e('Supporting members of management team', 'bidxplugin')?></h4>
            <table class="table table-bottom-border">
<?php
            foreach ( $businessSummary->managementTeam as $key => $member)
            {
?>
                <tr><td>
                <div class="media team-member">
<?php
                    if ( $member->profilePicture->document )
                    {
?>
                        <div class="bidx-profilepicture pull-left team-picture">
                            <div class="img-cropper">
                                <img src="<?php echo $member->profilePicture->document ?>" alt="">
                            </div>
                        </div>
<?php
                    }
                    else
                    {
?>
                        <div class="pull-left">
                            <div class="icons-rounded pull-left"><i class="fa fa-user text-primary-light"></i></div>
                        </div>
<?php
                    }
?>
                    <div class="media-body">
                        <div class="media-heading">
                            <strong><?php echo $member->firstName . ' ' . $member->lastName; ?></strong>
<?php
                            if ( $member->linkedIn ) :
?>
                                <div class="team-linkedin pull-right">
                                    <a target="_blank" class="btn btn-linkedin btn-xs" href="<?php echo $member->linkedIn; ?>">
                                        <i class="fa fa-linkedin-square"></i>
                                        <?php echo _e('LinkedIn', 'bidxplugin')?> </a>
                                </div>
<?php
                            endif;
?>
                        </div>
                        <div class="media-body">
                            <div class="team-role">
                                <em><?php echo $member->role; ?></em>
                            </div>
                            <div class="team-expert">
                                <?php echo $member->expertise; ?>
                            </div>
                        </div>
                    </div>
                </div>
                </td></tr>
<?php
            }
?>
            </table>
<?php
            endif;
?>
        </div>
    </div>

    <div class="row">
<?php
        if ( $this->exst( $company )) 
        {
        $countryOperationSpecifics = isset ($company->countryOperationSpecifics) ? $company->countryOperationSpecifics : NULL;
?>
        <div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
            <h3 class="text-uppercase"><?php _e('Company Details', 'bidxplugin')?></h3>
<?php
                $companyWebsite = null;

                if ( $this->exst( $company->website ) ) {
                    $companyWebsite = sprintf( '<a href="%1$s" target="_blank">%1$s</a>', $this->exst($company->website) );
                }

                if ( !empty( $company->registered ) )
                {
                    $statutoryAddress = $this->exst( $company->statutoryAddress );

                    $arStatutoryAddress = array();
                    if ( $this->exst( $statutoryAddress->streetNumber ) ) { $arStatutoryAddress[] = $statutoryAddress->streetNumber; }
                    if ( $this->exst( $statutoryAddress->street ) )       { $arStatutoryAddress[] = $statutoryAddress->street . ', '; }
                    if ( $this->exst( $statutoryAddress->postalCode ) )   { $arStatutoryAddress[] = $statutoryAddress->postalCode; }
                    if ( $this->exst( $statutoryAddress->neighborhood ) ) { $arStatutoryAddress[] = $statutoryAddress->neighborhood; }

                    $arStatutoryCityCountry = array();
                    if ( $this->exst( $statutoryAddress->country ) )      { $arStatutoryCityCountry[] = $this->getStaticVal( 'country', $statutoryAddress->country ); }
                    if ( $this->exst( $statutoryAddress->cityTown ) )     { $arStatutoryCityCountry[] = $statutoryAddress->cityTown; }

                }

            $rowValues = array
            (
                __('Company name','bidxplugin') => $this->exst($company->name),
                __('Company website','bidxplugin') => $companyWebsite,
                __('Registered','bidxplugin') => $this->exst($company->registered) == true ? __('Yes','bidxplugin') : __('No','bidxplugin'),
                __('Legal form of business','bidxplugin') => $this->getStaticVal( 'legalForm', $this->exst($company->legalFormBusiness) ),
                __('Statutory country, city','bidxplugin') => $arStatutoryCityCountry ? implode( ', ', $arStatutoryCityCountry ) : NULL,
                __('Statutory address','bidxplugin') => $arStatutoryAddress ? implode( ' ', $arStatutoryAddress ) : NULL
            );

            if ( $this->checkEmpty( $rowValues ) ) :
                echo $this->tableRow ( $rowValues );
            endif;

            if ( $countryOperationSpecifics )
            {
                $header = array (
                    __('Country','bidxplugin') => 'country',
                    __('Company trade name','bidxplugin') => 'companyTradeName',
                    __('Permit or licences','bidxplugin') => 'permitsLicencesObtained',
                    __('Company Address','bidxplugin') => 'companyAddress'
                );

                $countryOperationSpecificsHtml = $this->addTableRows( $header, $countryOperationSpecifics, 'table table-bordered table-company', '', array('permitsLicencesObtained' => 'hidden-xs'), array( 'permitsLicencesObtained', 'country', 'companyAddress' ) );

                $rowValues = array ( __('Country Operation Specifics','bidxplugin') => $countryOperationSpecificsHtml );

                echo $this->addRowsWithLabelBelow ( 'col-sm-12', 'col-sm-12', $rowValues, array ( 'tag_label' => 'h4', 'class_label' => 'text-uppercase' ) );
            }
        }
?>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-4 col-sm-offset-4 big-padding-vertical">
            <a href="/join" class="btn btn-lg btn-block btn-secondary"><?php echo _e( 'Access business summary', 'bidxplugin' ); ?></a>
        </div>
    </div>


<?php
            }
?>


</div>
