<?php

$businessSummary = $this->data;

$financialSummariesItem = <<<EOT
    <div class="financialSummariesItem {{extraItemClasses}}" data-year="{{year}}">
        <div class="fs-cell fs-header">

            <div class="fs-header-controls-left">
                <a href="#prev" class="btnPrev"><span class="fui-arrow-left"></span></a>
                <a href="#addPreviousYear" class="btnAddPrev"><i class="fui-plus-inverted"></i></a>
            </div>

            <div class="fs-content">
                <header class="year">{{year}}</header>
                <p class="yearLabel">{{year_label}}</p>
            </div>

            <div class="fs-header-controls-right">
                <a href="#next" class="btnNext"><span class="fui-arrow-right"></span></a>
                <a href="#addNextYear" class="btnAddNext"><i class="fui-plus-inverted"></i></a>
            </div>
        </div>

        <div class="fs-cell fs-section-header"></div>

        <!-- Sales revenues -->
        <div class="fs-cell fs-row control-group">
            <label class="fs-cell-label">{{lblSalesRevenues}}</label>
            <div class="controls view viewEdit">
                <input type="text" name="salesRevenue[{{year}}]">
            </div>
            <div class="view viewShow value fs-content">
                <span>{{salesRevenue}}</span>
            </div>
        </div>

        <!-- Operational Costs -->
        <div class="fs-cell fs-row control-group">
            <label class="fs-cell-label">{{lblOperationalCosts}}</label>
            <div class="controls view viewEdit">
                <input type="text" name="operationalCosts[{{year}}]">
            </div>
            <div class="view viewShow value fs-content">
                <span>{{operationalCosts}}</span>
            </div>
        </div>

        <!-- Operational Costs -->
        <div class="fs-cell fs-row">
            <label class="fs-cell-label">{{lblTotalIncome}}</label>
            <div class="totalIncome value fs-content">
                <span class="view viewEdit">-</span>
                <span class="view viewShow">{{totalIncome}}</span>
            </div>
        </div>

        <div class="fs-cell fs-section-header"></div>

        <!-- Finance Needed -->
        <div class="fs-cell fs-row control-group">
            <label class="fs-cell-label">{{lblFinanceNeeded}}</label>
            <div class="controls view viewEdit">
                <input type="text" name="financeNeeded[{{year}}]">
            </div>
            <div class="view viewShow value fs-content">
                <span>{{financeNeeded}}</span>
            </div>
        </div>

        <div class="fs-cell fs-section-header"></div>

        <!-- Number Of Employees -->
        <div class="fs-cell fs-row control-group">
            <label class="fs-cell-label">{{lblNumberOfEmployees}}</label>
            <div class="controls view viewEdit">
                <input type="text" name="numberOfEmployees[{{year}}]">
            </div>
            <div class="view viewShow value fs-content">
                <span>{{numberOfEmployees}}</span>
            </div>
        </div>

    </div><!-- /financialSummariesItem -->
EOT;

$financialSummaries = $this->exst( $businessSummary->financialSummaries );

$hasYears       = false;
$hasPrevYear    = false;
$hasNextYear    = false;

$lastYear       = NULL;
$firstYear      = NULL;

$nrPrevYears    = 0;
$nrNextYears    = 0;

$curYear        = date( 'Y' );

// The financial summary year template exists of two types of variables, dynamic and
//
$financialSummariesItemTranslations = array(
    '{{lblSalesRevenues}}'         => __('Sales revenues','bidxplugin'),
    '{{lblOperationalCosts}}'      => __('Operational costs','bidxplugin'),
    '{{lblTotalIncome}}'           => __('Total income','bidxplugin'),
    '{{lblFinanceNeeded}}'         => __('Finance needed','bidxplugin'),
    '{{lblNumberOfEmployees}}'     => __('Number of employees','bidxplugin')
);

if ( $financialSummaries ) {

    $years      = get_object_vars( $financialSummaries );

    if ( $years && count( $years )) {

        $hasYears = true;

        ksort( $years );

        // Find the last year
        //
        end( $years );
        $lastYear = key( $years );
        reset( $years );
        $firstYear = key( $years );

        $nrPrevYears = $curYear - $firstYear;
        $nrNextYears = $lastYear - $curYear;

        foreach( $years as $year => $yearItem ) {
            $yearDiff = $curYear - $year;

            if ( $yearDiff > 0 )
            {
                $hasPrevYear = true;
            }

            if ( $yearDiff < 0 )
            {
                $hasNextYear = true;
            }
        }
    }
}

// No years? Create a dummy minimal set
//
if ( $hasYears == false ) {

    $hasYears   = true;

    $latstYear  = $curYear;
    $firstYear  = $curYear;

    $years = array( $curYear => (object)array(
        'financeNeeded'         => '-',
        'totalIncome'           => '-',
        'numberOfEmployees'     => '-',
        'operationalCosts'      => '-',
        'salesRevenue'          => '-'
    ) );
}

?>
<div class="financialSummary clearfix">

    <div class="fs-col-labels">
        <div class="fs-cell fs-header">
            <div class="pull-right fs-controls">
                <a href="#prev" class="btnPrev <?php echo ( $hasPrevYear ? '' : 'disabled' ); ?>"><span class="fui-arrow-left"></span></a>
            </div>
            <div class="fs-content"><strong><?php _e( 'Currency in: US Dollars', 'bidxplugin' ); ?></strong></div>
        </div>

        <!-- Section: INCOME STATEMENT -->
        <div class="fs-cell fs-section-header">
            <div class="fs-content"><strong><?php _e('Income statement','bidxplugin'); ?></strong></div>
        </div>

        <div class="fs-cell fs-row">
            <div class="fs-content"><?php _e( 'Sales revenues','bidxplugin'); ?></div>
        </div>

        <div class="fs-cell fs-row">
            <div class="fs-content"><?php _e( 'Operational costs','bidxplugin'); ?></div>
        </div>

        <div class="fs-cell fs-row">
            <div class="fs-content"><strong><?php _e( 'Total income','bidxplugin'); ?></strong></div>
        </div>

        <!-- Section: FINANCE NEEDED -->
        <div class="fs-cell fs-section-header">
            <div class="fs-content"><strong><?php _e( 'Finance needed','bidxplugin'); ?></strong> (<?php _e('from external financiers in US Dollars','bidxplugin'); ?>)</div>
        </div>

        <div class="fs-cell fs-row">
            <div class="fs-content"><?php _e( 'Needed','bidxplugin'); ?></div>
        </div>

        <!-- Section: NUMBER OF EMPLOYEES -->
        <div class="fs-cell fs-section-header">
            <div class="fs-content"><strong><?php _e( 'Number of employees','bidxplugin'); ?></strong> (<?php _e('being directly paid in this business','bidxplugin'); ?>)</div>
        </div>

        <div class="fs-cell fs-row">
            <div class="fs-content"><?php _e( 'Numbers','bidxplugin'); ?></div>
        </div>

    </div><!-- /col-label -->

    <div class="fs-col-years clearfix">

        <div class="financialSummariesItem addItem <?php echo ( ( $hasPrevYear && $nrNextYears >= 1 ) ? 'hide' : '' ); ?>">

            <!-- EDIT -->
            <div class="view viewEdit">
                <p class="addYear">
                    <a href="#addPreviousYear"><i class="fui-plus-inverted"></i> <?php _e( 'Add previous year','bidxplugin' ); ?></a>
                </p>
            </div><!-- /EDIT -->

            <!-- SHOW -->
            <div class="view viewShow">
                <p class="noMoreYears"><?php _e( 'No earlier years', 'bidxplugin' ); ?></p>
            </div><!-- /SHOW -->

        </div>
<?php
    if ( $hasYears ) {

        $count = 0;

        // Only display curYear - 1, curYear and curYear +1
        //
        foreach( $years as $year => $yearItem ) {

            $extraItemClasses = array();

            $yearDiff = $curYear - $year;

            if ( ( $hasNextYear && $yearDiff > 1 ) || ( $yearDiff < -1 && $hasPrevYear ) )
            {
                $extraItemClasses[] = "hide";
            }

            if ( $year < $curYear ) {
                $yearLabel = __('Actuals','bidxplugin');
            } else if ( $year > $curYear ) {
                $yearLabel = __('Forecast','bidxplugin');
            } else {
                $yearLabel = __('Current year','bidxplugin');

                // Start with the current year being the selected one
                //
                $extraItemClasses[] = "selected";
            }

            // Add first and last markers on the items
            //
            if ( $year == $firstYear ) {
                $extraItemClasses[] = "first";
            }

            if ( $year == $lastYear ) {
                $extraItemClasses[] = "last";
            }


            $tokens = array_merge( $financialSummariesItemTranslations, array(
                // Data values
                //
                '{{year}}'                  => $year,
                '{{year_label}}'            => $yearLabel,
                '{{financeNeeded}}'         => $yearItem->financeNeeded,
                '{{totalIncome}}'           => $yearItem->totalIncome,
                '{{numberOfEmployees}}'     => $yearItem->numberOfEmployees,
                '{{operationalCosts}}'      => $yearItem->operationalCosts,
                '{{salesRevenue}}'          => $yearItem->salesRevenue,
                '{{extraItemClasses}}'      => implode( ' ', $extraItemClasses )
            ));

            echo $this->replaceMessageTokens( $financialSummariesItem, $tokens );

            $count++;
        }
    }
?>
        <div class="financialSummariesItem addItem <?php echo ( ( $hasNextYear && $nrPrevYears >= 1 )  ? 'hide' : '' ); ?>">

            <!-- EDIT -->
            <div class="view viewEdit">
                <p class="addYear">
                    <a href="#addNextYear"><i class="fui-plus-inverted"></i> <?php _e('Add year forward','bidxplugin'); ?></a>
                </p>
            </div><!-- /EDIT -->

            <!-- SHOW -->
            <div class="view viewShow">
                <p class="noMoreYears"><?php _e('No later years','bidxplugin'); ?></p>
            </div><!-- /SHOW -->
        </div>
    </div><!-- /fs-col-years -->

    <div class="fs-col-right">
        <div class="fs-controls">
            <a href="#next" class="btnNext <?php echo ( $hasNextYear ? '' : 'disabled' ); ?>"><span class="fui-arrow-right"></span></a>
        </div>
    </div>

    <!-- SNIPPETS -->
    <div class="snippets hide">
<?php
        // Dump the item as a snippet, pull it through the replaceMessageTokens to have the template
        // placeholders be replaced with empty values
        //
        echo $this->replaceMessageTokens( $financialSummariesItem, $financialSummariesItemTranslations );
?>
    </div>

</div><!-- /financialSummary -->
