  <div id="resetpassword" class="block-odd mainState mainStateResetpassword">

    <h1><?php echo _e('Reset password','bidxplugin'); ?></h1>

    <form id="frmResetpassword" action="/">
        <div class="control-group">
            <label class="control-label"><?php _e('Email address','bidxplugin');?></label>

            <div class="form-group">
                <input class="form-control" type="email" name="username" placeholder="<?php _e('Enter your email address','bidxplugin');?>" />
            </div>
        </div>
        <div class="error-separate"></div>
        <button type="submit" class="btn btn-primary"><?php _e('Send me a new password','bidxplugin');?></button>
        <br>
        <br>
        <p>
            <?php _e('Did you remember your password again?.','bidxplugin');?><br/>
            <?php _e('Click <a href="#auth/login">here</a> to go to login.','bidxplugin');?>
        </p>
    </form>

    <div class="resetpasswordSuccess">
        <h3><?php _e('Email has been sent','bidxplugin');?></h3>
        <p>
            <?php _e('An email with instructions on how to change your password has been sent to your email address.','bidxplugin');?> <br>
            <?php _e('If you do not see the email in your inbox please check your spam box.','bidxplugin');?>
        </p>
        <p>
            <?php printf( __('If the message does not appear in your spam box within an hour please notify us <a href="%s">here</a>.', 'bidxplugin'), "/contact"  ); ?>
        </p>
            <?php printf( __('Click <a href="%s">here</a> to go to homepage.', 'bidxplugin'), "/"  ); ?>
        </p>
    </div>

</div>

