<!-- 
    Search startpage.
    Single page application that is setup
-->	

<div>


    <div class="row-fluid">
        <div class="span12"><h4>Nr of  members <?php echo $this->data->memberProfileCount;?></h4></div>
        <div class="span12"><h4>Nr of  investors <?php echo $this->data->investorCount;?></h4></div>
        <div class="span12"><h4>Nr of  entrepreneur <?php echo $this->data->entrepreneurCount;?></h4></div>
    </div>
    <br /><br /><br /><br />
    <div class="row-fluid">
        <div class="span8">
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <th>Select</th>
                        <th>First + Last name</th>
                        <th>Location</th>
                        <th>Member since</th>
                    </tr>

                    <tr>
                        <td>
                            <span class="label"><input type="checkbox"/></span>
                        </td>
                        <td>
                            <span class="label">Altaf Samnani</span>
                        </td>
                        <td>
                            <span class="label">India</span>
                        </td>
                        <td>
                            <span class="label">01-13-2010</span>
                        </td>
                   </tr>
                   <tr>
                        <td>
                            <span class="label"><input type="checkbox"/></span>
                        </td>
                        <td>
                            <span class="label">Jaap Gorup</span>
                        </td>
                        <td>
                            <span class="label">The Netherlands</span>
                        </td>
                        <td>
                            <span class="label">01-13-2010</span>
                        </td>
                   </tr>
                   <tr>
                        <td>
                            <span class="label"><input type="checkbox"/></span>
                        </td>
                        <td>
                            <span class="label">Iratxe Florez</span>
                        </td>
                        <td>
                            <span class="label">Spain</span>
                        </td>
                        <td>
                            <span class="label">01-13-2010</span>
                        </td>
                   </tr>
                   <tr>
                        <td>
                            <span class="label"><input type="checkbox"/></span>
                        </td>
                        <td>
                            <span class="label">Thierry Sanders</span>
                        </td>
                        <td>
                            <span class="label">The Netherlands</span>
                        </td>
                        <td>
                            <span class="label">01-13-2010</span>
                        </td>
                   </tr>
                   </tbody>
            </table>
        </div>
    </div>

   </div>