<!-- 
    Search startpage.
    Single page application that is setup
-->	

<div id="group-dashboard">
    <div class="row-fluid">
        <div class="span8">
            <h2>Group growth</h2>
        </div>

    </div>
    <div class="row-fluid">
        <div class="span6">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Members and business</th>
                        <th>Amount</th>
                        <!-- <th>Lastaddition</th> -->
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Members</td>
                        <td><?php echo $this->data->memberProfileCount; ?></td>

                    </tr>
                    <tr>
                        <td>Entrepreneurs</td>
                        <td><?php echo $this->data->entrepreneurCount; ?></td>
                    </tr>
                    <tr>
                        <td>Investors</td>
                        <td><?php echo $this->data->investorCount; ?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="row-fluid">
    <section class="span12 well dashboard">
        <!-- ************************* utility views *********************************** -->
        <article class="view viewLoad"><?php _e ('Loading...', 'bidxplugin') ?></article>

        <article class="view viewList">
            <div class="row-fluid">
                <div class="span12">
                    <h2>Who is joining your group?</h2>
                </div>

                <!-- Latest member data -->
                <div class="span12 latest-member">
                    <ul class="listheader ">
                        <li class="mediaheader" >
                            <div class="row-fluid">
                            <div class="span2 pull-left check">
                                <label class="checkbox">
                                    <input type="checkbox" data-toggle="checkbox" class="messagesCheckall" value="">
                                </label>
                            </div>
                            <div class="span10 headerbody">
                                <div class="row-fluid">
                                    <div class="span4"><strong><span class="placeholder user"><?php _e ('First + Last name', 'bidxplugin') ?></span></strong></div>
                                    <div class="span2"><strong><span class="placeholder userId"/><?php _e ('Location', 'bidxplugin') ?></span></strong></div>
                                    <div class="span2"><strong><span class="placeholder membersince"/><?php _e ('Member since', 'bidxplugin') ?></span></strong></div>
                                    <div class="span2"><strong><span class="placeholder role"/><?php _e ('Role', 'bidxplugin') ?></span></strong></div>
                                    <div class="span2"><strong><span class="placeholder lastlogin"/><?php _e ('Last Login', 'bidxplugin') ?></span></strong></div>
                                </div>
                            </div>
                            </div>
                        </li>
                    </ul>
                   
                        <!-- MESSAGE LIST -->
                        <ul class="list media-list ">
                            <li class="media">
                                <div class="pull-left check"></div>
                                <div class="pull-left">
                                    <?php _e ('Loading...', 'bidxplugin') ?>
                                </div>
                            </li>

                        </ul>
                   
                    <div class="pagination">
                        <ul>
                            <li class="previous"><a class="fui-arrow-left" href="#fakelink"></a></li>
                            <li class="active"><a href="#fakelink">1</a></li>
                            <li><a href="#fakelink">2</a></li>
                            <li><a href="#fakelink">3</a></li>
                            <li><a href="#fakelink">4</a></li>
                            <li><a href="#fakelink">5</a></li>
                            <li><a href="#fakelink">6</a></li>
                            <li><a href="#fakelink">7</a></li>
                            <li><a href="#fakelink">8</a></li>
                            <li><a href="#fakelink">9</a></li>
                            <li><a href="#fakelink">10</a></li>
                            <li class="next"><a class="fui-arrow-right" href="#fakelink"></a></li>
                        </ul>
                    </div>
                </div>               
            </div>
            <div class="row-fluid">
                <div class="span4 offset8">
                    <a class="btn btn-primary" href="#dashboard/dashboardCompose">Say hi to new members</a>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span12">
                    You have received 24 New Emails <a href="/mail"> Click here</a> to visit
                </div>
            </div>
        </article>

        <article class="modalView modalDashboardCompose">
            <div  id="dashboard" class="mainState mainStateDashboard">                <!-- Modal -->
                <div class="modal hide fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h3 id="myModalLabel"><?php _e ('Delete message', 'bidxplugin') ?></h3>
                    </div>
                    <div class="modal-body">
                        <form action="">
                            <div class="row-fluid">
                                <div class="control-group">
                                    <div class="input-prepend">

                                        <span class="add-on">Recipients</span>
                                        <div class="controls">
                                            <div class="bidx-tagsinput-container">
                                                <input type="text" autocomplete="off" name="contacts"      class="bidx-tagsinput enclosed defer"  data-bidxdatakey="members" placeholder="<?php _e ('Add Recipient') ?>">
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row-fluid">
                                <div class="control-group">
                                    <div class="input-prepend">

                                        <span class="add-on">Subject</span>
                                        <div class="controls">
                                            <input type="text" name="subject" placeholder="<?php _e ('Your subject goes here...', 'bidxplugin') ?>">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row-fluid">
                                <div class="control-group">
                                    <div class="controls">
                                        <textarea name="content" placeholder="<?php _e ('Please type your message here..', 'bidxplugin') ?>"></textarea>
                                    </div>
                                </div>

                            </div>
                            <div class="pull-left">

                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <a class="btn" data-dismiss="modal" aria-hidden="true"><?php _e ('Close', 'bidxplugin') ?></a>
                        <a class="btn btn-primary" href="/mail/#mail/%section%/delete/"><?php _e ('Delete message', 'bidxplugin') ?></a>
                        <a href="/mail/#mail/discardConfirm" class="btn compose-cancel"><?php _e ('Discard message') ?></a>
                        <button type="submit" class="btn btn-primary compose-submit"><?php _e ('Send message', 'bidxplugin') ?></button>

                    </div>
                </div>
            </div>
        </article>
    </section>
</div>
</div>
<script type="text/html" id="dashboard-listitem">
    <!--
    <li class="media" >
    <div class="row-fluid">
    <div class="span2 pull-left check">
    <label class="checkbox">
    <input type="checkbox" data-toggle="checkbox"  value="" data-id="">
    </label>
    </div>
    <div class="span10 media-body">
    <div class="row-fluid">
    <div class="span4"><h6 class="media-heading"><span class="placeholder user"><?php _e ('SENDER UNKNOWN IN API', 'bidxplugin') ?></span></h6></div>
    <div class="span2"><span class="placeholder location"/></div>
    <div class="span2"><span class="placeholder membersince"/></div>
    <div class="span2"><span class="placeholder role"/></div>
    <div class="span2"><span class="placeholder lastlogin"/></div>
    </div>
    <div class="subject">
    <span class="placeholder subject"/>
    </div>
    </div>
    </li>
    -->
</script>

<script type="text/html" id="dashboard-empty">
    <!--
    <li class="media">
    <div class="pull-left check"></div>
    <div class="">
    <?php _e ('No messages available') ?>
    </div>
    </li>
    -->
</script>
