<div class="dashboard">
    <h1>Investor dashboard</h1>

    <div class="row-fluid ">
        <div class="span12 well">
            <h2>Recommended business</h2>
            <p>These are the groups you have created. Click on the name of the group to edit appearances, create content or administrate members</p>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Entrepeneur</th>
                        <th>Country</th>
                        <th>Industry</th>
                        
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <a data-toggle="collapse" data-target="#table1-row1-col1" class="accordion-toggle">
                                Business Proposal A
                            </a>
                        </td>
                        <td>
                            <a data-toggle="collapse" data-target="#table1-row1-col2" class="accordion-toggle">
                                First Last Name
                            </a>
                        </td>
                        <td>Ecuador</td>
                        <td>Green energy</td>
                    </tr>
                    <tr>
                        <td colspan="5" class="detailRow">
                            <div class="accordian-body collapse" id="table1-row1-col1">
                                <div class="row-fluid">
                                    <div class="span6">
                                        <ul class="unstyled">
                                           <li>
                                                <label>Business proposal</label> 
                                                Name business proposal
                                            </li>
                                           <li>
                                                <label>Entrepreneur</label> 
                                                First + Last name
                                            </li>
                                           <li>
                                                <label>Industry</label> 
                                                Industry
                                            </li>
                                           <li>
                                                <label>Product</label> 
                                                Product
                                            </li>
                                           <li>
                                                <label>Country</label> 
                                                Country
                                            </li>
                                           <li>
                                                <label>Investment needed</label> 
                                                Amount
                                            </li>
                                           <li>
                                                <label>Business stage</label> 
                                                Stage
                                            </li>
                                           <li>
                                                <label>Impact</label> 
                                                Impact
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="span6">
                                        <figure style="width:200px; height:200px; background-color:grey; color:white">Logo company</figure>
                                    </div>
                                    <div class="pull-right">
                                        <a href="#">View Proposal</a>
                                    </div>
                                </div>
                            </div>  
                        </td>
                    </tr>
                    <tr>
                        <td colspan="5" class="detailRow">
                            <div class="accordian-body collapse" id="table1-row1-col2">
                                <div class="row-fluid">
                                    <div class="span12">
                                        <h4>Entrepeneur Profile</h4>
                                        <ul class="unstyled">
                                           <li>
                                                <label>Entrepreneur</label> 
                                                First + Last name
                                            </li>
                                           <li>
                                                <label>Industry</label> 
                                                Industry
                                            </li>
                                           <li>
                                                <label>Product</label> 
                                                Product
                                            </li>
                                           <li>
                                                <label>Country</label> 
                                                Country
                                            </li>
                                           <li>
                                                <label>Investment needed</label> 
                                                Amount
                                            </li>
                                           <li>
                                                <label>Business stage</label> 
                                                Stage
                                            </li>
                                           <li>
                                                <label>Impact</label> 
                                                Impact
                                            </li>
                                        </ul>
                                    </div>
                                    
                                    <div class="pull-right">
                                        <a href="#">View full profile</a>
                                    </div>
                                </div>
                            </div>  
                        </td>
                    </tr>                    
                    <tr>
                        <td>
                            Business Proposal B

                        </td>
                        <td>First Last Name</td>
                        <td>Peru</td>
                        <td>Green energy</td>
                    </tr>
                    <tr>
                        <td>Business Proposal C</td>
                        <td>First Last Name</td>
                        <td>Colombia</td>
                        <td>Green energy</td>
                    </tr>
                    <tr>
                        <td>Business Proposal D</td>
                        <td>First Last Name</td>
                        <td>Peru</td>
                        <td>Green energy</td>
                    </tr>
                    <tr>
                        <td>Business Proposal E</td>
                        <td>First Last Name</td>
                        <td>Mexico</td>
                        <td>Green energy</td>
                    </tr>
                    <tr>
                        <td>Business Proposal F</td>
                        <td>First Last Name</td>
                        <td>Brazil</td>
                        <td>Green energy</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row-fluid">
       
        <div class="span12 well">
            <h2>Businessses contacted</h2>
            <p></p>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Entrepreneur</th>
                        <th>Location</th>
                        <th>Industry</th>
                        <th>Full access request</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            Business Proposal A
                        </td>
                        <td>First Last name</td>
                        <td>Ecuador</td>
                        <td>Green energy</td>
                        <td>
                            <a  data-toggle="collapse" data-target="#table2-row1" class="accordion-toggle">
                            Pending
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="5" class="detailRow">
                            <div class="accordian-body collapse" id="table2-row1">
                                <div class="row-fluid detailContent">
                                    <div class="span12">
                                        <h3>Acces requests</h3>
                                        <div class="alert alert-info">
                              
                                            Subject: Request to view full details of your plan <BR>
                                            

                                            To: Entrepreneur <BR>

                                            Date: dd/mm/yyyy <BR>

                                        </div>

                                    </div>
                                      <div class="pull-right">
                                        <a href="#">Send new email</a>
                                    </div>
                                </div>
                            </div>  
                        </td>
                    </tr>                
                    <tr>
                        <td>Business Proposal B</td>
                        <td>First Last name</td>
                        <td>Peru</td>
                        <td>Green energy</td>
                        <td>
                            <a  data-toggle="collapse" data-target="#table2-row2" class="accordion-toggle">Granted</a>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="5" class="detailRow">
                            <div class="accordian-body collapse" id="table2-row2">
                                <div class="row-fluid detailContent">
                                    <div class="span12">
                                        <h3>Acces requests</h3>
                                        <div class="alert alert-info">
                              
                                            Subject: Request to view full details of your plan <BR>
                                            

                                            To: Entrepreneur <BR>

                                            Date: dd/mm/yyyy <BR>

                                        </div>
                                        <div class="alert alert-info">
                              
                                            Subject: Access is granted <BR>

                                            To: Entrepreneur <BR>

                                            Date: dd/mm/yyyy <BR>

                                        </div>
                                    </div>
                                      <div class="pull-right">
                                        <a href="#">Send new email</a>
                                    </div>
                                </div>
                            </div>  
                        </td>
                    </tr>                                    
                    <tr>
                        <td>Business Proposal 1</td>
                        <td>First last name</td>
                        <td>Mexico</td>
                        <td>Green energy</td>
                        <td>Denied</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="row-fluid">
       
        <div class="span12 well">
            <h2>My investor accrediation status</h2>
            <p></p>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Group name</th>
                        <th>Location</th>
                        <th>Nr of members</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            GroupNameX
                        </td>
                        <td>Ecuador</td>
                        <td>Entrepeneurs</td>
                        <td>
                            <a  data-toggle="collapse" data-target="#table3-row1" class="accordion-toggle">
                            Pending
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="5" class="detailRow">
                            <div class="accordian-body collapse" id="table3-row1">
                                <div class="row-fluid detailContent">
                                    <div class="span6">
                                        Groupname<br/>
                                        Slogan<br/>
                                        Industry<br/>
                                        Impact<br/>
                                        <A href="#">Contact group admin</a><br/>
                                        <a href="#">Search for business in this group</a></br>
                                    </div>
                                    <div class="span6">
                                        <figure style="width:200px; height:200px; background-color:grey; color:white">Logo company</figure>
                                        <div class="row-fluid">
                                        <div class="span6"><a href="#">Leave this group</a></div>
                                        <div class="span6"><a href="#">Search groups</a></div>
                                        </div>
                                        
                                    </div>
                                </div>
                            </div>  
                        </td>
                    </tr>                
                  
                </tbody>
            </table>
        </div>
    </div>

    
</div>