

<div class="dashboard">
    <h1>My dashboard</h1>
    <div class="row-fluid">

        <div class="span6 well bidx-tile">
            <div class="bidx-tile-wrap">
                <h2 class="popover-title">My entrepreneur dashboard</h2>
                <div class="bidx-tile-body">
                <!-- TILE BODY GOES HERE -->
                    <p>
                        See here the business proposals you have created in the various groups you are a member of. Click on the title to view the proposal. You can edit it from the proposal page.
                    </p>

                    <div class="accordion entrepeneur-widget">
                        <div class="accordion-group">
                            <div class="accordion-heading">
                                <a class="accordion-toggle" data-toggle="collapse" data-parent=".entrepeneur-widget" href=".entrepeneur-body-1">
                                    Business Proposal 1
                                    <i class="fui-triangle-down-small pull-right"></i>
                                </a>
                            </div>
                            <div class="accordion-body collapse entrepeneur-body-1">
                                <div class="accordion-inner">
                                   <div class="dashboard-item">
                                        <label >Status:</label>
                                        Published
                                   </div>
                                   <div class="dashboard-item">
                                        <label >Completion:</label>
                                        70% completed
                                   </div>
                                </div>
                            </div>
                        </div>
                        <div class="accordion-group">
                            <div class="accordion-heading">
                                <a class="accordion-toggle" data-toggle="collapse" data-parent=".entrepeneur-widget" href=".entrepeneur-body-2">
                                    Business Proposal 2
                                    <i class="fui-triangle-down-small pull-right"></i>
                                </a>
                            </div>
                            <div class="accordion-body collapse entrepeneur-body-2">
                                <div class="accordion-inner">
                                   <div class="dashboard-item">
                                        <label >Status:</label>
                                        Unpublished
                                   </div>
                                    <div class="dashboard-item">
                                        <label >Completion:</label>
                                        20% completed
                                   </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- TILE BODY GOES HERE -->
                <div class="bidx-tile-push"></div>
            </div>

            <div class="bidx-tile-footer">
                <a href="#" class="btn btn-primary btn-wide">Go to entrepeneur dashboard<i class="fui-arrow-right"></i></a>
            </div>
        </div>

        <div class="span6 well bidx-tile">
            <h2  class="popover-title">My group admin dashboard</h2>
            <p>These are the groups  you have created. Click on the name of the group to edit appearances, create content or administrate members</p>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Group name</th>
                        <th>Status</th>
                        <th>Total members</th>
                        <th>New members</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Group NameX</td>
                        <td>Published</td>
                        <td>200</td>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>Group NameZ</td>
                        <td>Unpublished</td>
                        <td>0</td>
                        <td>0</td>
                    </tr>
                    <tr>
                        <td>GroupnameY</td>
                        <td>Unpublished</td>
                        <td>0</td>
                        <td>0</td>

                    </tr>
                    <tr>
                        <td>GroupNameA</td>
                        <td>Published</td>
                        <td>534</td>
                        <td>20</td>

                    </tr>
                </tbody>
            </table>
            <div class="pagination center">
                <ul>
                    <li class="previous"><a class="fui-arrow-left" href="#fakelink"></a></li>
                    <li class="active"><a href="#fakelink">1</a></li>
                    <li><a href="#fakelink">2</a></li>
                    <li><a href="#fakelink">3</a></li>
                    <li><a href="#fakelink">4</a></li>
                    <li><a href="#fakelink">5</a></li>
                    <li class="pagination-dropdown dropup">
                    <i class="dropdown-arrow"></i>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#fakelink">
                    <i class="fui-triangle-up"></i>
                    </a>
                    <ul class="dropdown-menu">
                    <li><a href="#fakelink">6&ndash;10</a></li>
                    <li><a href="#fakelink">11&ndash;15</a></li>
                    <li><a href="#fakelink">16&ndash;20</a></li>
                    </ul>
                    </li>
                    <li class="next"><a class="fui-arrow-right" href="#fakelink"></a></li>
                </ul>
            </div>
            <a href="#" class="btn btn-primary btn-wide">Go to Group Admin Dashboard<i class="fui-arrow-right"></i></a>
        </div>

    </div>

    <div class="row-fluid">

        <div class="span6 well bidx-tile">
            <h2 class="popover-title">My investor dashboard</h2>
            <p>See here the latest three business proposals that have been published in recently and may be of your interest. Click on view more to see the full list.</p>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Location</th>
                        <th>Industry</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Business Proposal 1</td>
                        <td>Ecuador</td>
                        <td>Green energy</td>
                    </tr>
                    <tr>
                        <td>Business Proposal 2</td>
                        <td>Peru</td>
                        <td>Green Energy</td>
                    </tr>
                    <tr>
                        <td>Business Proposal 3</td>
                        <td>Colombia</td>
                        <td>Green Energy</td>
                    </tr>
                    <tr>
                        <td>Business Proposal 1</td>
                        <td>Ecuador</td>
                        <td>Green energy</td>
                    </tr>
                </tbody>
            </table>
            <div class="pagination center">
                <ul>
                    <li class="previous"><a class="fui-arrow-left" href="#fakelink"></a></li>
                    <li class="active"><a href="#fakelink">1</a></li>
                    <li><a href="#fakelink">2</a></li>
                    <li><a href="#fakelink">3</a></li>
                    <li><a href="#fakelink">4</a></li>
                    <li><a href="#fakelink">5</a></li>
                    <li class="pagination-dropdown dropup">
                    <i class="dropdown-arrow"></i>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#fakelink">
                    <i class="fui-triangle-up"></i>
                    </a>
                    <ul class="dropdown-menu">
                    <li><a href="#fakelink">6&ndash;10</a></li>
                    <li><a href="#fakelink">11&ndash;15</a></li>
                    <li><a href="#fakelink">16&ndash;20</a></li>
                    </ul>
                    </li>
                    <li class="next"><a class="fui-arrow-right" href="#fakelink"></a></li>
                </ul>
            </div>
            <a href="/investor-dashboard" class="btn btn-primary btn-wide">Go to Investor Dashboard<i class="fui-arrow-right"></i></a>
        </div>


        <div class="span6 well bidx-tile">
            <h2 class="popover-title">My companies</h2>
            <p>Description… Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since</p>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>Group name</th>
                        <th>Registerd</th>
                        <th>Employees</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Company name 1</td>
                        <td>yes</td>
                        <td>yes</td>
                    </tr>
                    <tr>
                        <td>Company name 2</td>
                        <td>no</td>
                        <td>yes</td>
                    </tr>
                </tbody>
            </table>
            <button class="btn btn-primary btn-wide"><i class="fui-plus"></i>Create a new company</button>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span6 well bidx-tile">
            <h2 class="popover-title">My mentor dashboard</h2>
            <div></div>
         </div>
    </div>
</div>