        <div class=" tabs-region">
            <hr>
            <div class="side-bar well">

<?php
    if( $isSuperAdmin ) {
?>
    <h2><?php _e('Admin functionality', 'bidxplugin')?></h2>
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong><?php _e('Wordpress dashboard', 'bidxplugin')?></strong>
        </div>
        <div class="panel-body">
            <em><?php _e('Visit wordpress dashboard', 'bidxplugin')?></em>
            <a href="/wp-admin" class="btn btn-primary pull-right"><i class="fa fa-eye"></i> <?php _e('Visit','bidxplugin')?></a>
        </div>
    </div>
<?php
    }
    else if ( isset($this->data->isMyProfile) && $this->data->isMyProfile ) {
?>
            <h2><?php _e('Create and grow', 'bidxplugin')?></h2>
<?php
        if ( isset( $entities->bidxEntrepreneurProfile ) ) {
?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong><?php _e('Create a business summary', 'bidxplugin')?></strong>
                </div>
                <div class="panel-body">
                    <em><?php _e('Create your business', 'bidxplugin')?></em>
                    <a href="<?php echo _l('businesssummary');?>/#createBusinessSummary" class="btn btn-primary pull-right"><i class="fa fa-plus-circle"></i> <?php _e('Create','bidxplugin')?></a>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong><?php _e('Do you own or participate in a company?', 'bidxplugin')?></strong>
                </div>
                <div class="panel-body">
                    <em><?php _e('Add a company', 'bidxplugin')?></em>
                    <a href="<?php echo _l('company');?>/#createCompany" class="btn btn-primary pull-right"><i class="fa fa-plus-circle"></i> <?php _e('Add','bidxplugin'); ?></a>
                </div>
            </div>

<?php
        }

        // Create entrepreneur
        //
        if ( !isset( $entities->bidxEntrepreneurProfile ) ) {
?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong><?php _e('Become an entrepreneur', 'bidxplugin')?></strong>
                </div>
                <div class="panel-body">
                    <em><?php _e('Create your entrepreneur profile', 'bidxplugin')?></em>
                    <a href="<?php echo _l('member');?>/#createEntrepreneur" class="btn btn-primary pull-right"><i class="fa fa-plus-circle"></i> <?php _e('Create','bidxplugin')?></a>
                </div>
            </div>
<?php
        } else {
?>
            <div class="panel panel-default">
                <div class="panel-body">
<?php
                    printf( __( 'Go to %sEntrepreneur dashboard%s', 'bidxplugin' ), '<a href="'._l('entrepreneur-dashboard').'">', '</a>' );
?>
                </div>
            </div>

<?php
        }

        // Create investor
        //
        if ( !isset( $entities->bidxInvestorProfile )) {
?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong><?php _e('Become an investor', 'bidxplugin')?></strong>
                </div>
                <div class="panel-body">
                    <em><?php _e('Create your resources', 'bidxplugin')?></em>
                    <a href="<?php echo _l('member');?>/#createInvestor" class="btn btn-primary pull-right"><i class="fa fa-plus-circle"></i> <?php _e('Invest','bidxplugin')?></a>
                </div>
            </div>
<?php
        } else {
?>
            <div class="panel panel-default">
                <div class="panel-body">
<?php
                    printf( __( 'Go to %sInvestor dashboard%s', 'bidxplugin' ), '<a href="'._l('investor-dashboard').'">', '</a>' );
?>
                </div>
            </div>
<?php
        }

        // Create mentor
        //
        if ( !isset( $entities->bidxMentorProfile )) {
?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong><?php _e('Become a mentor', 'bidxplugin')?></strong>
                </div>
                <div class="panel-body">
                    <em><?php _e('Create your mentor profile', 'bidxplugin')?></em>
                    <a href="<?php echo _l('member');?>/#createMentor" class="btn btn-primary pull-right"><i class="fa fa-plus-circle"></i> <?php _e('Create','bidxplugin')?></a>
                </div>
            </div>
<?php
        } else {
?>
            <div class="panel panel-default">
                <div class="panel-body">
<?php
                    printf( __( 'Go to %sMentor dashboard%s', 'bidxplugin' ), '<a href="'._l('mentor-dashboard').'">', '</a>' );
?>
                </div>
            </div>
<?php
        }

    }
          //  }
            $this->render('view-group.phtml');
?>

            </div>
<?php 
            if ( BidxCommon::$staticSession->authenticated == 'true')
            {
?>
                <div class="region-side">
<?php               
                    dynamic_sidebar('priv-member-side');
?>
                </div>
<?php                
            }
            else
            {
?>
                <div class="region-side">
<?php               
                    dynamic_sidebar('pub-member-side');
?>
                </div>
<?php                
            }
?>
        </div>
