<div id="editInvestor" class="row-fluid mainState mainStateEditInvestor">

    <!-- LOAD -->
    <div class="view viewLoad span12">
        <span><?php _e('Retrieving investor information...','bidxplugin'); ?></span>
    </div>

    <!-- CREATE -->
    <div class="view viewCreate span12">
        <span><?php _e('Creating investor...','bidxplugin'); ?></span>
    </div>

    <!-- ERROR -->
    <div class="view viewError span12">
        <h2><?php _e('Error','bidxplugin'); ?></h2>
        <p class="errorMsg"></p>
    </div>

    <!-- EDIT -->
    <div class="view viewEdit">

        <form id="frmeditInvestor">

            <div class="span3">
                <ul class="nav nav-list nav-edit nav-editInvestor hidden-phone">
                    <li><a href="#editInvestor/generalInformation"><?php _e('General information','bidxplugin'); ?></a>
                    <li><a href="#editInvestor/investmentPreferences"><?php _e('Investment preferences','bidxplugin'); ?></a>
                    <li><a href="#editInvestor/investmentHistory"><?php _e('Investment history','bidxplugin'); ?></a>
                    <li><a href="#editInvestor/references"><?php _e('References','bidxplugin'); ?></a>
                    <li><a href="#editInvestor/documents"><?php _e('Documents','bidxplugin'); ?></a>
                </ul>
            </div>

            <div class="span9">

                <!-- "id" is actually the memberProfileId, but to not have to rewrite the file upload let's do it like this -->
                <input type="hidden" name="investorProfileId"     />
                <input type="hidden" name="domain"              />

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editInvestor/generalInformation"></span>
                    <legend><?php _e('General information','bidxplugin'); ?></legend>

                    <div class="row-fluid">
                        <div class="span12">

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Describe yourself as investor','bidxplugin'); ?></label>
                                <div class="controls">
                                    <textarea name="summary" placeholder="<?php _e('Please type the summary of yourself as investor','bidxplugin'); ?>" ></textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">

                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Do you invest on behalf of an institution?','bidxplugin'); ?></label>
                                <div class="controls">
                                    <label class="radio inline"><input type="radio" value="true"  name="investsForInst" data-toggle="radio"/> <?php _e('Yes','bidxplugin'); ?></label>
                                    <label class="radio inline"><input type="radio" value="false" name="investsForInst" data-toggle="radio"/> <?php _e('No','bidxplugin'); ?></label>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid toggle toggle-investsForInst">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Institution type','bidxplugin'); ?></label>
                                <div class="controls">
                                    <select name="investorType"></select>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid toggle toggle-investsForInst">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Institution name','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="institutionName" placeholder="<?php _e('Please type the name of the institution','bidxplugin'); ?>">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid toggle toggle-investsForInst">
                        <div class="span6">
                            <div class="control-group formfield" data-validation='{"typecheck": [{"url":{"text":"Please fill in a valid URL"}}]}'>
                                <label class="control-label"><?php _e('Institution website'); ?></label>
                                <div class="controls">
                                    <input type="text" name="institutionWebsite" placeholder="<?php _e('Please type the website of the institution','bidxplugin'); ?>">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid institutionAddressItem">
                        <div class="span6">

                            <input type="hidden" name="institutionAddress.coordinates"    />

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Country','bidxplugin'); ?></label>
                                <div class="controls">
                                    <select name="institutionAddress.country" ></select>
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('City','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="institutionAddress.cityTown" placeholder="<?php _e('Please type your city','bidxplugin'); ?>" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Street','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="institutionAddress.street" placeholder="<?php _e('Please type your street','bidxplugin'); ?>" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Street number','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="institutionAddress.streetNumber" placeholder="<?php _e('Please type your street number','bidxplugin'); ?>" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Postal code','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="institutionAddress.postalCode" placeholder="<?php _e('Please type your postcode','bidxplugin'); ?>" />
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Neighborhood','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="institutionAddress.neighborhood" placeholder="<?php _e('Please type your neighborhood','bidxplugin'); ?>" />
                                </div>
                            </div>
                        </div>

                        <div class="span6">
                            <div class="institutionAddressMap"></div>
                        </div>
                    </div>

                </fieldset>


                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editInvestor/investmentPreferences"></span>
                    <legend><?php _e('Investment preferences','bidxplugin'); ?></legend>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Industry','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" autocomplete="off" name="focusIndustry" class="bidx-tagsinput disabled" disabled data-bidxdatakey="industry" placeholder="<?php _e('Focus industry','bidxplugin'); ?>">
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Languages','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" autocomplete="off" name="focusLanguage" class="bidx-tagsinput disabled" disabled data-bidxdatakey="language" placeholder="<?php _e('Languages','bidxplugin'); ?>">
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Social impact','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" autocomplete="off" name="focusSocialImpact" class="bidx-tagsinput disabled" disabled data-bidxdatakey="socialImpact" placeholder="<?php _e('Social impact','bidxplugin'); ?>">
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Environmental impact','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" autocomplete="off" name="focusEnvImpact" class="bidx-tagsinput disabled" disabled data-bidxdatakey="envImpact" placeholder="<?php _e('Environmental impact','bidxplugin'); ?>">
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Consumer type','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" autocomplete="off" name="focusConsumerType" class="bidx-tagsinput disabled" disabled data-bidxdatakey="consumerType" placeholder="<?php _e('Consumer type','bidxplugin'); ?>">
                                </div>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Stage of business','bidxplugin'); ?></label>

                                <label class="checkbox" for="cbFocusStageBusinessStartup">
                                    <input type="checkbox" name="focusStageBusiness" value="startUp" id="cbFocusStageBusinessStartup" data-toggle="checkbox">
                                    <?php _e('Startup','bidxplugin'); ?>
                                </label>

                                <label class="checkbox" for="cbFocusStageBusinessEstablished">
                                    <input type="checkbox" name="focusStageBusiness" value="established" id="cbFocusStageBusinessEstablished" data-toggle="checkbox">
                                    <?php _e('Established','bidxplugin'); ?>
                                </label>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Gender','bidxplugin');?></label>

                                <label class="checkbox" for="cbFocusGenderMale">
                                    <input type="checkbox" name="focusGender" value="m" id="cbFocusGenderMale" data-toggle="checkbox">
                                    <?php _e('Male','bidxplugin'); ?>
                                </label>

                                <label class="checkbox" for="cbFocusGenderFemale">
                                    <input type="checkbox" name="focusGender" value="f" id="cbFocusGenderFemale" data-toggle="checkbox">
                                    <?php _e('Female','bidxplugin'); ?>
                                </label>
                            </div>

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Investment type','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" autocomplete="off" name="investmentType" class="bidx-tagsinput disabled" disabled data-bidxdatakey="investmentType" placeholder="<?php _e('Investment type'); ?>">
                                </div>
                            </div>

                        </div>

                        <div class="span6">
                            <h6><?php _e('Location','bidxplugin'); ?></h6>

                            <label class="radio"><input type="radio" data-toggle="radio" name="focusLocationType" value="country"><?php _e('Country / Countries','bidxplugin'); ?></label>
                            <label class="radio"><input type="radio" data-toggle="radio" name="focusLocationType" value="city"><?php _e('City / Cities','bidxplugin'); ?></label>
                            <label class="radio"><input type="radio" data-toggle="radio" name="focusLocationType" value="reach"><?php _e('Region','bidxplugin'); ?></label>

                            <div class="control-group formfield toggle toggle-focusLocationType toggle-focusLocationType-country">
                                <label class="control-label"><?php _e('Country','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" autocomplete="off" name="focusCountry" class="bidx-tagsinput disabled" disabled data-bidxdatakey="country" placeholder="<?php _e('Country','bidxplugin'); ?>">
                                </div>
                            </div>

                            <div class="control-group formfield toggle toggle-focusLocationType toggle-focusLocationType-city">
                                <label class="control-label"><?php _e('City','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" autocomplete="off" name="focusCity" class="bidx-tagsinput" placeholder="<?php _e('City','bidxplugin'); ?>">
                                </div>
                            </div>

                            <div class="control-group formfield  toggle toggle-focusLocationType toggle-focusLocationType-reach">
                            <label class="control-label"><?php _e('Region','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="focusReach" data-type="location" data-type-arguments='{"showMap":"true","mapDimensions":"width:100%;height:400px;","setMarkers":"true", "drawCircle":"true"}' />
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="row-fluid">
                    </div>

                    <h4><?php _e('Investment size','bidxplugin'); ?></h4>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Minimal investment','bidxplugin'); ?></label>
                                <div class="controls">
                                    <div class="input-prepend">
                                        <span class="add-on">$</span>
                                        <input type="number" name="minInvestment" placeholder="<?php _e('Minimal investment','bidxplugin'); ?>" min="0">
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Maximum investment','bidxplugin'); ?></label>
                                <div class="controls">
                                    <div class="input-prepend">
                                        <span class="add-on">$</span>
                                        <input type="number" name="maxInvestment" placeholder="<?php _e('Maximum investment','bidxplugin'); ?>" min="0">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span12">

                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Other preferences (max. 60 words)','bidxplugin'); ?></label>
                                <div class="controls">
                                    <textarea name="additionalPreferences" placeholder="<?php _e('Please type any additional preferences','bidxplugin'); ?>"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                </fieldset>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editInvestor/investmentHistory"></span>
                    <legend><?php _e('Investment history','bidxplugin'); ?></legend>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Number of investments in the last 12 months','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="number" name="numberInvestments" placeholder="<?php _e('Number of investments','bidxplugin'); ?>">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Amount invested in the last 12 months','bidxplugin'); ?></label>
                                <div class="controls">
                                    <div class="input-prepend">
                                        <span class="add-on">$</span>
                                        <input type="number" name="numberInvestments" placeholder="<?php _e('Number of investments','bidxplugin'); ?>">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group formfield">
                                <label class="control-label"><?php _e('Typical involvement','bidxplugin'); ?></label>
                                <div class="btn-group" data-toggle="buttons-radio" name="typicalInvolvement">
                                  <button type="button" class="btn btn-primary" value="advisory"><?php _e('Advisory','bidxplugin'); ?></button>
                                  <button type="button" class="btn btn-primary" value="handsOn"><?php _e('Hands-On','bidxplugin'); ?></button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="intermediate-row">
                        <h6><?php _e('Previous investment','bidxplugin'); ?></h6>
                        <a href="#addPreviousInvestment" class="btn btn-primary"><span class="fui-plus"></span><?php _e('Add','bidxplugin'); ?></a>
                    </div>

                    <div class="previousInvestmentContainer"></div>

                </fieldset>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editInvestor/references"></span>
                    <legend><?php _e('References','bidxplugin'); ?></legend>

                    <div class="intermediate-row">
                        <a href="#addReference" class="btn btn-primary"><span class="fui-plus"></span><?php _e('Add','bidxplugin'); ?></a>
                    </div>

                    <div class="referencesContainer"></div>

                </fieldset>

                <fieldset class="well hideOnCreate">
                    <span class="scrollPositionMarker" id="editInvestor/documents"></span>
                    <legend><?php _e('Documents','bidxplugin'); ?></legend>

                    <div class="formfield">
                        <input type="file" name="attachment" data-type="fileUpload" data-type-arguments='{"url":"/wp-admin/admin-ajax.php?action=file_upload", "extraValues":[{"name": "uploadtype", "value":"investorprofileattachment"}], "addFields":["investorProfileId","domain"], "callback": "bidx.investorprofile.attachmentUploadDone"}'/>
                    </div>

                    <div class="attachmentsContainer"></div>

                </fieldset>
            </div>

        </form>
    </div>

    <div class="snippets hide">

        <!-- Previous Investment -->
        <div class="previousInvestmentsItem span6 well well-white">
            <div class="control-group formfield">
                <label class="control-label"><?php _e('Company name','bidxplugin'); ?></label>
                <div class="controls">
                    <input type="text" name="companyName" placeholder="<?php _e('Please type the name','bidxplugin'); ?>">
                </div>
            </div>

            <div class="control-group formfield">
                <label class="control-label"><?php _e('Company web-site?','bidxplugin'); ?></label>
                <div class="controls">
                    <input type="text" name="companyWebsite" placeholder="<?php _e('Please type the URL','bidxplugin'); ?>">
                </div>
            </div>

            <div class="control-group formfield">
                <label class="control-label"><?php _e('Amount invested','bidxplugin'); ?></label>
                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on">$</span>
                        <input type="number" name="investment" placeholder="<?php _e('Amount invested','bidxplugin'); ?>">
                    </div>
                </div>
            </div>

            <div class="control-group formfield">
                <label class="control-label"><?php _e('Investment type','bidxplugin'); ?></label>
                <div class="controls">
                    <select name="investmentType"></select>
                </div>
            </div>

            <a href="#removeItem" class="btn btn-danger btn-mini btn-block"><?php _e('Remove this investment','bidxplugin'); ?></a>
        </div>

        <!-- Reference -->
        <div class="referencesItem span6 well well-white">
            <div class="control-group formfield">
                <label class="control-label"><?php _e('First name','bidxplugin'); ?></label>
                <div class="controls">
                    <input type="text" name="firstName" placeholder="<?php _e('Please type the first name','bidxplugin'); ?>">
                </div>
            </div>

            <div class="control-group formfield">
                <label class="control-label"><?php _e('Last name','bidxplugin'); ?></label>
                <div class="controls">
                    <input type="text" name="lastName" placeholder="<?php _e('Please type the last name','bidxplugin'); ?>">
                </div>
            </div>

            <div class="control-group formfield">
                <label class="control-label"><?php _e('Professional title','bidxplugin'); ?></label>
                <div class="controls">
                    <input type="text" name="professionalTitle" placeholder="<?php _e('Please type the professional title','bidxplugin'); ?>">
                </div>
            </div>

            <div class="control-group formfield" >
                <label class="control-label"><?php _e('LinkedIn profile','bidxplugin'); ?></label>
                <div class="controls">
                    <input type="text" name="linkedIn" placeholder="<?php _e('Please type your LinkedIn profile url','bidxplugin'); ?>" />
                </div>
            </div>

            <div class="control-group formfield" data-validation='{"typecheck": [{"email":{"text":"<?php _e('Please fill in a valid email address','bidxplugin'); ?>"}}]}'>
                <label class="control-label"><?php _e('Email address','bidxplugin'); ?></label>
                <div class="controls">
                    <input type="email" name="emailAddress" placeholder="<?php _e('Please type your email address','bidxplugin'); ?>" />
                </div>
            </div>

            <div class="control-group formfield">
                <label class="control-label"><?php _e('Landline','bidxplugin'); ?></label>
                <div class="controls">
                    <input type="text" name="contactDetail[0].landLine" placeholder="<?php _e('Please type your landline number','bidxplugin'); ?>" />
                </div>
            </div>

            <div class="control-group formfield">
                <label class="control-label"><?php _e('Mobile','bidxplugin'); ?></label>
                <div class="controls">
                    <input type="text" name="contactDetail[0].mobile" placeholder="<?php _e('Please type your mobile number','bidxplugin'); ?>" />
                </div>
            </div>

            <a href="#removeItem" class="btn btn-danger btn-mini btn-block"><?php _e('Remove this reference','bidxplugin'); ?></a>
        </div>

        <!-- Attachment -->
        <div class="attachmentItem span4 well well-white">
            <div class="row-fluid">
                <div class="span4">
                    <a href="#" class="documentLink"><img class="img-rounded documentImage"></a>
                </div>
                <div class="span8">
                    <h3 class="documentName"></h3>
                    <p class="uploadedDateTime"></p>

                    <div class="control-group formfield">
                        <div class="controls">
                            <input type="text" name="purpose" placeholder="<?php _e('Short description','bidxplugin'); ?>">
                        </div>
                    </div>

                    <div class="control-group formfield">
                        <label class="control-label"><?php _e('Document type','bidxplugin'); ?></label>
                        <div class="controls">
                            <select name="documentType"></select>
                        </div>
                    </div>
                </div>
            </div>

            <a href="#removeItem" class="btn btn-danger btn-mini btn-block"><?php _e('Delete','bidxplugin'); ?></a>
        </div>
    </div>

</div><!-- // row -->
