<div id="editInvestor" class="mainState mainStateEditInvestor">

    <!-- LOAD -->
    <div class="view viewLoad alert alert-info text-center">
        <div class="progress progress-striped active">
            <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                <?php _e('Retrieving investor information...','bidxplugin'); ?>
            </div>
        </div>
    </div>

    <!-- CREATE -->
    <div class="view viewCreate alert alert-info text-center">
        <div class="progress progress-striped active">
            <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                <?php _e('Creating investor profile...','bidxplugin'); ?>
            </div>
        </div>
    </div>

    <!-- ERROR -->
    <div class="view viewError alert alert-warning">
        <h2><?php _e('Error','bidxplugin'); ?></h2>
        <p class="errorMsg"></p>
    </div>

    <!-- EDIT -->
    <div class="view viewEdit">

        <form id="frmeditInvestor">


            <div id="investerAccordion">

                <!-- generalInformation -->
                <div class="panel panel-default panel-open">

                    <div class="panel-heading">
                        <a class="btn-block" data-toggle="collapse" data-parent="#investerAccordion" href="#generalInformation">
                            <span class="fa fa-chevron-right accordion-state-icon"></span>
                            <?php _e('General information','bidxplugin'); ?>
                        </a>
                    </div>

                    <div id="generalInformation" class="panel-collapse collapse in" style="overflow: visible;">
                        <div class="panel-body">
                            <!-- accordion body -->

                            <blockquote class="alert-info">
                                <?php _e('Tell visitors and members of the group how you see yourself as an investor. Give a brief description of your investment interests.', 'bidxplugin')?>
                            </blockquote>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label><?php _e('Describe yourself as an investor','bidxplugin'); ?></label>
                                        <textarea name="summary" class="form-control" placeholder="<?php _e('Please type in the description of you as an investor','bidxplugin'); ?>" ></textarea>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label><?php _e('Investor type','bidxplugin'); ?></label>
                                        <select name="investorType"></select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label><?php _e('Do you invest on behalf of an institution?','bidxplugin'); ?></label>

                                        <div class="radio">
                                            <input type="radio" value="true" id="radio-investsForInstYes" name="investsForInst" data-toggle="radio" />
                                            <label for="radio-investsForInstYes"><span></span><?php _e('Yes','bidxplugin'); ?></label>
                                        </div>
                                        <div class="radio">
                                            <input type="radio" value="false" id="radio-investsForInstNo" name="investsForInst" data-toggle="radio" />
                                            <label for="radio-investsForInstNo"><span></span><?php _e('No','bidxplugin'); ?></label>
                                        </div>

                                    </div>
                                </div>
                            </div>

                            <div class="row toggle toggle-investsForInst">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label><?php _e('Institution name','bidxplugin'); ?></label>
                                        <div class="input-group">
                                            <span class="input-group-addon"><i class="fa fa-building-o"></i></span>
                                            <input type="text" class="form-control" name="institutionName" placeholder="<?php _e('Please enter the name of your institution','bidxplugin'); ?>">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label><?php _e('Institution website'); ?></label>
                                        <div class="input-group">
                                            <span class="input-group-addon"><i class="fa fa-globe"></i></span>
                                            <input type="text" class="form-control" name="institutionWebsite" placeholder="<?php _e('Please enter the name of your institution','bidxplugin'); ?>">
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row institutionAddressItem">
                                <div class="col-sm-6">
                                    <input type="hidden" name="institutionAddress.coordinates"    />
                                    <div class="form-group">
                                        <label><?php _e('Country','bidxplugin'); ?></label>
                                        <select name="institutionAddress.country" ></select>
                                    </div>
                                    <div class="form-group">
                                        <label><?php _e('City','bidxplugin'); ?></label>
                                        <input type="text" class="form-control" name="institutionAddress.cityTown" placeholder="<?php _e('Please enter your city','bidxplugin'); ?>" />
                                    </div>
                                    <div class="form-group">
                                        <label><?php _e('Street','bidxplugin'); ?></label>
                                        <input type="text" class="form-control" name="institutionAddress.street" placeholder="<?php _e('Please enter your street name','bidxplugin'); ?>" />
                                    </div>
                                    <div class="form-group">
                                        <label><?php _e('Building number','bidxplugin'); ?></label>
                                        <input type="text" class="form-control" name="institutionAddress.streetNumber" placeholder="<?php _e('Please enter your building number','bidxplugin'); ?>" />
                                    </div>
                                    <div class="form-group">
                                        <label><?php _e('Postal code','bidxplugin'); ?></label>
                                        <input type="text" class="form-control" name="institutionAddress.postalCode" placeholder="<?php _e('Please enter your postcode','bidxplugin'); ?>" />
                                    </div>
                                    <div class="form-group">
                                        <label><?php _e('Neighborhood','bidxplugin'); ?></label>
                                        <input type="text" class="form-control" name="institutionAddress.neighborhood" placeholder="<?php _e('Please enter your neighborhood','bidxplugin'); ?>" />
                                    </div>
                                </div>

                                <div class="col-sm-6">
                                    <div class="institutionAddressMap"></div>
                                </div>
                            </div>

                            <!-- \\ accordion body -->
                        </div>
                    </div>
                </div>

                <!-- investmentPreferences -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a class="btn-block" data-toggle="collapse" data-parent="#investerAccordion" href="#investmentPreferences">
                            <span class="fa fa-chevron-right accordion-state-icon"></span>
                            <?php _e('Investment preferences','bidxplugin'); ?>
                        </a>
                    </div>
                    <div id="investmentPreferences" class="panel-collapse collapse">
                        <div class="panel-body">
                            <!-- accordion body -->
                            <blockquote class="alert-info">
                                <?php _e('Use this section to define your investment preferences, such as countries, products or industries that you would like to invest in. This information will be used to match your profileto businesses that fit these criteria.', 'bidxplugin')?>
                            </blockquote>

                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label><?php _e('Industry','bidxplugin'); ?></label>
                                        <select name="focusIndustry" multiple></select>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label><?php _e('Languages','bidxplugin'); ?></label>
                                        <select name="focusLanguage" multiple></select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label><?php _e('Social impact','bidxplugin'); ?></label>
                                        <select name="focusSocialImpact" multiple></select>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label><?php _e('Environmental impact','bidxplugin'); ?></label>
                                        <select name="focusEnvImpact" multiple></select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label><?php _e('Consumer type','bidxplugin'); ?></label>
                                        <select name="focusConsumerType" multiple></select>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label><?php _e('Investment type','bidxplugin'); ?></label>
                                        <select name="investmentType" multiple></select>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label><?php _e('Stage of business','bidxplugin'); ?></label>
                                        <div class="checkbox">
                                            <input type="checkbox" value="startup" id="checkbox-cbFocusStageBusinessStartup" name="focusStageBusiness" />
                                            <label for="checkbox-cbFocusStageBusinessStartup"><span></span><?php _e('Startup','bidxplugin'); ?></label>
                                        </div>
                                        <div class="checkbox">
                                            <input type="checkbox" value="established" id="checkbox-cbFocusStageBusinessEstablished" name="focusStageBusiness" />
                                            <label for="checkbox-cbFocusStageBusinessEstablished"><span></span><?php _e('Established','bidxplugin'); ?></label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label><?php _e('Gender','bidxplugin');?></label>
                                        <div class="checkbox">
                                            <input type="checkbox" value="m" id="checkbox-cbFocusGenderMale" name="focusGender" data-toggle="checkbox" />
                                            <label for="checkbox-cbFocusGenderMale"><span></span><?php _e('Male','bidxplugin'); ?></label>
                                        </div>
                                        <div class="checkbox">
                                            <input type="checkbox" value="f" id="checkbox-cbFocusGenderFemale" name="focusGender" data-toggle="checkbox" />
                                            <label for="checkbox-cbFocusGenderFemale"><span></span><?php _e('Female','bidxplugin'); ?></label>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label><?php _e('Location','bidxplugin'); ?></label>

                                        <div class="radio">
                                            <input type="radio" value="country" id="radio-focusLocationTypeCountry" name="focusLocationType" data-toggle="radio" />
                                            <label for="radio-focusLocationTypeCountry"><span></span><?php _e('Country / Countries','bidxplugin'); ?></label>
                                        </div>
                                        <div class="radio">
                                            <input type="radio" value="city" id="radio-focusLocationTypeCity" name="focusLocationType" data-toggle="radio" />
                                            <label for="radio-focusLocationTypeCity"><span></span><?php _e('City / Cities','bidxplugin'); ?></label>
                                        </div>
                                        <div class="radio">
                                            <input type="radio" value="reach" id="radio-focusLocationTypeReach" name="focusLocationType" data-toggle="radio" />
                                            <label for="radio-focusLocationTypeReach"><span></span><?php _e('Region','bidxplugin'); ?></label>
                                        </div>
                                    </div>


                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group toggle toggle-focusLocationType toggle-focusLocationType-country">
                                        <label><?php _e('Country','bidxplugin'); ?></label>
                                        <select name="focusCountry" multiple></select>
                                    </div>

                                    <div class="form-group toggle toggle-focusLocationType toggle-focusLocationType-city">
                                        <label><?php _e('City','bidxplugin'); ?></label>
                                        <div class="bidx-tagsinput-container">
                                            <input type="text" class="bidx-tagsinput enclosed" autocomplete="off" name="focusCity" class="bidx-tagsinput enclosed" placeholder="<?php _e('City','bidxplugin'); ?>">
                                        </div>
                                    </div>

                                    <div class="form-group  toggle toggle-focusLocationType toggle-focusLocationType-reach">
                                        <label><?php _e('Region','bidxplugin'); ?></label>
                                        <input type="text" class="form-control" name="focusReach" data-type="location" />
                                    </div>

                                </div>
                            </div>

                            <h4><?php _e('Investment size','bidxplugin'); ?></h4>

                            <div class="row">

                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label><?php _e('Maximum investment','bidxplugin'); ?></label>
                                        <div class="input-group">
                                            <span class="input-group-addon"><i class="fa fa-usd"></i></span>
                                            <input type="text" class="form-control" name="maxInvestment" placeholder="<?php _e('Maximum investment','bidxplugin'); ?>" min="0">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label><?php _e('Minimum investment','bidxplugin'); ?></label>
                                        <div class="input-group">
                                            <span class="input-group-addon"><i class="fa fa-usd"></i></span>
                                            <input type="text" class="form-control" name="minInvestment" placeholder="<?php _e('Minimal investment','bidxplugin'); ?>" min="0">
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label><?php _e('Total investment in the previous year','bidxplugin'); ?></label>
                                        <div class="input-group">
                                            <span class="input-group-addon"><i class="fa fa-usd"></i></span>
                                            <input type="text" class="form-control" name="totalInvestment" placeholder="<?php _e('Total investment','bidxplugin'); ?>" min="0">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">

                                    <div class="form-group">
                                        <label><?php _e('Other preferences (max. 60 words)','bidxplugin'); ?></label>
                                        <textarea name="additionalPreferences" class="form-control" placeholder="<?php _e('Please enter any additional preferences','bidxplugin'); ?>"></textarea>
                                    </div>
                                </div>
                            </div>

                            <!-- \\ accordion body -->
                        </div>
                    </div>
                </div>

                <!-- investmentHistory -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a class="btn-block" data-toggle="collapse" data-parent="#investerAccordion" href="#investmentHistory">
                            <span class="fa fa-chevron-right accordion-state-icon"></span>
                            <?php _e('Investment history','bidxplugin'); ?>
                        </a>
                    </div>
                    <div id="investmentHistory" class="panel-collapse collapse">
                        <div class="panel-body">
                            <!-- accordion body -->
                            <blockquote class="alert-info">
                                <?php _e('Entrepreneurs are interested in the investments you have made in the past. Give a few details about investments made in the last 12 months or earlier (if  any).', 'bidxplugin')?>
                            </blockquote>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label><?php _e('Number of investments in the last 12 months','bidxplugin'); ?></label>
                                        <div class="input-group">
                                            <span class="input-group-addon"><i class="fa fa-money"></i></span>
                                            <input type="text" class="form-control" name="numberInvestments" placeholder="<?php _e('Number of investments','bidxplugin'); ?>">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label><?php _e('Amount invested in the last 12 months','bidxplugin'); ?></label>
                                        <div class="input-group">
                                            <span class="input-group-addon"><i class="fa fa-usd"></i></span>
                                            <input type="text" class="form-control" name="numberInvestments" placeholder="<?php _e('Number of investments','bidxplugin'); ?>">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label><?php _e('Typical involvement','bidxplugin'); ?></label>
                                        <div class="radio">
                                            <input type="radio" value="advisory" id="radio-typicalInvolvementAdvisory" name="typicalInvolvement" data-toggle="radio" />
                                            <label for="radio-typicalInvolvementAdvisory"><span></span><?php _e('Advisory','bidxplugin'); ?></label>
                                        </div>
                                        <div class="radio">
                                            <input type="radio" value="handsOn" id="radio-typicalInvolvementHandsOn" name="typicalInvolvement" data-toggle="radio" />
                                            <label for="radio-typicalInvolvementHandsOn"><span></span><?php _e('Hands-On','bidxplugin'); ?></label>
                                        </div>

                                    </div>
                                </div>
                            </div>

                            <h4><?php _e('Previous investment','bidxplugin'); ?>
                                <a href="#addPreviousInvestment" class="btn btn-xs btn-primary"><span class="fa fa-plus"></span> <?php _e('Add','bidxplugin'); ?></a>
                            </h4>

                            <div class="previousInvestmentContainer"></div>

                            <!-- \\ accordion body -->
                        </div>
                    </div>
                </div>

                <!-- references -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a class="btn-block" data-toggle="collapse" data-parent="#investerAccordion" href="#references">
                           <span class="fa fa-chevron-right accordion-state-icon"></span>
                           <?php _e('References','bidxplugin'); ?>
                        </a>
                    </div>
                    <div id="references" class="panel-collapse collapse">
                        <div class="panel-body">
                            <!-- accordion body -->
                            <blockquote class="alert-info">
                                <?php _e('References from other entrepreneurs or investment partners are important when getting in touch with another member of the platform. Fill in details of those you have worked with  and are willing recommend you.', 'bidxplugin')?>
                            </blockquote>
                            <h4><?php _e('Entrepreneurs References','bidxplugin'); ?>
                                <a href="#addReference" class="btn btn-xs btn-primary"><span class="fa fa-plus"></span> <?php _e('Add','bidxplugin'); ?></a>
                            </h4>


                            <div class="referencesContainer"></div>

                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a class="btn-block" data-toggle="collapse" data-parent="#investerAccordion" href="#documents">
                           <span class="fa fa-chevron-right accordion-state-icon"></span>
                           <?php _e('Documents','bidxplugin'); ?>
                        </a>
                    </div>
                    <div id="documents" class="panel-collapse collapse">
                        <div class="panel-body attachmentsControl">
                            <div class="attachmentsContainer"></div>

                            <button data-toggle="modal" data-target="#addDocs" class="btn btn-primary js-btn-add-attachments"><span class="fa fa-plus"></span> <?php _e('Add documents','bidxplugin');?></button>

                            <div class="addAttachmentsModal modal fade" id="addDocs" role="dialog" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                            <h3><?php _e('Check the files you want to attach to your investor profile', 'bidxplugin' ); ?></h3>
                                        </div>
                                        <div class="modal-body">
<?php
                                            // Media app will only be inserted once, this is by design!
                                            //
                                            echo do_shortcode( '[bidx app="media"]' );
?>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-primary btnSelectFile"><?php _e( 'Select file', 'bidxplugin' ); ?></button>
                                            <button type="button" class="btn btn-link btnCancelSelectFile" data-dismiss="modal"><?php _e( 'Cancel', 'bidxplugin' ); ?></button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>

                <!-- \\ accordion -->
            </div>

        </form>
    </div>

    <div class="snippets hide">

        <!-- Previous Investment -->
        <div class="previousInvestmentsItem col-sm-6">
            <div class="well">
                <div class="form-group col-sm-12">
                    <label><?php _e('Company name','bidxplugin'); ?></label>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-building-o"></i></span>
                        <input type="text" class="form-control" name="companyName" placeholder="<?php _e('Please enter the company name','bidxplugin'); ?>">
                    </div>
                </div>

                <div class="form-group col-sm-12">
                    <label><?php _e('Company website?','bidxplugin'); ?></label>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-globe"></i></span>
                        <input type="text" class="form-control" name="companyWebsite" placeholder="<?php _e('Please enter the company URL','bidxplugin'); ?>">
                    </div>
                </div>

                <div class="form-group col-sm-12">
                    <label><?php _e('Amount invested','bidxplugin'); ?></label>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-usd"></i></span>
                        <input type="text" class="form-control" name="investment" placeholder="<?php _e('Amount invested','bidxplugin'); ?>">
                    </div>
                </div>

                <div class="form-group col-sm-12">
                    <label><?php _e('Investment type','bidxplugin'); ?></label>
                    <select name="investmentType"></select>
                </div>

                <a href="#removeItem" class="btn btn-danger btn-sm btn-block"><?php _e('Remove this investment','bidxplugin'); ?></a>
            </div>
        </div>

        <!-- Reference -->
        <div class="referencesItem col-sm-6">
            <div class="well">
                <div class="form-group col-sm-12">
                    <label><?php _e('First name','bidxplugin'); ?></label>
                    <input type="text" class="form-control" name="firstName" placeholder="<?php _e('Please enter the first name','bidxplugin'); ?>">
                </div>

                <div class="form-group col-sm-12">
                    <label><?php _e('Last name','bidxplugin'); ?></label>
                    <input type="text" class="form-control" name="lastName" placeholder="<?php _e('Please enter the last name','bidxplugin'); ?>">
                </div>

                <div class="form-group col-sm-12">
                    <label><?php _e('Professional title','bidxplugin'); ?></label>
                    <input type="text" class="form-control" name="professionalTitle" placeholder="<?php _e('Please enter the professional title','bidxplugin'); ?>">
                </div>

                <div class="form-group col-sm-12" >
                    <label><?php _e('LinkedIn profile','bidxplugin'); ?></label>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-linkedin-square"></i></span>
                        <input type="text" class="form-control" name="linkedIn" placeholder="<?php _e('Please enter your LinkedIn profile URL','bidxplugin'); ?>" />
                    </div>
                </div>

                <div class="form-group col-sm-12">
                    <label><?php _e('Email address','bidxplugin'); ?></label>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                        <input type="email" class="form-control" name="emailAddress" placeholder="<?php _e('Please enter your email address','bidxplugin'); ?>" />
                    </div>
                </div>

                <div class="form-group col-sm-12">
                    <label><?php _e('Landline','bidxplugin'); ?></label>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-phone-square"></i></span>
                        <input type="text" class="form-control" name="landLine" placeholder="<?php _e('Please enter your landline number','bidxplugin'); ?>" />
                    </div>
                </div>

                <div class="form-group col-sm-12">
                    <label><?php _e('Mobile','bidxplugin'); ?></label>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-tablet"></i></span>
                        <input type="text" class="form-control" name="mobile" placeholder="<?php _e('Please enter your mobile number','bidxplugin'); ?>" />
                    </div>
                </div>

                <a href="#removeItem" class="btn btn-danger btn-sm btn-block"><?php _e('Remove this reference','bidxplugin'); ?></a>
            </div>
        </div>

        <!-- Attachment -->
        <div class="attachmentItem col-sm-4">
            <div class="well">
                <div class="row">
                    <div class="col-sm-4">
                        <a href="#" class="documentLink"><img class="img-rounded documentImage"></a>
                    </div>
                    <div class="col-sm-7">
                        <h3 class="documentName"></h3>
                        <p class="createdDateTime"></p>
                        <p class="purpose"></p>
                        <p class="documentType"></p>
                    </div>
                </div>
                <a href="#removeItem" class="btn btn-danger btn-sm btn-block"><?php _e('Remove from profile','bidxplugin'); ?></a>
            </div>
        </div>
    </div>

</div><!-- // row -->
