<div id="editEntrepreneur" class="mainState mainStateEditEntrepreneur">

    <!-- LOAD -->
    <div class="view viewLoad alert alert-info text-center">
        <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e('Retrieving entrepreneur information...','bidxplugin'); ?>
    </div>

    <!-- ERROR -->
    <div class="view viewError alert alert-warning">
        <h2><?php _e('Error','bidxplugin'); ?></h2>
        <p class="errorMsg"></p>
    </div>

    <!-- EDIT -->
    <div class="view viewEdit">

        <form id="frmeditEntrepreneur">

            <div id="entrepreneurProfileEdit">
                <div class="panel panel-default panel-open">
                    <div class="panel-heading">
                        <a class="btn-block" data-toggle="collapse" data-parent="#entrepreneurProfileEdit" href="#entrepreneurProfileDetails">
                            <span class="fa fa-chevron-right accordion-state-icon"></span>
                            <?php _e('Entrepreneur profile','bidxplugin');?>
                        </a>
                    </div>
                <div id="entrepreneurProfileDetails" class="panel-collapse collapse in">
                    <div class="panel-body">

                        <blockquote class="alert-info">
                            <?php _e('Complete this short form with information about you as entrepreneur. Be aware that investors and other members potentially interested in your business will be very interested to know more about you, your motivation and what makes you thrive as an entrepreneur. Treat this form as your first contact with, and pitch to potential investors and business partners.', 'bidxplugin')?>
                        </blockquote>

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label><?php _e('Summary','bidxplugin'); ?></label>
                                    <textarea name="summary" class="form-control" placeholder="<?php _e('Please describe yourself as an entrepreneur (max. 900 characters)','bidxplugin'); ?>" ></textarea>
                                </div>
                            </div>
<!--                             <div class="col-sm-6">
                                <div class="form-group">
                                    <label><?php _e('Focus industry','bidxplugin'); ?></label>
                                    <div class="controls">
                                        <select name="focusIndustry" multiple></select>
                                    </div>
                                </div>
                            </div>
 -->                        </div>

                        <div class="industrySectors">
                            <label><?php _e('Focus industry','bidxplugin'); ?></label>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">

                                <div class="form-group">
                                    <label><?php _e('Have you ever owned a business before?','bidxplugin'); ?></label>

                                    <div class="radio">
                                        <input type="radio" value="true" id="radio-prevRunBusinessYes" name="prevRunBusiness" data-toggle="radio" />
                                        <label for="radio-prevRunBusinessYes"><span></span><?php _e('Yes','bidxplugin'); ?></label>
                                    </div>
                                    <div class="radio">
                                        <input type="radio" value="false" id="radio-prevRunBusinessNo" name="prevRunBusiness" data-toggle="radio" />
                                        <label for="radio-prevRunBusinessNo"><span></span><?php _e('No','bidxplugin'); ?></label>
                                    </div>

                                </div>
                            </div>
                        </div>

                        <div class="toggle togglePrevRunBusiness">
                            <h4><?php _e('Previous businesses','bidxplugin'); ?>
                                <a href="#addPreviousBusiness" class="btn btn-xs btn-primary"><span class="fa fa-plus"></span> <?php _e('Add','bidxplugin'); ?></a>
                            </h4>
                        </div>

                        <div class="toggle togglePrevRunBusiness previousBusinessContainer"></div>
                        </div>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading  js-cv-panel">
                        <a class="btn-block" data-toggle="collapse" data-parent="#entrepreneurProfileEdit" href="#entrepreneurProfileCV">
                            <span class="fa fa-chevron-right accordion-state-icon"></span>
                            <?php _e('CV','bidxplugin');?>
                        </a>
                    </div>
                    <div id="entrepreneurProfileCV" class="panel-collapse collapse cvControl">
                        <div class="panel-body">
                            <div class="row cvContainer">
                                <div class="col-sm-6">

                                    <div class="form-group">
                                        <blockquote class="hasCV alert-info">
                                            <h3 class="documentName"></h3>
                                            <p class="createdDateTime"></p>
                                            <a href="#" class="downloadLink btn btn-sm btn-warning"><i class="fa fa-download"></i> <?php _e('Download CV','bidxplugin'); ?></a>
                                        </blockquote>

                                        <blockquote class="deletedCV alert-warning">
                                            <div class="row">
                                                <div class="col-sm-3">
                                                    <i class="fa fa-question-circle document-icon"></i>
                                                </div>
                                                <div class="col-sm-9">
                                                    <?php _e('Your CV has been removed from the media library.','bidxplugin'); ?>
                                                </div>
                                            </div>
                                        </blockquote>

                                        <blockquote class="noCV alert-warning">
                                            <?php _e('No CV uploaded yet','bidxplugin'); ?>
                                        </blockquote>
                                    </div>

                                </div>
                                <div class="col-sm-6">
                                    <a href="#changeCv" data-toggle="modal" class="btn btn-primary">
                                        <span class="hasCV"><?php _e('Select a different document'); ?></span>
                                        <span class="noCV"><?php _e('Select a document','bidxplugin'); ?></span>
                                        <span class="deletedCV"><?php _e('Replace missing document','bidxplugin'); ?></span>
                                    </a>

                                    <div class="changeCvModal modal fade">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                            <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                            <h3><?php _e('Check the file you want to use as your CV', 'bidxplugin' ); ?></h3>
                                            </div>
                                            <div class="modal-body">
                        <?php
                                                // Media app will only be inserted once, this is by design!
                                                //
                                                echo do_shortcode( '[bidx app="media"]' );
                        ?>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-primary btnSelectFile"><?php _e( 'Select file(s)', 'bidxplugin' ); ?></button>
                                                <button type="button" class="btn btn-link btnCancelSelectFile" data-dismiss="modal"><?php _e( 'Cancel', 'bidxplugin' ); ?></button>

                                            </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a class="btn-block" data-toggle="collapse" data-parent="#entrepreneurProfileEdit" href="#entrepreneurProfileDocs">
                            <span class="fa fa-chevron-right accordion-state-icon"></span>
                            <?php _e('Other documents','bidxplugin');?>
                        </a>
                    </div>
                    <div id="entrepreneurProfileDocs" class="panel-collapse collapse attachmentsControl">
                        <div class="panel-body">

                            <div class="attachmentsContainer"></div>

                            <button data-toggle="modal" class="btn btn-primary js-btn-add-attachments"><span class="fa fa-plus"></span> <?php _e('Add documents', 'bidxplugin')?></button>

                            <div class="addOtherDocsModal modal fade">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                            <h3><?php _e('Check the files you want to attach to your entrepreneur profile', 'bidxplugin' ); ?></h3>
                                        </div>
                                        <div class="modal-body">
<?php
                                            // Media app will only be inserted once, this is by design!
                                            //
                                            echo do_shortcode( '[bidx app="media"]' );
?>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-primary btnSelectFile"><?php _e( 'Select file(s)', 'bidxplugin' ); ?></button>
                                            <button type="button" class="btn btn-link btnCancelSelectFile" data-dismiss="modal"><?php _e( 'Cancel', 'bidxplugin' ); ?></button>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </form>
    </div>

    <div class="snippets hide">
        <div class="previousBusinessItem col-sm-4">
            <div class="well">
                <div class="form-group">
                    <label><?php _e('Name of company','bidxplugin'); ?></label>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-building-o"></i></span>
                        <input type="text" class="form-control" name="company" placeholder="<?php _e('Please enter the business name','bidxplugin'); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label><?php _e('What happened to this business?','bidxplugin'); ?></label>
                    <select name="businessOutcome"></select>
                </div>

                <div class="form-group">
                    <label><?php _e('Company website?','bidxplugin'); ?> <small class="text-muted"><?php _e('Optional','bidxplugin'); ?></small></label>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-globe"></i></span>
                        <input type="text" class="form-control" name="webSite" placeholder="<?php _e('Please enter the URL of the company','bidxplugin'); ?>">
                    </div>
                </div>

                <a href="#removeItem" class="btn btn-danger btn-sm btn-block"><?php _e('Remove this business','bidxplugin'); ?></a>
            </div>
        </div>

        <!-- Attachment -->
        <div class="attachmentItem col-md-4">
            <div class="media well">
                <div class="pull-left icons-rounded attachmentMissing"><i class="fa fa-question-circle text-primary-light"></i></div>
                <a class="pull-left documentLink img-cropper" href="#">
                    <div class="icons-rounded attachmentDefault"><i class="fa fa-file-text-o text-primary-light"></i></div>
                    <img class="media-object img-rounded documentImage">
                </a>
                <div class="media-body">
                    <strong class="media-heading documentName"></strong>
                    <div class="createdDateTime"></div>
                    <div class="purpose"></div>
                    <div class="documentType"></div>
                </div>
                <a href="#removeItem" class="btn btn-danger btn-sm btn-block clearboth top-margin-lineheight"><?php _e('Remove','bidxplugin'); ?></a>
            </div>
        </div>
    </div>

</div><!-- // row -->
