<div id="editEntrepreneur" class="mainState mainStateEditEntrepreneur">

    <!-- LOAD -->
    <div class="view viewLoad alert alert-info text-center">
        <div class="progress progress-striped active">
            <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                <?php _e('Retrieving entrepreneur information...','bidxplugin'); ?>
            </div>
        </div>
    </div>

    <!-- ERROR -->
    <div class="view viewError alert alert-warning">
        <h2><?php _e('Error','bidxplugin'); ?></h2>
        <p class="errorMsg"></p>
    </div>

    <!-- EDIT -->
    <div class="view viewEdit">

        <form id="frmeditEntrepreneur">

            <div id="accordionEntrepreneurEdit">
                <div class="panel panel-default panel-open">
                    <div class="panel-heading">
                        <a class="btn-block" data-toggle="collapse" data-parent="#accordionEntrepreneurEdit" href="#accordionEntrepreneurDetails">
                            <span class="fa fa-chevron-right accordion-state-icon"></span>
                            <?php _e('Entrepreneur profile','bidxplugin');?>
                        </a>
                    </div>
                <div id="accordionEntrepreneurDetails" class="panel-collapse collapse in" style="overflow: visible;">
                    <div class="panel-body">

                        <div class="alert alert-info">
                            <?php _e('Complete this short form with information about you as entrepreneur. Be aware that investors and other members potentially interested in your business will be very interested to know more about you, your motivation and what makes you thrive as an entrepreneur. Treat this form as your first contact with, and pitch to potential investors and business partners.', 'bidxplugin')?>
                        </div>

                        <div class="row">
                            <div class="col-sm-12">

                                <div class="form-group">
                                    <label><?php _e('Summary','bidxplugin'); ?></label>
                                    <textarea name="summary" class="form-control" placeholder="<?php _e('Please describe yourself as an entrepreneur (max. 900 characters)','bidxplugin'); ?>" ></textarea>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label><?php _e('Focus industry','bidxplugin'); ?></label>
                                    <div class="controls">
                                        <select name="focusIndustry" multiple></select>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">

                                <div class="form-group">
                                    <label><?php _e('Have you ever owned a business before?','bidxplugin'); ?></label>
                                    <label class="radio"><input type="radio" value="true" name="prevRunBusiness" data-toggle="radio"/> <?php _e('Yes','bidxplugin'); ?></label>
                                    <label class="radio"><input type="radio" value="false" name="prevRunBusiness" data-toggle="radio"/> <?php _e('No','bidxplugin'); ?></label>
                                </div>
                            </div>
                        </div>

                        <div class="toggle togglePrevRunBusiness intermediate-row">
                            <h6><?php _e('Previous businesses','bidxplugin'); ?></h6>
                            <a href="#addPreviousBusiness" class="btn btn-primary"><span class="fa fa-plus"></span><?php _e('Add','bidxplugin'); ?></a>
                        </div>

                        <div class="toggle togglePrevRunBusiness previousBusinessContainer"></div>
                        </div>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a class="btn-block" data-toggle="collapse" data-parent="#accordionEntrepreneurEdit" href="#accordionEntrepreneurCV">
                            <span class="fa fa-chevron-right accordion-state-icon"></span>
                            <?php _e('CV','bidxplugin');?>
                        </a>
                    </div>
                    <div id="accordionEntrepreneurCV" class="panel-collapse collapse cvControl">
                        <div class="panel-body">
                            <div class="row cvContainer">
                                <div class="col-sm-4">

                                    <div class="form-group">
                                        <div class="hasCV">
                                            <h3 class="documentName"></h3>
                                            <p class="uploadedDateTime"></p>

                                            <a href="#" class="documentLink"><?php _e('Download CV','bidxplugin'); ?></a>
                                        </div>

                                        <div class="noCV alert alert-warning">
                                            <?php _e('No CV uploaded yet','bidxplugin'); ?>
                                        </div>
                                    </div>

                                </div>
                                <div class="col-sm-8">
                                    <a href="#changeCv" data-toggle="modal" class="btn btn-primary"><span class="hasCV"><?php _e('Or select a different document'); ?></span><span class="noCV"><?php _e('Select a document','bidxplugin'); ?></span></a>

                                    <div class="changeCvModal modal fade">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                            <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                            <h3><?php _e('Check the file you want to use as your CV', 'bidxplugin' ); ?></h3>
                                            </div>
                                            <div class="modal-body">
                        <?php
                                                // Media app will only be inserted once, this is by design!
                                                //
                                                echo do_shortcode( '[bidx app="media"]' );
                        ?>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="#" class="btn btn-primary btnSelectFile"><?php _e( 'Select file(s)', 'bidxplugin' ); ?></a>
                                                <a href="#" class="btn btnCancelSelectFile"><?php _e( 'Cancel', 'bidxplugin' ); ?></a>
                                            </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <a class="btn-block" data-toggle="collapse" data-parent="#accordionEntrepreneurEdit" href="#accordionEntrepreneurDocs">
                            <span class="fa fa-chevron-right accordion-state-icon"></span>
                            <?php _e('Other documents','bidxplugin');?>
                        </a>
                    </div>
                    <div id="accordionEntrepreneurDocs" class="panel-collapse collapse attachmentsControl">
                        <div class="panel-body">

                            <div class="attachmentsContainer"></div>

                            <button data-target="#addotherdocs" data-toggle="modal" class="btn btn-primary"><?php _e('Add documents', 'bidxplugin')?></button>

                            <div class="addAttachmentsModal modal fade" id="addotherdocs">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                            <h3><?php _e('Check the files you want to attach to your entrepreneur profile', 'bidxplugin' ); ?></h3>
                                        </div>
                                        <div class="modal-body">
<?php
                                            // Media app will only be inserted once, this is by design!
                                            //
                                            echo do_shortcode( '[bidx app="media"]' );
?>
                                        </div>
                                        <div class="modal-footer">
                                            <a href="#" class="btn btn-primary btnSelectFile"><?php _e( 'Select file(s)', 'bidxplugin' ); ?></a>
                                            <a href="#" class="btn btnCancelSelectFile"><?php _e( 'Cancel', 'bidxplugin' ); ?></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </form>
    </div>

    <div class="snippets hide">
        <div class="previousBusinessItem col-sm-4">
            <div class="well">
                <div class="form-group">
                    <label><?php _e('Name of company','bidxplugin'); ?></label>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-building-o"></i></span>
                        <input type="text" class="form-control" name="company" placeholder="<?php _e('Please enter the business name','bidxplugin'); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label><?php _e('What happened to this business?','bidxplugin'); ?></label>
                    <select name="businessOutcome"></select>
                </div>

                <div class="form-group">
                    <label><?php _e('Company website?','bidxplugin'); ?></label>
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-globe"></i></span>
                        <input type="text" class="form-control" name="webSite" placeholder="<?php _e('Please enter the URL of the company','bidxplugin'); ?>">
                    </div>
                </div>

                <a href="#removeItem" class="btn btn-danger btn-mini btn-block"><?php _e('Remove this business','bidxplugin'); ?></a>
            </div>
        </div>

        <!-- Attachment -->
        <div class="attachmentItem col-sm-4">
            <div class="well">
                <div class="row">
                    <div class="col-sm-4">
                        <a href="#" class="documentLink"><img class="img-rounded documentImage"></a>
                    </div>
                    <div class="col-sm-7">
                        <h3 class="documentName"></h3>
                        <p class="createdDateTime"></p>
                        <p class="purpose"></p>
                        <p class="documentType"></p>
                    </div>
                </div>
                <a href="#removeItem" class="btn btn-danger btn-mini btn-block"><?php _e('Remove from profile','bidxplugin'); ?></a>
            </div>
        </div>

    </div>

</div><!-- // row -->
