<div id="editMember" class="mainState mainStateEditMember">

    <!-- LOAD -->
    <div class="view viewLoad alert alert-info text-center">
        <div class="progress progress-striped active">
            <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                <?php _e('Retrieving member information...','bidxplugin'); ?>
            </div>
        </div>
    </div>

    <!-- ERROR -->
    <div class="view viewError alert alert-warning">
        <h2><?php _e('Error','bidxplugin'); ?></h2>
        <p class="errorMsg"></p>
    </div>

    <!-- EDIT -->
    <div class="view viewEdit">

        <form id="frmeditMember">
        <div class="row">
            <div class="col-sm-12">


            <div class="panel-group" id="accordionMemberEdit">
            <div class="panel panel-default panel-open">
                <div class="panel-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionMemberEdit" href="#accordionMemberPersonalDetails">
                        <span class="fui-arrow-right accordion-state-icon"></span>
                        <?php _e('Personal details','bidxplugin');?>
                    </a>
                </div>
                <div id="accordionMemberPersonalDetails" class="panel-collapse collapse in" style="overflow: visible;">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-6">

                                <div class="form-group">
                                    <label><?php _e('First name','bidxplugin'); ?></label>
                                    <input type="text" class="form-control" name="personalDetails.firstName" placeholder="<?php _e('Please enter your first name','bidxplugin'); ?>">
                                </div>

                                <div class="form-group">
                                    <label><?php _e('Last name','bidxplugin'); ?></label>
                                    <input type="text" class="form-control" name="personalDetails.lastName" placeholder="<?php _e('Please enter your last name','bidxplugin'); ?>">
                                </div>

                                <div class="form-group">
                                    <label><?php _e('Professional title','bidxplugin'); ?></label>
                                    <input type="text" class="form-control" name="personalDetails.professionalTitle" placeholder="<?php _e('Please enter your professional title','bidxplugin'); ?>">
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <div class="profilePictureControl">
                                    <label><?php _e('Profile picture','bidxplugin'); ?></label>
                                    <div class="profilePictureContainer"></div>
                                    <a href="#changeProfilePicture" data-toggle="modal" data-target="#ProfilePictureModal" class="btn btn-default"><?php _e('Change profile picture','bidxplugin');?></a>

                                    <div class="changeProfilePictureModal modal fade" id="ProfilePictureModal" role="dialog" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                    <h3><?php _e('Select the file you want to use for a profile picture', 'bidxplugin' ); ?></h3>
                                                </div>
                                                <div class="modal-body">
    <?php
                                                    // Media app will only be inserted once, this is by design!
                                                    //
                                                    echo do_shortcode( '[bidx app="media"]' );
    ?>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-primary btnSelectFile"><?php _e( 'Select file', 'bidxplugin' ); ?></button>
                                                    <button type="button" class="btn btn-link btnCancelSelectFile" data-dismiss="modal"><?php _e( 'Cancel', 'bidxplugin' ); ?></button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">

                                <div class="form-group">
                                    <label><?php _e('Gender','bidxplugin'); ?></label>
                                    <label class="radio"><input type="radio" value="m" name="personalDetails.gender" data-toggle="radio"/> <?php _e('Male'); ?></label>
                                    <label class="radio"><input type="radio" value="f" name="personalDetails.gender" data-toggle="radio"/> <?php _e('Female'); ?></label>
                                </div>

                            </div>
                            <div class="col-sm-6">

                                <div class="form-group">
                                    <label><?php _e('Date of birth','bidxplugin'); ?></label>
                                    <input type="text" class="form-control" name="personalDetails.dateOfBirth" data-type="date" placeholder="<?php _e('Please type your date of birth'); ?>">
                                </div>

                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">

                                <div class="form-group ">
                                    <label><?php _e('Nationality','bidxplugin'); ?></label>
                                    <select name="personalDetails.nationality" ></select>
                                </div> <!-- // form-group -->

                            </div>
                            <div class="col-sm-6">

                                <div class="form-group ">
                                    <label><?php _e('Highest Education','bidxplugin'); ?></label>
                                    <select name="personalDetails.highestEducation"></select>
                                </div>

                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">

                                <div class="form-group ">
                                    <label><?php _e('Email address','bidxplugin'); ?></label>
                                    <div class="input-group">
                                        <span class="input-group-addon">E-mail icon</span>
                                        <input type="email" class="form-control" name="personalDetails.emailAddress" placeholder="<?php _e('Please enter your email address','bidxplugin'); ?>" />
                                    </div>
                                </div>

                            </div>
                            <div class="col-sm-6">

                                <div class="form-group" >
                                    <label><?php _e('LinkedIn profile','bidxplugin'); ?></label>
                                    <div class="input-group">
                                        <span class="input-group-addon">LinkedIn icon</span>
                                        <input type="text" class="form-control" name="personalDetails.linkedIn" placeholder="<?php _e('Please enter your LinkedIn profile URL','bidxplugin'); ?>" />
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">

                                <div class="form-group">
                                    <label><?php _e('Skype','bidxplugin'); ?></label>
                                    <div class="input-group">
                                        <span class="input-group-addon">Skype icon</span>
                                        <input type="text" class="form-control" name="personalDetails.skype" placeholder="<?php _e('Please enter your Skype username','bidxplugin'); ?>" />
                                    </div>
                                </div>

                            </div>
                            <div class="col-sm-6">

                                <div class="form-group">
                                    <label><?php _e('Facebook profile','bidxplugin'); ?></label>
                                    <div class="input-group">
                                        <span class="input-group-addon">Facebook icon</span>
                                        <input type="text" class="form-control" name="personalDetails.facebook" placeholder="<?php _e('Please enter you Facebook profile name','bidxplugin'); ?>" />
                                    </div>
                                </div>

                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">

                                <div class="form-group">
                                    <label><?php _e('Twitter','bidxplugin'); ?></label>
                                    <div class="input-group">
                                        <span class="input-group-addon">@</span>
                                        <input type="text" class="form-control" name="personalDetails.twitter" placeholder="<?php _e('Please enter your Twitter name','bidxplugin'); ?>" />
                                    </div>
                                </div>

                            </div>
                            <div class="col-sm-6">

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionMemberEdit" href="#accordionMemberLanguage">
                        <span class="fui-arrow-right accordion-state-icon"></span>
                        <?php _e('Language','bidxplugin');?>
                    </a>
                </div>
                <div id="accordionMemberLanguage" class="panel-collapse collapse">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-6">
                                <div class="form-group addLanguageGroup">
                                    <label><?php _e('Select the languages you speak:','bidxplugin'); ?></label>
                                    <div class="input-group">
                                        <input class="form-control" type="text" name="addLanguage" autocomplete="off" disabled />
                                        <span class="input-group-btn">
                                            <button type="button" class="btn btn-default js-btn-add-language" disabled><?php _e('Add to list','bidxplugin'); ?></button>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-4">
                                <strong><?php _e('List of your languages','bidxplugin'); ?></strong>
                            </div>
                            <div class="col-sm-4">
                                <strong><?php _e('Choose your mother tongue','bidxplugin'); ?></strong>
                            </div>
                        </div>

                        <div class="languageList clearfix"></div>
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionMemberEdit" href="#accordionMemberAddress">
                        <span class="fui-arrow-right accordion-state-icon"></span>
                        <?php _e('Your current address','bidxplugin');?>
                    </a>
                </div>
                <div id="accordionMemberAddress" class="panel-collapse collapse addressItem">
                    <div class="panel-body">

                        <div class="row">
                            <div class="col-sm-6">

                                <input type="hidden" name="personalDetails.address[0].coordinates"    />

                                <div class="form-group">
                                    <label><?php _e('Country','bidxplugin'); ?></label>
                                    <select name="personalDetails.address[0].country" ></select>
                                </div>

                                <div class="form-group">
                                    <label><?php _e('City','bidxplugin'); ?></label>
                                    <input type="text" class="form-control" name="personalDetails.address[0].cityTown" placeholder="<?php _e('Please enter your city','bidxplugin'); ?>" />
                                </div>

                                <div class="form-group">
                                    <label><?php _e('Street','bidxplugin'); ?></label>
                                    <input type="text" class="form-control" name="personalDetails.address[0].street" placeholder="<?php _e('Please type your street','bidxplugin'); ?>" />
                                </div>

                                <div class="form-group">
                                    <label><?php _e('Building number','bidxplugin'); ?></label>
                                    <input type="text" class="form-control" name="personalDetails.address[0].streetNumber" placeholder="<?php _e('Please enter your building number','bidxplugin'); ?>" />
                                </div>

                                <div class="form-group">
                                    <label><?php _e('Postal code','bidxplugin'); ?></label>
                                    <input type="text" class="form-control" name="personalDetails.address[0].postalCode" placeholder="<?php _e('Please enter your postcode','bidxplugin'); ?>" />
                                </div>

                                <div class="form-group">
                                    <label><?php _e('Neighborhood','bidxplugin'); ?></label>
                                    <input type="text" class="form-control" name="personalDetails.address[0].neighborhood" placeholder="<?php _e('Please enter your neighborhood','bidxplugin'); ?>" />
                                </div>


                            </div>

                            <div class="col-sm-6">
                                <div class="currentAddressMap"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionMemberEdit" href="#accordionMemberContact">
                        <span class="fui-arrow-right accordion-state-icon"></span>
                        <?php _e('Your contact details?','bidxplugin');?>
                    </a>
                </div>
                <div id="accordionMemberContact" class="panel-collapse collapse contactDetailItem">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-6">

                                <div class="form-group">
                                    <label><?php _e('Landline','bidxplugin'); ?></label>
                                    <div class="input-group">
                                        <span class="input-group-addon">Old telephone icon</span>
                                        <input type="text" class="form-control" name="personalDetails.contactDetail[0].landLine" placeholder="<?php _e('Please enter your landline number','bidxplugin'); ?>" />
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label><?php _e('Mobile','bidxplugin'); ?></label>
                                    <div class="input-group">
                                        <span class="input-group-addon">Mobile icon</span>
                                        <input type="text" class="form-control" name="personalDetails.contactDetail[0].mobile" placeholder="<?php _e('Please enter your mobile number','bidxplugin'); ?>" />
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label><?php _e('Fax','bidxplugin'); ?></label>
                                    <div class="input-group">
                                        <span class="input-group-addon">Fax icon</span>
                                        <input type="text" class="form-control" name="personalDetails.contactDetail[0].fax" placeholder="<?php _e('Please enter your fax number','bidxplugin'); ?>" />
                                    </div>
                                </div>

                            </div><!-- // col-sm-6 - left form column -->

                            <div class="col-sm-6">
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionMemberEdit" href="#accordionMemberDocuments">
                        <span class="fui-arrow-right accordion-state-icon"></span>
                        <?php _e('Documents','bidxplugin');?>
                    </a>
                </div>
                <div id="accordionMemberDocuments" class="panel-collapse collapse attachmentsControl">
                    <div class="panel-body">
                    <div class="attachmentsContainer"></div>

                    <a href="#addAttachments" data-toggle="modal" class="btn btn-primary"><?php _e('Add documents', 'bidxplugin')?></a>

                    <div class="addAttachmentsModal modal fade">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                    <h3><?php _e('Check the files you want to attach to your member profile', 'bidxplugin' ); ?></h3>
                                </div>
                                <div class="modal-body">
<?php
                                    echo do_shortcode( '[bidx app="media"]' );
?>
                                </div>
                                <div class="modal-footer">
                                    <a href="#" class="btn btn-primary btnSelectFile"><?php _e( 'Select file(s)', 'bidxplugin' ); ?></a>
                                    <a href="#" class="btn btnCancelSelectFile"><?php _e( 'Cancel', 'bidxplugin' ); ?></a>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
                </div>
            </div>

            </div>

            </div>
        </div>
        </form>
    </div>

    <div class="snippets hide">

        <!-- Language item -->
        <div class="row languageItem">
            <div class="col-sm-4">
                <label class="pull-left languageDescr"></label>
                <button class="btn pull-right btnRemoveLanguage"><span class="">Trash icon</span></button>
            </div>
            <div class="col-sm-4">
                <button class="btn btnSetMotherLanguage"><?php _e('This is your mother tongue','bidxplugin'); ?></button>
                <p class="isCurrentMotherLanguage"><?php _e('My mother tongue','bidxplugin'); ?></p>
            </div>
        </div>

        <!-- Attachment -->
        <div class="attachmentItem col-sm-4">
            <div class="well">
                <div class="row">
                    <div class="col-sm-4">
                        <a href="#" class="documentLink"><img class="img-rounded documentImage"></a>
                    </div>
                    <div class="col-sm-7">
                        <h3 class="documentName"></h3>
                        <p class="createdDateTime"></p>
                        <p class="purpose"></p>
                        <p class="documentType"></p>
                    </div>
                </div>
                <a href="#removeItem" class="btn btn-danger btn-mini btn-block"><?php _e('Remove from profile','bidxplugin'); ?></a>
            </div>
        </div>
    </div>

</div><!-- // row -->
