<div id="editMember" class="row-fluid mainState mainStateEditMember">

    <!-- LOAD -->
    <div class="view viewLoad span12">
        <span><?php _e('Retrieving member information...','bidxplugin'); ?></span>
    </div>

    <!-- ERROR -->
    <div class="view viewError span12">
        <h2><?php _e('Error','bidxplugin'); ?></h2>
        <p class="errorMsg"></p>
    </div>

    <!-- EDIT -->
    <div class="view viewEdit">

        <form id="frmeditMember">

            <div class="span3">
                <ul class="nav nav-list nav-editMember nav-edit hidden-phone">
                    <li><a href="#editMember/personalDetail"><?php _e('Personal details','bidxplugin'); ?></a>
                    <li><a href="#editMember/language"><?php _e('Language','bidxplugin'); ?></a>
                    <li><a href="#editMember/currentAddress"><?php _e('Current address','bidxplugin'); ?></a>
                    <li><a href="#editMember/contactDetails"><?php _e('Contact details','bidxplugin'); ?></a>
                    <li><a href="#editMember/documents"><?php _e('Documents','bidxplugin'); ?></a>
                </ul>
            </div>

            <div class="span9">

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editMember/personalDetail"></span>
                    <legend><?php _e('Personal details','bidxplugin'); ?></legend>

                    <div class="row-fluid">
                        <div class="span5">

                            <div class="control-group">
                                <label class="control-label"><?php _e('First name','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.firstName" placeholder="<?php _e('Please enter your first name','bidxplugin'); ?>">
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label"><?php _e('Last name','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.lastName" placeholder="<?php _e('Please enter your last name','bidxplugin'); ?>">
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label"><?php _e('Professional title','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.professionalTitle" placeholder="<?php _e('Please enter your professional title','bidxplugin'); ?>">
                                </div>
                            </div>
                        </div>

                        <div class="span5 offset1">
                            <div class="control-group profilePictureControl">
                                <label class="control-label"><?php _e('Profile picture','bidxplugin'); ?></label>
                                <div class="controls">
                                    <div class="profilePictureContainer"></div>
                                    <a href="#changeProfilePicture" class="btn"><?php _e('Change profile picture','bidxplugin');?></a>

                                    <div class="changeProfilePictureModal modal hide fade">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                            <h3><?php _e('Select the file you want to use for a profile picture', 'bidxplugin' ); ?></h3>
                                        </div>
                                        <div class="modal-body">
    <?php
                                            // Media app will only be inserted once, this is by design!
                                            //
                                            echo do_shortcode( '[bidx app="media"]' );
    ?>
                                        </div>
                                        <div class="modal-footer">
                                            <a href="#" class="btn btn-primary btnSelectFile"><?php _e( 'Select file', 'bidxplugin' ); ?></a>
                                            <a href="#" class="btn btnCancelSelectFile"><?php _e( 'Cancel', 'bidxplugin' ); ?></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span5">

                            <div class="control-group">
                                <label class="control-label"><?php _e('Gender','bidxplugin'); ?></label>
                                <div class="controls">
                                    <label class="radio"><input type="radio" value="m" name="personalDetails.gender" data-toggle="radio"/> <?php _e('Male'); ?></label>
                                    <label class="radio"><input type="radio" value="f" name="personalDetails.gender" data-toggle="radio"/> <?php _e('Female'); ?></label>
                                </div>
                            </div>

                        </div>
                        <div class="span5 offset1">

                            <div class="control-group">
                                <label class="control-label"><?php _e('Date of birth','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.dateOfBirth" data-type="date" placeholder="<?php _e('Please type your date of birth'); ?>">
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span5">

                            <div class="control-group ">
                                <label class="control-label"><?php _e('Nationality','bidxplugin'); ?></label>
                                <div class="controls">
                                    <select name="personalDetails.nationality" ></select>
                                </div> <!-- // controls -->
                            </div> <!-- // control-group -->

                        </div>
                        <div class="span5 offset1">

                            <div class="control-group ">
                                <label class="control-label"><?php _e('Highest Education','bidxplugin'); ?></label>
                                <div class="controls">
                                    <select name="personalDetails.highestEducation"></select>
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span5">

                            <div class="control-group ">
                                <label class="control-label"><?php _e('Email address','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="email" name="personalDetails.emailAddress" placeholder="<?php _e('Please enter your email address','bidxplugin'); ?>" />
                                </div>
                            </div>

                        </div>
                        <div class="span5 offset1">

                            <div class="control-group" >
                                <label class="control-label"><?php _e('LinkedIn profile','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.linkedIn" placeholder="<?php _e('Please enter your LinkedIn profile URL','bidxplugin'); ?>" />
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span5">

                            <div class="control-group">
                                <label class="control-label"><?php _e('Skype','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.skype" placeholder="<?php _e('Please enter your Skype username','bidxplugin'); ?>" />
                                </div>
                            </div>

                        </div>
                        <div class="span5 offset1">

                            <div class="control-group">
                                <label class="control-label"><?php _e('Facebook profile','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.facebook" placeholder="<?php _e('Please enter you Facebook profile name','bidxplugin'); ?>" />
                                </div>
                            </div>

                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span5">

                            <div class="control-group">
                                <label class="control-label"><?php _e('Twitter','bidxplugin'); ?></label>
                                <div class="controls">
                                    <div class="input-prepend">
                                        <span class="add-on">@</span>
                                        <input type="text" name="personalDetails.twitter" placeholder="<?php _e('Please enter your Twitter name','bidxplugin'); ?>" />
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="span5 offset1">

                        </div>
                    </div>
                </fieldset>

                <fieldset class="well">
                    <span class="scrollPositionMarker" id="editMember/language"></span>
                    <legend><?php _e('Language','bidxplugin'); ?></legend>

                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group addLanguageGroup">
                                <label class="control-label"><?php _e('Select the languages you speak:','bidxplugin'); ?></label>
                                <div class="controls">
                                    <div class="row-fluid">
                                        <div class="input-append">
                                            <input class="span10" type="text" name="addLanguage" autocomplete="off" disabled />
                                            <button type="button" class="btn btn-large btnAddLanguage" disabled><?php _e('Add to list','bidxplugin'); ?></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row-fluid">
                        <div class="span4">
                            <strong><?php _e('List of your languages','bidxplugin'); ?></strong>
                        </div>
                        <div class="span4">
                            <strong><?php _e('Choose your mother tongue','bidxplugin'); ?></strong>
                        </div>
                    </div>

                    <div class="languageList clearfix"></div>
                </fieldset>

                <fieldset class="well addressItem">
                    <span class="scrollPositionMarker" id="editMember/currentAddress"></span>
                    <legend><?php _e('Your current address','bidxplugin'); ?></legend>

                    <div class="row-fluid">
                        <div class="span5">

                            <input type="hidden" name="personalDetails.address[0].coordinates"    />

                            <div class="control-group">
                                <label class="control-label"><?php _e('Country','bidxplugin'); ?></label>
                                <div class="controls">
                                    <select name="personalDetails.address[0].country" ></select>
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label"><?php _e('City','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.address[0].cityTown" placeholder="<?php _e('Please enter your city','bidxplugin'); ?>" />
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label"><?php _e('Street','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.address[0].street" placeholder="<?php _e('Please type your street','bidxplugin'); ?>" />
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label"><?php _e('Building number','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.address[0].streetNumber" placeholder="<?php _e('Please enter your building number','bidxplugin'); ?>" />
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label"><?php _e('Postal code','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.address[0].postalCode" placeholder="<?php _e('Please enter your postcode','bidxplugin'); ?>" />
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label"><?php _e('Neighborhood','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.address[0].neighborhood" placeholder="<?php _e('Please enter your neighborhood','bidxplugin'); ?>" />
                                </div>
                            </div>


                        </div>

                        <div class="span6 offset1">
                            <div class="currentAddressMap"></div>
                        </div>
                    </div>
                </fieldset>

                <fieldset class="well contactDetailItem">
                    <span class="scrollPositionMarker" id="editMember/contactDetails"></span>
                    <legend><?php _e('Your contact details?','bidxplugin'); ?></legend>

                    <div class="row-fluid">
                        <div class="span5">

                            <div class="control-group">
                                <label class="control-label"><?php _e('Landline','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.contactDetail[0].landLine" placeholder="<?php _e('Please enter your landline number','bidxplugin'); ?>" />
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label"><?php _e('Mobile','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.contactDetail[0].mobile" placeholder="<?php _e('Please enter your mobile number','bidxplugin'); ?>" />
                                </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label"><?php _e('Fax','bidxplugin'); ?></label>
                                <div class="controls">
                                    <input type="text" name="personalDetails.contactDetail[0].fax" placeholder="<?php _e('Please enter your fax number','bidxplugin'); ?>" />
                                </div>
                            </div>

                        </div><!-- // span5 - left form column -->

                        <div class="span5">
                        </div>
                    </div>
                </fieldset>

                <fieldset class="well attachmentsControl">
                    <span class="scrollPositionMarker" id="editMember/documents"></span>
                    <legend><?php _e('Documents','bidxplugin'); ?></legend>

                    <div class="attachmentsContainer"></div>

                    <a href="#addAttachments" data-toggle="modal" class="btn btn-primary"><?php _e('Add documents', 'bidxplugin')?></a>

                    <div class="addAttachmentsModal modal hide fade">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h3><?php _e('Check the files you want to attach to your member profile', 'bidxplugin' ); ?></h3>
                      </div>
                        <div class="modal-body">
    <?php
                            // Media app will only be inserted once, this is by design!
                            //
                            echo do_shortcode( '[bidx app="media"]' );
    ?>
                        </div>
                        <div class="modal-footer">
                            <a href="#" class="btn btn-primary btnSelectFile"><?php _e( 'Select file(s)', 'bidxplugin' ); ?></a>
                            <a href="#" class="btn btnCancelSelectFile"><?php _e( 'Cancel', 'bidxplugin' ); ?></a>
                        </div>
                    </div>

                </fieldset>
            </div>

        </form>
    </div>

    <div class="snippets hide">

        <!-- Language item -->
        <div class="row-fluid languageItem">
            <div class="span4">
                <label class="pull-left languageDescr"></label>
                <button class="btn pull-right btnRemoveLanguage"><i class="icon-trash"></i></button>
            </div>
            <div class="span4">
                <button class="btn btnSetMotherLanguage"><?php _e('This is your mother tongue','bidxplugin'); ?></button>
                <p class="isCurrentMotherLanguage"><?php _e('My mother tongue','bidxplugin'); ?></p>
            </div>
        </div>

        <!-- Attachment -->
        <div class="attachmentItem span4 well well-white">
            <div class="row-fluid">
                <div class="span4">
                    <a href="#" class="documentLink"><img class="img-rounded documentImage"></a>
                </div>
                <div class="span7">
                    <h3 class="documentName"></h3>
                    <p class="createdDateTime"></p>
                    <p class="purpose"></p>
                    <p class="documentType"></p>
                </div>
            </div>
            <a href="#removeItem" class="btn btn-danger btn-mini btn-block"><?php _e('Remove from profile','bidxplugin'); ?></a>
        </div>
    </div>

</div><!-- // row -->
