<?php
    $sessionData    = BidxCommon::$staticSession;
    $entities       = isset( $sessionData->data->wp->entities ) ? $sessionData->data->wp->entities : null;

    // Create entrepreneur
    //
    if ( isset( $entities->bidxEntrepreneurProfile ) ) {
?>
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong><?php _e('Create a business summary', 'bidxplugin')?></strong>
            </div>
            <div class="panel-body">
                <em><?php _e('Create your business', 'bidxplugin')?></em>
                <a href="<?php echo _l('businesssummary');?>/#createBusinessSummary" class="btn btn-primary pull-right"><i class="fa fa-plus-circle"></i> <?php _e('Create','bidxplugin')?></a>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <strong><?php _e('Do you own or participate in a company?', 'bidxplugin')?></strong>
            </div>
            <div class="panel-body">
                <em><?php _e('Add a company', 'bidxplugin')?></em>
                <a href="<?php echo _l('company');?>/#createCompany" class="btn btn-primary pull-right"><i class="fa fa-plus-circle"></i> <?php _e('Add','bidxplugin'); ?></a>
            </div>
        </div>
<?php
    }
    if ( !isset( $entities->bidxEntrepreneurProfile ) ) {
?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong><?php _e('Become an entrepreneur', 'bidxtheme')?></strong>
        </div>
        <div class="panel-body">
            <em><?php _e('Create your entrepreneur profile', 'bidxtheme')?></em>
            <a href="<?php echo _l('member');?>/#createEntrepreneur" class="btn btn-primary pull-right"><i class="fa fa-plus-circle"></i> <?php _e('Create','bidxtheme')?></a>
        </div>
    </div>
<?php
    } else {
?>
    <div class="panel panel-default">
        <div class="panel-body">
<?php
            printf( __( 'View your %sentrepreneur profile%s', 'bidxtheme' ), '<a href="'._l('member').'/#entrepreneur-profile">', '</a>' );
?>
        </div>
    </div>
<?php
    }
?>
