<?php
    $sessionData    = BidxCommon::$staticSession;
    $entities       = isset( $sessionData->data->wp->entities ) ? $sessionData->data->wp->entities : null;

    // Create investor
    //
    if ( !isset( $entities->bidxInvestorProfile )) {
?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong><?php _e('Become an investor', 'bidxtheme')?></strong>
        </div>
        <div class="panel-body">
            <em><?php _e('Create your resources', 'bidxtheme')?></em>
            <a href="/member/#createInvestor" class="btn btn-primary pull-right"><i class="fa fa-plus-circle"></i> <?php _e('Invest','bidxtheme')?></a>
        </div>
    </div>
<?php
    } else {
?>
    <div class="panel panel-default">
        <div class="panel-body">
<?php
        printf( __( 'View your %sinvestor profile%s', 'bidxtheme' ), '<a href="/member/#investor-profile">', '</a>' );
?>
        </div>
    </div>
<?php
    }
?>
