<?php
    $sessionData    = BidxCommon::$staticSession;
    $entities       = isset( $sessionData->data->wp->entities ) ? $sessionData->data->wp->entities : null;

    // Create investor
    //
    if ( !isset( $entities->bidxInvestorProfile )) {
?>
    <div class="call-to-action clearfix">
        <div class="pull-left">
            <div><strong><?php _e('Become an investor', 'bidxtheme')?></strong></div>
            <em><?php _e('Create your resources', 'bidxtheme')?></em>
        </div>
        <a href="/member/#createInvestor" class="btn btn-primary bidx-theme-colour-one pull-right"><i class="bidx-plus"></i><?php _e('Invest','bidxtheme')?></a>
    </div>
<?php
    } else {
?>
    <div class="call-to-action clearfix">
        <div class="pull-left">
<?php
        printf( __( 'View your %sinvestor profile%s', 'bidxtheme' ), '<a href="/member/#investor-profile">', '</a>' );
?>
        </div>
    </div>
<?php
    }
?>
