<?php

$data                           = $this->data;
$member                         = isset($this->data->member->displayName) ?  $this->data->member->displayName: NULL ;
$ownProfile                     = $this->data->isMyProfile;
$entities                       = $this->sessionData->data->wp->entities;
$isSuperAdmin                   = is_super_admin();
$canEdit                        = $this->data->bidxMemberProfile->bidxMeta->bidxCanEdit;
$memberId                       = isset( $this->data->member->bidxMeta->bidxMemberId ) ? $this->data->member->bidxMeta->bidxMemberId : null ;
$loggedInMemberId               = isset( $this -> sessionData -> data -> id ) ? $this -> sessionData -> data -> id : null;
$authenticated                  = isset( $this -> sessionData -> authenticated ) && $this -> sessionData -> authenticated ==  'true';
$isLoggedinMemberIsMentor       = isset( $this -> sessionData -> data -> wp -> entities -> bidxMentorProfile ) ? $this -> sessionData -> data -> wp -> entities -> bidxMentorProfile : null;
$isLoggedinMemberIsInvestor     = isset( $this -> sessionData -> data -> wp -> entities -> bidxInvestorProfile ) ? $this -> sessionData -> data -> wp -> entities -> bidxInvestorProfile : null;
$isLoggedinMemberIsEntrepreneur = isset( $this -> sessionData -> data -> wp -> entities -> bidxEntrepreneurProfile ) ? true : false;

$groupIds                       = array_keys ( (array)$this -> sessionData -> data -> groups );
$inGroup                        = in_array( $this -> sessionData -> data -> currentGroup, $groupIds);
$personalDetails                = isset( $data->bidxMemberProfile->personalDetails ) ? $data->bidxMemberProfile->personalDetails : NULL;
$isEntrepreneur                 = isset( $data->bidxEntrepreneurProfile ) ? $data->bidxEntrepreneurProfile : NULL ;
$isInvestor                     = isset( $data->bidxInvestorProfile ) ? $data->bidxInvestorProfile : NULL;
$isMentor                       = isset( $data->bidxMentorProfile ) ? $data->bidxMentorProfile : NULL;

?>
<div class="member box-border top-margin-lineheight">
    <div class="clearfix bg-primary-light main-padding">
        <h1 class="text-center bidx-page-heading">
            <span class="default"><?php echo (isset($this->data->isMyProfile) && $this->data->isMyProfile) ? __('My Profile','bidxplugin') : $member; ?></span>

            <span class="editMember hide"><?php _e('Edit my member profile', 'bidxplugin')?></span>

            <span class="editInvestor hide"><?php _e('Edit my investor profile', 'bidxplugin')?></span>
            <span class="createInvestor hide"><?php _e('Create my investor profile', 'bidxplugin')?></span>

            <span class="editEntrepreneur hide"><?php _e('Edit my entrepreneur profile', 'bidxplugin')?></span>
            <span class="createEntrepreneur hide"><?php _e('Create my entrepreneur profile', 'bidxplugin')?></span>

            <span class="editMentor hide"><?php _e('Edit my mentor profile', 'bidxplugin')?></span>
            <span class="createMentor hide"><?php _e('Create my mentor profile', 'bidxplugin')?></span>
        </h1>
    </div>

    <div class="actions hide-overflow main-margin">
        <div class="pull-left quick-action-links">
           <?php
           if(false && $this->isLoggedInGroupOwner && $memberId != $loggedInMemberId)
            { ?>
            <div class="pull-left">
                <label class="markLabel"><?php _e('Mark as', 'bidxplugin')?>:</label>
                <button class="btn btn-sm btn-success">
                    <div class="fa fa-bookmark fa-above fa-big"></div>
                    <?php _e('Accrediated', 'bidxplugin')?>
                </button>
                <button class="btn btn-sm btn-danger">
                    <div class="fa fa-ban fa-above fa-big"></div>
                    <?php _e('Not Accrediated', 'bidxplugin')?>
                </button>
           </div>
           <?php } ?>


            <div class="tagging pull-left">
                <div class="taggingButton"></div>
            </div>





<?php
            if ( $canEdit && $isLoggedinMemberIsEntrepreneur ) :
?>
                <!-- <a href="#" class="btn btn-sm btn-primary">
                    <div class="fa fa-dashboard fa-above fa-big"></div>
                    <?php _e('Dashboard', 'bidxplugin')?>
                </a> -->
                <a href="<?php echo _l('businesssummary');?>/#createBusinessSummary" class="btn btn-sm btn-primary">
                    <div class="fa fa-suitcase fa-above fa-big"></div>
                    <?php _e('Create Business', 'bidxplugin')?>
                </a>
                <a href="<?php echo _l('company');?>/#createCompany" class="btn btn-sm btn-primary">
                    <div class="fa fa-building fa-above fa-big"></div>
                    <?php _e('Add Company', 'bidxplugin')?>
                </a>
<?php
            endif;
?>
<?php
            if ( $isLoggedinMemberIsInvestor && !$isLoggedinMemberIsMentor ) :
?>
                <a href="<?php echo _l('member');?>/#createMentor" class="btn btn-sm btn-primary">
                    <div class="fa fa-compass fa-above fa-big"></div>
                    <?php _e('Become mentor', 'bidxplugin')?>
                </a>
<?php
            endif;
?>
        </div>

<?php
        if ( $canEdit ) :
?>
            <div class="btn-group pull-right">
                <button class="btn btn-sm btn-primary editProfile">
                    <div class="fa fa-pencil fa-above fa-big"></div>
                    <?php _e('Edit Profile', 'bidxplugin')?>
                </button>
           </div>
<?php
        endif;
?>
<?php
        if ( $memberId != $loggedInMemberId && $authenticated && $inGroup ) :
?>
            <a href="<?php echo _l('mail');?>/#mail/contacts/action=connect&id=<?php echo $memberId ?>" class="btn btn-sm btn-warning btn-contact hide pull-right">
                <div class="fa fa-user fa-above fa-big"></div>
                <?php _e('Connect', 'bidxplugin')?>
            </a>
<?php
        endif;

        // If current profile is not loggedin user, is  mentor, loggedin is not mentor, in a group
        if ( $memberId != $loggedInMemberId && $authenticated && $inGroup && $isMentor && !$isLoggedinMemberIsMentor) :
?>
            <a href="#mentoringRequest/confirmMentoringRequest/mentorId=<?php echo $memberId ?>" class="btn btn-sm btn-mentor btn-mentoring mentor-cl hide pull-right">
                <div class="fa fa-compass fa-above fa-big"></div>
                <?php _e('Request mentoring', 'bidxplugin')?>
            </a>
<?php
        endif;
?>
        <div class="tagging btn-group pull-right">
            <div class="taggingLabel"></div>
        </div>
        <div class="taggingLabel btn-group pull-right hide">
            <span class="accreditation-labels">
                <div class="text-uppercase main-margin-horizontal accreditation accr-Pending">
                    <span class="fa fa-bookmark-o fa-big pull-left"></span>
                    <?php _e('Pending Accreditation', 'bidxplugin')?>

                </div>

                <div class="text-uppercase main-margin-horizontal accreditation accr-Accepted hide">
                    <span class="fa fa-bookmark fa-big pull-left"></span>
                    <?php _e('Accreditated', 'bidxplugin')?>
                </div>

                <div class="text-uppercase main-margin-horizontal accreditation accr-Refused hide">
                    <span class="fa fa-ban fa-big pull-left"></span>
                    <?php _e('Not Accreditated', 'bidxplugin')?>
                </div>
            </span>
        </div>

        <div class="editControls btn-group pull-right"></div>
    </div>

    <div class="row mainState mainStateShow main-padding">
        <div class="col-sm-12">

            <div class="view viewMainsuccess alert alert-success">
                <p class="successMsg"></p>
            </div>
            <div class="view viewMainerror alert alert-warning">
                <p class="errorMsg"></p>
            </div>
        </div>
        <div class="col-sm-12">

<div class="row tabs-vertical">

    <div class="col-sm-3 tabs-nav">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs tabs-left">
            <li class="active"><a href="#tab-member" data-toggle="tab"><i class="pull-left fa fa-user"></i> <?php _e('Member', 'bidxplugin')?></a></li>
<?php
            if ( !empty($this->data->bidxEntrepreneurProfile ) ):
?>
            <li><a href="#tab-entreprenuer" data-toggle="tab"><i class="pull-left fa fa-lightbulb-o"></i> <?php _e('Entrepreneur','bidxplugin');?></a></li>
<?php
            endif;
?>
<?php
            if ( !empty($this->data->bidxInvestorProfile ) ) :
?>
                <li><a href="#tab-investor" data-toggle="tab"><i class="pull-left fa fa-bank"></i> <?php _e('Investor','bidxplugin');?></a></li>
<?php
            endif;
?>
<?php
            if ( !empty($this->data->bidxMentorProfile ) ):
?>

            <li><a href="#tab-mentor" data-toggle="tab"><i class="pull-left fa fa-compass"></i> <?php _e('Mentor','bidxplugin');?></a></li>
<?php
            endif;
?>
        </ul>

        <?php // $this-> //render('create-grow.phtml'); ?>
    </div>

    <div class="col-sm-9 tabs-content">
        <!-- Tab panes -->
        <div id="myProfile" class="tab-content">
            <div class="tab-pane active" id="tab-member">
                <?php $this->render('view-member.phtml');  ?>
            </div>
<?php
            if ( !empty($this->data->bidxEntrepreneurProfile ) ):
?>
            <div class="tab-pane" id="tab-entreprenuer">
                <?php $this->render('view-entrepreneur.phtml'); ?>
            </div>
<?php
            endif;
?>
<?php
            if ( !empty($this->data->bidxInvestorProfile ) ) :
?>
            <div class="tab-pane" id="tab-investor">
                <?php $this->render('view-investor.phtml'); ?>
            </div>
<?php
            endif;
?>
<?php
            if ( !empty($this->data->bidxMentorProfile ) ):
?>
            <div class="tab-pane" id="tab-mentor">
                <?php $this->render('view-mentor.phtml'); ?>
            </div>
<?php
            endif;
?>
        </div>
    </div>

</div>


        </div>




    </div>
    <?php $this->render('edit-member.phtml'); ?>
    <?php $this->render('edit-entrepreneur.phtml'); ?>
    <?php $this->render('edit-investor.phtml'); ?>
    <?php $this->render('edit-mentor.phtml'); ?>
    <?php $this->render('mentoring-request.phtml'); ?>
</div>
