<?php
$member         = isset($this->data->member->displayName) ?  $this->data->member->displayName: NULL ;
$entities       = $this->sessionData->data->wp->entities;
$isSuperAdmin   = is_super_admin();
?>
<div class="member">
    <div class="clearfix">
        <h1 class="pull-left bidx-page-heading">
            <span class="default"><?php echo (isset($this->data->isMyProfile) && $this->data->isMyProfile) ? __('My Profile','bidxplugin') : $member; ?></span>

            <span class="editMember hide"><?php _e('Edit my member profile', 'bidxplugin')?></span>

            <span class="editInvestor hide"><?php _e('Edit my investor profile', 'bidxplugin')?></span>
            <span class="createInvestor hide"><?php _e('Create my investor profile', 'bidxplugin')?></span>

            <span class="editEntrepreneur hide"><?php _e('Edit my entrepreneur profile', 'bidxplugin')?></span>
            <span class="createEntrepreneur hide"><?php _e('Create my entrepreneur profile', 'bidxplugin')?></span>

            <span class="editMentor hide"><?php _e('Edit my mentor profile', 'bidxplugin')?></span>
            <span class="createMentor hide"><?php _e('Create my mentor profile', 'bidxplugin')?></span>

        </h1>


    </div>

    <div class="actions well hide-overflow">
        <div class="btn-group pull-left">
            <a href="#" class="btn btn-sm btn-primary">
                <div class="fa fa-dashboard fa-above fa-big"></div>
                Dashboard
            </a>
            <a href="#" class="btn btn-sm btn-primary">
                <div class="fa fa-suitcase fa-above fa-big"></div>
                Create Business
            </a>
            <a href="#" class="btn btn-sm btn-primary">
                <div class="fa fa-tasks fa-above fa-big"></div>
                Add Company
            </a>
        </div>
        <div class="editControls btn-group pull-right"></div>
    </div>

    <div class="row mainState mainStateShow">
        <div class="col-sm-12">

            <div class="view viewMainsuccess alert alert-success">
                <p class="successMsg"></p>
            </div>
            <div class="view viewMainerror alert alert-warning">
                <p class="errorMsg"></p>
            </div>
        </div>
        <div class="col-sm-12">
        
<div class="row tabs-vertical">

    <div class="col-sm-3 tabs-nav">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs tabs-left">
            <li class="active"><a href="#tab-member" data-toggle="tab"><i class="pull-left fa fa-user"></i> Member</a></li>
            <li><a href="#tab-entreprenuer" data-toggle="tab"><i class="pull-left fa fa-lightbulb-o"></i> Entrepreneur</a></li>
<?php
            if ( $this->isLoggedInInvestor || $this->isLoggedInGroupOwner ) :
?>          
                <li><a href="#tab-investor" data-toggle="tab"><i class="pull-left fa fa-bank"></i> Investor</a></li>
<?php
            endif;
?>          

            <li><a href="#tab-mentor" data-toggle="tab"><i class="pull-left fa fa-compass"></i> Mentor</a></li>
        </ul>
        
        <?php // $this-> //render('create-grow.phtml'); ?>
    </div>

    <div class="col-sm-9 tabs-content">
        <!-- Tab panes -->
        <div id="myProfile" class="tab-content">
            <div class="tab-pane active" id="tab-member">
                <?php $this->render('view-member.phtml');  ?>
            </div>
            <div class="tab-pane" id="tab-entreprenuer">
                <?php $this->render('view-entrepreneur.phtml'); ?>
            </div>
<?php
            if ( $this->isLoggedInInvestor || $this->isLoggedInGroupOwner ) :
?>          
            <div class="tab-pane" id="tab-investor">
                <?php $this->render('view-investor.phtml'); ?>
            </div>
<?php
            endif;
?>          
            <div class="tab-pane" id="tab-mentor">
                <?php $this->render('view-mentor.phtml'); ?>
            </div>
        </div>
    </div> 

</div>


        </div>




    </div>
    <?php $this->render('edit-member.phtml'); ?>
    <?php $this->render('edit-entrepreneur.phtml'); ?>
    <?php $this->render('edit-investor.phtml'); ?>
    <?php $this->render('edit-mentor.phtml'); ?>
    <?php $this->render('mentoring-request.phtml'); ?>
</div>
