<?php
$member         = isset($this->data->member->displayName) ?  $this->data->member->displayName: NULL ;
$entities       = $this->sessionData->data->wp->entities;
?>
<div class="block-odd member">
    <div class="clearfix">
        <h1 class="pull-left bidx-page-heading">
            <span class="default"><?php echo (isset($this->data->isMyProfile) && $this->data->isMyProfile) ? __('My Profile') : $member; ?></span>

            <span class="editMember hide"><?php _e('Edit my member profile', 'bidxplugin')?></span>

            <span class="editInvestor hide"><?php _e('Edit my investor profile', 'bidxplugin')?></span>
            <span class="createInvestor hide"><?php _e('Create my investor profile', 'bidxplugin')?></span>

            <span class="editEntrepreneur hide"><?php _e('Edit my entrepreneur profile', 'bidxplugin')?></span>
            <span class="createEntrepreneur hide"><?php _e('Create my entrepreneur profile', 'bidxplugin')?></span>

            <span class="editMentor hide"><?php _e('Edit my mentor profile', 'bidxplugin')?></span>
            <span class="createMentor hide"><?php _e('Create my mentor profile', 'bidxplugin')?></span>

        </h1>
        <div class="editControls btn-group pull-right"></div>
    </div>

    <div class="row mainState mainStateShow">
        <div class="col-sm-8">
            <div id="accordionProfile">
                <?php $this->render('view-member.phtml');  ?>
                <?php $this->render('view-entrepreneur.phtml'); ?>
                <?php $this->render('view-investor.phtml'); ?>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="side-bar well">

<?php
    if ( isset($this->data->isMyProfile) && $this->data->isMyProfile) {
?>
            <h2><?php _e('Create and grow', 'bidxplugin')?></h2>
<?php
        // Create entrepreneur
        //
        if ( !isset( $entities->bidxEntrepreneurProfile ) ) {
?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong><?php _e('Become an entrepreneur', 'bidxplugin')?></strong>
                </div>
                <div class="panel-body">
                    <em><?php _e('Create your business', 'bidxplugin')?></em>
                    <a href="/member/#createEntrepreneur" class="btn btn-primary pull-right"><i class="fa fa-plus-circle"></i> <?php _e('Create','bidxplugin')?></a>
                </div>
            </div>
<?php
        } else {
?>
            <div class="panel panel-default">
                <div class="panel-body">
<?php
                    printf( __( 'Go to %sEntrepreneur dashboard%s', 'bidxtheme' ), '<a href="/entrepreneur-dashboard">', '</a>' );
?>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong><?php _e('Create a business summary', 'bidxplugin')?></strong>
                </div>
                <div class="panel-body">
                    <em><?php _e('Create your business', 'bidxplugin')?></em>
                    <a href="/businesssummary/#createBusinessSummary" class="btn btn-primary pull-right"><i class="fa fa-plus-circle"></i> <?php _e('Create','bidxplugin')?></a>
                </div>
            </div>
<?php
        }

        // Create investor
        //
        if ( !isset( $entities->bidxInvestorProfile )) {
?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong><?php _e('Become an investor', 'bidxtheme')?></strong>
                </div>
                <div class="panel-body">
                    <em><?php _e('Create your resources', 'bidxtheme')?></em>
                    <a href="/member/#createInvestor" class="btn btn-primary pull-right"><i class="fa fa-plus-circle"></i> <?php _e('Invest','bidxplugin')?></a>
                </div>
            </div>
<?php
        } else {
?>
            <div class="panel panel-default">
                <div class="panel-body">
<?php
                    printf( __( 'Go to %sInvestor dashboard%s', 'bidxtheme' ), '<a href="/investor-dashboard">', '</a>' );
?>
                </div>
            </div>
<?php
        }

    }


    //    if ( isset($this->data->isMyProfile) && $this->data->isMyProfile) {
?>
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="pull-right">
                        <a href="/company/#createCompany" class="btn btn-primary"><i class="fa fa-plus"></i> <?php _e('Add a company','bidxplugin'); ?></a>
                    </div>
                </div>
            </div>
<?php
          //  }
            $this->render('view-group.phtml');
?>

            </div>
        </div>
    </div>
    <?php $this->render('edit-member.phtml'); ?>
    <?php $this->render('edit-entrepreneur.phtml'); ?>
    <?php $this->render('edit-investor.phtml'); ?>
    <?php $this->render('edit-mentor.phtml'); ?>
</div>
