<?php
    $isLoggedinMemberIsInvestor = isset( $this -> sessionData -> data -> wp -> entities -> bidxInvestorProfile ) ? $this -> sessionData -> data -> wp -> entities -> bidxInvestorProfile : null;

?>

<div id="mentoringRequest" >

    <div class="modalView modalConfirmRequest">
                <!-- Modal -->
        <div class="modal fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                 <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h3 id="myModalLabel"><?php _e ('Send request') ?></h3>
                    </div>
                    <div class="modal-body">
                        <p>
                            <?php _e ('You are about to send the mentoring request. Are you sure?') ?>
                        </p>
                    </div>
                    <div class="modal-footer">
                        <a class="btn" href="#mentoringRequest/cancelRequest"><?php _e ('Cancel') ?></a>
                        <a href="#" class="btn btn-primary" data-href="#mentoringRequest/sendRequest/" ><?php _e ('Send request') ?></a>
                    </div>
                 </div>
            </div>
        </div>
    </div>
    <div class="modalView modalNobusinesssummary">
                <!-- Modal -->
        <div class="modal fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                 <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h3 id="myModalLabel"><?php _e ('Create business summary') ?></h3>
                    </div>
                    <div class="modal-body">
                        <p>
                            <?php _e ('Currently there is no any business summary, please create one before you ask for mentoring') ?>
                        </p>
                    </div>
                    <div class="modal-footer">
                        <a href="#" class="btn btn-primary" data-href="#mentoringRequest/cancelRequest" ><?php _e ('Ok') ?></a>
                    </div>
                 </div>
            </div>
        </div>
    </div>
    <div class="modalView modalConfirmMentoringRequest">
                <!-- Modal -->
        <div class="modal fade bidx-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                 <div class="modal-content">
                    <div class="modal-header">
                        <a class="btn btnRequestCancel pull-right" href="#mentoringRequest/cancelRequest">
                            <button type="button" class="close">×</button>
                        </a>
                        <h3 id="myModalLabel"><?php _e ('Request mentoring') ?></h3>
                    </div>
                    <div class="modal-body">
                        <form class="frmrequestMentor">
                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label><?php _e('What advice do you need ?','bidxplugin'); ?></label>
                                        <textarea name="summary" class="form-control" placeholder="<?php _e('Please tell mentor what advice do you need ? (min. 300 characters)','bidxplugin'); ?>" ></textarea>
                                    </div>
                                    <div class="form-group">
                                        <label><?php _e('Which expertise do you need?','bidxplugin'); ?></label>
                                         <select class= "chosen-industry" name="mentoringIndustry" multiple></select>
                                    </div>
                                    <div class="form-group">
                                        <label><?php _e('For which of your businesses?','bidxplugin'); ?></label>
                                         <select class="chosen-summary" name="businessSummary"></select>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <a class="btn btnRequestCancel" href="#mentoringRequest/cancelRequest"><?php _e ('Cancel') ?></a>
                        <a class="btn btn-primary btnRequestSubmit"  ><?php _e ('Send request') ?></a> <!-- data-href="#mentoringRequest/sendRequest/" -->
                    </div>
                 </div>
            </div>
        </div>
    </div>
</div><!-- // row -->
