<?php
    $sessionData    = BidxCommon::$staticSession;
    $entities       = isset( $sessionData->data->wp->entities ) ? $sessionData->data->wp->entities : null;

    // Create mentor
    //
    if ( !isset( $entities->bidxMentorProfile )) {
?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <strong><?php _e('Become a mentor', 'bidxtheme')?></strong>
        </div>
        <div class="panel-body">
            <em><?php _e('Create your resources', 'bidxtheme')?></em>
            <a href="<?php echo _l('member');?>/#createMentor" class="btn btn-primary pull-right"><i class="fa fa-plus-circle"></i> <?php _e('Mentor','bidxtheme')?></a>
        </div>
    </div>
<?php
    } else {
?>
    <div class="panel panel-default">
        <div class="panel-body">
<?php
        printf( __( 'View your %smentor profile%s', 'bidxtheme' ), '<a href="'._l('member').'/#mentor-profile">', '</a>' );
?>
        </div>
    </div>
<?php
    }
?>
