<?php

$mentorDetails  =   isset($this->data->bidxMentorProfile) ? $this->data->bidxMentorProfile : NULL;
$mentorDetailsBidxMeta = isset( $mentorDetails->bidxMeta )
    ? $mentorDetails->bidxMeta
    : $mentorDetails;

if ( $mentorDetails && ( $mentorDetailsBidxMeta->bidxEntityStatus == 'PUBLISHED' || $mentorDetailsBidxMeta->bidxCanEdit  ) ) {

    //$mentorType = $this->exst ($mentorDetails->investorType);

                if ($mentorDetailsBidxMeta->bidxCanEdit)
                {
?>
                    <div class="view viewNoproposals alert alert-warning">
                        <a data-dismiss='alert' class='close fa fa-times' type='button'></a>
                        <?php _e( 'No business proposals found based on your filter settings', 'bidxplugin'); ?>
                    </div>
<?php
                }
?>

            <div class="profile-block">
<?php
                if ($mentorDetailsBidxMeta->bidxCanEdit)
                {
?>
                    <div class="btn-group show hide-overflow">
<?php

                            $href = "#editMentor/" . $this -> exst( $mentorDetailsBidxMeta->bidxOwnerId );
?>
                            <a class="btn btn-sm btn-primary pull-right hide" href="<?php echo $href; ?>"><i class="fa fa-pencil"></i> <?php _e( 'Edit', 'bidxplugin' ); ?></a>
                    </div>
<?php
                }

                $rowValues = array(
                    __('Mentor profile summary','bidxplugin')     =>  $this->exst($mentorDetails->summary),
                    __('Institution name','bidxplugin')           =>  $this->exst($mentorDetails->institutionName),
                    __('Institution website','bidxplugin')        =>  $this->exst($mentorDetails->institutionWebsite)
                );

                if ( $this->checkEmpty( $rowValues ) ) :
?>
                    <h4><?php _e('About', 'bidxplugin')?></h4>
<?php               
                    echo $this->tableRow ( $rowValues );
                endif;



                $rowValues = array(
                    __('Skype','bidxplugin')                    =>  $this->exst($mentorDetails->preferredCommunication->skype),
                    __('Google hangout','bidxplugin')           =>  $this->exst($mentorDetails->preferredCommunication->hangout),
                    __('AIM','bidxplugin')                      =>  $this->exst($mentorDetails->preferredCommunication->aim),
                    __('ICQ','bidxplugin')                      =>  $this->exst($mentorDetails->preferredCommunication->icq)
                );

                if ( $this->checkEmpty( $rowValues ) ) :
?>
                    <h4><?php _e('Preferred Communication', 'bidxplugin')?></h4>
<?php               
                    echo $this->tableRow ( $rowValues );
                endif;

                $rowValues = array(
                    __('Languages','bidxplugin')                => $this->getMultiValues( $this->exst( $mentorDetails->focusLanguage ), ', ','language' ),
                    __('Focus countries','bidxplugin')          => $this->getMultiValues( $this->exst( $mentorDetails->focusCountry ), ', ','country' ),
                    __('Focus cities','bidxplugin')             => $this->getMultiValues( $this->exst( $mentorDetails->focusCity ), ',', null, 'cityTown' ),
                    __('Focus Industry','bidxplugin')           => $this->getMultiValues( $this->exst( $mentorDetails->focusIndustry ), '<br> ','industry' ),
                    __('Focus Expertise','bidxplugin')          => $this->getMultiValues( $this->exst( $mentorDetails->focusExpertise ), ', ','mentorExpertise' ),
                    __('Focus Gender','bidxplugin')             => $this->getMultiValues( $this->exst( $mentorDetails->focusGender ), ', ','gender' ),
                    __('Stage of business','bidxplugin')        => $this->getMultiValues( $this->exst( $mentorDetails->focusStageBusiness ), ', ','stageBusiness' ),
                    __('Social impact','bidxplugin')            => $this->getMultiValues( $this->exst( $mentorDetails->focusSocialImpact ), ', ','socialImpact' ),
                    __('Environmental impact','bidxplugin')     => $this->getMultiValues( $this->exst( $mentorDetails->focusEnvImpact ), ', ','envImpact' ),
                    _x('Other preferences','test','bidxplugin') => $this->exst ($mentorDetails->focusPreferences)
                );

                if ( $this->checkEmpty( $rowValues ) ) :
?>
                    <h4><?php _e('Mentoring Preferences', 'bidxplugin')?></h4>
<?php               
                    echo $this->tableRow ( $rowValues );
                endif;

                $focusReach = $this->exst($mentorDetails->focusReach);
                if ( $this->exst($focusReach->coordinates) && $this->exst($focusReach->coordinates) ) {
?>
                    <div class="row">
                        <div class="col-sm-6 reach-map">
<?php
                    $mapParams = array(
                        'center'        => $focusReach->coordinates,
                        'size'          => '640x300',
                        'zoom'          => 10,
                        'sensor'        => 'false'
                    );

                    printf(
                        '<img src="%s?%s" />',
                        'https://maps.googleapis.com/maps/api/staticmap',
                        http_build_query( $mapParams )
                    );
?>
                        </div>
                    </div>
<?php
                }

                if ( $this->exst ($mentorDetails->attachment) )
                {
                    echo $this->displayDocuments ( $mentorDetails->attachment, __('Documents','bidxplugin') );
                }

        ?>

        <?php
                $references = $this->exst( $mentorDetails->references );

                // A set of properties is only applicable to any other type than Angel or private
                //
                //if ( $investorType && $investorType != 'AngelInvPrivIndiv' ) {

                    // Institution name
                    //
                    // $rowValues = array (__('Institution details','bidxplugin') => $this->exst($mentorDetails->institutionName));
                    // echo $this->addRowsWithLabelAdjacent ('col-sm-4', 'col-sm-8', $rowValues, array ('tag_label' => 'label', 'class_value' => ''));

                    // Institution website
                    //
                    // $rowValues = array (__('Institution website','bidxplugin') => $this->exst($mentorDetails->institutionWebsite));
                    // echo $this->addRowsWithLabelAdjacent ('col-sm-4', 'col-sm-8', $rowValues, array ('tag_label' => 'label', 'class_value' => ''));

                //}

                    // Reach
                    //
                    // - business says "there are one of three ways to specify reach"
                    // - api says "there are three ways of specifying reach"
                    //
                    // So we have to figure out which type this investor has picked.

                    // TODO: list references (personaldetails)
                // Previous investments
                //

                if ( $references ) {
                    echo '<h5>' . __('References','bidxplugin') . '</h5>';

                    $header = array(
                        __('Name','bidxplugin')                     => 'name',
                        __('Professional title','bidxplugin')       => 'professionalTitle',
                        __('LinkedIn profile','bidxplugin')         => 'linkedIn',
                        __('Email address','bidxplugin')            => 'emailAddress'
                        // __('Landline','bidxplugin')                 => 'contactDetail[0].landLine',
                        // __('Mobile','bidxplugin')                   => 'contactDetail[0].mobile'
                    );

                    $merge['name'] = array ('firstName', 'lastName');

                    echo $this->addTableRows($header, $this->exst( $mentorDetails->references ), 'table table-bordered', $merge, array('linkedIn' => 'hidden-xs', 'emailAddress' => 'hidden-xs') );
                }

                if ($mentorDetailsBidxMeta->bidxCanEdit)
                {
?>
                <a class="view viewMentoringbutton btn btn-xs bidx-mentor label bidx-label" href="<?php echo _l('mentor-dashboard');?>">
                    <span class="countMentoringProposals"><?php _e('%count% business proposals want mentoring', 'bidxplugin')?></span>
                </a>
<?php
                }
?>
            </div><!-- // details-block of investor -->
<?php } ?>
