<?php

$entrepreneurDetails = $this->exst ($this->data->bidxEntrepreneurProfile);
$businessSummary = $this->exst ($this->data->wp->entities->bidxBusinessSummary);
$companies = $this->exst ($this->data->companies);

$entrepreneurBidxMeta = isset( $entrepreneurDetails->bidxMeta )
    ? $entrepreneurDetails->bidxMeta
    : $entrepreneurDetails;

$businessSummaryBidxMeta = isset( $businessSummary->bidxMeta )
    ? $businessSummary->bidxMeta
    : $businessSummary;

if ($entrepreneurDetails &&
    ( $entrepreneurDetails->bidxEntityStatus == 'PUBLISHED' || $entrepreneurBidxMeta->bidxCanEdit  ) ) {
    ?>

    <div class="well profile-block">

        <div class="btn-group control-buttons">
            <?php if ($entrepreneurBidxMeta->bidxCanEdit) { ?>
                <a class="btn btn-primary" href="#editEntrepreneur/<?php echo $this->exst ($entrepreneurDetails->ownerId); ?>"><?php _e('Edit','bidxplugin'); ?></a>

                    <?php
                        if ($entrepreneurBidxMeta->bidxEntityStatus == 'DRAFT') {

                            // Encode the missing fields into an attribute so we can provide a nice
                            // UI feedback in the implementation of the publish button
                            //
                            // TODO: this is of couse only for the fields we know are going to be
                            // missed and fail. This is not helping for the actual publishing which
                            // might pop up with all kinds of errors. That should be handled in the
                            // front-end when actually doing the publishing
                            //
                            $missingFields = array();

                            if ( !$this->exst( $entrepreneurDetails->cv )) {
                                $missingFields[] = 'CV';
                            }

                            $missingFieldsAttribute = count($missingFields)
                                ? sprintf( 'data-missingfields=\'%s\'', json_encode($missingFields) )
                                : '';
                    ?>
                <a class="btn btn-primary" href="#publish/<?php echo $this->exst ($entrepreneurDetails->bidxEntityId); ?>" <?php echo $missingFieldsAttribute; ?>>Publish</a>
                    <?php
                        }
                    }
                    ?>
        </div>

        <h4>Entrepreneur profile</h4>
        <div class="row-fluid">
            <?php
            $rowValues = array ( __('Summary','bidxplugin') => $this->exst ($entrepreneurDetails->summary));
            echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'h5'));
            ?>
            <br/>
            <?php
            $focusIndustry = $this->getMultiValues ($this->exst ($entrepreneurDetails->focusIndustry), ', ');
            $rowValues = array ( __('Focus Industry','bidxplugin') => $focusIndustry);
            echo $this->addRowsWithLabelAdjacent ('span6', 'span6', $rowValues, array ('tag_label' => 'h5', 'class_value' => 'adjacentval'));
            ?>
            <br/>
            <?php
            $previousBusiness = $this->exst ($entrepreneurDetails->previousBusiness);
            $header = array ( __('Name of Company','bidxplugin') => 'company', __('Outcome of business','bidxplugin') => 'businessOutcome', __('Company web-site','bidxplugin') => 'webSite');
            $previousBusinessHtml = $this->addTableRows ($header, $previousBusiness, 'table table-bordered');

            $rowValues = array ( __('Previous Business(es)','bidxplugin') => $previousBusinessHtml);
            echo $this->addRowsWithLabelBelow ('span12', 'span12', $rowValues, array ('tag_label' => 'h5'));
            ?>
            <br/>
            <?php
            echo $this->getAttachmentsDisplay ('12', '12', array ( __('Documents','bidxplugin') => $this->exst ($entrepreneurDetails->attachment)));
            ?>
        </div>
    </div>
<?php
}

// Business Summary
//

if ($businessSummary) {
    ?>
    <div class="well profile-block">

        <!-- Business Summaries Profile -->
        <div class="row-fluid">
            <div class="span12">
                <h4><?php echo ($this->data->isMyProfile) ? __('My business','bidxplugin') : __('This person has a business','bidxplugin'); ?></h4>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span3">
                <img data-src="holder.js/100x100/industrial/auto/text:No Image" class="img-rounded">
            </div>
            <div class="span7">
                <div class="row-fluid">
                    <div class="span12">
                        <h5><?php echo $this->exst($businessSummary->name); ?></h5>
                    </div>
                </div>
                <!-- Personal details 6/6 Start -->

                <?php
                $industryVal = $this->getMultiValues ($this->exst ($businessSummary->industry), ', ');
                $countryVal = $this->getMultiValues ($this->exst ($businessSummary->countryOperation), ', ', 'country', 'country');

                $joinLink = ((isset ($businessSummaryBidxMeta->bidxEntityId)) && $businessSummaryBidxMeta->bidxEntityId)
                    ? "<a href='/business/" . $businessSummaryBidxMeta->bidxEntityId . "'>" . __('view more','bidxplugin') ."</a>"
                    : '';

                $rowValues = array ($businessSummary->slogan,
                  $businessSummary->summary,
                  $industryVal,
                  $countryVal);

                echo $this->addMultipleRows ('span12', $rowValues);
                echo $this->addMultipleRows ('span12 offset10', array ($joinLink));
                ?>
            </div>
        </div>
    </div>
    <?php
}

// Companies listing
//
if ($companies) {
    ?>
    <div class="accordion" id="companies">
        <?php
        foreach ($companies as $index => $company) {

            $companyBidxMeta = isset( $company->bidxMeta ) ? $company->bidxMeta : $company;

            $collapseId = sprintf ('companyAccordion-%s', $companyBidxMeta->bidxEntityId);

            $useDataSrc = false;
            $picSrc = $this->exst ($company->logo->document);

            if (!$picSrc) {
                $picSrc = 'holder.js/100x100/industrial/auto/text:No Image';
                $useDataSrc = true;
            }
            ?>
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle <?php echo ( $index != 0 ) ? 'collapsed' : ''; ?>" data-toggle="collapse" data-parent="#companies" href="#<?php echo $collapseId ?>">
                        <h4><?php echo $company->name ?></h4>
                        <div class="control-buttons">
                            <span class="bidx-expand">+</span>
                            <span class="bidx-collapse">-</span>
                        </div>
                    </a>
                </div><!-- accordion-heading -->
                <div id="<?php echo $collapseId ?>" class="accordion-body collapse <?php echo ( $index == 0 ) ? 'in' : ''; ?>">
                    <div class="accordion-inner">
                        <div class="btn-group control-buttons">
                        <?php if ($companyBidxMeta->bidxCanEdit) { ?>
                            <a class="btn btn-primary" href="/company/<?php echo $company->ownerId; ?>/#editCompany/<?php echo $company->ownerId; ?>">Edit</a>
                        <?php } ?>
                        </div>

                        <div class="row-fluid">
                            <div class="span4">
                                <img <?php $useDataSrc ? "data-" : "" ?>src="<?php echo $picSrc ?>" class="img-rounded">
                            </div>
                            <div class="span8">
                                <ul class="unstyled">
                                    <?php
                                    $companyWebsite = $this->exst ( $company->website );
                                    $companyRegistered = $this->exst ( $company->registered );
                                    printf ('<li>%s</li>', $company->name);

                                    if ($companyWebsite) {
                                        printf ('<li>%s</li>', $companyWebsite);
                                    }


                                    if ($companyRegistered) {
                                        printf ('<li>%s</li>', date ('d-m-Y', strtotime ($this->exst ($company->dateCompanyEstab))));

                                        $arStatutoryAddress = array ();

                                        if (!empty($company->statutoryAddress->street)) {
                                            $arStatutoryAddress[] = $company->statutoryAddress->street;
                                        }

                                        if (!empty($company->statutoryAddress->streetNumber)) {
                                            $arStatutoryAddress[] = $company->statutoryAddress->streetNumber;
                                        }

                                        if (!empty($company->statutoryAddress->postalCode)) {
                                            $arStatutoryAddress[] = $company->statutoryAddress->postalCode;
                                        }


                                        $arStatutoryCityCountry = array ();

                                        if (!empty($company->statutoryAddress->cityTown)) {
                                            $arStatutoryCityCountry[] = $company->statutoryAddress->cityTown;
                                        }

                                        if (!empty($company->statutoryAddress->country)) {
                                            $arStatutoryCityCountry[] = $company->statutoryAddress->country;
                                        }

                                        printf ('<li>%s</li>', implode (' ', $arStatutoryAddress));
                                        printf ('<li>%s</li>', implode (' ', $arStatutoryCityCountry));
                                    }
                                    ?>
                                </ul>
                            </div>
                        </div>

                        <div class="bottom-controls">
        <?php
        $viewMoreLink = "<a href='/company/" . $company->ownerId . "'>". __('view more','bidxplugin') ."</a>";
        echo $viewMoreLink;
        ?>
                        </div>
                    </div>
                </div><!-- accordion-body -->
            </div><!-- accordion-group -->
        <?php
    }
    ?>
    </div><!-- accordion #companies -->
        <?php
    }

    if ( $this->exst($this->data->isMyProfile)) {
        ?>

    <div class="pull-right">
        <a href="/company/#createCompany" class="btn btn-primary"><?php _e('Add a company','bidxplugin'); ?></a>
    </div>

<?php } ?>




