<?php

$groupDetails   = isset($this->data->groups) ? $this->data->groups : NULL ;
$showGroup      = (count( (array)$groupDetails)) ? true : false;

?>
<!-- Group Info -->
<?php
    if( $showGroup )
    {
?>
        <ul class="media-list">
            <!-- Joined Group -->
            <h2><?php _e('Joined groups','bidxplugin'); ?></h3>

<?php
            foreach( $groupDetails as $groupValue)
            {
                // BIDX-2158 "/#joinGroup/" . $groupValue->bidxMeta->bidxGroupId is not working; as a workaround open a new tab and redirect to /join
                // (This might not be too nice for groups with a custom domain.)
                $joinLink = ($this->exst($groupValue->join)) ? "<a class='btn btn-xs btn-warning pull-right' target='_blank' href='" . $groupValue->bidxMeta->bidxGroupUrl . "/join'>" . __('Join','bidxplugin') . "</a>":'';
?>
                <li class="media">
                    <div class="pull-left">
                        <div class="icons-rounded pull-left"><i class="fa fa-group text-primary-light"></i></div>
                    </div>
                    <div class="media-body">
                    <a target="_blank" href="<?php echo $groupValue->bidxMeta->bidxGroupUrl ?>">
                        <h4><?php echo $groupValue->name?></h4>
                        <p><?php echo $groupValue->slogan?></p>
                    </a>
<?php
                        if ( !empty($joinLink) )
                        {
                            echo $joinLink;
                        }
?>
                    </div>
                </li>
<?php
            }
?>
        </ul>

<?php
    }
?>
