<?php

$mentorDetails  =   isset($this->data->bidxMentorProfile) ? $this->data->bidxMentorProfile : NULL;
$mentorDetailsBidxMeta = isset( $mentorDetails->bidxMeta ) ? $mentorDetails->bidxMeta : $mentorDetails;

if ( $mentorDetails && ( $mentorDetailsBidxMeta->bidxEntityStatus == 'PUBLISHED' || $mentorDetailsBidxMeta->bidxCanEdit  ) ) {

        if ($mentorDetailsBidxMeta->bidxCanEdit)
        {
?>
            <div class="view viewNoproposals alert alert-warning">
                <a data-dismiss='alert' class='close fa fa-times' type='button'></a>
                <?php _e( 'No business proposals found based on your filter settings', 'bidxplugin'); ?>
            </div>
<?php
        }
?>
            <div class="profile-block">
                <div class="mentorSectionTaggingLabel"></div>
<?php
                if ($mentorDetailsBidxMeta->bidxCanEdit)
                {
?>
                    <div class="btn-group show hide-overflow">
<?php
                            $href = "#editMentor/" . $this -> exst( $mentorDetailsBidxMeta->bidxOwnerId );
?>
                            <a class="btn btn-sm btn-primary pull-right hide" href="<?php echo $href; ?>"><i class="fa fa-pencil"></i> <?php _e( 'Edit', 'bidxplugin' ); ?></a>
                    </div>
<?php
                }

                $rowValues = array(
                    __('Mentor profile summary','bidxplugin')     =>  $this->exst($mentorDetails->summary),
                    __('Institution name','bidxplugin')           =>  $this->exst($mentorDetails->institutionName),
                    __('Institution website','bidxplugin')        =>  $this->exst($mentorDetails->institutionWebsite)
                );

                if ( $this->checkEmpty( $rowValues ) ) :
?>
                    <h4 class="memberTitle"><?php _e('About', 'bidxplugin')?></h4>
<?php
                    echo $this->tableRow ( $rowValues );
                endif;

                $rowValues = array(
                    __('Languages','bidxplugin')                => $this->getMultiValues( $this->exst( $mentorDetails->focusLanguage ), ', ','language' ),
                    __('Focus countries','bidxplugin')          => $this->getMultiValues( $this->exst( $mentorDetails->focusCountry ), ', ','country' ),
                    __('Focus cities','bidxplugin')             => $this->getMultiValues( $this->exst( $mentorDetails->focusCity ), ',', null, 'cityTown' ),
                    __('Focus Industry','bidxplugin')           => $this->getMultiValues( $this->exst( $mentorDetails->focusIndustry ), '<br> ','industry' ),
                    __('Focus Expertise','bidxplugin')          => $this->getMultiValues( $this->exst( $mentorDetails->focusExpertise ), ', ','mentorExpertise' ),
                    __('Focus Gender','bidxplugin')             => $this->getMultiValues( $this->exst( $mentorDetails->focusGender ), ', ','gender' ),
                    __('Stage of business','bidxplugin')        => $this->getMultiValues( $this->exst( $mentorDetails->focusStageBusiness ), ', ','stageBusiness' ),
                    __('Social impact','bidxplugin')            => $this->getMultiValues( $this->exst( $mentorDetails->focusSocialImpact ), ', ','socialImpact' ),
                    __('Environmental impact','bidxplugin')     => $this->getMultiValues( $this->exst( $mentorDetails->focusEnvImpact ), ', ','envImpact' ),
                    _x('Other preferences','test','bidxplugin') => $this->exst ($mentorDetails->focusPreferences)
                );

                if ( $this->checkEmpty( $rowValues ) ) :
?>
                    <h4><?php _e('Mentoring Preferences', 'bidxplugin')?></h4>
<?php
                    echo $this->tableRow ( $rowValues );

                endif;

                $focusReach = $this->exst($mentorDetails->focusReach);

                if ( $this->exst($focusReach->coordinates) && $this->exst($focusReach->coordinates) ) {
?>
                    <div class="row">
                        <div class="col-sm-6 reach-map">
<?php
                    $mapParams = array(
                        'center'        => $focusReach->coordinates,
                        'size'          => '640x300',
                        'zoom'          => 10,
                        'sensor'        => 'false'
                    );

                    printf(
                        '<img src="%s?%s" />',
                        'https://maps.googleapis.com/maps/api/staticmap',
                        http_build_query( $mapParams )
                    );
?>
                        </div>
                    </div>
<?php
                }

                if ( $this->exst ($mentorDetails->attachment) )
                {
                    echo $this->displayDocuments ( $mentorDetails->attachment, __('Documents','bidxplugin') );
                }

                $references = $this->exst( $mentorDetails->references );

                if ( $references ) {
                    echo '<h5>' . __('References','bidxplugin') . '</h5>';

                    $header = array(
                        __('Name','bidxplugin')                     => 'name',
                        __('Professional title','bidxplugin')       => 'professionalTitle',
                        __('LinkedIn profile','bidxplugin')         => 'linkedIn',
                        __('Email address','bidxplugin')            => 'emailAddress'
                    );

                    $merge['name'] = array ('firstName', 'lastName');

                    echo $this->addTableRows($header, $this->exst( $mentorDetails->references ), 'table table-bordered', $merge, array('linkedIn' => 'hidden-xs', 'emailAddress' => 'hidden-xs') );
                }
?>
            </div> <!-- // details-block of investor -->
<?php } ?>
