<?php

$investorDetails = isset($this->data->bidxInvestorProfile) ? $this->data->bidxInvestorProfile : NULL;
$investorDetailsBidxMeta = isset( $investorDetails->bidxMeta )
    ? $investorDetails->bidxMeta
    : $investorDetails;


if ( $investorDetails && ( $investorDetailsBidxMeta->bidxEntityStatus == 'PUBLISHED' || $investorDetailsBidxMeta->bidxCanEdit  ) ) {

    //$investorType = $this->exst ($investorDetails->investorType);
?>

        <div class="profile-block">

            <div class="btn-group show hide-overflow">
    <?php
                if ($investorDetailsBidxMeta->bidxCanEdit) {
                    $href = "#editInvestor/" . $this -> exst( $investorDetailsBidxMeta->bidxOwnerId );
    ?>
                    <a class="btn btn-sm btn-primary pull-right" href="<?php echo $href; ?>"><i class="fa fa-pencil"></i> <?php _e( 'Edit', 'bidxplugin' ); ?></a>
    <?php
                    }
    ?>
            </div>

    <?php
            // Institution address
            //
            $address = '';
            if ($this->exst ($investorDetails->institutionAddress )) {

                $institutionAddress = $investorDetails->institutionAddress;

                $addressArr = array (
                    $this->exst ($institutionAddress->street,'') . ' ' . $this->exst ($institutionAddress->streetNumber,''),
                    $this->exst ($institutionAddress->cityTown,''),
                    __('country') => $this->exst ($institutionAddress->country,''),
                    $this->exst ($institutionAddress->postalCode)
                );

                $address = $this->createRowValue ($addressArr, ', ');
            }

            $investmentSize = array(
                $this->exst( $investorDetails->minInvestment, '' ),
                $this->exst( $investorDetails->maxInvestment, '' )
            );

            $rowValues = array(
                __('Investor profile summary','bidxplugin')   =>  $this->exst ($investorDetails->summary),
                __('Investor type','bidxplugin')              =>  $this->getStaticVal('investorType', $this->exst ($investorDetails->investorType)),
                __('Investment types','bidxplugin')           =>  $this->getMultiValues($this->exst( $investorDetails->investmentType ), ', ','investmentType'),
                __('Institution details','bidxplugin')        =>  $this->exst($investorDetails->investsForInst) ? $this->exst($investorDetails->institutionName) : NULL,
                __('Institution website','bidxplugin')        =>  $this->exst($investorDetails->investsForInst) ? $this->exst($investorDetails->institutionWebsite) : NULL,
                __('Address','bidxplugin')                    =>  $address,
                // __('Industry','bidxplugin')                   =>  $this->getMultiValues($this->exst ($investorDetails->focusIndustry), ', ','industry'),
                __('Industry','bidxplugin')                   =>  $this->getMultiValues($this->exst ($investorDetails->focusIndustrySector), '<br> ','industrySector'),
                __('Social impact','bidxplugin')              =>  $this->getMultiValues($this->exst ($investorDetails->focusSocialImpact), ', ','socialImpact'),
                __('Environmental impact','bidxplugin')       =>  $this->getMultiValues($this->exst ($investorDetails->focusEnvImpact), ', ','envImpact'),
                __('Consumer type','bidxplugin')              =>  $this->getMultiValues($this->exst ($investorDetails->focusConsumerType), ', ','consumerType'),
                __('Language(s) of operation','bidxplugin')   =>  $this->getMultiValues($this->exst ($investorDetails->focusLanguage), ', ','language'),
                __('Stage of business','bidxplugin')          =>  $this->getMultiValues($this->exst ($investorDetails->focusStageBusiness), ', ','stageBusiness'),
                __('Gender','bidxplugin')                     =>  $this->getMultiValues($this->exst ($investorDetails->focusGender), ', ','gender'),
                __('Investment size','bidxplugin')            =>  implode( $investmentSize, ' - ' )
            );
            echo $this->pairRows( $rowValues );
    ?>
            <!-- <h4>Reach</h4> -->
    <?php

            $focusReach = $this->exst($investorDetails->focusReach);
            if ( $this->exst($focusReach->coordinates) && $this->exst($focusReach->coordinates) ) {
    ?>
                <div class="row">
                    <div class="col-sm-6 reach-map">
    <?php
                $mapParams = array(
                    'center'        => $focusReach->coordinates,
                    'size'          => '640x300',
                    'zoom'          => $this->setZoom($focusReach->reach),
                    'sensor'        => 'false'
                );

                printf(
                    '<img src="%s?%s" />',
                    'https://maps.googleapis.com/maps/api/staticmap',
                    http_build_query( $mapParams )
                );
    ?>
                    </div>
                </div>
    <?php
            }

            $rowValues = array (
                __('Focus countries','bidxplugin') => $this->getMultiValues ($this->exst ($investorDetails->focusCountry), ', ','country'),
                __('Focus cities','bidxplugin') => $this->getMultiValues($this->exst ($investorDetails->focusCity), ',', null, 'cityTown'),
                __('Other preferences','bidxplugin') => $this->exst ($investorDetails->additionalPreferences),
                __('Number of investments in the last 12 months','bidxplugin') => $this->exst( $investorDetails->numberInvestments ),
                __('Total investments made in the last 12 months','bidxplugin') => $this->exst( $investorDetails->totalInvestment )
            );
            echo $this->pairRows( $rowValues );

            // Previous investments
            //
            echo '<h4>' . __('Previous investments','bidxplugin') . '</h4>';

            $header = array(
                __('Name of Company','bidxplugin')           => 'companyName',
                __('Amount invested','bidxplugin')           => 'investment',
                __('Investment type','bidxplugin')           => 'investmentType',
                __('URL of Company website','bidxplugin')    => 'companyWebsite'
            );

            echo $this->addTableRows($header, $this->exst( $investorDetails->previousInvestments ), 'table table-bordered', '', array('investmentType' => 'hidden-xs', 'companyWebsite' => 'hidden-xs') );

            if ( $this->exst ($investorDetails->attachment) )
            {
                echo $this->displayDocuments ( $investorDetails->attachment, __('Documents','bidxplugin') );
            }

    ?>

    <?php
            $references = $this->exst( $investorDetails->references );

            // A set of properties is only applicable to any other type than Angel or private
            //
            //if ( $investorType && $investorType != 'AngelInvPrivIndiv' ) {

                // Institution name
                //
                // $rowValues = array (__('Institution details','bidxplugin') => $this->exst($investorDetails->institutionName));
                // echo $this->addRowsWithLabelAdjacent ('col-sm-4', 'col-sm-8', $rowValues, array ('tag_label' => 'label', 'class_value' => ''));

                // Institution website
                //
                // $rowValues = array (__('Institution website','bidxplugin') => $this->exst($investorDetails->institutionWebsite));
                // echo $this->addRowsWithLabelAdjacent ('col-sm-4', 'col-sm-8', $rowValues, array ('tag_label' => 'label', 'class_value' => ''));

            //}

                // Reach
                //
                // - business says "there are one of three ways to specify reach"
                // - api says "there are three ways of specifying reach"
                //
                // So we have to figure out which type this investor has picked.

                // TODO: list references (personaldetails)
            // Previous investments
            //

            if ( $references ) {
                echo '<h4>' . __('References','bidxplugin') . '</h4>';

                $header = array(
                    __('Name','bidxplugin')                     => 'name',
                    __('Professional title','bidxplugin')       => 'professionalTitle',
                    __('LinkedIn profile','bidxplugin')         => 'linkedIn',
                    __('Email address','bidxplugin')            => 'emailAddress'
                    // __('Landline','bidxplugin')                 => 'contactDetail[0].landLine',
                    // __('Mobile','bidxplugin')                   => 'contactDetail[0].mobile'
                );

                $merge['name'] = array ('firstName', 'lastName');

                echo $this->addTableRows($header, $this->exst( $investorDetails->references ), 'table table-bordered', $merge, array('linkedIn' => 'hidden-xs', 'emailAddress' => 'hidden-xs') );
            }

    ?>
        </div><!-- // details-block of investor -->
<?php } ?>
