<?php

    $data                       = $this->data;
    $memberId                   = isset( $this->data->member->bidxMeta->bidxMemberId ) ? $this->data->member->bidxMeta->bidxMemberId : null ;
    $loggedInMemberId           = isset( $this -> sessionData -> data -> id ) ? $this -> sessionData -> data -> id : null;
    $authenticated              = isset( $this -> sessionData -> authenticated ) && $this -> sessionData -> authenticated ==  'true';
    $isLoggedinMemberIsMentor   = isset( $this -> sessionData -> data -> wp -> entities -> bidxMentorProfile ) ? $this -> sessionData -> data -> wp -> entities -> bidxMentorProfile : null;
    $groupIds                   = array_keys ( (array)$this -> sessionData -> data -> groups );
    $inGroup                    = in_array( $this -> sessionData -> data -> currentGroup, $groupIds);
    $personalDetails            = isset( $data->bidxMemberProfile->personalDetails ) ? $data->bidxMemberProfile->personalDetails : NULL;
    $isEntrepreneur             = isset( $data->bidxEntrepreneurProfile ) ? $data->bidxEntrepreneurProfile : NULL ;
    $isInvestor                 = isset( $data->bidxInvestorProfile ) ? $data->bidxInvestorProfile : NULL;
    $isMentor                   = isset( $data->bidxMentorProfile ) ? $data->bidxMentorProfile : NULL;
    $personalDetailsBidxMeta    = isset( $personalDetails->bidxMeta ) ? $personalDetails->bidxMeta : $personalDetails;
    $entrepreneurDetails        = isset( $data->bidxEntrepreneurProfile ) ? $data->bidxEntrepreneurProfile: NULL ;
    $firstName                  = $this->exst( $personalDetails->firstName );
    $lastName                   = $this->exst( $personalDetails->lastName );
    $professionalTitle          = $this->exst( $personalDetails->professionalTitle );
    $gender                     = $this->addExtraValuesToRows( 'gender', $this->exst( $personalDetails->gender ) );
    $dateofBirth                = ( $authenticated && isset( $personalDetails->dateOfBirth ) ) ? date( 'd M Y', strtotime ( $this->addExtraValuesToRows( 'dateOfBirth', $this->exst( $personalDetails->dateOfBirth ) ) ) ): NULL;
    $highestEducation           = $this->addExtraValuesToRows( 'highestEducation', $this->exst( $personalDetails->highestEducation ) );
    $emailAddress               = $this->exst( $personalDetails->emailAddress );
    $mobile                     = $this->getMultiValues ($this->exst ($personalDetails->contactDetail), ', ', NULL, 'mobile');
    $fax                        = $this->getMultiValues ($this->exst ($personalDetails->contactDetail), ', ', NULL, 'fax');
    $landLine                   = $this->getMultiValues ($this->exst ($personalDetails->contactDetail), ', ', NULL, 'landLine');
    $useDataSrc                 = false;
    $picSrc                     = $this->exst ( $personalDetails->profilePicture->document );


    $nationality                = $this->addExtraValuesToRows( 'nationality', $this->exst( $personalDetails->nationality ) );

    // Language Details
    $languageData               = $this->exst( $personalDetails->languageDetail );
    $languageDetails            = ( $languageData ) ? $this->getMultiValues ( $languageData, ', ', 'language', 'language' ) : NULL;
    $motherLanguageDetails      = $this->getMultiValues ( $languageData, ', ', 'language', 'language', array ( 'motherLanguage' => '1' ) );
    $motherlanguage             = $this->addExtraValuesToRows( 'motherlanguage', $motherLanguageDetails );

    if ( !$personalDetails->profilePicture->document )
    {
        $useDataSrc             = true;
    }

    // Address Details
    $address = '';
    if ( $this->exst( $personalDetails->address[0] ) )
    {
        if ( $authenticated )
        {
            $street             = $this->exst( $personalDetails->address[0]->street,'' );
            $streetNumber       = $this->exst( $personalDetails->address[0]->streetNumber,'' );
            $cityTown           = $this->exst( $personalDetails->address[0]->cityTown,'' );
            $postalCode         = $this->exst( $personalDetails->address[0]->postalCode,'' );
            $addressArr         = array (
                                            $street . ' ' . $streetNumber,
                                            $cityTown,
                                            __('country') => $personalDetails->address[0]->country,
                                            $personalDetails->address[0]->postalCode
                                        );

            $address            = $this->createRowValue ($addressArr, ', ');

        }
        else
        {
            $country            = array ( __('country') => $personalDetails->address[0]->country );
            $address            = $this->createRowValue ($country);
        }
    }

?>

            <div class="row">
                <div class="col-sm-3">
<?php
                if ($picSrc)
                {
                    $pisWidth = $this->exst( $personalDetails->profilePicture->width ) ?       $personalDetails->profilePicture->width . 'px;' : "auto;";
                    $pisLeft  = $this->exst( $personalDetails->profilePicture->left )  ? '-' . $personalDetails->profilePicture->left  . 'px;' : "auto;";
                    $pisTop   = $this->exst( $personalDetails->profilePicture->top )   ? '-' . $personalDetails->profilePicture->top   . 'px;' : "auto;";

                    $profileImage = '<img' .
                                    ' src="' . $picSrc . '"'.
                                    ' style="'.
                                        'width: ' . $pisWidth .
                                        'left: ' . $pisLeft .
                                        'top: ' . $pisTop .
                                    '"' .' />';
?>
                    <div class="img-cropper"><?php echo $profileImage; ?></div>
<?php
                }
                else
                {
?>
                    <div class="icons-rounded pull-left"><i class="fa fa-user text-primary-light"></i></div>
<?php
                }
?>
                </div>
                <div class="col-sm-9">
                    <div class="row">
                        <div class="col-sm-7">
                            <h2 class="top-0"><?php echo ucwords($firstName . '&nbsp;' . $lastName); ?></h2>
                        </div>
                        <div class="col-sm-5">
<?php
                            if ( $this->exst( $personalDetailsBidxMeta->bidxCanEdit ) )
                            {
?>
                                <a class="btn btn-sm btn-primary pull-right" href="#editMember/<?php echo $personalDetailsBidxMeta->bidxOwnerId; ?>"><i class="fa fa-pencil"></i> <?php _e( 'Edit', 'bidxplugin' ); ?></a>
<?php
                            }

                            if ( $memberId != $loggedInMemberId && $authenticated && $inGroup )
                            {
?>
                                <a class="btn btn-xs btn-warning pull-right" href="/mail/#mail/contacts/action=connect&id=<?php echo $memberId ?>"><?php _e('Connect', 'bidxplugin')?></a>
<?php
                            }

                            // If current profile is not loggedin user, is  mentor, loggedin is not mentor, in a group
                            if ( $memberId != $loggedInMemberId && $authenticated && $inGroup && $isMentor && !$isLoggedinMemberIsMentor)
                            {
?>
                                <a class="btn btn-xs btn-danger pull-right label bidx-label btn-mentoring hide" href="#mentoringRequest/confirmMentoringRequest/mentorId=<?php echo $memberId ?>"><?php _e('Request mentoring', 'bidxplugin')?></a>
<?php
                            }

?>
                        </div>
                    </div>
<?php
                    if ( $firstName ) :
?>
                    <div class="row">
                        <div class="col-sm-12">
                            <?php echo $professionalTitle; ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <?php if ( $isEntrepreneur ) { ?>
                                <span class="label bidx-label bidx-entrepreneur"><?php _e('Entrepreneur', 'bidxplugin') ?></span>
                            <?php } ?>
                            <?php if ( $isInvestor && ($this->isLoggedInInvestor || $this->isLoggedInGroupOwner)) { ?>
                                <span class="label bidx-label bidx-investor"><?php _e('Investor', 'bidxplugin') ?></span>
                            <?php } ?>
                            <?php if ( $isMentor ) { ?>
                                <span class="label bidx-label bidx-mentor"><?php _e('Mentor', 'bidxplugin') ?></span>
                            <?php } ?>
                            <?php if ( !$isEntrepreneur || !$isInvestor ) { ?>
                                <span class="label bidx-label bidx-member"><?php _e('Member', 'bidxplugin') ?></span>
                            <?php } ?>
                        </div>
                    </div>
                    <hr>

                    <div class="row">
<?php
                        // Fields for left column
                        $leftCol = array ( $gender, $nationality, $motherlanguage );
                        echo $this->addMultipleRows('col-sm-5', $leftCol);

                        // Fields for right column
                        $rightCol = array ( $dateofBirth, $highestEducation, $languageDetails, $address );
                        echo $this->addMultipleRows('col-sm-7', $rightCol);
?>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-sm-7">
<?php
                            $rowValues = array (__('E-mail','bidxplugin') => $this->exst ($personalDetails->emailAddress));
                            echo $this->addRowsWithLabelAdjacent ('col-xs-3', 'col-sm-8', $rowValues, array ('class_label' => 'label label-info btn-block text-center'));
                            $rowValues = array (__('Mobile','bidxplugin') => $this->getMultiValues ($this->exst ($personalDetails->contactDetail), ', ', NULL, 'mobile'));
                            echo $this->addRowsWithLabelAdjacent ('col-xs-3', 'col-sm-8', $rowValues, array ('class_label' => 'label label-info btn-block text-center'));
                            $rowValues = array (__('Fax','bidxplugin') => $this->getMultiValues ($this->exst ($personalDetails->contactDetail), ', ', NULL, 'fax'));
                            echo $this->addRowsWithLabelAdjacent ('col-xs-3', 'col-sm-8', $rowValues, array ('class_label' => 'label label-info btn-block text-center'));
                            $rowValues = array (__('Landline','bidxplugin') => $this->getMultiValues ($this->exst ($personalDetails->contactDetail), ', ', NULL, 'landLine'));
                            echo $this->addRowsWithLabelAdjacent ('col-xs-3', 'col-sm-8', $rowValues, array ('class_label' => 'label label-info btn-block text-center'));
?>
                        </div>

                        <div class="col-sm-5 member-social">
<?php
                            $rowValues1 = array (
                                __('Facebook','bidxplugin') => $this->addSocialPluginScript ('facebookprofile', $this->exst ($personalDetails->facebook)),
                                __('Linkedin','bidxplugin') => $this->addSocialPluginScript ('linkedin', $this->exst ($personalDetails->linkedIn)),
                            );
                            if ( $authenticated ) {
                                $rowValues2 = array (
                                    __('Twitter','bidxplugin') => $this->addSocialPluginScript ('twitterprofile', $this->exst ($personalDetails->twitter)),
                                    __('Skype','bidxplugin') => $this->addSocialPluginScript ('skype', $this->exst ($personalDetails->skype))
                                );
                            }
                            $rowValues = ( isset( $rowValues2 ) ) ? array_merge( $rowValues1, $rowValues2 ) : $rowValues1;
                            echo $this->addAdjacentRows ('pull-left', $rowValues, array ('Skype' => 'skypeclass', 'Linkedin' => 'linkedin', 'Facebook' => 'facebook', 'Twitter' => 'twitter' ));
?>
                        </div>
                    </div>
<?php
                    endif;
?>
                </div>
            </div>

            <?php
                // Attachments
                //
                if ( $this->exst ($personalDetails->attachment) )
                {
                    echo $this->displayDocuments ( $personalDetails->attachment, __('Documents','bidxplugin') );
                }
            ?>

