<?php

$entrepreneurDetails = isset($this->data->bidxEntrepreneurProfile) ? $this->data->bidxEntrepreneurProfile : NULL ;
$businessSummary = isset ($this->data->wp->entities->bidxBusinessSummary) ? $this->data->wp->entities->bidxBusinessSummary : NULL;
$memberId                   = isset( $this->data->member->bidxMeta->bidxMemberId ) ? $this->data->member->bidxMeta->bidxMemberId : null ;
$loggedInMemberId           = isset( $this -> sessionData -> data -> id ) ? $this -> sessionData -> data -> id : null;
$authenticated              = isset( $this -> sessionData -> authenticated ) && $this -> sessionData -> authenticated ==  'true';
$groupIds                   = array_keys ( (array)$this -> sessionData -> data -> groups );
$inGroup                    = in_array( $this -> sessionData -> data -> currentGroup, $groupIds);
$isLoggedinMemberIsMentor   = isset( $this -> sessionData -> data -> wp -> entities -> bidxMentorProfile ) ? $this -> sessionData -> data -> wp -> entities -> bidxMentorProfile : null;
$isMentor                   = isset( $data->bidxMentorProfile ) ? $data->bidxMentorProfile : NULL;
$companies = isset ($this->data->companies) ? $this->data->companies : NULL;

$entrepreneurBidxMeta = isset( $entrepreneurDetails->bidxMeta )
    ? $entrepreneurDetails->bidxMeta
    : $entrepreneurDetails;

$businessSummaryBidxMeta = isset( $businessSummary->bidxMeta )
    ? $businessSummary->bidxMeta
    : $businessSummary;

if ($entrepreneurDetails &&
    ( $entrepreneurBidxMeta->bidxEntityStatus == 'PUBLISHED' || $entrepreneurBidxMeta->bidxCanEdit  ) ) {
    ?>


<div class="panel panel-default">
    <div class="panel-heading">
        <a class="btn-block" data-toggle="collapse" data-parent="#myProfile" href="#entrepreneur-profile">
            <span class="fa fa-chevron-right accordion-state-icon"></span>
            <?php _e('Entrepreneur profile','bidxplugin');?>
        </a>
    </div>
    <div id="entrepreneur-profile" class="panel-collapse collapse">
        <div class="panel-body">




                <div class="btn-group show hide-overflow">
<?php               if ($entrepreneurBidxMeta->bidxCanEdit)
                    {
?>
                        <a class="btn btn-sm btn-primary pull-right" href="#editEntrepreneur/<?php echo $this->exst ($entrepreneurBidxMeta->bidxOwnerId); ?>"><i class="fa fa-pencil"></i> <?php _e( 'Edit', 'bidxplugin' ); ?></a>
<?php
                    }
?>
                </div>

                    <?php
                    $rowValues = array(
                        __('Summary','bidxplugin')          =>  $this->exst ($entrepreneurDetails->summary),
                        __('Focus Industry','bidxplugin')   =>  $this->getMultiValues ($this->exst ($entrepreneurDetails->focusIndustry), ', ','industry')
                        );
                    echo $this->pairRows( $rowValues );
?>
                    <hr>
<?php

                    $previousBusiness = $this->exst ($entrepreneurDetails->previousBusiness);
                    $header = array (
                        __('Name of Company','bidxplugin') => 'company',
                        __('Outcome of business','bidxplugin') => 'businessOutcome',
                        __('Company website','bidxplugin') => 'webSite'
                    );
                    $previousBusinessHtml = $this->addTableRows ($header, $previousBusiness, 'table table-bordered', '', array('webSite' => 'hidden-xs'), array( 'businessOutcome' ));
                    $rowValues = array ( __('Previous Business(es)','bidxplugin') => $previousBusinessHtml);
                    echo $this->addRowsWithLabelBelow ('col-sm-12', 'col-sm-12', $rowValues, array ('tag_label' => 'h4'));
                    /* Cv Display */
                    if ( $this->exst( $entrepreneurDetails->cv->document ) ) {
?>
                        <div class="row">
                            <div class="col-sm-12">
                                <h4><?php _e( 'CV', 'bidxplugin' ); ?></h4>
                                <a class="btn btn-info" href="<?php echo $entrepreneurDetails->cv->document; ?>">
                                    <?php echo $entrepreneurDetails->cv->documentName; ?>
                                    <i class="fa fa-download"></i>
                                </a>
                            </div>
                        </div>
<?php
                    }

                    /* Document Display */
                        if ( $this->exst ($entrepreneurDetails->attachment) ) {
                            echo $this->displayDocuments ( $entrepreneurDetails->attachment, __('Documents','bidxplugin') );
                        }
?>

<?php
        // Business Summary listing
        //
        if ($businessSummary) {
            $labelBusiness = ( count( $businessSummary ) > 1 ) ? __('Businesses','bidxplugin') : __('Business','bidxplugin');
?>
            <div class="row">
                <div class="col-sm-12">
                    <h4><?php echo $labelBusiness; ?></h4>


                    <div class="list-group js-fakecrop">
<?php
                        foreach ($businessSummary as $index => $business) {

?>
                                    <div class="list-group-item">
                                        <div class="list-group-item-text">
                                            <div class="row">
                                                <div class="col-sm-2">
<?php
                                                    if ( empty( $business -> externalVideoPitch ) ) {
                                                        echo '<div class="icons-rounded pull-left"><i class="fa fa-suitcase text-primary-light"></i></div>';
                                                    } else {
                                                        $videoUrl = $this->exst($business -> externalVideoPitch);
                                                        $parsedVideo = $this->parseVideos( $videoUrl );
                                                        $videoThumb = $parsedVideo[0]['fullsize'];

                                                        echo '<div class="img-cropper pull-left"><img src="' . $videoThumb . '" alt=""></div>';
                                                    }
?>
                                                </div>
                                                <div class="col-sm-8">
                                                    <h4 class="list-group-item-heading"><a href="<?php echo _l('businesssummary');?>/<?php echo $business->bidxMeta->bidxEntityId ?>"><?php echo $business->name; ?></a></h4>
                                                    <ul class="list-unstyled">
<?php
                                                        $businessSlogan = $this->exst ( $business->slogan );
                                                        $businessSummary = $this->exst ( $business->summary );
                                                        $businessCountry = $this->exst ( $business->countryOperation );
                                                        $businessIndustry = $this->exst ( $business->industry );

                                                        if ($businessSlogan) {
                                                            printf ('<li>%s</li>', $businessSlogan);
                                                        }

                                                        if ($businessSummary) {
                                                            printf ('<li>%s</li>', $businessSummary);
                                                        }

                                                        if ($businessIndustry) {
                                                            printf ('<li>%s</li>', $this->getMultiValues ($businessIndustry, ', ', 'industry'));
                                                        }

                                                        if ($businessCountry) {
                                                            printf ('<li>%s</li>', $this->getMultiValues ($businessCountry, ', ', 'country'));
                                                        }

?>
                                                    </ul>
                                                </div>
                                                <div class="col-sm-2">
<?php
                                                    // If current profile is not loggedin user, not a mentor, in a group and Loggedin user is mentor
                                                    if ( $memberId != $loggedInMemberId && $authenticated && $inGroup && $isLoggedinMemberIsMentor && !$isMentor)
                                                    {
?>
                                                        <a class="btn btn-sm btn-danger pull-right bp-<?php echo $business->bidxMeta->bidxEntityId;?>" href="#mentoringRequest/confirmRequest/entityId=<?php echo $business->bidxMeta->bidxEntityId;?>"><?php _e('Mentor this plan', 'bidxplugin')?></a>
<?php
                                                    }
                                                    if ( $memberId === $loggedInMemberId )
                                                    {
?>
                                                        <a class="btn btn-xs btn-primary pull-right" href="<?php echo _l('businesssummary');?>/<?php echo $business->bidxMeta->bidxEntityId ?>/#editBusinessSummary/edit/<?php echo $business->bidxMeta->bidxEntityId; ?>"><i class="fa fa-pencil"></i> <?php _e( 'Edit', 'bidxplugin' ); ?></a>
<?php
                                                    }
?>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
<?php
                        }
?>
                    </div>
                </div>
            </div>
<?php
            }


        // Companies listing
        //
        if ($companies) {
            $labelCompany = ( count( $companies ) > 1 ) ? __('Companies','bidxplugin') : __('Company','bidxplugin');
?>
            <div class="row">
                <div class="col-sm-12">
                    <h4><?php echo $labelCompany; ?></h4>


                    <div class="list-group js-fakecrop">
<?php
                        foreach ($companies as $index => $company) {
?>
                            <div class="list-group-item">
                                <div class="list-group-item-text">
                                    <div class="row">
                                        <div class="col-sm-2">
<?php
                                            if ( $company->logo && $company->logo->document) {
                                                echo '<div class="img-cropper pull-left"><img src="' . $company->logo->document . '" alt=""></div>';
                                            } else {
                                                echo '<div class="icons-rounded pull-left"><i class="fa fa-tasks text-primary-light"></i></div>';
                                            }
?>
                                        </div>
                                        <div class="col-sm-8">
                                            <h4 class="list-group-item-heading"><a href="<?php echo _l('company');?>/<?php echo $company->bidxMeta->bidxEntityId ?>"><?php echo $company->name; ?></a></h4>
                                            <ul class="list-unstyled">
                                                <?php
                                                $companyWebsite = $this->exst ( $company->website );
                                                $companyRegistered = $this->exst ( $company->registered );
                                                printf ('<li>%s</li>', $company->name);

                                                if ($companyWebsite) {
                                                    printf ('<li>%s</li>', $companyWebsite);
                                                }


                                                if ($companyRegistered) {
                                                    printf ('<li>%s</li>', date ('d-m-Y', strtotime ($this->exst ($company->dateCompanyEstab))));

                                                    $arStatutoryAddress = array ();

                                                    if (!empty($company->statutoryAddress->street)) {
                                                        $arStatutoryAddress[] = $company->statutoryAddress->street;
                                                    }

                                                    if (!empty($company->statutoryAddress->streetNumber)) {
                                                        $arStatutoryAddress[] = $company->statutoryAddress->streetNumber;
                                                    }

                                                    if (!empty($company->statutoryAddress->postalCode)) {
                                                        $arStatutoryAddress[] = $company->statutoryAddress->postalCode;
                                                    }


                                                    $arStatutoryCityCountry = array ();

                                                    if (!empty($company->statutoryAddress->cityTown)) {
                                                        $arStatutoryCityCountry[] = $company->statutoryAddress->cityTown;
                                                    }

                                                    if (!empty($company->statutoryAddress->country)) {
                                                        $arStatutoryCityCountry[] = $company->statutoryAddress->country;
                                                    }

                                                    printf ('<li>%s</li>', implode (' ', $arStatutoryAddress));
                                                    printf ('<li>%s</li>', implode (' ', $arStatutoryCityCountry));
                                                }
                                                ?>
                                            </ul>
                                        </div>
                                        <div class="col-sm-2">
                                            <?php if ($company->bidxMeta->bidxCanEdit) { ?>
                                                <div class="hide-overflow">
                                                    <a class="btn btn-xs btn-primary pull-right" href="<?php echo _l('company');?>/<?php echo $company->bidxMeta->bidxEntityId;; ?>/#editCompany/<?php echo $company->bidxMeta->bidxEntityId; ?>"><i class="fa fa-pencil"></i> <?php _e( 'Edit', 'bidxplugin' ); ?></a>
                                                </div>
                                            <?php } ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
<?php
                        }
?>
                    </div>
                </div>
            </div>
<?php
            }
?>
        </div>
    </div>
</div>

<?php } ?>
