<?php

$groupDetails = $this->exst ($this->data->groups);

$showGroup = (count( (array)$groupDetails)) ? true : false;

$groupInfo = $this->exst ($this->data->groupInfo);


?>
<!-- Group Info -->
<?php
    if($groupInfo) {

              $groupDataSrc = false;
              $picSrc     = $groupInfo->logo;

              if (!$groupInfo->logo) {
                $picSrc     = 'holder.js/100x100/industrial/auto/text:No Image - group';
                $groupDataSrc = true;
              }

?>
<div class="well sidebar-block">
    <div class="row-fluid sidebar-block-heading">
        <div class="span4"><img width="100" height="100" <?php echo $groupDataSrc ? "data-" : "" ?>src="<?php echo $picSrc ?>" class="img-rounded"></div>
        <div class="span8 sidebar-block-intro">
            <h4 class="sidebar-block-title"><?php echo $groupInfo->groupName ?></h4>
            <p><?php echo $groupInfo->slogan ?></p>
        </div>
    </div>

    <!-- Description -->
    <p class="sidebar-block-content"><?php echo $groupInfo->description;?></p>

    <!-- Company name , URL -->
    <div class="row-fluid">
<?php
        //$rowValues = array('Company name' => $groupValue->bidxGroupUrl );
        //echo $this->addRowsWithLabelAdjacent('span6','span6',$rowValues);
?>
    </div>
</div>
<?php }

if( $showGroup ) { ?>
<div class="well sidebar-block">
    <!-- Joined Group -->
    <h3><?php _e('Joined groups','bidxplugin'); ?></h3>

<?php
    foreach( $groupDetails as $groupValue) {
        $joinLink = ($this->exst($groupValue->join)) ? "<a href='#joinGroup/".$groupValue->bidxGroupId."'>" . __('Join') . "</a>":'';
        $groupDataSrc = false;
              $picSrc     = $this->exst($groupValue->logo);

              if (!$picSrc) {
                $picSrc     = 'holder.js/100x100/industrial/auto/text:No Image - showgroup';
                $groupDataSrc = true;
              }
?>
    <div class="clearfix">
        <div class="row-fluid sidebar-block-heading">
            <div class="span4"><img width="100" height="100" <?php echo $groupDataSrc ? "data-" : "" ?>src="<?php echo $picSrc ?>" class="img-rounded"></div>
            <div class="span8 sidebar-block-intro">
                <h4 class="sidebar-block-title"><?php echo $groupValue->name?></h4>
                <p><?php echo $groupValue->slogan?></p>
            </div>

        </div>
        <div class="pull-right"><?php echo $joinLink ?></div>
    </div>
<?php } ?>
</div>
<?php } ?>
