<?php

$entrepreneurDetails = isset($this->data->bidxEntrepreneurProfile) ? $this->data->bidxEntrepreneurProfile : NULL ;
$businessSummary = isset ($this->data->wp->entities->bidxBusinessSummary) ? $this->data->wp->entities->bidxBusinessSummary : NULL;
$memberId                   = isset( $this->data->member->bidxMeta->bidxMemberId ) ? $this->data->member->bidxMeta->bidxMemberId : null ;
$loggedInMemberId           = isset( $this -> sessionData -> data -> id ) ? $this -> sessionData -> data -> id : null;
$authenticated              = isset( $this -> sessionData -> authenticated ) && $this -> sessionData -> authenticated ==  'true';
$groupIds                   = array_keys ( (array)$this -> sessionData -> data -> groups );
$inGroup                    = in_array( $this -> sessionData -> data -> currentGroup, $groupIds);
$isLoggedinMemberIsMentor   = isset( $this -> sessionData -> data -> wp -> entities -> bidxMentorProfile ) ? $this -> sessionData -> data -> wp -> entities -> bidxMentorProfile : null;
$isMentor                   = isset( $data->bidxMentorProfile ) ? $data->bidxMentorProfile : NULL;
$companies = isset ($this->data->companies) ? $this->data->companies : NULL;

$entrepreneurBidxMeta = isset( $entrepreneurDetails->bidxMeta )
    ? $entrepreneurDetails->bidxMeta
    : $entrepreneurDetails;

$businessSummaryBidxMeta = isset( $businessSummary->bidxMeta )
    ? $businessSummary->bidxMeta
    : $businessSummary;

if ($entrepreneurDetails &&
    ( $entrepreneurBidxMeta->bidxEntityStatus == 'PUBLISHED' || $entrepreneurBidxMeta->bidxCanEdit  ) ) {
    ?>


<div class="panel panel-default">
    <div class="panel-heading">
        <a class="btn-block" data-toggle="collapse" data-parent="#myProfile" href="#entrepreneur-profile">
            <span class="fa fa-chevron-right accordion-state-icon"></span>
            <?php _e('Entrepreneur profile','bidxplugin');?>
        </a>
    </div>
    <div id="entrepreneur-profile" class="panel-collapse collapse">
        <div class="panel-body">




                <div class="btn-group pull-right">
<?php               if ($entrepreneurBidxMeta->bidxCanEdit)
                    {
?>
                        <a class="btn btn-sm btn-primary" href="#editEntrepreneur/<?php echo $this->exst ($entrepreneurBidxMeta->bidxOwnerId); ?>"><i class="fa fa-pencil"></i> <?php _e( 'Edit', 'bidxplugin' ); ?></a>
<?php
                    }
?>
                </div>

                    <?php
                    $rowValues = array ( __('Summary','bidxplugin') => $this->exst ($entrepreneurDetails->summary));
                    echo $this->addRowsWithLabelBelow ('col-sm-12', 'col-sm-12', $rowValues, array ('tag_label' => 'h5'));
                    ?>
                    <br/>
                    <?php
                    $focusIndustry = $this->getMultiValues ($this->exst ($entrepreneurDetails->focusIndustry), ', ','industry');
                    $rowValues = array ( __('Focus Industry','bidxplugin') => $focusIndustry);
                    echo $this->addRowsWithLabelAdjacent ('col-sm-6', 'col-sm-6', $rowValues, array ('tag_label' => 'label', 'class_value' => ''));
                    ?>
                    <br/>
                    <?php
                    $previousBusiness = $this->exst ($entrepreneurDetails->previousBusiness);
                    $header = array (
                        __('Name of Company','bidxplugin') => 'company',
                        __('Outcome of business','bidxplugin') => 'businessOutcome',
                        __('Company website','bidxplugin') => 'webSite'
                    );
                    $previousBusinessHtml = $this->addTableRows ($header, $previousBusiness, 'table table-bordered', '', array('webSite' => 'hidden-xs'), array( 'businessOutcome' ));
                    $rowValues = array ( __('Previous Business(es)','bidxplugin') => $previousBusinessHtml);
                    echo $this->addRowsWithLabelBelow ('col-sm-12', 'col-sm-12', $rowValues, array ('tag_label' => 'h5'));
                    ?>
                    <br/>
                    <?php
                    /* Cv Display */
                    $cvDetails[] = $this->exst( $entrepreneurDetails->cv );
                    echo $this->getAttachmentsDisplay ('col-sm-12', 'col-sm-12', array ( __('CV','bidxplugin') => $cvDetails));

                    /* Document Display */
                    echo $this->getAttachmentsDisplay ('col-sm-12', 'col-sm-12', array ( __('Documents','bidxplugin') => $this->exst ($entrepreneurDetails->attachment)));
                    ?>

<?php
        // Business Summary listing
        //
        if ($businessSummary) {
            $labelBusiness = ($this->data->isMyProfile) ? __('My business','bidxplugin') : __('This person has a business','bidxplugin');
?>          <div class="view viewLoadrequest alert alert-info text-center">
                <div class="progress progress-striped active">
                    <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                        <?php _e ('Loading (Sending your request)...', 'bidxplugin') ?>
                    </div>
                </div>
            </div>
             <div class="well profile-block">
                <h4 id="businesssummary">Business Summary</h4>
                <div class="accordion" id="businesses">
<?php
                    foreach ($businessSummary as $index => $business) {

                        $businessBidxMeta = isset( $business->bidxMeta ) ? $business->bidxMeta : $business;

                        $collapseId = sprintf ('businessAccordion-%s', $businessBidxMeta->bidxEntityId);

?>
                        <div class="accordion-group">
                            <div class="accordion-heading">
                                <a class="accordion-toggle hide-overflow ds-block <?php echo ( $index != 0 ) ? 'collapsed' : ''; ?>" data-toggle="collapse" data-parent="#businesses" href="#<?php echo $collapseId ?>">
                                    <span class="bidx-expand pull-left"><span class="fa fa-plus-square"></span></span>
                                    <span class="bidx-collapse pull-left"><span class="fa fa-minus-square"></span></span>
                                    <h5>&nbsp;<?php echo $business->name ?></h5>
                                </a>
                            </div><!-- accordion-heading -->
                            <div id="<?php echo $collapseId ?>" class="accordion-body collapse <?php echo ( $index == 0 ) ? 'in' : ''; ?>">
                                <div class="accordion-inner">
                                    <div class="row">
                                        <div class="col-sm-2">
                                            <div class="icons-rounded pull-left"><i class="fa fa-suitcase text-primary-light"></i></div>

                                            <img <?php echo $useDataSrc ? "data-" : "" ?>src="<?php echo $picSrc ?>" class="img-rounded">
                                        </div>
                                        <div class="col-sm-8">
                                            <ul class="list-unstyled">
                                                <?php
                                                $businessSlogan = $this->exst ( $business->slogan );
                                                $businessSummary = $this->exst ( $business->summary );
                                                $businessCountry = $this->exst ( $business->countryOperation );
                                                $businessIndustry = $this->exst ( $business->industry );

                                                printf ('<li><h4>%s</h4></li>', $business->name);

                                                if ($businessSlogan) {
                                                    printf ('<li>%s</li>', $businessSlogan);
                                                }

                                                if ($businessSummary) {
                                                    printf ('<li>%s</li>', $businessSummary);
                                                }

                                                if ($businessIndustry) {
                                                    printf ('<li>%s</li>', $this->getMultiValues ($businessIndustry, ', ', 'industry'));
                                                }

                                                if ($businessCountry) {
                                                    printf ('<li>%s</li>', $this->getMultiValues ($businessCountry, ', ', 'country'));
                                                }

                                                ?>
                                            </ul>
                                        </div>
                                        <div class="col-sm-2">
                                            <?php
                                            // If current profile is not loggedin user, not a mentor, in a group and Loggedin user is mentor
                                            if ( $memberId != $loggedInMemberId && $authenticated && $inGroup && $isLoggedinMemberIsMentor && !$isMentor)
                                            {
                                             ?>
                                                <a class="btn btn-xs btn-danger pull-right label bidx-label bp-<?php echo $businessBidxMeta->bidxEntityId;?>" href="#mentoringRequest/confirmRequest/type=mentoring&action=connect&businessid=<?php echo $businessBidxMeta->bidxEntityId;?>&id=<?php echo $memberId ?>"><?php _e('Mentor this plan', 'bidxplugin')?></a>
                                           <?php
                                            } ?>
                                        </div>
                                    </div>

                                    <div class="bottom-controls">
<?php

                        //$redirect = http_build_query( array( "cancel"=> $_SERVER[ "REQUEST_URI" ] ) ); // @msp: currently useless because the view state doesnt have a hash and is not routed through Backbone
                        $viewMoreLink = "<a href='/businesssummary/" . $businessBidxMeta->bidxEntityId ."'>". __('view more','bidxplugin') ."</a>";
                        echo $viewMoreLink;
?>
                                    </div>
                                </div>
                            </div><!-- accordion-body -->
                        </div><!-- accordion-group -->
<?php
                }
?>
                </div><!-- accordion #companies -->
            </div>
<?php
            }

        // Companies listing
        //
        if ($companies) {
            $labelCompany = ($this->data->isMyProfile) ? __('My Company','bidxplugin') : __('This person has a company','bidxplugin');
?>
            <div class="well profile-block">

                <h4 id="company"><?php _e( 'Company', 'bidxplugin' ); ?></h4>

            <div class="accordion" id="companies">
        <?php
                foreach ($companies as $index => $company) {

                    $companyBidxMeta = isset( $company->bidxMeta ) ? $company->bidxMeta : $company;
                    $collapseId = sprintf ('companyAccordion-%s', $companyBidxMeta->bidxEntityId);

                    $picSrc = $this->exst ($company->logo->document);

                    ?>
                    <div class="accordion-group">
                        <div class="accordion-heading">
                            <a class="accordion-toggle hide-overflow ds-block <?php echo ( $index != 0 ) ? 'collapsed' : ''; ?>" data-toggle="collapse" data-parent="#companies" href="#<?php echo $collapseId ?>">
                                <span class="bidx-expand pull-left"><span class="fa fa-plus-square"></span></span>
                                <span class="bidx-collapse pull-left"><span class="fa fa-minus-square"></span></span>
                                <h5>&nbsp;<?php echo $company->name ?></h5>
                            </a>
                        </div><!-- accordion-heading -->
                        <div id="<?php echo $collapseId ?>" class="accordion-body collapse <?php echo ( $index == 0 ) ? 'in' : ''; ?>">
                            <div class="accordion-inner">
                            <?php if ($companyBidxMeta->bidxCanEdit) { ?>
                                <div class="hide-overflow">
                                    <a class="btn btn-sm btn-primary pull-right" href="/company/<?php echo $companyBidxMeta->bidxEntityId;; ?>/#editCompany/<?php echo $companyBidxMeta->bidxEntityId; ?>"><i class="fa fa-pencil"></i> <?php _e( 'Edit', 'bidxplugin' ); ?></a>
                                </div>
                            <?php } ?>

                                <div class="row">
                                    <div class="col-sm-2">
                                        <?php if ( $picSrc ) { ?>
                                            <img <?php //echo $useDataSrc ? "data-" : "" ?>src="<?php echo $picSrc ?>" class="img-rounded documentImage">
                                        <?php } else { ?>
                                            <div class="icons-rounded pull-left"><i class="fa fa-tasks text-primary-light"></i></div>
                                        <?php } ?>
                                    </div>
                                    <div class="col-sm-10">
                                        <ul class="list-unstyled">
                                            <?php
                                            $companyWebsite = $this->exst ( $company->website );
                                            $companyRegistered = $this->exst ( $company->registered );
                                            printf ('<li>%s</li>', $company->name);

                                            if ($companyWebsite) {
                                                printf ('<li>%s</li>', $companyWebsite);
                                            }


                                            if ($companyRegistered) {
                                                printf ('<li>%s</li>', date ('d-m-Y', strtotime ($this->exst ($company->dateCompanyEstab))));

                                                $arStatutoryAddress = array ();

                                                if (!empty($company->statutoryAddress->street)) {
                                                    $arStatutoryAddress[] = $company->statutoryAddress->street;
                                                }

                                                if (!empty($company->statutoryAddress->streetNumber)) {
                                                    $arStatutoryAddress[] = $company->statutoryAddress->streetNumber;
                                                }

                                                if (!empty($company->statutoryAddress->postalCode)) {
                                                    $arStatutoryAddress[] = $company->statutoryAddress->postalCode;
                                                }


                                                $arStatutoryCityCountry = array ();

                                                if (!empty($company->statutoryAddress->cityTown)) {
                                                    $arStatutoryCityCountry[] = $company->statutoryAddress->cityTown;
                                                }

                                                if (!empty($company->statutoryAddress->country)) {
                                                    $arStatutoryCityCountry[] = $company->statutoryAddress->country;
                                                }

                                                printf ('<li>%s</li>', implode (' ', $arStatutoryAddress));
                                                printf ('<li>%s</li>', implode (' ', $arStatutoryCityCountry));
                                            }
                                            ?>
                                        </ul>
                                    </div>
                                </div>

                                <div class="bottom-controls">
                <?php
                $viewMoreLink = "<a href='/company/" . $companyBidxMeta->bidxEntityId . "'>". __('view more','bidxplugin') ."</a>";
                echo $viewMoreLink;
                ?>
                                </div>
                            </div>
                        </div><!-- accordion-body -->
                    </div><!-- accordion-group -->
                <?php
            }
            ?>
            </div><!-- accordion #companies -->
            </div>
        <?php
            }

        ?>
        </div>
    </div>
</div>

<?php } ?>
