<div id="investor-dashboard">

    <h1 class="pagetitle">My investor dashboard</h1>
    <div class="dashboard">

        <div class="view viewError alert">
            <h1><?php _e('Error','bidxplugin')?></h1>
            <span class="errorMsg"></span>
        </div>


        <div class="accordion" id="investorDashboardAccordion">
            <!-- Help -->
             <div class="accordion-group <?php echo ($this->startingPage) ? 'accordion-open': '';?>">
                <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#investorDashboardAccordion" href="#investorDashboardAccordion-Help"><span class="fui-arrow-right accordion-state-icon"></span> <?php _e('Help','bidxplugin'); ?></a>
                </div>
                <div id="investorDashboardAccordion-Help" class="accordion-body collapse <?php echo ($this->startingPage) ? 'in': '';?>">
                    <div class="accordion-inner">
                       <?php $this->render('investor/help.phtml'); ?>
                    </div>
                 </div>
            </div>




        <div class="view viewLoad"><?php _e ('Loading matches...', 'bidxplugin') ?></div>


            <div class="accordion-group accordion-open view viewMatch">
                <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#investorDashboardAccordion" href="#investorDashboardAccordion-RecommendedBusiness"><span class="fui-arrow-right accordion-state-icon"></span> Recommended business</a>
                </div>
                <div id="investorDashboardAccordion-RecommendedBusiness" class="accordion-body collapse in">
                    <div class="accordion-inner">
                        <p>These are the groups you have created. Click on the name of the group to edit appearances, create content or administrate members</p>
                        <table class="table table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Entrepreneur</th>
                                    <th class="hidden-phone">Country</th>
                                    <th class="hidden-phone">Industry</th>
                                </tr>
                            </thead>
                            <tbody class="match investor-match">
                                <div class="pull-left">
                                    <?php //_e ('Loading...', 'bidxplugin') ?>
                                </div>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>


            <div class="view viewLoadcontact"><?php _e ('Loading businesses contacted...', 'bidxplugin') ?></div>

            <div class="accordion-group view viewContact">
                <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#investorDashboardAccordion" href="#investorDashboardAccordion-BusinessesContacted"><span class="fui-arrow-right accordion-state-icon"></span> Businesses contacted</a>
                </div>
                <div id="investorDashboardAccordion-BusinessesContacted" class="accordion-body collapse">
                    <div class="accordion-inner">
                        <p></p>
                        <table class="table table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Entrepreneur</th>
                                    <th class="hidden-phone">Location</th>
                                    <th class="hidden-phone">Industry</th>
                                    <th class="hidden-phone">Your last visit</th>
                                    <th class="hidden-phone">Request status</th>
                                    <th class="hidden-phone">Changes since last visit?</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody class="contact investor-contact ">
                                <div class="pull-left">
                                    <?php// _e ('Loading...', 'bidxplugin') ?>
                                </div>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>



            <div class="view viewLoadpreference"><?php _e ('Loading preference...', 'bidxplugin') ?></div>

            <div class="accordion-group view viewPreference">
                <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#investorDashboardAccordion" href="#investorDashboardAccordion-InvestmentPreferences"><span class="fui-arrow-right accordion-state-icon"></span> My investment preferences</a>
                </div>
                <div id="investorDashboardAccordion-InvestmentPreferences" class="accordion-body collapse">
                    <div class="accordion-inner">
                        <div class="btn-group control-buttons">
<?php
                            // #msp: is it possible not to have an ID in the page?? what would the url be then..
                            $id = $this->exst ( $this -> sessionData -> data -> id );
                            $href = "/member#editInvestor/" . $id . "/" . http_build_query( array( "success"=> "/investor-dashboard/#dashboard/investor", "cancel"=> "/investor-dashboard/#dashboard/investor" ) );
?>
                            <a class="btn btn-primary" href="<?php echo $href; ?>"><?php _e('Edit','bidxplugin'); ?></a>
                        </div>
                        <p></p>
                        <div class="preference investor-preference ">
                            <div class="pull-left">
                                <?php //_e ('Loading...', 'bidxplugin') ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div><!-- accordion -->

    </div>
</div>
<script type="text/html" id="investor-contactitem">
<!--
<tr>
    <td>
      <a data-toggle="collapse" data-target="#%accordion-id%" class="accordion-toggle">
      <span class="placeholder name">%name%</span>
      </a>
   </td>
    <td>
        <span class="placeholder name">%name%</span>
    </td>
    <td class="hidden-phone">
        <span class="placeholder countryOperation">%countryOperation%</span>
    </td>
    <td class="hidden-phone">
        <span class="placeholder industry">%industry%</span>
    </td>
    <td class="hidden-phone">
        <span class="placeholder bidxCreationDateTime">%bidxCreationDateTime%</span>
    </td>
    <td class="hidden-phone">
        <a  data-toggle="collapse" data-target="#status-%accordion-id%" class="accordion-toggle">
        <span class="placeholder status">%status%</span>
        </a>
    </td>
    <td class="hidden-phone">
        <span class="placeholder bidxCreationDateTime">%bidxCreationDateTime%</span>
    </td>
    <td>
        <span class="placeholder stopviewing"><a href="#">Stop viewing</a></span>
    </td>
</tr>
<tr class="list detail-list" >
    <td colspan="8" class="detailRow">
        <div class="accordion-body collapse" id="%accordion-id%">
            <div class="row-fluid">
                <div class="span2">
                    <span class="placeholder document"><img src="%document%"/></span>
                </div>
                <div class="span10">
                    <div class="row-fluid">
                        <div class="span6">
                            <label>Business proposal</label>
                            <div class="placeholder name"><a target = "_blank" href="/businesssummary/%bidxEntityId%">%name%</a></div>
                        </div>
                        <div class="span6">
                             <label>Entrepreneur</label>
                             <div class="placeholder creator"><a target = "_blank" href="/member/%bidxOwnerId%">%creator%</a></div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span6">
                            <label>Industry</label>
                            <div class="placeholder industry">%industry%</div>
                        </div>
                        <div class="span6">
                            <label>Product</label>
                            <div class="placeholder productService">%productService%</div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span6">
                            <label>Country</label>
                            <div class="placeholder countryOperation">%countryOperation%</div>
                        </div>
                        <div class="span6">
                            <label>Investment needed</label>
                            <div class="placeholder financingNeeded">%financingNeeded%</div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span6">
                            <label>Business stage</label>
                            <div class="placeholder stageBusiness">%stageBusiness%</div>
                        </div>
                        <div class="span6">
                            <label>Environmental Impact</label>
                            <div class="placeholder envImpact">%envImpact%</div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span6 offset6">
                            <div class="pull-right">
                                <span class="placeholder bidxEntityId"><a target = "_blank" href="/businesssummary/%bidxEntityId%">View Proposal</a> </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </td>
</tr>
<tr>
    <td colspan="8" class="detailRow">
        <div class="accordion-body collapse" id="status-%accordion-id%">
            <div class="row-fluid detailContent">
                <div class="span12">
                    <h3>Acces requests</h3>
                    <div class="alert alert-info">
                        Subject: Request to view full details of your plan <BR>
                        To: <span class="placeholder contactName">%contactName%</span> <BR>
                        Date: <span class="placeholder startDate">%startDate%</span> <BR>
                    </div>
                </div>
                <div class="pull-right">
                    <a href="#">Send new email</a>
                </div>
            </div>
        </div>
    </td>
</tr>
-->
</script>
<script type="text/html" id="investor-preferenceitem">
<!--
    <div class="row-fluid">
        <div class="span6">
            <label>Industry</label>
            <div class="placeholder focusIndustry">%focusIndustry%</div>
        </div>
        <div class="span6">
            <label>Social impact</label>
            <div class="placeholder focusSocialImpact">%focusSocialImpact%</div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span6">
            <label>Environmental impact</label>
            <div class="placeholder focusEnvImpact">%focusEnvImpact%</div>
        </div>
        <div class="span6">
            <label>Languages</label>
            <div class="placeholder focusLanguage" >%focusLanguage%</div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span6">
            <label>Country</label>
            <div class="placeholder focusCountry" >%focusCountry%</div>
        </div>
        <div class="span6">
            <label>Consumer type</label>
            <div class="placeholder focusConsumerType" >%focusConsumerType%</div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span6">
            <label>Stage of business</label>
            <div class="placeholder focusStageBusiness" >%focusStageBusiness%</div>
        </div>
        <div class="span6">
            <label>Gender</label>
            <div class="placeholder focusGender" >%focusGender%</div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span6">
            <label>Investment type</label>
            <div class="placeholder investmentType" >%investmentType%</div>
        </div>
        <div class="span6">
            <label>Minimum investment</label>
            <div class="placeholder minInvestment" >%minInvestment%</div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span6">
            <label>Maximum investment</label>
            <div class="placeholder maxInvestment" >%maxInvestment%</div>
        </div>
        <div class="span6">
            <label>Total investment in the previous year</label>
            <div class="placeholder totalInvestment">%totalInvestment%</div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span6">
            <label>Other preferences</label>
            <div class="placeholder additionalPreferences" >%additionalPreferences%</div>
        </div>
    </div>
    -->

</script>
<script type="text/html" id="investor-matchitem">
    <!--
    <tr>
   <td>
      <a data-toggle="collapse" data-target="#%accordion-id%" class="accordion-toggle">
      <span class="placeholder name_s">%name_s%</span>
      </a>
   </td>
   <td>
      <span class="placeholder creator"><a target = "_blank" href="/member/%creatorId%" >%creator%</a></span>
   </td>
   <td class="hidden-phone">
      <span class="placeholder countrylabel_ss">%countrylabel_ss%</span>
   </td>
   <td class="hidden-phone">
      <span class="placeholder industrylabel_ss">%industrylabel_ss%</span>
   </td>
</tr>
<tr class="list detail-list" >
   <td colspan="5" class="detailRow">
      <div class="accordion-body collapse" id="%accordion-id%">
      <div class="row-fluid">
            <div class="span3">
                <span class="placeholder companylogodoc_url"><img src="%companylogodoc_url%"/></span>
            </div>
        <div class="span9">
            <div class="row-fluid">
                <div class="span6">
                    <label>Business proposal</label>
                    <div class="placeholder name_s"><a target = "_blank" href="/businesssummary/%entityid_l%">%name_s%</a></div>
                </div>
                <div class="span6">
                     <label>Entrepreneur</label>
                     <div class="placeholder creator"><a target = "_blank" href="/member/%creatorId%">%creator%</a></div>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span6">
                    <label>Industry</label>
                    <div class="placeholder industrylabel_ss">%industrylabel_ss%</div>
                </div>
                <div class="span6">
                    <label>Product</label>
                    <div class="placeholder productservicelabel_ss">%productservicelabel_ss%</div>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span6">
                    <label>Country</label>
                    <div class="placeholder countrylabel_ss">%countrylabel_ss%</div>
                </div>
                <div class="span6">
                    <label>Investment needed</label>
                    <div class="placeholder financingneeded_d">%financingneeded_d%</div>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span6">
                    <label>Business stage</label>
                    <div class="placeholder stagebusinesslabel_s">%stagebusinesslabel_s%</div>
                </div>
                <div class="span6">
                    <label>Environmental Impact</label>
                    <div class="placeholder envimpactlabel_ss">%envimpactlabel_ss%</div>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span6 offset6">
                    <div class="pull-right">
                        <span class="placeholder entityid_l"><a target = "_blank" href="/businesssummary/%entityid_l%">View Proposal</a> </span>
                    </div>
                </div>
            </div>
         </div>
      </div>
      </div>
   </td>
</tr>
<tr class="list entrepreneur-list" >
   <div class="pull-left">
      <?php _e ('Loading...', 'bidxplugin') ?>
   </div>
</tr>
    -->
</script>
<script type="text/html" id="investor-empty">
<!--
<tr class="match investor-match" >
    <td colspan='7'>
       <div class="pull-left">
          <?php _e ('No matches available', 'bidxplugin') ?>
       </div>
    </td>
</tr>
-->
</script>

<script type="text/html" id="entrepreneur-listitem">
    <!--
    <td colspan="5" class="detailRow">
    <div class="accordion-body collapse" id="table1-row1-col2">
    <div class="row-fluid">
    <div class="span12">
    <h4>Entrepreneur Profile</h4>
    <ul class="unstyled">
    <li>
    <label>Entrepreneur</label>
    <span class="placeholder ename"/>
    </li>
    <li>
    <label>Industry</label>
    <span class="placeholder eindustry"/>
    </li>
    <li>
    <label>Product</label>
    <span class="placeholder eproduct"/>
    </li>
    <li>
    <label>Country</label>
    <span class="placeholder ecountry"/>
    </li>
    <li>
    <label>Investment needed</label>
    <span class="placeholder eamount"/>
    </li>
    <li>
    <label>Business stage</label>
    <span class="placeholder estage"/>
    </li>
    <li>
    <label>Impact</label>
    <span class="placeholder eimpact"/>
    </li>
    </ul>
    </div>

    <div class="pull-right">
    <a href="#">View full profile</a>
    </div>
    </div>
    </div>
    </td>
    -->
</script>


