<div id="investor-dashboard">

    <h1 class="pagetitle"><?php _e('My investor dashboard','bidxplugin');?></h1>
    <div class="dashboard">

        <div class="view viewError alert alert-warning">
            <h1><?php _e('Error','bidxplugin')?></h1>
            <span class="errorMsg"></span>
        </div>


        <div id="investorDashboardAccordion">
            <!-- Help -->
            <div class="view viewLoad alert alert-info text-center">
                <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e ('Loading matches...', 'bidxplugin') ?>
            </div>
            <div class="view viewLoadcontact alert alert-info text-center">
                <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e ('Loading businesses contacted...', 'bidxplugin') ?>
            </div>
            <div class="view viewLoadpreference alert alert-info text-center">
                <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e ('Loading preference...', 'bidxplugin') ?>
            </div>

            <div class="panel panel-default <?php echo ($this->startingPage) ? 'panel-open': '';?>">
                <div class="panel-heading">
                    <a class="btn-block" data-toggle="collapse" data-parent="#investorDashboardAccordion" href="#investorDashboardAccordion-Help"><span class="fa fa-chevron-right accordion-state-icon"></span> <?php _e('Help','bidxplugin'); ?></a>
                </div>
                <div id="investorDashboardAccordion-Help" class="panel-collapse collapse <?php echo ($this->startingPage) ? 'in': '';?>">
                    <div class="panel-body">
                       <?php $this->render('investor/help.phtml'); ?>
                    </div>
                 </div>
            </div>
            <div class="panel panel-default panel-open view viewMatch">
                <div class="panel-heading">
                    <a class="btn-block" data-toggle="collapse" data-parent="#investorDashboardAccordion" href="#investorDashboardAccordion-RecommendedBusiness"><span class="fa fa-chevron-right accordion-state-icon"></span> <?php _e('Recommended business','bidxplugin'); ?></a>
                </div>
                <div id="investorDashboardAccordion-RecommendedBusiness" class="panel-collapse collapse in">
                    <div class="panel-body">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th><?php _e('Title','bidxplugin');?></th>
                                    <th><?php _e('Entrepreneur','bidxplugin');?></th>
                                    <th class="hidden-xs"><?php _e('Country','bidxplugin');?></th>
                                    <th class="hidden-xs"><?php _e('Industry','bidxplugin');?></th>
                                </tr>
                            </thead>
                            <tbody class="match investor-match">
                                <div class="pull-left">
                                    <?php //_e ('Loading...', 'bidxplugin') ?>
                                </div>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>



            <div class="panel panel-default view viewContact">
                <div class="panel-heading">
                    <a class="btn-block" data-toggle="collapse" data-parent="#investorDashboardAccordion" href="#investorDashboardAccordion-BusinessesContacted"><span class="fa fa-chevron-right accordion-state-icon"></span> <?php _e('Businesses contacted','bidxplugin');?></a>
                </div>
                <div id="investorDashboardAccordion-BusinessesContacted" class="panel-collapse collapse">
                    <div class="panel-body">
                        <p></p>
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th><?php _e('Title','bidxplugin');?></th>
                                    <th><?php _e('Entrepreneur','bidxplugin');?></th>
                                    <th class="hidden-xs"><?php _e('Location','bidxplugin');?></th>
                                    <th class="hidden-xs"><?php _e('Industry','bidxplugin');?></th>
                                    <th class="hidden-xs"><?php _e('Your last visit','bidxplugin');?></th>
                                    <th class="hidden-xs"><?php _e('Request status','bidxplugin');?></th>
                                    <th class="hidden-xs"><?php _e('Changes since last visit?','bidxplugin');?></th>
                                    <th class="hide"></th>
                                </tr>
                            </thead>
                            <tbody class="contact investor-contact ">
                                <div class="pull-left">
                                    <?php// _e ('Loading...', 'bidxplugin') ?>
                                </div>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>




            <div class="panel panel-default view viewPreference">
                <div class="panel-heading">
                    <a class="btn-block" data-toggle="collapse" data-parent="#investorDashboardAccordion" href="#investorDashboardAccordion-InvestmentPreferences"><span class="fa fa-chevron-right accordion-state-icon"></span> <?php _e('My investment preferences','bidxplugin');?></a>
                </div>
                <div id="investorDashboardAccordion-InvestmentPreferences" class="panel-collapse collapse">
                    <div class="panel-body">
                        <div class="hide-overflow">
                            <div class="btn-group pull-right">
<?php
                                // #msp: is it possible not to have an ID in the page?? what would the url be then..
                                $id = $this->exst ( $this -> sessionData -> data -> id );
                                $href = _l('member'). "#editInvestor/" . $id . "/" . http_build_query( array( "success"=> _l('investor-dashboard')."#dashboard/investor", "cancel"=> _l('investor-dashboard')."#dashboard/investor" ) );
?>
                                <a class="btn btn-primary" href="<?php echo $href; ?>"><i class="fa fa-pencil"></i> <?php _e( 'Edit', 'bidxplugin' ); ?></a>
                            </div>
                        </div>
                        <div class="preference investor-preference"></div>
                    </div>
                </div>
            </div>


        </div><!-- accordion -->

    </div>
</div>
<script type="text/html" id="investor-contactitem">
<!--
<tr>
    <td>
      <a data-toggle="collapse" data-target="#%accordion-id%" class="btn-block">
      <span class="placeholder name">%name%</span>
      </a>
   </td>
    <td>
        <span class="placeholder name">%creator%</span>
    </td>
    <td class="hidden-xs">
        <span class="placeholder countryOperation">%countryOperation%</span>
    </td>
    <td class="hidden-xs">
        <span class="placeholder industry">%industry%</span>
    </td>
    <td class="hidden-xs">
        <span class="placeholder bidxCreationDateTime">%bidxCreationDateTime%</span>
    </td>
    <td class="hidden-xs">
        <span class="placeholder status">%status%</span>
    </td>
    <td class="hidden-xs">
        <span class="placeholder bidxCreationDateTime">%bidxCreationDateTime%</span>
    </td>
    <td class="hide">
        <span class="placeholder stopviewing"><a href="#"><?php _e( 'Stop viewing','bidxplugin');?></a></span>
    </td>
</tr>
<tr class="list detail-list" >
    <td colspan="8" class="detailRow">
        <div class="panel-collapse collapse" id="%accordion-id%">
            <div class="row">
                <div class="col-sm-2">
                    <a class="pull-left" href="<?php echo _l('businesssummary');?>/%bidxEntityId%" data-role='businessImage'>
                        <div class="icons-rounded pull-left"><i class="fa fa-suitcase text-primary-light"></i></div>
                    </a>
                </div>
                <div class="col-sm-10">
                    <div class="row">
                        <div class="col-sm-6">
                            <label><?php _e('Business proposal','bidxplugin');?></label>
                            <div class="placeholder name"><a target = "_blank" href="/businesssummary/%bidxEntityId%">%name%</a></div>
                        </div>
                        <div class="col-sm-6">
                             <label><?php _e('Entrepreneur','bidxplugin');?></label>
                             <div class="placeholder creator"><a target = "_blank" href="/member/%bidxOwnerId%">%creator%</a></div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <label><?php _e('Industry','bidxplugin');?></label>
                            <div class="placeholder industry">%industry%</div>
                        </div>
                        <div class="col-sm-6">
                            <label><?php _e('Product','bidxplugin');?></label>
                            <div class="placeholder productService">%productService%</div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <label><?php _e('Country','bidxplugin');?></label>
                            <div class="placeholder countryOperation">%countryOperation%</div>
                        </div>
                        <div class="col-sm-6">
                            <label><?php _e('Investment needed','bidxplugin');?></label>
                            <div class="placeholder financingNeeded">%financingNeeded%</div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <label><?php _e('Business stage','bidxplugin');?></label>
                            <div class="placeholder stageBusiness">%stageBusiness%</div>
                        </div>
                        <div class="col-sm-6">
                            <label><?php _e('Environmental Impact','bidxplugin');?></label>
                            <div class="placeholder envImpact">%envImpact%</div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-6">
                            <div class="pull-right">
                                <span class="placeholder bidxEntityId"><a target = "_blank" href="<?php echo _l('businesssummary');?>/%bidxEntityId%"><?php _e('View Proposal','bidxplugin');?></a> </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </td>
</tr>
-->
</script>
<script type="text/html" id="investor-preferenceitem">
<!--
    <div class="row">
        <div class="col-sm-6">
            <label><?php _e('Industry','bidxplugin');?></label>
            <div class="placeholder focusIndustry">%focusIndustry%</div>
        </div>
        <div class="col-sm-6">
            <label><?php _e('Social impact','bidxplugin');?></label>
            <div class="placeholder focusSocialImpact">%focusSocialImpact%</div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <label><?php _e('Environmental impact','bidxplugin');?></label>
            <div class="placeholder focusEnvImpact">%focusEnvImpact%</div>
        </div>
        <div class="col-sm-6">
            <label><?php _e('Languages','bidxplugin');?></label>
            <div class="placeholder focusLanguage" >%focusLanguage%</div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <label><?php _e('Country','bidxplugin');?></label>
            <div class="placeholder focusCountry" >%focusCountry%</div>
        </div>
        <div class="col-sm-6">
            <label><?php _e('Consumer type','bidxplugin');?></label>
            <div class="placeholder focusConsumerType" >%focusConsumerType%</div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <label><?php _e('Stage of business','bidxplugin');?></label>
            <div class="placeholder focusStageBusiness" >%focusStageBusiness%</div>
        </div>
        <div class="col-sm-6">
            <label><?php _e('Gender','bidxplugin');?></label>
            <div class="placeholder focusGender" >%focusGender%</div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <label><?php _e('Investment type','bidxplugin');?></label>
            <div class="placeholder investmentType" >%investmentType%</div>
        </div>
        <div class="col-sm-6">
            <label><?php _e('Minimum investment','bidxplugin');?></label>
            <div class="placeholder minInvestment" >%minInvestment%</div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <label><?php _e('Maximum investment','bidxplugin');?></label>
            <div class="placeholder maxInvestment" >%maxInvestment%</div>
        </div>
        <div class="col-sm-6">
            <label><?php _e('Total investment in the previous year','bidxplugin');?></label>
            <div class="placeholder totalInvestment">%totalInvestment%</div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <label><?php _e('Other preferences','bidxplugin');?></label>
            <div class="placeholder additionalPreferences" >%additionalPreferences%</div>
        </div>
    </div>
    -->

</script>
<script type="text/html" id="investor-matchitem">
    <!--
    <tr>
   <td>
      <a data-toggle="collapse" data-target="#%accordion-id%" class="btn-block">
      <span class="placeholder name_s">%name_s%</span>
      </a>
   </td>
   <td>
      <span class="placeholder creator"><a target = "_blank" href="<?php echo _l('member');?>/%creatorId%" >%creator%</a></span>
   </td>
   <td class="hidden-xs">
      <span class="placeholder countrylabel_ss">%countrylabel_ss%</span>
   </td>
   <td class="hidden-xs">
      <span class="placeholder industrylabel_ss">%industrylabel_ss%</span>
   </td>
</tr>
<tr class="list detail-list" >
   <td colspan="5" class="detailRow">
      <div class="panel-collapse collapse" id="%accordion-id%">
      <div class="row">
            <div class="col-sm-3">
                <a class="pull-left" href="<?php echo _l('businesssummary');?>/%entityid_l%" data-role='businessImage'>
                    <div class="icons-rounded pull-left"><i class="fa fa-suitcase text-primary-light"></i></div>
                </a>
            </div>
        <div class="col-sm-9">
            <div class="row">
                <div class="col-sm-6">
                    <label><?php _e('Business proposal','bidxplugin');?></label>
                    <div class="placeholder name_s"><a target = "_blank" href="<?php echo _l('businesssummary');?>/%entityid_l%">%name_s%</a></div>
                </div>
                <div class="col-sm-6">
                     <label><?php _e('Entrepreneur','bidxplugin');?></label>
                     <div class="placeholder creator"><a target = "_blank" href="<?php echo _l('member');?>/%creatorId%">%creator%</a></div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <label><?php _e('Industry','bidxplugin');?></label>
                    <div class="placeholder industrylabel_ss">%industrylabel_ss%</div>
                </div>
                <div class="col-sm-6">
                    <label><?php _e('Product','bidxplugin');?></label>
                    <div class="placeholder productservicelabel_ss">%productservicelabel_ss%</div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <label><?php _e('Country','bidxplugin');?></label>
                    <div class="placeholder countrylabel_ss">%countrylabel_ss%</div>
                </div>
                <div class="col-sm-6">
                    <label><?php _e('Investment needed','bidxplugin');?></label>
                    <div class="placeholder financingneeded_d">%financingneeded_d%</div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <label><?php _e('Business stage','bidxplugin');?></label>
                    <div class="placeholder stagebusinesslabel_s">%stagebusinesslabel_s%</div>
                </div>
                <div class="col-sm-6">
                    <label><?php _e('Environmental Impact','bidxplugin');?></label>
                    <div class="placeholder envimpactlabel_ss">%envimpactlabel_ss%</div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 col-sm-offset-6">
                    <div class="pull-right">
                        <span class="placeholder entityid_l"><a class="btn btn-primary btn-sm" target = "_blank" href="<?php echo _l('businesssummary');?>/%entityid_l%"><?php _e('View Proposal','bidxplugin');?></a> </span>
                    </div>
                </div>
            </div>
         </div>
      </div>
      </div>
   </td>
</tr>
    -->
</script>
<script type="text/html" id="investor-empty">
<!--
<tr class="match investor-match" >
    <td colspan='7'>
       <div class="pull-left">
          <?php _e ('No matches available', 'bidxplugin') ?>
       </div>
    </td>
</tr>
-->
</script>

<script type="text/html" id="entrepreneur-listitem">
    <!--
    <td colspan="5" class="detailRow">
    <div class="panel-collapse collapse" id="table1-row1-col2">
    <div class="row">
    <div class="col-sm-12">
    <h4><?php _e('Entrepreneur Profile','bidxplugin');?></h4>
    <ul class="list-unstyled">
    <li>
    <label><?php _e('Entrepreneur','bidxplugin');?></label>
    <span class="placeholder ename"/>
    </li>
    <li>
    <label><?php _e('Industry','bidxplugin');?></label>
    <span class="placeholder eindustry"/>
    </li>
    <li>
    <label><?php _e('Product','bidxplugin');?></label>
    <span class="placeholder eproduct"/>
    </li>
    <li>
    <label><?php _e('Country','bidxplugin');?></label>
    <span class="placeholder ecountry"/>
    </li>
    <li>
    <label><?php _e('Investment needed','bidxplugin');?></label>
    <span class="placeholder eamount"/>
    </li>
    <li>
    <label><?php _e('Business stage','bidxplugin');?></label>
    <span class="placeholder estage"/>
    </li>
    <li>
    <label><?php _e('Impact','bidxplugin');?></label>
    <span class="placeholder eimpact"/>
    </li>
    </ul>
    </div>

    <div class="pull-right">
    <a href="#"><?php _e('View full profile','bidxplugin');?></a>
    </div>
    </div>
    </div>
    </td>
    -->
</script>


