<div id="investor-dashboard">
    <h1>Investor dashboard</h1>
    <section class="row-fluid dashboard">
        <article class="view viewLoad"><?php _e ('Loading...', 'bidxplugin') ?></article>
        <article class="view viewError alert">
                <h1><?php _e('Error','bidxplugin')?></h1>
                <span class="errorMsg"></span>
            </article>
        <article class="view viewMatch">
            <div class="row-fluid ">

                <div class="span12 well">
                    <h2>Recommended business</h2>
                    <p>These are the groups you have created. Click on the name of the group to edit appearances, create content or administrate members</p>
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Entrepreneur</th>
                                <th>Country</th>
                                <th>Industry</th>

                            </tr>
                        </thead>
                        <tbody class="match investor-match">
                        <div class="pull-left">
                            <?php //_e ('Loading...', 'bidxplugin') ?>
                        </div>
                        </tbody>
                    </table>
                </div>
            </div>
        </article>
        <article class="view viewLoadcontacts"><?php _e ('Loading...', 'bidxplugin') ?></article>
        <article class="view viewContacts">
            <div class="row-fluid">

                <div class="span12 well">
                    <h2>Businesses contacted</h2>
                    <p></p>
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Entrepreneur</th>
                                <th>Location</th>
                                <th>Industry</th>
                                <th>Full access request</th>
                            </tr>
                        </thead>
                        <tbody class="contacts investor-contacts ">
                        <div class="pull-left">
                            <?php// _e ('Loading...', 'bidxplugin') ?>
                        </div>
                        </tbody>
                    </table>
                </div>
            </div>
        </article>

        <article class="view viewLoadpreference"><?php _e ('Loading...', 'bidxplugin') ?></article>
        <article class="view viewPreference">
            <div class="row-fluid">
                <div class="span12 profile-block well">
                    <div class="btn-group control-buttons">
                        <a class="btn btn-primary" href="/member#editInvestor/<?php echo $this->exst ($this->sessionData->data->id); ?>/investmentPreferences"><?php _e('Edit','bidxplugin'); ?></a>
                    </div>
                    <h2>My investment preferences</h2>
                    <p></p>
                    <div class="preference investor-preference ">
                        <div class="pull-left">
                            <?php //_e ('Loading...', 'bidxplugin') ?>
                        </div>
                    </div>
                </div>
            </div>
        </article>
</div>
<script type="text/html" id="investor-contactitem">
    <!--
    <tr>
    <td>
    <span class="placeholder name"/>
    </td>
    <td>
    <span class="placeholder country"/>
    </td>
    <td>
    <span class="placeholder bcindustry"/>
    </td>
    <td>
    <a  data-toggle="collapse" data-target="#table2-row1" class="accordion-toggle">
    <span class="placeholder bcstatus"/>
    </a>
    </td>
    </tr>
    <tr>
    <td colspan="5" class="detailRow">
    <div class="accordian-body collapse" id="table2-row1">
    <div class="row-fluid detailContent">
    <div class="span12">
    <h3>Acces requests</h3>
    <div class="alert alert-info">

    Subject: Request to view full details of your plan <BR>


    To: <span class="placeholder name"/> <BR>

    Date: <span class="placeholder startDate"/> <BR>

    </div>

    </div>
    <div class="pull-right">
    <a href="#">Send new email</a>
    </div>
    </div>
    </div>
    </td>
    </tr>
    -->
</script>
<script type="text/html" id="investor-preferenceitem">
    <!--
    <div class="row-fluid">
       <div class="span6"><label>Industry</label></div>
       <div class="span6"><div class="placeholder focusIndustry" /> </div>
    </div>
    <div class="row-fluid">
       <div class="span6"><label>Social impact</label></div>
       <div class="span6"><div class="placeholder focusSocialImpact" /></div>
    </div>
    <div class="row-fluid">
       <div class="span6"><label>Environmental impact</label></div>
       <div class="span6"><div class="placeholder focusEnvImpact" /></div>
    </div>
    <div class="row-fluid">
       <div class="span6"><label>Languages</label></div>
       <div class="span6"><div class="placeholder focusLanguage" /></div>
    </div>
    <div class="row-fluid">
       <div class="span6"><label>Country</label></div>
       <div class="span6"><div class="placeholder focusCountry" /></div>
    </div>
    <div class="row-fluid">
       <div class="span6"><label>Consumer type</label></div>
       <div class="span6"><div class="placeholder focusConsumerType" /></div>
    </div>
    <div class="row-fluid">
       <div class="span6"><label>Stage of business</label></div>
       <div class="span6"><div class="placeholder focusStageBusiness" /></div>
    </div>
    <div class="row-fluid">
       <div class="span6"><label>Gender</label></div>
       <div class="span6"><div class="placeholder focusGender" /></div>
    </div>
    <div class="row-fluid">
       <div class="span6"><label>Investment type</label></div>
       <div class="span6"><div class="placeholder investmentType" /></div>
    </div>
    <div class="row-fluid">
       <div class="span6"><label>Investment size</label></div>
    </div>
    <div class="row-fluid">
       <div class="span6"><label>Minimum investment</label></div>
       <div class="span6"><div class="placeholder minInvestment" /></div>
    </div>
    <div class="row-fluid">
       <div class="span6"><label>Maximum investment</label></div>
       <div class="span6"><div class="placeholder maxInvestment" /></div>
    </div>
    <div class="row-fluid">
       <div class="span6"><label>Total investment in the previous year</label></div>
       <div class="span6"><div class="placeholder totalInvestment" /></div>
    </div>
    <div class="row-fluid">
       <div class="span6"><label>Other preferences</label></div>
       <div class="span6"><div class="placeholder additionalPreferences" /></div>
    </div>
    -->

</script>
<script type="text/html" id="investor-matchitem">
    <!--
    <tr>
   <td>
      <a data-toggle="collapse" class="accordion-toggle toggleid">
      <span class="placeholder name_s"/>
      </a>
   </td>
   <td>
      <span class="placeholder creator"/>
      
   </td>
   <td>
      <span class="placeholder countrylabel_ss"/>
   </td>
   <td>
      <span class="placeholder industrylabel_ss"/>
   </td>
</tr>
<tr class="list detail-list" >
   <td colspan="5" class="detailRow">
      <div class="accordian-body collapse toggleid">
         <div class="row-fluid">
            <div class="span6">
               <ul class="unstyled">
                  <li>
                     <label>Business proposal</label>
                     <span class="placeholder name_s"/>
                  </li>
                  <li>
                     <label>Entrepreneur</label>
                     <span class="placeholder creator"/>
                  </li>
                  <li>
                     <label>Industry</label>
                     <span class="placeholder industrylabel_ss"/>
                  </li>
                  <li>
                     <label>Product</label>
                     <span class="placeholder productservicelabel_ss"/>
                  </li>
                  <li>
                     <label>Country</label>
                     <span class="placeholder countrylabel_ss"/>
                  </li>
                  <li>
                     <label>Investment needed</label>
                     <span class="placeholder financingneeded_d123"/>
                  </li>
                  <li>
                     <label>Business stage</label>
                     <span class="placeholder stagebusinesslabel_s"/>
                  </li>
                  <li>
                     <label>Environmental Impact</label>
                     <span class="placeholder envimpactlabel_ss"/>
                  </li>
               </ul>
            </div>
            <div class="span6">
               <span class="placeholder companylogodoc_url"/>
            </div>
            <div class="span10">
               <div class="pull-right">
                  <span class="placeholder entityid_l"/>
               </div>
            </div>
         </div>
      </div>
   </td>
</tr>
<tr class="list entrepreneur-list" >
   <div class="pull-left">
      <?php _e ('Loading...', 'bidxplugin') ?>
   </div>
</tr>
    -->
</script>
<script type="text/html" id="investor-empty">
<!--
<tr class="match investor-match" >
    <div class="pull-left">
    <?php _e ('No matches available', 'bidxplugin') ?>
    </div>
</tr>
-->
</script>

<script type="text/html" id="entrepreneur-listitem">
    <!--
    <td colspan="5" class="detailRow">
    <div class="accordian-body collapse" id="table1-row1-col2">
    <div class="row-fluid">
    <div class="span12">
    <h4>Entrepreneur Profile</h4>
    <ul class="unstyled">
    <li>
    <label>Entrepreneur</label>
    <span class="placeholder ename"/>
    </li>
    <li>
    <label>Industry</label>
    <span class="placeholder eindustry"/>
    </li>
    <li>
    <label>Product</label>
    <span class="placeholder eproduct"/>
    </li>
    <li>
    <label>Country</label>
    <span class="placeholder ecountry"/>
    </li>
    <li>
    <label>Investment needed</label>
    <span class="placeholder eamount"/>
    </li>
    <li>
    <label>Business stage</label>
    <span class="placeholder estage"/>
    </li>
    <li>
    <label>Impact</label>
    <span class="placeholder eimpact"/>
    </li>
    </ul>
    </div>

    <div class="pull-right">
    <a href="#">View full profile</a>
    </div>
    </div>
    </div>
    </td>
    -->
</script>


