<div class="help details-block">
    <h1>Investor dashboard</h1>
    <div class="row-fluid">
        <div class="span8">Welcome to your new bidX group! You can always come here to:</div>
        <div class="span4"><input type="checkbox" class="startpage" <?php echo ($this->startingPage) ? 'checked':'';?> />&nbsp;Select as starting page</div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class='alert alert-success'>
                      <button data-dismiss='alert' class='close fui-cross' type='button'></button>
                      This is notificatin from Bidx !!
                    </div>
        </div>
        <div class="span4 offset6"><input type="checkbox"/>&nbsp;Don't show this message anymore</div>
    </div>



    <div class="row-fluid">
        <div class="span12">Congratulations! You are now a registered investor in the bidX platform. Get familiar with your new tools:</div>

    </div>
    <!-- 1. Preference -->
    <div class="row-fluid">
        <div class="span6"><label> Update your preferences anytime </label></div>
        <div class="span6"><div><a href="?page=groupsettings">Go to Group Settings</a> </div></div>

    </div>
    <div class="row-fluid">
        <div class="span12">
            If you want to update your preferences, you can easily do that from your dashboard. Specify different preferences to get new opportunities.
        </div>
    </div>

    <!-- 2. Keep up with new plans -->
    <div class="row-fluid">
        <div class="span6"><label> Keep up with new plans </label></div>
        <div class="span6"><div><a href="?page=groupsettings">Go to recommended plans</a> </div></div>

    </div>
    <div class="row-fluid">
        <div class="span12">
            bidX finds  your best suited plans as soon as these are published. We match your investor profile date with that of new businesses. The section Recommended plans in your dashboard lists the plans that could be interesting for you.
        </div>
    </div>

    <!-- 3. Get alerts in your inbox -->
    <div class="row-fluid">
        <div class="span6"><label>Get alerts in your inbox</label></div>
        <div class="span6"><div><a href="?page=groupsettings">Go to Inbox</a> </div></div>

    </div>
    <div class="row-fluid">
        <div class="span12">
            We will also send you weekly updates to your inbox. These messages contain the list of businesses that have been published during the last seven days.  If during your registration you accepted that we could send you emails to your personal inbox, you will receive those alerts there too. If you didn’t do so during your registration, but you would like to receive them now, you can change that setting at your Account Settings
        </div>
    </div>

    <!-- 4. One click, one contact -->
    <div class="row-fluid">
        <div class="span6"><label>One click, one contact</label></div>
        <div class="span6"><div><a href="?page=groupsettings">Go to  Contacts</a> </div></div>

    </div>
    <div class="row-fluid">
        <div class="span12">
            Invite other members to become your contacts and grow your own network. Click on the Contact link at the member profiles and an invitation to become a contact will be send to them.
        </div>
    </div>

    <!-- 5. Access to businesses full information   -->
    <div class="row-fluid">
        <div class="span6"><label> Access to businesses full information  </label></div>
        <div class="span6"><div><a href="?page=groupsettings">Go to contacted businesses</a> </div></div>

    </div>
    <div class="row-fluid">
        <div class="span12">
            If you see a business that you are interested about, you can request the entrepreneur to grant you access to view full data of the business. This will enclose full business and financial plan as well as the CV of the entrepreneur.  Click the link Request access that you will see on the business page. A message will be sent to the entrepreneur with your request. Plans you have requested access to will be listed in the section Contacted businesses in your dashboard
        </div>
    </div>

    <!-- 6. Contact your group moderator    -->
    <div class="row-fluid">
        <div class="span6"><label> Contact your group moderator  </label></div>
        <div class="span6"><div><a href="?page=groupsettings">Send message to group moderator</a> </div></div>

    </div>
    <div class="row-fluid">
        <div class="span12">
            For any additional questions over this group, functionalities, problems or suggestions, please contact your group moderator. He or she will be delighted to help you. If you encounter a problem with the platform, the group moderator will forward it to the bidX technical support.
        </div>
    </div>









</div>