<!-- 
	Search startpage.
	Single page application that is setup
 -->	
 <?php 
 $numFound = 0;
 if ( property_exists($this -> results, 'data') ) {
	 $docs = $this -> results -> data -> docs;
	 $numFound = $this -> results -> data -> numFound;
 }
 ?>
 <br /><br />
<div>
	<?php if ($numFound < 1 ) { ?>
	<div class="row-fluid">
		<div class="search alert">
			 <button type="button" class="close" data-dismiss="alert">&times;</button>
			 <h3>No results</h3>
			 <p>Your query did not have any results. Please retry with a more specific search term</p>
		</div>
	</div>	
	<?php } else { ?>
	<div class="row-fluid">
		<div class="span12"><h4>Search results (<?php echo $this -> results -> data -> numFound ?>)</h4></div>
	</div>
	
	<div class="row-fluid">
		<div class="search-result-container span8">
		
	<?php foreach ( $docs as $doc )  { 
		
		switch ($doc -> type) {

			case 'bidxMemberProfile':
				$fullname = $doc -> firstname_s . ' ' . $doc -> lastname_s;
		?>
			<div class="search-result-item well">
				<div class="row-fluid">
					<div class="span2">
						<div>
							<a href="/member/<?php echo $doc -> userId ?>">
						<?php if (property_exists( $doc , 'profilepicturedoc_url' ) ) {
							?>
								<img src="<?php echo $doc -> profilepicturedoc_url ?>" class="logo img-rounded" alt="<?php echo $fullname ?>"/>							
						<?php  } else { ?>
								<img data-src="holder.js/75x75/social/text:member" class="logo img-rounded" alt="<?php echo $fullname ?>"/>							
						<?php  }?>
							</a>
						</div>
					</div>
					<div class="span8">
						<div>
							<em><?php echo $fullname ?></em>
							<p><?php echo $doc -> professionaltitle_t ?></p>
							<p><?php echo $doc -> countrylabel_s ?></p>
						</div>
						<div>
							<span class="label">Member</span>
						</div>
					</div>
					<div class="span2">
						<a href="/member/<?php echo $doc -> userId ?>">view</a>
					</div>
				</div>
			</div>								
<?php	
			break;
			
			case 'bidxCompanyProfile':
?>
			<div class="search-result-item well">
				<div class="row-fluid">
					<div class="span2">
						<div>
							<img data-src="holder.js/75x75/social/text:company" class="logo img-rounded" alt=""/>							
						</div>
					</div>
					<div class="span8">
						<div>
							<em><?php echo $doc -> id ?></em>
						</div>
						<div>
							<span class="label">Company</span>
						</div>
					</div>
					<div class="span2">
						<a href="#">view</a>
					</div>
				</div>
			</div>
<?php 				
			break;

			case 'bidxInvestorProfile':
				$fullname = $doc -> firstname_s . ' ' . $doc -> lastname_s;
?>
			<div class="search-result-item well">
				<div class="row-fluid">
					<div class="span2">
						<div>
							<img data-src="holder.js/75x75/social/text:investor" class="logo img-rounded" alt=""/>							
						</div>
					</div>
					<div class="span8">
						<em><?php echo $fullname ?></em><br />
						<?php echo $doc -> summary_t ?><br />
						<?php echo $doc -> countrylabel_s ?>, <?php echo $doc -> city_s ?><br />
						<span class="label">Investor</span>
					</div>
					<div class="span2">
						<a href="#">view</a>
					</div>
				</div>
			</div>
<?php 				
			break;			

			case 'bidxEntrepreneurProfile':
				$fullname = $doc -> firstname_s . ' ' . $doc -> lastname_s;
?>
			<div class="search-result-item well">
				<div class="row-fluid">
					<div class="span2">
						<div>
 							<a href="/member/<?php echo $doc -> userId ?>?#showEntrepreneur">
						<?php if (property_exists( $doc , 'profilePicturedoc_url' ) ) {
								$items = explode( '/', $doc -> profilePicturedoc_url );
								$imageUrl = '/dl/document/' . $items[2] . '/' . $items[3] ;
							?>
								<img src="<?php echo $imageUrl ?>" class="logo img-rounded" alt="<?php echo $fullname ?>"/>							
						<?php  } else { ?>
								<img data-src="holder.js/75x75/social/text:member" class="logo img-rounded" alt="<?php echo $fullname ?>"/>							
						<?php  }?>
							</a>
						</div>
					</div>
					<div class="span8">
						<div>
							<em><?php echo $fullname ?></em><br />
							<?php echo $doc -> professionaltitle_t ?><br />
							<?php echo $doc -> countrylabel_s ?>, <?php echo $doc -> city_s ?><br />							
							<span class="label">Entrepreneur</span>
						</div>
					</div>
					<div class="span2">
						<a href="/member/<?php echo $doc -> userId ?>?#showEntrepreneur">view</a>
					</div>
				</div>
			</div>
<?php 				
			break;
			
			case 'bidxBusinessSummary':
?>
			<div class="search-result-item well">
				<div class="row-fluid">
					<div class="span2">
						<div>
							<a href="/business/<?php echo $doc -> userId ?>">
						<?php if (property_exists( $doc , 'picturedoc_url' ) ) {
								$items = explode( '/', $doc -> 	picturedoc_url );
								$imageUrl = '/dl/document/' . $items[2] . '/' . $items[3] ;
							?>
								<img src="<?php echo $imageUrl ?>" class="logo img-rounded" alt="<?php echo $fullname ?>"/>							
						<?php  } else { ?>
								<img data-src="holder.js/75x75/social/text:business" class="logo img-rounded" alt="<?php echo $fullname ?>"/>							
						<?php  }?>
							</a>						
						</div>
					</div>
					<div class="span8">
						<div>
							<em><?php echo $doc -> name_s ?></em><br />
							<?php echo $doc -> slogan_s ?><br/>
							<?php echo $doc -> industrylabel_ss ?>, <?php echo $doc -> countrylabel_s ?><br />
							<span class="label">Business</span>
						</div>
					</div>
					<div class="span2">
						<a href="/business/<?php echo $doc -> userId ?>">view</a>
					</div>
				</div>
			</div>
<?php 				
			break;			
		} 
	} ?>
			<div>					
<?php 	
	if ( property_exists( $this, 'previousLink' ) ) {
	?>
	<a href="?<?php echo $this -> previousLink ?>" class="btn">Previous</a>
	<?php
	}
	if ( property_exists( $this, 'nextLink' ) ) {
	?>
	<a href="?<?php echo $this -> nextLink ?>" class="btn">Next</a>
	<?php	
	}	
?>	
			</div>					
		</div>
<?php } ?>
	
		<div class="sidebar span4">
			<div>
			
			</div>
			<div>
			<ul class="nav nav-list">
	            <li class="nav-header">Filters</li>
	            <li>
	              <a href="#fakelink">
	                UX Design
	                <span class="nav-counter">19</span>
	              </a>
	            </li>
	            <li class="active">
	              <a href="#fakelink">
	                Photography
	                <span class="nav-counter">130</span>
	              </a>
	            </li>
	            <li>
	              <a href="#fakelink">
	                Art
	                <span class="nav-counter">9</span>
	              </a>
	            </li>
	            <li class="divider"></li>
	            <li class="nav-header">Condition</li>
	            <li>
	              <a href="#fakelink">
	                Brand new
	                <span class="nav-counter">69</span>
	              </a>
	            </li>
	            <li>
	              <a href="#fakelink">
	                Read-used
	                <span class="nav-counter">21</span>
	              </a>
	            </li>
	            <li>
	              <a href="#fakelink">
	                Work-used
	                <span class="nav-counter">40</span>
	              </a>
	            </li>
	          </ul>
			</div>
		
			<!--
			<div class="facetnavigation row-fluid">
				<div>
					Search in:
					<div class="btn-group" data-toggle="buttons-radio">
					  <button class="btn" name="selection" value="1">This Group</button>
					  <button class="btn" name="selection" value="2">All My Groups</button>
					  <button class="btn" name="selection" value="3">All Groups</button>
					</div>
				</div>
				<div>
					Filter results on:
				</div>
				<div class="accordion" id="accordion2">
					<div class="accordion-group">
						<div class="accordion-heading">
							<a class="accordion-toggle" data-toggle="collapse"
								data-parent="#accordion2" href="#collapseOne"> People </a>
						</div>
						<div id="collapseOne" class="accordion-body collapse">
							<div class="accordion-inner">
								<h4>Filter on role</h4>
								<label class="checkbox"> 
									<input type="checkbox" value="Member-only" /> Member only
								</label> 
								<label class="checkbox"> 
									<input type="checkbox" value="Entrepreneur" /> Entrepreneur
								</label> 
								<label class="checkbox"> 
									<input type="checkbox" value="Investor" /> Investor
								</label> 
								<h4>Filter on text</h4>
								<input type="text" placeholder="Location" class="form-search" /> 
								<input type="text" placeholder="Language" class="form-search" /> 
								<input type="text" placeholder="Industry" class="form-search" /> 
								<input type="text" placeholder="Theme" class="form-search" />
							</div>
						</div>
					</div>
					<div class="accordion-group">
						<div class="accordion-heading">
							<a class="accordion-toggle" data-toggle="collapse"
								data-parent="#accordion2" href="#collapseTwo"> Business </a>
						</div>
						<div id="collapseTwo" class="accordion-body collapse">
							<div class="accordion-inner">Anim pariatur cliche...</div>
						</div>
					</div>
					<div class="accordion-group">
						<div class="accordion-heading">
							<a class="accordion-toggle" data-toggle="collapse"
								data-parent="#accordion3" href="#collapseThree"> Group </a>
						</div>
						<div id="collapseThree" class="accordion-body collapse">
							<div class="accordion-inner">Anim pariatur cliche...</div>
						</div>
					</div>
				</div>
			</div>
 			 -->	
		</div>
	</div>
</div>