<!-- 
	Search startpage.
	Single page application that is setup
 -->	
 <?php 
 $numFound = 0;
 if ( property_exists($this -> results, 'data') ) {
	 $docs = $this -> results -> data -> docs;
	 $numFound = $this -> results -> data -> numFound;
 }
 ?>
 <br /><br />
<div>
	<?php if ($numFound < 1 ) { ?>
	<div class="row-fluid">
		<div class="search alert">
			 <button type="button" class="close" data-dismiss="alert">&times;</button>
			 <h3>No results</h3>
			 <p>Your query did not have any results. Please retry with a more specific search term</p>
		</div>
	</div>	
	<?php } else { ?>
	<div class="row-fluid">
		<div class="span12"><h4>Search results (<?php echo $this -> results -> data -> numFound ?>)</h4></div>
	</div>
	
	<div class="row-fluid">
		<div class="span8">
		<table class="table table-striped">
			<tbody>
				<tr>
					<th>Type</th>
					<th>Image</th>
					<th>Description</th>
					<th></th>
				</tr>
	<?php foreach ( $docs as $doc )  { 
		
		switch ($doc -> type) {

			case 'bidxMemberProfile':
				$fullname = $doc -> firstname_s . ' ' . $doc -> lastname_s;
		?>
			<tr>
				<td>
					<span class="label">Member</span>
				</td>
				<td>
					<a href="/member/<?php echo $doc -> userId ?>">
						<?php if (property_exists( $doc , 'profilepicturedoc_url' ) ) {
							?>
								<img src="<?php echo $doc -> profilepicturedoc_url ?>" class="logo img-rounded" alt="<?php echo $fullname ?>"/>							
						<?php  } else { ?>
								<img data-src="holder.js/75x75/social/text:member" class="logo img-rounded" alt="<?php echo $fullname ?>"/>							
						<?php  }?>
					</a>
				</td>
				<td>
					<em><?php echo $fullname ?></em>
					<p><?php echo $doc -> professionaltitle_t ?></p>
					<p><?php echo $doc -> countrylabel_s ?></p>
					
				</td>
				<td>
					<a class="fui-arrow-right" href="/member/<?php echo $doc -> userId ?>">view</a>
				</td>
			</tr>								
<?php	
			break;
			
			case 'bidxCompanyProfile':
?>
			<tr>
				<td>
					<span class="label">Company</span>
				</td>
				<td>
					<img data-src="holder.js/75x75/social/text:company" class="logo img-rounded" alt=""/>							
				</td>
				<td>
					<em><?php echo $doc -> id ?></em>		
				</td>
				<td>
					<a href="#">view</a>
				</td>
			</tr>
<?php 				
			break;

			case 'bidxInvestorProfile':
				$fullname = $doc -> firstname_s . ' ' . $doc -> lastname_s;
?>
			<tr>
				<td>
					<span class="label">Investor</span>
				</td>
				<td>
					<img data-src="holder.js/75x75/social/text:investor" class="logo img-rounded" alt=""/>							
				</td>
				<td>
					<em><?php echo $fullname ?></em><br />
					<?php echo $doc -> summary_t ?><br />
					<?php echo $doc -> countrylabel_s ?>, <?php echo $doc -> city_s ?><br />
					
				</td>
				<td>
					<a href="/investor/<?php echo $doc -> userId ?>">view</a>
				</td>
			</tr>
<?php 				
			break;			

			case 'bidxEntrepreneurProfile':
				$fullname = $doc -> firstname_s . ' ' . $doc -> lastname_s;
?>
			<tr>
				<td>
					<span class="label">Entrepreneur</span>
				</td>
				<td>
 					<a href="/member/<?php echo $doc -> userId ?>?#showEntrepreneur">
						<?php if (property_exists( $doc , 'profilePicturedoc_url' ) ) {
								$items = explode( '/', $doc -> profilePicturedoc_url );
								$imageUrl = '/dl/document/' . $items[2] . '/' . $items[3] ;
							?>
								<img src="<?php echo $imageUrl ?>" class="logo img-rounded" alt="<?php echo $fullname ?>"/>							
						<?php  } else { ?>
								<img data-src="holder.js/75x75/social/text:member" class="logo img-rounded" alt="<?php echo $fullname ?>"/>							
						<?php  }?>
							</a>
				</td>
				<td>
					<em><?php echo $fullname ?></em><br />
					<?php echo $doc -> professionaltitle_t ?><br />
					<?php echo $doc -> countrylabel_s ?>, <?php echo $doc -> city_s ?><br />							
					
				</td>
				<td>
					<a href="/member/<?php echo $doc -> userId ?>?#showEntrepreneur">view</a>
				</td>
			</tr>
<?php 				
			break;
			
			case 'bidxBusinessSummary':
?>
			<tr>
				<td>
					<span class="label">Business</span>
				</td>
				<td>
					<a href="/business/<?php echo $doc -> userId ?>">
						<?php if (property_exists( $doc , 'picturedoc_url' ) ) {
								$items = explode( '/', $doc -> 	picturedoc_url );
								$imageUrl = '/dl/document/' . $items[2] . '/' . $items[3] ;
							?>
								<img src="<?php echo $imageUrl ?>" class="logo img-rounded" alt="<?php echo $fullname ?>"/>							
						<?php  } else { ?>
								<img data-src="holder.js/75x75/social/text:business" class="logo img-rounded" alt="<?php echo $fullname ?>"/>							
						<?php  }?>
							</a>						
				</td>
				<td>
					<em><?php echo $doc -> name_s ?></em><br />
					<?php echo $doc -> slogan_s ?><br/>
					<?php echo $doc -> industrylabel_ss ?>, <?php echo $doc -> countrylabel_s ?><br />
				</td>
				<td>
					<a href="/business/<?php echo $doc -> userId ?>">view</a>
				</td>
			</tr>
<?php 				
			break;			
		} 
	} ?>
		</tbody>
	</table>					
<?php 	
	if ( property_exists( $this, 'previousLink' ) ) {
	?>
	<a href="?<?php echo $this -> previousLink ?>" class="btn">Previous</a>
	<?php
	}
	if ( property_exists( $this, 'nextLink' ) ) {
	?>
	<a href="?<?php echo $this -> nextLink ?>" class="btn">Next</a>
	<?php	
	}	
?>						
		</div>
<?php } ?>
	
		<div class="sidebar span4">
			<div>
			
			</div>
			<div>
			<ul class="nav nav-list">
	            <li class="nav-header">Filters</li>
	            <li>
	              <a href="#fakelink">
	                UX Design
	                <span class="nav-counter">19</span>
	              </a>
	            </li>
	            <li class="active">
	              <a href="#fakelink">
	                Photography
	                <span class="nav-counter">130</span>
	              </a>
	            </li>
	            <li>
	              <a href="#fakelink">
	                Art
	                <span class="nav-counter">9</span>
	              </a>
	            </li>
	            <li class="divider"></li>
	            <li class="nav-header">Condition</li>
	            <li>
	              <a href="#fakelink">
	                Brand new
	                <span class="nav-counter">69</span>
	              </a>
	            </li>
	            <li>
	              <a href="#fakelink">
	                Read-used
	                <span class="nav-counter">21</span>
	              </a>
	            </li>
	            <li>
	              <a href="#fakelink">
	                Work-used
	                <span class="nav-counter">40</span>
	              </a>
	            </li>
	          </ul>
			</div>
		</div>

	