<?php

    // check if there is a contenttitle (Which would have been set in the shortcode tag). If not revert to standard text
    //
    if ( isset( $this -> contenttitle ) && $this -> contenttitle != '' ){

      //  $title = $this -> contenttitle; // Temparary PM-321 solution
       $title = "<h1>".__('Register as a member','bidxplugin')."</h1>";
    } else {

        $title = __('Become a member','bidxplugin');
    }

        $groupNotification = (isset($this->groupNotification) && $this->groupNotification) ? $this->groupNotification : NULL;


 ?>
<div id="register" class="block-odd mainState mainStateRegister">
    <form id="frmRegister" action="/">

        <h1><?php _e($title, 'bidxplugin' ); ?></h1>
        <div class="form-group">
            <label><?php _e('First name','bidxplugin');?></label>
            <input type="text" class="form-control" name="personalDetails.firstName" placeholder="<?php _e('Enter your first name','bidxplugin');?>" />
        </div>

        <div class="form-group">
            <label><?php _e('Last name','bidxplugin');?></label>
            <input type="text" class="form-control" name="personalDetails.lastName" placeholder="<?php _e('Enter your last name','bidxplugin');?>" />
        </div>

        <div class="form-group">
            <label><?php _e('Email address','bidxplugin');?></label>
            <input type="text" class="form-control" name="username" placeholder="<?php _e('Enter your email address','bidxplugin');?>" />
        </div>

        <div class="form-group">
            <label><?php _e('What is your country?','bidxplugin');?></label>
            <select name="personalDetails.address.country"></select>
        </div>

        <div class="form-group">
            <label><?php _e('What is your city?','bidxplugin');?></label>
            <input type="text" class="form-control" name="personalDetails.address.cityTown" placeholder="<?php _e('Enter your city','bidxplugin');?>" />
        </div>

        <div class="form-group checkbox" style="display: inline;">
            <input type="checkbox" value="" id="checkbox-acceptTerms" name="acceptTerms" />
            <label for="checkbox-acceptTerms"><span></span><?php _e( 'I accept the bidX', 'bidxplugin' )?></label>
        </div>
        <?php printf( __( '<a href="%s" target="_blank"> Terms of Service </a>', 'bidxplugin'), "/terms-of-service" ); ?>

        <div class="form-group checkbox" style="display: inline-block;">
            <input type="checkbox" value="" id="checkbox-preventSpam" name="preventSpam" />
            <label for="checkbox-preventSpam"><span></span><?php _e( 'Please check this to help us prevent spam', 'bidxplugin' )?></label>
        </div>
        <br>
        <button type="submit" class="btn btn-primary" style="display: block;"><?php _e('Register','bidxplugin');?></button>

        <?php if( isset($this->showLoginLink) && $this->showLoginLink) { ?>
        <p>
            <?php _e('Forgot your password? Click <a href="#auth/resetpassword">here</a> to recover.','bidxplugin');?><br/>
            <?php _e('Login? Click <a href="/auth/#auth/login">here</a> to go to login.','bidxplugin');?>
        </p>
        <?php } ?>
        <input type="hidden" name="urlparam" value="<?php  echo base64_encode('groupname='.$groupNotification);?>">
    </form>

    <div class="registerSuccess hide">
        <h3><?php _e('Registration complete','bidxplugin');?></h3>
        <p><?php _e('The registration is complete. An email has been sent to your email address with follow-up instructions','bidxplugin');?></p>
        <p><?php printf( __('Click <a href="%s">here</a> to go to the group homepage.', 'bidxplugin'), "/"  ); ?></p>
    </div>
</div>
