<?php

    // check if there is a contenttitle (Which would have been set in the shortcode tag). If not revert to standard text
    //
    if ( isset( $this -> contenttitle ) && $this -> contenttitle != '' ){

        $title = $this -> contenttitle;
    } else {

        $title = 'Become a member';
    }

 ?>
<div id="register" class="block-odd mainState mainStateRegister">
    <form id="frmRegister" action="/">

        <h1><?php _e($title, 'bidxplugin' ); ?></h1>
        <div class="row-fluid">
            <div class="span12">
                <div class="control-group">
                    <label class="control-label"><?php _e('First name','bidxplugin');?></label>
                    <div class="controls">
                        <input type="text" name="personalDetails.firstName" placeholder="<?php _e('Enter your first name','bidxplugin');?>" />
                    </div>
                </div>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span12">
                <div class="control-group">
                    <label class="control-label"><?php _e('Last name','bidxplugin');?></label>
                    <div class="controls">
                        <input type="text" name="personalDetails.lastName" placeholder="<?php _e('Enter your last name','bidxplugin');?>" />
                    </div>
                </div>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span12">
                <div class="control-group">
                    <label class="control-label"><?php _e('Email address','bidxplugin');?></label>
                    <div class="controls">
                        <input type="text" name="username" placeholder="<?php _e('Enter your email address','bidxplugin');?>" />
                    </div>
                </div>
            </div>
        </div>

        <div class="row-fluid">
            <div class="span12">
                <div class="control-group">
                    <label class="control-label"><?php _e('What is your location?','bidxplugin');?></label>
                    <div class="controls">
                        <input type="text" name="location" placeholder="<?php _e('Please enter your location','bidxplugin');?>" data-type="location" />
                    </div>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <div class="control-group">
                    <label class="checkbox">
                        <input type="checkbox" value="" name="acceptTerms" data-toggle="checkbox" /><?php _e( 'I accept the bidX', 'bidxplugin' )?>
                    </label>
                    <?php printf( __( '<a href="%s">Terms & Conditions </a>', 'bidxplugin'), "/termsandconditions" ); ?>
                </div>
            </div>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <label class="checkbox">
                    <input type="checkbox" value="" name="preventSpam" data-toggle="checkbox" /> <?php _e( 'Please check this to help us prevent spam', 'bidxplugin' )?>
                </label>
            </div>
        </div>

        <div class="buttonwrapper">
            <button type="submit" class="btn btn-primary bidx-theme-colour-two"><?php _e('Register','bidxplugin');?></button>
        </div>
        <?php if($this->showLoginLink) { ?>
        <p>
            <?php _e('Forgot your password? Click <a href="#auth/resetpassword">here</a> to recover.','bidxplugin');?><br/>
            <?php _e('Login? Click <a href="/auth/#auth/login">here</a> to go to login.','bidxplugin');?>
        </p>
        <?php } ?>
        <input type="hidden" name="urlparam" value="<?php  echo base64_encode('groupname='.$this->groupNotification);?>">
    </form>

    <div class="registerSuccess hide">
        <h3><?php _e('Registration complete','bidxplugin');?></h3>
        <p><?php _e('The registration is complete. An email has been sent to your email address with follow-up instructions','bidxplugin');?></p>
        <p><?php printf( __('Click <a href="%s">here</a> to go to the group homepage.', 'bidxplugin'), "/"  ); ?></p>
    </div>
</div>
