<div class="view viewShow top-margin-lineheight bottom-margin-lineheight">
	<div class="row container">
		<div class="col-md-4">
			<img src="/wp-content/plugins/bidx-plugin/apps/expressform/<?php echo $this->expressCustom; ?>static/img/telaviv.png" alt="Cover Image"  width="100%" height="100%" />
		</div>
		<div class="col-md-8">
			<h1 class="text-primary-dark expressTitle"><?php _e('Telaviv', 'bidxplugin');?> </h1>
			<h3 class="text-copy"><?php _e("We believe in the transformative power of values-driven innovation to improve the lives of people all over the world.<br/><br/>

Apply with Pears Program for Global Innovation<br>With Pears Program for Global Innovation you can receive:
<ul>
	<li>free mentoring (accounting, marketing, legal, etc.)</li>
	<li>Access to loans & equity finance</li>
	<li>Get media exposure</li>
	<li>Access a network of other innovative businesses (earsprogram.com)</li>
	<li>Get support from us</li></ul><br/>
Join Pears Program Today! ", "bidxplugin");?>
			</h3>
			<a class="btn btn-primary btn-lg center btn-block active btn-participate pull-right" href="#createExpressForm"><?php _e('Participate now','bidxplugin');?> </a>
		</div>
	</div>
</div>