<div class="view viewThankyou top-margin-lineheight bottom-margin-lineheight">
	<div class="row container">
		<div class="col-md-4 hide">
			<img src="/wp-content/plugins/bidx-plugin/apps/expressform/<?php echo $this->expressCustom; ?>static/img/telaviv.png" alt="Cover Image"  width="100%" height="100%" />
		</div>
		<div class="col-md-12">
			<h1 class="text-primary-dark expressTitle"><?php _e('Thank you', 'bidxplugin');?> </h1>
			<h3 class="text-copy"><?php _e("You have succesfully applied for the Telaviv community. Please check your inbox to verify your account, Once you verify your account you are entitled to the get following benefits.<br/><br/>

With Pears Program for Global Innovation you can receive:
<ul>
	<li>Free mentoring (accounting, marketing, legal, etc.)</li>
	<li>Access to loans & equity finance</li>
	<li>Get media exposure</li>
	<li>Access a network of other innovative businesses (earsprogram.com)</li>
	<li>Get support from us</li></ul><br/>", "bidxplugin");?>
			</h3>
			<a class="btn btn-primary btn-lg center btn-block active btn-participate pull-right" href="http://www.pearsprogram.com/#!contact-us/clm2"><?php _e('Contact us','bidxplugin');?> </a>
		</div>
	</div>
</div>