<?php
    $images = array();

    // get images associated with this post
    //
    $images = get_attached_media( 'image', get_the_ID() );

    if ( count( $images ) > 0 ) {
?>
    <!-- IMAGE Carousel -->
    <div class="container">
        <div id="groupCarousel" class="carousel slide">
<?php
            // If there is only 1 image in the array don't show the nav arrows and the indicator
            // TODO: Don't load the carousel plugin and the extra markup
            if ( count($images) != 1 ) {
?>
                <ol class="carousel-indicators">
<?php
                    $count = 0;
                    foreach ( $images as $id => $image ) {
?>
                        <li data-target="#groupCarousel" data-slide-to="<?php echo $count ?>" <?php if ($count == 0) { ?>class="active" <?php } $count++; ?> ></li>
<?php
                    }
?>
                </ol>
<?php
            }
?>
            <!-- Carousel items -->
            <div class="carousel-inner img-rounded">
<?php
            $count = 0;
            foreach ( $images as $id => $image ) {
                $img = wp_get_attachment_image_src( $image->ID, 400 );
                //parse URL to ensure having only relative links
                $img_url = parse_url($img[0]);
?>
                <div class="item <?php if ($count == 0) { ?>active<?php } $count++; ?>">
                    <img class="img" src="<?php echo $img_url['path'] ?>" />
<?php
                    if ( !empty( $image -> post_content ) ) {
?>
                    <div class="container">
                        <div class="carousel-caption img-rounded"><?php echo $image -> post_content ?></div>
                    </div>
<?php
                    } // !empty( $image  -> post_content )
?>
                </div>
<?php
            } // foreach
?>
            </div>
<?php
            // If there is only 1 image in the array don't show the nav arrows and the indicator
            // TODO: Don't load the carousel plugin and the extra markup
            if ( count($images) != 1 ) {
?>

            <!-- Carousel nav -->
            <a class="left carousel-control img-rounded" href="#groupCarousel" data-slide="prev"><span class="fa fa-chevron-left"></span></a>
            <a class="right carousel-control img-rounded" href="#groupCarousel" data-slide="next"><span class="fa fa-chevron-right"></span></a>
<?php
            }
?>
        </div>
    </div>
    <!-- // IMAGE Carousel -->
<?php

    }  else {
?>
<div class="container">
    <div class="alert alert-danger">
        <?php _e('Please add images using the mediamanager for this page in the Wordpress Admin', 'bidxtheme') ?>
    </div>
</div>
<?php
    }
?>




