
<?php
wp_enqueue_script ('bidx-form');
?>
<div id="auth" class="block-odd mainState mainStateAuth">
    <div class="container">

        <section>

            <!-- LOGIN -->
            <article class="view viewLogin ">
                <div class="row-fluid">
                    <div class="span6 offset3 bidx-well bidx-theme-colour-panel-one">
                        <?php echo do_shortcode( '[bidx app="login"]' );?>
                    </div>
                </div>
            </article>

            <!-- FORGOT PASSWORD -->
            <article class="view viewResetpassword">
                <div class="row-fluid">
                    <div class="span6 offset3 bidx-well bidx-theme-colour-panel-one">
                        <?php echo do_shortcode( '[bidx app="resetpassword"]' );?>
                    </div>
                </div>
            </article>

            <!-- REGISTER -->
            <article  class="view viewRegister">
                <div class="row-fluid">
                    <div class="span6 offset3 bidx-well bidx-theme-colour-panel-one">
                        <?php echo do_shortcode( '[bidx app="register"]' );?>
                    </div>
                </div>
            </article>

        </section>
    </div>
</div>