<div id="auth" class="block-odd mainState mainStateAuth">
    <div class="container">

        <section>

            <!-- LOGIN -->
            <article class="view viewLogin viewInitial">
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3 well bidx-theme-colour-panel-one">
                        <?php echo do_shortcode( '[bidx app="login"]' );?>
                    </div>
                </div>
            </article>

            <!-- FORGOT PASSWORD -->
            <article class="view viewResetpassword">
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3 well bidx-theme-colour-panel-one">
                        <?php echo do_shortcode( '[bidx app="resetpassword"]' );?>
                    </div>
                </div>
            </article>

            <!-- REGISTER -->
            <article  class="view viewRegister">
                <div class="row">
                    <div class="col-sm-6 col-sm-offset-3 well bidx-theme-colour-panel-one">
                        <?php echo do_shortcode( '[bidx app="register"]' );?>
                    </div>
                </div>
            </article>

        </section>
    </div>
</div>
