<?php


?>

<form action="/wp-login.php" method="post">
	<div class="formfield" data-validation='{"required":{"text":"<?php _e('This field is mandatory','i18n');?>"},"typecheck":[{"email":{"text":"<?php _e('This is not a valid e-mail address','i18n');?>"}}]}'>
		<label><?php _e('Email address','bidxplugin');?></label>
		<input type="text" name="log" placeholder="<?php _e('Type your email address','bidxplugin');?>" />
	</div>

	<div class="buttonwrapper">
		<a href="#" class="button primary jsForget"><?php _e('Send me a new password','bidxplugin');?></a>

	</div>
	<p>
		<?php _e('Did you remember your password again?','bidxplugin');?> <br><?php _e('Click <a href="/forgot-password">here</a> to recover.','bidxplugin');?><br/>

	</p>

		<!-- <input type="button" name="wp-submit"  value="Log In" /> -->
		<input type="hidden" name="redirect_to" value="[!Q!]" />
		<input type="hidden" name="testcookie" value="1" />
</form>
<script type="text/javascript">
	$(function(){
		$("form").form({
			callToAction : '.jsForget',
			errorClass : 'error',
			url : '/wp-admin/admin-ajax.php?action=bidx_signin'
		});
	});
</script>
