<?php
if ( is_user_logged_in() ) {
?>
<div class="signup span4 well">
	<h3><?php _e('Not available!','bidxplugin');?></h3>
	<a href="<?php echo wp_logout_url( get_permalink() ); ?>" title="Logout"><?php _e('Logout','bidxplugin');?></a> <?php _e('to use','bidxplugin');?>
</div>
<?php 
} else {
?>
<div class="signup span4 well">

	<form class="fieldset">
		<div class="formfield huge" data-validation='{"required":{"text":"<?php _e('This field is mandatory','i18n');?>"},"typecheck":[{"custom":{"url":"/wp-admin/admin-ajax.php?action=bidx_request","apiurl":"groups/validateGroupName","apimethod":"get"}}]}'>
			<input type="text" name="groupName" placeholder="<?php _e('Your group name','bidxplugin');?>" class="highlight" value="">
		</div>
		<div class="formfield huge" data-validation='{"required":{"text":"<?php _e('This fields is mandatory','i18n');?>"},"typecheck":[{"email":{"text":"<?php _e('This is not a valid e-mail address','i18n');?>"}},{"custom":{"url":"/wp-admin/admin-ajax.php?action=bidx_request","apiurl":"members/validateUsername","apimethod":"get"}}]}'>
			<input type="email" name="username" placeholder="<?php _e('Your email address','bidxplugin');?>">
		</div>
		<div class="formfield huge" data-validation='{"required":{"text":"<?php _e('This fields is mandatory','i18n');?>"}}'>
			<input type="password" name="password" placeholder="<?php _e('Your password','bidxplugin');?>">
		</div>
		<a href="#" class="btn btn-success jsCreateGroup"><?php _e('Create your group','bidxplugin');?></a>
	</form>
	
	<div class="group-creation-progress">
		<p class="lead"><?php _e('Your group is being created','bidxplugin');?></p>
		<div class="loader"></div>
		<p><?php _e('This might take a moment of your time','bidxplugin');?></p>
	</div>

	<!-- externalize this -->
	<script type="text/javascript">
    	$(function(){
    		/*
    			if handler sends back response it can include the following json:
    			{
					status: 'OK',
					redirect:'<URL to redirect too>'
				},
				{ //not yet implemented
					status: 'ERROR',
					fields: [{field:fieldname,error:errormessage}[,]]
				}
    		*/

    		$(".fieldset").form({
    			callToAction : '.jsCreateGroup', // the selector for submit button
    			errorClass : 'error', //the css class used as error message
    			url : '/wp-admin/admin-ajax.php?action=bidx_request',
    			apiurl : 'groups',
    			apimethod : 'post',
    			beforeSubmit : function(){
						var $this=$(".fieldset");
			    		$this.fadeOut("fast", function(){
			    			$(".group-creation-progress").fadeIn('fast');
			    		});
	    			},
	    			//custom error message for frontend registration in case group creation fails
	    			error: function(data){
	    				$(".group-creation-progress").html("<div class=\"text sub\"><?php _e('Group creation failed. Please reload the page and try again.<br/> If the problem persists, please contact us.','bidxplugin');?>");
	    				if(data.text) {
	    					$(".group-creation-progress").append(data.text);
	    				}
	    			}
	    			
	    		});

	    		(function() {
	    			/*custom event to fix field positioning when validation kicks in*/
	    			var fs = $(".fieldset");

	    			var startMargin = parseInt(fs.css("margin-top").replace("px",""));
 					//when change occurs count error messages for this fieldset an calculate margin correction
		    		$(".fieldset :input").change(correctMargins);
		    		$(".jsCreateGroup").click(correctMargins);
	    			function correctMargins() {
	    				var removeMargin = 0;
		    			//exclude

						var fields = fs.find(":input").map(function(){
		    				return $(this).attr("name")}).each(function(i,name){
		    					var match = JSON.stringify($(".fieldset").form("getElement",name).validation).match(/"error":true/g);
		    					if(match != null)
		    						removeMargin += 10;
		    				});
	    					fs.animate({
								"margin-top":startMargin-removeMargin
									}, 'fast');
				    			}

					})();
			});
    </script>
</div>
<?php 
}
?>
