<?php
?>
<style>
	input, select, textarea {
		width:				100%;
	}

	textarea {
		line-height:		24px;
		padding-top:		10px;
		padding-right:		10px;
	}
</style>
<div id="groupRegistration" class="mainState mainStateShow">
	<form  name="registration">
		<?php
			//generate hiddenfields. REMARK: we might not want to print all values here!!
			foreach ( $_POST as $key => $value ) {
				 echo  "<input type='hidden' name='" . $key . "' value='" . $value . "'>" ;
			}
		 ?>

		<div class="row-fluid">

			<div class="span4 well">

				<div class="row-fluid">

					<div class="span11">


						<h3><?php _e('Complete your profile','bidxplugin');?></h3>

		                <div class="control-group">
		                    <label class="control-label"><?php _e('First name','bidxplugin'); ?></label>
		                    <div class="controls">
		                        <input type="text" name="personalDetails.firstName" placeholder="<?php _e('Please enter your first name','bidxplugin'); ?>">
		                    </div>
		                </div>

		                <div class="control-group">
		                    <label class="control-label"><?php _e('Last name','bidxplugin'); ?></label>
		                    <div class="controls">
		                        <input type="text" name="personalDetails.lastName" placeholder="<?php _e('Please enter your last name','bidxplugin'); ?>">
		                    </div>
		                </div>

		                <div class="control-group">
		                    <label class="control-label"><?php _e('E-mail','bidxplugin'); ?></label>
		                    <div class="controls">
		                        <input type="text" name="personalDetails.emailAddress" value="<?php echo isset( $_POST["username"] ) ?  $_POST["username"]: ""; ?>"/>
		                    </div>
		                </div>

		                <div class="control-group">
		                    <label class="control-label"><?php _e('What is your location?','bidxplugin');?></label>
		                    <div class="controls">
		                        <input type="text" name="personalDetails.address" placeholder="<?php _e('Please enter your location','bidxplugin');?>" data-type="location" data-type-arguments=''/>
		                    </div>
		                </div>
					</div>
				</div>
			</div>

			<div class="span8 well">

				<h3><?php _e('About your group','bidxplugin');?></h3>

 				<div class="control-group">
                    <label class="control-label"><?php _e('Group Name','bidxplugin');?></label>
                    <div class="controls">
                    	<input type="text" name="businessGroupName" readonly="readonly" placeholder="<?php _e('Please enter your group name','bidxplugin');?>" value="<?php echo isset( $_POST["groupName"] ) ?  $_POST["groupName"]: ""; ?>"/>
                    </div>
                </div>

	            <div class="control-group">
                    <label class="control-label"><?php _e('Define your group (max. 140 characters)','bidxplugin');?></label>
                    <div class="controls">
                       <textarea name="slogan" maxlength="140" placeholder="<?php _e('Define your group','bidxplugin');?>"></textarea>
                    </div>
                </div>

	            <div class="control-group">
                    <label class="control-label"><?php _e('Short description','bidxplugin');?></label>
                    <div class="controls">
						<textarea name="description" placeholder="<?php _e('Please provide a short description','bidxplugin');?>"></textarea>
                    </div>
                </div>

	            <div class="control-group">
                    <label class="control-label"><?php _e('Company','bidxplugin');?></label>
                    <div class="controls">
						<input type="text" name="company" placeholder="<?php _e('Please enter your company name','bidxplugin');?>" />
                    </div>
                </div>

	            <div class="control-group">
                    <label class="control-label"><?php _e('Website','bidxplugin');?></label>
                    <div class="controls">
						<input type="text" name="website"  placeholder="<?php _e('Please fill in your website address','bidxplugin');?>" />
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label"><?php _e('Industry','bidxplugin'); ?></label>
                     <div class="controls">
                    	<select name="focusIndustry" multiple></select>
                    </div>
                </div>


				<div class="control-group">
					<label class="control-label"><?php _e('Roles','bidxplugin');?></label>
					<div class="controls">
						<select name="role">
							<option value=""><?php _e('Which member roles does your group focus on','bidxplugin');?></option>
							<option value="investors"><?php _e('Investors','bidxplugin');?></option>
							<option value="entrepreneurs"><?php _e('Entrepreneurs','bidxplugin');?></option>
						</select>
					</div>
				</div>

                <div class="control-group">
                    <label class="control-label"><?php _e('Social impact','bidxplugin'); ?></label>
					<div class="controls">
	                    <select name="focusSocialImpact" multiple></select>
	                </div>
                </div>

                <div>
                	<label><?php _e('Location','bidxplugin'); ?></label>

                    <label class="radio">
                    	<input type="radio" data-toggle="radio" name="focusLocationType" value="country"><?php _e('Country / Countries','bidxplugin'); ?>
                    </label>
                    <label class="radio">
                    	<input type="radio" data-toggle="radio" name="focusLocationType" value="city"><?php _e('City / Cities','bidxplugin'); ?>
                    </label>
                    <label class="radio">
                    	<input type="radio" data-toggle="radio" name="focusLocationType" value="reach"><?php _e('Region','bidxplugin'); ?>
                    </label>
                </div>

                <div>
                	 <div class="control-group toggle toggle-focusLocationType toggle-focusLocationType-country">
	                    <label class="control-label"><?php _e('Country','bidxplugin'); ?></label>
	                    <div class="controls">
	                        <select name="focusCountry" multiple></select>
	                    </div>
	                </div>

	                <div class="control-group toggle toggle-focusLocationType toggle-focusLocationType-city">
	                    <label class="control-label"><?php _e('City','bidxplugin'); ?></label>
	                    <div class="controls">
	                    	<div class="bidx-tagsinput-container">
		                        <input type="text" autocomplete="off" name="focusCity" class="bidx-tagsinput enclosed" placeholder="<?php _e('City','bidxplugin'); ?>">
	                        </div>
	                    </div>
	                </div>

	                <div class="control-group  toggle toggle-focusLocationType toggle-focusLocationType-reach">
	                    <label class="control-label"><?php _e('Region','bidxplugin'); ?></label>
	                    <div class="controls">
	                        <input type="text" name="focusReach" data-type="location" />
	                    </div>
	                </div>

                </div>

				<div>
					<button type="submit" class="btn btn-primary bidx-theme-colour-one">Save Profile</button>
				</div>
			</div>

		</div>

	</form>
</div>
<script type="text/javascript">

/*
		$("form").form({
			callToAction : '.jsSave',
			errorClass : 'error',
			url : '/wp-admin/admin-ajax.php?action=bidx_register',
			apiurl:'ajax_register_action',
			apimethod:'post',
			enablePlugins: ['date','location','countryAutocomplete'],
			beforeSubmit : function () {
				///*document.location = "/group-creation-success/"
			}
		});



		$('[data-toggle="radio"]').change(function(e){

			var $this=$(this);

			//FlatUI triggers the onchange of all checkboxes, checked or not. We only want the checked on to fire the event
			if( !$this.is(":checked") ) {
				return false;
			}
			switch($this.val())
			{
				case "city":
					$( ".location-map, .location-list.countries" ).fadeOut( 'fast', function()
					{

						$( ".location-list.cities" ).fadeIn('fast');
					});
				break;
				case "country":
					$(" .location-map, .location-list.cities ").fadeOut( 'fast', function()
					{
						$( ".location-list.countries" ).fadeIn('fast');
					});
				break;
				case "coord":
					$( ".location-list" ).fadeOut( 'fast',function()
					{
						$( ".location-map" ).fadeIn( 'fast' );
					});
				break;
			}
		});*/

</script>
