
<?php
wp_enqueue_script ('bidx-form');
$blog_title = strtolower (get_bloginfo ());

// Remove this code after next release
$group_anonymous_login = $blog_title . 'groupanonymous';

if (!username_exists ($group_anonymous_login)) {
    $blog_id = get_current_blog_id ();
    $group_password = $blog_title . 'bidxGeeks9';
    $new_user_caps_anonymous = array ('read' => true);
    $new_role_added = add_role ('groupanonymous', 'Group Anonymous', $new_user_caps_anonymous);

    $group_anonymous_email = $blog_title . '_anonymous@bidx.net';
    //Add Group Member Role
    $user_id_anonymous = wpmu_create_user ($group_anonymous_login, $group_password, $group_anonymous_email);
    add_user_to_blog ($blog_id, $user_id_anonymous, 'groupanonymous');
}
?>
<div id="auth" class="block-odd mainState mainStateAuth">
    <div class="container">

        <section>

            <!-- LOGIN -->
            <article class="view viewLogin ">
                <div class="row-fluid">
                    <div class="span6 offset3 block-login bidx-theme-colour-panel-one">
                        <form id="frmLogin" action="/wp-login.php" method="post">
                            <h1>Login</h1>
                            <div class="row-fluid">
                                <div class="span8">
                                    <div class="control-group">
                                        <label class="control-label"><?php _e('Email address','bidxplugin');?></label>

                                        <div class="controls">
                                            <input type="email" name="log" placeholder="<?php _e('Type your email address','bidxplugin');?>" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row-fluid">
                                <div class="span8">
                                    <div class="control-group">
                                        <label class="control-label"><?php _e('Password','bidxplugin');?></label>

                                        <div class="controls">
                                            <input type="password" name="pwd" placeholder="<?php _e('Type your password','bidxplugin');?>" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="error-separate"></div>
                            <div class="row-fluid">
                                <div class="span4">
                                    <div class="buttonwrapper">
                                        <button type="submit" class="btn btn-primary btn-block bidx-theme-colour-one"><?php _e('Login','bidxplugin');?></button>
                                    </div>
                                </div>
                            </div>


                            <p>
                            <?php _e('Forgot your password. Click <a href="#auth/resetpassword">here</a> to recover.','bidxplugin');?><br/>
                            <?php
                                if ($this->showRegisterLink)
                                {
                            ?>
                                <?php _e('Not a member? Click <a href="#auth/register">here</a> to register.','bidxplugin');?>
                            <?php
                                }
                            ?>
                            </p>

                            <input type="hidden" name="redirect_to" value="<?php echo $this->redirectTo;?>" />
                            <input type="hidden" name="testcookie" value="1" />
                        </form>
                    </div>
                </div>
            </article>

            <!-- FORGOT PASSWORD -->
            <article class="view viewResetpassword">
                <div class="row-fluid">
                    <div class="span6 offset3 block-login bidx-theme-colour-panel-one">
                        <form id="frmResetpassword" action="/">
                            <div class="row-fluid">
                                <div class="span8">
                                    <div class="control-group">
                                        <label class="control-label"><?php _e('Email address','bidxplugin');?></label>

                                        <div class="controls">
                                            <input type="email" name="username" placeholder="<?php _e('Type your email address','bidxplugin');?>" />
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="buttonwrapper">
                                <button type="submit" class="btn btn-primary bidx-theme-colour-one"><?php _e('Send me a new password','bidxplugin');?></button>
                            </div>

                            <p>
                                <?php _e('Did you remember your password again?.','bidxplugin');?><br/>
                                <?php _e('Click <a href="#auth/login">here</a> to go to login.','bidxplugin');?>
                            </p>
                        </form>

                        <div class="resetpasswordSuccess hide">
                            <h3><?php _e('E-mail has been send','bidxplugin');?></h3>
                            <p><?php _e('Password reset e-mail has been send','bidxplugin');?> <br>
                                <?php _e('A password reset link has been send to you. Please check your inbox and click on the link within the e-mail to reset your password.','bidxplugin');?>
                                <br/>
                                <?php _e('Click <a href="/">here</a> to go to homepage.','bidxplugin');?>
                            </p>
                        </div>
                    </div>
                </div>
            </article>

            <!-- REGISTER -->
            <article  class="view viewRegister <?php //echo ($this->type=='register') ? 'mainStateShow':'';?>">
                 <?php $this->render ('inc_registration.phtml'); ?>
            </article>


            <script src="https://maps.googleapis.com/maps/api/js?v=3&sensor=false&libraries=places"></script>

        </section>
    </div>
</div>
