
<?php
wp_enqueue_script ('bidx-form');
$blog_title = strtolower (get_bloginfo ());

// Remove this code after next release
$group_anonymous_login = $blog_title . 'groupanonymous';

if (!username_exists ($group_anonymous_login)) {
    $blog_id = get_current_blog_id ();
    $group_password = $blog_title . 'bidxGeeks9';
    $new_user_caps_anonymous = array ('read' => true);
    $new_role_added = add_role ('groupanonymous', 'Group Anonymous', $new_user_caps_anonymous);

    $group_anonymous_email = $blog_title . '_anonymous@bidx.net';
    //Add Group Member Role
    $user_id_anonymous = wpmu_create_user ($group_anonymous_login, $group_password, $group_anonymous_email);
    add_user_to_blog ($blog_id, $user_id_anonymous, 'groupanonymous');
}
?>
<div id="auth" class="block-odd mainState mainStateAuth">
    <div class="container">

        <section class="block-login">

            <!-- LOGIN -->
            <article class="view viewLogin ">

                <form id="frmLogin" action="/wp-login.php" method="post">
                    <div class="row-fluid">
                        <div class="span8">
                            <div class="control-group">
                                <label class="control-label"><?php _e('Email address','bidxplugin');?></label>

                                <div class="controls">
                                <input type="email" name="log" placeholder="<?php _e('Type your email address','bidxplugin');?>" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span8">
                            <div class="control-group">
                                <label class="control-label"><?php _e('Password','bidxplugin');?></label>

                                <div class="controls">
                                    <input type="password" name="pwd" placeholder="<?php _e('Type your password','bidxplugin');?>" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="error-separate"></div>
                    <div class="row-fluid">
                        <div class="span4">
                            <div class="buttonwrapper">
                                <button type="submit" class="btn btn-primary btn-block bidx-theme-colour-one"><?php _e('Login','bidxplugin');?></button>
                            </div>
                        </div>
                    </div>


                    <p>
                    <?php _e('Forgot your password. Click <a href="#auth/resetpassword">here</a> to recover.','bidxplugin');?><br/>
                    <?php
                        if ($this->showRegisterLink)
                        {
                    ?>
                        <?php _e('Not a member? Click <a href="#register">here</a> to register.','bidxplugin');?>
                    <?php
                        }
                    ?>
                    </p>

                    <input type="hidden" name="redirect_to" value="<?php echo $this->redirectTo;?>" />
                    <input type="hidden" name="testcookie" value="1" />
                </form>
            </article>

            <!-- FORGOT PASSWORD -->
            <article class="view viewResetpassword">
                <form id="frmResetpassword" action="/">
                    <div class="formfield" data-validation='{"required":{"text":"<?php _e('This fields is mandatory','i18n');?>"},"typecheck":[{"email":{"text":"<?php _e('This is not a valid e-mail address','i18n');?>"}}]}'>
                        <label><?php _e('Email address','bidxplugin');?></label>
                        <input type="text" name="username" placeholder="<?php _e('Type your email address','bidxplugin');?>" />
                    </div>

                    <div class="buttonwrapper">
                        <button type="submit" class="btn btn-primary"><?php _e('Send me a new password','bidxplugin');?></button>
                    </div>

                    <p>
                        <?php _e('Did you remember your password again?.','bidxplugin');?><br/>
                        <?php _e('Click <a href="#auth/login">here</a> to go to login.','bidxplugin');?>
                    </p>
                </form>

                <div class="resetpasswordSuccess hide">
                    <h3><?php _e('E-mail has been send','bidxplugin');?></h3>
                    <p><?php _e('Password reset e-mail has been send','bidxplugin');?> <br>
                        <?php _e('A password reset link has been send to you. Please check your inbox and click on the link within the e-mail to reset your password.','bidxplugin');?>
                        <br/>
                        <?php _e('Click <a href="/">here</a> to go to homepage.','bidxplugin');?>
                    </p>
                </div>

            </article>

            <!-- REGISTER -->
             <?php $this->render ('inc_registration.phtml'); ?>

            <script src="https://maps.googleapis.com/maps/api/js?v=3&sensor=false&libraries=places"></script>

        </section>
    </div>
</div>
