<div id="login" class="block-odd mainState mainStateLogin">
   <form id="frmLogin" method="post">
        <h1><?php _e('Login','bidxplugin'); ?></h1>

<?php
    if ($this->socialauth)
    {
?>
        <label class="label-center"><?php echo _e('Choose a social network','bidxplugin') ?></label>
        <div class="row">
            <div class="col-sm-6">
                <a href="/bidx-soca/bidxauth?id=googleplus" class="btn btn-google btn-block btn-lg" role="button"><i class="fa fa-google-plus-square"></i> <?php _e('Google', 'bidxplugin');?></a>
            </div>
            <div class="col-sm-6">
                <!-- <a href="/bidx-soca/bidxauth?id=linkedin" class="btn btn-linkedin btn-block btn-lg hide" role="button"><i class="fa fa-linkedin-square"></i> <?php //_e('LinkedIn', 'bidxplugin');?></a> -->
                <a href="#auth/resetpassword/linkedin=true" class="btn btn-linkedin btn-block btn-lg" role="button"><i class="fa fa-linkedin-square"></i> <?php _e('LinkedIn', 'bidxplugin');?></a>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-sm-6">
                <a href="/bidx-soca/bidxauth?id=facebook" class="btn btn-facebook btn-block btn-lg" role="button"><i class="fa fa-facebook-square"></i> <?php _e('Facebook', 'bidxplugin');?></a>
            </div>
            <div class="col-sm-6">
                <a href="/bidx-soca/bidxauth?id=hotmail" class="btn btn-hotmail btn-block btn-lg" role="button"><i class="fa fa-windows"></i> <?php _e('Hotmail', 'bidxplugin');?></a>
            </div>
        </div>
        <div class="or">&mdash;&nbsp;<?php _e('OR','bidxplugin');?>&nbsp;&mdash;</div>

<?php
    }
?>

        <div class="form-group">
            <label class=""><?php _e('Email address','bidxplugin');?></label>
            <input type="email" class="form-control" name="log" placeholder="<?php _e('Enter your email address','bidxplugin');?>" />
        </div>
        <div class="form-group">
            <label class=""><?php _e('Password','bidxplugin');?></label>
            <input type="password" class="form-control" name="pwd" placeholder="<?php _e('Enter your password','bidxplugin');?>" />
        </div>
        <div class="error-separate alert alert-danger"></div>
        <button type="submit" class="btn btn-primary"><?php _e('Login','bidxplugin');?></button>
        <br>
        <br>
        <p>
        <?php
            if ($this->showLink != "false")
            {
                 _e('Forgot your password? Click <strong><a href="#auth/resetpassword">here</a></strong> to recover.','bidxplugin');


        ?><br/>
        <?php
                $registerUrl = _l('join'.'/#join/register');
                printf( __('Not a member? Click <strong><a href="%s">here</a></strong> to register.','bidxplugin'), $registerUrl);

            }
        ?>
        </p>

        <input type="hidden" name="redirect_to" value="<?php echo (isset($this->redirectTo)) ? $this->redirectTo:'';?>" />
        <input type="hidden" name="testcookie" value="1" />
    </form>
</div>




