<?php
$companyBidxMeta = isset( $this->company->bidxMeta )
    ? $this->company->bidxMeta
    : $this->company;
?>

<?php
    if ( $this->noheader != 'true' )
    {
?> 
    <div class="company box-border top-margin-lineheight">
<?php
    }
    else
    {
?>
    <div class="company top-margin-lineheight">
<?php
    }
?>
    <div class="mainState mainStateShow clearfix">
        <?php $this->render('view-company.phtml'); ?>
    </div>
<?php
    $this->render('edit-company.phtml');
?>
</div>
