<?php
$companyBidxMeta = isset( $this->company->bidxMeta )
    ? $this->company->bidxMeta
    : $this->company;

?>
<div class="block-odd">
<?php
    if(empty($this->bpSummary)) {
?>
    <div class="pageHeader clearfix">
        <div class="container clearfix">
            <h1><?php echo ucwords( $this->company->name); ?></h1>
            <div class="editControls btn-group"></div>
        </div>
    </div>
<?php
    }
?>
    <div class="row-fluid mainState mainStateShow">
        <div class="span12">

            <div class="well profile-block">

                <div class="btn-group controls">
<?php
    if ($companyBidxMeta->bidxCanEdit) {
?>
                    <a class="btn btn-primary" href="#editCompany/<?php echo $companyBidxMeta->bidxEntityId; ?>">Edit</a>
<?php
    }
?>
                </div>

                <h4><?php _e('Company details','bidxplugin'); ?></h4>

                <div class="row-fluid">
                    <div class="span8">
                        <?php $this->render('view-company.phtml'); ?>
                    </div>
                </div><!-- row -->
            </div><!-- well -->
        </div>
    </div>
<?php
    if(empty($this->bpSummary)) {
        $this->render('edit-company.phtml');
    }
?>
</div>
