<?php
$companyBidxMeta = isset( $this->company->bidxMeta )
    ? $this->company->bidxMeta
    : $this->company;

?>
<?php
    if(!$this->noheader) {
?>
    <div class="pageHeader clearfix">
        <h1 class="pull-left"><?php echo ucwords( $this->company->name); ?></h1>
        <div class="editControls btn-group pull-right"></div>
    </div>
<?php
    }
?>
<div class="mainState mainStateShow">
    <div class="panel panel-default">
        <div class="profile-block">
            <div class="btn-group controls">
<?php
                if ($companyBidxMeta->bidxCanEdit) {
?>
                <a class="btn btn-primary" href="#editCompany/<?php echo $companyBidxMeta->bidxEntityId; ?>">Edit</a>
<?php
                }
?>
            </div>
            <?php $this->render('view-company.phtml'); ?>
        </div>
    </div>
</div>
<?php
    $this->render('edit-company.phtml');
?>
