<div id="editCompany" class="mainState mainStateEditCompany">

    <!-- LOAD -->
    <div class="view viewLoad alert alert-info text-center">
        <div class="progress progress-striped active">
          <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
            <?php _e('Retrieving company information...','bidxplugin'); ?>
          </div>
        </div>
    </div>

    <!-- ERROR -->
    <div class="view viewError alert alert-warning">
        <h2><?php _e('Error','bidxplugin'); ?></h2>
        <p class="errorMsg"></p>
    </div>

    <!-- EDIT -->
    <div class="view viewEdit">

        <form id="frmeditCompany">

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php _e('Company details','bidxplugin'); ?></h3>
                </div>
                <div class="panel-body">
                    <blockquote class="alert-info js-mode-standalone">
                        <?php _e('In this section you can create a company.','bidxplugin')?>
                    </blockquote>
                    <div class="row">
                        <div class="col-sm-6">

                            <h3 class="js-mode-standalone"><?php _e('Create a new company','bidxplugin')?></h3>

                            <div class="form-group formfield">
                                <label><?php _e('Company name','bidxplugin'); ?></label>
                                <input type="text" class="form-control" name="name" placeholder="<?php _e('Please enter your company name','bidxplugin'); ?>">
                            </div>

                            <div class="form-group formfield">
                                <label><?php _e('Company website','bidxplugin'); ?></label>
                                <input type="text" class="form-control" name="website" placeholder="<?php _e('Please fill in your website address','bidxplugin'); ?>">
                            </div>

                            <input type="hidden" name="statutoryAddress.coordinates"    />

                            <h3>Company main address</h3>
                            <blockquote class="alert-info"><?php _e('Enter the physical address where your company is registered.','bidxplugin')?></blockquote>

                            <div class="form-group formfield">
                                <label><?php _e('Country','bidxplugin'); ?></label>
                                <select name="statutoryAddress.country"></select>
                            </div>

                            <div class="form-group formfield">
                                <label><?php _e('City','bidxplugin'); ?></label>
                                <input type="text" class="form-control" name="statutoryAddress.cityTown" placeholder="<?php _e('Please enter your city','bidxplugin'); ?>" />
                            </div>

                            <div class="form-group formfield">
                                <label><?php _e('Street','bidxplugin'); ?></label>
                                <input type="text" class="form-control" name="statutoryAddress.street" placeholder="<?php _e('Please enter your street name','bidxplugin'); ?>" />
                            </div>

                            <div class="form-group formfield">
                                <label><?php _e('Building number','bidxplugin'); ?></label>
                                <input type="text" class="form-control" name="statutoryAddress.streetNumber" placeholder="<?php _e('Please enter your building number','bidxplugin'); ?>" />
                            </div>

                            <div class="form-group formfield">
                                <label><?php _e('Postal code','bidxplugin'); ?></label>
                                <input type="text" class="form-control" name="statutoryAddress.postalCode" placeholder="<?php _e('Please enter your postcode','bidxplugin'); ?>" />
                            </div>

                            <div class="form-group formfield">
                                <label><?php _e('Neighborhood','bidxplugin'); ?></label>
                                <input type="text" class="form-control" name="statutoryAddress.neighborhood" placeholder="<?php _e('Please enter your neighborhood','bidxplugin'); ?>" />
                            </div>

                            <div class="currentAddressMap"></div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group logo-control">
                                <label class="control-label"><?php _e('Logo','bidxplugin'); ?></label>
                                <div class="controls">
                                    <div class="logoContainer"></div>
                                    <br>
                                    <a href="#changeLogo" class="btn btn-default"><?php _e('Select logo','bidxplugin');?></a>

                                    <div class="changeLogoModal modal fade">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                    <h3><?php _e('Select the file you want to use for a logo', 'bidxplugin' ); ?></h3>
                                                </div>
                                                <div class="modal-body">
    <?php
                                                    echo do_shortcode( '[bidx app="media"]' );
    ?>
                                                </div>
                                                <div class="modal-footer">
                                                    <a href="#" class="btn btn-primary btnSelectFile"><?php _e( 'Select file(s)', 'bidxplugin' ); ?></a>
                                                    <a href="#" class="btn btn-default btnCancelSelectFile"><?php _e( 'Cancel', 'bidxplugin' ); ?></a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group formfield">
                                <label><?php _e('Is your company registered?','bidxplugin'); ?></label>
                                <div class="radio">
                                    <input type="radio" value="true" id="radio-registeredYes" name="registered" data-toggle="radio" />
                                    <label for="radio-registeredYes"><span></span><?php _e('Yes','bidxplugin'); ?></label>
                                </div>
                                <div class="radio">
                                    <input type="radio" value="false" id="radio-registeredNo" name="registered" data-toggle="radio" />
                                    <label for="radio-registeredNo"><span></span><?php _e('No','bidxplugin'); ?></label>
                                </div>
                            </div>

                            <div class="form-group formfield toggle toggle-registered">
                                <label><?php _e('Date of registration','bidxplugin'); ?></label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                    <input type="text" class="form-control" name="dateCompanyEstab" data-type="date" placeholder="<?php _e('Please enter the date you registered your business','bidxplugin'); ?>">
                                </div>
                            </div>

                            <div class="form-group formfield toggle toggle-registered">
                                <label><?php _e('Legal form of business','bidxplugin'); ?></label>
                                <select name="legalFormBusiness"></select>
                            </div>

                            <div class="form-group formfield toggle toggle-registered">
                                <label><?php _e('Fiscal number','bidxplugin'); ?></label>
                                <div class="input-group">
                                    <span class="input-group-addon">#</span>
                                    <input type="text" class="form-control" name="fiscalNumber" placeholder="<?php _e('Please enter your fiscal number','bidxplugin'); ?>">
                                </div>
                            </div>

                            <div class="form-group formfield toggle toggle-registered">
                                <label><?php _e('Company registration number','bidxplugin'); ?></label>
                                <div class="input-group">
                                    <span class="input-group-addon">#</span>
                                    <input type="text" class="form-control" name="registrationNumber" placeholder="<?php _e('Please enter your registration number','bidxplugin'); ?>">
                                </div>
                            </div>

                            <div class="form-group formfield">
                                <label><?php _e('Do you have employees?','bidxplugin'); ?></label>
                                <div class="radio">
                                    <input type="radio" value="true" id="radio-haveEmployeesYes" name="haveEmployees" data-toggle="radio" />
                                    <label for="radio-haveEmployeesYes"><span></span><?php _e('Yes','bidxplugin'); ?></label>
                                </div>
                                <div class="radio">
                                    <input type="radio" value="false" id="radio-haveEmployeesNo" name="haveEmployees" data-toggle="radio" />
                                    <label for="radio-haveEmployeesNo"><span></span><?php _e('No','bidxplugin'); ?></label>
                                </div>
                            </div>

                            <div class="form-group formfield toggle toggle-haveEmployees">
                                <label><?php _e('Number of permanent female employees','bidxplugin'); ?></label>
                                <div class="input-group">
                                    <span class="input-group-addon">#</span>
                                    <input type="text" class="form-control" name="numPermFemaleEmpl" placeholder="<?php _e('Please enter the number of permanent female employees employed by your business','bidxplugin'); ?>">
                                </div>
                            </div>

                            <div class="form-group formfield toggle toggle-haveEmployees">
                                <label><?php _e('Number of permanent male employees','bidxplugin'); ?></label>
                                <div class="input-group">
                                    <span class="input-group-addon">#</span>
                                    <input type="text" class="form-control" name="numPermMaleEmpl" placeholder="<?php _e('Please enter the number of permanent male employees employed by your business','bidxplugin'); ?>">
                                </div>
                            </div>

                            <div class="form-group formfield toggle toggle-haveEmployees">
                                <label><?php _e('Number of temporary female employees','bidxplugin'); ?></label>
                                <div class="input-group">
                                    <span class="input-group-addon">#</span>
                                    <input type="text" class="form-control" name="numTempFemaleEmpl" placeholder="<?php _e('Please enter the number of temporary female employees employed by your business','bidxplugin'); ?>">
                                </div>
                            </div>

                            <div class="form-group formfield toggle toggle-haveEmployees">
                                <label><?php _e('Number of temporary male employees','bidxplugin'); ?></label>
                                <div class="input-group">
                                    <span class="input-group-addon">#</span>
                                    <input type="text" class="form-control" name="numTempMaleEmpl" placeholder="<?php _e('Please enter the number of temporary male employees employed by your business','bidxplugin'); ?>">
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <div class="countryOperationSpecifics">
                        <blockquote class="alert-info">
                            <?php _e( 'If you have offices in other locations, you can add them in the section below', 'bidxplugin' ); ?>
                        </blockquote>
                        <h4><?php _e('Country Operation Specifics','bidxplugin'); ?>
                            <a href="#addCountryOperationSpecifics" class="btn btn-xs btn-primary"><span class="fa fa-plus"></span> <?php _e('Add','bidxplugin'); ?></a>
                        </h4>
                    </div>

                    <div class="countryOperationSpecificsContainer"></div>
                </div>
            </div>

        </form>
    </div>

    <div class="snippets hide">
        <div class="countryOperationSpecificsItem col-sm-4">
            <div class="well">
                <div class="form-group formfield">
                    <label class="control-label"><?php _e('Country','bidxplugin'); ?></label>
                    <div class="controls">
                        <select name="country"></select>
                    </div>
                </div>
                <div class="form-group formfield">
                    <label><?php _e('Company trade name','bidxplugin'); ?></label>
                    <input type="text" class="form-control" name="companyTradeName" placeholder="<?php _e('Please enter your company’s trading name','bidxplugin'); ?>" />
                </div>
                <div class="form-group formfield">
                    <label class="control-label"><?php _e('Permits and/or licenses','bidxplugin'); ?></label>
                    <div class="controls">
                        <select name="permitsLicencesObtained"></select>
                    </div>
                </div>

                <a href="#removeItem" class="btn btn-danger btn-sm btn-block"><?php _e('Remove this office','bidxplugin'); ?></a>
            </div>
        </div>
    </div>
</div><!-- // row #editCompany -->
