<div id="editCompany" class="row-fluid mainState mainStateEditCompany">

    <!-- LOAD -->
    <div class="view viewLoad span12">
        <span><?php _e('Retrieving company information...','bidxplugin'); ?></span>
    </div>

    <!-- ERROR -->
    <div class="view viewError span12">
        <h2><?php _e('Error','bidxplugin'); ?></h2>
        <p class="errorMsg"></p>
    </div>

    <!-- EDIT -->
    <div class="view viewEdit">

        <form id="frmeditCompany">

            <!-- "id" is actually the memberProfileId, but to not have to rewrite the file upload let's do it like this -->
            <input type="hidden" name="companyProfileId"     />
            <input type="hidden" name="domain"              />

            <fieldset class="well">
                <span class="scrollPositionMarker" id="editCompany/companyDetail"></span>
                <legend><?php _e('Company detail','bidxplugin'); ?></legend>

                <div class="row-fluid">
                    <div class="span4">

                        <div class="control-group formfield">
                            <label class="control-label"><?php _e('Company name','bidxplugin'); ?></label>
                            <div class="controls">
                                <input type="text" name="name" placeholder="<?php _e('Please type your company name','bidxplugin'); ?>">
                            </div>
                        </div>

                        <div class="control-group formfield">
                            <label class="control-label"><?php _e('Company website','bidxplugin'); ?></label>
                            <div class="controls">
                                <input type="text" name="website" placeholder="<?php _e('Please type your website','bidxplugin'); ?>">
                            </div>
                        </div>

                        <input type="hidden" name="statutoryAddress.coordinates"    />

                        <div class="control-group formfield">
                            <label class="control-label"><?php _e('Country','bidxplugin'); ?></label>
                            <div class="controls">
                                <select name="statutoryAddress.country"></select>
                            </div>
                        </div>

                        <div class="control-group formfield">
                            <label class="control-label"><?php _e('City','bidxplugin'); ?></label>
                            <div class="controls">
                                <input type="text" name="statutoryAddress.cityTown" placeholder="<?php _e('Please type your city','bidxplugin'); ?>" />
                            </div>
                        </div>

                        <div class="control-group formfield">
                            <label class="control-label"><?php _e('Street','bidxplugin'); ?></label>
                            <div class="controls">
                                <input type="text" name="statutoryAddress.street" placeholder="<?php _e('Please type your street','bidxplugin'); ?>" />
                            </div>
                        </div>

                        <div class="control-group formfield">
                            <label class="control-label"><?php _e('Street number','bidxplugin'); ?></label>
                            <div class="controls">
                                <input type="text" name="statutoryAddress.streetNumber" placeholder="<?php _e('Please type your street number','bidxplugin'); ?>" />
                            </div>
                        </div>

                        <div class="control-group formfield">
                            <label class="control-label"><?php _e('Postal code','bidxplugin'); ?></label>
                            <div class="controls">
                                <input type="text" name="statutoryAddress.postalCode" placeholder="<?php _e('Please type your postcode','bidxplugin'); ?>" />
                            </div>
                        </div>

                        <div class="control-group formfield">
                            <label class="control-label"><?php _e('Neighborhood','bidxplugin'); ?></label>
                            <div class="controls">
                                <input type="text" name="statutoryAddress.neighborhood" placeholder="<?php _e('Please type your neighborhood','bidxplugin'); ?>" />
                            </div>
                        </div>

                        <div class="currentAddressMap"></div>

                        <div class="control-group formfield">
                            <label class="control-label"><?php _e('Is your company registered?','bidxplugin'); ?></label>
                            <div class="controls">
                                <label class="radio inline"><input type="radio" value="true"  name="registered" data-toggle="radio"/> <?php _e('Yes','bidxplugin'); ?></label>
                                <label class="radio inline"><input type="radio" value="false" name="registered" data-toggle="radio"/> <?php _e('No','bidxplugin'); ?></label>
                            </div>
                        </div>

                        <div class="control-group formfield toggle toggle-registered">
                            <label class="control-label"><?php _e('Date of registration','bidxplugin'); ?></label>
                            <div class="controls">
                                <input type="text" name="dateCompanyEstab" data-type="date" placeholder="<?php _e('Please type your date of date of registration','bidxplugin'); ?>">
                            </div>
                        </div>

                        <div class="control-group formfield toggle toggle-registered">
                            <label class="control-label"><?php _e('Legal form of business','bidxplugin'); ?></label>
                            <div class="controls">
                                <select name="legalFormBusiness"></select>
                            </div>
                        </div>

                        <div class="control-group formfield toggle toggle-registered">
                            <label class="control-label"><?php _e('Fiscal number','bidxplugin'); ?></label>
                            <div class="controls">
                                <input type="text" name="fiscalNumber" placeholder="<?php _e('Please type your fiscal number','bidxplugin'); ?>">
                            </div>
                        </div>

                        <div class="control-group formfield toggle toggle-registered">
                            <label class="control-label"><?php _e('Company registration number','bidxplugin'); ?></label>
                            <div class="controls">
                                <input type="text" name="registrationNumber" placeholder="<?php _e('Please type your registration number','bidxplugin'); ?>">
                            </div>
                        </div>

                        <div class="control-group formfield">
                            <label class="control-label"><?php _e('Do you have employees?','bidxplugin'); ?></label>
                            <div class="controls">
                                <label class="radio inline"><input type="radio" value="true"  name="haveEmployees" data-toggle="radio"/> <?php _e('Yes','bidxplugin'); ?></label>
                                <label class="radio inline"><input type="radio" value="false" name="haveEmployees" data-toggle="radio"/> <?php _e('No','bidxplugin'); ?></label>
                            </div>
                        </div>

                        <div class="control-group formfield toggle toggle-haveEmployees">
                            <label class="control-label"><?php _e('Number of permanent female employees','bidxplugin'); ?></label>
                            <div class="controls">
                                <input type="text" name="numPermFemaleEmpl" placeholder="<?php _e('Please type the number of permanent female employees','bidxplugin'); ?>">
                            </div>
                        </div>

                        <div class="control-group formfield toggle toggle-haveEmployees">
                            <label class="control-label"><?php _e('Number of permanent male employees','bidxplugin'); ?></label>
                            <div class="controls">
                                <input type="text" name="numPermMaleEmpl" placeholder="<?php _e('Please type the number of permanent male employees','bidxplugin'); ?>">
                            </div>
                        </div>

                        <div class="control-group formfield toggle toggle-haveEmployees">
                            <label class="control-label"><?php _e('Number of temporary female employees','bidxplugin'); ?></label>
                            <div class="controls">
                                <input type="text" name="numTempFemaleEmpl" placeholder="<?php _e('Please type the number of temporary female employees','bidxplugin'); ?>">
                            </div>
                        </div>

                        <div class="control-group formfield toggle toggle-haveEmployees">
                            <label class="control-label"><?php _e('Number of temporary male employees','bidxplugin'); ?></label>
                            <div class="controls">
                                <input type="text" name="numTempMaleEmpl" placeholder="<?php _e('Please type the number of temporary male employees','bidxplugin'); ?>">
                            </div>
                        </div>
                    </div>

                    <div class="span4">
                        <div class="control-group formfield logo-control">
                            <label class="control-label"><?php _e('Logo','bidxplugin'); ?></label>
                            <div class="controls">
                                <div class="logoContainer" id="editCompanyLogo"></div>
                                <input type="file" name="fileContent" data-type="fileUpload" data-type-arguments='{"url":"/wp-admin/admin-ajax.php?action=file_upload", "extraValues":[{"name": "uploadtype", "value":"companylogo"}], "addFields":["companyProfileId","domain"], "imageContainer": "#editCompanyLogo"}'/>
                            </div>
                        </div>
                    </div>

                    <div class="span4 countryOperationSpecifics">
                        <div class="accordion" id="countryOperationSpecificsAccordion"></div>
                        <a href="#addCountryOperationSpecifics" class="btn btn-large btn-block btn-primary"><?php _e('Add country specific operations','bidxplugin'); ?></a>
                    </div>
                </div>

            </fieldset>

        </form>
    </div>

    <div class="snippets hide">
        <div class="countryOperationSpecificsItem accordion-group">
            <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#countryOperationSpecificsAccordion" href="#">
                    <h4 class="accordion-title">&nbsp;</h4>
                    <div class="control-buttons">
                        <span class="bidx-expand">+</span>
                        <span class="bidx-collapse">-</span>
                    </div>
                </a>
            </div><!-- accordion-heading -->
            <div class="accordion-body collapse in" id="">
                <div class="accordion-inner">
                    <div class="control-group formfield">
                        <label class="control-label"><?php _e('Country','bidxplugin'); ?></label>
                        <div class="controls">
                            <select name="country"></select>
                        </div>
                    </div>

                    <div class="control-group formfield">
                        <label class="control-label"><?php _e('Company trade name','bidxplugin'); ?></label>
                        <div class="controls">
                            <input type="text" name="companyTradeName" placeholder="<?php _e('Please type your company trade name','bidxplugin'); ?>">
                        </div>
                    </div>

                    <div class="control-group formfield">
                        <label class="control-label"><?php _e('Permits licences obtained','bidxplugin'); ?></label>
                        <div class="controls">
                            <select name="permitsLicencesObtained"></select>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

</div><!-- // row -->
