<?php
    $companyBidxMeta = isset( $this->company->bidxMeta )
        ? $this->company->bidxMeta
        : $this->company;

    $comLogo = $this->exst($this->company->logo->document);
    $countryOperationSpecifics = isset ($this->company->countryOperationSpecifics) ? $this->company->countryOperationSpecifics : NULL;
?>
<div class="bg-primary-light main-padding">
    <h1 class="text-center"><?php echo ($this->companyTitle) ? ucwords( $this->company->name) :''; ?></h1>
</div>

<div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">

<?php
        if ( $companyBidxMeta->bidxCanEdit )
        {
?>
            <div class="btn-group controls pull-right top-margin-lineheight">
                <a class="btn btn-primary" href="#editCompany/<?php echo $companyBidxMeta->bidxEntityId; ?>"><i class="fa fa-big fa-above fa-pencil"></i> <?php _e( 'Edit', 'bidxplugin' ); ?></a>
            </div>
<?php
        }
?>
    </div>
</div>

<div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
    <div class="text-center bottom-margin-lineheight top-margin-lineheight">
<?php
        if ( !$comLogo )
        {
            echo '<div class="icons-rounded"><i class="fa fa-building text-primary-light"></i></div>';
        }
        else
        {
            echo '<img class="img-responsive center-image" src="'.$comLogo.'"/>';
        }
?>
    </div>
<?php

    $companySite = $this->exst( $this->company->website ) ? sprintf( '<a href="%1$s" target="_blank">%1$s</a>', $this->exst( $this->company->website )) : NULL;

    if ( !empty( $this->company->registered ) )
    {

        $statutoryAddress = $this->exst( $this->company->statutoryAddress );

        $arStatutoryAddress = array();
        if ( $this->exst( $statutoryAddress->streetNumber ) ) { $arStatutoryAddress[] = $statutoryAddress->streetNumber; }
        if ( $this->exst( $statutoryAddress->street ) )       { $arStatutoryAddress[] = $statutoryAddress->street . ', '; }
        if ( $this->exst( $statutoryAddress->postalCode ) )   { $arStatutoryAddress[] = $statutoryAddress->postalCode; }
        if ( $this->exst( $statutoryAddress->neighborhood ) ) { $arStatutoryAddress[] = $statutoryAddress->neighborhood; }

        $arStatutoryCityCountry = array();
        if ( $this->exst( $statutoryAddress->country ) )      { $arStatutoryCityCountry[] = $this->getStaticVal( 'country', $statutoryAddress->country ); }
        if ( $this->exst( $statutoryAddress->cityTown ) )     { $arStatutoryCityCountry[] = $statutoryAddress->cityTown; }

    }
    $rowValues = array(
        __('Company name','bidxplugin') => $this->exst($this->company->name),
        __('Company website') => $this->companyWebsite,
        __('Registered') => $this->exst($this->company->registered) == true ? __('Yes','bidxplugin') : __('No','bidxplugin'),
        __('Legal form of business') => $this->getStaticVal( 'legalForm', $this->exst($this->company->legalFormBusiness) ),
        __('Registration number') => $this->exst($this->company->registrationNumber),
        __('Fiscal number') => $this->exst($this->company->fiscalNumber),
        __('Date of registration') => $this->exst($this->company->dateCompanyEstab),
        __('Permanent female employees') => $this->exst($this->company->numPermFemaleEmpl ),
        __('Permanent male employees') => $this->exst($this->company->numPermMaleEmpl ),
        __('Temporary female employees') => $this->exst($this->company->numTempFemaleEmpl ),
        __('Temporary male employees') => $this->exst($this->company->numTempMaleEmpl ),
        __('Statutory country, city') => $arStatutoryCityCountry ? implode( ', ', $arStatutoryCityCountry ) : NULL,
        __('Statutory address') => $arStatutoryAddress ? implode( ' ', $arStatutoryAddress ) : NULL
    );
    echo $this->tableRow( $rowValues );

    if ( $countryOperationSpecifics )
    {
        $header = array (
            __('Country','bidxplugin') => 'country',
            __('Company trade name','bidxplugin') => 'companyTradeName',
            __('Permit or licences','bidxplugin') => 'permitsLicencesObtained',
            __('Company Address','bidxplugin') => 'companyAddress'
        );

        $countryOperationSpecificsHtml = $this->addTableRows( $header, $countryOperationSpecifics, 'table table-bordered', '', array('permitsLicencesObtained' => 'hidden-xs'), array( 'permitsLicencesObtained', 'country', 'companyAddress' ) );
        
        $rowValues = array ( __('Country Operation Specifics','bidxplugin') => $countryOperationSpecificsHtml );
        
        echo $this->addRowsWithLabelBelow ( 'col-sm-12', 'col-sm-12', $rowValues, array ( 'tag_label' => 'h4' ) );
    }
?>
    </div>
</div>
