<?php


?>

<form action="/wp-login.php" method="post">
	<div class="formfield" data-validation='{"required":{"text":"This fields is mandatory"},"typecheck":[{"email":{"text":"This is not a valid e-mail address"}}]}'>
		<label>Email address</label>
		<input type="text" name="log" placeholder="Type your email address" />
	</div>

	<div class="buttonwrapper">
		<a href="#" class="button primary jsForget">Send me a new password</a>

	</div>
	<p>
		Did you remember your password again? <br>Click <a href="/forgot-password">here</a> to recover.<br/>

	</p>

		<!-- <input type="button" name="wp-submit"  value="Log In" /> -->
		<input type="hidden" name="redirect_to" value="[!Q!]" />
		<input type="hidden" name="testcookie" value="1" />
</form>
<script type="text/javascript">
	$(function(){
		$("form").form({
			callToAction : '.jsForget',
			errorClass : 'error',
			url : '/wp-admin/admin-ajax.php?action=bidx_signin'
		});
	});
</script>
