

<div  class="mainState mainStateRegister <?php echo ($this->type=='register') ? 'mainStateShow':'';?>" style="display:none">
	<form id="frmRegister" action="/">
		<div class="formfield" data-validation='{"required":{"text":"<?php _e('A first name is mandatory');?>"}}'>
			<label><?php _e('First name');?></label>
			<input type="text" name="personalDetails.firstName" placeholder="<?php _e('Type your first name');?>" />
		</div>

		<div class="formfield" data-validation='{"required":{"text":"<?php _e('A last name is mandatory');?>"}}'>
			<label><?php _e('Last name');?></label>
			<input type="text" name="personalDetails.lastName" placeholder="<?php _e('Type your last name');?>" />
		</div>

		<div class="formfield" data-validation='{"required":{"text":"<?php _e('This field is mandatory');?>"},"typecheck":[{"email":{"text":"<?php _e('This is not a valid e-mail address');?>"}},{"custom":{"url":"/wp-admin/admin-ajax.php?action=bidx_request","apiurl":"members/validateUsername","apimethod":"get"}}]}'>
			<label><?php _e('Email address','bix-plugin');?></label>
			<input type="text" name="username" placeholder="<?php _e('Type your email address');?>" />
		</div>

		<div class="formfield" data-validation='{"required":{"text":"<?php _e('A location is mandatory');?>"}}'>
			<label><?php _e('What is your location?');?></label>
			<input type="text" name="address" placeholder="<?php _e('Please type your location');?>" data-type="location" data-type-arguments=''/>
		</div>

		<div class="buttonwrapper">
			<a href="#" class="btn btn-primary jsRegister"><?php _e('Register');?></a>
		</div>
        <?php if($this->showLoginLink) { ?>
		<p>
			<?php _e('Forgot your password. Click <a href="#resetpassword">here</a> to recover.');?><br/>
			<?php _e('Login? Click <a href="#login">here</a> to go to login.');?>
		</p>
        <?php } ?>
	</form>

	<div class="registerSuccess hide">
		<h3><?php _e('Registration complete');?></h3>
		<p><?php _e('The registration is complete. An e-mail has been dispatched with followup instructions.');?></p>
        </div>
</div>

<script>
        window.bidx = window.bidx || {};
        window.bidx.api = {
                settings: {
                        servicesPath:   '/wp-content/plugins/bidx-plugin/static/js/bidxAPI/services/'
                }
        };

        $(function(){
                var $stateRegister	= $( ".mainStateRegister" )
                ,	$frmRegister 	= $( "#frmRegister" )
                ,	$btnRegister	= $frmRegister.find( ".jsRegister" )

                ;

                $frmRegister.form({
                        errorClass : 'error',
                        enablePlugins: ['location','countryAutocomplete']
                });

                $btnRegister.click( function( e )
                {
                        e.preventDefault();

                       $frmRegister.submit();
                } );

                $frmRegister.submit( function( e )
                {
                        e.preventDefault();

                        var valid = $frmRegister.form( "validateForm" );

                        if ( !valid || $btnRegister.hasClass( "disabled" ) )
                        {
                                return;
                        }

                        $btnRegister.addClass( "disabled" );

                        // Build up the data for the member request
                        //
                        var member =
                        {
                                emailAddress: 			$frmRegister.find( "[name='username']" ).val()
                        ,	personalDetails:
                                {
                                        firstName: 				$frmRegister.find( "[name='personalDetails.firstName']" ).val()
                                ,	lastName: 				$frmRegister.find( "[name='personalDetails.lastName']" ).val()
                                }
                        };

                        // Currently, address is required, so this is a bit of an unlogical test. Wouldn't be surprised it will
                        // be gone
                        //
                        if ( $frmRegister.find( "[name='address']" ).val() )
                        {
                                // Finding the hidden fields is a hack, just search for the fields *ENDING* with names we are looking for
                                // Just to not have to change the location.js plugin
                                //
                                member.personalDetails.address =
                                [
                                        {
                                            coordinates: 			$frmRegister.find( "[name$=location]" ).val()
                                        ,	postalCode: 			$frmRegister.find( "[name$=postalCode]" ).val()
                                        ,	country: 				$frmRegister.find( "[name$=country]" ).val()
                                        ,	cityTown: 				$frmRegister.find( "[name$=cityTown]" ).val()
                                        ,	neighborhood: 			$frmRegister.find( "[name$=neighborhood]" ).val()
                                        ,	streetNumber: 			$frmRegister.find( "[name$=streetNumber]" ).val()
                                        ,	street: 				$frmRegister.find( "[name$=street]" ).val()
                                        }
                                ];
                        }

                bidx.api.call(
                    "member.save"
                ,   {
                        groupDomain:    bidx.common.groupDomain
                    ,   data:           member
                    ,   success:        function( response )
                        {
                            bidx.utils.log( "member.save::success::response", response );

                            // Go to group dashboard
                            //


                            $frmRegister.hide();
                            $stateRegister.find( ".registerSuccess" ).removeClass( "hide" );
                            var urlparam = '<?php  echo base64_encode('groupname='.$this->groupNotification);?>';
                            var url = window.location.protocol + "//" + window.location.host + "?smsg=4&rs=true&sparam=" + urlparam;
		                    window.location.href = url;
                        }
                    ,   error:          function( jqXhr )
                        {
                            $btnRegister.removeClass( "disabled" );

                            alert( "<?php _e('Problem while registering');?> );
                        }
                    }
                );

                } );





        });
</script>
