
<?php
wp_enqueue_script ('bidx-form');
$blog_title = strtolower (get_bloginfo ());

// Remove this code after next release
$group_anonymous_login = $blog_title . 'groupanonymous';

if (!username_exists ($group_anonymous_login)) {
    $blog_id = get_current_blog_id ();
    $group_password = $blog_title . 'bidxGeeks9';
    $new_user_caps_anonymous = array ('read' => true);
    $new_role_added = add_role ('groupanonymous', 'Group Anonymous', $new_user_caps_anonymous);

    $group_anonymous_email = $blog_title . '_anonymous@bidx.net';
    //Add Group Member Role
    $user_id_anonymous = wpmu_create_user ($group_anonymous_login, $group_password, $group_anonymous_email);
    add_user_to_blog ($blog_id, $user_id_anonymous, 'groupanonymous');
}
?>
<div class="block-odd">
    <div class="container">
        <div class="block-login">
            <!-- LOGIN -->
            <div class="mainState mainStateLogin mainStateShow">

                <form id="frmLogin" action="/wp-login.php" method="post">
                    <div class="formfield" data-validation='{"required":{"text":"<?php _e('This fields is mandatory','bidx-plugin');?>"},"typecheck":[{"email":{"text":"<?php _e('This is not a valid e-mail address','bidx-plugin');?>"}}]}'>
                        <label><?php _e('Email address','bidx-plugin');?></label>
                        <input type="text" name="log" placeholder="<?php _e('Type your email address','bidx-plugin');?>" />
                    </div>
                    <div class="formfield" data-validation='{"required":{"text":"<?php _e('A password is mandatory','bidx-plugin');?>"}}'>
                        <label><?php _e('Password','bidx-plugin');?></label>
                        <input type="password" name="pwd" placeholder="<?php _e('Type your password','bidx-plugin');?>" />
                    </div>
                    <div class="buttonwrapper">
                        <a href="#" class="btn btn-primary jsLogin"><?php _e('Login','bidx-plugin');?></a>
                    </div>

                        <p>
                            <?php _e('Forgot your password. Click <a href="#resetpassword">here</a> to recover.','bidx-plugin');?><br/>
                     <?php if ($this->showRegisterLink) { ?>
                            <?php _e('Not a member? Click <a href="#register">here</a> to register.','bidx-plugin');?>
                        </p>
                    <?php } ?>

            <!-- <input type="button" name="wp-submit"  value="Log In" /> -->
                    <input type="hidden" name="redirect_to" value="[!Q!]" />
                    <input type="hidden" name="testcookie" value="1" />
                </form>
                <script>
                    $(function() {

                        var formParams = {
                            callToAction: '.jsLogin',
                            errorClass: 'error',
                            url: '/wp-admin/admin-ajax.php?action=bidx_signin'
                        };

                        $("#frmLogin").form( formParams );

                        $("#frmLogin  > .formfield > :input").keypress( function(e){
                            if( e.which === 13 ) {
                                $(".jsLogin").trigger( "click" );
                            }
                        });
                    });
                </script>
            </div>

            <!-- FORGOT PASSWORD -->
            <div class="mainState mainStateResetpassword" style="display:none">
                <form id="frmResetpassword" action="/">
                    <div class="formfield" data-validation='{"required":{"text":"This fields is mandatory"},"typecheck":[{"email":{"text":"This is not a valid e-mail address"}}]}'>
                        <label><?php _e('Email address','bidx-plugin');?></label>
                        <input type="text" name="username" placeholder="Type your email address" />
                    </div>

                    <div class="buttonwrapper">
                        <a href="#" class="btn btn-primary jsResetpassword"><?php _e('Send me a new password','bidx-plugin');?></a>
                    </div>

                    <p>
                        <?php _e('Did you remember your password again?.','bidx-plugin');?><br/>
                        <?php _e('Click <a href="#login">here</a> to go to login.','bidx-plugin');?>
                    </p>
                </form>

                <div class="resetpasswordSuccess hide">
                    <h3><?php _e('E-mail has been send','bidx-plugin');?></h3>
                    <p><?php _e('Password reset e-mail has been send','bidx-plugin');?> <br>
                        <?php _e('A password reset link has been send to you. Please check your inbox and click on the link within the e-mail to reset your password.','bidx-plugin');?>
                        <br/>
                        <?php _e('Click <a href="/">here</a> to go to homepage.','bidx-plugin');?>
                    </p>
                </div>

            </div>
            <!-- REGISTER -->
             <?php
            if($this->type == 'default') {
                $this->render ('registration.phtml');
            }
            ?>

            <script>
                window.bidx = window.bidx || {};
                window.bidx.api = {
                    settings: {
                        servicesPath: '/wp-content/plugins/bidx-plugin/static/js/bidxAPI/services/'
                    }
                };
                $(function() {
                    /* Forgot Password */
                    var $stateResetpassword = $(".mainStateResetpassword")
                            , $frmResetpassword = $("#frmResetpassword")
                            , $btnResetpassword = $frmResetpassword.find(".jsResetpassword")

                            ;

                    $btnResetpassword.click(function(e)
                    {
                        e.preventDefault();

                        $frmResetpassword.submit();
                    });

                    $frmResetpassword.submit(function(e)
                    {
                        e.preventDefault();


                        if ($btnResetpassword.hasClass("disabled"))
                        {
                            return;
                        }

                        $btnResetpassword.addClass("disabled");

                        // Build up the data for the member request
                        //
                        var resetpass =
                                {
                                    username: $frmResetpassword.find("[name='username']").val()

                                };


                        bidx.api.call(
                                "resetpassword.save"
                                , {
                            groupDomain: bidx.common.groupDomain
                                    , data: resetpass
                                    , success: function(response)
                            {
                                bidx.utils.log("resetpassword.save::success::response", response);

                                // Go to group dashboard
                                //

                                $frmResetpassword.hide();
                                $stateResetpassword.find(".resetpasswordSuccess").removeClass("hide");

                                //		                    window.location.href = url;
                            }
                            , error: function(jqXhr)
                            {
                                alert(JSON.stringify(jqXhr));
                                $btnResetpassword.removeClass("disabled");

                                alert("Problem while reseting the password");
                            }
                        }
                        );

                    });
                });

            </script>


            <script src="https://maps.googleapis.com/maps/api/js?v=3&sensor=false&libraries=places"></script>
        </div>
    </div>
</div>
