
<?php
wp_enqueue_script ('bidx-form');
$blog_title = strtolower (get_bloginfo ());

// Remove this code after next release
$group_anonymous_login = $blog_title . 'groupanonymous';

if (!username_exists ($group_anonymous_login)) {
    $blog_id = get_current_blog_id ();
    $group_password = $blog_title . 'bidxGeeks9';
    $new_user_caps_anonymous = array ('read' => true);
    $new_role_added = add_role ('groupanonymous', 'Group Anonymous', $new_user_caps_anonymous);

    $group_anonymous_email = $blog_title . '_anonymous@bidx.net';
    //Add Group Member Role
    $user_id_anonymous = wpmu_create_user ($group_anonymous_login, $group_password, $group_anonymous_email);
    add_user_to_blog ($blog_id, $user_id_anonymous, 'groupanonymous');
}
?>
<div class="block-odd">
    <div class="container">  
        <div class="block-login">
            <!-- LOGIN -->
            <div class="mainState mainStateLogin mainStateShow">

                <form id="frmLogin" action="/wp-login.php" method="post">
                    <div class="formfield" data-validation='{"required":{"text":"This fields is mandatory"},"typecheck":[{"email":{"text":"This is not a valid e-mail address"}}]}'>
                        <label>Email address</label>
                        <input type="text" name="log" placeholder="Type your email address" />
                    </div>
                    <div class="formfield" data-validation='{"required":{"text":"A password is mandatory"}}'>
                        <label>Password</label>
                        <input type="password" name="pwd" placeholder="Type your password" />
                    </div>
                    <div class="buttonwrapper">
                        <a href="#" class="btn btn-primary jsLogin">Login</a>
                    </div>

                    <?php if ($this->showRegisterLink) { ?>
                        <p>
                            Forgot your password. Click <a href="#resetpassword">here</a> to recover.<br/>
                            Not a member? Click <a href="#register">here</a> to register.
                        </p>
                    <?php } ?>

            <!-- <input type="button" name="wp-submit"  value="Log In" /> -->
                    <input type="hidden" name="redirect_to" value="[!Q!]" />
                    <input type="hidden" name="testcookie" value="1" />
                </form>
                <script>
                    $(function() {
                        $("#frmLogin").form({
                            callToAction: '.jsLogin',
                            errorClass: 'error',
                            url: '/wp-admin/admin-ajax.php?action=bidx_signin'
                        });
                    });
                </script>
            </div>

            <!-- FORGOT PASSWORD -->
            <div class="mainState mainStateResetpassword" style="display:none">
                <form id="frmResetpassword" action="/">
                    <div class="formfield" data-validation='{"required":{"text":"This fields is mandatory"},"typecheck":[{"email":{"text":"This is not a valid e-mail address"}}]}'>
                        <label>Email address</label>
                        <input type="text" name="username" placeholder="Type your email address" />
                    </div>

                    <div class="buttonwrapper">
                        <a href="#" class="btn btn-primary jsResetpassword">Send me a new password</a>
                    </div>

                    <p>
                        Did you remember your password again?.<br/>
                        Click <a href="#login">here</a> to go to login.
                    </p>
                </form>

                <div class="resetpasswordSuccess hide">
                    <h3>E-mail has been send</h3>
                    <p>Password reset e-mail has been send <br>
                        A password reset link has been send to you. Please check your inbox and click on the link within the e-mail to reset your password.
                        <br/>
                        Click <a href="/">here</a> to go to homepage.
                    </p>
                </div>

            </div>
            <!-- REGISTER -->
            <?php $this->render ('registration.phtml'); ?>

            <script>
                window.bidx = window.bidx || {};
                window.bidx.api = {
                    settings: {
                        servicesPath: '/wp-content/plugins/bidx-plugin/static/js/bidxAPI/services/'
                    }
                };
                $(function() {
                    /* Forgot Password */
                    var $stateResetpassword = $(".mainStateResetpassword")
                            , $frmResetpassword = $("#frmResetpassword")
                            , $btnResetpassword = $frmResetpassword.find(".jsResetpassword")

                            ;

                    $btnResetpassword.click(function(e)
                    {
                        e.preventDefault();

                        $frmResetpassword.submit();
                    });

                    $frmResetpassword.submit(function(e)
                    {
                        e.preventDefault();


                        if ($btnResetpassword.hasClass("disabled"))
                        {
                            return;
                        }

                        $btnResetpassword.addClass("disabled");

                        // Build up the data for the member request
                        //
                        var resetpass =
                                {
                                    username: $frmResetpassword.find("[name='username']").val()

                                };


                        bidx.api.call(
                                "resetpassword.save"
                                , {
                            groupDomain: bidx.common.groupDomain
                                    , data: resetpass
                                    , success: function(response)
                            {
                                bidx.utils.log("resetpassword.save::success::response", response);

                                // Go to group dashboard
                                //

                                $frmResetpassword.hide();
                                $stateResetpassword.find(".resetpasswordSuccess").removeClass("hide");

                                //		                    window.location.href = url;
                            }
                            , error: function(jqXhr)
                            {
                                alert(JSON.stringify(jqXhr));
                                $btnResetpassword.removeClass("disabled");

                                alert("Problem while reseting the password");
                            }
                        }
                        );

                    });
                });

            </script>


            <script src="https://maps.googleapis.com/maps/api/js?v=3&sensor=false&libraries=places"></script>
        </div>
    </div>
</div>
