<div id="entrepreneur-dashboard" class="box-border top-margin-lineheight">
    <div class="clearfix bg-primary-light main-padding">
        <h1 class="text-center bidx-page-heading"><?php _e('My entrepreneur dashboard','bidxplugin');?></h1>
    </div>
    <div class="dashboard">
        <div class="view viewError alert alert-warning main-margin">
            <h1><?php _e('Error','bidxplugin')?></h1>
            <span class="errorMsg"></span>
        </div>
        <div class="row tabs-vertical main-padding">
            <div class="col-sm-3 tabs-nav">
                <!-- Nav tabs -->
                <ul class="nav nav-tabs tabs-left">
                    <li class="active"><a href="#tab-businesses" data-toggle="tab"><?php _e('My business plan','bidxplugin');?></a></li>
                    <li><a href="#tab-companies" data-toggle="tab"><?php _e('My Companies','bidxplugin');?></a></li>
                    <li><a href="#tab-groups" data-toggle="tab"><?php _e('Joined Portals','bidxplugin');?></a></li>
                </ul>
            </div>
            <div class="col-sm-9 tabs-content">
                <div class="tab-content">
                    <div class="tab-pane active" id="tab-businesses">
                        <div class="view viewLoad alert alert-info text-center">
                            <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e('Loading', 'bidxplugin') ?>
                        </div>
                    </div>

                    <div class="tab-pane" id="tab-companies">
                        <div class="view viewLoadcompanies alert alert-info text-center">
                            <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e('Loading', 'bidxplugin') ?>
                        </div>
                    </div>

                    <div class="tab-pane" id="tab-groups">
                        <div class="view viewLoadGroups alert alert-info text-center">
                            <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e('Loading', 'bidxplugin') ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/html" id="entrepreneur-investorsitem">
    <!--

    <div class="cardView">
        <div class="cardHeader hide-overflow">
            <div class="info-cell pull-left"><?php echo _e( 'Completed', 'bidxplugin' ); ?>: %completionMess%</div>
            <div class="info-cell pull-left"><?php echo _e( 'Finance Needed', 'bidxplugin' ); ?>: %financingNeeded%</div>
            <a href="/businesssummary/%bidxEntityId%" class="btn btn-primary btn-xs pull-right info-action main-margin-half"><?php echo _e( 'View Business', 'bidxplugin' ); ?> </a>
        </div>
        <div class="cardContent main-padding">
            <div class="cardTop">
                <div class="row">
                    <div class="col-sm-3">
                        <a class="pull-left main-margin-half" href="/businesssummary/%bidxEntityId%" data-role='businessImage'>
                            <div class="icons-rounded"><i class="fa fa-suitcase text-primary-light"></i></div>
                        </a>
                    </div>
                    <div class="col-sm-9">
                        <h3 class="top-0">%name%</h3>
                        <h4><span class="bs-slogan">%slogan%</span></h4>
                        <table class="table table-condensed table-bottom-border">
                            <tbody>
                                <tr><td><?php echo _e( 'Business stage', 'bidxplugin' ); ?></td><td>%stageBusiness%</td></tr>
                                <tr><td><?php echo _e( 'Year sales started', 'bidxplugin' ); ?></td><td>%yearSalesStarted%</td></tr>
                                <tr><td><?php echo _e( 'Industry', 'bidxplugin' ); ?></td><td>%industry%</td></tr>
                                <tr><td><?php echo _e( 'Country of business', 'bidxplugin' ); ?></td><td>%countryOperation%</td></tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="cardFooter">
            <div class="alert alert-info hide-overflow">
                <div class="pull-left">
                    <?php _e('Interested investor','bidxplugin')?>: <a href="/member/%investorId%">%displayName%</a>
                </div>
                <div class="pull-right">
                    <span class="info-cell pull-left bg-%status%"><?php echo _e( 'Status', 'bidxplugin' ); ?>: %status%</span>
                    <span class="btn-%bidxEntityId%-%investorId%">
                        <button type="button" data-btn="accept" class="grantAccess btn btn-xs btn-success" data-summaryid="%bidxEntityId%" data-investorid="%investorId%"><?php _e('Accept','bidxplugin')?></button>
                        <button type="button" data-btn="reject" class="grantAccess btn btn-xs btn-danger" data-summaryid="%bidxEntityId%" data-investorid="%investorId%" ><?php _e('Reject','bidxplugin')?></button>
                    </span>
                    <a href="/mail#mail/compose/recipients=%investorId%" class ="btn btn-xs btn-info" title="Send a message" target="_blank"><?php _e('Contact','bidxplugin')?></a>
                </div>
            </div>
        </div>
    </div>

    -->
</script>

<script type="text/html" id="entrepreneur-businessitem">
    <!--

    <div class="cardView">
        <div class="cardHeader hide-overflow">
            <div class="info-cell pull-left"><?php echo _e( 'Completed', 'bidxplugin' ); ?>: %completeness%%</div>
            <div class="info-cell pull-left"><?php echo _e( 'Finance Needed', 'bidxplugin' ); ?>: %financingNeeded%</div>
            <a href="/businesssummary/%bidxEntityId%" class="btn btn-primary btn-xs pull-right info-action main-margin-half"><?php echo _e( 'View Business', 'bidxplugin' ); ?> </a>
        </div>
        <div class="cardContent main-padding">
            <div class="cardTop">
                <div class="row">
                    <div class="col-sm-3">
                        <a class="pull-left main-margin-half" href="/businesssummary/%bidxEntityId%" data-role='businessImage'>
                            <div class="icons-rounded"><i class="fa fa-suitcase text-primary-light"></i></div>
                        </a>
                    </div>

                    <div class="col-sm-9">
                        <h3 class="top-0">%name%</h3>
                        <h4><span class="bs-slogan">%slogan%</span></h4>
                        <table class="table table-condensed table-bottom-border">
                            <tbody>
                                <tr><td><?php echo _e( 'Business stage', 'bidxplugin' ); ?></td><td>%stageBusiness%</td></tr>
                                <tr><td><?php echo _e( 'Year sales started', 'bidxplugin' ); ?></td><td>%yearSalesStarted%</td></tr>
                                <tr><td><?php echo _e( 'Industry', 'bidxplugin' ); ?></td><td>%industry%</td></tr>
                                <tr><td><?php echo _e( 'Country of business', 'bidxplugin' ); ?></td><td>%countryOperation%</td></tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="cardFooter">

        </div>
    </div>
    -->
</script>
<script type="text/html" id="empty-message">
<!--
<div class="alert alert-sm hide-overflow bg-Requested">
 %msg%
 <a href="%btnLink%" class="btn btn-xs btn-primary pull-right"><span class="fa fa-plus"></span>%btnMsg%</a>
</div>

-->
</script>

<script type="text/html" id="entrepreneur-mentorsitem">
     <!--
    <div class="cardView">
        <div class="cardHeader hide-overflow">
            <div class="info-cell pull-left bg-%status%"><?php echo _e( 'Status', 'bidxplugin' ); ?>: %status%</div>
            <div class="info-cell pull-left"><?php echo _e( 'Finance Needed', 'bidxplugin' ); ?>: %financingNeeded%</div>
            <a href="/businesssummary/%entityId%" class="btn btn-primary btn-xs pull-right info-action main-margin-half"><?php echo _e( 'View Business', 'bidxplugin' ); ?> </a>
        </div>
        <div class="cardContent main-padding">
            <div class="cardTop">
                <div class="row">
                    <div class="col-sm-3">
                        <a class="pull-left main-margin-half" href="/businesssummary/%entityId%" data-role='businessImage'>
                            <div class="icons-rounded"><i class="fa fa-suitcase text-primary-light"></i></div>
                        </a>
                    </div>
                    <div class="col-sm-9">
                        <h3 class="top-0">%name%</h3>
                        <h4><span class="bs-slogan">%slogan%</span></h4>
                        <table class="table table-condensed table-bottom-border">
                            <tbody>
                                <tr><td><?php echo _e( 'Business stage', 'bidxplugin' ); ?></td><td>%stageBusiness%</td></tr>
                                <tr><td><?php echo _e( 'Year sales started', 'bidxplugin' ); ?></td><td>%yearSalesStarted%</td></tr>
                                <tr><td><?php echo _e( 'Industry', 'bidxplugin' ); ?></td><td>%industry%</td></tr>
                                <tr><td><?php echo _e( 'Country of business', 'bidxplugin' ); ?></td><td>%countryOperation%</td></tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="cardFooter">
            <div class="alert bg-%status% hide-overflow">
                <div class="pull-left">
                    %statusMessage% <a href="/member/%creatorId%">%creator%</a>
                </div>
                <div class="pull-right">
                    <span class="entrepreneur-respond-action">
                        <a href="#" data-href="<?php echo _l('mentor-dashboard')?>/#mentoring/confirmRequest/requestId=%requestId%&type=mentor&action=accepted" class="btn-bidx-accept btn btn-xs btn-success"><?php _e('Accept','bidxplugin');?></a>
                        <a href="#" data-href="<?php echo _l('mentor-dashboard')?>/#mentoring/confirmRequest/requestId=%requestId%&type=mentor&action=rejected" class="btn-bidx-ignore btn btn-xs btn-danger"><?php _e('Ignore','bidxplugin');?></a>
                        <a href="#" data-href="<?php echo _l('mail')?>/#mail/compose/recipients=%receipientId%" target="_blank" class="btn-bidx-contact hide btn btn-xs btn-info"><?php _e('Contact mentor','bidxplugin');?></a>
                    </span>
                    <span class="entrepreneur-wait-action">
                        <a href="#" data-href="<?php echo _l('mail')?>/#mail/compose/recipients=%receipientId%" class="btn-bidx-reminder btn btn-xs btn-primary"><?php _e('Send a reminder','bidxplugin');?></a>
                        <a href="#" data-href="<?php echo _l('mail')?>/#mail/compose/recipients=%receipientId%" target="_blank" class="btn-bidx-contact hide btn btn-xs btn-info"><?php _e('Contact mentor','bidxplugin');?></a>
                        <a href="#" data-href="<?php echo _l('mentor-dashboard')?>/#mentoring/confirmRequest/requestId=%requestId%&type=mentor&action=cancel" class="btn-bidx-cancel btn btn-xs btn-danger"><?php _e('Cancel request','bidxplugin');?></a>
                    </span>
                    <span class="entrepreneur-ongoing-action">
                        <a href="#" data-href="<?php echo _l('mail')?>/#mail/compose/recipients=%receipientId%" target="_blank" class="btn-bidx-contact hide btn btn-xs btn-info"><?php _e('Contact mentor','bidxplugin');?></a>
                        <a href="#" data-href="<?php echo _l('mentor-dashboard')?>/#mentoring/confirmRequest/requestId=%requestId%&type=mentor&action=cancel" class="btn-bidx-stop btn btn-xs btn-danger"><?php _e('Stop mentoring','bidxplugin');?></a>
                    </span>
                </div>
            </div>
        </div>
    </div>
</script>
