<div id="entrepreneur-dashboard">
    <h1>Entrepreneur dashboard</h1>
    <section class="span12 well dashboard">
        <article class="view viewLoad"><?php _e ('Loading...', 'bidxplugin') ?></article>
        <article class="view viewError">
                <h1><?php _e('Error','bidxplugin')?></h1>
                <span class="errorMsg"></span>
            </article>
        <article class="view viewBusiness">
            <div class="row-fluid ">

                <div class="span12 well">
                    <h2>Business</h2>
                    <p>Here you can see the businesses you have created some details about them. If you</p>
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Industry</th>
                                <th>Location</th>
                                <th>Finance needed</th>
                                <th>Completion</th>
                                <th>Status</th>
                                <th>Created date</th>
                            </tr>
                        </thead>
                        <tbody class="business entrepreneur-business">
                        <div class="pull-left">
                            <?php //_e ('Loading...', 'bidxplugin') ?>
                        </div>
                        </tbody>
                    </table>
                </div>
            </div>
        </article>
        <article class="view viewLoadinvestors"><?php _e ('Loading...', 'bidxplugin') ?></article>
        <article class="view viewInvestors">
            <div class="row-fluid">

                <div class="span12 well">
                    <h2>Interested investors</h2>
                    <p></p>
                    <table class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th>Send a message</th>
                                <th>Investor</th>
                                <th>Interested in</th>
                                <th>Location</th>
                                <th>Type of Investor</th>
                                <th>Type of Investment</th>
                                <th>Created Date</th>
                            </tr>
                        </thead>
                        <tbody class="investors entrepreneur-investors ">
                        <div class="pull-left">
                            <?php// _e ('Loading...', 'bidxplugin') ?>
                        </div>
                        </tbody>
                    </table>
                </div>
            </div>
        </article>

</div>
<script type="text/html" id="entrepreneur-investorsitem">
    <!--
    <tr>
        <td>
           <span class="placeholder sendmsg"> %sendmsg% </span>
        </td>
        <td>
           <span class="placeholder name"> %name% </span>
        </td>
        <td>
           <span class="placeholder interestedin"> %interestedin% </span>
        </td>
        <td>
           <span class="placeholder location"> %location% </span>
        </td>
        <td>
           <span class="placeholder typeofinvestor"> %typeofinvestor% </span>
        </td>
        <td>
           <span class="placeholder typeofinvestment"> %typeofinvestment% </span>
        </td>
        <td>
           <span class="placeholder bidxCreationDateTime"> %bidxCreationDateTime% </span>
        </td>
    </tr>
    -->
</script>

<script type="text/html" id="entrepreneur-businessitem">
    <!--
    <tr>
        <td>
           <span class="placeholder name"> %name% </span>
        </td>
        <td>
           <span class="placeholder industry"> %industry% </span>
        </td>
        <td>
           <span class="placeholder countryOperation"> %countryOperation% </span>
        </td>
        <td>
           <span class="placeholder financingNeeded"> %financingNeeded% </span>
        </td>
        <td>
           <span class="placeholder completion"> %completion% </span>
        </td>
        <td>
           <span class="placeholder stageBusiness"> %stageBusiness% </span>
        </td>
        <td>
           <span class="placeholder bidxCreationDateTime"> %bidxCreationDateTime% </span>
        </td>
    </tr>
    -->
</script>
<script type="text/html" id="entrepreneur-empty">
<!--
<tr class="business entrepreneur-business" >
    <div class="pull-left">
    <?php _e ('No businesses available', 'bidxplugin') ?>
    </div>
</tr>
-->
</script>

<script type="text/html" id="entrepreneur-listitem">
    <!--
    <td colspan="5" class="detailRow">
    <div class="accordian-body collapse" id="table1-row1-col2">
    <div class="row-fluid">
    <div class="span12">
    <h4>Entrepreneur Profile</h4>
    <ul class="unstyled">
    <li>
    <label>Entrepreneur</label>
    <span class="placeholder ename"/>
    </li>
    <li>
    <label>Industry</label>
    <span class="placeholder eindustry"/>
    </li>
    <li>
    <label>Product</label>
    <span class="placeholder eproduct"/>
    </li>
    <li>
    <label>Country</label>
    <span class="placeholder ecountry"/>
    </li>
    <li>
    <label>Investment needed</label>
    <span class="placeholder eamount"/>
    </li>
    <li>
    <label>Business stage</label>
    <span class="placeholder estage"/>
    </li>
    <li>
    <label>Impact</label>
    <span class="placeholder eimpact"/>
    </li>
    </ul>
    </div>

    <div class="pull-right">
    <a href="#">View full profile</a>
    </div>
    </div>
    </div>
    </td>
    -->
</script>


