<div id="entrepreneur-dashboard">
    <div>
        <h1 class="pagetitle">My entrepreneur dashboard</h1>
        <div class="row dashboard">

            <div class="view viewError alert alert-warning">
                <h1><?php _e('Error','bidxplugin')?></h1>
                <span class="errorMsg"></span>
            </div>

            <div id="entrepreneurDashboardAccordion">
                <!-- Help -->
                <div class="view viewLoad alert alert-info text-center">
                    <div class="progress progress-striped active">
                      <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                        <?php _e ('Loading businesses ...', 'bidxplugin') ?>
                    </div>
                </div>
                </div>
                <div class="view viewLoadinvestors alert alert-info text-center">
                    <div class="progress progress-striped active">
                        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                            <?php _e ('Loading investors ...', 'bidxplugin') ?>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default <?php echo ($this->startingPage) ? 'panel-open': '';?>">
                    <div class="panel-heading">
                        <a class="btn-block" data-toggle="collapse" data-parent="#entrepreneurDashboardAccordion" href="#entrepreneurDashboardAccordion-Help"><span class="fa fa-chevron-right accordion-state-icon"></span> <?php _e('Help','bidxplugin'); ?></a>
                    </div>
                    <div id="entrepreneurDashboardAccordion-Help" class="panel-collapse collapse <?php echo ($this->startingPage) ? 'in': '';?>">
                        <div class="panel-body">
                           <?php $this->render('entrepreneur/help.phtml'); ?>
                        </div>
                   </div>
                </div>


                <div class="panel panel-default panel-open view viewBusiness">
                    <div class="panel-heading">
                        <a class="btn-block" data-toggle="collapse" data-parent="#entrepreneurDashboardAccordion" href="#entrepreneurDashboardAccordion-Business"><span class="fa fa-chevron-right accordion-state-icon"></span> Business</a>
                    </div>
                    <div id="entrepreneurDashboardAccordion-Business" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <p>Here you can see the businesses you have created some details about them.</p>
                            <table class="table table-striped table-hover">
                                <thead>
                                    <tr>
                                        <th>Title</th>
                                        <th>Industry</th>
                                        <th class="hidden-xs">Location</th>
                                        <th class="hidden-xs">Finance needed</th>
                                        <th class="hidden-xs">Year sales started</th>
                                        <th class="hidden-xs">Status</th>
                                        <th class="hidden-xs">Last update</th>
                                    </tr>
                                </thead>
                                <tbody class="business entrepreneur-business">
                                    <div class="pull-left">
                                        <?php //_e ('Loading...', 'bidxplugin') ?>
                                    </div>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>


                <div class="panel panel-default view viewInvestors">
                    <div class="panel-heading">
                        <a class="btn-block" data-toggle="collapse" data-parent="#entrepreneurDashboardAccordion" href="#entrepreneurDashboardAccordion-Investors"><span class="fa fa-chevron-right accordion-state-icon"></span> Interested investors</a>
                    </div>
                    <div id="entrepreneurDashboardAccordion-Investors" class="panel-collapse collapse">
                        <div class="panel-body">
                            <p></p>
                            <table class="table table-striped table-hover">
                                <thead>
                                    <tr>
                                        <th>Send a message</th>
                                        <th>Investor</th>
                                        <th>Interested in</th>
                                        <th class="hidden-xs">Location</th>
                                        <th class="hidden-xs">Type of Investor</th>
                                        <th class="hidden-xs">Type of Investment</th>
                                        <th class="hidden-xs">Request status</th>
                                        <th class="hidden-xs">Last time viewed plan</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody class="investors entrepreneur-investors">
                                    <div class="pull-left">
                                        <?php// _e ('Loading...', 'bidxplugin') ?>
                                    </div>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/html" id="entrepreneur-investorsitem">
    <!--
<tr>
    <td>
        <a href="/mail#mail/compose/recipients=%investorId%" class ="bidx-mail" title="Send a message" target="_blank">
         </a>
    </td>
    <td>
        <span class="placeholder displayName">
            <a href="/member/%investorId%">%displayName%</a>
        </span>
    </td>
    <td>
      <a data-toggle="collapse" data-target="#investor-%accordion-id%" class="btn-block">
      <span class="placeholder name">%name%</span>
      </a>
   </td>

    <td class="hidden-xs">
        <span class="placeholder countryOperation">%countryOperation%</span>
    </td>
    <td class="hidden-xs">
        <span class="placeholder investorType">%investorType%</span>
    </td>
    <td class="hidden-xs">
        <span class="placeholder investmentType">%investmentType%</span>
    </td>

    <td class="hidden-xs">
        <span class="placeholder status">%status%</span>
        </a>
    </td>
    <td class="hidden-xs">
        <span class="placeholder bidxLastUpdateDateTime">%bidxLastUpdateDateTime%</span>
    </td>
    <td class="controlbuttons">
        <div class="btn-%bidxEntityId%-%investorId%">
            <button type="button" data-btn="accept" class="grantAccess btn btn-success" data-summaryid="%bidxEntityId%" data-investorid="%investorId%">Accept</button>
            <button type="button" data-btn="reject" class="grantAccess btn btn-danger" data-summaryid="%bidxEntityId%" data-investorid="%investorId%" >Reject</button>
        </div>
    </td>

</tr>
<tr class="list detail-list" >
    <td colspan="9" class="detailRow">
        <div class="panel-collapse collapse" id="investor-%accordion-id%">
            <div class="row">
                <div class="col-sm-2">
                    <span class="placeholder js-document document"><img src="%document%"/></span>
                </div>
                <div class="col-sm-10">
                    <div class="row">
                        <div class="col-sm-6">
                            <label>Business proposal</label>
                            <span class="placeholder name"> %name% </span>
                        </div>
                        <div class="col-sm-6">
                             <label>Slogan</label>
                             <span class="placeholder slogan"> %slogan% </span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <label>Summary</label>
                            <span class="placeholder summary"> %summary% </span>
                        </div>
                        <div class="col-sm-6">
                            <label>Reason for submission</label>
                            <span class="placeholder reasonForSubmission"> %reasonForSubmission% </span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <label>Environmental Impact</label>
                            <span class="placeholder envImpact"> %envImpact% </span>
                        </div>
                        <div class="col-sm-6">
                            <label>Country</label>
                            <span class="placeholder countryOperation"> %countryOperation% </span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <label>Business stage</label>
                            <span class="placeholder stageBusiness"> %stageBusiness% </span>
                        </div>
                        <div class="col-sm-6">
                            <label>Consumer type</label>
                            <span class="placeholder consumerType"> %consumerType% </span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <label>Investment type</label>
                            <span class="placeholder investmentType"> %investmentType% </span>
                        </div>
                        <div class="col-sm-6">
                            <label>Finance needed</label>
                            <span class="placeholder financingNeeded"> %financingNeeded% </span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <label>Summary of finance needed</label>
                            <span class="placeholder summaryFinancingNeeded"> %summaryFinancingNeeded% </span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-6">
                            <div class="pull-right">
                                <span class="placeholder bidxEntityId"><a target = "_blank" href="/businesssummary/%bidxEntityId%">View Proposal</a> </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
   </td>
</tr>

    -->
</script>
<script type="text/html" id="entrepreneur-businessitem">
    <!--
    <tr>
        <td>
           <span class="placeholder name"> <a data-toggle="collapse" data-target="#%accordion-id%" class="btn-block">%name%</a> </span>
        </td>
        <td>
           <span class="placeholder industry"> %industry% </span>
        </td>
        <td class="hidden-xs">
           <span class="placeholder countryOperation"> %countryOperation% </span>
        </td>
        <td class="hidden-xs">
           <span class="placeholder financingNeeded"> %financingNeeded% </span>
        </td>
        <td class="hidden-xs">
           <span class="placeholder yearSalesStarted"> %yearSalesStarted% </span>
        </td>
        <td class="hidden-xs">
           <span class="placeholder stageBusiness"> %stageBusiness% </span>
        </td>
        <td class="hidden-xs">
           <span class="placeholder bidxLastUpdateDateTime"> %bidxLastUpdateDateTime% </span>
        </td>
    </tr>
    <tr class="list detail-list" >
        <td colspan="7" class="detailRow">
            <div class="panel-collapse collapse" id="%accordion-id%">
                <div class="row">
                    <div class="col-sm-2">
                        <span class="placeholder js-document document"> %documentIcon% </span>
                    </div>
                    <div class="col-sm-10">
                        <div class="row">
                            <div class="col-sm-6">
                                <label>Business proposal</label>
                                <div class="placeholder name"> %name% </div>
                            </div>
                            <div class="col-sm-6">
                                 <label>Slogan</label>
                                 <div class="placeholder slogan"> %slogan% </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <label>Summary</label>
                                <div class="placeholder summary"> %summary% </div>
                            </div>
                            <div class="col-sm-6">
                                <label>Reason for submission</label>
                                <div class="placeholder reasonForSubmission"> %reasonForSubmission% </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <label>Environmental Impact</label>
                                <div class="placeholder envImpact"> %envImpact% </div>
                            </div>
                            <div class="col-sm-6">
                                <label>Country</label>
                                <div class="placeholder countryOperation"> %countryOperation% </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <label>Business stage</label>
                                <div class="placeholder stageBusiness"> %stageBusiness% </div>
                            </div>
                            <div class="col-sm-6">
                                <label>Consumer type</label>
                                <div class="placeholder consumerType"> %consumerType% </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">
                                <label>Investment type</label>
                                <div class="placeholder investmentType"> %investmentType% </div>
                            </div>
                            <div class="col-sm-6">
                                <label>Finance needed</label>
                                <div class="placeholder financingNeeded"> %financingNeeded% </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-6">
                                <label>Summary of finance needed</label>
                                <div class="placeholder summaryFinancingNeeded"> %summaryFinancingNeeded% </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6 col-sm-offset-6">
                                <div class="pull-right">
                                    <div class="placeholder bidxEntityId"><a class="btn btn-primary btn-sm" target = "_blank" href="/businesssummary/%bidxEntityId%">View Proposal</a> </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </td>
    </tr>
    -->
</script>
<script type="text/html" id="entrepreneur-empty">
<!--
<tr class="business entrepreneur-business" >
    <td colspan='8'>
        <div class="pull-left">
            <?php _e ('No matches available', 'bidxplugin') ?>
        </div>
    </td>
</tr>
-->
</script>

<script type="text/html" id="entrepreneur-listitem">
    <!--
    <td colspan="5" class="detailRow">
    <div class="panel-collapse collapse" id="table1-row1-col2">
    <div class="row">
    <div class="col-sm-12">
    <h4>Entrepreneur Profile</h4>
    <ul class="list-unstyled">
    <li>
    <label>Entrepreneur</label>
    <span class="placeholder ename"/>
    </li>
    <li>
    <label>Industry</label>
    <span class="placeholder eindustry"/>
    </li>
    <li>
    <label>Product</label>
    <span class="placeholder eproduct"/>
    </li>
    <li>
    <label>Country</label>
    <span class="placeholder ecountry"/>
    </li>
    <li>
    <label>Investment needed</label>
    <span class="placeholder eamount"/>
    </li>
    <li>
    <label>Business stage</label>
    <span class="placeholder estage"/>
    </li>
    <li>
    <label>Impact</label>
    <span class="placeholder eimpact"/>
    </li>
    </ul>
    </div>

    <div class="pull-right">
    <a href="#">View full profile</a>
    </div>
    </div>
    </div>
    </td>
    -->
</script>


