<?php $http = (is_ssl()) ? 'https://':'http://'; ?>

<div id="searchHome" class="top-margin-lineheight">


    <div class="row">
         <section class="views">
            <div class="col-sm-8">
                <div class="searchcontrol bg-primary-darker">
                    <div class="search">
                        <form action="" class="searchform">
                            <div class="input-group">
                                <input type="text" class="form-control form-q" name="q" placeholder="<?php _e("Search","bidxplugin");?>" value="">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="submit">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                </div>

               <!-- BusinessSummaries VIEW -->
                <article class="view viewSearchList">
                    <div class="view viewPager">
                        <div class="pagerContainer">
                            <div class="row">
                                <div class="col-sm-2 pagerTotal"></div>
                                <div class="col-sm-10">
                                    <ul class="pager pull-left"></ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="view viewSort">
                       <div class="media-list sort-list">
                            <?php _e('Rendering sort...', 'bidxplugin');?>
                        </div>
                    </div>

                     <ul class="media-list search-list">
                        <!-- Results will be loaded here through js -->
                    </ul>

                    <div class="view viewLoad alert alert-info text-center">
                        <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e("Loading search results, please wait...", "bidxplugin");?>
                    </div>
                    <div class="view viewPager">
                        <div class="pagerContainer">
                            <div class="row">
                                <div class="col-sm-2 pagerTotal"></div>
                                <div class="col-sm-10">
                                    <ul class="pager pull-left"></ul>
                                </div>
                            </div>
                        </div>
                    </div>

                </article>

                <!-- ERROR -->
                <div class="view viewError alert alert-warning">
                    <p class="errorMsg"></p>
                </div>

            </div>
            <div class="col-sm-4">
                <div class="side-bar well sideBar main-facet">
                    <article class="viewFacet">
                        <div class="facet-reset hide">
                            <a data-filter="reset" class="anchor-reset btn btn-block btn-danger"><?php _e("Clear all filters", "bidxplugin");?></a>
                        </div>
                         <div class="facet-list">

                            <?php _e('Rendering facets...', 'bidxplugin');?>
                         </div>
                    </article>
                </div>
            </div>
        </section>
    </div>

        <!-- Html Templates for Facet Category -->
        <script type="text/html" id="facet-listitem">
            <div class="facet-category-%facets_name%">
                <h5 class="facet-title">%facets_name%</h5>
                <div class="list-group"></div>
            </div>
        </script>
        <!-- Html Templates for Category results -->
        <script type="text/html" id="facetsub-listitem">
            <a data-filter="%filterQuery%" class="list-group-item filter">
                <span class="view viewClose"><i class="fa fa-times text-success"></i></span>
                <span class="badge">%facetValues_count%</span>
                %facetValues_name%
            </a>
        </script>

        <!-- Html Template for Sort -->
        <script type="text/html" id="sort-listitem">
            <div class="row">
                <div class="col-sm-2">
                    <h5><?php _e('Sort by:', 'bidxplugin');?></h5>
                </div>
                <div class="col-sm-2 hide">
                    <h6><a data-type='relevance' data-order = '%relevance%' class="sort relevance btn-link"><?php _e('Relevance', 'bidxplugin');?></a></h6>
                </div>
                <div class="col-sm-2 hide">
                    <h6><a data-type='country'  data-order = '%country%' class="sort country btn-link"><?php _e('Country', 'bidxplugin');?></a></h6>
                </div>
                <div class="col-sm-2 hide">
                    <h6><a data-type='industry' data-order = '%industry%' class="sort industry btn-link"><?php _e('Industry', 'bidxplugin');?></a></h6>
                </div>
                <div class="col-sm-4">
                    <h6><a data-type='entityId' data-order = '%entityId%' class="sort entityId btn-link"><?php _e('Date', 'bidxplugin');?></a></h6>
                </div>
            </div>
        </script>


        <!-- 1. businessSummary Snippet -->
        <script type="text/html" id="businesssummary-listitem">
             <!--
            <li class="media well">

            <div class="row">
                <div class="col-sm-3">
                    <a class="pull-left" href="<?php echo _l('businesssummary');?>/%entityId%" data-role='businessImage'>
                        <div class="icons-rounded pull-left"><i class="fa fa-suitcase text-primary-light"></i></div>
                    </a>
                </div>
                <div class="col-sm-9">
                    <div class="row">
                        <div class="col-sm-6">
                            <a href="<?php echo _l('businesssummary');?>/%entityId%">
                                <h4>%name%</h4>
                            </a>
                        </div>
                        <div class="col-sm-4">
                            <div "row view viewLastupdate pull-right">%bidxLastUpdateDateTime%</div>
                        </div>

                        <div class="col-sm-2">
                                <a href="<?php echo _l('businesssummary');?>/%entityId%" class="btn btn-xs btn-warning pull-right"><?php _e('View','bidxplugin')?></a>
                        </div>
                    </div>
                    <div class="row view viewSummary">
                        <div class="col-sm-12">
                            <div>%summary%</div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12"> <hr> </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-sm-6 view viewIndustry">
                            <label><?php _e('Industry','bidxplugin');?></label>
                            <div>%industry%</div>
                        </div>
                        <div class="col-sm-6 view viewFinance">
                            <label><?php _e('Finance needed','bidxplugin');?></label>
                            <div>%financingNeeded%</div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6 view viewReason">
                            <label><?php _e('Reason for submission','bidxplugin');?></label>
                            <div>%reasonForSubmission%</div>
                        </div>
                        <div class="col-sm-6 view viewCountry">
                            <label><?php _e('Country of business', 'bidxplugin');?></label>
                            <div>%countryOperation%</div>
                        </div>
                    </div>
                </div>
            </div>
            </li>
            -->
        </script>

        <!-- 2. Company Snippet -->
        <script type="text/html" id="company-listitem">
             <!--
            <li class="media well">

            <div class="row">
                <div class="col-sm-3">
                    <a class="pull-left" href="<?php echo _l('company');?>/%entityId%" data-role='companyImage'>
                        <div class="icons-rounded pull-left"><i class="fa fa-building text-primary-light"></i></div>
                    </a>
                </div>
                <div class="col-sm-9">
                    <div class="row">
                        <div class="col-sm-6">
                            <a href="<?php echo _l('businesssummary');?>/%entityId%">
                                <h4>%name%</h4>
                            </a>
                        </div>
                        <div class="col-sm-6">
                                <span class="label bidx-label bidx-mentor ">%registered%</span>
                                <a href="<?php echo _l('company');?>/%entityId%" class="btn btn-xs btn-warning pull-right"><?php _e('View','bidxplugin')?></a>
                        </div>
                    </div>
                    <div class="row view viewWebsite">
                        <div class="col-sm-12">
                            <div>%website%</div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12"> <hr> </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="view viewCityTown">
                                <label><?php _e('City','bidxplugin');?></label>
                                <div>%cityTown%</div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="view viewCountry">
                                <label><?php _e('Country','bidxplugin');?></label>
                                <div>%country%</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </li>
            -->
        </script>

        <!-- 3. Memberprofile Snippet -->
        <script type="text/html" id="member-profile-listitem">
            <!--
            <li class="media well">

            <div class="row">
                <div class="col-sm-3">
                    <a class="pull-left" href="<?php echo _l('member');?>/%memberId%" data-role='memberImage'>
                        <div class="icons-rounded pull-left"><i class="fa %fa-user% text-primary-light"></i></div>
                    </a>
                </div>
                <div class="col-sm-9">
                    <div class="row">
                        <div class="col-sm-7">
                            <a href="<?php echo _l('member');?>/%memberId%">
                                <h4>%firstName% %lastName%</h4>
                            </a>
                        </div>
                        <div class="col-sm-5">
                                <a href="<?php echo _l('mail');?>/#mail/contacts/action=connect&amp;id=%memberId%" class="btn btn-xs btn-warning pull-right"><?php _e('Connect','bidxplugin')?></a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                         %professionalTitle%
                             <span class="label bidx-label bidx-entrepreneur">%role_entrepreneur%</span>
                             <span class="label bidx-label bidx-mentor">%role_mentor%</span>
                             <span class="label bidx-label bidx-investor">%role_investor%</span>
                         </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12"> <hr> </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5">
                            <div>%gender%</div>
                            <div>%motherLanguage%</div>
                        </div>
                        <div class="col-sm-7">
                            <div class="hide"> %dateOfBirth% </div>
                            <div> %highestEducation% </div>
                            <div> %language% </div>
                            <div> %city%%country% </div>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-sm-12">
                            <div>%interest%</div>
                        </div>
                    </div>

                    <div class="row hide">
                        <div class="col-sm-8">
                            <div class="row view viewEmailAddress">
                                <div class="col-sm-3">
                                    <div class="label label-info btn-block text-center"> E-mail </div>
                                </div>
                                <div class="col-sm-8 col-sm-offset-1">
                                    <div> %emailAddress% </div>
                                </div>
                            </div>
                            <div class="row view viewMobile">
                                <div class="col-sm-3">
                                    <div class="label label-info btn-block text-center"> Mobile </div>
                                </div>
                                <div class="col-sm-8 col-sm-offset-1">
                                    <div> %mobile% </div>
                                </div>
                            </div>
                            <div class="row view viewLandline">
                                <div class="col-sm-3">
                                    <div class="label label-info btn-block text-center"> Landline </div>
                                </div>
                                <div class="col-sm-8 col-sm-offset-1">
                                    <div> %landLine% </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-4 member-social">
                            <div class="row">
                                <div class="pull-left view viewFacebook">
                                    <div class="facebook">
                                        <a title="View my Facebook Profile" target="_blank" href="http://www.facebook.com/%facebook%"><i class="fa fa-facebook-square"></i></a>
                                    </div>
                                </div>
                                <div class="pull-left view viewTwitter">
                                    <div class="twitter"> <a title="View my Twitter Profile" target="_blank" href="https://twitter.com/%twitter%"><i class="fa fa-twitter-square"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </li>
            -->
        </script>
        <!-- 4. Business group snippet -->
        <script type="text/html" id="group-listitem">
             <!--
            <li class="media well">

            <div class="row">
                <div class="col-sm-3">
                    <a class="pull-left" target="_blank" href="<?php echo $http.'%bidxWebsiteName%.'.DOMAIN_CURRENT_SITE;?>" data-role='groupImage'>
                        <div class="icons-rounded pull-left"><i class="fa fa-group text-primary-light"></i></div>
                    </a>
                </div>
                <div class="col-sm-9">
                    <div class="row">
                        <div class="col-sm-6">
                            <a href="<?php echo $http.'%bidxWebsiteName%.'.DOMAIN_CURRENT_SITE;?>">
                                <h4>%name%</h4>
                            </a>
                        </div>
                        <div class="col-sm-4">
                            <div "row view viewLastupdate pull-right">%bidxLastUpdateDateTime%</div>
                        </div>

                        <div class="col-sm-2">
                                <a target="_blank" href="<?php echo $http.'%bidxWebsiteName%.'.DOMAIN_CURRENT_SITE;?>" class="btn btn-xs btn-warning pull-right"><?php _e('View','bidxplugin')?></a>
                        </div>
                    </div>
                    <div class="row view viewWebsite">
                        <div class="col-sm-12">
                            <div>%website%</div>
                        </div>
                    </div>
                    <div class="row view viewSummary">
                        <div class="col-sm-12">
                            <div>%summary%</div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12"> <hr> </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-sm-6 view viewFocusIndustry">
                            <label><?php _e('Focus industry','bidxplugin');?></label>
                            <div>%focusIndustry%</div>
                        </div>
                        <div class="col-sm-6 view viewFocusSocialImpact">
                            <label><?php _e('Focus social impact','bidxplugin');?></label>
                            <div>%focusSocialImpact%</div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6 view viewFocusEnvImpact">
                            <label><?php _e('Focus environmental impact','bidxplugin');?></label>
                            <div>%focusEnvImpact%</div>
                        </div>
                        <div class="col-sm-6 view viewFocusCountry">
                            <label><?php _e('Focus Country', 'bidxplugin');?></label>
                            <div>%focusCountry%</div>
                        </div>
                    </div>
                </div>
            </div>
            </li>
            -->
        </script>

        <!-- 5. Empy resultset Snippet -->
        <script type="text/html" id="search-empty">
            <!--
            <li class="media">
                <div class="pull-left check"></div>
                <div class="alert alert-warning">
                    <?php _e('No search results available','bidxplugin')?>
                </div>
            </li>
            -->
        </script>

        <!-- 6. Result not loaded through js Snippet -->
        <script type="text/html" id="error-listitem">
            <li class="media well">
                <div class="row">
                    <div class="col-sm-12">
                        <?php _e('Problem loading the result','bidxplugin'); ?>
                    </div>
                </div>
            </li>
         </script>
</div>
