<?php $http = (is_ssl()) ? 'https://':'http://'; ?>

<div id="searchHome" class="top-margin-lineheight">


    <div class="row">
         <section class="views">
            <div class="col-sm-4">
                <div class="side-bar well sideBar main-facet">
                    <article class="viewFacet">
                        <div class="facet-reset">
                            <a data-filter="save"  class="anchor-save btn btn-block btn-success"><span class="fa fa-plus"></span> <?php _e('Save this search', 'bidxplugin');?></a>
                            <a data-filter="reset" class="anchor-reset btn btn-block btn-danger"><?php _e("Clear all filters", "bidxplugin");?></a>


                        </div>
                         <div class="facet-list">

                            <?php _e('Rendering facets...', 'bidxplugin');?>
                         </div>
                    </article>
                </div>
            </div>
            <div class="col-sm-8">
                 <div>
                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane fade in active" id="home">
                            <div class="searchcontrol bg-primary-darker">
                                <div class="search">
                                    <form action="" class="searchform">
                                        <div class="input-group">
                                            <input type="text" class="form-control form-q" name="q" placeholder="<?php _e("Search","bidxplugin");?>" value="">
                                            <span class="input-group-btn">
                                                <button class="btn btn-default" type="submit">
                                                    <i class="fa fa-search"></i>
                                                </button>
                                            </span>
                                        </div>
                                    </form>
                                </div>
                            </div>

                           <!-- BusinessSummaries VIEW -->
                            <article class="view viewSearchList">
                                <div class="view viewPager" >
                                    <div class="pagerContainer">
                                        <div class="row bulkAction">
                                            <div class="col-sm-2 col-sm-offset-2">
                                                    <div class="pagerTotal pull-left"></div>
                                            </div>
                                            <div class="col-sm-8">
                                                    <ul class="pager"></ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="view viewSort">
                                   <div class="media-list sort-list">
                                        <?php _e('Rendering sort...', 'bidxplugin');?>
                                    </div>

                                </div>
                                 <br/>
                                <div class="view viewLoad alert alert-info text-center">
                                    <i class="fa fa-circle-o-notch fa-spin"></i> <?php _e("Loading search results, please wait...", "bidxplugin");?>
                                </div>
                                 <ul class="media-list search-list">
                                    <!-- Results will be loaded here through js -->
                                </ul>
                                <div class="view viewSort">
                                   <div class="media-list sort-list">
                                        <?php _e('Rendering sort...', 'bidxplugin');?>
                                    </div>
                                </div>
                                <div class="view viewPager" >
                                    <div class="pagerContainer">
                                        <div class="row bulkAction">
                                            <div class="col-sm-2 col-sm-offset-2">
                                                    <div class="pagerTotal pull-left"></div>
                                            </div>
                                            <div class="col-sm-8">
                                                    <ul class="pager"></ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </article>

                            <!-- ERROR -->
                            <div class="view viewError alert alert-warning">
                                <p class="errorMsg"></p>
                            </div>

                        </div>
                        <div role="tabpanel" class="tab-pane" id="profile">

                        </div>

                      </div>
                </div>


            </div>

        </section>
    </div>

    <?php $this->render('../../mail/templates/compose.phtml'); ?>


         <!-- Html Templates for Facet Category -->
        <script type="text/html" id="facet-type">
            <div class="facet-category-Type">
                <h5 class="facet-title">Type</h5>
                <div class="list-group"><a data-filter="facet_entityType:bidxMemberProfile" class="list-group-item filter">
                <span class="view viewClose"><i class="fa fa-times text-success"></i></span>
                <span class="badge">25</span>
                Member profile
            </a><a data-filter="facet_entityType:bidxBusinessSummary" class="list-group-item filter">
                <span class="view viewClose"><i class="fa fa-times text-success"></i></span>
                <span class="badge">3</span>
                Business summary
            </a><a data-filter="facet_entityType:bidxMentorProfile" class="list-group-item filter">
                <span class="view viewClose"><i class="fa fa-times text-success"></i></span>
                <span class="badge">1</span>
                Mentor
            </a></div>
            </div>
        </script>

        <!-- Html Templates for Facet Category -->
        <script type="text/html" id="facet-listitem">
            <div class="facet-category-%facets_name%">
                <h5 data-name="%facets_name%" class="facet-title">%facets_title%</h5>
                <div class="list-group"></div>
            </div>
        </script>
        <!-- Html Templates for Category results -->
        <script type="text/html" id="facetsub-listitem">
            <a data-value="%facetValues_name%" data-filter="%filterQuery%" class="list-group-item filter">
                <span class="view viewClose"><i class="fa fa-times text-success"></i></span>
                <span class="badge">%facetValues_count%</span>
                %facets_title%
            </a>
        </script>
        <!-- Html Templates for Range results -->
        <script type="text/html" id="facetrange-listitem"> <!--
            <b>%facets_min%</b>&nbsp;&nbsp;
                <input type="text" id="slider-range-%facetrange%" class="slider-range"></div>&nbsp;&nbsp;
            <b>%facets_max%</b>
        -->
        </script>

        <!-- Html Templates for Category results -->
        <script type="text/html" id="facettop-listitem">
            <div class="search-sm-6">
                <a data-filter="%filterQuery%" class="filter">
                    %facetValues_name%<span class="">(%facetValues_count%)</span>
                    <span class="view viewClose"><i class="fa fa-times text-success"></i></span>
                </a>
            </div>
        </script>

        <!-- Html Template for Sort -->
        <script type="text/html" id="sort-listitem">
            <div class="cardContent main-padding">
                <div class="row">
                    <div class="col-sm-1">
                        <div class="checkbox">
                            <input type="checkbox" value="1" id="selectAll" name="selectAll" />
                            <label for="checkbox-%bidxEntityId%"><span></span></label>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="pull-left">
                            <select name="bulk">
                                <option value=''><?php _e('  --Select Bulk actions--  ', 'bidxplugin')?> </option>
                                <option value='sendEmail'><?php _e('Send email', 'bidxplugin')?> </option>
                                <option class="hide" value='sendRequest'><?php _e('Send request', 'bidxplugin')?> </option>
                            </select>
                        </div>
                        <a data-status="APPLIED" class="btn btn-lg btn-primary btn-apply disabled" name='apply'>Apply</a>
                    </div>
                    <div class="col-sm-3 pull-right">
                        <select name="filterBy" class="hide">
                            <option value=''><?php _e('Default order', 'bidxplugin')?> </option>
                            <option value='latest'><?php _e('Latest registered', 'bidxplugin')?> </option>
                            <option value='completeness'><?php _e('By completeness', 'bidxplugin')?> </option>
                        </select>
                    </div>

                    <div class="col-sm-2 pull-right hide">
                        <a data-type='created' data-order = '%created%' class="sort sorting_%created% created btn-link"><h6><?php _e('Created', 'bidxplugin');?></h6></a>
                    </div>
                    <div class="col-sm-2 hide">
                        <h6><a data-type='relevance' data-order = '%relevance%' class="sort relevance btn-link"><?php _e('Relevance', 'bidxplugin');?></a></h6>
                    </div>
                    <div class="col-sm-2 hide">
                        <h6><a data-type='country'  data-order = '%country%' class="sort country btn-link"><?php _e('Country', 'bidxplugin');?></a></h6>
                    </div>
                    <div class="col-sm-2 hide">
                        <h6><a data-type='industry' data-order = '%industry%' class="sort industry btn-link"><?php _e('Industry', 'bidxplugin');?></a></h6>
                    </div>
                </div>
            </div>
        </script>

        <script type="text/html" id="businesssummary-listitem">
            <!--
            <div class="cardView">
                <div class="cardHeader hide-overflow">
                    <div class="info-cell pull-left"><?php echo _e( 'Completed', 'bidxplugin' ); ?>: %completeness%</div>
                    <div class="info-cell pull-left"><?php echo _e( 'Finance Needed', 'bidxplugin' ); ?>: %financingNeeded%</div>
                    <div class="info-cell pull-left"><?php echo _e( 'Last update', 'bidxplugin' ); ?>: %modified%</div>
                    <a href="/businesssummary/%entityId%" class="btn btn-primary btn-xs pull-right info-action main-margin-half"><?php echo _e( 'View Business', 'bidxplugin' ); ?> </a>
                </div>
                <div class="cardContent main-padding">
                    <div class="cardTop">
                        <div class="row">
                            <div class="col-sm-1">
                                <div class="checkbox">
                                    <input type="checkbox" data-name = "%name%" value="%userId%" id="checkbox_%userId%" name="actionRecord" />
                                    <label for="checkbox-%userId%"><span></span></label>
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <a class="pull-left main-margin-half" href="/businesssummary/%entityId%" data-role='businessImage'>
                                    <div class="icons-rounded"><i class="fa fa-suitcase text-primary-light"></i></div>
                                </a>
                            </div>

                            <div class="col-sm-9">
                                <div class="pull-left searchBTitle">
                                    <h3 class="top-0 pull-left">%title%
                                        <small>&nbsp; <?php _e('by', 'bidxplugin');?>&nbsp;<a href="<?php echo _l('member');?>/%userId%">%name%</a></small>
                                    </h3>
                                    <div class="rating-wrapper pull-right">
                                        <div  class="raty"></div>
                                    </div>
                                </div>
                                <div>
                                    <h4><span class="bs-slogan">%slogan%</span></h4>
                                </div>
                                <table class="table table-condensed table-bottom-border">
                                    <tbody>
                                        <tr class="view viewStageOfBusines"><td><?php _e("Business stage", "bidxplugin");?></td><td>%stageOfBusines%</td></tr>
                                        <tr class="view viewYearSalesStarted"><td><?php _e("Year sales started", "bidxplugin");?></td><td>%yearSalesStarted%</td></tr>
                                        <tr class="view viewIndustry"><td><?php _e("Industry", "bidxplugin");?></td><td>%industry%</td></tr>
                                        <tr class="view viewCountry" ><td><?php _e("Country of business", "bidxplugin");?></td><td>%country%</td></tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="cardFooter">

                </div>
            </div>
            -->
        </script>

        <script type="text/html" id="member-profile-listitem">   <!--
            <div class="cardView">
                <div class="cardHeader hide-overflow">
                    <div class="info-cell pull-left"><?php echo _e( 'Completed', 'bidxplugin' ); ?>: %completionMesh%</div>
                    <div class="info-cell pull-left"><?php echo _e( 'Last update', 'bidxplugin' ); ?>: %modified%</div>
                    <a href="<?php echo _l('member');?>/%userId%" class="btn btn-primary btn-xs pull-right info-action main-margin-half"><?php echo _e( 'View Member', 'bidxplugin' ); ?> </a>
                </div>
                <div class="cardContent main-padding">
                    <div class="cardTop">
                        <div class="row">
                            <div class="col-sm-1">
                                <div class="checkbox">
                                    <input type="checkbox" data-name = "%name%" value="%userId%" id="checkbox-%userId%" name="actionRecord" />
                                    <label for="checkbox-%userId%"><span></span></label>
                                </div>
                            </div>
                            <div class="col-sm-2">
                                <a class="pull-left main-margin-half" href="<?php echo _l('member');?>/%userId%" data-role='memberImage'>
                                    <div class="icons-rounded"><i class="fa fa-user text-primary-light"></i></div>
                                </a>
                            </div>
                            <div class="col-sm-9">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <h3 class="top-0 pull-left">%name%</h3>
                                        <div class="">
                                            <span class="label bidx-label bidx-entrepreneur">%role_entrepreneur%</span>
                                            <span class="label bidx-label bidx-mentor">%role_mentor%</span><i class="fa fa-mentor"></i>
                                            <span class="label bidx-label bidx-investor">%role_investor%</span><i class="fa fa-investor"></i>
                                        </div>
                                    </div>
                                </div>
                                <h4 class="view viewProfessionalTitle"><span class="bs-slogan">%professionalTitle%</span></h4>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <table class="table table-condensed table-bottom-border">
                                            <tbody>
                                                <tr class="view viewMotherTongue"><td><?php _e('Mothertongue', 'bidxplugin');?></td><td>%mothertongue%</td></tr>
                                                <tr class="view viewLangauge"><td><?php _e('Languages spoken', 'bidxplugin');?></td><td>%language%</td></tr>
                                                <tr class="view viewHighestEducation"><td><?php _e('Highest education', 'bidxplugin');?></td><td>%highestEducation%</td></tr>
                                                <tr class="view viewCountry"><td><?php _e('Place', 'bidxplugin');?></td><td>%city%%country%</td></tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="cardFooter">

                </div>
            </div>
            -->
        </script>


        <!-- 2. Company Snippet -->
        <script type="text/html" id="company-listitem">
             <!--
            <li class="media well">

            <div class="row">
                <div class="col-sm-3">
                    <a class="pull-left" href="<?php echo _l('company');?>/%entityId%" data-role='companyImage'>
                        <div class="icons-rounded pull-left"><i class="fa fa-building text-primary-light"></i></div>
                    </a>
                </div>
                <div class="col-sm-9">
                    <div class="row">
                        <div class="col-sm-6">
                            <a href="<?php echo _l('businesssummary');?>/%entityId%">
                                <h4>%name%</h4>
                            </a>
                        </div>
                        <div class="col-sm-6">
                                <span class="label bidx-label bidx-mentor ">%registered%</span>
                        </div>
                    </div>
                    <div class="row view viewWebsite">
                        <div class="col-sm-12">
                            <div>%website%</div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12"> <hr> </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="view viewCityTown">
                                <label><?php _e('City','bidxplugin');?></label>
                                <div>%cityTown%</div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="view viewCountry">
                                <label><?php _e('Country','bidxplugin');?></label>
                                <div>%country%</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </li>
            -->
        </script>



        <!-- 4. Business group snippet -->
        <script type="text/html" id="group-listitem">
             <!--
            <li class="media well">

            <div class="row">
                <div class="col-sm-3">
                    <a class="pull-left" target="_blank" href="<?php echo $http.'%bidxWebsiteName%.'.DOMAIN_CURRENT_SITE;?>" data-role='groupImage'>
                        <div class="icons-rounded pull-left"><i class="fa fa-group text-primary-light"></i></div>
                    </a>
                </div>
                <div class="col-sm-9">
                    <div class="row">
                        <div class="col-sm-6">
                            <a href="<?php echo $http.'%bidxWebsiteName%.'.DOMAIN_CURRENT_SITE;?>">
                                <h4>%name%</h4>
                            </a>
                        </div>
                        <div class="col-sm-6">
                            <div "row view viewLastupdate pull-right">%bidxCreationDateTime%</div>
                        </div>
                    </div>
                    <div class="row view viewWebsite">
                        <div class="col-sm-12">
                            <div>%website%</div>
                        </div>
                    </div>
                    <div class="row view viewSummary">
                        <div class="col-sm-12">
                            <div>%summary%</div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12"> <hr> </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-sm-6 view viewFocusIndustry">
                            <label><?php _e('Focus industry','bidxplugin');?></label>
                            <div>%focusIndustry%</div>
                        </div>
                        <div class="col-sm-6 view viewFocusSocialImpact">
                            <label><?php _e('Focus social impact','bidxplugin');?></label>
                            <div>%focusSocialImpact%</div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6 view viewFocusEnvImpact">
                            <label><?php _e('Focus environmental impact','bidxplugin');?></label>
                            <div>%focusEnvImpact%</div>
                        </div>
                        <div class="col-sm-6 view viewFocusCountry">
                            <label><?php _e('Focus Country', 'bidxplugin');?></label>
                            <div>%focusCountry%</div>
                        </div>
                    </div>
                </div>
            </div>
            </li>
            -->
        </script>

        <!-- 5. Empy resultset Snippet -->
        <script type="text/html" id="search-empty">
            <!--
            <li class="media">
                <div class="pull-left check"></div>
                <div class="alert alert-warning">
                    <?php _e('No search results available','bidxplugin')?>
                </div>
            </li>
            -->
        </script>

        <!-- 6. Result not loaded through js Snippet -->
        <script type="text/html" id="error-listitem">
            <li class="media well">
                <div class="row">
                    <div class="col-sm-12">
                        <?php _e('Problem loading the result','bidxplugin'); ?>
                    </div>
                </div>
            </li>
         </script>
</div>
