<?php $http = (is_ssl()) ? 'https://':'http://'; ?>

<div id="searchHome">

    <div class="row">

         <section class="views">

            <div class="col-sm-8">
                <div class="searchcontrol bg-primary-darker">
                    <div class="search">
                        <form action="" class="searchform">
                            <div class="input-group">
                                <input type="text" class="form-control form-q" name="q" placeholder="<?php _e("Search","bidxplugin");?>" value="">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="submit">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </form>
                    </div>
                </div>

                <!-- ERROR -->
                <div class="view viewError alert alert-warning">
                    <p class="errorMsg"></p>
                </div>

            </div>

            <div class="col-sm-4">
                <div class="side-bar well sideBar main-facet">
                    <article class="viewFacet">
                        <div class="facet-reset hide">
                            <a data-filter="reset" class="filter btn btn-block btn-danger"><?php _e("Clear all filters", "bidxplugin");?></a>
                        </div>
                         <div class="facet-list">

                            <?php _e('Rendering facets...', 'bidxplugin');?>
                         </div>
                    </article>
                </div>
            </div>
            
        </section>

    </div>

</div>
