 <?php
 $numFound = 0;
 if ( property_exists( $this -> results, 'data' ) ) {
	 $docs = $this -> results -> data -> docs;
	 $numFound = $this -> results -> data -> numFound;
 }
 ?>
<div>
	<?php
		if ( property_exists( $this -> error ) ) { ?>
	<div class="row">
		<div class="search error">
			 <button type="button" class="close" data-dismiss="alert">&times;</button>
			 <h3>Error</h3>
			 <p><?php echo $this -> error ?></p>
		</div>
	</div>

<?		} else
			if ( $numFound < 1 ) { ?>
	<div class="row">
		<div class="search alert">
			 <button type="button" class="close" data-dismiss="alert">&times;</button>
			 <h3>No results</h3>
			 <p>Your query did not have any results. Please retry with a more specific search term</p>
		</div>
	</div>
		<?php } else { ?>
	<div class="row">
		<div class="col-sm-12"><h4>Search results (<?php echo $this -> results -> data -> numFound ?>)</h4></div>
	</div>

	<div class="row">
		<div class="col-sm-12">
		<table class="table table-striped">
			<tbody>
				<tr>
					<th>Type</th>
					<th>Image</th>
					<th>Description</th>
					<th></th>
				</tr>
	<?php foreach ( $docs as $doc )  {

		switch ($doc -> type) {

			case 'bidxMemberProfile':
				$fullname = $doc -> firstname_s . ' ' . $doc -> lastname_s;
		?>
			<tr>
				<td>
					<span class="label">Member</span>
				</td>
				<td>
					<a href="/member/<?php echo $doc -> userId ?>">
				<?php if (property_exists( $doc , 'profilepicturedoc_url' ) ) {
							?>
						<img src="<?php echo $doc -> profilepicturedoc_url ?>" height="75" width="75" class="logo img-rounded" alt="<?php echo $fullname ?>"/>
				<?php  } else { ?>
						<img data-src="holder.js/75x75/social/text:member" class="logo img-rounded" alt="<?php echo $fullname ?>"/>
				<?php  }?>
					</a>
				</td>
				<td>
					<p><?php echo $fullname ?></p>
					<?php echo $doc -> professionaltitle_t ?><br />
					<?php echo $doc -> countrylabel_s ?>
				</td>
				<td>
					<a href="/member/<?php echo $doc -> userId ?>">view</a>
				</td>
			</tr>
<?php
			break;

			case 'bidxCompanyProfile':
?>
			<tr>
				<td>
					<span class="label">Company</span>
				</td>
				<td>
					<a href="/company/<?php echo $doc -> companyId ?>">
				<?php if (property_exists( $doc , 'doc_url' ) ) {
							?>
						<img src="<?php echo $doc -> doc_url ?>" class="logo img-rounded" alt="<?php echo $fullname ?>"/>
				<?php  } else { ?>
						<img data-src="holder.js/75x75/social/text:member" class="logo img-rounded" alt="<?php echo $fullname ?>"/>
				<?php  }?>
					</a>
				</td>
				<td>
					<em><?php echo $doc -> id ?></em>
				</td>
				<td>
					<a href="#">view</a>
				</td>
			</tr>
<?php
			break;

			case 'bidxInvestorProfile':
				$fullname = $doc -> firstname_s . ' ' . $doc -> lastname_s;
?>
			<tr>
				<td>
					<span class="label">Investor</span>
				</td>
				<td>
					<!-- lookup the investor? -->
				</td>
				<td>
					<em><?php echo $fullname ?></em><br />
					<?php echo $doc -> summary_t ?><br />
					<?php echo $doc -> countrylabel_s ?>, <?php echo $doc -> city_s ?><br />

				</td>
				<td>
					<a href="/investor/<?php echo $doc -> userId ?>">view</a>
				</td>
			</tr>
<?php
			break;

			case 'bidxEntrepreneurProfile':
				$fullname = $doc -> firstname_s . ' ' . $doc -> lastname_s;
?>
			<tr>
				<td>
					<span class="label">Entrepreneur</span>
				</td>
				<td>
					<!-- standard entrepreneur profile label here -->
				</td>
				<td>
					<em><?php echo $fullname ?></em><br />
					<?php echo $doc -> professionaltitle_t ?><br />
					<?php echo $doc -> countrylabel_s ?>, <?php echo $doc -> city_s ?><br />

				</td>
				<td>
					<a href="/member/<?php echo $doc -> userId ?>?#showEntrepreneur">view</a>
				</td>
			</tr>
<?php
			break;

			case 'bidxBusinessSummary':
?>
			<tr>
				<td>
					<span class="label">Business</span>
				</td>
				<td>
					<!-- standard business summary label here -->
				</td>
				<td>
					<em><?php echo $doc -> name_s ?></em><br />
					<?php echo $doc -> slogan_s ?><br/>
					<?php echo $doc -> industrylabel_ss ?>, <?php echo $doc -> countrylabel_s ?><br />
				</td>
				<td>
					<a href="/business/<?php echo $doc -> userId ?>">view</a>
				</td>
			</tr>
<?php
			break;

			case 'bidxBusinessGroup':
				?>
			<tr>
				<td>
					<span class="label">Group</span>
				</td>
				<td>

				</td>
				<td>
					<em><?php echo $doc -> name_s ?></em><br />
					<?php echo $doc -> slogan_t ?><br/>
					<?php echo $doc -> grouptype_s ?><br />
				</td>
				<td>
					<a href="http://<?php echo $doc -> domain_s ?>.bidx.net">view</a>
				</td>
			</tr>
			<?php
						break;
		}
	} ?>
		</tbody>
	</table>
	<div class="row">
		<div class="col-sm-6">
<?php
	if ( isset( $this -> previousLink ) ) {
	?>
		<a href="?<?php echo $this -> previousLink ?>" class="btn btn-primary pull-left">
			<span class="fa fa-chevron-left"></span>
			 <?php echo _e('Previous', 'bidxplugin'); ?>
		</a>
	<?php
	} ?>
		</div>
		<div class="col-sm-6">
<?php if ( isset( $this -> nextLink ) ) {
	?>
		<a href="?<?php echo $this -> nextLink ?>" class="btn btn-primary pull-right">
			<?php echo _e('Next', 'bidxplugin'); ?>
			<span class="fa fa-chevron-right"></span>
		</a>
	<?php
	}
?>
		</div>
	</div>
	<div class="row">
		&nbsp;
	</div>
</div>

<?php } ?>
</div>



