<!-- 
	Original page, should be standard if logged in
 -->
 <?php 
 $numFound = 0;
 if ( property_exists( $this -> results, 'data' ) ) {
	 $docs = $this -> results -> data -> docs;
	 $numFound = $this -> results -> data -> numFound;
 }
 ?>
<div>
	<?php 
		if ( property_exists( $this -> error ) ) { ?>
	<div class="row-fluid">
		<div class="search error">
			 <button type="button" class="close" data-dismiss="alert">&times;</button>
			 <h3>Error</h3>
			 <p><?php echo $this -> error ?></p>
		</div>
	</div>
<?		}

		if ( $numFound < 1 ) { ?>
	<div class="row-fluid">
		<div class="search alert">
			 <button type="button" class="close" data-dismiss="alert">&times;</button>
			 <h3>No results</h3>
			 <p>Your query did not have any results. Please retry with a more specific search term</p>
		</div>
	</div>	
	<?php } else { ?>
	<div class="row-fluid">
		<div class="span12"><h4>Search results (<?php echo $this -> results -> data -> numFound ?>)</h4></div>
	</div>
	
	<div class="row-fluid">
		<div class="span8">
		<table class="table table-striped">
			<tbody>
				<tr>
					<th>Type</th>
					<th>Description</th>
					<th></th>
				</tr>
	<?php foreach ( $docs as $doc )  { 
		
		switch ($doc -> type) {

			case 'bidxMemberProfile':
				$fullname = $doc -> firstname_s . ' ' . $doc -> lastname_s;
		?>
			<tr>
				<td>
					<span class="label">Member</span>
				</td>
				<td>
					<p><?php echo $fullname ?></p>
					<?php echo $doc -> professionaltitle_t ?><br />
					<?php echo $doc -> countrylabel_s ?>
				</td>
				<td>
					<a href="/member/<?php echo $doc -> userId ?>">view</a>
				</td>
			</tr>								
<?php	
			break;
			
			case 'bidxCompanyProfile':
?>
			<tr>
				<td>
					<span class="label">Company</span>
				</td>
				<td>
					<em><?php echo $doc -> id ?></em>		
				</td>
				<td>
					<a href="#">view</a>
				</td>
			</tr>
<?php 				
			break;

			case 'bidxInvestorProfile':
				$fullname = $doc -> firstname_s . ' ' . $doc -> lastname_s;
?>
			<tr>
				<td>
					<span class="label">Investor</span>
				</td>
				<td>
					<em><?php echo $fullname ?></em><br />
					<?php echo $doc -> summary_t ?><br />
					<?php echo $doc -> countrylabel_s ?>, <?php echo $doc -> city_s ?><br />
					
				</td>
				<td>
					<a href="/investor/<?php echo $doc -> userId ?>">view</a>
				</td>
			</tr>
<?php 				
			break;			

			case 'bidxEntrepreneurProfile':
				$fullname = $doc -> firstname_s . ' ' . $doc -> lastname_s;
?>
			<tr>
				<td>
					<span class="label">Entrepreneur</span>
				</td>
				<td>
					<em><?php echo $fullname ?></em><br />
					<?php echo $doc -> professionaltitle_t ?><br />
					<?php echo $doc -> countrylabel_s ?>, <?php echo $doc -> city_s ?><br />							
					
				</td>
				<td>
					<a href="/member/<?php echo $doc -> userId ?>?#showEntrepreneur">view</a>
				</td>
			</tr>
<?php 				
			break;
			
			case 'bidxBusinessSummary':
?>
			<tr>
				<td>
					<span class="label">Business</span>
				</td>
				<td>
					<em><?php echo $doc -> name_s ?></em><br />
					<?php echo $doc -> slogan_s ?><br/>
					<?php echo $doc -> industrylabel_ss ?>, <?php echo $doc -> countrylabel_s ?><br />
				</td>
				<td>
					<a href="/business/<?php echo $doc -> userId ?>">view</a>
				</td>
			</tr>
<?php 				
			break;	

			case 'bidxBusinessGroup':
				?>
						<tr>
							<td>
								<span class="label">Group</span>
							</td>
							<td>
								<em><?php echo $doc -> name_s ?></em><br />
								<?php echo $doc -> slogan_t ?><br/>
								<?php echo $doc -> focusindustrylabel_ss ?>, <?php echo $doc -> countrylabel_s ?><br />
							</td>
							<td>
								<a href="http://<?php $doc -> domain_s ?>.bidx.net">view</a>
							</td>
						</tr>
			<?php 				
						break;			
		} 
	} ?>
		</tbody>
	</table>
	<div class="row-fluid">
		<div class="span6">					
<?php 
	if ( isset( $this -> previousLink ) ) { 
	?>
		<a href="?<?php echo $this -> previousLink ?>" class="btn btn-block btn-primary fui-arrow-left">Previous
			<i class="fui-arrow-left pull-left"></i>
		</a>
	<?php
	} ?>
		</div>
		<div class="span6">	
<?php if ( isset( $this -> nextLink ) ) { 
	?>
		<a href="?<?php echo $this -> nextLink ?>" class="btn btn-block btn-primary">Next
			<i class="fui-arrow-right pull-right"></i>
		</a>
	<?php	
	}	
?>	
		</div>
	</div>	
	<div class="row-fluid">
		&nbsp;
	</div>				
</div>

	
		<div class="sidebar span4">
			<div>
				<!-- Navbar items -->
			</div>
			<div>
			<ul class="nav nav-list">			
	            <!--  
	            <li class="nav-header">Find by location</li>
	            <li>
	               	    Location position search here          
	            </li>
	            -->	 	            
				<li class="divider"></li>				
	            <li class="nav-header">Find By Type</li>
	            <li class="active">
	                All
	                <span class="nav-counter"><?php echo $this -> results -> data -> numFound ?></span>
	            </li>
	            <li	>
	            	Members Only
	            </li>
	            <li>
	                Entrepreneurs
	            </li>
	            <li>
	                Investors
	            </li>
	            <li>
	                Businesses
	            </li>
	            <li>
	                Groups
	            </li>	            	            
	            <li class="divider"></li>
	            <li class="nav-header">Filters</li>
	            <li>
	                <label>Language</label>
          			<input name="tagsinput" class="tagsinput tagsinput-primary" value="" id="tags_industry" style="display: none;">
          			<div id="tags_industry_tagsinput" class="tagsinput tagsinput-primary small" style="height: 100%;">
          				<div class="tagsinput-add-container" id="tags_industry_addTag">
          					<div class="tagsinput-add"></div>
          					<input id="tags_industry_tag small" value="" data-default="" style="color: rgb(102, 102, 102); width: 12px;">
          				</div>
          			</div>	                
	            </li>
	            <li>
	                <label>Industry</label>
          			<input name="tagsinput" class="tagsinput tagsinput-primary" value="" id="tags_theme" style="display: none;">
          			<div id="tags_theme_tagsinput" class="tagsinput tagsinput-primary small" style="height: 100%;">
          				<div class="tagsinput-add-container" id="tags_theme_addTag">
          					<div class="tagsinput-add"></div>
          					<input id="tags_theme_tag" value="" data-default="" style="color: rgb(102, 102, 102); width: 12px;">
          				</div>
          			</div>	                
	            </li>
	            <!--  
	            <li class="divider"></li>
	            <li class="nav-header">Find in</li>
	            <li>
	               	    Radio control here            
	            </li>
	            -->	            
	          </ul>
			</div>
		</div>
	</div>
<?php } ?>	
</div>
		

	