<div class="row counterWrapper main-padding">
	<div class="col-sm-4">
		<i class="fa fa-user fa-4x"></i><strong data-type="members" class="counterTxt" data-to='4122' data-easing='Members'>0</strong>
	</div>
	<div class="col-sm-4">
		<i class="fa fa-suitcase fa-4x"></i><strong data-type="plans" class="counterTxt" data-to='1233' data-easing='Business plans'>0</strong>
	</div>
	<div class="col-sm-4">
		<i class="fa fa-graduation-cap fa-4x"></i><strong data-type="mentors" class="counterTxt" data-to='342' data-easing='Mentors'>0</strong>
	</div>
</div>