<?php
$view = new TemplateLibrary( BIDX_PLUGIN_DIR . '/../admin/'.$this->className.'/static/templates/' );
$screen = get_current_screen();
$columns = absint( $screen->get_columns() );
$columns_css = '';
if ( $columns ) {
	$columns_css = " columns-$columns";
}

echo delete_user_option( $this->userId, "meta-box-order_".$screen->id, true );

?>
<div class="wrap <?php echo $this->className;?>">

	<?php screen_icon(); ?>

	<h2 class="admintitle"> <?php echo esc_html($this->title);?> </h2>

	<div id="message" class="updated below-h2 view viewMessage" style="display:none;">

	</div>

	<form name="my_form" method="post">
		<input type="hidden" name="action" value="some-action">
		<?php wp_nonce_field( 'some-action-nonce' ); ?>

		<div id="poststuff">

			<div id="post-body" class="metabox-holder<?php echo $columns_css; ?>">
				<?php echo $view->render( $this->className.'.phtml' ); ?>
			</div>
		</div> <!-- #poststuff -->

	</form>
</div><!-- .wrap -->

<?php
	/* Used to save closed metaboxes and their order */
	wp_nonce_field( 'meta-box-order', 'meta-box-order-nonce', false );
	wp_nonce_field( 'closedpostboxes', 'closedpostboxesnonce', false );
?>