<div id="account" class="block-odd mainState mainStateAccount top-margin-lineheight">
    <!-- mail stage: this is the ajax target -->
    <section>

        <!-- ************************* utility views *********************************** -->
        <article class="view viewLoad"><?php _e('Loading...','bidxplugin')?>
        </article>

        <article class="view viewError alert alert-warning">
            <h1><?php _e('Error','bidxplugin')?></h1>
            <div class="errorMsg"></div>
            <p>
                <a href="/account">Try again</a>
            </p>
        </article>

        <article class="view viewCredentials">

            <div class="row">
                <div class="col-sm-6 col-sm-offset-3 well">
                    <form id="frmCredentials" action="/">
                        <h1><?php _e('Account settings','bidxplugin');?></h1>
                        <h3><?php _e('Change your password', 'bidxplugin')?></h3>
                        <p>
                            <?php _e('Here you can change your password.', 'bidxplugin')?>
                        </p>

                        <div class="form-group">
                            <label><?php _e('Current password','bidxplugin');?></label>
                            <input type="password" class="form-control" name="currentPassword" placeholder="<?php _e('Enter your current password','bidxplugin');?>" />
                        </div>

                        <div class="form-group">
                            <label><?php _e('New password','bidxplugin');?></label>
                            <input type="password" class="form-control" name="newPassword" placeholder="<?php _e('Enter your new password','bidxplugin');?>" />
                        </div>

                        <div class="form-group">
                            <label><?php _e('Repeat new password','bidxplugin');?></label>
                            <input type="password" class="form-control" name="newPasswordRepeat" placeholder="<?php _e('Repeat your new password','bidxplugin');?>" />
                        </div>

                        <button type="submit" class="btn btn-primary"><span class="fa fa-refresh"></span> <?php _e('Update','bidxplugin');?></button>

                    </form>

                    <div class="accountChangeSuccess hide">
                        <h3><?php _e('Account change complete','bidxplugin');?></h3>
                        <p><?php _e('The registration is complete. An email has been sent to your email address with follow-up instructions','bidxplugin');?></p>
                    </div>
                </div>
            </div>

        </article>

        <article class="view viewCredentialsChanged">

            <div class="row">
                <div class="col-sm-6 col-sm-offset-3">

                    <h1><?php _e('Account settings','bidxplugin');?></h1>

                    <p>
                        <?php _e('Your password has been succesfully changed', 'bidxplugin')?>
                    </p>


                    <div class="accountChangeSuccess hide">
                        <h3><?php _e('Account change complete','bidxplugin');?></h3>
                        <p><?php _e('The registration is complete. An email has been sent to your email address with follow-up instructions','bidxplugin');?></p>
                    </div>
                </div>
            </div>

        </article>

</div>


