<div id="account" class="block-odd mainState mainStateAccount">
    <!-- mail stage: this is the ajax target -->
    <section>

        <!-- ************************* utility views *********************************** -->
        <article class="view viewLoad"><?php _e('Loading...','bidxplugin')?>
        </article>

        <article class="view viewError">
            <h1><?php _e('Error','bidxplugin')?></h1>
            <div class="errorMsg"></div>
            <p>
                <a href="/account">Try agian</a>
            </p>
        </article>

        <article class="view viewCredentials">

            <div class="row-fluid">
                <div class="span6 offset3 bidx-well bidx-theme-colour-panel-one">
                    <form id="frmCredentials" action="/">
                        <h1><?php _e('Account settings','bidxplugin');?></h1>
                        <h3><?php _e('Change your password', 'bidxplugin')?></h3>
                        <p>
                            <?php _e('Here you can change your log in credentials. Please note that if you change your email address, all notifications from the bidX platform or from groups that you are a member of will be forwarded to the new email address.', 'bidxplugin')?>
                        </p>
                        <div class="row-fluid">
                            <div class="span12">
                                <div class="control-group">
                                    <label class="control-label"><?php _e('Current password','bidxplugin');?></label>
                                    <div class="controls">
                                        <input type="password" name="currentPassword" placeholder="<?php _e('Enter your current password','bidxplugin');?>" />
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row-fluid">
                            <div class="span12">
                                <div class="control-group">
                                    <label class="control-label"><?php _e('New password','bidxplugin');?></label>
                                    <div class="controls">
                                        <input type="password" name="newPassword" placeholder="<?php _e('Enter your new password','bidxplugin');?>" />
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row-fluid">
                            <div class="span12">
                                <div class="control-group">
                                    <label class="control-label"><?php _e('Repeat new password','bidxplugin');?></label>
                                    <div class="controls">
                                        <input type="password" name="newPasswordRepeat" placeholder="<?php _e('Repeat your new password','bidxplugin');?>" />
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="buttonwrapper">
                            <button type="submit" class="btn btn-primary bidx-theme-colour-one"><?php _e('Update','bidxplugin');?></button>
                        </div>

                    </form>

                    <div class="accountChangeSuccess hide">
                        <h3><?php _e('Account change complete','bidxplugin');?></h3>
                        <p><?php _e('The registration is complete. An email has been sent to your email address with follow-up instructions','bidxplugin');?></p>
                    </div>
                </div>
            </div>

        </article>

        <article class="view viewCredentialsChanged">

            <div class="row-fluid">
                <div class="span6 offset3 bidx-well bidx-theme-colour-panel-one">

                    <h1><?php _e('Account settings','bidxplugin');?></h1>

                    <p>
                        <?php _e('Your password has been succesfully changed', 'bidxplugin')?>
                    </p>


                    <div class="accountChangeSuccess hide">
                        <h3><?php _e('Account change complete','bidxplugin');?></h3>
                        <p><?php _e('The registration is complete. An email has been sent to your email address with follow-up instructions','bidxplugin');?></p>
                    </div>
                </div>
            </div>

        </article>

</div>

